### ISSUE TITLE
No control over Media thumbnail size

### ISSUE THREAD

**Issue by ridhwaans** [reactstrap/reactstrap#1000]
I'm using `"reactstrap": "^5.0.0-beta.3"` and https://reactstrap.github.io/components/media/.

I have a Media object in my render()
```
let imgStyle = {
  minHeight: '128px',
  minWidth: '128px'
}
...
<Media>
  <Media left>
    <Media style={imgStyle} object src={'https://image.tmdb.org/t/p/w500' + data.season.episodes[i].still_path} />
  </Media>
  <Media body middle>
    <Media heading>
      {data.season.episodes[i].name}&emsp;
      <Badge color="primary">{'Episode ' + data.season.episodes[i].episode_number}</Badge>
    </Media>
    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
  </Media>
</Media>
```  
<img width="1657" alt="github issue" src="https://user-images.githubusercontent.com/1103336/39593271-4c45e690-4ed7-11e8-85c7-1bff17ab62f6.png">

The image style is not working as expected. I want the image on the left is full sized but I want it to appear as a thumbnail and positioned beside the heading and body, like an item from a vertical playlist (i.e. youtube 'up next' )

**Comment by TheSharpieOne** [comment]
Here is your code minus the variables: https://stackblitz.com/edit/reactstrap-v6-cahuzf?file=Example.js
Here is how it looks:
![image](https://user-images.githubusercontent.com/664714/39595711-3f4b813c-4ede-11e8-9336-7a323f2e5cdb.png)
You'll need some of the spacing utility classes to add some space between the image and the content, but overall the image size looks right.

**Comment by ridhwaans** [comment]
thanks
