### ISSUE TITLE
Codepen linked in the issue template does not work

### ISSUE THREAD

**Issue by apaatsio** [reactstrap/reactstrap#1003]
### Issue description

`ISSUE_TEMPLATE.md` has a link to https://codepen.io/TheSharpieOne/pen/GMMPEZ but that pen does not work.

### What is happening?

Codepen does not render anything because loading Reactstrap fails.

### What should be happening?

Codepen should render some stuff.

### Steps to reproduce issue

1. Go to https://codepen.io/TheSharpieOne/pen/GMMPEZ
2. Observe the output panel

### Error message in console

Chrome Version 68.0.3409.2 (Official Build) dev (64-bit)

```
reactstrap.full.min.js:1 Failed to load resource: the server responded with a status of 404 ()
index.html:1 Refused to execute script from 'https://unpkg.com/reactstrap@next/dist/reactstrap.full.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
pen.js:38 Uncaught ReferenceError: Reactstrap is not defined
    at pen.js:38
```

**Comment by TheSharpieOne** [comment]
fixed in bfb8cc5
