### ISSUE TITLE
Tooltip not closing on mobile

### ISSUE THREAD

**Issue by ntucakovic** [reactstrap/reactstrap#1004]
### Issue description
Tooltip can't close on mobile devices when opened on hover event.

- components: `Tooltip` (probably Popover as well, haven't tried)
- reactstrap version `#5.0.0` also on `#6.0.1`
- import method `es`
- react version `#16.3.1`
- bootstrap version `#4.0.0`

### What is happening?

Compare the behavior between the two on mobile (bugs on both Android and iOS).
Reactstrap: Tooltip is opened on hover event and you can't close it.
Bootstrap: Tooltip is opened on click only and can be closed when clicked away.

https://reactstrap.github.io/components/tooltips/
https://getbootstrap.com/docs/4.1/components/tooltips/

### What should be happening?

Tooltip should close when clicking away, anywhere on the page.

**Comment by ntucakovic** [comment]
This is also happening on latest Reactstrap version, v6.0.1. Updated issue to reflect that.

**Comment by Kofaka** [comment]
Have the same thing.

**Comment by olefrank** [comment]
Anyone found a solution to this?

**Comment by nathanbacon** [comment]
Just submitted a PR #1083 that fixes this.

**Comment by ntucakovic** [comment]
Any update on when this will be released? I got an email that it's merged :)

**Comment by mounlion** [comment]
Thanks you!
