### ISSUE TITLE
can't ref in <Input></Input>

### ISSUE THREAD

**Issue by NoMoreViolence** [reactstrap/reactstrap#1006]
### Issue description

- components: `Input`
- reactstrap version `#6.0.1`
- import method `umd/csj/es` 
- react version `#16.3.2`
- bootstrap version `#4.1.1`

### What is happening?

I just put ref on Input tag but, I can't I use typescript, so I used any type, but doesn't work

### What should be happening?
can use ref in <Input></Input>

### Steps to reproduce issue

1. ... Declare variables     ex) public password: any = null
2. ... link ref  in <Input ref  => { this.password = ref /> 
3. ... do it! this.password.focus()
4. ... Error!

### Error message in console
```
TypeError: _this.password.focus is not a function
```

### Code

 
```typescript

class Login extends React.Component {
public password: any = null

someMethod = () => {
     this.password.focus()
}

render() {
    return (
                <Input
                  type="password"
                  placeholder="Password Here"
                  ref={ref => {
                    this.password = ref
                  }}
                />
                <button onClick={this.someMethod}> Click me! </button>
      )
   }
}

```

**Comment by TheSharpieOne** [comment]
`ref` can only get a reference to the thing you use it on, `Input`. Use `innerRef` to get a reference to the underlying input.

**Comment by NoMoreViolence** [comment]
Thank You!

**Comment by amitKumar56** [comment]
> `ref` can only get a reference to the thing you use it on, `Input`. Use `innerRef` to get a reference to the underlying input.

Thanks man,you save my day
