### ISSUE TITLE
Read all Input values on form submit? 

### ISSUE THREAD

**Issue by elissaioskon** [reactstrap/reactstrap#1008]
- reactstrap version `5.0.0`
```
       onFormSubmit = ()=>{
     //I want to read input value here to do somevalidation an other stuff
}
 ```

```
  
                       <Form onSubmit={onFormSubmit}>
                       <FormGroup>
                            <Input type="email" name="email" placeholder="Email" />
                        </FormGroup>
       
                        <Button type="submit"  >Submit</Button>
                        </Form>
    ```
```

My real form have more inputs. How can i read all of them on submit?
i have tried innerRef but the function i  pass is executed many times.
At component Input  of reactbootstrap i find that innerRef  can be also a string, but how
i can access the string then?

**Comment by bestguy** [comment]
It sounds like this is a general React question, and not related to Reactstrap.
Your sample above is similar to how you'd do it in jQuery, etc but is not how you should approach it in React:

If you are trying to submit a Form via ajax, etc, you typically bind the values to a data object from the props or state, then the onSubmit just references that data, and doesn't try to 'read' the input values.   

Please see full example here:
https://stackblitz.com/edit/reactstrap-v5-beta-starter-y68hte?file=index.js

**Comment by elissaioskon** [comment]
Thanks for your answer. When i type something on an <Input> component of reactstrap the input updates and i was thinking that there is a state in <Input> component otherwise how it updates and maintain state the input field?This is the reason that i didnt created a new state.

**Comment by bestguy** [comment]
Yes, you are correct that there is internal state, but that's only useful if you want to do a traditional HTTP form post.  This React documentation explains in depth: https://reactjs.org/docs/forms.html

**Comment by TheSharpieOne** [comment]
Shameless plug: [Availity reactstrap validation](https://availity.github.io/availity-reactstrap-validation/)
Availity reactstrap validation gives easy to use validation and form submission, adding things like `onValidSubmit` and `onInvalidSubmit` as well as enhancing `onSubmit` to include the field values and information about which fields are invalid.
See https://availity.github.io/availity-reactstrap-validation/components/avform/ for details and examples

**Comment by elissaioskon** [comment]
I come back to this thread. if i dont use innerRef and have a contact form that keeps the state of all inputs and pass it as props to the reactstrap inputs component <Input value=this.props ... >.
Then if i write something to an input it lags.Thats because it rerender the whole form every time an input changes.
This is from react devtools when check highlight updates

![image](https://user-images.githubusercontent.com/26840252/41192567-68af764a-6c08-11e8-942a-4d853b3cad54.png)

**Comment by TheSharpieOne** [comment]
Yes, it will render the component in which the state changed, then react will diff it and only update the DOM if needed. If you are binding functions in your render, it will cause more overhead and more components to rerender as a new function will be created every render and be passed to the component which will determine that a prop has changed and cause that component to rerender.

If you can, please provide the code for your form.

**Comment by elissaioskon** [comment]
A bit late but i write what i had found that solve my above issue.
after removing all callbacks from inputs elements at onChange the form does not lag.
i change from this:     
onChange((e)=> this.handleChange(e, 'name'))
onChange((e)=> this.handleChange(e, 'lastname'))

to this:
onChange = (this.handleChange)

and this.handleChange is :
handleChange(e){
switch(e.target.name){
...save to state e.target.value
}
}

Thanks for all the answers above.

**Comment by key8297** [comment]
I am trying to achieve the same thing, so i found this post.
From last comment, I do this, which seems works well to me.
_at 2020, there is hook for react_


const [customer, setCustomer] = useState({});

const onChange = (e) => {
        let prop = {};
        prop[e.target.name] = e.target.value;
        let customer1 = Object.assign({}, customer, prop);
        setCustomer(customer1);
}

 <Input type="text" name="text1" placeholder="text1" onChange={onChange} />
 <Input type="text" name="text2" placeholder="text2" onChange={onChange} />

so customer will have prop text1, text2 with value.

Thanks.
