### ISSUE TITLE
CustomInput type="checkbox" color change ? 

### ISSUE THREAD

**Issue by dkati** [reactstrap/reactstrap#1010]
### Issue description

- components: `<CustomInput type="checkbox" />`
- reactstrap version `#6.0.1`
- import method `umd/csj/es` 
- react version `#16.3.2`
- bootstrap version `#4.1.1`

### What is happening?

i cant find a way to change that blue color

**Comment by TheSharpieOne** [comment]
AFAIK bootstrap doesn't provide any variants for them, they will default to that "primary" color and you can apply validation styles (via reactstrap `valid` and `invalid` props) to apply those styles/colors ("success" and "danger" respectively). Other than that, you would need to theme your bootstrap to change the colors that way; via css/scss.

**Comment by dkati** [comment]
@TheSharpieOne any code snippet ? i cant understand what do u mean

**Comment by TheSharpieOne** [comment]
Eh, I guess when they are checked, the color is always the same: https://stackblitz.com/edit/reactstrap-v6-vorhz4?file=Example.js
So the only why to change the color would be to change the CSS styles.

You may want to open an issue/feature request on bootstrap's repo asking bootstrap to add color variants to custom inputs (at least checkbox and radio)

**Comment by Husseinghrayeb** [comment]
check this link: https://stackoverflow.com/questions/48373119/change-bootstrap-4-checkbox-background-color.

**Comment by IgorBaio** [comment]
Use 

.custom-checkbox .custom-control-input:checked ~ .custom-control-label::after {
  background-color: $your_color !important
}

on main.scsss
