### ISSUE TITLE
9 Vulnerabilities found installing Bootstrap

### ISSUE THREAD

**Issue by Limoli** [reactstrap/reactstrap#1015]
### Issue description
After the execution of command `npm install --save bootstrap@4.1.1`, I got the following error:
```
+ bootstrap@4.1.1
added 202 packages from 89 contributors, removed 165 packages and updated 1139 packages in 67.33s
[!] 9 vulnerabilities found [30776 packages audited]
    Severity: 9 Low
    Run `npm audit` for more detail
```

### Steps to reproduce issue

1. Exactly the same steps of the tutorial.

### Error message in console

```
+ bootstrap@4.1.1
added 202 packages from 89 contributors, removed 165 packages and updated 1139 packages in 67.33s
[!] 9 vulnerabilities found [30776 packages audited]
    Severity: 9 Low
    Run `npm audit` for more detail
```

### Code

No custom code yet.

**Comment by TheSharpieOne** [comment]
I'm going to assume you meant install `reactstrap` and not `bootstrap`, but either way it is most likely one of the other packages you have installed since installing either of them and auditing results in no vulnerabilities found:

Here is reactstrap:

```bash
$ npm install --save reactstrap
npm WARN reactstrap@6.0.1 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN reactstrap@6.0.1 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-popper@0.10.4 requires a peer of react@0.14.x || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-popper@0.10.4 requires a peer of react-dom@0.14.x || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@2.3.1 requires a peer of react@>=15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@2.3.1 requires a peer of react-dom@>=15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ reactstrap@6.0.1
added 27 packages from 145 contributors in 14.92s
$ npm audit

                       === npm audit security report ===

[+] no known vulnerabilities found
    Packages audited: 72 (0 dev, 0 optional)
```

**Comment by Limoli** [comment]
Thank you for the response @TheSharpieOne !
I am going to install reactstrap of course, but I have just followed the "Getting started" section.
![screen shot 2018-05-11 at 09 16 03](https://user-images.githubusercontent.com/5011711/39911568-2fc023d4-54fc-11e8-8354-fb7af80c2a42.png)

**Comment by TheSharpieOne** [comment]
Ok, but still when I install bootstrap I don't have npm telling me it added 202 packages from 89 contributors (nor removing packages.... since, well there were none to begin with). It only claims to have added 27 packages from 145 contributors.
You may want to run `npm audit` to see which packages are the issue or open this issue with bootstrap itself if you believe they have vulnerabilities in their package. If you don't want to install bootstrap, you can always just reference the CSS direct via CDN: https://getbootstrap.com/docs/4.1/getting-started/introduction/#css

**Comment by Limoli** [comment]
I don't know exactly why you don't get these vulnerabilities.
I have simply installed what is requested:

**First step**
```
npm install -g create-react-app
create-react-app my-app
cd my-app/
npm start
```

**Second step**
```
npm install --save bootstrap@4.1.1
+ bootstrap@4.1.1
added 202 packages from 89 contributors, removed 165 packages and updated 1139 packages in 67.33s
[!] 9 vulnerabilities found [30776 packages audited]
    Severity: 9 Low
    Run `npm audit` for more detail
```

I didn't proceed with the other steps (reactstrap) as I get these vulnerabilities.

**Audit**
<img width="596" alt="screen shot 2018-05-11 at 21 09 29" src="https://user-images.githubusercontent.com/5011711/39942391-a3e09e2a-555f-11e8-96ec-4aec84154134.png">

**Comment by gergely-nagy** [comment]
These vulnerabilities come from `create-react-app`.
Please open a new issue with [CRA](https://github.com/facebook/create-react-app) itself!

**Comment by Limoli** [comment]
Yes, I have already seen and maybe migrating from NPM to Yarn seems the good fix for me.

**Comment by gergely-nagy** [comment]
Migrating from `npm` to `yarn` doesn't solve your issue !
`yarn` installs the same packages, but doesn't have the feature which log the vulnerabilities.
