### ISSUE TITLE
Modals, animation on-close does not always happen.

### ISSUE THREAD

**Issue by ghost** [reactstrap/reactstrap#1016]
Reactstrap **6.0.1**.

If I go here: https://reactstrap.github.io/components/modals/

and I try any modal I can see animation on open and on close.

If instead I try the modal in "Modals with Custom Transition Timeouts" section I can see the on-open animation, but not the on-close animation.

Is it a feature or a bug?

**Comment by TheSharpieOne** [comment]
That is a feature, but it's a bad example and really doesn't explain what it is doing. Looking at the code it sets the transition timeout to a very low number which basically causes it to not appear to transition.
