### ISSUE TITLE
Nav Dropdown Input Autofocus

### ISSUE THREAD

**Issue by mackbrowne** [reactstrap/reactstrap#1020]
### What is happening?

I'm trying to put an input box that will auto-focus inside of a dropdown nav item.  I've created an example below.

[This Example](https://stackblitz.com/edit/reactstrap-nav-dropdown-input?file=Example.js)

### What should be happening?

I'm trying to make the input box auto-focus when the dropdown is opened.  Either when clicked, or when the 'down' button is pressed on the keyboard when tabbing through nav items.

### Steps to reproduce issue

1. Click the "input" nav item or press down when using tab to navigate
2. see that the cursor is not focused.  I want it to focus.

**Comment by TheSharpieOne** [comment]
Just add `autoFocus` to the `Input`: https://stackblitz.com/edit/reactstrap-nav-dropdown-input-frao7p?file=Example.js

`autoFocus` is standard HTML and is not specific to reactstrap so it is not documented in reactstrap's documentation (similar to `onChange` or `onFocus` props).
