### ISSUE TITLE
It should be possible to change the trigger for UncontrolledTooltip

### ISSUE THREAD

**Issue by DiabolusExMachina** [reactstrap/reactstrap#1022]
### Issue description

- components: `UncontrolledTooltip`
- reactstrap version `6.0.1`
- react version `16.3.2`
- bootstrap version `^4.1.1`

### What is happening?

It is not possible to change the trigger of the UncontrolledTooltip. It is always **hover** 

### What should be happening?
It should be possible to change the trigger for UncontrolledTooltip like this

```
<UncontrolledTooltip trigger="focus" placement="right" target="id">
           Some Text
</UncontrolledTooltip>
```
Popper.js Supports this see here: https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/tooltip-documentation.md

**Comment by TheSharpieOne** [comment]
I have been wanting to better align tooltip and popover (as well as their uncontrolled counterparts). It seems like they do similar things in similar ways except the trigger is different... but the trigger, as this issue mentions, should be able to be changed. Technically, you could have a popover work on mouse events and a tooltip work on click events. The only real different between the two would be the default events it uses and the classNames which align with the bootstrap styles for each.
If anyone wants to take a stab at resolving this, please keep the above in mind and also address this similar concern with the popover component (maybe by creating a base component with all of the logic and having other components which implements the defaults for tooltip and popover.)

**Comment by illiteratewriter** [comment]
@TheSharpieOne  `react-popper` has an events prop. Wouldn't passing a prop to `react-popper` solve this?

**Comment by TheSharpieOne** [comment]
react-popper has [eventsEnabled](https://github.com/FezVrasta/react-popper#eventsenabled) which defaults to `true`. It controls [eventsEnabled from Popper.js](https://popper.js.org/popper-documentation.html#Popper.Defaults.eventsEnabled) which just determines if it should listen for resize and scroll events to update.

**Comment by illiteratewriter** [comment]
I'll give this a shot.

**Comment by illiteratewriter** [comment]
Will do for popover too...

**Comment by illiteratewriter** [comment]
@TheSharpieOne I want to build this like you said (**by creating a base component with all of the logic and having other components which implements the defaults for tooltip and popover.**), but I have never written tests, so when I write tests, should I write them for the base component or for the Tooltip component?
