### ISSUE TITLE
Can't resolve 'reactstrap' when using github master branch

### ISSUE THREAD

**Issue by buncismamen** [reactstrap/reactstrap#1032]
### Issue description

- components: `reactstrap`
- reactstrap version `#master`
- import method `umd/csj/es`
- react version `#16.3.2`
- bootstrap version `#4.1.1`

### What is happening?

Module not found: Can't resolve 'reactstrap'
when using github master branch

### What should be happening?

should not error just like the released version

### Steps to reproduce issue

1. create-react-app
2. yarn add https://github.com/reactstrap/reactstrap.git#master
3. call any component from reactstrap

### Error message in console

```
Failed to compile.

./src/App.js
Module not found: Can't resolve 'reactstrap' in '/home/user/reactstrapbeta/src'

```

**Comment by locpd** [comment]
If you add from github, you only have src files. You must "build" dist files from src files in order to use it.

**Comment by TheSharpieOne** [comment]
This is correct, reactstrap doesn't check in dist files. You can either build the dist or reference the /src/index directly and instruct your build/bundling tool to babel the contents of it (not 100% sure if that last thing will work, but it seems like it would based on how some other component libraries get away with not having a dist at all)

**Comment by Samiys** [comment]
npm install --save reactstrap react react-dom

**Comment by Nguyenau** [comment]
Thank  you, it helped me npm install --save reactstrap react react-dom
