### ISSUE TITLE
Feature request: Make ModalHeader Icon customizable

### ISSUE THREAD

**Issue by mxmzb** [reactstrap/reactstrap#1053]
### Issue description

- components: `ModalHeader`
- reactstrap version `#6.0.1`

### What is happening?

You can't change the close icon element.

### What should be happening?

**This is a feature request.** You should be able to pass a custom close icon element.

**Comment by illiteratewriter** [comment]
Icon should be an image right?

**Comment by TheSharpieOne** [comment]
currently it's a font icon

**Comment by illiteratewriter** [comment]
So for this, I'll do something like pass a font-icon as props?

**Comment by mxmzb** [comment]
i was imagining an arbitrary jsx element that you can pass. also, i'd love to contribute at this point and will take care of this myself (unless you already done with this of course) :) .

**Comment by illiteratewriter** [comment]
@mxmzb yeah sure, you can work on it. :)

**Comment by gergely-nagy** [comment]
Merged via (#1168) (5f33a1a) . Released in [6.5.0](https://github.com/reactstrap/reactstrap/compare/6.4.0...6.5.0)
