### ISSUE TITLE
Modal is not working

### ISSUE THREAD

**Issue by Nicholaz99** [reactstrap/reactstrap#1055]
### Issue description
I try to use Modal in reactstrap and its not working

### Error message in console

```
Uncaught TypeError: ReactDOM.createPortal is not a function
Unhandled promise rejection TypeError: ReactDOM.createPortal is not a function
```

### Code
`<div>`
`  <Modal isOpen={true}>`
 `   <ModalBody>`
 `     hai`
 `   </ModalBody>`
 ` </Modal>`
`</div>`

**Comment by TheSharpieOne** [comment]
Upgrade react to 16

**Comment by Nicholaz99** [comment]
@TheSharpieOne Thank you so much!!

**Comment by praWINK** [comment]
I am having react 16.5.2, reactDOM also the same version, but still got the same error

**Comment by TheSharpieOne** [comment]
If you are getting that `ReactDOM` doesn't have `createPortal` and you are 100% certain that you are using react-dom `16.5.2`, then you may want to file an issue with react itself since that function should be defined per their API docs.
