### ISSUE TITLE
'reactstrap' does not contain an export named 'UncontrolledCollapse'.

### ISSUE THREAD

**Issue by zxr90** [reactstrap/reactstrap#1057]
### Issue description
'reactstrap' does not contain an export named 'UncontrolledCollapse'.
- components: `UncontrolledCollapse`
- reactstrap version `#6.0.1`
- react version `#16.4.0`
- bootstrap version `#4.1.1`

### What is happening?

'reactstrap' does not contain an export named 'UncontrolledCollapse'.

### Steps to reproduce issue

1. .yarn add reactstrap
2. import UncontrolledCollapse

### Error message in console
'reactstrap' does not contain an export named 'UncontrolledCollapse'.
```
paste error message with stacktrack here
```

### From my yarn.lock

```
reactstrap@^6.0.1:
  version "6.0.1"
  resolved "https://registry.yarnpkg.com/reactstrap/-/reactstrap-6.0.1.tgz#944984ee8dc684c7dc09b8de9b722153a1ca7e95"
  dependencies:
    classnames "^2.2.3"
    lodash.isfunction "^3.0.9"
    lodash.isobject "^3.0.2"
    lodash.tonumber "^4.0.3"
    prop-types "^15.5.8"
    react-popper "^0.10.4"
    react-transition-group "^2.3.1"

bootstrap@4.1.1:
  version "4.1.1"
  resolved "https://registry.yarnpkg.com/bootstrap/-/bootstrap-4.1.1.tgz#3aec85000fa619085da8d2e4983dfd67cf2114cb"
```

**Comment by TheSharpieOne** [comment]
Can you try with 6.1.0?

**Comment by zxr90** [comment]
@TheSharpieOne Great! works with the new release.
