### ISSUE TITLE
Carousel: Option to disable autoPlay does not exist?

### ISSUE THREAD

**Issue by aliceathens** [reactstrap/reactstrap#1060]
In your doc's you state pass false to autoPlay prop but that doesn't exist in your list of props and the prop 'ride' does not accept 'false' please advise.. I can't have the carousel auto play.

**Comment by aliceathens** [comment]
My mistake its interval={false}

**Comment by avinashg-wal** [comment]
Thank you @aliceathens, that was helpful!

**Comment by ZebGirouard** [comment]
So just to clarify, these docs should definitely be fixed, too.

https://reactstrap.github.io/components/carousel/

The link above still says:

`Autoplay (ride="carousel") is enabled by default, you can disable it by passing false to the autoPlay prop.`

This is incorrect.  I just tried this today, and it does not work.  However, `interval={ false }` does work.

Luckily Google has this as a top result, and until the docs are fixed, I hope my little contribution helps, too.

**Comment by TheSharpieOne** [comment]
The extended quote from the "Uncontrolled Carousel" section of the docs is as follows:
> For the most basic use-case an uncontrolled component can provide the functionality wanted without the need to manage/control the state of the component. `UncontrolledCarousel` does not require `previous`, `next` nor `activeIndex` props to work. Anything provided to a normal `Carousel` can also be provided to `UncontrolledCarousel`, overriding the control `UncontrolledCarousel` provides. Additionally, you can hide the controls by passing `false` to the `controls` prop and you can disable the indicators by passing `false` to the `indicators` prop; both are visible by default. Autoplay (`ride="carousel"`) is enabled by default, you can disable it by passing `false` to the `autoPlay` prop.

Everything there is about `UncontrolledCarousel` not `Carousel`. They are two different components.

The `Carousel` props define:
```
  // Autoplays the carousel after the user manually cycles the first item. If "carousel", autoplays the carousel on load.
  // This is how bootstrap defines it... I would prefer a bool named autoplay or something...
  ride: PropTypes.oneOf(['carousel']),
  // the interval at which the carousel automatically cycles (default: 5000)
  interval: PropTypes.oneOfType([
    PropTypes.number,
    PropTypes.string,
    PropTypes.bool,
  ]),
```
It does mention that it works the way it works (why things are named the way they are named) because that is how bootstrap defined their API. reactstrap tries to match bootstrap's API as much as possible so that someone who knows bootstrap and use that knowledge with reactstrap.

I know the format of reactstrap's docs is not great / sucks and I am sorry. I would love to update them, but I barely have time to review PRs or even fix things within the codebase.

**Comment by ZebGirouard** [comment]
Thanks for responding @TheSharpieOne .  I feel the reactstrap docs are generally quite easy to follow, and small things like this are the exceptions that prove the rule.

I added a small explanatory comment in the docs in this PR: https://github.com/reactstrap/reactstrap/pull/1723

Feel free to reword if you want, but basically I just added what's in the bootstrap options link you referenced above.

**Comment by alfredrafael** [comment]
interval={false}

**Comment by azizurrahmaan** [comment]
Hello, I was trying to control the interval prop by the state of the element the that holds the carousel. But it seems like the interval prop is used only one time ( of initialization ), and does not affect the carousel to stop from sliding even when null is set to the interval prop afterwards. Can anybody help me how can I dynamically change the behavior (stop sliding / start sliding) of the carousel?

**Comment by alfredrafael** [comment]
Hey,

If you click here <https://june23.netlify.app/wedding-day> (a website I am
working on) you will notice this carousel has no automatic side-scrolling.
How did I do this? Here
<https://github.com/alfredrafael/boda/blob/master/src/components/WeddingDay/WeddingDay.js>
is my code for that component (at line # 91... the previous array is just
data with the pictures). This is an implementation of THIS
<https://reactstrap.github.io/components/carousel/#Uncontrolled-Carousel>
example from ReactStrap.

Let me know if this works for you

All the best,
*Alfredo R. Pabon* | *Software Developer*
(617) 580-1400 | afredrafael@gmail.com <alfredrafael@gmail.com>
*www.alfredorafael.com <http://www.alfredorafael.com>*

**Comment by erayarslan** [comment]
interval={null}

**Comment by firebird2552** [comment]
Today I tried these options after finding several other options. 
`data-interval="false" (did not work)`
when I added 
`interval={false} `
the carousel just ran faster on auto
when I added
`interval={null}` 
it stopped.

Actual site code
`return ( 
<Carousel className="h-100" interval={null}>
{images.map(image => {
return (
<Carousel.Item className="col-12">
<Card.Img variant='top' className="img-thumbnail project-image" src={image} />
</Carousel.Item>
)
})}
</Carousel >)`
