### ISSUE TITLE
Vertical nav tabs

### ISSUE THREAD

**Issue by digital-nomad17** [reactstrap/reactstrap#1065]
### Issue description

- components: `nav, tab`
- reactstrap version `#5.0.0`
- import method `umd/csj/es` 
- react version `#16.3.0`
- bootstrap version `#4.1`

### What is happening?

Is there a way to vertically arrange the nav for the tabs like in the [boostrap4 example](https://getbootstrap.com/docs/4.0/components/navs/)?

### Code

```
<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
  <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Home</a>
  <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Profile</a>
  <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Messages</a>
  <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">Settings</a>
</div>
<div class="tab-content" id="v-pills-tabContent">
  <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">...</div>
  <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">...</div>
  <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">...</div>
  <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">...</div>
</div>
```

**Comment by gergely-nagy** [comment]
Yes, of course!
The `Nav ` component has a `vertical `prop which is a boolean and controls the `flex-column` class.

Demo: https://stackblitz.com/edit/reactstrap-1065?file=Example.js

**Comment by TheSharpieOne** [comment]
I'm closing this since the the issue appears it was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Comment by eeriee** [comment]
The example is only for the nav panel, how to make the tab-content also vertical like https://www.npmjs.com/package/bootstrap-vertical-tabs?
