### ISSUE TITLE
shouldCloseOnOverlayClick not work

### ISSUE THREAD

**Issue by kduy969** [reactstrap/reactstrap#1084]
### Issue description

- components: `Modal`
- reactstrap version `#6.0.1`
- react version `#16.3.2`
- bootstrap version `#4.1.1`

I set shouldCloseOnOverlayClick = false on Modal props, expect toggle event will not fire when I click outside dialog, but it's still. Here's the code:

`<Modal shouldCloseOnOverlayClick={false}  isOpen={this.props.open} toggle={this.props.toggle} >{content}</Modal>`

**Comment by TheSharpieOne** [comment]
Not too sure where you got that prop from, but AFAIK that isn't a reactstrap prop.
Checkout the reactstrap docs: https://reactstrap.github.io/components/modals/ which tries to mimic [bootstrap's options](http://getbootstrap.com/docs/4.1/components/modal/#options) as much as possible. In this case, bootstrap has `backdrop`
> Includes a modal-backdrop element. Alternatively, specify static for a backdrop which doesn't close the modal on click.

reactstrap has a `backdrop` prop, which when set to `static` will act the same (backdrop which doesn't close the modal on click).

We can even test it out in the reactstrap docs.

**Comment by kduy969** [comment]
Thanks ! My bad, idk why webstorm suggest me this props when I type should... in <Modal> tag, so weird.

**Comment by TheSharpieOne** [comment]
It probably thinks you are using https://github.com/reactjs/react-modal/issues/149
