### ISSUE TITLE
Reactstrap carousel not showing the image, by entering the path from local disk in "src".

### ISSUE THREAD

**Issue by PujaSrivastava10** [reactstrap/reactstrap#1086]
Hello,
i'm trying to use reactstrap carousel in my app. The problem arrives when i'm trying to insert a picture in "src". I'm using **picture which is stored in the same folder** where my jsx file to create carousel is kept.  So, i'm using **src: 'image.jpg'** as my path but image is not showing in the browser. Whereas, it is working fine when, i'm using any link to display some image from internet.

Kindly help me to solve this issue.

**Comment by gergely-nagy** [comment]
I'm closing this because it's more of a general browser question than anything related to reactstrap.
Please check this out: https://www.w3schools.com/hTml/html_filepaths.asp
Hope this helps!

**Comment by PujaSrivastava10** [comment]
Hi @gergely-nagy,

1. I tried using import
2. I tried using require
3. I tried giving the path directly. Moreover, I may not know the actual path of the image, since these are getting built by webpack, even I have tried using `/static/media` in the relative path, but of no use.
```
import React , {Component} from 'react';
import { Carousel,
  UncontrolledCarousel,
  CarouselItem,
  CarouselControl,
  CarouselIndicators,
  CarouselCaption } from 'reactstrap';
  import himalaya from './images/himalaya.jpg';

 const items = [
  {
    src : {require('./images/beach.jpg')}, // even I tried using require, but no result
    altText: 'img can not be displayed',
    caption: '-Roxane Gay',
    header: '“Long walks on the beach are the supposed holy grail of a romantic evening. The beach becomes a kind of utopia - the place where all our dreams come true.”'
  },
  {
    src: {himalaya}, //by import, this is getting treated as a constant.
    altText: 'img can not be displayed',
    caption: '-Karen Blixen',
    header: '“You know you are truly alive when you’re living among lions.”'
  },
  {
    src:'./images/stream.jpg',
    altText: 'img can not be displayed',
    caption: '-Edmund Hillary',
    header: '“It is not the mountain we conquer but ourselves.”'
  }
];
```
Below is my folder structure:

![folder structure](https://user-images.githubusercontent.com/30182041/41921444-81591de2-7980-11e8-9349-8e2d5c830926.JPG)

Please let me know, where am I missing. It will be of great help.
Thanks

**Comment by ruk91** [comment]
Same issue here. @PujaSrivastava10  Did you find any solution?
