### ISSUE TITLE
DropdownToggle open on mouse hover

### ISSUE THREAD

**Issue by gaurav3017** [reactstrap/reactstrap#1088]
Is it possible to enable mouse hover event to DropdownToggle? Currently, it only supports onClick.

**Comment by TheSharpieOne** [comment]
You control when the menu opens and closes, the component doesn't control or support anything specifically. It only calls your toggle function and you determine if it does anything.
You can add `onMouseEnter` and `onMouseLeave` to the `Dropdown` and have it open and close the menu.
See: https://stackblitz.com/edit/reactstrap-v6-lgz4y2?file=Example.js

```jsx
import React from 'react';
import { Dropdown, DropdownToggle, DropdownMenu, DropdownItem } from 'reactstrap';

export default class Example extends React.Component {
  constructor(props) {
    super(props);

    this.toggle = this.toggle.bind(this);
    this.onMouseEnter = this.onMouseEnter.bind(this);
    this.onMouseLeave = this.onMouseLeave.bind(this);
    this.state = {
      dropdownOpen: false
    };
  }

  toggle() {
    this.setState(prevState => ({
      dropdownOpen: !prevState.dropdownOpen
    }));
  }

  onMouseEnter() {
    this.setState({dropdownOpen: true});
  }

  onMouseLeave() {
    this.setState({dropdownOpen: false});
  }

  render() {
    return (
      <Dropdown className="d-inline-block" onMouseOver={this.onMouseEnter} onMouseLeave={this.onMouseLeave} isOpen={this.state.dropdownOpen} toggle={this.toggle}>
        <DropdownToggle caret>
          Dropdown
        </DropdownToggle>
        <DropdownMenu>
          <DropdownItem header>Header</DropdownItem>
          <DropdownItem disabled>Action</DropdownItem>
          <DropdownItem>Another Action</DropdownItem>
          <DropdownItem divider />
          <DropdownItem>Another Action</DropdownItem>
        </DropdownMenu>
      </Dropdown>
    );
  }
}
```
![dropdown-mouse-toggle](https://user-images.githubusercontent.com/664714/41860559-f118a572-786c-11e8-9278-deb61070b935.gif)

**Comment by apwat56102** [comment]
and sub menu 
ro multi level menu

**Comment by jamesdamild** [comment]
hi there , how would you change the  onmouserover bakcground color for the dropdown items  please ??? am struggling with it

**Comment by TheSharpieOne** [comment]
@jamesdamild you can just use CSS and target the dropdown item class with `:hover`:
```css
.dropdown-item:hover {
  background-color: #ff0000;
}
```
demo: https://stackblitz.com/edit/reactstrap-v6-wqa3hd?file=style.css

**Comment by jamesdamild** [comment]
thanks a lot i figure it out earlier, thanks anyways :)

**Comment by Kyaw22Thet22Khai** [comment]
if dropdown button is too many, how I can separate items of dropdown menu. for Example, dropdownmenu1 for dropdown1 and dropdownmenu2 for dropdown2

**Comment by TheSharpieOne** [comment]
You can use multiple dropdowns, you just need to manage their state independent from one-another.

**Comment by Kyaw22Thet22Khai** [comment]
Thank you, but I want to use map function !!!

**Comment by darkyen** [comment]
With the react-hooks update you can also do, super tiny!

```
import React, { useState } from 'react';
import { Dropdown } from 'reactstrap';

export default function HoverControlledDropdown(props) {
  const [isOpen, updateIsOpen] = useState(false);

  return (
    <Dropdown
      {...props}
      onMouseOver={() => updateIsOpen(true)}
      onFocus={() => updateIsOpen(true)}
      onMouseLeave={() => updateIsOpen(false)}
      onBlur={() => updateIsOpen(false)}
      toggle={() => updateIsOpen(!isOpen)}
      isOpen={isOpen}
    />
  );
}
```

**Comment by MotorCityCobra** [comment]
@darkyen
Where is HoverControlledDropdown used?
You import it into App.js with that name?

**Comment by likitha2303** [comment]
I have created multiple dropdowns, when mouseover is placed on one dropdown, all menus of all dropdowns are getting displayed. pls help me with this.

**Comment by MotorCityCobra** [comment]
@likitha2303 
You just have to try every combination the drop down and the lists and/ or components can be combined. That's how I eventually got it to work.  
If you can't work the combinations out yourself just post your code on StackOverflow with one of your attempts to solve it and someone will post the correct configuration for you.

**Comment by zakaurehman** [comment]
how can I change dropdown button. Means color size ???

**Comment by bstiffler582** [comment]
Any idea how I can accomplish showing the drop down onFocus of an Input element? It seems the toggle functionality expects a click and any other events will get in the way - e.g. I can get it to pop up with the following:

`
const categoryDropDownToggle = () => setCategoryDropdownOpen(prevState => !prevState);
...
<Dropdown isOpen={categoryDropDownOpen} toggle={categoryDropDownToggle}>
                            <DropdownToggle tag="div" data-toggle="dropdown" aria-expanded={categoryDropDownOpen}>
                                <Input onFocus={() => { setCategoryDropdownOpen(true); }} />
                            </DropdownToggle>
                            <DropdownMenu>`

but then it is quickly hidden by the toggle.

**Comment by bstiffler582** [comment]
Any idea how I can accomplish showing the drop down onFocus of an Input element? It seems the toggle functionality expects a click and any other events will get in the way - e.g. I can get it to pop up with the following:

```
const toggle = () => setDropDownOpen(prevState => !prevState);

<Dropdown isOpen={dropDownOpen} toggle={toggle}>
   <DropdownToggle tag="div" data-toggle="dropdown" aria-expanded={dropDownOpen}>
      <Input onFocus={() => { setDropDownOpen(true); }} />
   </DropdownToggle>
<DropdownMenu>
```

but then it is quickly hidden by the toggle.

**Comment by mmAli-Akbaryan** [comment]
> With the react-hooks update you can also do, super tiny!
> 
> ```
> import React, { useState } from 'react';
> import { Dropdown } from 'reactstrap';
> 
> export default function HoverControlledDropdown(props) {
>   const [isOpen, updateIsOpen] = useState(false);
> 
>   return (
>     <Dropdown
>       {...props}
>       onMouseOver={() => updateIsOpen(true)}
>       onFocus={() => updateIsOpen(true)}
>       onMouseLeave={() => updateIsOpen(false)}
>       onBlur={() => updateIsOpen(false)}
>       toggle={() => updateIsOpen(!isOpen)}
>       isOpen={isOpen}
>     />
>   );
> }
> ```

what should be in props??
