### ISSUE TITLE
"Black flash" when open a modal without fade effect.

### ISSUE THREAD

**Issue by ghost** [reactstrap/reactstrap#1100]
If I go here: https://reactstrap.github.io/components/modals/

and I try "Modals without Fade Effect" I can see a "black flash" (maybe of backdrop element) on open and on close.

It is much more evident when it opens.

Is it a feature or a bug?

I can't slow down thing to understand better, but is really bad.

**Comment by andrewhamill** [comment]
I have the same question/issue. This can be reproduced on the reactstrap component page: https://reactstrap.github.io/components/modals/

under: Modals without Fade Effect

This appears to happen on Chrome and not on Firefox.

My personal opinion is this would be a better UI implementation without the "black flash".
