### ISSUE TITLE
Can we support text align prop on a Col?

### ISSUE THREAD

**Issue by smksnutmeg** [reactstrap/reactstrap#1109]
### Issue description

- components: `Col`

### What is happening?

We would like to control text-align on different sizes: xs, sm, md, lg

### What should be happening?

```
<Col xs={ align: 'center' } md={ align: 'right }
```

**Comment by TheSharpieOne** [comment]
Related: #959 #482 #81
The extra "utility" classes which are not specific to the layout components as they can be added to any component or element need to be manually added via `className`. For your case, this would be `className="text-center text-md-right"`
