### ISSUE TITLE
`UncontrolledCarousel` is not being exported

### ISSUE THREAD

**Issue by alamothe** [reactstrap/reactstrap#1111]
### `UncontrolledCarousel` is not being exported

- components: `UncontrolledCarousel`
- reactstrap version `#6.2.0`

Looking at the `index.js`, `UncontrolledCarousel` is not being exported at all. I am unable to import this component

**Comment by gergely-nagy** [comment]
The `index.js` file contains the `UncontrolledCarousel ` export.
https://github.com/reactstrap/reactstrap/blob/2d75db09c382124529c9b5c38e70b8791875ee5b/src/index.js#L126
Please make sure you've typed the component's name correctly!

Demo: https://stackblitz.com/edit/reactstrap-1111?file=Example.js

**Comment by alamothe** [comment]
My bad, I was thrown off because the list wasn't sorted...

The problem is actually with the TypeScript typings which lack `UncontrolledCarousel` so it can't be imported in TypeScript: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/reactstrap/index.d.ts

Should this be filed as an issue here or in DefinitelyTyped repository?

Thanks for the quick response!

**Comment by plat123456789** [comment]
sam problem here

**Comment by JProff** [comment]
UncontrolledCarousel missed too

**Comment by AkivaRanells** [comment]
"UncontrolledCarousel" is still not imported/exported in type definitions @types\reactstrap\index.d.ts
