### ISSUE TITLE
UncontrolledTooltips do not position correctly if the wrapper has an overflow: auto

### ISSUE THREAD

**Issue by Muntaner** [reactstrap/reactstrap#1118]
### Issue description

- components: `UncontrolledTooltip`
- reactstrap version `^6.1.0`
- react version `^16.4.0`
- bootstrap version `^4.1.1`

### What is happening?

The title says it all: UncontrolledTooltips do not position correctly if the wrapper has an overflow: auto.
After a lot of searching, [I landed on this popper.js issue](https://github.com/FezVrasta/popper.js/issues/648) which is exactly the problem I am reporting for Reactstrap.
### What should be happening?

UncontrolledTooltip should be placed correctly on the target DOM element.

### Steps to reproduce issue

1. Create a div and wrap it in another div with the CSS (or the React style) overflow: auto.
2. Create an UncontrolledTooltip and set as target this div.

### Error message in console
No error in console, just UX.

### Code
Check the following section.

### A solution I found
By looking at the issue [I pointed at previously](https://github.com/FezVrasta/popper.js/issues/648), seems like the problem is the following: 
> It's the correct behavior, the preventOverflow modifier uses by default, as boundariesElement, the scrollParent, you can change it to viewport or window or anything else supported.

So, I resolved the issue by adding the `modifiers` prop to the UncontrolledTooltip:

`
<UncontrolledTooltip modifiers={{preventOverflow: {boundariesElement: 'window'}}} autohide={false} delay={{ show: 200, hide: 5 }} placement='left' target={`${id}_${j}`}>
...
</UncontrolledTooltip>
`

**Comment by TheSharpieOne** [comment]
Looks like [bootstrap exposes an easy way to set the boundary](https://github.com/twbs/bootstrap/blob/abb48686267db3dadaa390e62538d23216c046d3/js/src/tooltip.js#L298-L300) (also [documented](http://getbootstrap.com/docs/4.1/components/tooltips/#options). We should probably expose a `boundary` prop which sets the `preventOverflow.boundariesElement` in the same way.

**Comment by pachuka** [comment]
@TheSharpieOne - I think the boundariesElement can also apply to the Dropdown/UncontrolledDropdown, should a new issue be created for that?

**Comment by tarik-besic** [comment]
Nice solution with the modifiers prop, works great now!
