### ISSUE TITLE
Add Toggle Switch Component

### ISSUE THREAD

**Issue by deveshjadon98** [reactstrap/reactstrap#1120]
### Create Toggle Switch Component

I am looking to create a toggle switch component and add it to reactstrap, Currently i have to use [Bootstrap Toggle](http://www.bootstraptoggle.com/) for the same, which is an added dependency.

Open to hear other's opinion about this.

**Comment by TheSharpieOne** [comment]
reactstrap is a react component library for bootstrap which allows users to use bootstrap in react without depending on jquery. The component you linked to is not part of bootstrap and thus not part of reactstrap.
If you like, you can create a react compatible component for Bootstrap Toggle and publish it separately.

**Comment by ItsOmiii2005** [comment]
You can use MdBoostrap switch component :)
