### ISSUE TITLE
CustomInput is disable!

### ISSUE THREAD

**Issue by RodruF** [reactstrap/reactstrap#1122]
Guys i have a problem , when i want import the class in my react app :
import { Alert, Form, FormGroup, Input, Row, Col, Card, CardBody, CardHeader, Label, Button, InputGroup, Modal, ModalHeader, ModalBody, CustomInput } from 'reactstrap';

Then appear a error in CustomInput that told me CustomInput is not a module of reacstrap.

what about this error? is normal or you can use this easily.
Can someone help me?

**Comment by TheSharpieOne** [comment]
Ensure you the latest version of reactstrap
