### ISSUE TITLE
change the Collapse tag prop

### ISSUE THREAD

**Issue by JustinMartinDev** [reactstrap/reactstrap#1135]
Hello i'm using your reactstrap library to create a collapse table with some row collapsed. 
My problem is that : 
When i use a the tag <UncontrolledCollapse> that create a `<div>` and i would like to have a <tr> with the same properties than the `<div>`. So i investigate in your library and i find it : 
 
"Collapase.js" : 
```jsx
const defaultProps = {
  ...Transition.defaultProps,
  isOpen: false,
  appear: false,
  enter: true,
  exit: true,
  tag: 'div',
  timeout: TransitionTimeouts.Collapse,
};
```

I forked the git and try to change the tag:'div' by tag:'tr' and that works well. But i want to know if we can change the props tag without change the library;

**Comment by TheSharpieOne** [comment]
those are the _default_ props, which mean if you do not provide a prop specified there, it will default to that value.
If you want to specify the `tag` to be a `tr`, just add `tag="tr"` to the `Collapse` and it will output a `tr` element.:

```jsx
<Collapse tag="tr" {/*...your other props here...*/}>
  {/* content here */}
</Collapse>
```

**Comment by JustinMartinDev** [comment]
Thx
