### ISSUE TITLE
Does Progress support custom color ?

### ISSUE THREAD

**Issue by kduy969** [reactstrap/reactstrap#1138]
I can't found any prop in Progress to set custom color, is this possible ?

**Comment by bencochrane1** [comment]
@kduy969 looks like it doesn't without setting CSS. I'm using styled components so it's not an option for me so I went for http://react-component.github.io/progress/ which has a nice set of props for customising color etc

**Comment by TheSharpieOne** [comment]
It only supports what bootstrap itself supports. You can extend bootstrap to add custom `bg-` variants and provide that variant as the `color` prop.

https://stackblitz.com/edit/reactstrap-v6-c9gasf?file=Example.js

![image](https://user-images.githubusercontent.com/664714/43092550-973f30e6-8e7b-11e8-9c4f-d2ba42acf61e.png)

**Comment by JonRider** [comment]
Took me forever to figure this out too. The trick is using **barClassName** to set the background-color prop. 

In React - 
```
<Progress
     className="my-2"
     barClassName="my-progress"
     striped
     value="25"
     >
     1/4
</Progress>
```

Your CSS -
```
.my-progress {
  background-color: var(--primary) !important;
}
```
