### ISSUE TITLE
Tooltip jumps to top of the page on iOS (Chrome and Safari)

### ISSUE THREAD

**Issue by poisa** [reactstrap/reactstrap#1144]
This can be reproduced by looking at the [docs](https://reactstrap.github.io/components/tooltips/) page from an iOS browser. The tooltip renders for a fraction of a second and the view jumps all the way to the top. Scrolling down shows that the tooltip has gone. 

Only way of showing the tooltip is by doing a soft tap-and-hold.

**Comment by poisa** [comment]
@TheSharpieOne Yeah, makes sense to just preventDefault() and be on with it. Thanks!

**Comment by TheSharpieOne** [comment]
whoops, need to keep this open to fix it on the docs

**Comment by gergely-nagy** [comment]
Closed with #1154
