### ISSUE TITLE
Highlighting the active dropdown item

### ISSUE THREAD

**Issue by gaurav3017** [reactstrap/reactstrap#1148]
```
<UncontrolledDropdown>
               <DropdownToggle nav caret>
                       <span>Availability</span>
                </DropdownToggle>
                <DropdownMenu>
                       <DropdownItem href="url">
                                 Backup
                       </DropdownItem>
                       <DropdownItem href="url">
                                 Restore
                       </DropdownItem>
                       <DropdownItem href="url">
                                  Share
                       </DropdownItem>
                </DropdownMenu>
 </UncontrolledDropdown>
```
How can I highlight the dropdown item which is selected? I tried adding `<NavLink activeClassName="active-item">Restore</NavLink>` inside `<DropdownItem>` but it doesn't work.

**Comment by gergely-nagy** [comment]
Add `active` prop to `DropdownItem` component to style them as active.
[Demo](https://stackblitz.com/edit/reactstrap-1148)

**Comment by gergely-nagy** [comment]
Yes, of course! This library adds the bootstrap classes which use CSS. You can override the SASS variables in bootstrap and create a custom style. In this situation, you should override the `dropdown-item active` class to provide a custom active dropdown style.
[Demo](https://stackblitz.com/edit/reactstrap-1148v2)

**Comment by gergely-nagy** [comment]
I am closing this issue as it appears to be resolved. If that is not correct, please feel free to comment and it will be reopened.
