### ISSUE TITLE
Tooltip timeout option

### ISSUE THREAD

**Issue by alisd23** [reactstrap/reactstrap#115]
The current **Tooltip** component has some fixed timeout which decides how long the tooltip remains visible after a mouseout event.

https://github.com/reactstrap/reactstrap/blob/master/src/Tooltip.jsx#L63

It would be nice to have the option of changing this via an option prop.

I think the usual use case (also the case for me) is not wanting any delay at all - i.e. timeout: 0.
Unless there is some specific reason why the fixed timeout exists?

**Comment by eddywashere** [comment]
Having a delay is great for giving users a chance to grab content within a tooltip. That may not be a requirement for everyone. +1 to having something like a `delay` prop that takes a string/number/object.  ex: `{ "show": 500, "hide": 100 }`.

**Comment by alisd23** [comment]
That sounds good, I'll try to get a PR in for this sometime this week, unless someone beats me to it :+1:

**Comment by alisd23** [comment]
@eddywashere just thinking about this again, is there ever a use case for needing a 'show' delay. I can't think of any situation where delaying the showing part would be useful, it would just make the UI seem unresponsive. Thoughts?

**Comment by TheSharpieOne** [comment]
Tooltip with a mouseover would benefit from the show delay. Imagine all of the time you roll over something (usually an ad, but still) and it pops up something... and all you were trying to do was go over it to get to something else, not trigger it. It's even more annoying when the tooltip which you did not intend to trigger covers the thing you were trying to get to.

**Comment by alisd23** [comment]
Yeah OK that's a valid point, I guess it's worth having the option then

**Comment by rlech** [comment]
delay not working for UncontrolledTooltip
