### ISSUE TITLE
CustomInput error

### ISSUE THREAD

**Issue by bp12345** [reactstrap/reactstrap#1152]
- components: `CustomInput`
- reactstrap version `^5.0.0`
- import method `import { Col, Button, Input, Form, FormGroup, Label, FormFeedback, Alert, CustomInput } from 'reactstrap'; 
- react version `^16.4.1`
- bootstrap version `^4.1.3`

### What is happening?
I've created a form using the ReactStrap `Input`, however, if I try change some of the `Input` to `CustomInput` the app crashes. Console reports: ` React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

If I change `CustomInput` to `Input` it works fine. I've tried using CustomInput before and had the same thing happen. Is this a bug?

```
<FormGroup>
  <Label for="exampleCheckbox">Checkboxes</Label>
  <div>
    <CustomInput type="checkbox" id="exampleCustomCheckbox" label="Check this custom checkbox" />
    <CustomInput type="checkbox" id="exampleCustomCheckbox2" label="Or this one" />
    <CustomInput type="checkbox" id="exampleCustomCheckbox3" label="But not this disabled one" disabled />
  </div>
</FormGroup>
```

**Comment by TheSharpieOne** [comment]
You need to upgrade reactstrap to `^6.0.0`

**Comment by bp12345** [comment]
OMG. Thanks. I'm new to programming. When I ran npm update reactstrap it seemed to be locked to 5.0.
So I removed it and then reinstalled it. As a result, it upgraded to the new version. 

Is this a common problem with NPM, not updating to correct versions, or am I suppose to update in a certain way. I realise this isn't specific to reactstrap, but I was hoping you could shed some light on the issue.

Thanks again.

**Comment by TheSharpieOne** [comment]
`^5.0.0` will tell npm to only upgrade it minor and patch versions **not** major version (to < 6). It's typically done this was as to avoid bringing in breaking changes indicated by a major version bump. If you want the latest version, you can use `*` as the version number, but if reactstrap publishes a new version with breaking changes, it may break your code.

You can use this tool: https://semver.npmjs.com/ to check what versions would be allowed given a package and a version string

**Comment by Zahirmasoodi** [comment]
https://reactstrap.github.io/?path=/docs/home-upgrading--page
