### ISSUE TITLE
Dropdown Select according keypress

### ISSUE THREAD

**Issue by Lug16** [reactstrap/reactstrap#1156]
Hi all,
I would like to know if there is any way to select an item in the Dropdown component according to a key pressed. Sorry if this is not the way to ask a question here.

**Comment by TheSharpieOne** [comment]
👋 Hi @Lug16! Do mean like a hotkey (pressing `3` would select the 3rd item) or typeahead (pressing `H` would select the item starting with "H")?

Either way is not supported as bootstrap itself doesn't have that feature. The only dropdown keyboard support is arrow keys (shifting which item is active) and enter/space (selecting the active item)

I wouldn't mind adding a feature like this as this sounds like it can help with accessibility.

**Comment by Lug16** [comment]
Hey @TheSharpieOne thanks for your response. Yeah, I meant (pressing `H` would select the item starting with "H")
It would be awesome to have something like that, I'm not a very experienced JS developer, but if you need my help, I will gladly help you.

Thanks

**Comment by Lug16** [comment]
Guys, I know that the thread is closed and the PR adding the functionality is merged, but just downloaded the latest version and I was not able to make it work. Here is a sandbox with the test that I did. https://codesandbox.io/s/qqq4q74o26 . Am I missing something?

**Comment by TheSharpieOne** [comment]
it hasn't been released yet. I'll try to cut a release some time today.

**Comment by bugovicsb** [comment]
Can this feature be switched off somehow? I would like to implement my own search functionality on keydown.
