### ISSUE TITLE
NavBar Component not Collapsing on GatsbyJS

### ISSUE THREAD

**Issue by InfraK** [reactstrap/reactstrap#1157]
- components: `NavBar`
- reactstrap version `#6.3.1`
- react version `#16.4.1`
- bootstrap version `#4.1.3`
-gatsby version `#1.9.277`

### What is happening?

The navBar collapse toggle is not changing according to state.

### What should be happening?

The navbar should collapse on 'isOpen' false;

### Code
Link to code
https://stackblitz.com/edit/reactstrap-yvgtag?file=NavBar.js

**Comment by ludwig-vaan** [comment]
NavBar Component not Collapsing on GatsbyJS

I have the same problem with :
-         "reactstrap": "^6.5.0",
-         "react": "^16.6.0",
-         "gatsby": "^2.0.40",
-         "bootstrap": "^4.1.3",

**What is happening?**
The navBar collapse toggle is not changing according to state.

**What should be happening?**
The navbar should collapse on 'isOpen' false;

**Steps to reproduce issue**
https://github.com/ludwig-vaan/osteopathie-animale-bordeaux
- `git clone`
- `yarn`
- `yarn build`
- `yarn serve`

this bug doen't appear in develop mode :
`yarn develop`

**Comment by Drakenwolf** [comment]
Any update or info about this issue? I am having a similar issue with the UncontrolledAccordion
