### ISSUE TITLE
Opening one collapse button, everything will open

### ISSUE THREAD

**Issue by dreeeyy** [reactstrap/reactstrap#1163]
- components: `name`
- reactstrap version `6.3.1`
- import method `umd/csj/es` 
- react version `16.4.1`
- bootstrap version `4.1.3`

### What is happening?

When I click just one button, the everything will open
when i click this..
![image](https://user-images.githubusercontent.com/31465727/43695694-c99b1374-996c-11e8-9530-f55ed8bb37be.png)

the rest will also open
![image](https://user-images.githubusercontent.com/31465727/43695718-ecf4778e-996c-11e8-8219-b9deb8dc6709.png)

### What should be happening?

I want them to individually work. 

### Code
class Dashboard extends Component {
constructor(props) {
    super(props);
    this.onEntering = this.onEntering.bind(this);
    this.onEntered = this.onEntered.bind(this);
    this.onExiting = this.onExiting.bind(this);
    this.onExited = this.onExited.bind(this);
    this.toggle = this.toggle.bind(this);
    this.toggleAccordion = this.toggleAccordion.bind(this);
    this.toggleCustom = this.toggleCustom.bind(this);
    this.toggleFade = this.toggleFade.bind(this);
    this.state = {
      collapse: false,
      accordion: [true, false, false],
      custom: [true, false],
      status: "Closed",
      fadeIn: true,
      timeout: 300
    };
  }

  onEntering() {
    this.setState({ status: "Opening..." });
  }

  onEntered() {
    this.setState({ status: "Opened" });
  }

  onExiting() {
    this.setState({ status: "Closing..." });
  }

  onExited() {
    this.setState({ status: "Closed" });
  }

  toggle() {
    this.setState({ collapse: !this.state.collapse });
  }

  toggleAccordion(tab) {
    const prevState = this.state.accordion;
    const state = prevState.map((x, index) => (tab === index ? !x : false));

    this.setState({
      accordion: state
    });
  }

  toggleCustom(tab) {
    const prevState = this.state.custom;
    const state = prevState.map((x, index) => (tab === index ? !x : false));

    this.setState({
      custom: state
    });
  }

  toggleFade() {
    this.setState({ fadeIn: !this.state.fadeIn });
  }

 <Col>
            <Card className="text-white bg-info">
              <CardHeader id="headingOne">
                <i className="fa fa-align-justify" /> Tier 1{" "}
              </CardHeader>
              <CardBody className="pb-0">
                <div id="accordion">
                  <Card>
                    <CardHeader id="headingOne">
                      <Button
                        block
                        color="link"
                        className="text-left m-0 p-0"
                        onClick={() => this.toggleAccordion(0)}
                        aria-expanded={this.state.accordion[0]}
                        aria-controls="collapseOne"
                      >
                        <h5 className="m-0 p-0">Task #1</h5>
                      </Button>
                    </CardHeader>
                    <Collapse
                      isOpen={this.state.accordion[0]}
                      data-parent="#accordion"
                      id="collapseOne"
                      aria-labelledby="headingOne"
                    >
                      <CardBody>
                        1. Anim pariatur cliche reprehenderit, enim eiusmod high
                        life accusamus terry richardson ad squid. 
                      </CardBody>
                    </Collapse>
                  </Card>
                  <Card>
                    <CardHeader id="headingTwo">
                      <Button
                        block
                        color="text-light bg-dark"
                        className="text-left m-0 p-0"
                        onClick={() => this.toggleAccordion(1)}
                        aria-expanded={this.state.accordion[1]}
                        aria-controls="collapseTwo"
                      >
                        <h5 className="m-0 p-0">Task #2</h5>
                      </Button>
                    </CardHeader>
                    <Collapse
                      isOpen={this.state.accordion[1]}
                      data-parent="#accordion"
                      id="collapseTwo"
                    >
                      <CardBody>
                        2. Anim pariatur cliche reprehenderit, enim eiusmod high
                        life accusamus terry richardson ad squid.
                      </CardBody>
                    </Collapse>
                  </Card>
                  <Card>
                    <CardHeader id="headingThree">
                      <Button
                        block
                        color="link"
                        className="text-left m-0 p-0"
                        onClick={() => this.toggleAccordion(2)}
                        aria-expanded={this.state.accordion[2]}
                        aria-controls="collapseThree"
                      >
                        <h5 className="m-0 p-0">Collapsible Group Item #3</h5>
                      </Button>
                    </CardHeader>
                    <Collapse
                      isOpen={this.state.accordion[2]}
                      data-parent="#accordion"
                      id="collapseThree"
                    >
                      <CardBody>
                        3. Anim pariatur cliche reprehenderit, enim eiusmod high
                        life accusamus terry richardson ad squid.
                      </CardBody>
                    </Collapse>
                  </Card>
                </div>
              </CardBody>
            </Card>
          </Col>

Thats just about it.. and i separated each of them by creating enclosing the same code with another <Col></Col>

**Comment by dreeeyy** [comment]
Here's my code:
 <Col>
            <Card className="text-white bg-info">
              <CardHeader id="headingOne">
                <i className="fa fa-align-justify" /> Tier 1{" "}
              </CardHeader>
              <CardBody className="pb-0">
                <div id="accordion">
                  <Card>
                    <CardHeader id="headingOne">
                      <Button
                        block
                        color="link"
                        className="text-left m-0 p-0"
                        onClick={() => this.toggleAccordion(0)}
                        aria-expanded={this.state.accordion[0]}
                        aria-controls="collapseOne"
                      >
                        <h5 className="m-0 p-0">Task #1</h5>
                      </Button>
                    </CardHeader>
                    <Collapse
                      isOpen={this.state.accordion[0]}
                      data-parent="#accordion"
                      id="collapseOne"
                      aria-labelledby="headingOne"
                    >
                      <CardBody>
                        1. Anim pariatur cliche reprehenderit, enim eiusmod high
                        life accusamus terry richardson ad squid. 
                      </CardBody>
                    </Collapse>
                  </Card>
                  <Card>
                    <CardHeader id="headingTwo">
                      <Button
                        block
                        color="text-light bg-dark"
                        className="text-left m-0 p-0"
                        onClick={() => this.toggleAccordion(1)}
                        aria-expanded={this.state.accordion[1]}
                        aria-controls="collapseTwo"
                      >
                        <h5 className="m-0 p-0">Task #2</h5>
                      </Button>
                    </CardHeader>
                    <Collapse
                      isOpen={this.state.accordion[1]}
                      data-parent="#accordion"
                      id="collapseTwo"
                    >
                      <CardBody>
                        2. Anim pariatur cliche reprehenderit, enim eiusmod high
                        life accusamus terry richardson ad squid.
                      </CardBody>
                    </Collapse>
                  </Card>
                  <Card>
                    <CardHeader id="headingThree">
                      <Button
                        block
                        color="link"
                        className="text-left m-0 p-0"
                        onClick={() => this.toggleAccordion(2)}
                        aria-expanded={this.state.accordion[2]}
                        aria-controls="collapseThree"
                      >
                        <h5 className="m-0 p-0">Collapsible Group Item #3</h5>
                      </Button>
                    </CardHeader>
                    <Collapse
                      isOpen={this.state.accordion[2]}
                      data-parent="#accordion"
                      id="collapseThree"
                    >
                      <CardBody>
                        3. Anim pariatur cliche reprehenderit, enim eiusmod high
                        life accusamus terry richardson ad squid.
                      </CardBody>
                    </Collapse>
                  </Card>
                </div>
              </CardBody>
            </Card>
          </Col>


and this..
class Dashboard extends Component{
constructor(props) {
    super(props);
    this.onEntering = this.onEntering.bind(this);
    this.onEntered = this.onEntered.bind(this);
    this.onExiting = this.onExiting.bind(this);
    this.onExited = this.onExited.bind(this);
    this.toggle = this.toggle.bind(this);
    this.toggleAccordion = this.toggleAccordion.bind(this);
    this.toggleCustom = this.toggleCustom.bind(this);
    this.toggleFade = this.toggleFade.bind(this);
    this.state = {
      collapse: false,
      accordion: [true, false, false],
      custom: [true, false],
      status: "Closed",
      fadeIn: true,
      timeout: 300
    };
  }

  onEntering() {
    this.setState({ status: "Opening..." });
  }

  onEntered() {
    this.setState({ status: "Opened" });
  }

  onExiting() {
    this.setState({ status: "Closing..." });
  }

  onExited() {
    this.setState({ status: "Closed" });
  }

  toggle() {
    this.setState({ collapse: !this.state.collapse });
  }

  toggleAccordion(tab) {
    const prevState = this.state.accordion;
    const state = prevState.map((x, index) => (tab === index ? !x : false));

    this.setState({
      accordion: state
    });
  }

  toggleCustom(tab) {
    const prevState = this.state.custom;
    const state = prevState.map((x, index) => (tab === index ? !x : false));

    this.setState({
      custom: state
    });
  }

  toggleFade() {
    this.setState({ fadeIn: !this.state.fadeIn });
  }

**Comment by arraqib** [comment]
Fixes #1163
