### ISSUE TITLE
Opening modal from outside of modalComponent

### ISSUE THREAD

**Issue by hilyin** [reactstrap/reactstrap#1164]
Hi,

I am attempting to use reactstrap modal where I programmatically open the modal, but I do not see anything in the docs explaining how to open the modal from a parent component. Any help is appreciated.

Thanks.

**Comment by virgofx** [comment]
The docs outline this pretty clearly. Modal visibility is controlled with the `isOpen` prop.

http://reactstrap.github.io/components/modals/

**Comment by hilyin** [comment]
Hey @virgofx , it does seem clear yes. But Here is an example of it not opening:
https://jsfiddle.net/n5u2wwjg/123932/

I'd really appreciate any ideas on why its not working.

**Comment by virgofx** [comment]
In your example, your toggle button was too small ... clicking it worked fine. You're initial state was also set to false ignoring the `isOpen`

Working example:

https://jsfiddle.net/qex0s4wd/

**Comment by hilyin** [comment]
@virgofx Thanks man, I appreciate your help. I have one more question, is it possible to re-open the modal from the parent component (without the toggle button) after closing it?

**Comment by virgofx** [comment]
I don't really understand .. Your parent component controls the state of the modal. So you can open it however/whenever --- the example uses a button.... this could change to a timer and open/close every 10 seconds .. or react to anything else in your application and then appropriate control the state of the **Modal** (`<Modal .../>`) via the `isOpen` property which is stored as **state** in your parent object.

**Comment by hilyin** [comment]
Thank you, I'll ask there.
