### ISSUE TITLE
Select Multiple Input to capture array of options

### ISSUE THREAD

**Issue by lausellduane** [reactstrap/reactstrap#1167]
Hi there,

I have a form which has 3 select multiple inputs among other inputs. I want to be able to select multiple values from the user and push them into an array. The issue I am having is that when I select the first option it drops its 'focus' ( I am not sure if that is the correct term for it) then I can't shift/cmd+click to select other options. 

![screen shot 2018-08-08 at 4 12 40 pm](https://user-images.githubusercontent.com/20842443/43861813-f161ff34-9b25-11e8-95cb-d7017d3d03d3.png)

This is what I want:

![screen shot 2018-08-08 at 4 03 00 pm](https://user-images.githubusercontent.com/20842443/43861367-9ad41400-9b24-11e8-86c6-0a59a1b429b5.png)

But, when i click 1 option it selects it and then drops it.

The code for the inputs:

`<FormGroup className="pr-1 mb-0">

                            <Label for="service_ids">Services:</Label>
                              <Input
                                    type="select"
                                    name="service_ids"
                                    ref="createService"
                                    id="service_ids"
                                    defaultValue=""
                                    value={this.state.incident.service_ids}
                                    onChange={(event) => {
                                        this.onChange(event);
                                        this.getSelectValues(event);
                                    }}
                                    required
                                    multiple
                              >
                                <option value="service1">service1</option>
                                <option value="service2">service2</option>
                                <option value="service3">service3</option>
                              </Input>
                          </FormGroup>`

onChange updates the state with the selections and getSelectValues function is supposed to push the selected options to an array.

`onChange(event) {
        this.setValid(event);
        let newState = {incident: this.state.incident};
        newState['incident'][event.target.name] = event.target.value;
        this.setState(newState);
        console.log(this.state);
    }

getSelectValues(event) {
        let opts = [], opt;
        
        for (let i = 0, len = event.target.options.length; i < len; i++) {
            opt = event.target.options[i];

            if (opt.selected) {
                opts.push(opt);
            }
        }
        console.log('opts: ', opts);
        return opts;
    }`

The JSON body with the formData for the post request: 

`let formData = JSON.stringify({

          id: eventID,
          name: ReactDOM.findDOMNode(this.refs.createName).value,
          status: ReactDOM.findDOMNode(this.refs.createStatus).value,
          server_ids: ReactDOM.findDOMNode(this.refs.createServer).value,
          customer_ids: ReactDOM.findDOMNode(this.refs.createCustomer).value,
          service_ids: ReactDOM.findDOMNode(this.refs.createService).value,
          downtime: ReactDOM.findDOMNode(this.refs.createDowntime).value,
          start_time: ReactDOM.findDOMNode(this.refs.createStartTime).value,
          created: createdDate
        });` 

 I am not sure If I need to make a modification to service_ids, customer_ids, server_ids in order to hold an array.

If anyone has come across a similar thing I would appreciate you to share how you implemented it.

Thanks in advance.

**Comment by TheSharpieOne** [comment]
I see you setting `newState['incident'][event.target.name] = event.target.value;` and not calling `getSelectValues`. `event.target.value` will be the last option selected and not the list of select options.

Also, I you should be pulling the `value` out of the selected options: `opts.push(opt);` -> `opts.push(opt.value);`

Check out this example: https://stackblitz.com/edit/reactstrap-v6-wwzerv?file=Example.js

**Comment by lausellduane** [comment]
Hi @TheSharpieOne  I updated getSelectValues with `opts.push(opt);` -> `opts.push(opt.value);` to get the value and it works as expected. 

`
getSelectValues(event) {
        let newState = { incident: this.state.incident };
        let opts = [], opt;

        for (let i = 0, len = event.target.options.length; i < len; i++) {
            opt = event.target.options[i];

            if (opt.selected) {
                opts.push(opt.value);
            }
        }
        newState['incident'][event.target.name] = opts;
        this.setState(newState);
    }

`

I still don't get what you meant by me setting `newState['incident'][event.target.name] = event.target.value;` and not the result in the second paragraph. Can you explain more about what needs to be changed in order to get the list of selected options. Currently it only gets the last selected option as you mentioned.

**Comment by lausellduane** [comment]
I am closing this issue, I found the answer to capture multiple values from the select multiple input and insert them in an array is to use `React.createRef(); ` and not `ReactDOM.findDOMNode().value`. It seems that findDOMNode only gets 1 value.

If anyone encounters with this here is how I implemented it:

To create the reference you declare it in the constructor like this `this.createService = React.createRef();`

To access the reference value you can call the _current_ attribute of the node. To build the form data for the post request you use `service_ids: this.createService.current.props.value`

To attach the reference to a react element like the input you need call the reference in the ref prop like this `ref={this.createService}` 

The function to get the list of values from the input: 

`getSelectValues(event) {
        this.setValid(event);
        let newState = { incident: this.state.incident };
        let target = event.target;
        let name = target.name;
        let opts = Array.from(target.selectedOptions, option => parseInt(option.value, 10));
        newState['incident'][name] = opts;
        this.setState(newState);
        console.log('getSelectValues newState: ', newState);
    }`

reference: https://reactjs.org/docs/refs-and-the-dom.html

![image](https://user-images.githubusercontent.com/20842443/44696792-f767ae80-aa46-11e8-8029-13c0b1968eb7.png)

![image](https://user-images.githubusercontent.com/20842443/44696810-0babab80-aa47-11e8-978a-c2886ebd1d08.png)
