### ISSUE TITLE
No option to change navbar height

### ISSUE THREAD

**Issue by harveyslash** [reactstrap/reactstrap#1170]
- components: `Navbar`
- reactstrap version `^6.3.1`
- import method `es` 

### What is happening?

No simple way to change navbar height. 

### What should be happening?

Some prop can be used to change navbar height. Manually setting css style will mess with the animation.

**Comment by TheSharpieOne** [comment]
It's the same for setting bootstrap itself

**Comment by harveyslash** [comment]
I added a classname of `py-0` (that removes y axis padding) to the navbar , and got the desired result.
