### ISSUE TITLE
Sticky top not working

### ISSUE THREAD

**Issue by harveyslash** [reactstrap/reactstrap#1179]
- components: `Navbar`
- reactstrap version `6.3.1`
- import method `es` 

### What is happening?

setting sticky="top" does not make the navbar 'fixed' while also pushing the content underneath it, below. 

This is my 'home page'. I have included the whole thing so that it may help understand why its causing such an issue. 

```
 <div>

                    <NavBarWithButtonsContainer/>

                <div>

                    <Jumbotron fluid style={bodyStyle}>
                        <Container fluid>

                            <div className='text-center' style={{marginTop: "25%"}}>

                             
                            </div>

                        </Container>

                    </Jumbotron>

                    </Container>

                </div>

                {this.state.openPopup &&
             
                }

            </div>
```

And my navbarwithbuttons is: 

```
 <div>

                <Navbar color={this.state.bgColor} light expand="md"  sticky={'top'} className="shadow-sm py-0 border-dark border-bottom">

                    <Container>
                        <NavbarBrand tag={Link} to="/"> <img src={this.props.lightLogo ? beatestLogo : beatestDarkLogo} height="30"/> </NavbarBrand>


                        {this.props.children &&
                        <div>
                            < NavbarToggler onClick={this.toggle} className="navbar-light"/>

                            <Collapse isOpen={this.state.isOpen} navbar>

                                <Nav className="ml-auto" navbar>
                                    {this.props.children}
                                </Nav>
                            </Collapse>

                        </div>

                        }
                    </Container>

                </Navbar>
            </div>


```

Oddly enough, if I copy paste the generated html of my navbar after my page renders into the body section, it does become 'sticky'. But otherwise it doesnt stick when i scroll past it

**Comment by TheSharpieOne** [comment]
Bootstrap notes that `.sticky-top` uses position: sticky, which [isn’t fully supported in every browser](https://caniuse.com/#feat=css-sticky).

The support it hit or miss, only firefox has full support.

This sounds like a browser defect as the same HTML produces different results.

There is a `fixed` prop which uses `position: fixed` which does a similar thing. It has better browser support and may be able to be used based on your design needs.

Reactstrap only adds the bootstrap classes, anything else after that is bootstrap's styles.

**Comment by harveyslash** [comment]
It seems to be an issue with the navbar inside a div. 
Since react expects to be inside a div , is there any case in which reactstrap will ever get sticky navbar to correctly work ?

**Comment by TheSharpieOne** [comment]
`Navbar` will output a `<nav>` by default (overridable via the `tag` prop). This `<nav>` will get all of the classes, such as `.navbar .sticky-top`. It will be "stuck" to the parent element. If there is a `<div>` wrapping just the `Navbar` it is most likely coming from your usage.

Take a look at this usage: https://stackblitz.com/edit/reactstrap-v6-34oeaf?file=Example.js

**Comment by harveyslash** [comment]
I was wrapping the navbar inside a div that was causing the issue (not sure why). After seeing your example, I was able to narrow the issue to this. 

Thanks!

**Comment by MichaelDimmitt** [comment]
Sticky cares about 
1) parent element height and maxHeight
2) overflow-y

often this involves changing heights to minHeight
or removing overflow-y: hidden

that was specified before the sticky elements existed.
