### ISSUE TITLE
CSS: fixed table header

### ISSUE THREAD

**Issue by Binhngoc** [reactstrap/reactstrap#1183]
- i'm using reactstrap yours
and do not know how to do CSS fixed table header

**Comment by scottblinch** [comment]
Do you mean fixed-width cells or do you want the table header to be `position: fixed`? Either way, I'm not sure if that would be the concern of reactstrap. You'd achieve the former by using [`table-layout`](https://css-tricks.com/fixing-tables-long-strings/) and the latter by perhaps using a [different existing React package](https://react-table.js.org/#/story/fixed-header-w-vertical-scroll).

**Comment by hungdev** [comment]
i have the same question

**Comment by TheSharpieOne** [comment]
This would be a better question for bootstrap since bootstrap is the styles/css and reactstrap just applies the bootstrap classes
Also, this might help: https://css-tricks.com/position-sticky-and-table-headers/

**Comment by juanRebolledo** [comment]
I was searching the way to make this possible. 


`.table-responsive{
  height:400px;  
  overflow:auto;
}
 thead tr:nth-child(1) th{
    background: white;
    position: sticky;
    top: 0;
    z-index: 10;
  }`

This works
