### ISSUE TITLE
how to get radio button value ?

### ISSUE THREAD

**Issue by kohahn** [reactstrap/reactstrap#1192]
### Issue description

- components: `name`
- reactstrap version `6.4.2`
- import method `umd/csj/es` 
- react version `#x.x.x`
- bootstrap version `#x.x.x`

### What is happening?

I looking for docs, but not find.

### What should be happening?

I want to get radio button value
### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

### Code

https://stackblitz.com/edit/reactstrap-v5-beta-starter-mwxss5?file=index.js

**Comment by TheSharpieOne** [comment]
Radios and how they work are not specific to reactstrap, please see http://react.tips/radio-buttons-in-reactjs/ for how radios work within react.

It's really the `checked` prop (which is similar to the `value` from of "normal" inputs except it's a boolean so you have to determine that you state value is equal to the `value` prop on the specific radio.

Note that for the examples on that page, `<input />` can be replaced with reactstrap's `<Input />` and everything will work the same code wise.
