### ISSUE TITLE
DropdownItem link invisible in inverse/dark Navbar.

### ISSUE THREAD

**Issue by geon** [reactstrap/reactstrap#1193]
- components: `DropdownItem`, `Navbar`
- reactstrap version `#6.4.0`
- import method `import in typescript` 
- react version `#16.3.2`
- bootstrap version `#x.x.x`
What? I use Reactstrap *instead* of bootstrap, right?

### What is happening?

When using a dark/inverse Navbar, the Navbar looks great, but the background of the DropdownItem is still light, making the light text on it invisible.

### What should be happening?

The DropdownItem should either have dark text, or the background should be dark, like the Navbar.

As it is, I had to manually add the `className="bg-dark"`attribute on all `DropdownMenu`s and `DropdownItem`s.

### Steps to reproduce issue

Run the code.

### Code

```
				<Navbar color="dark" dark expand="md">
					<Nav className="ml-auto" navbar>
						<UncontrolledDropdown nav inNavbar>
							<DropdownToggle nav caret>
								This looks fine
							</DropdownToggle>
							<DropdownMenu>
								<DropdownItem>
									Invisible text
								</DropdownItem>
							</DropdownMenu>
						</UncontrolledDropdown>
					</Nav>
				</Navbar>

```

**Comment by TheSharpieOne** [comment]
> bootstrap version #x.x.x
What? I use Reactstrap instead of bootstrap, right?

reactstrap replaces bootstrap.js, not bootstrap css. You still need bootstrap to for styles.

Here is what the code you provided in action, I can see the "Invisible text"
https://stackblitz.com/edit/reactstrap-v6-bu8xia?file=Example.js

**Comment by geon** [comment]
> reactstrap replaces bootstrap.js, not bootstrap css. You still need bootstrap to for styles.

Right. I had `https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css` included. I had totally forgotten about that. I was searching through my npm imports.

> I can see the "Invisible text"

Even with the older Bootstrap css I was using, The stackblitz example still looks correctly. Something else must be wrong in my setup. I'll dig deeper.

**Comment by geon** [comment]
I found the difference. I was using a `NavLink` inside the `DropdownItem`. That made it invisible. It outputs a link inside a button, which is clearly wrong.

some example of how you shoul use links in menues would be helpful. I opted for `<DropdownItem tag="a" href={href}>`. But that was not very obvious.
