### ISSUE TITLE
Panel support

### ISSUE THREAD

**Issue by HonzsSedlomn** [reactstrap/reactstrap#1196]
Is anyone working on panel component support? I don't see this component in the documentation

**Comment by crissdev** [comment]
@HonzsSedlomn We have cards instead. See https://getbootstrap.com/docs/4.1/migration/#panels and https://reactstrap.github.io/components/card/

**Comment by TheSharpieOne** [comment]
As @crissdev pointed out, panels were removed from bootstrap in bootstrap 4 and reactstrap only supports bootstrap 4 so reactstrap doesnt contain panels.
