### ISSUE TITLE
react-popper 1.0.x compliant

### ISSUE THREAD

**Issue by sevdog** [reactstrap/reactstrap#1197]
### Issue description
The following components (at least) should be updated to use the latest version of `react-popper` (branch `1.0.x`, which was first released on [14h June](https://github.com/FezVrasta/react-popper/releases/tag/v1.0.0))

- components: `PopperContent`, `DropdownToggle`

### What is happening?

As of now, these components are using `Target` and `Arrow` imported from `react-popper` which have been removed/reworked in version `1.0.x`.

### What should be happening?

These components should use new `react-popper` APIs and dependency should change to use branch `1.0.x`.

**Comment by virgofx** [comment]
Right now the 1.0.x build also breaks externally as it didn't include the proper UMD external Rollup build config from 0.10.x. So before supporting 1.0.x , react-popper will need to be fixed upstream.

**Comment by sevdog** [comment]
UMD rollup was not fixed in [this PR](https://github.com/FezVrasta/react-popper/pull/159)?

**Comment by virgofx** [comment]
I know I checked the original 1.0.0 and I believe 1.0.1 and it did not work. The rollup was still broken. We merged some fixes into the v.0.10.x series that never made it to the 1.0.  They don't do a lot of testing on the external. 

You can test it right now by using the example external code in the Readme and attempt to pull in the specific versions of `react-popper`.

**Comment by sevdog** [comment]
I've created [this gist](https://gist.github.com/sevdog/7082c8f67a6bf3a643419bef8095adaa) based on Reactstrap's Readme (which also need to be updated, cause `TooltipTrigger` and `TooltipContent` are not in the codebase).

On my machine there were no errors with `ReactPopper` (tested with Chrome and Edge), but the example remains broken cause APIs have been changed.

**Comment by virgofx** [comment]
1.0.2 may have fixed it ... I'll reconfirm also

**Comment by virgofx** [comment]
FYI - 1.0.2 doesn't work externally ... need to fix react-popper Rollup build process.

**Comment by alamothe** [comment]
+1 

Would be great to update `react-popper` dependency!

**Comment by dcousens** [comment]
If you use `react-popper@1.0.2` and this project together,  you will run into confusing errors.

**Comment by sevdog** [comment]
> If you use `react-popper@1.0.2` and this project together, you will run into confusing errors.

This is obvious because there are breaking changes in `react-popper` since [`1.0.0-beta4`](https://github.com/FezVrasta/react-popper/releases/tag/v1.0.0-beta.4).

**Comment by dcousens** [comment]
@sevdog not exactly,  you might expect `npm` to sandbox the two dependencies such that `reactstrap` uses `0.10.x` and your project use `react-popper@1.0.2`,  but,  that isn't a thing.

**Comment by fnpen** [comment]
@virgofx 

```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react-popper/1.3.2/umd/react-popper.min.js"></script>
console.log(ReactPopper); -> output object with methods
```

Is working correct.

They have changed API.
You need help with change code? Because you are writing here about UMD config problems.

Thank you!

**Comment by virgofx** [comment]
Let me confirm again ... I know they re-released a few versions let me check.

**Comment by fnpen** [comment]
> Let me confirm again ... I know they re-released a few versions let me check.

I migrated to 1.3.x and tests also, but I have problems with old context API.  I make helper to work with it.

https://github.com/reactstrap/reactstrap/pull/1376

**Comment by sevdog** [comment]
Since #1427 was merged and now this package requires `"react-popper": "^1.3.6"`.

This issue can be closed, thanks.
