### ISSUE TITLE
Full support for React 16.3 ref objects as `target` property

### ISSUE THREAD

**Issue by josh-degraw** [reactstrap/reactstrap#1198]
According to #947, there should be support for using the React 16.3 `createRef` api as the `target` element in components such as `Tooltip`. If this is the case, the type definitions should be updated to reflect this. 

I am currently trying to use this api to use tooltips and I'm using Typescript, and if this is implemented, the type definitions do not reflect this. I'd be happy to submit a PR to fix this if necessary.

**Comment by TheSharpieOne** [comment]
I believe your usage may not be right. `Tooltip`'s `target` accepts a DOMElement which can be obtained React 16.3 "ref objects" via `myref.current`. You should be passing in the current reference from the object and not the object itself.
```jsx
this.myRef = React.createRef();
//...
<div ref={this.myRef} />
// this would not return the reference
<Tooltip target={this.myRef}>
// This is how you get the reference
<Tooltip target={this.myRef.current}>
```

Just as before the ref object people used functions to obtain the ref, those functions could not be used as `target`, but the ref obtained from those functions could be used: 
```jsx
getRef = ref => {
  this.myRef = ref;
}
//...
<div ref={this.getRef} />
// this would be the "old way" equivalent of what you are trying to do
<Tooltip target={this.getRef}> {/* This never worked */}
// this is how the "old way" worked
<Tooltip target={this.myRef}> {/* This works */}
```

Note: the `target` _must_ be provided, so you need to ensure you have the ref before you attempt to render `Tooltip`

**Comment by josh-degraw** [comment]
@virgofx Cool I'll start in on it.

@TheSharpieOne I feel like this adds unnecessary boilerplate to the user of the library. It's not a hard thing to add a check in the rendering logic to allow for passing in the full Ref object. In fact I would argue that it's a better practice because it keeps it more declarative, and the intent is very clear.

This way, I can write 
``` tsx
class MyComponent extends React.Component {
  private target = React.createRef<HTMLAnchorElement>();

  private container = React.createRef<HTMLDivElement>();

  public render() {
      return (
          <div ref={this.containerObj}>
              <p>Somewhere in here is a <a href="#" ref={this.refObj}>tooltip</a>.</p>
              <UncontrolledTooltip container={this.container} target={this.target}>
                  Hello world!
              </UncontrolledTooltip>
          </div>
      );
  }
}
```

And now I as the implementer don't have to worry about the null checks, and I can be confident that all of my references are correct, and I don't have to concern myself with the ordering of when the target is rendered, but I know that when it is rendered the tooltip should work as expected.

The alternative would be something like

``` tsx
class MyComponent extends React.Component {
  private target = React.createRef<HTMLAnchorElement>();

  private container = React.createRef<HTMLDivElement>();

  render() {
      return (
          <div ref={this.containerObj}>
              <p>Somewhere in here is a <a href="#" ref={this.refObj}>tooltip</a>.</p>
              {
                this.container.current && this.target.current
                && 
                <UncontrolledTooltip container={this.container.current} target={this.target.current}>
                     Hello world!
                </UncontrolledTooltip>
              }
          </div>
      );
  }
}
```

Which seems overly verbose and adds unnecessary mental overhead to the writer. I would be okay with the above if the library would handle null `current` values instead, but I would prefer the first way I've outlined here as it seems more idiomatic to me.
