### ISSUE TITLE
dropdown doesnt work if i'm placing <input/> inside DropdownToggle (in firefox)

### ISSUE THREAD

**Issue by borispinus** [reactstrap/reactstrap#1202]
I reproduced the case on https://reactstrap.github.io/components/dropdowns/: replaced plain text with </input>. Just like that:
![screenshot_1](https://user-images.githubusercontent.com/12012421/45152969-30d4b280-b1db-11e8-9fe6-3daebe5ee06c.png)

And then nothing happens on DropdownToggle click: popup is not showing, no focus on input.

In chrome it works fine

**Comment by TheSharpieOne** [comment]
It's considered invalid HTML markup to have an `input` within a `button`. You'll need to change the `tag` on the `DropdownToggle` to be something like a `div`.
