### ISSUE TITLE
Set specific behavior on escape key pressed in Input

### ISSUE THREAD

**Issue by ganzf** [reactstrap/reactstrap#1213]
- components: `Input`
- reactstrap version `#5.0.0`
- import method `es`
- react version `#16.3.1`
- bootstrap version `#4.1.0`

### What is happening?

When pressing escape key while focusing an Input, onBlur is called but not onKeyPress.

### What should be happening?

I would expect onKeyPress to be called first, so that I can prevent propagation and add custom behavior.

### Steps to reproduce issue

1. Create an Input
2. pass an onKeyPress prop and onBlur
3. Notice how onKeyPress is not called for escape key

If this is an expected behavior, i'm sorry to bother you, but if you can give me some directions as to how I can bypass this issue, I would be very grateful :)

SOLVED: Make sure no browser extension is capturing your inputs against your will and without your knowledge.

**Comment by TheSharpieOne** [comment]
Try `onKeyDown`. IIRC `onKeyPress` is both the down and the up, since the `esc` event will trigger the blur it would be to late at that point. `onKeyDown` should allow you to get the event and even prevent if it needed.

**Comment by ganzf** [comment]
Thank you for your answer ! Unfortunately, this does not work either. But that was certainly a good idea 👍

**Comment by TheSharpieOne** [comment]
I think something else must be going on in your setup. Here is an example of how to handle the esc key. 

When I run it and hit esc, I get the alert and am able to preventDefault
https://stackblitz.com/edit/reactstrap-v6-jwzm5v?file=Example.js

```jsx
import React, { Component } from 'react';
import { Input } from 'reactstrap';

class Example extends Component {
  handle = event => {
    console.log(event.keyCode);
    if (event.keyCode === 27) {
      event.preventDefault();
      alert('You hit esc!')
    }
  }
  render() {
    return (
      <div>
        <Input onKeyDown={this.handle} />
      </div>
    )
  }
}

export default Example;
```

**Comment by ganzf** [comment]
Well, thanks for the snippet. What browser are you using ? I'm on chrome Version 68.0.3440.106 (Official Build) (64-bit).
In your snippet, when I press the escape key it blurs the input but nothing is called. If I hade an onBlur function to the input, the onBlur function is called.

**Comment by TheSharpieOne** [comment]
Google Chrome Version 69.0.3497.81 (Official Build) (64-bit) on Mac

**Comment by ganzf** [comment]
I've tried your snippet in incognito mode, it works. I probably have an extension in the way of a correct behavior. 
I'll update this post when I find the one causing the issue ! 👍

**Comment by nerfologist** [comment]
I just had the very same problem (unable to intercept ESC keypresses on `onKeyDown` in a textarea). In my case the culprit was the Vimium extension. Mentioning for posterity.

**Comment by jordwest** [comment]
Ahhahah thanks @nerfologist, had the same issue here, just Vimium 🤦

**Comment by benjaminorthner** [comment]
omg thank you @nerfologist ... Spent so long on this and in the end it was just vimium for me aswell

**Comment by Kristiyan96** [comment]
As @nerfologist said, 

```
<TextField
    ...
    onKeyDown={handleEscape}
/>

const handleEscape = ({ code }) => {
  if (code === 'Escape') {
    handleClose();
  }
};
```

**Comment by ntrp** [comment]
> I just had the very same problem (unable to intercept ESC keypresses on `onKeyDown` in a textarea). In my case the culprit was the Vimium extension. Mentioning for posterity.

Man I was going insane over this crap....
