### ISSUE TITLE
Nav Props thows Dev Console Error

### ISSUE THREAD

**Issue by DBombay** [reactstrap/reactstrap#1214]
- components: `Nav`
- reactstrap version `6.3.1`
- import method `es` 
- react version `16.4.2`
- bootstrap version `4.1.2`

### What is happening?

We're getting a console error regarding a prop passed to `<Nav>`

### What should be happening?

Since this Header was built following the example, we expect that there'd be no error message.

### Steps to reproduce issue

1. Build a header with a `Nav` component
2. Pass the prop of `navbar` to the component without a value: `<Nav navbar>`
3. Open Chrome dev console and review error message.

### Error message in console

On our application's home page header, the console is logging the following error:

<img width="1665" alt="screen shot 2018-09-10 at 10 05 40 am" src="https://user-images.githubusercontent.com/4355236/45302451-603c3580-b4e1-11e8-8511-5c54c6138c02.png">

In case that's too small:

```
Warning: Received `true` for a non-boolean attribute `navbar`.

If you want to write it to the DOM, pass a string instead: navbar="true" or navbar={value.toString()}.
```

I followed the warning message's suggestion and changed the `prop` to `<Nav navbar={true}>` and `<Nav navbar{true.toString()}>`.

Both returned the following error:

<img width="1666" alt="screen shot 2018-09-10 at 10 11 04 am" src="https://user-images.githubusercontent.com/4355236/45302661-e5274f00-b4e1-11e8-815c-47abc20a389b.png">

or:

```
Warning: Failed prop type: Invalid prop `navbar` of type `string` supplied to `Nav`, expected `boolean`.
```

### Code
```
      <Nav navbar>
        <Navbar navbar fixed='top' expand="lg" color="primary" className='justify-content-between'>
      ...
        </Navbar>
      </Nav>
```

**Comment by TheSharpieOne** [comment]
> Since this Header was built following the example, we expect that there'd be no error message.

Which example? It probably needs to be updated/corrected.

Do not add `navbar` to `Navbar`

**Comment by DBombay** [comment]
@TheSharpieOne 

The example was the one [here] (https://reactstrap.github.io/components/navbar/), specifically:

```
      <div>
        <Navbar color="light" light expand="md">
          <NavbarBrand href="/">reactstrap</NavbarBrand>
          <NavbarToggler onClick={this.toggle} />
          <Collapse isOpen={this.state.isOpen} navbar>
            <Nav className="ml-auto" navbar>
              <NavItem>
...
```

You can also ignore the `navbar` on `<Navbar>`, that was removed after I copied and pasted

**Comment by TheSharpieOne** [comment]
> You can also ignore the navbar on <Navbar>, that was removed after I copied and pasted

That was your issue, the first verror was complaining about `navbar` on `nav` (not `Nav`), `nav` is the DOM element created by `Navbar`

The second error message is because you tried to change `navbar` on `Nav` to be a string, which it only allows boolean.

**Comment by DBombay** [comment]
Turns out there was a `<footer>` element with a nested `<Navbar navbar>`, which would appear to be the culprit. Thanks for the help!

**Comment by YechiamTK** [comment]
I think it's better to reopen this one as opposed to creating a similar one.
I'm following the logic in the docs for `<Navbar>`:

`<Navbar color="light" light expand="md">
          ...
          <Nav className="mr-auto" navbar>
            <NavItem>
              <NavLink href="/components/">Components</NavLink>
              ....
            <UncontrolledDropdown nav inNavbar>
              <DropdownToggle nav caret>
                Options` 
            ...`

Following this logic I have:

`<Reactstrap.Navbar color='dark' expand='sm' className='pt-3 shadow d-flex'>
...
                    <Reactstrap.Nav className="mx-auto">
...
                        <Reactstrap.UncontrolledDropdown nav inNavbar className="mx-5">`

From which I recieve 2 Warnings: the first, on `nav` same warning as DBombay received; the second, on `inNavbar`:

`Warning: React does not recognize the `inNavbar` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `innavbar` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`
