### ISSUE TITLE
<Input plaintext> should render an <input>, not a <p>

### ISSUE THREAD

**Issue by michaelti** [reactstrap/reactstrap#1225]
- reactstrap version `#6.4.0`
- bootstrap version `#4.1.3`

### What is happening?

When rendering an `<Input>` with the `plaintext` prop, reactstrap outputs a paragraph tag instead of an input tag.
Demo: https://stackblitz.com/edit/reactstrap-x86s49?file=Example.js

### What should be happening?

According to the [Bootstrap docs](https://getbootstrap.com/docs/4.1/components/forms/), a "plaintext" input simply needs to be an `<input>` with the "form-control-plaintext" class. The input should not be changed to a `<p>` in this case. If the input must also be read-only, the html "readonly" property should be used.

### Code / Suggested fix?

This behaviour seems to be located in [src/Input.js (line 78)](https://github.com/reactstrap/reactstrap/blob/master/src/Input.js#L78):
```
if (plaintext || staticInput) {
    formControlClass = `${formControlClass}-plaintext`;
    Tag = tag || 'p';
}
```

I believe the line `Tag = tag || 'p';` should be removed.

I could submit a PR, but I'm new at contributing and don't want to break anything!

**Comment by TheSharpieOne** [comment]
I think this changed under us and we didn't notice.

I'll put up a PR, but I think it's considered a breaking change for reactstrap to change the default tag.

**Comment by TheSharpieOne** [comment]
This is done, it's considered a breaking change as the markup generated will be different. It's included in the feature/v7 branch which will be release once all of the other breaking changes are completed and ready.
