### ISSUE TITLE
SVG Navbar

### ISSUE THREAD

**Issue by Yourdigitalheart** [reactstrap/reactstrap#1227]
- components: `NavBarBrand`
- reactstrap version `#6.4.0`
- import method `umd/csj/es` 
- react version `#16.5.0`
- bootstrap version `#4.0.0`

### What is happening?

Impossible to show an svg image on the navbar. I try many ways but impossible 

Thanks

**Comment by AndyCJ** [comment]
You mean like this?

https://jsfiddle.net/n5u2wwjg/191829/
