### ISSUE TITLE
Hitting enter key on Dropdown item with a link does not redirect me

### ISSUE THREAD

**Issue by simontong** [reactstrap/reactstrap#1228]
- components: `Dropdown`
- reactstrap version `#6.4.0`
- import method `es`
- react version `#16.5.0`
- bootstrap version `#4.1.3`

### What is happening?
I have a dropdown with some links using react router and I want to be able to tab through them and hit enter to go to the URL. When I hit enter nothing is happening (a-la `e.preventDefault()`)

### What should be happening?
Should be redirecting to the URL specified in the router. 

I believe it might be related to the `handleKeyDown` method in the Dropdown.js file.
What I am not sure about is if there is a specific reason that hitting space will trigger the onClick event but hitting enter doesn't.

### Code
```jsx
import React from 'react';
import { Dropdown, DropdownItem, DropdownMenu, DropdownToggle } from 'reactstrap';
import { Link } from 'react-router-dom';
import styles from './styles.scss';

class MyMenu extends React.Component {

  state = {
    isOpen: false,
  };

  toggle = () => {
    this.setState({ isOpen: !this.state.isOpen });
  };

  render () {
    return (
      <Navbar color="dark" dark expand="md" className={styles.navbar}>
        <Link to="/" className="navbar-brand">
          <span className={styles.logo}/>
          <span>My Logo</span>
        </Link>
        <NavbarToggler/>
        <Collapse isOpen={true} navbar>
          <Nav className="mr-auto" navbar>
            <Dropdown nav inNavbar isOpen={this.state.isOpen} toggle={this.toggle}>
              <DropdownToggle nav caret>My Items</DropdownToggle>
              <DropdownMenu className="shadow-sm rounded">
                <DropdownItem tag={Link} to="/go-here">Go here</DropdownItem>
              </DropdownMenu>
            </Dropdown>
          </Nav>
        </Collapse>
      </Navbar>
    );
  }
}

export default MyMenu;
```

**Comment by AndyCJ** [comment]
I currently have this working in my application using the following:

    import { NavLink as RouteNavLink } from 'react-router-dom';
    import { Collapse, DropdownItem, DropdownMenu, DropdownToggle, Nav, Navbar, NavbarBrand, NavbarToggler, NavItem, NavLink, UncontrolledDropdown } from 'reactstrap';

    <Navbar color="light" light expand="md">
        <NavbarBrand href="/">FooBar</NavbarBrand>
        <NavbarToggler onClick={this.toggle} />
        <Collapse isOpen={this.state.isOpen} navbar>
            <Nav className="ml-auto" navbar>
                <NavItem>
                    <NavLink to="/" tag={RouteNavLink}>Home</NavLink>
                </NavItem>
                <UncontrolledDropdown title={displayName} nav inNavbar>
                    <DropdownToggle nav caret>{displayName}</DropdownToggle>
                    <DropdownMenu right>
                        <DropdownItem tag="div">
                            <NavLink to="/logout" tag={RouteNavLink}>Logout</NavLink>
                        </DropdownItem>
                        <DropdownItem tag="div">
                            <NavLink to="/resetpassword" tag={RouteNavLink}>Reset Password</NavLink>
                        </DropdownItem>
                    </DropdownMenu>
                </UncontrolledDropdown>
            </Nav>
        </Collapse>
    </Navbar>

**Comment by TheSharpieOne** [comment]
Looks like [this change](https://github.com/reactstrap/reactstrap/commit/abbac56c18ba4aeb7552fff7a23976bee28d99c0) introduced this. The change intended for the code to handle selecting items based on the item text and the key pressed so it changed from only checking for specific keys to only excluding certain keys but it does not account for the enter key.

**Comment by simontong** [comment]
Just created this pull request
https://github.com/reactstrap/reactstrap/pull/1232

**Comment by KevinKlingelsmith** [comment]
Hi, 

I'm still seeing an issue with the enter key not resulting in a redirect in version 6.5.0.
Pressing the space bar works as expected, pressing the enter key doesn't.

Looking at the above mentioned f2528da,  the affected line of code is

`if (e.which === keyCodes.space && keyCodes.enter && this.props.isOpen && container !== e.target) {`

I believe that should be 

`if ((e.which === keyCodes.space || e.which === keyCodes.enter) && this.props.isOpen && container !== e.target) {`

I did update the distributed .js manually with this change and verified that it worked as I would expect.

**Comment by mogularpb** [comment]
This is also an issue for accessibility as the ability to select with the Enter key is a commonly expected behaviour

**Comment by simontong** [comment]
Just made a pull request with corrections outlined in @KevinKlingelsmith's comment
