### ISSUE TITLE
CustomInput type="checkbox" change not working

### ISSUE THREAD

**Issue by bestguy** [reactstrap/reactstrap#1236]
- components: `CustomInput`
- reactstrap version `#6.4.0`
- react version `#16`
- bootstrap version `#4.1`

### What is happening?

I'm unable to use `<CustomInput type="checkbox">` with onChange, onClick, or onInput and toggle change:

      <CustomInput
          type="checkbox"
          checked={this.state.checked}
          onChange={e => this.setState({ checked: e.target.checked })}
        />

### What should be happening?

I'd expect it to work the same as a normal `<Input type="checkbox">`:

      <Input
          type="checkbox"
          checked={this.state.checked}
          onChange={e => this.setState({ checked: e.target.checked })}
        />

### Code

https://stackblitz.com/edit/reactstrap-ujvq62?file=Example.js

**Comment by TheSharpieOne** [comment]
CustomInputs needs an `id` to link the fake input/label to the hidden input. It works the same a bootstrap itself if you don't provide an `id` (and `for` attribute on the label)

Checkout: https://stackblitz.com/edit/reactstrap-v9gnh7?file=Example.js

`id` is a required prop. While it is documented in the way reactstrap documents those things, this just shows that reactstrap's documentation format is not the best.
Closing in favor of #585 which is more about improving the docs.

**Comment by bestguy** [comment]
Ah, thanks a lot for the explanation @TheSharpieOne , sounds good
