### ISSUE TITLE
React-TS: using <Row form> causes build error.

### ISSUE THREAD

**Issue by Ashniu123** [reactstrap/reactstrap#1240]
- components: `Row`
- reactstrap version `#6.4.0`
- import method `umd/csj/es` 
- react version `#16.5.2`
- bootstrap version `#4.1.3`

### What is happening?

Typescript part fails with `<Row form>...</Row>` because the 'form' is already defined in the interface `AllHTMLAttributes<T>` as `string`.

PR leading to this issue [here](https://github.com/reactstrap/reactstrap/pull/1237#issuecomment-424814915).

### What should be happening?

No error

### Steps to reproduce issue

1. Use `<Row form>...</Row>` in React-TS

### Error message in console

```
Type 'true' is not assignable to type 'string | undefined'.
```

### Description
I had made a PR in which I thought that `form` would be a good attribute for `form-row` class. Original issue [here](https://github.com/reactstrap/reactstrap/issues/1195). Apparently, the types interfere with it and build fails on React-TS.

### Solution
Suggest a better prop name or maybe make a new `<FormRow>` element.
Also update `@types/reactstrap` accordingly.

P.S. Thanks to [marcoromag](https://github.com/marcoromag) for finding the issue.

**Comment by TheSharpieOne** [comment]
The commit you are referencing hasn't been released. Also typescript is a separate thing and the typescript definitions are kept in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/reactstrap and maintained by others. You may want to open an issue there if the definition needs to be updated.
