### ISSUE TITLE
Can Not Type A Space In An Input

### ISSUE THREAD

**Issue by cutterbl** [reactstrap/reactstrap#1241]
- components: `Input`
- reactstrap version `#6.4.0`
- import method `es`
- react version `#16.4.2`
- bootstrap version `#4.1.3`

### What is happening?

I can not type a space in an Input field

### What should be happening?

When I type a space (like putting someone's fullname in the field) it should type a space

### Steps to reproduce issue

1. Render an Input `return <Input/>`
2. Try to type in `foo bar`

### Error message in console

```
There are no errors thrown in the console
```

### Code

```javascript
import React from 'react';
import { Input } from 'reactstrap';

const Search = () => <Input/>;
export default Search;
```

I literally stripped down my app until the only thing I was doing was rendering this input, and it still wouldn't allow it. I'm using webpack (latest stable) with babel (latest stable) to bundle my code. My webpack config has one rule for `jsx` files.

```
     {
        test: /\.jsx?$/,
        use: [
          {
            loader: 'babel-loader'
          }
        ]
      }
```

My babel config is pretty standard:

```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-transform-runtime",
    "@babel/plugin-transform-async-to-generator",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread"
  ],
  "sourceMaps": "inline"
}
```

Currently I am not optimizing/minimizing the code. (Hope this additional info helps)

**Comment by cutterbl** [comment]
I can try to put together a stripped down repo. The client would not allow this code to be publicly shared. I'll see if I can't put something together by the end of the day.

**Comment by GoPro16** [comment]
Closing this issue, feel free to re-open if you are still running into issues.
