### ISSUE TITLE
Navbar toggle menu Icon (hamburger) invisible when menu collapses.

### ISSUE THREAD

**Issue by Resumane** [reactstrap/reactstrap#1248]
The navbar toggle menu Icon that should appear when the navbar collapses is invisible when not using "light". My navbar is the same as in https://reactstrap.github.io/components/navbar/ but without "light".

I can't use "light" because it overrides my styling of nav items.

**Comment by h0h0h0** [comment]
+1 for this.

**Comment by TheSharpieOne** [comment]
Per bootstrap: http://getbootstrap.com/docs/4.1/components/navbar/#color-schemes
> Choose from .navbar-light for use with light background colors, or .navbar-dark for dark background colors.

It has to be `light` or `dark`, they don't really have an option for neither.

reactstrap doesn't color or style anything, that all happens via bootstrap's CSS. If there is a style issue which is causing something to not be visible, you should open an issue with bootstrap itself.

If you have custom styles for your nav items then you may need custom styles for the navbar.

**Comment by pedrozo96** [comment]
Hello, in my case works like this 

` <Navbar className="YOUR-CUSTOM-STYLES" light expand="md">`

Where  <Navbar> is your React Component from Reacstrap and "YOUR-CUSTOM-STYLES" are your styles.

Check the screenshot

[Screenshot](https://i.ibb.co/KFHdBRc/Captura.jpg)
