### ISSUE TITLE
PopoverContent not re-rendering

### ISSUE THREAD

**Issue by zeroasterisk** [reactstrap/reactstrap#125]
If you edit the props for PopverContent, and it's already open, it doesn't re-render the content until closed and opened again.

Take a look at the following codepen... just open one and let it sit for a few seconds... 
http://codepen.io/zeroasterisk/pen/zKxgrJ

You can see in the console.log that the state --> props are updating, but the UI is not.  If you close and re-open the popover, it shows the new/current props.

**Comment by eddywashere** [comment]
It's likely missing the rerender on prop update. Right now it checks if isOpen changed. Not an issue if the inner content is self contained, I think. Definitely need to fix this use case. Thanks for reporting!

**Comment by TheSharpieOne** [comment]
Yeah, the TetherContent only updates the content when it hides/shows. It needs a check for if it is showing/there is a container/element when the props change and to rerender (for a reason other than show/hide) the subtree if the container is there (similar to how the modal updates).

**Comment by eddywashere** [comment]
Fix published in 3.0.1

**Comment by eddywashere** [comment]
Updated Example pointing to 3.0.1: http://codepen.io/eddywashere/pen/Xjbkmx
