### ISSUE TITLE
Module Parse Failed

### ISSUE THREAD

**Issue by The-Code-Monkey** [reactstrap/reactstrap#1250]
I get this error when trying npm start

./node_modules/reactstrap/src/FormGroup.js
Module parse failed: Unexpected token (30:4)
You may need an appropriate loader to handle this file type.
|     inline,
|     tag: Tag,
|     ...attributes
|   } = props;
|

why is this happeneing

**Comment by ducanh2110** [comment]
@TheSharpieOne I'm newbie, can you explain more details about the solution? Thanks so much

**Comment by ducanh2110** [comment]
Thanks for your reply. I already used create-react-app and I still got this
error.  But yesterday I have just restart and delete some component, remove
node_modules. And now I can build it with no error. Thanks for your support.

**Comment by cbuschka** [comment]
Possibly you could import from the bundled version of reactstrap:
```
import {FormGroup} from 'reactstrap';
```
instead of
```
import FormGroup from 'reactstrao/src/FormGroup';
```

Sometime I ago we were hit by webpack/babel6 not capable of loading es6 modules form node_modules folder. So we used this to workaround.
