### ISSUE TITLE
UncontrolledCollapse error on IE11. Object doesn't support property or method 'forEach'

### ISSUE THREAD

**Issue by themetis** [reactstrap/reactstrap#1257]
### Issue description
- components: `UncontrolledCollapse`
- reactstrap version `6.5.0`
- import method `es`
- react version `16.5.2`
- bootstrap version `4.1.3`

### What is happening?

I've got an error when it is rendered on IE11.
The error is  "Object doesn't support property or method 'forEach'"

### Code

https://stackblitz.com/edit/reactstrap-uncontrolled-collapse-llryd4

**Comment by gergely-nagy** [comment]
Merged via #1262 ! Will be out in next release.

**Comment by z1m1n** [comment]
@gergely-nagy when will be next release?

**Comment by juanmiguelbesada** [comment]
Already fixed and merged. You should close this.
