### ISSUE TITLE
Collapse with delay does not work

### ISSUE THREAD

**Issue by burtonator** [reactstrap/reactstrap#1272]
- components: `Collapse`
- reactstrap version 6.5.0
- import method: typescript with commonjs
- react version 16.5.0
- bootstrap version 4.1.1

### What is happening?

<Collapse delay={{show: 0, hide: 0}}

... this just doesn't work. I don't want a delay but the default behavior is still used.

**Comment by jeff-nz** [comment]
Hi @burtonator ,

try this:
```
<Collapse timeout={{ enter: 0, exit: 0 }} />
```

Hope it helps.

**Comment by burtonator** [comment]
Thanks.. I don't follow.. what is the collapse for?  you want me to put the tooltip text in it?

**Comment by burtonator** [comment]
also, not seeing a timeout param in the Collapse...

**Comment by GoPro16** [comment]
The component directly uses [react-transition-group props](http://reactcommunity.org/react-transition-group/transition) so if you are having issues you can reference that lib for more examples.
