### ISSUE TITLE
6.4.0 breaks multiple selection in Modal

### ISSUE THREAD

**Issue by stefanb2** [reactstrap/reactstrap#1280]
- components: `Modal`
- reactstrap version `6.4.0`
- import method `npm`
- react version `16.6.0`
- bootstrap version `4.1.3`

### What is happening?

I have a Modal with a multiple select input in it. After upgrading from `6.3.0` to `6.4.0` it is no longer possible to perform multiple selections on that input. When I open the modal, click on the input to put it into focus and then try to select multiple items, i.e. either

* click on item A, press SHIFT-click on item B (i.e. select items A to B),
* click on item A, press CTRL-click on item B (i.e. select items A & B), or
* press CTRL-A (i.e. select all items on the list)

instead of the performing the selection the modal closes the moment I press either SHIFT or CTRL. I experienced the same behaviour on Chromium and Firefox.

Upgrading to `6.5.0` does not fix the issue.

### What should be happening?

Multiple selection should be possible instead of closing the Modal.

Downgrading to `6.3.0` fixes the issue.

### Steps to reproduce issue

1. upgrade reactstrap from `6.3.0` to `6.4.0`
2. rebuild the application
3. run the application and test the modals with multiple select inputs in them

### Error message in console

N/A

### Code

Input in the Modal:

```javascript
<Input
      ...
      multiple
      onChange={this.onChange}
      size={size ? size : '30'}
      type="select"
      value={this.state.selected}
      ...
>
   .... code to generate the <option> entries ....
</Input>
```

**Comment by stefanb2** [comment]
I'm not sure if this is relevant: the `Modal` is attached to a `Dropdown` / `DropdownToggle` in a `NavBar`, i.e. clicking on the dropdown text in the "menu bar" opens the modal window. The `isOpen` state of the `Dropdown` is passed as `isOpen=` property into the Modal.

**Comment by gergely-nagy** [comment]
I cannot reproduce: https://stackblitz.com/edit/reactstrap-1280?file=Example.js
Can you make an example on stackblitz?

**Comment by stefanb2** [comment]
Your example uses `Button` instead of `Dropdown` and therefore the issue is not reproducible. I edited your example and replaced the first `<Button>` with the following code (not sure if my edits were saved in that project without me logging in...)

```javascript
<Dropdown toggle={this.toggle}>
    <DropdownToggle nav>Launch Modal</DropdownToggle>
    <Modal
    ...
    </Modal>
</Dropdown>
```
and then I can reproduce the issue.

**Comment by stefanb2** [comment]
@gergely-nagy can you please update/remove the label?

**Comment by gergely-nagy** [comment]
I’m not 100% sure what you mean, but this is generally a poor user experience.
Apart from that it works still perfectly.
Code: https://stackblitz.com/edit/reactstrap-1280-v2?file=Example.js
Example: https://reactstrap-1280-v2.stackblitz.io/

**Comment by stefanb2** [comment]
@gergely-nagy your example code is not applicable to our application, i.e. we can't use a hamburger menu.

But I think your example points the out the way to work around this issue: you need to decouple the toggle for the `Dropdown` and the `Modal`. I have to verify this observation in the real application code tomorrow.

**Comment by stefanb2** [comment]
A quick test shows that changing the component code from
```javascript
<Dropdown
    toggle={this.toggle}
>
    <DropdownToggle
        nav
    >
    <Modal ..../>
</Dropdown>
```
to
```javascript
<Dropdown
    toggle={() => {}} // ignore toggle
>
    <DropdownToggle
        nav
        onClick={this.toggle}
    >
    <Modal ..../>
</Dropdown>
```
brings back the SHIFT-select and CTRL-select functionality of the multiple select input. I do not see any side effects on the other modal functionality, i.e. clicking om the menu bar opens the modal, clicking on the close elements in the Modal closes the modal.

**BUT:** CTRL-A, i.e. selecting all elements in the input list, no longer works. BTW: CTRL-A doesn't seem to work on stackblitz at all, i.e. it always selects elements in the development application. I guess that is a side-effect of the online IDE.

**Comment by stefanb2** [comment]
After a little bit more thinking and hacking around I conclude that updating to reactstrap 6.4.0 exposed a "misuse" in our application code that used to work.

* 6.4.0 changed the behaviour of the event handling for `Dropdown`, i.e. key events bubbling up from the child now trigger the `toggle=` callback
* not being aware that `onClick=` property works on `DropdownToggle` and that it can be used instead of the `toggle=` of the `Dropdown` parent
* putting the `Modal` as child of `Dropdown` thus causing the bubbling up of events

It seems there are several ways of doing it "correctly":

* make the `Modal` a sibling of `Dropdown`
* make the `Dropdown` `toggle=` a no-op and use the `DropdownToggle` `onClick=` for the callback
* replace `Dropdown` with `UncontrolledDropdown` (i.e.. remove the need for `toggle=`) and use the `DropdownToggle` `onClick=` for the callback

The obvious choice of using `Button` instead of `Dropdown` **does not** work, because `Button` doesn't support the `nav` boolean property to change its look from a regular button to a button in a navigation bar.

Closing as NOTABUG.
