### ISSUE TITLE
Override default configuration

### ISSUE THREAD

**Issue by grocc** [reactstrap/reactstrap#1284]
Hi to everybody.
I would like to understand how can I override the standard code.
For example, how can I change the standard breakpoint, or the gutter, or the color definition.
I can't find nothing about it in the doc.

Thanks to all!

**Comment by TheSharpieOne** [comment]
reactstrap doesn't have that in it's documentation as it's specific to bootstrap and bootstrap already documents that.

http://getbootstrap.com/docs/4.1/getting-started/theming/
http://getbootstrap.com/docs/4.1/extend/approach/

**Comment by grocc** [comment]
Yes, i get it following this page
http://getbootstrap.com/docs/4.1/getting-started/webpack/
Thanks!
