### ISSUE TITLE
how to use reactstrap navbar with react-router-dom? [Solved]

### ISSUE THREAD

**Issue by rajaee-rad** [reactstrap/reactstrap#1285]
Why is there no document to use the react-router-dom?
how can find full example for using reouter-dom and navigation in reactstrap?

- components: `name`
- reactstrap version `last version`
- react version `6.5`
- bootstrap version `4`

**Comment by AugustoAleGon** [comment]
I got the same question.

**Comment by ryanrs-chang** [comment]
same question, too~

**Comment by rajaee-rad** [comment]
i found solution

Navigation.js
```

import React, {Component} from "react";
import {Link} from 'react-router-dom';
import {
    Collapse,
    Navbar,
    NavbarToggler,
    NavbarBrand,
    Nav,
    NavLink,
    NavItem,
    UncontrolledDropdown,
    DropdownToggle,
    DropdownMenu,
    DropdownItem } from 'reactstrap';


export class Navigation extends Component {
    constructor(props) {
      super(props);
  
      this.toggle = this.toggle.bind(this);
      this.state = {
        isOpen: false
      };
    }
    toggle() {
      this.setState({
        isOpen: !this.state.isOpen
      });
    }
    render() {
      return (
        <div>
          <Navbar color="light" light expand="md">
            <NavbarBrand href="/">reactstrap</NavbarBrand>
            <NavbarToggler onClick={this.toggle} />
            <Collapse isOpen={this.state.isOpen} navbar>
              <Nav className="ml-auto" navbar>
                <NavItem>
                  **<NavLink tag={Link} to="/plantInfo">Plant Info</NavLink>**
                </NavItem>
                <UncontrolledDropdown nav inNavbar>
                  <DropdownToggle nav caret>
                    Options
                  </DropdownToggle>
                  <DropdownMenu right>
                    <DropdownItem>
                      Option 1
                    </DropdownItem>
                    <DropdownItem>
                      Option 2
                    </DropdownItem>
                    <DropdownItem divider />
                    <DropdownItem>
                      Reset
                    </DropdownItem>
                  </DropdownMenu>
                </UncontrolledDropdown>
              </Nav>
            </Collapse>
          </Navbar>
        </div>
      );
    }
  }
```

Main.js

```
import React, {Component} from "react";
import {Route} from 'react-router-dom';

import {Navigation} from './containers/Navigation';
import {Footer} from './containers/Footer';
import {PlantInfo} from './components/PlantInfo';


class App extends Component {
    render() {
        return (
            <div className="container-fluid">
                <div className="row">
                    <main className="main-content col-lg-12 col-md-12 col-sm-12 p-0">
                        <Navigation/>
                        <div class="main-content-container container-fluid px-4">
                            <Route  path="/plantInfo" component={PlantInfo}  />
                        </div>
                        <Footer/>
                    </main>
                </div>
            </div>
        );
    }
}

export default App;
```

**Comment by clemlak** [comment]
One small addition to rajaee-rad reply. What I like to do is to import `NavLink` from `react-router-dom` and then use the Bootstrap classes to highlight active pages:

```jsx
<NavItem>
  <NavLink exact to="/" className="nav-link" activeClassName="active">Home</NavLink>
</NavItem>
```

**Comment by TheSharpieOne** [comment]
You can still use all of the react router dom `NavLink` props when using reactstrap's `NavLink` with `tag` and not have to worry about `className`:

```jsx
import { NavLink as RRNavLink } from 'react-router-dom';
import { NavLink } from 'reactstrap';
// ...
<NavLink tag={RRNavLink} exact to="/" activeClassName="active">Home</NavLink>
```

**Comment by OndeVai** [comment]
This works, but doesn't address the fact that the containing NavItem is the one that needs the "activeClassName"

**Comment by AbhaysinghBhosale** [comment]
Great, Worked like a charm

**Comment by visionwind** [comment]
Thanks! I wanted to have the menu automatically close when a link is clicked on a xs device so I added `onClick={this.toggle}` to the NavLink props and it worked.

**Comment by TheSharpieOne** [comment]
I'm closing this since the the issue appears to be answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Comment by bilalbutt044** [comment]
i have tried all the methods describe above but these are not working in react hooks. when i pass `Link` or `NavLink` of `react-router-dom` in `tag` i got error 

> Error: Invariant failed: You should not use <NavLink> outside a <Router>

here is the my code 
`
import React, { useEffect } from "react";
import firebase from "../../config/config";
import { Nav, NavItem, NavLink } from "reactstrap";

import { Link, NavLink as RRNavLink } from "react-router-dom";

const Sidebar = props => {
  useEffect(() => {
    var db = firebase.firestore();
    // get collection
    // db.collection("course")
    //   .get()
    //   .then(snapshot => {
    //     snapshot.docs.map(data => console.log(data.data()));
    //   });

    // add collection by code
    //     db.collection("background")
    //       .add({
    //         image: "my image",
    //         version: "1.1"
    //       })
    //       .then(docRef => console.log(docRef.id));
    db.collection("background")
      .doc("HQjpRTg6WSHj1C3tTd1s")
      .update({ image: "lol", version: "1.3" });
  });

  //   update collection

  return (
    <div>
      <Nav className="col-md-3" vertical>
        <NavItem>
          <NavLink tag={RRNavLink} to="/home">
            categories
          </NavLink>
        </NavItem>
        <NavItem>
          <NavLink to="/home">extra categories</NavLink>
        </NavItem>
        <NavItem>
          <NavLink to="/home">background</NavLink>
        </NavItem>
      </Nav>
    </div>
  );
};

export default Sidebar;



`

**Comment by alonana** [comment]
see an example project from this in [this post](https://runkiss.blogspot.com/2020/02/react-bootstrap-with-navbar-react.html)

**Comment by TheSharpieOne** [comment]
@alonana The post you linked is about react-bootstrap; not reactstrap.
