### ISSUE TITLE
UncontrolledTooltip triggered while mouse still moving.

### ISSUE THREAD

**Issue by burtonator** [reactstrap/reactstrap#1286]
- components: `UncontrolledTooltip`
- reactstrap version `#6.5.0`
- import method `umd/csj/es` 
- react version `#16.5.2`
- bootstrap version `#4.1.1`

An UncontrolledTooltip is triggered if you're hovering over it but still moving the mouse, just still within the element.

This is very very different than any other tooltip implementation and really triggers the tooltip at the wrong times.  It's popping up when I'm just using the UI regularly... which is super confusing.

It should only pop up when the mouse is idle for the timeout.

**Comment by TheSharpieOne** [comment]
This is consistent with Bootstrap.
http://getbootstrap.com/docs/4.1/components/tooltips/]

You can add a delay if you want to have the tooltip wait before appearing.
