### ISSUE TITLE
Any character opens Dropdown menu

### ISSUE THREAD

**Issue by eckdanny-osi** [reactstrap/reactstrap#1287]
- components: `Dropdown`
- reactstrap version `6.5.0`
- import method `es`
- react version `16.5.2`
- bootstrap version `4.1.3`

### What is happening?

Any key (including e.g.; `Esc` or `Shift`) opens the `Dropdown` menu 

### What should be happening?

open the `Dropdown` (aria menu) only when `Enter` is pressed (from [WAI ARIA 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#menu))

### Steps to reproduce issue

1. keyboard nav to put focus on the `DropdownToggle` (the button tag)
2. press a key

![dropdown-bug](https://user-images.githubusercontent.com/30477263/48175365-8a7f5900-e2c0-11e8-8fcc-077eed673bf5.gif)

### Code

[![Edit 1vo8knprml](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1vo8knprml)

**Comment by eckdanny-osi** [comment]
I've started working on a fork. 85% satisfied (leaving on road trip tmrw). Hoping to get a PR out early next week to address wai-aria/keyboard-nav improvements to `Dropdown`. The **WiP Branch** is [here](https://github.com/reactstrap/reactstrap/compare/master...eckdanny-osi:fix-dropdown-keyboard-nav?expand=1).

Gist of changes:

* [x] Home/End key jumps
* [x] up/down wraps
* [x] spacebar enter interchangeable
* [x] aria [role=menuitem]
* [x] 1st item gets focus on menu expand
* [x] misc focus mgmt
* [ ] more tests
* [ ] memoize some stuff

![dropdown-upstream-pr](https://user-images.githubusercontent.com/30477263/48254716-a3baff00-e3bf-11e8-9b41-d3b592060744.gif)

**Comment by TheSharpieOne** [comment]
It should default to how bootstrap does it. You can allow for extra props to control extra ability.

Bootstrap doesn't do any of these:
- Home/End key jumps
- up/down wraps
- spacebar enter interchangeable
- 1st item gets focus on menu expand

**Comment by eckdanny-osi** [comment]
_d'oh!_ I'd been checking the [PR Thread](https://github.com/reactstrap/reactstrap/pull/1293) for feedback instead of here 🤕 

> Bootstrap doesn't do any of these:
> 
> * Home/End key jumps
> * up/down wraps
> * spacebar enter interchangeable
> * 1st item gets focus on menu expand

Apologies. I've only recently become familiar with project history and at time of submission hadn't understood the implied goal: _functional parity with Bootstrap_.

1. **Home/End key jumps**
   * 👍 not a feature in BS4
   * 🗯WAI-ARIA1.1 optional, but _required_ "If arrow key wrapping is not supported"<sup>[[1]](https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-11)</sup>
1. **up/down wraps**
   * 👍 not a feature in BS4
   * 🗯WAI-ARIA1.1 optional
1. **spacebar/enter**
   * 👎this ***does*** activate the menu button in BS4<sup>[[2]](https://getbootstrap.com/docs/4.1/components/dropdowns/#single-button)</sup>
   *  🗯WAI-ARIA1.1 requires space _and_ enter to "open the menu"<sup>[[3]](https://www.w3.org/TR/wai-aria-practices-1.1/#x3-15-menu-button)</sup>
1. **1st item gets focus on menu expand***
   * 👍 not a feature in BS4
   *  🗯WAI-ARIA1.1 "place focus on the first menu item"<sup>[[3]](https://www.w3.org/TR/wai-aria-practices-1.1/#x3-15-menu-button)</sup><sup>[[4]](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L446)</sup>

IMO **2** is a bug and  _must_ be supported in `reactstrap`. Actually any of the following keyCodes: `ESC`, `ENTER`, `SPACE`, `UP_ARROW`, `DOWN_ARROW` open the menu in BS4 (and only those keys). This behavior should be replicated as BS4.1 does this.

WAI ARIA requires either **1** or **2**, but BS4 fails this... what is the path to ARIA compliance here? (Same for **4**). Raise in BS4.x, wait for fix, replicate here?
