### ISSUE TITLE
Request) Add guide on theming components!

### ISSUE THREAD

**Issue by guledali** [reactstrap/reactstrap#1288]
Please an guide on how to customize reactstrap with styled components

![styled-button](https://user-images.githubusercontent.com/20647282/48211682-49e41600-e37a-11e8-89df-a5eab46bfaa5.png)

![import-styled](https://user-images.githubusercontent.com/20647282/48211697-52d4e780-e37a-11e8-83d8-62889ecc092c.png)

**Comment by TheSharpieOne** [comment]
reactstrap _mostly_ adds bootstrap classes to elements. bootstrap's CSS is what styles everything and bootstrap has a specific way to extends and implement themes.
http://getbootstrap.com/docs/4.1/getting-started/theming
http://getbootstrap.com/docs/4.1/extend/approach
http://getbootstrap.com/docs/4.1/getting-started/webpack/

styled-components shows how to style third-party components: https://www.styled-components.com/docs/basics#styling-any-components

There is nothing special you have to do to make any of this work with reactstrap.

**Comment by guledali** [comment]
@TheSharpieOne Yeah I know that you can style with regular classes the reason why I showcased styled components it that I believe in the CSSinJS and also some people use bootstrap to base their design-system and those images show how you could do that.

**Comment by eckdanny-osi** [comment]
@guledali i don't think what you're suggesting is advisable. 

You're overriding BS4's `btn-primary`,  a generated css class with one-off style defs for a particular component. You're foregoing the opportunity to pick new BS theme or customize one yourself (e.g. theming/extending). The BS4 design system is expressed in sass (not js), if you want to dial the _theme_ knobs, doing it there is best. 

There's no reason you _can't_ use css-in-js... but I think you'll run into challenges quickly given BS4's dependency on the cascade and sass-powered style system
