### ISSUE TITLE
<NavbarToggler> usage

### ISSUE THREAD

**Issue by rpassis** [reactstrap/reactstrap#129]
Hi there ,
Would it be possible to include a simple example on how to implement a collapsible `Navbar` component? I can see the `<NavbarToggler>` is available but haven't been able to make it work.
Many thanks,
Rog

**Comment by eddywashere** [comment]
Definitely need to add that. Thanks for reporting!

**Comment by Kepro** [comment]
@eddywashere i looking into code, and there is nothing about onClick or something, can you add some easy example here?

**Comment by eddywashere** [comment]
@Kepro @rpassis this is now documented thansk to @edgji in #216. thanks!
