### ISSUE TITLE
Neutrino incompatibility

### ISSUE THREAD

**Issue by pascollin** [reactstrap/reactstrap#1290]
### Issue description

- components: `all`
- reactstrap version `#6.5.0`
- react version `#16.6.1`

### Installing reactstrap isn't compatible with neutrino nodejs applications builder

After reactstrap installation, neutrino fresh installed application fails to start with this error message : 
> Error: Cannot find module '@neutrinojs/standardjs'

### What should be happening?

`npm start` should run webpack and serve the application

### Steps to reproduce issue

1. create a new fresh react application with neutrino (https://neutrinojs.org/packages/react/)
`npx @neutrinojs/create-project <directory-name>`
2. start the application
```
cd <directory-name>
npm start
```
=> The empty application is served locally
3. install reactstrap

> npm install reactstrap --save

4. start the application

> npm start

 (fails)

> Error: Cannot find module '@neutrinojs/standardjs'

### Error message in console

> > neutrino start
> 
> { Error: Cannot find module '@neutrinojs/standardjs'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:513:25)
>     at Module.require (internal/modules/cjs/loader.js:643:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at req (/usr/local/lib/node_modules/neutrino/src/utils.js:45:10)
>     at Api.require (/usr/local/lib/node_modules/neutrino/src/api.js:193:12)
>     at Api.use (/usr/local/lib/node_modules/neutrino/src/api.js:204:21)
>     at use (/usr/local/lib/node_modules/neutrino/src/api.js:246:27)
>     at _map (/usr/local/lib/node_modules/neutrino/node_modules/ramda/src/internal/_map.js:6:19)
>     at map (/usr/local/lib/node_modules/neutrino/node_modules/ramda/src/map.js:64:14) code: 'MODULE_NOT_FOUND' }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! react06@1.0.0 start: `neutrino start`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the react06@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Code

```
npx @neutrinojs/create-project demo-issue
cd demo-issue
npm start
```

> ctrl-c

```
npm install reactstrap
npm start
```
> Error: Cannot find module '@neutrinojs/standardjs'

**Comment by TheSharpieOne** [comment]
You might want to open an issue with neutrinojs or just use create-react-app instead of neutrinojs.
