### ISSUE TITLE
Roadmap to Stable Release

### ISSUE THREAD

**Issue by eddywashere** [reactstrap/reactstrap#13]
Some of these items include nested components, listing only top level sections.

- [x] Tables
- [x] Container
- [x] Row
- [x] Col
- [x] Button
- [x] ButtonGroup
- [x] ButtonDropdown
- [x] Dropdown
- [x] Modal
- [x] Popover
- [x] Tag
- [x] Card
- [x] Tooltip
- [x] Navbar
- [x] Nav
  - [ ] TabContent, TabPane
- [ ] Forms (In Progress)
- [ ] Jumbotron
- [ ] InputGroup
- [ ] Alert
- [ ] MediaObject
- [ ] Breadcrumb
- [ ] Pagination
- [ ] Progress
- [x] ListGroup
- [ ] Scrollspy
- [ ] Collapse
- [ ] Carousel
- [ ] Utilities
- [ ] Better Documentation for customizing component output with `tag` prop

Each component should have an individual issue to track status that contains the following

- any component names necessary
- propTypes for each component
- example react markup

**Comment by eddywashere** [comment]
Moving these to individual issues. I'd like to be able to sort these issues by reactions on the issue description. More 👍's by the community would hopefully mean a higher priority.

**Comment by sidekickstudio** [comment]
is there any example i can use about React Router with reactstrap?
thnks

**Comment by eddywashere** [comment]
@sidekickstudio a little late, but check out the docs, it uses react router and passes through `Link` to the `tag` prop of link components. ex: https://github.com/reactstrap/reactstrap/blob/f23a323f2903c8a3defb0add2d8490124bbd2cc0/docs/lib/UI/Nav.js#L12

**Comment by georgiosd** [comment]
No typeahead/autocomplete? :(

**Comment by TheSharpieOne** [comment]
@georgiosd this project aims to support what bootstrap itself supports and bootstrap doesn't support typeahead/autocomplete out of the box AFAIK.

**Comment by stevokk** [comment]
@georgiosd check out [react-autosuggest](https://github.com/moroshko/react-autosuggest) - I've got it up and running fairly easily, it uses AutoWhatever under the hood allowing you to theme it with bootstrap classes.

**Comment by cr101** [comment]
@stevokk  Does `react-autosuggest` work with non-hard-coded suggestions? As in, retrieving the suggestions from the database based the on user input?

**Comment by stevokk** [comment]
I load all my data to search on component mount as it is a small dataset, but I see no issue using the following to accomplish it:

```
  // Called by AutoSuggest on field change
  onChange(event, { newValue }) {
    this.setState({
      searchTerm: newValue
    });
  }

  // Autosuggest will call this function every time you need to update suggestions.
  // 
  onSuggestionsFetchRequested({ value }) {
    fetch(`${API_URL}/search?q=${this.state.searchTerm}`)
        .then((response) => this.setState({searchResults: response}));
  }
```

**Comment by cr101** [comment]
@stevokk I'd like to implement an instant search and that might work. Thanks

**Comment by error-yatish** [comment]
@eddywashere  i can't find 

> multi-selection-dropdown

 in **reactstrap**.... may i get this functionality using **reactstrap**??

**Comment by RohanDamani** [comment]
I see Row and Col, will there be a solution for Grid?

**Comment by TheSharpieOne** [comment]
@RohanDamani reactstrap support what bootstrap supports and [bootstrap says nope](https://github.com/twbs/bootstrap/issues/23057#issuecomment-315491199)

**Comment by joeldsouzax** [comment]
Hey, does this support bootstrap flex?

**Comment by TheSharpieOne** [comment]
It supports bootstrap layouts which use flexbox.
You can also add the flexbox utilities to components, but there currently is no utility props.

**Comment by AshishKapoor** [comment]
No responsive images?

**Comment by TheSharpieOne** [comment]
There is not special code/js for responsive images, just the css via a class. Since it is just the class and no variations there is no component for it. You just have to add className to your img tag. This is similar for utility type classes.

**Comment by Lug16** [comment]
Great tool. Any plans on "Scrollspy"?

**Comment by salilchhetri** [comment]
4.x introduced some breaking changes, you'll need to import Link from react-router-dom.
import { Link } from 'react-router-dom'

**Comment by dkati** [comment]
good evening ? any way to show charts (any kind of it) with reactstrap ?
cant find anything

**Comment by TheSharpieOne** [comment]
Bootstrap doesn't have charts so neither does reactstrap.

**Comment by elisechant** [comment]
Icons ?

**Comment by TheSharpieOne** [comment]
Bootstrap v4 doesn't have icons, it's a separate package. You can include them and use them the same was with reactstrap as you would with bootstrap.
