### ISSUE TITLE
Multiple Select in drop-down

### ISSUE THREAD

**Issue by dexter-skr** [reactstrap/reactstrap#1301]
Hi,
Is there a way I can do multiple select like this.,

When collapsed : 
![screen shot 2018-11-21 at 11 09 52](https://user-images.githubusercontent.com/26404869/48816694-22c81400-ed7e-11e8-87e7-ca392d91fd33.png)

When expanded:
![screen shot 2018-11-21 at 11 07 29](https://user-images.githubusercontent.com/26404869/48816629-e5638680-ed7d-11e8-9941-95dfea028f2c.png)

And after the selection / deselection of any item, the array state gets pushed / popped.
Due to space constraint , am not able to use the multi-select box.

**Comment by TheSharpieOne** [comment]
Bootstrap doesn't support the feature you are wanting so neither does reactstrap.

I would suggest looking at something like react-select which has something similar (though, by default the collapsed view lists the selected item, but it can be overridden in v2+)
