### ISSUE TITLE
Popover blurred on chrome

### ISSUE THREAD

**Issue by thomaxxl** [reactstrap/reactstrap#1303]
- components: `Popover`
- reactstrap version `#6.5.0`
- react version `#16.6.3`
- bootstrap version `#4.0.0-alpha.6`

### What is happening?

Popover content looks blurred on chrome.
This didn't happen before, only since a couple of weeks.

It doesn't look blurred on IE

### What should be happening?

Shouldn't look blurred

### Steps to reproduce issue

run the code below

### Error message in console

N/A

### Code
I created a new app with 
```
npx create-react-app my-app
npm i reactstrap
```
then App.jsx:

```javascript
import React from 'react';
import { Button, Popover, PopoverHeader, PopoverBody } from 'reactstrap';

export default class Example extends React.Component {
  constructor(props) {
    super(props);

    this.toggle = this.toggle.bind(this);
    this.state = {
      popoverOpen: false
    };
  }

  toggle() {
    this.setState({
      popoverOpen: !this.state.popoverOpen
    });
  }

  render() {
    return (
      <div>
        <Button id="Popover1" onClick={this.toggle}>
          Launch Popover
        </Button>
        <Popover placement="bottom" isOpen={this.state.popoverOpen} target="Popover1" toggle={this.toggle}>
          <PopoverHeader>Popover Title</PopoverHeader>
          <PopoverBody>Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</PopoverBody>
        </Popover>
      </div>
    );
  }
}
```

**Comment by TheSharpieOne** [comment]
The version of bootstrap you are using is not compatible with the version reactstrap you are using.

I am on Chrome and am not noticing a blur: https://stackblitz.com/edit/reactstrap-v6-m9xqj7?file=Example.js

**Comment by thomaxxl** [comment]
I guess you're right, your example isn't blurred, I haven't managed to resolve the problem but I guess that's not your problem :) thanks!

**Comment by polys** [comment]
This is still an issue, even with the latest `reactstrap@7.1.0` and `react@16.8.3` but only when you're zoomed in or out, or with High DPI enabled.

You can see the issue with @TheSharpieOne 's example or this fork https://reactstrap-v6-gj7hm6.stackblitz.io with the latest versions.

![image](https://user-images.githubusercontent.com/4301432/53285105-b8e05180-3754-11e9-82c1-2b9eda004706.png)

**Comment by TheSharpieOne** [comment]
I see a slight blur when zoomed in or out, but I am also noticing the same blur on bootstrap's docs which suggests this is an issue with the styles within bootstrap. I would recommend opening an issue with bootstrap (although, this may even be a browser related issue).

**Comment by papiro** [comment]
We have encountered this exact same issue and after debugging the css, I've determined that the cause is in Popper.js. It adds an inline-style with a `transform: translateZ()` which is causing the blurriness. Not sure why it needs the `translateZ` and not a `top`/`left` combo, but replacing it with `top`/`left` fixes it...
