### ISSUE TITLE
Module not found: Can't resolve 'bootstrap/dist/css/bootstrap.min.css' in

### ISSUE THREAD

**Issue by jasonfb** [reactstrap/reactstrap#1325]
I think I have an obscure "where to put things' #newbie question: in this package 

 it says "Import Bootstrap CSS in the src/index.js file:" import 'bootstrap/dist/css/bootstrap.min.css';      …

but when I do this I'm getting 

```
Module not found: Can't resolve 'bootstrap/dist/css/bootstrap.min.css' in '/Users/jason/Work/[XXX]/[xxx].com-front/client/src'
```

 even though I downloaded boostrap 4 and put the CSS files into this location — /client/src/bootstrap/dist/css/bootstrap.min.css

did a miss a step?  I don't understand why bootstrap.min.css is referenced but not explicitly added to the project in the setup instructions. 

my App.js file looks like

```
import React, { Component } from 'react';
import './App.css';
import 'bootstrap/dist/css/bootstrap.min.css';

import { Button } from 'reactstrap';

class App extends Component {
  state = {cities: []}
  async componentDidMount() {
    const response = await fetch('/cities')
    const cities   = await response.json()
    this.setState({cities: cities})
  }
  render() {
    return (
      <div>
        <header>

        </header>
        <Button color="danger">Danger!</Button>
        <ul>
        {this.state.cities.map( city => {
            return <li key={city.name}> <b>{city.name}</b>: {city.population}</li>
          })}
        </ul>
      </div>
  );
  }
}
export default App;
```

**Comment by TheSharpieOne** [comment]
`import 'bootstrap/dist/css/bootstrap.min.css';` is referencing the file from node_modules. You will need to `npm install bootstrap` to put it in your node_modules.

> even though I downloaded boostrap 4 and put the CSS files into this location — /client/src/bootstrap/dist/css/bootstrap.min.css

If this is the case, you can reference it with a relative path:
`import './bootstrap/dist/css/bootstrap.min.css';`

**Comment by youngheart12** [comment]
Hey jason try putting  'bootstrap/dist/css/bootstrap.min.css' in the index.js file 
in my case it had worked

**Comment by youngheart12** [comment]
hey @jasonfb  just install this **npm install --save bootstrap@^4.0.0-alpha.6  react-bootstrap@^0.32.1**
and add import './bootstap/dist/css/bootstrap.min.css' in the index.js
it will work fine
if you still having trouble you can reach me anytime

**Comment by TheSharpieOne** [comment]
@youngheart12 The versions of the things you are not compatible, you may experience  styling issues.

**Comment by jasonfb** [comment]
I generally use `yarn add` instead of `npm install`

this seems to have fixed the issue

```yarn add bootstrap```

after this I see that I was missing in my package.json `dependencies`
+    "bootstrap": "^4.2.1",


and also it looks like bootstrap@^4.2.1 got added to yarn.lock now also.

this seems to have cleared up the problem

**Comment by kannan007** [comment]
@youngheart12 Am still facing the issue if i import like this `import './bootstrap/dist/css/bootstrap.min.css';`

**Comment by GoPro16** [comment]
That comment is incorrect. Using `./` thinks its relative to the current directory and will not scan the node modules. You will need to use `bootstrap/dist/css/bootstrap.min.css` for it to look in the node modules directory for the package.

**Comment by GoPro16** [comment]
> hey @jasonfb just install this **npm install --save bootstrap@^4.0.0-alpha.6 react-bootstrap@^0.32.1**
> and add import 'bootstap/dist/css/bootstrap.min.css' in the index.js
> it will work fine
> if you still having trouble you can reach me anytime

I just updated their comment to make sure no one gets confused

**Comment by GennadySeleznev** [comment]
> `import 'bootstrap/dist/css/bootstrap.min.css';` is referencing the file from node_modules. You will need to `npm install bootstrap` to put it in your node_modules.
> 
> -OR-
> 
> > even though I downloaded boostrap 4 and put the CSS files into this location — /client/src/bootstrap/dist/css/bootstrap.min.css
> 
> If this is the case, you can reference it with a relative path:
> `import './bootstrap/dist/css/bootstrap.min.css';`

**Comment by LarryKarani** [comment]
I had the same issue  restarting the server after installing worked for me. LoL

**Comment by matanist** [comment]
`npm install --save bootstrap`  and try again

**Comment by GeorgeArgyrousis** [comment]
Having the `--save` flag did the trick for me. Ie `install --save bootstrap`.

**Comment by kami23** [comment]
I've faced the same problem and the solution which @TheSharpieOne offered in his first answer worked for me 
`npm install bootstrap`

**Comment by vedant11** [comment]
> Having the `--save` flag did the trick for me. Ie `install --save bootstrap`.

Might want to update npm then

**Comment by naftalib** [comment]
npm install bootstrap - worked for me

**Comment by rekhaanand94** [comment]
I installed bootstrap in node modules.. but its giving lot of warnings in my project..

**Comment by sholehap** [comment]
npm install bootstrap 

yes work for mee thank all

**Comment by LiNuX-Mallu** [comment]
> 
> 
> I think I have an obscure "where to put things' #newbie question: in this package
> 
> it says "Import Bootstrap CSS in the src/index.js file:" import 'bootstrap/dist/css/bootstrap.min.css'; …
> 
> but when I do this I'm getting
> 
> ```
> Module not found: Can't resolve 'bootstrap/dist/css/bootstrap.min.css' in '/Users/jason/Work/[XXX]/[xxx].com-front/client/src'
> ```
> 
> even though I downloaded boostrap 4 and put the CSS files into this location — /client/src/bootstrap/dist/css/bootstrap.min.css
> 
> did a miss a step? I don't understand why bootstrap.min.css is referenced but not explicitly added to the project in the setup instructions.
> 
> my App.js file looks like
> 
> ```
> import React, { Component } from 'react';
> import './App.css';
> import 'bootstrap/dist/css/bootstrap.min.css';
> 
> import { Button } from 'reactstrap';
> 
> class App extends Component {
>   state = {cities: []}
>   async componentDidMount() {
>     const response = await fetch('/cities')
>     const cities   = await response.json()
>     this.setState({cities: cities})
>   }
>   render() {
>     return (
>       <div>
>         <header>
> 
>         </header>
>         <Button color="danger">Danger!</Button>
>         <ul>
>         {this.state.cities.map( city => {
>             return <li key={city.name}> <b>{city.name}</b>: {city.population}</li>
>           })}
>         </ul>
>       </div>
>   );
>   }
> }
> export default App;
> ```

after $ npm install --save bootstrap@latest

just add 
import 'bootstrap' ;

now check by adding <div className="text-center"> 
this is the simple way

also add <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> in your index.html or it will not work .

if you are using router then you must import 'bootsrtap' in the router file that is enough
so you dont have have to import it in the component files .

import '../node-modules/bootstrap...... method wont work because CRA wont allow to import anything outside from src unless it is a package .

thank you .

**Comment by umerfarooq69** [comment]
Try this if you just want to simply import bootstrap like cmd
npm install --save bootstrap

**Comment by evearza** [comment]
does it work for react native?

**Comment by MiaLisen** [comment]
For me, updating the version of bootstrap in package.json from "^2.0.0" to "^5.1.3" and the running npm install again did the trick. *shrug*

**Comment by Divesh381** [comment]
**** ### Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\ABHI_MOIRYA\Desktop\ecommProje\frontend\src\bootstrap.min.css.map' file: Error: ENOENT: no such file or directory, 

I got the same problem and this is how I resolved the problem. 
All methods are tried but do not work for anyone finally the last method worked

_**import '../node_modules/bootstrap/dist/css/bootstrap.min.css';**_

**Comment by Abhayshah020** [comment]
> I think I have an obscure "where to put things' #newbie question: in this package
> 
> it says "Import Bootstrap CSS in the src/index.js file:" import 'bootstrap/dist/css/bootstrap.min.css'; …
> 
> but when I do this I'm getting
> 
> ```
> Module not found: Can't resolve 'bootstrap/dist/css/bootstrap.min.css' in '/Users/jason/Work/[XXX]/[xxx].com-front/client/src'
> ```
> 
> even though I downloaded boostrap 4 and put the CSS files into this location — /client/src/bootstrap/dist/css/bootstrap.min.css
> 
> did a miss a step? I don't understand why bootstrap.min.css is referenced but not explicitly added to the project in the setup instructions.
> 
> my App.js file looks like
> 
> ```
> import React, { Component } from 'react';
> import './App.css';
> import 'bootstrap/dist/css/bootstrap.min.css';
> 
> import { Button } from 'reactstrap';
> 
> class App extends Component {
>   state = {cities: []}
>   async componentDidMount() {
>     const response = await fetch('/cities')
>     const cities   = await response.json()
>     this.setState({cities: cities})
>   }
>   render() {
>     return (
>       <div>
>         <header>
> 
>         </header>
>         <Button color="danger">Danger!</Button>
>         <ul>
>         {this.state.cities.map( city => {
>             return <li key={city.name}> <b>{city.name}</b>: {city.population}</li>
>           })}
>         </ul>
>       </div>
>   );
>   }
> }
> export default App;
> ```For This error or any of this error lke:"ERROR in ./node_modules/bootstrap/dist/css/bootstrap.min.css (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/bootstrap/dist/css/bootstrap.min.css)" you could atleast try to remove the node-sass package `npm r node-sass` and install package sass `npm i sass` , Hopefully this will work! :)

**Comment by Abhayshah020** [comment]
ERROR in ./node_modules/bootstrap/dist/css/bootstrap.min.css (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/bootstrap/dist/css/bootstrap.min.css)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: property "url" must be followed by a ':'
        on line 5 of node_modules/bootstrap/dist/css/bootstrap.min.css
>> 2))}.form-select{--bs-form-select-bg-img:url("data:image/svg+xml,%3csvg x
   ------------------------------------------^

 @ ./node_modules/bootstrap/dist/css/bootstrap.min.css 2:12-121 9:17-24 13:7-14 45:20-27 47:4-60:5 49:6-59:7 50:38-45 56:26-33 58:21-28 68:15-22
 @ ./index.tsx
 
 To solve this issue you could try to uninstall node-sass package and install sass package, 
 try this code :
 npm r node-sass
 npm i sass
 
 //Make sure you have node version 14
