### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by amiuhle** [reactstrap/reactstrap#1338]
Are you planning on releasing a new version anytime soon?

Happy holidays!

**Comment by weisssean** [comment]
toastr.js no longer works with bootstrap 4. Can you create a new version with bootstrap toast?

**Comment by TheSharpieOne** [comment]
The next release is already set to be a breaking change. I would love to get forwardRefs into it, else we'll have to make another major version bump when that goes in.

**Comment by weisssean** [comment]
there's actually a quick fix so no worries:
[https://github.com/CodeSeven/toastr/issues/599](toastr)

**Comment by weisssean** [comment]
There's actually a quick fix so no worries.
[toastr fix](https://github.com/CodeSeven/toastr/issues/599)

**Comment by amiuhle** [comment]
@TheSharpieOne Can you just do a `6.5.1` with what's currently on master since `6.5.0`?

I would install via git URL, but that doesn't work because the built code is not in the repository. Maybe it's possible to deploy the package to GH Pages via CI build or something?

**Comment by TheSharpieOne** [comment]
master already has breaking changes making the next release `7.0.0`.
