### ISSUE TITLE
Support backward-compatible popover behavior

### ISSUE THREAD

**Issue by FelixHenninger** [reactstrap/reactstrap#1349]
- components: `Popover`
- reactstrap version `#7.0.x`
- import method `es`
- react version `#16.4.1`
- bootstrap version `#16.4.1`

### What is happening?

In earlier versions, popovers were dismissed if users clicked outside of the current popover (but not if the click was inside the popover). With the new version, popovers are either dismissed manually via their toggle (`trigger="click"`) or on the next click (with `trigger="focus"`), wherever it lands (even if on the popover itself).

### What should be happening?

This behavior appears to match the [bootstrap defaults](https://getbootstrap.com/docs/4.2/components/popovers/#dismiss-on-next-click), therefore I'm guessing that it is consistent. Thus, this is probably not a bug as much as a humble request for pointers or hints toward a backwards-compatible solution.

### Steps to reproduce issue

The changes are visible when comparing versions [6.5.0](https://reactstrap-ewpznv.stackblitz.io/) ([code](https://stackblitz.com/edit/reactstrap-ewpznv?file=Example.js)) and [7.0.2](https://reactstrap-vgbr1w.stackblitz.io/) ([code](https://stackblitz.com/edit/reactstrap-vgbr1w?file=Example.js)) by clicking on multiple popover toggles in sequence.
In the first case, only one popover is visible at a time, while in the second, several popovers compete for screen estate.

### Error message in console

(none)

### Code

(see above)

----

Thanks so much for your effort with this library! I've found it a joy to work with, and would like to apologize for reporting a semi-issue here. I'm guessing that I've missed a flag I should be setting, and would be happy to extend the documentation if that helps. Sorry for the trouble, and thanks in advance for your help!

**Comment by TheSharpieOne** [comment]
Yes, these changes were made to be consistent with bootstrap, but I do see that the previous behavior was also desired. Also, some how that commit message got lost and the breaking change was not included on the list in the change log making this even more problematic.
`trigger="focus"` was suppose to mimic what was previously there, but it still doesn't allow you to click on the popover as the button/triggering element would lose focus.

I think it would be a good thing to bring back as an opt-in (maybe via another trigger value (not sure what to call it, please suggest) or a prop in combination with the "focus" trigger).

**Comment by septs** [comment]
```html
trigger="classic"
```

The is `reactstrap@6` classic behavior.

**Comment by kinke** [comment]
We've also been hit by this - there was no `trigger` prop for the old Popover, the new one defaults to `click` -> manually showing the Popover upon focusing the target element via a click now immediately hides it again.

So I tried to work around it in our parent component (a textbox, showing a date/daterange picker as popover):
```JS
  inputRef = React.createRef<HTMLInputElement>();

  render = () => (
    <>
      <input ref={this.inputRef} ... />
      <Popover trigger="manual" innerRef={this.popoverRef} ... />;
    </>
  );

  _popover: ?HTMLElement = null;

  popoverRef = (popover: ?HTMLElement) => {
    this._popover = popover;
    if (popover) {
      ['click', 'touchstart'].forEach(event =>
        document.addEventListener(event, this.handleDocumentClick, true)
      );
    } else {
      ['click', 'touchstart'].forEach(event =>
        document.removeEventListener(event, this.handleDocumentClick, true)
      );
    }
  }

  handleDocumentClick = (e: Object) => {
    const input = this.inputRef.current;
    const popover = this._popover;
    if (input && popover && e.target !== input && !input.contains(e.target) && e.target !== popover && !popover.contains(e.target))
      this.props.toggle();
  }
```

This almost works, but shows a second issue - if the parent component is in a `Modal`, a click inside the popover now hides the modal. I guess this is due to the new portal; the old Popover also mounted itself at the end of `<body>` though.

**Comment by kinke** [comment]
I'd suggest something like an `interactive` prop for new `TooltipPopoverWrapper`, controlling whether clicks inside itself hide it (`interactive={false}`) or not (`interactive={true}`); it may be useful for tooltips too.

Having to specify `trigger="manual" manually as breaking change with v7 would be okay for me, as long as it's in the release notes somewhere. I'm not sure whether that should control the don't-hide-on-target-click too or whether we'd need an extra prop for that.

As to the portal issue, I haven't checked yet how that worked before.

**Comment by kinke** [comment]
Portal issue: #1358

**Comment by kinke** [comment]
Proposal: https://github.com/reactstrap/reactstrap/pull/1360

**Comment by cwacek** [comment]
I think this got broken again by 6b3c3ce. I cannot find any combination of triggers that will allow me to put a `Button` inside a popover and click on it without closing the `Popover`.

**Comment by TheSharpieOne** [comment]
@cwacek Here are two examples of how to put a button in a popover and click on it without closing the popover:
https://stackblitz.com/edit/reactstrap-v7-yrmjst?file=Example.js

```jsx
import React, { Component, useState } from 'react';
import { Button, Popover, PopoverHeader, PopoverBody } from 'reactstrap';

const Example = () => {
  const [is1Open, toggle1] = useState(false);
  const [is2Open, toggle2] = useState(false);
  return (
    <div>
      <Button id="Popover1" type="button">
        Launch Popover
        </Button>
      <Popover placement="bottom" isOpen={is1Open} target="Popover1" toggle={() => toggle1(!is1Open)}>
        <PopoverHeader>Popover Title</PopoverHeader>
        <PopoverBody>Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.
        <Button onClick={console.log.bind(console)}>Click It</Button></PopoverBody>
      </Popover>
      <Button id="Popover2" type="button">
        Launch Popover
        </Button>
      <Popover trigger="legacy" placement="bottom" isOpen={is2Open} target="Popover2" toggle={() => toggle2(!is2Open)}>
        <PopoverHeader>Popover Title</PopoverHeader>
        <PopoverBody>Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.
        <Button onClick={console.log.bind(console)}>Click It</Button></PopoverBody>
      </Popover>
    </div>
  )
};

export default Example;
```

**Comment by pkg01** [comment]
How do I put a button on popover and close the popover on button click? When I use `focus` button click is not triggered. When I use legacy popover is not closed on button click.

**Comment by tahv0** [comment]
"legacy" trigger is awesome. @TheSharpieOne 's example is the solution. Thanks :)

**Comment by BiswaViraj** [comment]
> How do I put a button on popover and close the popover on button click? When I use **focus** button click is not triggered. When I use **legacy** popover is not closed on button click.
> When I use **legacy** and call toggle on button click it calls the toggle again and opens the popover again.

did you find any solution to this?

**Comment by TheSharpieOne** [comment]
You can use manual and set `isOpen` to `true` (or actually toggle the current value) when clicking the trigger. You can set `isOpen` to `false` when the button within the popover is clicked.
You also could use trigger=click and set `isOpen` to `false` when the button within the popover is clicked.
