### ISSUE TITLE
Add innerRef to ListGroupItem

### ISSUE THREAD

**Issue by hector** [reactstrap/reactstrap#1354]
Please add an innerRef to ListGroupItem.
I am using it with react-pose animations and you need to pass the reference to the internal "li" element.

On the other hand it might be interesting to use [React.forwardRef](https://reactjs.org/docs/forwarding-refs.html) instead of innerRef, but this would be a change affecting all the library and it is out of the scope of this issue.

**Comment by GoPro16** [comment]
duplicate of #1082
