### ISSUE TITLE
How to have vertical tab content

### ISSUE THREAD

**Issue by eeriee** [reactstrap/reactstrap#1357]
- components: `TabContent, TabPane, Nav`
- reactstrap version `#7.0.2`
- react version `#16.7.0`
- bootstrap version `#4.2.1`

### What is happening?

`Nav` has a `vertical` prop, but the `TabContent` cannot be vertical.

### What should be happening?

How can i make it like the vertical tabs in https://getbootstrap.com/docs/4.2/components/navs/#javascript-behavior ?

### Code

          export default class Navigation extends React.Component {
          constructor(props) {
            super(props);

            this.toggle = this.toggle.bind(this);
            this.state = {
              activeTab: '1'
            };
          }

          toggle(tab) {
            if (this.state.activeTab !== tab) {
              this.setState({
                activeTab: tab
              });
            }
          }

          render() {
            return (
              <div>
                <Nav tabs vertical>
                  <NavItem>
                    <NavLink
                      className={classnames({active: this.state.activeTab === '1'})}
                      onClick={() => {
                        this.toggle('1');
                      }}
                    >
                      Tab1
                    </NavLink>
                  </NavItem>
                  <NavItem>
                    <NavLink
                      className={classnames({active: this.state.activeTab === '2'})}
                      onClick={() => {
                        this.toggle('2');
                      }}
                    >
                      Moar Tabs
                    </NavLink>
                  </NavItem>
                </Nav>
                <TabContent activeTab={this.state.activeTab}>
                  <TabPane tabId="1">
                    <Row>
                      <Col sm="12">
                        <h4>Tab 1 Contents</h4>
                      </Col>
                    </Row>
                  </TabPane>
                  <TabPane tabId="2">
                    <Row>
                      <Col sm="12">
                        <h4>Tab 2 Contents</h4>
                      </Col>
                    </Row>
                  </TabPane>
                </TabContent>
              </div>
            )
          }
        };

**Comment by gergely-nagy** [comment]
Here is a basic example. Hope this helps!
https://stackblitz.com/edit/reactstrap-1357?embed=1&file=Example.js

**Comment by TheSharpieOne** [comment]
bootstrap itself only support vertical pills and thus reactstrap only supports that as well. The library you linked brings in custom styles, no code/javascript. Reactstrap doesn't include any CSS, all of the CSS comes from bootstrap itself.
