### ISSUE TITLE
CustomInput label only accepts string

### ISSUE THREAD

**Issue by bhaskar-shrestha** [reactstrap/reactstrap#1362]
- components: CustomInput checkbox
- reactstrap version `^6.5.0`
- import method `umd/csj/es`  es
- react version `^16.6.3`
- bootstrap version `^4.2.1`

### What is happening?

CustomInput label is PropTypes.string

### What should be happening?

label should be PropTypes.node

### Steps to reproduce issue

My requirement is to have a red * to show it is a required field and unfortunately it breaks into 2 lines. The * has a different style and is in a <span/> of its own.

**Comment by changLiuUNSW** [comment]
We have similar requirement where we need to customize the label eg: add an image

**Comment by juanmiguelbesada** [comment]
This issue is already fixed and should be closed

https://github.com/reactstrap/reactstrap/blob/ad2a9a0101c838831f31a932a32cb37d3316c153/src/CustomInput.js#L10
