### ISSUE TITLE
Spinner is not exported from 'reactstrap'

### ISSUE THREAD

**Issue by juan-carlos-correa** [reactstrap/reactstrap#1366]
- components: `Spinner`
- reactstrap version `7.0.2 `
- import method `umd/csj/es` 
- react version `6.7.0`
- bootstrap version `4.2.1`

### What is happening?

I do

`import { Spinner } from 'reactstrap';`

and use it in render method like

`<Spinner color="primary" />`
according to the doc https://reactstrap.github.io/components/spinners/

### What should be happening?

I expected view the Spinner component.

I checked node_modules/reactstrap/src/index.js but Spinner is not exported.

### Steps to reproduce issue

1. setup reactstrap
2. in any component, do `import { Spinner } from 'reactstrap';`

### Error message in console

```
./src/Auth/Components/SignupForm.js
Attempted import error: 'Spinner' is not exported from 'reactstrap'.
```

### Code
`import { Spinner } from 'reactstrap';`

**Comment by gergely-nagy** [comment]
It hasn't been released yet.
The documentation runs ahead of the releases.
https://github.com/reactstrap/reactstrap/issues/1361#issuecomment-453154819

**Comment by gergely-nagy** [comment]
released in [7.1.0](https://github.com/reactstrap/reactstrap/releases/tag/7.1.0)

**Comment by Toyurc** [comment]
Hi @gergely-nagy ,  I just updated my reactstrap to 7.1.0 and I am still getting the error about Spinner not being exported

**Comment by gergely-nagy** [comment]
It works fine for me.
@Toyurc  try to reinstall your dependencies!
`rm -rf node_modules && npm i`

Here is a basic example. Hope this helps!  
https://stackblitz.com/edit/reactstrap-1366?file=Example.js

**Comment by tmhn** [comment]
I'm having a similar issue. Looking at the `node_modules/reactstrap/src/index.js` file, the Spinner is exported and it can be required into my app without issue from Webpack. When I try to view the page in Chrome and looking at the Dev Tools, it shows that there is markup there, however, the CSS for the spinner isn't present like it is when viewing the Dev Tools for the Reactstrap docs site. I've imported the bootstrap minified CSS file at the root of my app, so I'm not too sure what the issue is?
<img width="616" alt="screen shot 2019-01-29 at 19 56 16" src="https://user-images.githubusercontent.com/6421923/51936403-05f43080-2400-11e9-9a33-2eeac0559f34.png">

**Comment by gergely-nagy** [comment]
@tmhn which Bootstrap version are you using?
Spinners was added since [v4.2.0](https://github.com/twbs/bootstrap/issues/26952)!

**Comment by tmhn** [comment]
@gergely-nagy That was it, thanks!

**Comment by julienjules** [comment]
Hi there!
I face the same issue!
I reinstalled my dependencies as @gergely-nagy advise but the spinner doesn't still appear!
My reactstrap version "7.1.0"

**Comment by julienjules** [comment]
Soleds

> Hi there!
> I face the same issue!
> I reinstalled my dependencies as @gergely-nagy advise but the spinner doesn't still appear!
> My reactstrap version "7.1.0"

Solved by running commands:
`npm install bootstrap --save`
`npm install --save reactstrap react react-dom`
and then `npm audit fix --force`

**Comment by andresebr** [comment]
Still no luck using reactstrap v.8.0.0 and bootstrap v.4.3.1. I'm having a similar issue with **UncontrolledCollapse** 😕

**Comment by TheSharpieOne** [comment]
check the output of `npm ls reactstrap`

**Comment by andresebr** [comment]
![image](https://user-images.githubusercontent.com/7132215/58984797-81476380-879f-11e9-836d-8bbf62189fac.png)

**Comment by TheSharpieOne** [comment]
🤷‍♂ https://stackblitz.com/edit/reactstrap-v8-1kmzbs?file=Example.js

**Comment by ndanielsen** [comment]
Upgrading to "bootstrap": "4.3.1" solved this for me

**Comment by ishwarchandratiwari** [comment]
> @tmhn which Bootstrap version are you using?
> Spinners was added since [v4.2.0](https://github.com/twbs/bootstrap/issues/26952)!



> @tmhn which Bootstrap version are you using?
> Spinners was added since [v4.2.0](https://github.com/twbs/bootstrap/issues/26952)!

Thanx you saved my day

**Comment by Saibamen** [comment]
Spinner not include _spinners.scss https://github.com/reactstrap/reactstrap/issues/1651

**Comment by sovp-89** [comment]
Hi, I have the same problem, the spinner gets render but is not showing, I have reactstrap@8.9.0 and bootsrap@4.6.0 installed, does anyone know how to solve it?
