### ISSUE TITLE
How to use col-md-* or something similar

### ISSUE THREAD

**Issue by kingingcole** [reactstrap/reactstrap#1372]
I can only see usage for Col component. How do I use col-md- classes in them?

**Comment by TheSharpieOne** [comment]
http://reactstrap.github.io/components/layout/

```jsx
<Col md={6}>has class="col-md-6"</Col>
<Col md="6">also has class="col-md-6"</Col>
<Col md={{ size: 6, offset: 3 }}>has class="col-md-6" offset-md-3</Col>
```

**Comment by fengxiaoyue** [comment]
You can also do

```<div className="col-md-6">This is the same as the above methods, but far less intuitive. </div>```
