### ISSUE TITLE
question: how to use bootstrap spacing 

### ISSUE THREAD

**Issue by npomfret** [reactstrap/reactstrap#1375]
What's the syntax to add bootstrap [spacing](https://getbootstrap.com/docs/4.1/utilities/spacing/) to a component.  For example, in _pure_ bootstrap I could use `class="ml-1"` to add a left margin of size 1.

[edit] apologies, guess this is a duplicate of https://github.com/reactstrap/reactstrap/issues/1372

**Comment by TheSharpieOne** [comment]
It is similar for reactstrap: `className="ml-1"`

This comes from #81
