### ISSUE TITLE
Controlled popover with buttons interfered by legacy behavior

### ISSUE THREAD

**Issue by lxcid** [reactstrap/reactstrap#1388]
- components: `Popover`
- reactstrap version `#7.1.0`
- import method `es`
- react version `#16.6.0`
- bootstrap version `#4.2.1`

### What is happening?

If I have controlled popover with its trigger set to `legacy` and try to add the dismiss button (that toggled the `isOpen` state), `showWithDelay()` get trigged by `handleDocumentClick()`.

https://github.com/reactstrap/reactstrap/blob/ee15c869ec955c70ef84618aec70bf2d15935bad/src/TooltipPopoverWrapper.js#L195-L206

Because this is delayed, it get executed after we already manually toggled ourselves. `e.preventDefault()` or `e.stopPropagation()` doesn't work because `useCapture` is set to true thus overriding the normal event bubbling steps…

https://github.com/reactstrap/reactstrap/blob/ee15c869ec955c70ef84618aec70bf2d15935bad/src/TooltipPopoverWrapper.js#L226

This behavior cause the popover to get reopened.

### What should be happening?

Legacy popover should work with controlled component with buttons in the popover body.

**Comment by lxcid** [comment]
My solution is to access the ref of `TooltipPopoverWrapper` and call `clearShowTimeout()`.

It was inconvenience that we can't access `TooltipPopoverWrapper` ref from `Popover` (which just wrap it around)

I end up with something like this:

```js
const Popover = React.forwardRef((props, ref) => {
  const { className, innerClassName } = props;
  const popperClasses = classNames('popover', 'show', className);

  const classes = classNames('popover-inner', innerClassName);

  return (
    <TooltipPopoverWrapper
      {...props}
      ref={ref}
      className={popperClasses}
      innerClassName={classes}
    />
  );
});
```

Note that the code only work for v7.1.0

**Comment by TheSharpieOne** [comment]
We should probably check if the popover is already open before setting the delay to open it.

**Comment by oneinchman** [comment]
In PR #1426 I can see that you check this. However, when I install the latest version (7.1.0) i still get the [old code](https://github.com/reactstrap/reactstrap/blob/e341137285bae23ec4917cc26314adaaa9d12c92/src/TooltipPopoverWrapper.js#L189)

I tried installing with reactstrap@next. When I referenced the PR in package.json using `reactstrap/reactstrap#pull/1426/head` i get the new code but then the src folder is empty.
