### ISSUE TITLE
No animation on modal in firefox

### ISSUE THREAD

**Issue by codefln** [reactstrap/reactstrap#1389]
- components: `Modal`
- reactstrap version `#7.1.0`
- import method `es`
- react version `#16.7.0`
- bootstrap version `#4.1.0`

How to reproduce?
https://reactstrap.github.io/components/modals/
I will call any modal window. I will not see the animation (Firefox, Safari), but not Chrome. Chrome is fine.

**Comment by Neztore** [comment]
Using Firefox `64.0.2` and cannot reproduce this issue. All animations work fine for me on the Reactstrap modal page.

**Comment by codefln** [comment]
> Using Firefox `64.0.2` and cannot reproduce this issue. All animations work fine for me on the Reactstrap modal page.

Windows or Mac ?

**Comment by EndiM** [comment]
Same here, can't reproduce it..

OS: `Windows 10`
Firefox version: `64.0.2` and `65.0`
Chrome version: `72.0.3626.81`

OS: `macOS Mojave 10.14.2`
Chrome version: `71.0.3578.98`
Firefox version: `64.0.2`
Safari version: `12.0.2`

**Comment by gergely-nagy** [comment]
@codefln Maybe you have  `Reduce motion` enabled? Try to turn it off on your System Preferences.
![50064950-e66fb400-0181-11e9-894e-4aff9f1fffdc](https://user-images.githubusercontent.com/28930292/52124448-7e8a0580-2629-11e9-8a9e-1eb5517f4abd.png)

**Comment by codefln** [comment]
> @codefln Maybe you have `Reduce motion` enabled? Try to turn it off on your System Preferences.
> ![50064950-e66fb400-0181-11e9-894e-4aff9f1fffdc](https://user-images.githubusercontent.com/28930292/52124448-7e8a0580-2629-11e9-8a9e-1eb5517f4abd.png)

Yes it is because of the included function to "Reduce motion". But why did it work in chrome?

**Comment by gergely-nagy** [comment]
I don't know! Seems like this isn't a reactstrap issue and more so a Google Chrome choice that they doesn't support this feature yet.

**Comment by codefln** [comment]
> I don't know! Seems like this isn't a reactstrap issue and more so a Google Chrome choice that they doesn't support this feature yet.

In the classic bootstrap, this is no problem. Only in reactstrap
