### ISSUE TITLE
Dynamic Tabs

### ISSUE THREAD

**Issue by ukiyakimura** [reactstrap/reactstrap#139]
**Issue description**

I tried to create a dynamic tabs using map function,

my code look like this 
```
constructor(props) {
        super(props);

        this.toggle = this.toggle.bind(this);
        this.state = {
            activeTab: '1'
        };
    }

    toggle(tab) {
        if (this.state.activeTab !== tab) {
            this.setState({
                activeTab: tab.i
            });
        }
    }

    render() {
        return (
            <div>
                <Nav tabs>
                    {this.props.SetupTabTitles.map((data, i) =>
                        <NavItem>
                            <NavLink className={classnames({ active: this.state.activeTab === {i}} )} onClick={() => {this.toggle({i}); }} key={i}>
                                {data.tabTitles}
                            </NavLink>
                        </NavItem>
                    )}
                </Nav>

                <TabContent activeTab={this.state.activeTab}>
                    {this.props.SetupTabTitles.map(function(data, i) {
                        if(data.tabTitles == 'Position'){
                            return (
                                <TabPane tabId={i} key={i}>
                                    test1
                                </TabPane>
                            )
                        }else if(data.tabTitles == 'Periodic'){
                            return (
                                <TabPane tabId={i} key={i}>
                                    <PeriodicSetup />
                                </TabPane>
                            )
                        }
                    })}
                </TabContent>
            </div>
        );
    }
```

It works, but it has issues with the appearance, the tabs didn't show or indicate which tab is active.

- version #3.1.0
- components: Modal

**Comment by ajainarayanan** [comment]
@ukiyakimura Not sure if you have tried this,
#### Existing Code:
```
toggle(tab) {
        if (this.state.activeTab !== tab) {
            this.setState({
                activeTab: tab.i
            });
        }
    }
```
#### Fix:
```
toggle(tab) {
        if (this.state.activeTab !== tab.i) {
            this.setState({
                activeTab: tab.i
            });
        }
    }
```

You seem to be comparing `activeTab` with `tab` which is incorrect I believe. Please check the documentation for [Tabs here](https://reactstrap.github.io/components/tabs/)

**Comment by ukiyakimura** [comment]
@ajainarayanan i already try it. it has same result. if i put away "i" in activeTab: tab.i 
My tabContent wouldn't appear.

**Comment by ajainarayanan** [comment]
@ukiyakimura I see. One thing I could notice is your initial state has the activeTab as `'1'` (string) whereas the subsequent activeTab you set are `1` (number). It would be helpful if you could create a codepen example demo'ing your usecase.

**Comment by ukiyakimura** [comment]
@ajainarayanan i notice that too. i think that's the problem.  but i don't know how to create incremental number in string.

**Comment by ajainarayanan** [comment]
@ukiyakimura I am sorry to say but this is not the forum to discuss this problem. Github issues are supposed to be for filing issues on specific components in the project. I am not sure if this an issue with reactstrap per se.

**Comment by TheSharpieOne** [comment]
Demo of dynamic tabs: http://www.webpackbin.com/EksVPHG3-

**Comment by TheSharpieOne** [comment]
I would say the demo I posted shows that dynamic tabs are possible and do work, so there is no defect with reactstrap. @ukiyakimura if this answers your question / solves your problem, please close the issue.

**Comment by eddywashere** [comment]
Going to go ahead and close this. If there is a more specific example, please create a codepen or modify the working webpackbin from @TheSharpieOne. Thanks!

**Comment by pplonski** [comment]
There is nice example how dynamic tabs can be created: https://github.com/bmhaskar/dynamic-reactstrap-tabs
