### ISSUE TITLE
Switch needs appearance styling

### ISSUE THREAD

**Issue by gwhenne** [reactstrap/reactstrap#1393]
Currently, the checkbox in Switch only appears in the default blue style.

It should have classes which set the color to the standard list (primary, secondary, success, info etc.)

**Comment by nwalters512** [comment]
This seems outside the scope of reactstrap, as Bootstrap itself doesn't expose that ability: https://getbootstrap.com/docs/4.2/components/forms/#switches

**Comment by gwhenne** [comment]
Agreed - I meant to post this there.
