### ISSUE TITLE
Integrate React Hooks in the next release

### ISSUE THREAD

**Issue by JaffParker** [reactstrap/reactstrap#1396]
I've started to play around with React Hooks and since it's a way to share state logic between components, it could eliminate a few aspects that are a bit annoying with using Reactstrap. For example, here's what you could ship with the `Modal` component:

```js
import { useState } from 'react'

export function useModalState(defaultOpen = false) {
  const [ isOpen, setOpen ] = useState(defaultOpen);
  return { isOpen, toggle: () => setOpen(isOpen => !isOpen) };
}
```

Then that's what becomes with usage (edited the example from the site): 

```jsx
import React from 'react';
import { Button, Modal, ModalHeader, ModalBody, ModalFooter, useModalState } from 'reactstrap';

export default function ModalExample({buttonLabel, className}) {
  const { isOpen, toggle } = useModalState();
  
  return (
    <div>
      <Button color="danger" onClick={toggle}>{buttonLabel}</Button>
      <Modal isOpen={isOpen} toggle={toggle} className={className}>
        <ModalHeader toggle={toggle}>Modal title</ModalHeader>
        <ModalBody>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </ModalBody>
        <ModalFooter>
          <Button color="primary" onClick={toggle}>Do Something</Button>{' '}
          <Button color="secondary" onClick={toggle}>Cancel</Button>
        </ModalFooter>
      </Modal>
    </div>
  );
}
```

Another example, tabs:

```js
export function useTabsState(defaultTab = '1') {
  const [ activeTab, setActiveTab ] = useState(defaultTab);
  return {
    activeTab,
    switchToTab: tab =>
      activeTab !== tab && setActiveTab(tab)
  };
}
```

```jsx
import React from 'react';
import { TabContent, TabPane, Nav, NavItem, NavLink, Card, Button, CardTitle, CardText, Row, Col, useTabsState } from 'reactstrap';
import classnames from 'classnames';

export default function Example() {
  const { activeTab, switchToTab } = useTabsState();

  return (
    <div>
      <Nav tabs>
        <NavItem>
          <NavLink
            className={classnames({ active: activeTab === '1' })}
            onClick={() => { switchToTab('1'); }}
          >
            Tab1
          </NavLink>
        </NavItem>
        <NavItem>
          <NavLink
            className={classnames({ active: activeTab === '2' })}
            onClick={() => { switchToTab('2'); }}
          >
            Moar Tabs
          </NavLink>
        </NavItem>
      </Nav>
      <TabContent activeTab={activeTab}>
        <TabPane tabId="1">
          <Row>
            <Col sm="12">
              <h4>Tab 1 Contents</h4>
            </Col>
          </Row>
        </TabPane>
        <TabPane tabId="2">
          <Row>
            <Col sm="6">
              <Card body>
                <CardTitle>Special Title Treatment</CardTitle>
                <CardText>With supporting text below as a natural lead-in to additional content.</CardText>
                <Button>Go somewhere</Button>
              </Card>
            </Col>
            <Col sm="6">
              <Card body>
                <CardTitle>Special Title Treatment</CardTitle>
                <CardText>With supporting text below as a natural lead-in to additional content.</CardText>
                <Button>Go somewhere</Button>
              </Card>
            </Col>
          </Row>
        </TabPane>
      </TabContent>
    </div>
  );
}
```

The examples might not look too different, but the biggest difference (and really why hooks were created) is that we wouldn't have to re-create modal and tabs state classes every time we use one.

I could take time and make the pull request. Basically, I would just create hooks for the components that have classes in their examples in the docs. The only thing, those won't be able to be shipped until hooks go live, but that is not too far off, so you wanna be prepared :)

**Comment by TheSharpieOne** [comment]
State for the most part has left in user-land. The hooks are mention are not really specific to any of the components within reactstrap. For instance, the `useModalState` is just a boolean/toggle hook which can be found in several hook libs ([kitze/react-hanger](https://github.com/kitze/react-hanger#useboolean), [zakariaharti/react-hookedup](https://github.com/zakariaharti/react-hookedup#useBoolean), and [beizhedenglong/react-hooks-lib](https://github.com/beizhedenglong/react-hooks-lib#useToggleInitial) just to name a few). They can easily be used as is without having to add code to reactstrap.

We can for sure enhance the docs to showcase hooks being used to manage state, but other than that, I don't think we really need to make any changes.

I know a few of the components (such as the Uncontrolled components) keep state internally to make it easier for the basic/common control cases, maybe we can utilize some of the third-party libs mentioned above to bring in hooks there.

**Comment by madlemur** [comment]
I believe JaffParker was talking about using the hooks that are actually part of React (as of 16.8), not third-party libraries. But I also see what you're talking about as far as not codifying how to manage state in the components. It would be good to add in some examples of how to use the new React hooks to manage state for some of the components as an alternative to always creating a new class. At least show how to use the tools provided in the React toolbox.

**Comment by GoPro16** [comment]
Closing this as the docs have been updated with hooks for examples. Any state handling should be left up to the user and this library is not a hooks helper library
