### ISSUE TITLE
FilePicker in Dropdown

### ISSUE THREAD

**Issue by pReya** [reactstrap/reactstrap#1403]
Hey everyone,

I'm trying to create a reusable FilePicker component, that I can wrap around other components. Therefore it uses a hidden `<input>`. The code for my FilePicker looks like this:

```javascript
class SingleFileInput extends React.Component {
  constructor(props) {
    super(props);
    this.fileInput = React.createRef();
  }

  handleSubmit = event => {
    const { onSelectFile } = this.props;
    event.preventDefault();
    onSelectFile(this.fileInput.current.files[0]);
  };

  render() {
    const { children } = this.props;
    return (
      <>
        <input
          type="file"
          ref={this.fileInput}
          style={{ display: "none" }}
          onChange={() => console.log("NOT ARRIVING HERE")}
        />
        {React.cloneElement(children, {
          onClick: e => {
            e.preventDefault();
            this.fileInput.current.click();
          }
        })}
      </>
    );
  }
}
```

The component works well, if I wrap it around a `<div>Something</div>`. However it does not work, when I wrap it around a `<DropdownItem>`. In the latter case, the onChange handler of the component will never be called. I think this might have something to do with the fact, that the dropdown will be rerendered before the onChange callback is fired. Does this make sense?

Any idea how to solve this problem?

I put all the necessary code into this CodeSandbox: https://codesandbox.io/s/zl15p5rm0x

Thank you!

**Comment by TheSharpieOne** [comment]
You can add `toggle={false}` to the `DropdownItem` and it will stop the menu from toggle when the item is clicked.

**Comment by pReya** [comment]
Thanks @TheSharpieOne. I converted the `<UncontrolledButtonDropdown>`into a `<ButtonDropdown>`. I then added the `toggle={false}` flag to the `<DropdownItem>` and manually called the toggle function, after executing my custom logic. Looks like this now:

```javascript
class SingleFileInput extends React.Component {
  constructor(props) {
    super(props);
    this.fileInput = React.createRef();
  }

  handleSubmit = event => {
    const { onSelectFile, closeDropdown } = this.props;
    event.preventDefault();
    onSelectFile(this.fileInput.current.files[0]);
    if (typeof onCloseDropdown === "function") {
      closeDropdown();
    }
  };

  render() {
    const { children } = this.props;

    return (
      <>
        <input
          type="file"
          ref={this.fileInput}
          style={{ display: "none" }}
          onChange={this.handleSubmit}
        />
        {React.cloneElement(children, {
          onClick: e => {
            e.preventDefault();
            this.fileInput.current.click();
          }
        })}
      </>
    );
  }
}
```
