### ISSUE TITLE
Performance issue between default and named export

### ISSUE THREAD

**Issue by mjdavidson** [reactstrap/reactstrap#1407]
If I use:

```javascript
import Button from 'reactstrap/lib/Button';
```
vs
```javascript
import { Button } from 'reactstrap';
```

Am I gaining any performance benefits? I'm worried that each time I import a named export it's reimporting the whole library, as per this issue https://github.com/facebook/create-react-app/issues/4791#issuecomment-423045091

Does anyone have any insight?

**Comment by TheSharpieOne** [comment]
`import { Button } from 'reactstrap';` would require treeshaking to remove any unused reactstrap component code, that may be why it would take longer? I don't claim to know how treeshaking works, but I would imagine it imports and processes everything at first and then removes the dead branches. That sounds like a lot more work

`import Button from 'reactstrap/lib/Button';` grabs the specific file (the same one that `import { Button } from 'reactstrap';` would end up getting, but it does it more explicitly.

The performance would only be in the dev/build. The code to the client should be the same thanks to treeshaking. Both import methods are supported and it's really up to you.

**Comment by mjdavidson** [comment]
Cool, thanks for your help, have noticed that my hotloading does seem to be a lot faster, and build time is a lot faster.
