### ISSUE TITLE
Cannot use library with server renderer as of v7

### ISSUE THREAD

**Issue by Dakkers** [reactstrap/reactstrap#1408]
- components: (all)
- reactstrap version `#7.1.0`
- import method `es` 
- react version `#16.8.2`
- bootstrap version `#4.2.1`

### What is happening?

I'm using create-react-app for my client code, and doing some server-side rendering with the resulting static build. With version 7 (specifically 7.1.0 though I recall this happening with 7.0.2), I am unable to start my server renderer. My process is:

1. `npm run build` to do a create-react-app static build
2. `npm run build-server` (compiles my Express server code as it uses JSX)
3. `npm run start-server` <-- fails here, when trying to run the server (and import the App)

![image](https://user-images.githubusercontent.com/5009136/52958468-201b9180-3362-11e9-819e-52972911c4d0.png)

It specifically happens when I use, e.g.

```
import { FormFeedback } from 'reactstrap';
```

whereas if I use the following, it will work:

```
import FormFeedback from 'reactstrap/lib/FormFeedback';
```

Here's my server babel file:

```
{
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ]
  ],
  "presets": ["@babel/env", "react-app"]
}
```

server webpack:

```
const path = require('path');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  entry: './src/server/index.js',

  target: 'node',

  externals: [nodeExternals()],

  output: {
    path: path.resolve(`build-server`),
    filename: 'index.js'
  },

  module: {
    rules: [
      {
        test: /\.(s*)css$/,
        use: [
          'isomorphic-style-loader',
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1
            }
          }
        ]
      },
      {
        test: /\.jsx?$/,
        use: 'babel-loader'
      }
    ]
  }
};

```

### What should be happening?

I should be able to use `import { ... } from 'reactstrap';` when the App is imported in Node

### Steps to reproduce issue
(not really easy to reproduce)

1. Create basic App with create-react-app
2. Server-side render it

### Error message in console
(see above)

### Code
N/A

**Comment by Dakkers** [comment]
an update on this: I'm having the same problem with `react-router-dom`, version 4.4.0-beta6. they recently started doing ESM builds and it's resulting in the same unfortunate crap. I don't know how to change my webpack config to transpile these ESM-specific folders... argh!!!

**Comment by Dakkers** [comment]
@marnibrewster are you having trouble with this too?

**Comment by TheSharpieOne** [comment]
reactstrap provides multiple bundles for various import types. The package.json specifies the entry into each of the import types and it's up to your build tool to resolve the right one based on what it can handle.

https://github.com/reactstrap/reactstrap/blob/90cbbd056ceae61e86747c93a8ae192e0b99ec6d/package.json#L5-L11

A lot of babel configurations will not transpile node_modules (recently this has been starting to change). You may just need to include (or not exclude) node_modules in your babel loader.

**Comment by marnibrewster** [comment]
@Dakkers I thought I was, but it turned out that I had imported a reacstrap component improperly. WebStorm imported <Container> for me from "reacstrap/src", and the /src was breaking everything. The error messages were not helpful in figuring it out!

**Comment by Dakkers** [comment]
@marnibrewster would you be willing to share your server webpack? I spent so much time on the weekend on this and the more I work on it, the less I want to do web development as a whole (maybe it's time for me to go back to school)

**Comment by Dakkers** [comment]
@TheSharpieOne I am not excluding `node_modules` in my webpack file (see above) - there's no exclude there. I tried it with and without, to no avail. I will try explicitly including it, though I don't know if that'll do anything. do you have any other suggestions if that fails? I am super fed up with webpack and would love to just have my hand held through this crap.

**Comment by marnibrewster** [comment]
@Dakkers I also reverted to reacstrap v 6.5.0, which doesn't have the babel dependency. Maybe try that? It looks like I also reverted back to reactstrap @6.5.0. My imports look like: `import { Card, Row, Col, Container } from "reactstrap";`

**Comment by Dakkers** [comment]
@marnibrewster I had done that for a while but I don't want to fall too far behind. I've been using the `reactstrap/lib/component` style successfully but it's ugly and tedious. (at least it's working, which is better than what I can say for react-router 4.4.0-beta6... :\ )

**Comment by TheSharpieOne** [comment]
Maybe `webpack-node-externals` is removing the node_modules which means they don't get transpiled and bundled? Maybe you can whitelist reactstrap and react-router and see what happens

**Comment by Dakkers** [comment]
removing `external` was the solution. whitelisting didn't work for whatever reason - it's a server build so it's fine if it's a thicc file.
