### ISSUE TITLE
Add Ellipses and Boundaries for Pagination

### ISSUE THREAD

**Issue by bnikom** [reactstrap/reactstrap#1411]
- components: `Pagination`
- reactstrap version `#7.1.0`
- react version `#16.8.1`
- bootstrap version `#4.2.1`

Are there plans to add ellipses and/or boundaries to reactstrap?

something that would look similar to 
![screen shot 2019-02-22 at 4 57 27 pm](https://user-images.githubusercontent.com/28853525/53273820-1035e180-36c3-11e9-8103-ada1a710356d.png)

Where the ellipses would not show the whole paginated menu, but just the first, last, and center numbers? And it would be possible to move to the rest of the items on the menu from the arrow or clicking on the first/last paginated number on the center block?

Thank you.

**Comment by GoPro16** [comment]
What you are looking for I think it a library like [react-paginate](https://github.com/AdeleD/react-paginate) or [react-js-paginate](https://github.com/vayser/react-js-pagination). These libraries have all that logic built into them whereas reactstrap is supposed to be a simple component library that people can build off. 

I believe those libraries listed above can be customized so you can still add in props with the reactstrap components. If not, you should either open up and issue on their for adding that feature or maybe look into a pagination lib that handles all the logic and build a HOC out of it with reactstrap.

**Comment by bnikom** [comment]
thanks for the suggestion! I ended up using react-paginate. much appreciated.
