### ISSUE TITLE
Dropdown component issue - overlapped by other components if close by

### ISSUE THREAD

**Issue by fizcoder** [reactstrap/reactstrap#1415]
- components: `Dropdown`
- reactstrap version `#7.1.0`
- import method `import {Dropdown, DropdownToggle, DropdownMenu, DropdownItem } from 'reactstrap';`
- react version `#16.4.0`
- bootstrap version `#4.3.1`

### What is happening?

When I use the dropdown component, it's overlapped by another component if it's close by. 
See screenshot: 
![screenshot of dropdown overlap](https://user-images.githubusercontent.com/5448149/53424117-834c9a00-39da-11e9-9269-e850aed52ddb.png)

### What should be happening?

The dropdown should not be overlapped by other component.

### Steps to reproduce issue

1. Have components close to where the dropdown is
2. press dropdown and see how the dropdown overlaps.

**Comment by TheSharpieOne** [comment]
Could not reproduce given the reproduction steps provided: https://stackblitz.com/edit/reactstrap-v7-7otafu?file=Example.js

Can you provide more information or minimal sample code showcasing the issue.

**Comment by fizcoder** [comment]
Thanks for getting back. I just figured out what the issue was based on your response that it's working on your side. It was another plugin/component that's causing the issue. I will investigate to resolve or contact the plugin owner if I can't resolve. 

Closing this issue now.
