### ISSUE TITLE
Cannot read property 'popper' of undefined in popper.js

### ISSUE THREAD

**Issue by slaith** [reactstrap/reactstrap#1420]
- components: `DropDownToggle`
- reactstrap version `#7.1.0`
- import method `umd/csj/es` 
- react version `#16.8.3`
- bootstrap version `#4.3.1`

### When I click on a dropdown toggle, instead of opening the dropdown menu it throws an error saying 
Cannot read property 'popper' of undefined in popper.js

this is the line
       data.offsets.popper = getClientRect(data.offsets.popper);

 * @version 1.14.7 of popper

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
Uncaught in (promise): TypeError: Cannot read property 'popper' of undefined
    at eval (popper.js:889)
    at Array.forEach (<anonymous>)
    at runModifiers (popper.js:877)
    at Popper.update (popper.js:932)
    at Popper.update$$1 (popper.js:2511)
    at eval (popper.js:46)
```

### Code
other packages installed
```
   "@fortawesome/fontawesome-free": "^5.7.2",
    "axios": "^0.18.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "bootstrap": "^4.3.1",
    "font-awesome": "^4.7.0",
    "node-sass": "^4.11.0",
    "perfect-scrollbar": "^1.4.0",
    "react": "^16.8.3",
    "react-beautiful-dnd": "^10.0.4",
    "react-bootstrap": "^1.0.0-beta.5",
    "react-datetime": "^2.16.3",
    "react-dom": "^16.8.3",
    "react-hot-loader": "^4.7.1",
    "react-notification-alert": "^0.0.9",
    "react-perfect-scrollbar": "^1.4.4",
    "react-redux": "^6.0.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.5",
    "reactstrap": "7.1.0",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0"
```

**Comment by TheSharpieOne** [comment]
Need more information. The error message and everything provided is outside of reactstrap. You could open an issue with popper.js given the information provided.

Chances are there is something wrong with the way you are using reactstrap's dropdown. If you can provide that code (especially via something like [stackblitz](https://stackblitz.com/edit/reactstrap-v7?file=Example.js)) we might be able to better track down the issue.

**Comment by slaith** [comment]
My bad. Someone added some code in dropdown. This was working with a previous version though. I am not sure what happened, but removing it, everything worked fine. 


```
					      		<DropdownMenu modifiers={{
								      setMaxHeight: {
								        enabled: true,
								        order: 890,
								        fn: () => {
								          return {
								            styles: {
								              overflow: 'auto',
								              maxHeight: 100,
								            },
								          };
								        },
								      },
								    }}>
```
