### ISSUE TITLE
Tapping Popover or Tooltip with trigger="click" on mobile doesn't open it

### ISSUE THREAD

**Issue by hsource** [reactstrap/reactstrap#1425]
- components: `Tooltip`, `Popover` (via `TooltipPopoverWrapper`)
- reactstrap version `#7.1.0`
- import method `es` 
- react version `#x.x.x`
- bootstrap version `#4.2.1`

### What is happening?

Tapping an UncontrolledPopover with trigger of `click` or `legacy` causes it to open briefly but close soon after.

### What should be happening?

The popover should remain open

### Steps to reproduce issue

1. Open https://stackblitz.com/edit/reactstrap-cxz218?file=Example.js on phone (confirmed working on iOS Chrome and Safari)
2. Try clicking "Launch popover"

### Code

https://stackblitz.com/edit/reactstrap-cxz218?file=Example.js

**Comment by hsandrade** [comment]
Same thing here.
And if the popover content has an element with link like:
`<a href="http://www.google.com.br" target="_blank">Test</a>`
This link is activate automatically before de popover is closed (automatically too), if the popover is shown above the target element used to trigger.

**Comment by fcpauldiaz** [comment]
I'm still having this issue, is the fix deployed on npm ?

**Comment by kode-ninja** [comment]
Still having this issue too:
reactstrap 8.0.0
Chrome/Internet on Galaxy S9

**Comment by jhblacklock** [comment]
Having issue as well with the Tooltip component and latest.  

If `triggers="click hover"`, the result is having to click the button twice to show the Tooltip.

If `triggers="click"`, the Tooltip will show on first click, but it loses the `mouseout` event handling, so the user has to click on the target to close the tooltip.  If the target is hidden by the tooltip body, there is no way for the tooltip to be closed.

https://stackblitz.com/edit/reactstrap-v8-otxfh4?file=Example.js

**Comment by jhblacklock** [comment]
Forcing a delay `delay={{ show: 300, hide: 300 }}` fixes this issue.  The problem is the hover and click events fire one after another.

In mobile, `mouseenter` fires just before click, resulting in `showWithDelay` and `handleDocumentClick` to be called within ms of each other.

**Comment by rmlevangelio** [comment]
Still having this issue. This also crashes the mobile browser. You can try it by clicking the tooltip on mobile multiple times.

**Comment by 13it235** [comment]
> Forcing a delay e.g. `delay={{ show: 300, hide: 300 }}`, fixes this issue. The problem is the hover and click events fire one after another.
> 
> In mobile, `mouseenter` fires just before the `click` event, resulting in `showWithDelay` and `handleDocumentClick` to be called within ms of each other.

This is an issue even in the case of Popover. However my trigger type was legacy. @jhblacklock your solution worked for me . However, is it the same reason that you've mentioned above even in the legacy case? Thank you.

**Comment by jhblacklock** [comment]
That is a good question.  I'm not sure about that @13it235.  But if the solution worked, then chances are it's the same issue 🤷‍♂ 😆
