### ISSUE TITLE
Table responsive not getting name from cssModules

### ISSUE THREAD

**Issue by huan086** [reactstrap/reactstrap#1429]
- components: Table
- reactstrap version `#7.1.0`
- import method `es`
- react version `#16.8.1`
- bootstrap version `#4.3.1`

### What is happening?

https://github.com/reactstrap/reactstrap/blob/master/src/Table.js#L59 renders className `table-responsive` without looking in cssModules

### What should be happening?

The className should be the mangled name in cssModules

### Error message in console

None

### Code

```ts
import bootstrap from '../../css/bootstrap.scss';
const bs = bootstrap as any as { [classname: string]: string };
```

```tsx
<Table responsive cssModule={bs}>
```

**Comment by TheSharpieOne** [comment]
closed via #1430
