### ISSUE TITLE
Popover on click gets stuck to the extreme left

### ISSUE THREAD

**Issue by AshishKapoor** [reactstrap/reactstrap#1432]
- components: `Popover`
- reactstrap version `#5.0.0`
- import method `umd/csj/es` 
- react version `#16.8.4`
- bootstrap version `#4.3.1`

### What is happening?

![ezgif-2-02c174b1813a](https://user-images.githubusercontent.com/5203107/53933405-42344400-40c4-11e9-957b-fcce8de834f7.gif)
Popover on click gets stuck to the extreme left.

### What should be happening?

Should show and hide without moving around.

### Steps to reproduce issue

1. Click on the div with Popover
2. Click on an element from the list in that Popover
3. Observe

### Error message in console

NA

### Code

NA

**Comment by TheSharpieOne** [comment]
I cannot reproduce. Can you provide a minimal example using something like [stackblitz](https://stackblitz.com/edit/reactstrap-v7?file=Example.js)

**Comment by hung211097** [comment]
I'm having the same problem

**Comment by AshishKapoor** [comment]
@hung211097 can you provide some sample code to reproduce it?

**Comment by hung211097** [comment]
I've solved the problem. The reason is that I've set the same id on DOM. Thank you for your reply.

**Comment by hung211097** [comment]
> @hung211097 can you provide some sample code to reproduce it?

I've solved the problem. The reason is that I've set the same id on DOM. Thank you for your reply.
