### ISSUE TITLE
Missing props on PaginationLink

### ISSUE THREAD

**Issue by RogierDonkervliet** [reactstrap/reactstrap#1437]
### Issue description

- components: `PaginationLink`
- reactstrap version `#7.1.0`

### What is happening?
The PaginationLink provides two new props (first and last), according to the documentation:
https://reactstrap.github.io/components/pagination/#

However it's not in the latest tag (7.1.0), though it is in the master branch:
https://github.com/reactstrap/reactstrap/blob/master/src/PaginationLink.js

### What should be happening?
Create a new tag containing PaginationLink master.

**Comment by supergibbs** [comment]
Docs are based off the latest in master branch so they can be out of sync with the latest release.

**Comment by RogierDonkervliet** [comment]
That is a bit strange.. If the docs don't reflect the current release, what's the use of the documentation?

**Comment by gergely-nagy** [comment]
When a PR is merged to master, the docs automatically build.
We still have an issue regarding docs is out of sync with npm version https://github.com/reactstrap/reactstrap/issues/195
For now, just clone the version you are using and run the docs locally.

**Comment by TheSharpieOne** [comment]
This has now been released.
