### ISSUE TITLE
Datepicker violates the max limit if arrows are used

### ISSUE THREAD

**Issue by fabiosalvi** [reactstrap/reactstrap#1439]
- reactstrap version `#7.1.0`

As you can see from the screenshot,
selecting the date from the dropdown calendar the {max} constraint is respected,
but if you use the up and down arrows the constraint is violated.

![Screen Shot 2019-03-18 at 21 59 23](https://user-images.githubusercontent.com/29264173/54563948-e07caf80-49ca-11e9-91dc-f1021db5c658.png)

![Screen Shot 2019-03-18 at 22 00 32](https://user-images.githubusercontent.com/29264173/54563830-9267ac00-49ca-11e9-81ae-d5a9302ad413.png)

**Comment by TheSharpieOne** [comment]
reactstrap (nor bootstrap) have a date picker. The date picker you are seeing is coming from Google Chrome itself (given that the input's type="date").

You might want to [open an issue with Google Chrome](https://support.google.com/chrome/answer/95315?co=GENIE.Platform%3DDesktop&hl=en) or with [Chromium](https://crbug.com/wizard).
