### ISSUE TITLE
Attempted import error: 'UncontrolledPopover' is not exported from 'reactstrap'.

### ISSUE THREAD

**Issue by obayol** [reactstrap/reactstrap#1440]
Hi,

I'm trying to import UncontrolledPopover in my React Class, and the import statement "import { UncontrolledPopover } from 'reactstrap';" fails with the message "Attempted import error: 'UncontrolledPopover' is not exported from 'reactstrap'." even though reactstrap is installed. Can someone please help?

**Comment by TheSharpieOne** [comment]
The export is there:
https://github.com/reactstrap/reactstrap/blob/ad2a9a0101c838831f31a932a32cb37d3316c153/src/index.js#L47

Make sure you have the latest version.

**Comment by naishe** [comment]
In my case, the latest version fixes it. thanks.

**Comment by kaleem-elahi** [comment]
I am getting this same issue :( 

I also installed the latest version of reactstrap

**Comment by naishe** [comment]
8.0.1 or later?

**Comment by kaleem-elahi** [comment]
6.1.0

**Comment by kaleem-elahi** [comment]
@naishe 8.0.1 version worked, Thanks :)
