### ISSUE TITLE
Input type="textarea" with innerRef

### ISSUE THREAD

**Issue by NaridaL** [reactstrap/reactstrap#1455]
- components: `Input`
- reactstrap version `#7.1.3`
- import method `es` 
- react version `#16.8.6`
- bootstrap version `#4.1.3`

### What is happening?

It is not possible to get a ref to a textarea created with reactstrap without type assertions.

```ts
let ref = React.createRef<HTMLTextAreaElement>()
let comp = <Input type="textarea" innerRef={ref} />
```

> Type 'RefObject<HTMLTextAreaElement>' is not assignable to type '((instance: HTMLInputElement) => void) | RefObject<HTMLInputElement> | (((instance: HTMLInputElem...'.
>   Type 'RefObject<HTMLTextAreaElement>' is not assignable to type 'RefObject<HTMLInputElement>'.
>     **Type 'HTMLTextAreaElement' is not assignable to type 'HTMLInputElement'.**
>       Property 'accept' is missing in type 'HTMLTextAreaElement'.ts(2322)
> Input.d.ts(38, 3): The expected type comes from property 'innerRef' which is declared here on type '(IntrinsicAttributes & IntrinsicClassAttributes<Input<{}>> & Readonly<InputHTMLAttributes<HTMLInp...'

### What should be happening?

As Input type="textarea" is the way to get a textarea according to the docs, it should also be possible to get a ref to the textarea.

**Comment by walteribeiro** [comment]
I have the same problem, I think it's because the innerRef is typed to HTMLInputElement only.

![image](https://user-images.githubusercontent.com/10420735/82549662-a8737e00-9b33-11ea-9f98-5a25661c353f.png)

**Comment by iamandrewluca** [comment]
@walteribeiro what are you showing in the image a TypeScript types. The issue is about propTypes

**Comment by walteribeiro** [comment]
Because I had the same problem with typescript and found that it was because of typings
