### ISSUE TITLE
DropdownMenu - positionFixed not working anymore since v8

### ISSUE THREAD

**Issue by Maczuga** [reactstrap/reactstrap#1473]
- components: `DropdownMenu`
- reactstrap version `#8.0.0`
- import method `umd/csj/es` 
- react version `#16.8.4`
- bootstrap version `#4.3.1`

### What is happening?

Before v8 we used to be able to pass "positionFixed" prop in DropdownMenu component, which would be passed down to popper.

Since this commit this is no longer a case: https://github.com/reactstrap/reactstrap/commit/1afb2c2fc63e2310632920953b8922241cf64f86#comments

Due to that - it is impossible to use react-popper to make dropdown menu fixed instead of absolute.

More info about positionFixed in DropdownMenu: https://github.com/reactstrap/reactstrap/issues/1098#issuecomment-408533511

### What should be happening?

positionFixed prop (and perhaps some more) should be able to go into Popper.

### Steps to reproduce issue

1. Add <DropdownMenu> component with prop positionFixed={true}
2. Watch it not being placed as fixed

### Error message in console

none

### Code

`<DropdownMenu modifiers={{preventOverflow: {boundariesElement: 'window'}}} positionFixed={true}>{options}</DropdownMenu>`

**Comment by johanventer** [comment]
This still isn't working for me in 8.1.1. Reverted to 7.1.0 and positionFixed works as expected.

**Comment by johanventer** [comment]
> This still isn't working for me in 8.1.1, though I'm not sure I see why :(
> 
> Reverted to 7.1.0 and positionFixed works as expected.

Nevermind it works just fine, I was accidentally overriding the DropdownMenu style, which negated any additional style attribute being set by popper.
