### ISSUE TITLE
Import styles in Next Js

### ISSUE THREAD

**Issue by ernestojr** [reactstrap/reactstrap#1474]
Hi, I have a problem that the styles are not loaded in next js. According to the [official documentation](https://nextjs.org/docs/#importing-css--sass--less--stylus-files), I can import css or scss files to next Js. But when I add reactstrap and bootstrap to the project, the components work for me without problem, but not bootstrap styles. I hope you can help me with that. Thanks.

**Comment by Fred12** [comment]
I have the same problem with next version 8

**Comment by TheSharpieOne** [comment]
There is no special requirement for reactstrap around importing bootstrap's styles. You just need to include them in your project the same way you would if you were not even using reactstrap.
If you have an issue importing bootstrap's styles, I recommend opening an issue with next js or bootstrap itself.

At the bare minimum, you can add `<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">` to your index.html and not even use an `import` statement within your code.

**Comment by Fred12** [comment]
Hey, that really worked thanks! Is the same also possible with JQuery.js and Waypoint.js ? Or generally, with every other javascript library, does the import work the same simple way?

**Comment by TheSharpieOne** [comment]
@Fred12 you can certainly import everything via HTML tags. Things like jQuery and waypoint will expose their instances on the global scope. But you should be able to use `import` (or `require('...')`) statements to import them (this does depend on having you development environment properly configured though).

**Comment by ernestojr** [comment]
Hi guys, I tell you how I solved the problem, for some reason it does not work to import the bootstrap css file like this:
`import 'bootstrap / dist / css / bootstrap.css';`
I had to do the one direct import from the node_modules folder, like this:
`import '../node_modules/bootstrap/dist/css/bootstrap.css';`
This way I could import the bootstrap style to Next js.
This also applies to scss styles:
`@import '../node_modules/bootstrap/scss/bootstrap.scss';`
