### ISSUE TITLE
import bootstrap css

### ISSUE THREAD

**Issue by toeurtenh** [reactstrap/reactstrap#1477]
Hello all,

I am using react in laravel
stucture:

resouces->js
app.js
bootstrap.js
resouces->js->components
all components

I have installed reacstrap by following https://reactstrap.github.io/
and I am told by doing

Import Bootstrap CSS in the src/index.js file:

import 'bootstrap/dist/css/bootstrap.min.css';

where should I add this bootstrap css according to my stucture?

Thank you

- components: `name`
- reactstrap version `#x.x.x`
- import method `umd/csj/es` 
- react version `#x.x.x`
- bootstrap version `#x.x.x`

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by TheSharpieOne** [comment]
The plan is to import it in a single common place, such as the entry point to your application. Your app.js file should do fine.

**Comment by toeurtenh** [comment]
@TheSharpieOne sorry I don't understand

**Comment by TheSharpieOne** [comment]
add `import 'bootstrap/dist/css/bootstrap.min.css';` to the top of your app.js file

**Comment by toeurtenh** [comment]
thank you

**Comment by TheSharpieOne** [comment]
Take a look at https://laravel.com/docs/5.8/mix#plain-css and maybe even https://laravel.com/docs/5.8/mix#copying-files-and-directories
