### ISSUE TITLE
Error input group

### ISSUE THREAD

**Issue by toeurtenh** [reactstrap/reactstrap#1480]
I want to get very simple input group by using reactstrap as below

![want input](https://user-images.githubusercontent.com/8510436/57018048-b1886900-6c19-11e9-9ef4-6f9fbb16bb63.png)

by using
```jsx
<InputGroup>
    <InputGroupAddon addonType="prepend">@</InputGroupAddon>
    <Input placeholder="username" />
</InputGroup>
```

what i got is different as below

![error input](https://user-images.githubusercontent.com/8510436/57018073-cfee6480-6c19-11e9-81a7-99e0563de996.png)

how can i solve this?

- components: `name`
- reactstrap version `#x.x.x`
- import method `umd/csj/es` 
- react version `#x.x.x`
- bootstrap version `#x.x.x`

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by TheSharpieOne** [comment]
Doesn't look like you are using bootstrap 4. Make sure you have the latest version of bootstrap. If you must: go into node_modules/bootstrap and verify the version that way (since the installed version may be different than the version in your package.json under some circumstances).
