### ISSUE TITLE
Popover className is set on the wrong dom element in 8.0.0, compared to 7.1.0

### ISSUE THREAD

**Issue by andreipfeiffer** [reactstrap/reactstrap#1484]
- components: `Popover`
- reactstrap version `8.0.0`
- import method `es`
- react version `16.8.6`
- bootstrap version `4.3.1`

### What is happening?

In reactstrap `8.0.0`, when you pass `className` prop to `Popover`, those classes are set on the parent of the `<div class="popover">`, so you cannot override any of the Bootstrap styles.

### What should be happening?

In reactstrap `7.1.0`, when you pass `className` prop to `Popover`, those classes were set on the `<div class="popover">`, which allowed you to override Bootstrap default styles (such as the infamous `max-width: 276px`).

### Steps to reproduce issue

For `7.1.0`: https://codesandbox.io/s/1vn8yvjkp7

Popover content is wide, because the class `extra` is properly set on the `<div class="popover extra ...">`

For `8.0.0`: https://codesandbox.io/s/8z7kl3qw28

Popover content is narrow (276px as it is set in Bootstrap), because the class `extra` is NOT set on the `<div class="popover ...">`, but on its parent.

### Code

```
<Popover className="extra">
```

**Comment by sqs** [comment]
I found a workaround. You can use `TooltipPopoverWrapper` directly, and pass it props `popperClassName="popover show whatever-else" innerClassName="popover-inner whatever-else"`.
