### ISSUE TITLE
Highlight navbar after being clicked and resfresing page

### ISSUE THREAD

**Issue by toeurtenh** [reactstrap/reactstrap#1485]
Hello All,

I have used reactstrap (https://reactstrap.github.io/components/navbar/) for a simple navbar and it works very well but how do I get navbar pill (I mean selected menu with background color after being clicked and refreshing page and it should be dynamic).

I also followed this code which i got from stackoverflow it works but after refreshing page it doesn't work

    $(function () {
        $('a.nav-link').on('click', function (e) {
            window.localStorage.setItem('activeTab', $(e.target).attr('href'));
        });
        var activeTab = window.localStorage.getItem('activeTab');
        if (activeTab) {
            $('a.nav-link a[href="' + activeTab + '"]').tab('show');
            window.localStorage.removeItem("activeTab");
        }
    });

any ideas?

- components: `name`
- reactstrap version `#x.x.x`
- import method `umd/csj/es` 
- react version `#x.x.x`
- bootstrap version `#x.x.x`

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by TheSharpieOne** [comment]
This question is probably best to ask on stackoverflow. I can tell you that `NavItem` has an `active` prop which, when `true`, will make the item appear as active.

**Comment by toeurtenh** [comment]
Thank you for your recommandation but I can't post on stackoverflow as my account can't do. 
Yes I think so but I still don't know how to active as true.
