### ISSUE TITLE
0 value not displaying in DropdownToggle

### ISSUE THREAD

**Issue by tagyoureit** [reactstrap/reactstrap#1496]
- components: `DropdownToggle`
- reactstrap version `#8.0.0`
- import method `umd/csj/es`  es
- react version `#16.8.6`
- bootstrap version `#4.0.0`

### What is happening?
I'm passing props to a custom component that sometimes has the value of 0.  The render in my custom file looks like this:
```
    return (
      <div>
        <ButtonDropdown isOpen={this.state.dropdownOpen} toggle={this.toggleDropDown} disabled={this.state.disabled} >
          <DropdownToggle caret disabled={this.state.disabled}>
            {this.props.currentMinute}
          </DropdownToggle>
          <DropdownMenu>
            {positions()}
          </DropdownMenu>
        </ButtonDropdown>
      </div >
    )
```
When the value of `currentMinute=0` the display shows this:
![2019-05-20_21-17-49](https://user-images.githubusercontent.com/1646840/58068087-c5522b80-7b44-11e9-8939-29d7f2afc3ab.jpeg)
(In the yellow box the 0 comes from the parent file.)

### What should be happening?

0 should be displayed as a value just like the other values (

### Steps to reproduce issue

It appears that reactstrap is treating this 0 as a boolean value.  If I change the code to display based on an if/else `{this.props.currentMinute === 0 ? '0' : this.props.currentHour}` it does display properly.

![2019-05-20_21-25-24](https://user-images.githubusercontent.com/1646840/58068340-d8193000-7b45-11e9-8204-66d84d47ac28.jpeg)

Interestingly, it seems if I put _any_ other code as a child here it does render properly.  For example, `{this.props.currentMinute}{'anything else'}` will show `0anything else`.

### Error message in console

```
No error
```

### Code

https://stackblitz.com/edit/react-7zzcjw

**Comment by TheSharpieOne** [comment]
Probably due to https://github.com/reactstrap/reactstrap/blob/c844ab1f0c4e02c2169e8ad19b18cc59bf4bd3c6/src/DropdownToggle.js#L63

For now, you can just use `this.props.currentMinute.toString()`

**Comment by tagyoureit** [comment]
Thanks.  I settled on `{this.props.currentMinute}{''}` for now and it is working fine.

**Comment by kyletsang** [comment]
Closing as fixed
