### ISSUE TITLE
CustomInput used as a checkbox, UI bug with already true value

### ISSUE THREAD

**Issue by linkev21** [reactstrap/reactstrap#1500]
### Issue description
Hey Guys,
I have a strange behaviour with the CustomInput component used a Checkbox.

- components: `CustomInput`
- reactstrap version `7.1.0`
- react version `16.7.0`
- bootstrap version 4.3.1

### What is happening?
I use it in a form. Create and update form.
I made a component in top of the Checkbox who is a CheckboxList, because It's dynamics values. 

Everything is ok when I check the Checkbox and when all checkbox are unchecked by default.
But, on the update form, when some values are already checked (true), It's uncheck in a ui.

I inspect the elements in the console and I see the value as "true" but the checkbox is still uncheck.

### What should be happening?
Check when It should be with true check.

### Steps to reproduce issue
Create a basic form with a state like : 
`this.state = {
			checked: true,
		};`

And render a CustomInput with the checked value from the state. With true as begin, we see the checkbox as uncheck.

### Error message in console
No error.

### Code
Too many generics components I made but at the end, I made my own switch like :

`
class Switch extends PureComponent {
	state = {
		id: uuidv4(), //just to have unique value, the problem is not come from here.
	};

    render() {
        const {
            onCheck,
            checked,
            disabled,
            className,
            type,
            label
        } = this.props;
        const {id} = this.state;

        return (
            <CustomInput
                onChange={onCheck}
                name={name}
                value={checked}
                className={className}
                type={type}
                disabled={disabled}
                id={id}
                label={label}
            />
        );
    }
}`

(Strange indentation here...)

![bug custom input](https://user-images.githubusercontent.com/32356792/58380602-4aa96600-7fb3-11e9-823b-9805b2995bcd.JPG)

What is wrong ?

Thanks a lot !

**Comment by hoslersk** [comment]
I think this issue here is the use of `value` instead of `checked`. While you may want to manage and update `value` for a standard text input, the same type of approach for a checkbox or radio would need to be using the `checked` attribute.

Here is a description of the `checked` attribute: https://www.w3schools.com/tags/att_input_checked.asp

Since you're already passing a `checked` prop, you can just use that as the value for the `CustomInput`'s `checked` prop.

**Comment by linkev21** [comment]
Found it !

It seems I had a problem with the id I passed.
And I need to have both value and checked props (weird yes).

Thanks.
