### ISSUE TITLE
Really long dropdowns in modal can't scroll

### ISSUE THREAD

**Issue by tagyoureit** [reactstrap/reactstrap#1512]
- components: `Modal, Dropdown`
- reactstrap version `#8.0.0`
- import method `es` 
- react version `#16.8.6`
- bootstrap version `#4.3.1`

### What is happening?

I have a Dropdown button in a Modal dialogue that has about 70 choices in it.  It is really long and the user needs to scroll to see the bottom choices.  However, the button choices aren't scrolling.  I've tried both with and without the `scrollable=true` on the modal setting.  Each one has undesirable behavior.

Without scrollable property - Nothing scrolls at all; can't get to bottom of drop down list
With scrollable property - It scrolls the content of the modal for about half the height of the drop down list, and then scrolls/jumps (on some screens) down the list

### What should be happening?

I'd like to have either the modal or drop down button list scroll when the user scrolls the mouse.  I'm open to other suggestions on how to accomplish this as there are many layers of content on top of each other and this may be hard to correct.

### Steps to reproduce issue

Go to Stackblitz (below).  For each of the two examples click the button to open the modal, then click the dropdown to open the list.  Try to scroll to the bottom of the list.

### Error message in console
No errors

### Code

https://stackblitz.com/edit/react-tmhtw7

**Comment by mhmdrz** [comment]
same issue here, even onClick not working correctly with scrollable content

**Comment by tagyoureit** [comment]
I was able to fix this with the `modifiers` attribute.  See (currently incorrect) docs for modifiers on dropdowns page.  I submitted a docs bug #1710 to fix a small issue.

**Comment by AGSTRANGER** [comment]
I am facing a similar issue. I have posted it in this StackOverflow [link](https://stackoverflow.com/questions/61656910/reactstrap-problem-with-long-dropdown-menu-thats-displayed-inside-of-a-table)
