### ISSUE TITLE
Cannot Set Popovers width

### ISSUE THREAD

**Issue by blazinaj** [reactstrap/reactstrap#1518]
### Issue description

- components: `Popover`
- reactstrap version `#7.1.0`
- import method `es` 
- react version `#16.6.3`
- bootstrap version `#4.3.1`

### What is happening?
I cannot set the Popover width to anything different than standard.

### What should be happening?
I need a way to set Popover width inline in a React Class. I've tried multiple things and nothing seems to change it from the Standard 276px width.

**Comment by pswaroopk** [comment]
@blazinaj I think you can do something like this
`const StyledPopover = styled(Popover)`
  min-width: 328px;
`
`

**Comment by blazinaj** [comment]
Like this?
```
const StyledPopover = styled(Popover)"min-width: 328px;"
```

**Comment by pswaroopk** [comment]
I meant backtick, ```

**Comment by blazinaj** [comment]
I guess I'm not sure what you mean, StyledPopover as in a different library than in Reactstrap?

**Comment by pswaroopk** [comment]
StyledPopover is just a variable that you are creating to override some of the css properties that Popover component has, so it can be named to anything you want. It is a wrapper on Popover component.

**Comment by mchaledg19** [comment]
Hi, may I see you code for this issue? I have same issue. I don't know where I gonna put this 
const StyledPopover = styled(Popover)`min-width: 328px;`

**Comment by pswaroopk** [comment]
I just figured out, i missed out an important part in my earlier reply, you need to use styled-components library. ( "styled-components": "^2.0.0" include this in your package.json). You are essentially overriding the css properties that are provided by reactstrap. 

```
import React, { Component } from 'react'
import styled from 'styled-components'
import { Popover } from 'reactstrap'

const StyledPopover = styled(Popover)`
      min-width: 328px;
     background-color: #2F3337;
     && .arrow::after {
       border-right-color: #2F3337;
     }
`
const StyledPopoverBody = styled.div`
  background-color: #2F3337;
  color: #FFFFFF;
  h1 {
    font-size: 16px;
  }
  p {
    font-size: 12px;
  }
`
 <StyledPopover placement='right' isOpen={isPopoverOpen} target="popover-take-action">
     <StyledPopoverBody>
        <h1>Some header</h1>
        <p>Some Content</p>
     </StyledPopoverBody>
  </StyledPopover>
 ```

**Comment by blazinaj** [comment]
@pswaroopk Thank  you for the clarification 👍 

That seems like a good solution, I'm still curious if there's a way to accomplish it without having to import another library.

**Comment by mchaledg19** [comment]
Yes, I think it is better to have solution without importing another library.

**Comment by blazinaj** [comment]
The `styled-components` library worked great and solved my problem. I still hope that Reactstrap will try to build in a better styling solution natively so that we don't have to add another dependency. Closing this issue since the problem was solved. Thanks again @pswaroopk

**Comment by lastapella** [comment]
Hi,
Ithink this would fix your issue without `styled-components`.

```jsx
/* eslint react/no-multi-comp: 0, react/prop-types: 0 */
import React from 'react';
import { Button, UncontrolledPopover, PopoverHeader, PopoverBody } from 'reactstrap';
import './yours.css'

export default class Example extends React.Component {
  render() {
    return (
      <div>
        <Button id="PopoverFocus" type="button">
          Launch Popover (Focus)
        </Button>
        <UncontrolledPopover className="popover-container" trigger="focus" placement="bottom" target="PopoverFocus">
          <PopoverHeader>Focus Trigger</PopoverHeader>
          <PopoverBody>Focusing on the trigging element makes this popover appear. Blurring (clicking away) makes it disappear. You cannot select this text as the popover will disappear when you try.</PopoverBody>
        </UncontrolledPopover>
          <PopoverHeader>Click Trigger</PopoverHeader>
          <PopoverBody>Clicking on the triggering element makes this popover appear. Clicking on it again will make it disappear. You can select this text, but clicking away (somewhere other than the triggering element) will not dismiss this popover.</PopoverBody>
        </UncontrolledPopover>
      </div>
    );
  }
}
```

And then add this file next to your component.
```css
/* yours.css */
.popover-container>.popover{
	max-width: 1000px;
}
```

**Comment by larrywalters** [comment]
> Hi, I think this would fix your issue without `styled-components`.
> 
> ```js
> /* eslint react/no-multi-comp: 0, react/prop-types: 0 */
> import React from 'react';
> import { Button, UncontrolledPopover, PopoverHeader, PopoverBody } from 'reactstrap';
> import './yours.css'
> 
> export default class Example extends React.Component {
>   render() {
>     return (
>       <div>
>         <Button id="PopoverFocus" type="button">
>           Launch Popover (Focus)
>         </Button>
>         <UncontrolledPopover className="popover-container" trigger="focus" placement="bottom" target="PopoverFocus">
>           <PopoverHeader>Focus Trigger</PopoverHeader>
>           <PopoverBody>Focusing on the trigging element makes this popover appear. Blurring (clicking away) makes it disappear. You cannot select this text as the popover will disappear when you try.</PopoverBody>
>         </UncontrolledPopover>
>       </div>
>     );
>   }
> }
> ```
> 
> And then add this file next to your component.
> 
> ```css
> /* yours.css */
> .popover-container>.popover{
> 	max-width: 1000px;
> }
> ```

This was helpful, thanks!
