### ISSUE TITLE
reactstrap.github.io doesn't load with uBlock Origin Extension enabled

### ISSUE THREAD

**Issue by sbtnh** [reactstrap/reactstrap#1519]
It seems https://reactstrap.github.io is broken when `uBlock Origin` Chrome Extension is enabled. I see the page showing and then going completely blank.

All good when uBlock is disabled.

Here's the errors in the console:

![image](https://user-images.githubusercontent.com/675541/58812381-bdd45d00-85ef-11e9-9ce3-6e2ed717e8c8.png)

Browser: Chrome 74 - Mac / PC

**Comment by TheSharpieOne** [comment]
uBlock says "_you_ decide what enters your browser."
All of the content is coming from `reactstrap.github.io` except for the docsearch, which comes from cdn.jsdelivr.net (and that looks like it's loading).

Seems like uBlock is simply blocking reactstrap.github.io, you may want to allow reactstrap.github.io

![image](https://user-images.githubusercontent.com/664714/58824563-5a0b5d80-860a-11e9-8e20-e18645dbc640.png)

**Comment by sbtnh** [comment]
I confirm that if I whitelist `reactstrap.github.io` it's loading correctly.

![image](https://user-images.githubusercontent.com/675541/58825170-d05c8f80-860b-11e9-8bd8-82b8b0dfd080.png)

I mention this issue because until today (been using reactstrap for a while now) I was able to navigate the site with uBlock enabled and no whitelisting. It's no big deal, just tought you guys know.

**Comment by TheSharpieOne** [comment]
I haven't heard of uBlock before today. I am not 100% how it determines what gets blocked. I don't know why it would think reactstrap.github.io should be blocked especially if it just started blocking it recently. It looks like there have been recently releases of uBlock, maybe a change there has triggered it to start blocking reactstrap.github.io

@gorhill could you provide any insight to help avoid using needing to manually whitelist our docs?

**Comment by sbtnh** [comment]
I think what's happening is that uBlock thinks `prism.js` is a tracking scripts and blocks it, and when it's used later, it's undefined, JavaScript errors are triggered and nothing works after that. So it's not that `reactstrap.github.io` is blocked, but rather because `prism.js` is blocked and brakes everthing.

![image](https://user-images.githubusercontent.com/675541/58829171-326dc280-8615-11e9-8592-6fec3d811066.png)

**uBlock list of exclusions:**
![image](https://user-images.githubusercontent.com/675541/58829229-5f21da00-8615-11e9-8367-b2c54b2ae054.png)

I know you're using this [Prism](https://prismjs.com/), and not some prism tracking.

**Comment by TheSharpieOne** [comment]
😢
Let's just hope no one creates a popular tracking or ad product with files named something like index.js or app.js... because if they do, we are are 💀

**Comment by 4k** [comment]
Same with Adblock Plus.

**Comment by gorhill** [comment]
The filter is in EasyPrivacy, so any blocker using that list is going to be affected. Fyi @ryanbr.

**Comment by TheSharpieOne** [comment]
looks like someone has opened and issue with easylist: https://github.com/easylist/easylist/issues/3567

**Comment by gorhill** [comment]
Ok, I wasn't sure since when this filter existed. Since it was added just 3 days ago, I will "badfilter" it for uBO users until it's fixed in EasyList. uBO users should be able to get rid of the filter by forcing an update of the "uBlock filters --- Unbreak" list.

**Comment by sbtnh** [comment]
Thanks guys! 

Let me know if you want me to close the issue since it's more of a uBlock issue, or you prefer to wait until they fix it.

**Comment by sbtnh** [comment]
@gorhill forcing an update fixed it.

To force an update:

`uBlock Extension > Dashboard > Filters list tab`
![image](https://user-images.githubusercontent.com/675541/58885294-f3d91600-86af-11e9-898c-bbe0f8d47367.png)

**Comment by TheSharpieOne** [comment]
Also, a commit has been made to easy list to correct the issue, it should eventually make its way to all of the ad blockers which use the list.

https://github.com/easylist/easylist/commit/6dc4c8692cfdb38957de41e1c517bd13a3ad9dc0
