### ISSUE TITLE
Website is down.

### ISSUE THREAD

**Issue by apisandipas** [reactstrap/reactstrap#1527]
### What is happening?

Website is down

### What should be happening?

Website should render documentation

### Steps to reproduce issue

1. Go to website. Its blank.
2. See JS console throwing errors related to Prism

### Error message in console
"ReferenceError: Prism is not defined"

**Comment by TheSharpieOne** [comment]
Check out #1519 
TL;DR: force update uBO: `uBlock Extension > Dashboard > Filters list tab -> click Update now`

**Comment by TheSharpieOne** [comment]
Also, a commit has been made to easy list to correct the issue, it should eventually make its way to all of the ad blockers which use the list.

https://github.com/easylist/easylist/commit/6dc4c8692cfdb38957de41e1c517bd13a3ad9dc0
