### ISSUE TITLE
Public site doesn't load in FireFox

### ISSUE THREAD

**Issue by tim-field** [reactstrap/reactstrap#1529]
https://reactstrap.github.io/

![image](https://user-images.githubusercontent.com/1326910/59068381-21200100-8908-11e9-8027-5d66e8947731.png)

![image](https://user-images.githubusercontent.com/1326910/59068433-40b72980-8908-11e9-8213-191ba17dc658.png)

**Comment by TheSharpieOne** [comment]
It's your ad blocker. See #1519
