### ISSUE TITLE
Possible to turn on Flexbox Grid system?

### ISSUE THREAD

**Issue by acomito** [reactstrap/reactstrap#155]
Is it possible to turn on the [flexbox grid system](http://v4-alpha.getbootstrap.com/layout/flexbox-grid/) without going into the bootstrap npm module and messing with the Sass file?

> If you’re familiar with modifying variables in Sass—or any other CSS preprocessor—you’ll be right at home to move into flexbox mode.
> 
> - Open the _variables.scss file and find the $enable-flex variable.
> - Change it from false to true.
> - Recompile, and done!

> Alternatively, if you don’t need the source Sass files, you may swap the default Bootstrap compiled CSS with the compiled flexbox variation. Head to the download page for more information.
> 

via http://v4-alpha.getbootstrap.com/getting-started/flexbox/

**Comment by eddywashere** [comment]
No. Unfortunately bootstrap doesn't publish the flexbox version of their css in their dist folder in npm. Here's the url to find what is published `https://unpkg.com/bootstrap@4.0.0-alpha.4/dist/css/`. For demos I typically use `https://unpkg.com/bootstrap@4.0.0-alpha.4/dist/css/bootstrap.css`. Would love to start using the flexbox version. Closing this out but I'll drop that idea by in the bootstrap issues.

**Comment by eddywashere** [comment]
@acomito looks like this will be available in the alpha 5 release according to https://github.com/twbs/bootstrap/issues/20630

**Comment by acomito** [comment]
thanks for the quick response eddy
