### ISSUE TITLE
Docs - Unreliable calculation of next state

### ISSUE THREAD

**Issue by kode-ninja** [reactstrap/reactstrap#1554]
- components: `documentation`
- reactstrap version `#8.0.0`

### What is happening?

In many places throughout the documentation, it seems the examples provided are unreliably calculating the next state. 

For example in the Fade component:
```
    toggle() {
        this.setState({
            fadeIn: !this.state.fadeIn
        });
    }
```

React's relevant documentation: https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous 

### What should be happening?

I would expect the code sample to look like in the Modal component:
```
  toggle() {
    this.setState(prevState => ({
      modal: !prevState.modal
    }));
  }
```

I hope I'm not missing something here...

**Comment by bpas247** [comment]
FWIW #1572 would negate this issue :)

**Comment by kyletsang** [comment]
Closing as fixed
