### ISSUE TITLE
DateInput field not displayed correctly in safari

### ISSUE THREAD

**Issue by garritfra** [reactstrap/reactstrap#1559]
- components: `Input`
- reactstrap version `8.0.0` (Also in current)
- import method `es` 
- react version `16.8.6`
- bootstrap version `4.3.1`

### What is happening?

The date input does not have an option to select the date from a dropdown when using safari. Everything works as expected on chrome.

### What should be happening?

A dropdown should appear. Also, the user should be "guided" through the process of entering a date.

### Steps to reproduce issue

1. Open Safari
2. Navigate to the docs at [https://reactstrap.github.io/components/form/#Input-Types](https://reactstrap.github.io/components/form/#Input-Types)

### Error message in console

None

### Code

https://stackblitz.com/edit/reactstrap-gkbpdj?file=Example.js

**Comment by TheSharpieOne** [comment]
The datepicker you mention is browser specific. It is implemented by the browser, not reactstrap. Also, this is how it is in bootstrap itself.

For browser support and more information, check you: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

If you want a datepicker in every browser (as well as wanting the the experience to be the same in every browser) then you need a third-party lib, such as react-dates.
