### ISSUE TITLE
CSS classes not applied to components 

### ISSUE THREAD

**Issue by simran66** [reactstrap/reactstrap#156]
In  my app.js:

```
import React, {PropTypes}  from 'react';
import { Navbar, NavbarBrand, Nav, NavItem, NavLink } from 'reactstrap';
const TopHeader = (props) => {
  return(
    <div>
      <Navbar color="faded" light>
        <NavbarBrand href="/">reactstrap</NavbarBrand>
        <Nav className="pull-xs-right" navbar>
          <NavItem>
            <NavLink href="/components/">Components</NavLink>
          </NavItem>
          <NavItem>
            <NavLink href="https://github.com/reactstrap/reactstrap">Github</NavLink>
          </NavItem>
        </Nav>
      </Navbar>
    </div>
  );
}

```

It renders the elements but without any CSS. I have tried this in firefox and chrom.When I go to inspect element, there aren't any CSS classes. I don't have any custom CSS either. What could be the reason for plain HTML elements getting rendered without any CSS?

Here's a snapshot:

![nocss](https://cloud.githubusercontent.com/assets/4191009/18841062/28362ba4-842e-11e6-8ca0-8344bddd9db7.png)

**Comment by TheSharpieOne** [comment]
The classes are being applied/added to the elements. That is pretty much what reactstrap does. You have to bring bootstrap's css into your project yourself.
There are a few ways to do that.

- You can use npm: `npm install --save bootstrap@4.0.0-alpha.4`
- You can refernce it from a CDN: https://cdnjs.com/libraries/twitter-bootstrap/4.0.0-alpha.4
- You can use bower (though you really shouldn't): `bower install --save bootstrap#v4.0.0-alpha.4`
- You can download the files and manually add them to your project: https://github.com/twbs/bootstrap/archive/v4.0.0-alpha.4.zip

see https://github.com/twbs/bootstrap#quick-start for more

**Comment by eddywashere** [comment]
Great question. Great answer. Closing this. I'll make sure to note this in a getting started section. Thanks!
