### ISSUE TITLE
placeholder images not showing in docs

### ISSUE THREAD

**Issue by dpkshrma** [reactstrap/reactstrap#1560]
### What is happening?

Placeholder images like https://placeholdit.imgix.net/~text?txtsize=33&txt=318%C3%97180&w=318&h=180 are not showing up since the site seems to be down

### What should be happening?

Placeholder images should be displayed

### Steps to reproduce issue

1. open https://reactstrap.github.io/components/card/
2. check the card in first example

### Error message in console

```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
```

**Comment by lamhieu-vk** [comment]
@dpkshrma welcome a PR from you!

**Comment by bpas247** [comment]
duplicate of #1515
