### ISSUE TITLE
Drawer Component

### ISSUE THREAD

**Issue by oneringtorulethemall** [reactstrap/reactstrap#1561]
Hello,

   First, great set of components...used them on a couple of projects and works very well.
   I have a project I have in mind, but one of the things I need is a Drawer component.
   I'm debating between material-ui and reactstrap for the project. One of the nice features of
   material-ui is that it has a built-in drawer component that is easy to use. 

   Has anybody started/considered adding a general purpose drawer component to this library?
   
    Thanks!

**Comment by TheSharpieOne** [comment]
This project is a set of components matching the original bootstrap. Bootstrap itself depends on jquery and manipulates the DOM directly and doesn't mesh well with react. This library fixes that, but doesn't really provide anything that bootstrap itself doesn't provide.
There are third-party libraries which extend reactstrap to add more functionality similar to how other project extends bootstrap to add more functionality (such as any "bootstrap calendar" or "enhanced select" (select-2)).
If someone wants to make a reactstap-drawer lib, go for it!

A drawer can be created with a little bit of custom CSS and the Collapse component. Bootstrap itself does have an example and you can borrow the custom CSS from that example.
