### ISSUE TITLE
ETA of next release?

### ISSUE THREAD

**Issue by justingrant** [reactstrap/reactstrap#1568]
Is a new release planned soon?  I'm asking because #1495 (which fixes #1323 which makes Modal unusable in React StrictMode because the document isn't scrollable after you close a modal) was merged a few months ago but isn't released yet.

For anyone ending up here via Google or GitHub search, here's a workaround while waiting for a release. 
```
git clone https://github.com/reactstrap/reactstrap.git
cd reactstrap
npm install
npm run build
npm run postbuild
npm pack
cd ../path-to-your-app-goes-here
npm install ../reactstrap/reactstrap-8.0.0.tgz
```
The commands above assume that your app is in peer to `reactstrap` that's cloned from GitHub.  If it's not, adjust the paths. The point is that you can use `npm pack` to create a tarball that you can `npm install` from, instead of downloading and installing the tarball from the npm registry.

**Comment by TheSharpieOne** [comment]
8.0.1 is out
