### ISSUE TITLE
Space/Margin between columns

### ISSUE THREAD

**Issue by raboija** [reactstrap/reactstrap#1579]
Hi there,

I do need to have columns separated by some spaces. At this point I don't know how to achieve this…

Thanks for any help.

**Comment by bpas247** [comment]
can't you just apply additional styling on top of the `Col` component?
```jsx
const Example = () => (
  <Container>
    <Col style={{padding: '5px'}}>Column with additional styling</Col>
  </Container
);
```

**Comment by velthune** [comment]
@bpas247 answer is ok if you have a 'static' page, but when you will resize window you'll see that this is not the solutions for what you need (if I understand right)

**Comment by TheSharpieOne** [comment]
@velthune you can use percentages or even viewport units (such as `vw`) when adding inline styles.
Also, bootstrap has responsive spacing utilities/class names. These spacing utilities add space a certain break points.
See: https://getbootstrap.com/docs/4.0/utilities/spacing/#notation

**Comment by velthune** [comment]
Yes, I have set `className={"pl-4"}` and in a large monitor is ok, I see the two columns separated by the offset (`$spacer * 1.5`), but when I resize browser and columns become 1, padding is still existing: how can I resolve this?

Code is:

```
<Row className="no-gutters">
    <Col xs={12} md={4}>
       ....
     </Col>
     <Col xs={12} md={8} className={"pl-4"} >
      .....
     </Col>
</Row>
```

**Comment by TheSharpieOne** [comment]
Specifically:
> The classes are named using the format {property}{sides}-{size} for xs and {property}{sides}-{breakpoint}-{size} for sm, md, lg, and xl.

type adding the breakpoints: `pl-1 pl-sm-2 pl-md-3 pl-lg-4 pl-xl-5`

**Comment by velthune** [comment]
Thanks a lot for the tip, works with this combination:

    "pl-0 pl-sm-0 pl-md-3 pl-lg-4 pl-xl-5"
