### ISSUE TITLE
UncontrolledTooltip causes infinite loop when wrapper has overflow-x:auto

### ISSUE THREAD

**Issue by amillward** [reactstrap/reactstrap#1587]
- components: `UncontrolledTooltip`
- reactstrap version `#8.0.0`
- import method `umd/csj/es` 
- react version `#16.8.6`

### What is happening?

When an element with `overflow-x:auto` has an attached UncontrolledTooltip, triggering the tooltip causes an infinite loop, locking the browser

### What should be happening?

The tooltip should show

### Steps to reproduce issue

Add `overflow-x:auto` to a wrapper containing an element with a tooltip

### Error message in console

None

### Code

CodeSandbox: https://codesandbox.io/s/polished-framework-2mtgx

**Comment by belliAndrea** [comment]
Had the same problem.
I think it's related to the container's height. If i put a min-height on the container enough for the tooltip to be displayed it seems to work fine.

**Comment by YassienW** [comment]
#1488 #1482 Related?

**Comment by dumbmatter** [comment]
Does #1669 fix this?

**Comment by GoPro16** [comment]
This looks to be fixed in the latest version. Going to close but can re-open if anyone sees otherwise.
