### ISSUE TITLE
Input onCopy | Feature

### ISSUE THREAD

**Issue by rfdc** [reactstrap/reactstrap#1590]
I came across onCopy while using <Input/> and could not find any information about it.

Can I use it to make a Copy to clipboard component?

This could be a cool feature for this awesome package. 

Thanks

**Comment by GoPro16** [comment]
Not sure I am following what you are looking to add here? The `onCopy` function is a synthetic event already included in `React`.

https://codesandbox.io/s/reactstrap-issue-1590-mb78v

**Comment by rfdc** [comment]
that is what I was after but I did not want to add another package. 

It would be cool if reactstrap had that functionality. 

Thanks for your help
