### ISSUE TITLE
Can't remove border from selected button in button group.

### ISSUE THREAD

**Issue by AdamT213** [reactstrap/reactstrap#1595]
### Issue description
By default, the selected button in a button group has a grey border around it. This will not work in my case, but it does not seem to be controlled by any css that I can discern. Is there a way to remove this border?
- components: `button group`
- reactstrap version `6.4.0`
- react version `16.8.6`
- bootstrap version `4.1.0`

### What is happening?

There is a grey border on the selected button in the button group, just like in the demo. https://reactstrap.github.io/components/button-group/
### What should be happening?
This works fine when the buttons are also grey, but my buttons are green, and it looks out of place. Is it possible to remove the border? It is not controlled by a prop, nor by any discernible css that I can see in devtools.

Not have a grey border.
### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by GoPro16** [comment]
It sound like you are referring to the focus property when the button is selected. This happens by taking the background color and applying some `:focus` after effects on it. This in fact is a bootstrap css style of `btn-secondary:focus`.

If you want to circumvent this just pass a `color` prop that is no valid so `bootstrap` doesn't kick in with any of the default styles other than `btn` although I wouldn't recommend this. I would probably just add overrides for your colors in a `colors.scss` or `index.scss` file.

Just import the `bootstrap` library and overwrite the colors in some `scss` file.

```scss
$theme-colors: (
    "primary":#0A175A;
etc...
);
```

**Comment by AdamT213** [comment]
Thanks, I will try that!
