### ISSUE TITLE
Carousel component needs update to conform to new react lifecyle methods

### ISSUE THREAD

**Issue by gone-skiing** [reactstrap/reactstrap#1602]
- components: `Carousel `
- reactstrap version `8.0.1`
- react version `16.9.0`
- bootstrap version `4.3.1`

### What is happening?

backend.js:1 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

### What should be happening?

Deprecated method should not be used.

### Steps to reproduce issue

1. Any use of the component.

### Error message in console

```
backend.js:1 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Carousel
```

**Comment by drewskiii** [comment]
I'm having the same issue.

**Comment by Tulean** [comment]
Did you guys find any fix for it? I am also having the same issue.

**Comment by gone-skiing** [comment]
I never heard from maintainers. One option is to simply add prefixes to methods to suppress the warnings. Full credit fix requires changing component lifecycle methods to supported, I believe.

**Comment by ahmeed83** [comment]
Im still having the same issue. Are they planning to include it to the new version of reacstrap?

**Comment by stevesioli** [comment]
is anybody already working on this?  if not, I'd like to resolve for hacktoberfest.

**Comment by MarkEhr** [comment]
@stevesioli looks like #1638 fixes it for this specific component, but I'm sure you can find other comonents with the same problem if you wanna get Hacktoberfest points.

**Comment by stevesioli** [comment]
@MarkEhr I left a comment on that PR.  The object comparison they are using will not work as expected.

**Comment by onlywicked** [comment]
Anybody working on it. I would love to work on this issue.

**Comment by TheSharpieOne** [comment]
I believe @stevesioli might be working on this.

**Comment by onlywicked** [comment]
No worry.

**Comment by stevesioli** [comment]
should have a PR submitted for this today

**Comment by dsavai** [comment]
i founf the solution here https://stackoverflow.com/questions/56771532/react-owl-carousel-is-blank
