### ISSUE TITLE
[Question] Dropdown auto transform/translates

### ISSUE THREAD

**Issue by gavinkalika** [reactstrap/reactstrap#1603]
- components: `ButtonDropdown DropdownToggle DropdownMenu`
- reactstrap version `#7.1.0`
- import method `umd/csj/es` 
- react version `#16.8.6`
- bootstrap version `#4.2.1`

### What is happening?

I am using the drop down component and when I scroll the dropdown children items
moved with the scrolling. It appears to be a css property called "transform: translate".

How do I remove that css property?

### What should be happening?

It would be nice if the drop down items did not move with scrolling 

### Code

            <ButtonDropdown isOpen={toggle} toggle={ () => {setToggle(!toggle)} } direction="up">
                  <DropdownToggle caret>
                      <GateIcon/> Gate Control {index + 1}
                  </DropdownToggle>
                  <DropdownMenu style={divStyle}>
                      <DropdownItem >Open Gate</DropdownItem>
                      <DropdownItem>Close Gate</DropdownItem>
                      <DropdownItem>Auto Gate</DropdownItem>
                  </DropdownMenu>
              </ButtonDropdown>

**Comment by gavinkalika** [comment]
I think it might have something ot do with popper js. As a result, it might not be your problem.

**Comment by TheSharpieOne** [comment]
The dropdown menu is "attached" to the trigger. It will follow the trigger where ever it scrolls. This how bootstrap itself has implemented the feature.
The `transform: translate` is just more positions around the trigger (based on the direction you want the menu to open).
popper.js may support a feature where once the menu is open it remains "fixed" to the viewport and you should be able to configre popper.js through the dropdown if it does.

**Comment by gavinkalika** [comment]
thanks. closing issue.
