### ISSUE TITLE
Tests run slower in environments with limited resources

### ISSUE THREAD

**Issue by eddywashere** [reactstrap/reactstrap#161]
Tests are slow in Travis CI (~4 minutes) and in docker (46 seconds) compared to the 6-7 seconds it takes locally with access to decent resources. Nothing urgent but I'd thought I'd track this.

**Comment by TheSharpieOne** [comment]
facebook/jest#1532 seems to indicate it is just slow on the first run with coverage.... which is all travis and CI does.

**Comment by eddywashere** [comment]
womp. I bet it's repeatable in `create-react-app` if it had more components, realistic tests and a docker-compose file. Something to dig into and post there. Which may eventually fall into jest and related repos.

**Comment by TheSharpieOne** [comment]
Yeah. I'm ok with travis taking a little while. It seems faster than before. Dev is definitely faster and doesn't suffer from the memory issue anymore. Maybe we just wait until fb addresses the perf since it isn't really hurting this project right now.

**Comment by eddywashere** [comment]
closing, but adding a revisit label to keep track of things like this that aren't really actionable.

**Comment by eddywashere** [comment]
Still not fixed but it looks like there is a jest option to run tests in the current process via `--runInBand`. So far it's cut the test time in half.
