### ISSUE TITLE
React-router 5.x.x migration

### ISSUE THREAD

**Issue by elitsa-ivanova** [reactstrap/reactstrap#1612]
### Issue description
Hello :)

Are you planning on migrating to react-router 5.x.x?

**Comment by TheSharpieOne** [comment]
Not sure what you mean. We only use react-router for our docs. Unless there is a need to update it for our docs, it is unlikely that it will be updated (unless someone wants to submit a PR).
If there are any issues using react-router v5 with reactstrap, please let us know.  Right now the only suggested usage is with `tag` to various components. Something like

```jsx
import { NavLink } from 'reactstrap';
import { NavLink as RRNavLink } from 'react-router-dom';
// ... 
<NavLink tag={RRNavLink} to="/something">Something</NavLink>
// ...
```

**Comment by DarthVanger** [comment]
Nice idea with the `tag`, thanks!

Might be worth adding this example to the docs? Right now it uses `Navlink` directly from `ReactStrap` without the `tag` option https://reactstrap.github.io/components/navbar/

**Comment by dsolovieva** [comment]
@TheSharpieOne I faced the issue during migrating my app to react-router 5.x.x. The case is pretty similar to your example but I use `NavLink` from the `react-router-dom` as a `tag` for `DropdownItem`. Tag property is defined as:
```jsx
DropdownItem.propTypes = {
  //...
  tag: PropTypes.oneOfType([PropTypes.func, PropTypes.string]),
  //...
};
```
but in react-router-dom 5.x.x `NavLink` is wrapped in a `forwardRef` that is actually `Object`. So, it cause of warning about incorrect prop type.

The example of usage: 
```jsx
import { NavLink } from 'react-router-dom';
import { DropdownItem } from 'reactstrap';

<DropdownItem tag={NavLink} ...>
   //...
</DropdownItem>

```

**Comment by TheSharpieOne** [comment]
The `tag` propType is defined https://github.com/reactstrap/reactstrap/blob/546b15c5729c5ab794081dff83ffff3e7dbe139a/src/utils.js#L137-L146 which accepts an object of a particular shape.
It is used in DropdownItem: https://github.com/reactstrap/reactstrap/blob/546b15c5729c5ab794081dff83ffff3e7dbe139a/src/DropdownItem.js#L5-L18

This was added in v7.1.0

I know that prop-types have added a new specific propType for this. We might want to consider bumping the prop-types version to use the new propType to be more future-proof.

**Comment by dsolovieva** [comment]
@TheSharpieOne Thank you for such a fast reply, this is very helpful! 
I was guided by the documentation page https://reactstrap.github.io/components/dropdowns/. It seems it describes an older version.
