### ISSUE TITLE
Tag-input

### ISSUE THREAD

**Issue by jiman93** [reactstrap/reactstrap#1628]
I'm searching for a tag input component with bootstrap styling which strangely I couldn't find it here in reactstrap. Do I miss something? I'm looking for something like this https://www.npmjs.com/package/react-tag-input  with bootstrap styling

**Comment by TheSharpieOne** [comment]
bootstrap doesn't really have anything like that so neither does reactstrap. You'd have to use a third-party library to support what you are looking to do. Or you can create it yourself using [Badges](https://reactstrap.github.io/components/badge/) with an [Input](https://reactstrap.github.io/components/form/)
