### ISSUE TITLE
NavbarToggler Accessibility

### ISSUE THREAD

**Issue by TheSharpieOne** [reactstrap/reactstrap#1632]
reactstrap should add the `aria-label="Toggle navigation"` as seen in bootstrap's docs. It would be overridable by the props passed in.
reactstrap should also include information about the `aria-controls` and `aria-expanded` for additional a11y as those would need to be provided by the user (`NavbarToggler` doesn't actually know if it is toggled or not (maybe it could/should?))

**Comment by glenpadua** [comment]
Hey I'd like to pick this up. Will raise a PR in a while after I'm done!
