### ISSUE TITLE
Removing prev/next arrow buttons in date input types.

### ISSUE THREAD

**Issue by amrutraj** [reactstrap/reactstrap#1655]
Hi,
Is there any way to remove arrows next to the cross, without making modifications to the source? They are never ever used by my client but take up the last 2 digits of the year.
![datepicker](https://user-images.githubusercontent.com/346424/66563203-e7dbf400-eb7a-11e9-92af-2850c3264129.png)

**Comment by TheSharpieOne** [comment]
Those are the default styles for the browser. They are applied by the browser, not be reactstrap nor bootstrap. You can see some discussion here: https://github.com/twbs/bootstrap/issues/25605

You can see how date fields are handled by bootstrap here: https://getbootstrap.com/docs/4.3/content/reboot/

That said, you can use custom css/styles to remove those:
```
::-webkit-inner-spin-button { display: none; }
```
more info: https://stackoverflow.com/a/16106788/1873485

**Comment by amrutraj** [comment]
Thank you very much.
It would be awesome to know HOW one gets to know the names/classes of these elements without searching the web. Because I couldn't do it using the chromes dev tools (inspector).
For others who might want to remove the blue cross (also handled by the browser) simply add this 
`::-webkit-clear-button{ display: none !important; }` to your custom stylesheet.

**Comment by TheSharpieOne** [comment]
If you open chrome devTools settings and enable the shadow DOM ("Show user agent shadow DOM"), you can then expand the input and inspect to see how various elements are composed (everything is really just divs and spans) and their pseudo selectors.

![image](https://user-images.githubusercontent.com/664714/67778777-17737300-fa3a-11e9-8792-574399f60aa0.png)
