### ISSUE TITLE
Migrate remaining doc examples to function components

### ISSUE THREAD

**Issue by bpas247** [reactstrap/reactstrap#1659]
A continuation of #1572, We should migrate the remaining doc examples from class components to function components (via hooks). The remaining doc examples that will need to be migrated are:
- [x] [DropdownSizing](https://github.com/reactstrap/reactstrap/blob/master/docs/lib/examples/DropdownSizing.js)
- [x] [ButtonDropdownUncontrolled](https://github.com/reactstrap/reactstrap/blob/master/docs/lib/examples/ButtonDropdownUncontrolled.js)
- [x] [Dropdown](https://github.com/reactstrap/reactstrap/blob/master/docs/lib/examples/Dropdown.js)
- [x] [CustomDropdown](https://github.com/reactstrap/reactstrap/blob/master/docs/lib/examples/CustomDropdown.js)

**Comment by dvlprdave** [comment]
Hey, mind if I take this?

**Comment by bpas247** [comment]
Oops sorry, just noticed that #1667 was merged. 

@dvlprdave Awesome work 😄
