### ISSUE TITLE
Proper way to add text in the center of Navbar reactstrap?

### ISSUE THREAD

**Issue by yzhaopost** [reactstrap/reactstrap#1662]
I built a menu bar using reactstrap Navbar. I am trying to add text (please refer to the the red rectangle portion in the attached screenshot) in the center of the menu bar, but could not make it. 

![image](https://user-images.githubusercontent.com/45929614/66768515-97f57980-ee67-11e9-852f-82b8450f4c95.png)

I was just wondering what is the proper way to add text in the middle of the Navbar? Any suggestions would be greatly appreciated.

**Comment by TheSharpieOne** [comment]
Not really specific to reactstrap. Check out bootstrap's response to a similar issue: https://github.com/twbs/bootstrap/issues/27676

> This is a limitation of CSS—flexbox cannot inherently do what you want it to do without setting fixed widths on the first and last items (assuming three items). Absolute positioning is another option. So is grid layout, depending on your browser audience's intended support.

**Comment by yzhaopost** [comment]
@TheSharpieOne Thank you for your information. I am going to close this issue.
