### ISSUE TITLE
Input type="search"

### ISSUE THREAD

**Issue by Rads92** [reactstrap/reactstrap#1663]
- components: `Input`
- reactstrap version 6.5.0`
- react version `16.8.6`

### What is happening?

User is not able to select cursor position by mouse on Chrome. 
It works on other browsers.
### What should be happening?

User is able to select cursor position by mouse on Chrome. 

### Steps to reproduce issue

1. Try to select cursor position by mouse on Input component with type props equals to "search"

**Comment by TheSharpieOne** [comment]
This is very interesting. I was able to reproduce this with reactstrap as well as plain bootstrap (even bootstrap's docs have this issue with their search field).
~~I am going to defer this to bootstrap as all reactstrap is doing is applying the className to the input, the styles from the className come from bootstrap.~~

This appears to be a bug with chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1014243&q=search%20input%20padding&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

If the search input has left padding this will happen. Bootstrap's form-control styles add such padding.
Checkout https://codepen.io/TheSharpieOne/pen/YzzqdgW which is plain bootstrap and a plain html with padding example (no reactstrap), both suffer from this issue.

I am closing this as there is nothing reactstrap can do. Please use the link above to track the issue within chrome's bug tracker.
