### ISSUE TITLE
Scrollable table?

### ISSUE THREAD

**Issue by wkibbler** [reactstrap/reactstrap#1666]
Is there a way to create a table within a card that will scroll down the table instead of overflowing the card. I cant see anything in the docs and the Table component with not accept height as a style prop.
Is this possible?

**Comment by TheSharpieOne** [comment]
Not 100% sure what you are trying to do / how you want it to look, but... `height` on a `<table>` is deprecated/obsolete and should not be used.
Wrap it in a div, give that div a maxHeight and overflowY: 'auto'.
https://stackblitz.com/edit/reactstrap-v8-pwyocr?file=Example.js

**Comment by wkibbler** [comment]
thats perfect thanks

**Comment by harshalwagh96** [comment]
Thanks a lot
