### ISSUE TITLE
Tooltip on iOS opens only after double tap

### ISSUE THREAD

**Issue by rodlukas** [reactstrap/reactstrap#1676]
- components: `Tooltip`, `UncontrolledTooltip`
- reactstrap version `8.1.1`
- import method `es` 
- react version `16.10.2`
- bootstrap version `4.3.1`

### What is happening?

iOS (v13, safari): After one tap on the element that should trigger tooltip opening - nothing happens, the tooltip is not shown. After second tap the tooltip is finally opened.
On Android everything works fine - first tap opens the tooltip.

### What should be happening?

The tooltip should show after the first tap on iOS.

### Steps to reproduce issue
issue can be seen here: https://reactstrap.github.io/components/tooltips/ - try to open this page on iOS and tap on the "tooltip" href in the example (or in other examples) - tooltip is not opened, second tap - tooltip opens.

**Comment by Hectix** [comment]
When you touch an item on a webpage on an iPhone, it first triggers a hover state and then triggers the “click”. That is causing a tooltip to "not open" on the first click I think.

**Comment by rodlukas** [comment]
> 
> 
> When you touch an item on a webpage on an iPhone, it first triggers a hover state and then triggers the “click”. That might be causing a tooltip to "not open" on the first click I think.
> 
> ![image](https://camo.githubusercontent.com/3e77ce35dd30aaa9cd2ab36c879decc9f584acd7/68747470733a2f2f6373732d747269636b732e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031362f31302f696f732d646f75626c652d7461702e676966)

Yes, I found the same thing - https://css-tricks.com/annoying-mobile-double-tap-link-issue/ (that's probably also the source of the image you're referring to). However, Bootstrap somehow fixed this behaviour since their tooltips implementation works great with iOS.

**Comment by rodlukas** [comment]
The difference between iOS behaviour of bootstrap and reactstrap is only caused by the `target` tooltip property - bootstrap default value is `hover focus`, reactstrap default value is `click hover focus`. Setting the bootstrap default value on reactstrap Tooltip/UncontrolledTooltip (`target="hover focus"`) results in correct behaviour also on iOS - the first tap opens the tooltip.

Is there any reason why the default trigger value in reactstrap differs from the bootstrap value?

**Comment by TheSharpieOne** [comment]
no reason that I can think of. Want to create a PR to change that value?
