### ISSUE TITLE
How to disable Fade on modal?

### ISSUE THREAD

**Issue by lawlmart** [reactstrap/reactstrap#168]
Did I miss this in the docs? Didn't see it anywhere.

**Comment by eddywashere** [comment]
It's not possible at the moment. It should be added. I'll keep this open to track that.

**Comment by nndung179** [comment]
Could I take this enhancement @eddywashere ?

**Comment by eddywashere** [comment]
@nndung179 all yours 👍

**Comment by sidekickstudio** [comment]
Can i change the Modal animation when i press close button? some example? thanks

**Comment by mrchess** [comment]
+1. I'm also trying to remove the animation. Anyone know how to do it programmatically?

**Comment by cristian-sima** [comment]
Why does it take so long to add this feature?

**Comment by kheang** [comment]
+1.  It looks like https://github.com/reactstrap/reactstrap/pull/339 by @annejohnson addresses this issue nicely.

**Comment by eddywashere** [comment]
added in 4.6
