### ISSUE TITLE
CustomInput - How to use indeterminate state

### ISSUE THREAD

**Issue by martin8877** [reactstrap/reactstrap#1682]
Is it possible to use indeterminate state for CustomInput checkbox? 

Bootstrap [supports](https://getbootstrap.com/docs/4.3/components/forms/#checkboxes) it via indeterminate pseudo class.

**Comment by TheSharpieOne** [comment]
You'd have to set it similar to how it would be set with a regular input. You can get the input ref via `innerRef` prop.

```jsx
import React, { useRef } from "react";
import { CustomInput, Button } from "reactstrap";

const Example = () => {
  const inputRef = useRef();
  return (
    <div>
      <CustomInput
        id="checkbox"
        type="checkbox"
        innerRef={inputRef}
      />
      <div>
        <Button onClick={() => {
          if (inputRef.current) {
            inputRef.current.indeterminate = true;
          }
        }}>Set indeterminate</Button>
      </div>
    </div>
  );
};

export default Example;
```

https://stackblitz.com/edit/reactstrap-v8-3ppxsy?file=Example.js

**Comment by IIARROWS** [comment]
Module 'reactstrap' has no exported member 'CustomInput'. 9.1.5
