### ISSUE TITLE
Flexbox grid support

### ISSUE THREAD

**Issue by madisvain** [reactstrap/reactstrap#169]
Currently Col component does not support flexbox as there is no way to define a <Col> without it having the column number.

http://v4-alpha.getbootstrap.com/layout/flexbox-grid/
_Unlike the default grid system where a grid column starts as full-width in the xs tier, flexbox requires a .col-{breakpoint} class for each tier._

Flexbox would require to have the possibility of defining `<div class="col-xs">` but currently the <Col> element will add col-xs-12 by default.

**Comment by eddywashere** [comment]
Thanks for filing the issue! I could imagine leveraging the size props, and adding a boolean option that would only output the `col-${size}` class. It would look like this:

```jsx
<Row>
  <Col xs>col-xs</Col>
  <Col xs="6">col-xs-6</Col>
  <Col xs>col-xs</Col>
</Row>
```

Are the push/pull/offset classes supported in flexbox grid? If so, maybe `flex` is a prop or the size props accept `flex` or `auto` as a way to output the auto layout class.

```jsx
<Row>
  <Col xs="flex">col-xs</Col>
  <Col xs="6">col-xs-6</Col>
  <Col xs={{offset: 1, size: 'flex'}}>col-xs</Col>
</Row>
```

```jsx
<Row>
  <Col xs="auto">col-xs</Col>
  <Col xs="6">col-xs-6</Col>
  <Col xs={{offset: 1, size: 'auto'}}>col-xs</Col>
</Row>
```

**Comment by ronnyhaase** [comment]
- [x] Add flexbox auto size ability to Col component (PR #175)
- [ ] Add flexbox alignment support to Col & Row component
- [ ] Use a Bootstrap release with flexbox enabled for Docs

**Comment by ronnyhaase** [comment]
Hey guys!

I'm almost done with the last task for full flexbox support: Support flex alignment classes of Bootstrap.

I'd like to ask you for feedback regarding **naming** and **types** for the necessary properties:

Context: http://v4-alpha.getbootstrap.com/layout/flexbox-grid/

My current implementation looks like:

`<Col first="xs" first={['xs', 'sm']} first={{ xs: true, sm: true, /* ... */ }} first />`

Where a boolean `first` could may resolve to `['xs', 'sm', 'md', 'lg', 'xl']` and/or accept `"all"`?

What do you think about it? And also, do you think the props should be prefixed, like `order-first`. Or is it better to just have one prop `order` which expects `first`, `last` and `unordered` as attributes?

`<Col order={ first: ['xs'], last: ['xs', 'sm'], unordered: ['lg', 'xl'] } />`

*Or maybe both???*

For `<Row />` the same question arrises for horizontal & vertical alignment.

`<Row top middle bottom left center right around between />`

and/ or (?)

`<Row alignVertical={{...}} alignHorizontal={{...}} />`

or even (?)

`<Row alignment={ vertical: { middle: ['xs', 'sm'] }, horizontal: ... } />`

Looking forward to your feedback!

**Comment by ronnyhaase** [comment]
My personal preference right now would be single props accepting string or array of string, and bool / 'all' for all sizes.

**Comment by Casy** [comment]
@ronnyhaase first, thanks for all, i really appreciate it.
You finally decided how to do the vertical alignment?

**Comment by eddywashere** [comment]
@ronnyhaase thanks again for your patience and hard work on these components. Following up on our chat, here's the suggestion I mentioned for Col & Row. 

```jsx
<Col xs xsFirst xsLast xsUnordered></Col>
```

and

```jsx
<Row xs xsLeft xsTop></Row>
```

It adds more props but I think it simplifies the usage.

**Comment by eddywashere** [comment]
bootstrap 4 has switched to flexbox. #267 updates Col component to support new classes. Also, as a result of the flexbox switch, there were new flexbox utility classes added to bootstrap. Instead of making these props available on the components that could potentially use it, I think the simple solution is to let users add those classes manually, ex: `className="justify-content-between"`.

I'm going to close this out as I think the v4 alpha branch of reactstrap should satisfy the flexbox needs.
