### ISSUE TITLE
Does not work in shadow DOM

### ISSUE THREAD

**Issue by felixfbecker** [reactstrap/reactstrap#1691]
- components: `TooltipPopover`
- reactstrap version `8.1.1`
- import method `es` 
- react version `16.10.2`
- bootstrap version `4.3.1`

### What is happening?

In a browser extension, we need to render a popover we add to the DOM in a shadow DOM so that CSS only applies to the content in the popover and not affect the whole page.

However, using the popover inside a shadow root errors with `Error: The target 'Popover1' could not be identified in the DOM, check spelling`.
This seems to be because `Popover` is not purely using React features, but relying on `document.querySelector()`, which won't find elements inside shadow roots.

### What should be happening?

Popover should work as expected. I would expect it to work without global DOM selector queries, but instead using React features like refs and Portals.

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
Uncaught Error: The target 'Popover1' could not be identified in the dom, tip: check spelling
    at findDOMElements (utils.js:292)
    at getTarget (utils.js:310)
    at TooltipPopoverWrapper.updateTarget (TooltipPopoverWrapper.js:303)
    at TooltipPopoverWrapper.componentDidMount (TooltipPopoverWrapper.js:112)
    at commitLifeCycles (react-dom.development.js:20040)
    at commitLayoutEffects (react-dom.development.js:22802)
    at HTMLUnknownElement.callCallback (react-dom.development.js:344)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:397)
    at invokeGuardedCallback (react-dom.development.js:452)
    at commitRootImpl (react-dom.development.js:22578)
```

![image](https://user-images.githubusercontent.com/10532611/67677375-2f88bb00-f984-11e9-8101-54810d1b6f64.png)

### Code

https://stackblitz.com/edit/reactstrap-shadow-root-bug

**Comment by felixfbecker** [comment]
I figured out that this specific error can be prevented by using a ref for the target (which is broken in the latest release, but fixed on master). But triggers are still broken, because listeners are registered on the document and check `event.target` which is rewritten to the shadow root host element (as opposed to `event.composedPath()[0]`.

**Comment by freeman** [comment]
We are hit by this issue too. Is there an interest to make reactstrap compatible with shadow dom ?

**Comment by TheSharpieOne** [comment]
You can use a ref or a DOM element instead of a string. The issues @felixfbecker was having have been addressed in the latest version.

**Comment by felixfbecker** [comment]
I think this still applies though:

> But triggers are still broken, because listeners are registered on the document and check event.target which is rewritten to the shadow root host element (as opposed to event.composedPath()[0].

**Comment by TheSharpieOne** [comment]
Yeah, I suppose `element.currentTarget` would not be the shadow element (haven't tested, but MDN's docs didn't mention anything). The problem with `composedPath` is it is not supported by Edge, which is a must.

To get this to work with the shadow dom, I am not sure the best approach.

**Comment by felixfbecker** [comment]
Does Edge support shadow DOM? You could check for the presence of `composedPath` and fallback to `target`
