### ISSUE TITLE
Tooltip disable autohide broken

### ISSUE THREAD

**Issue by rachprospa** [reactstrap/reactstrap#1692]
- components: `Tooltip`
- reactstrap version `#8.1.1` (`#8.0.1` also tested)
- import method `es`
- react version `#16.8.4`
- bootstrap version `#4.3.1`

### What is happening?

Tooltip disable autohide is broken.

### What should be happening?

When `Tooltip` is passed the prop `autohide={false}`, the tooltip should not close when clicking/hovering over/selecting tooltip content (e.g. user tries to highlight and copy text, user tries to click on an anchor link within the tooltip). 

### Steps to reproduce issue

1. Pass `Tooltip` the `autohide={false}` prop
2. Try to click/highlight content inside the tooltip. The tooltip toggles closed.

For convenience, you can [test the component directly here](https://reactstrap.github.io/components/tooltips/):

![Screen Shot 2019-10-29 at 10 42 31 am](https://user-images.githubusercontent.com/51306098/67726271-6076f780-fa39-11e9-8db3-4af3c56d8ff2.png)

### Error message in console
N/A

### Code

Example implementation:
```
import React, { ReactChild } from 'react';
import { Tooltip } from 'reactstrap';

interface Props {
  children: ReactChild;
  targetId: string;
}

const CustomTooltip = ({ children, targetId }: Props) => {
  const [isOpen, setIsOpen] = React.useState(false);
  const toggle = () => {
    setIsOpen(!isOpen);
  };
  return (
    <>
      <span id={targetId}>
        Tooltip trigger
      </span>
      <Tooltip
        trigger="focus"
        autohide={false}
        isOpen={isOpen}
        target={targetId}
        toggle={toggle}
      >
        {children}
      </Tooltip>
    </>
  );
};
export default CustomTooltip;
```

**Comment by illiteratewriter** [comment]
This issue is because the default `hide` delay has been reduced to zero. The previous function worked on the premise that the `hideWithDelay` can be canceled by the time the user hovers over the tooltip (`clearTimeout`).

**Comment by nik72619c** [comment]
Hi, 
Thanks folks for such super fast replies. I tried to update my codebase to the latest `reactstrap` version and started noticing that the tooltip widths are now small. Anyone else facing this thing ?
Thanks !

**Comment by nik72619c** [comment]
cc: @illiteratewriter @rachprospa
