### ISSUE TITLE
Carousel: touch swipe is not working properly

### ISSUE THREAD

**Issue by ReactAcademyCa** [reactstrap/reactstrap#1696]
- components: `carousel`
- reactstrap version `#8.1.1`
- import method `es`
- react version `#16.11.0`
- bootstrap version `#4.3.1`

### What is happening?
On a device with a touch screen, when you try to swipe a carousel, the slide **does not** move to the next or previous one. 

### What should be happening?
On a device with a touch screen, when you try to swipe a carousel, the slide **should** move to the next or previous one.

### Steps to reproduce issue
Go to the reactstrap documentation with a touch enabled device (tablet, phone, Surface) and try to swipe. Touch is ignored. 
https://reactstrap.github.io/components/carousel/

Go to the React Bootstrap documentation and try to swipe. Touch works!
https://react-bootstrap.github.io/components/carousel/

Go to the Bootstrap documentation and try to swipe. Touch works!
https://getbootstrap.com/docs/4.3/components/carousel/#with-controls

**Comment by marcnjaramillo** [comment]
I looked at the documentation for both Reactstrap and Bootstrap React. One difference that I can see is that Bootstrap React has a variable called `SWIPE_THRESHOLD` and two methods specifically for handling touch events: `handleTouchStart` and `handleTouchEnd`. My understanding of touch events isn't that great, but it looks like the first method sets the state for `touchStartX`, and the second compares this state to the `SWIPE_THRESHOLD` and then moves the slide left, right, or not at all depending on the results of the comparison.

I couldn't see anything like this in the Reactstrap documentation, which would explain why the carousel can respond to only click events but not touch events.

**Comment by Ashniu123** [comment]
Close issue?

**Comment by TheSharpieOne** [comment]
hmm, usually merging closes the issues. I don't think the commit message was right. Needed something like "fixes #1696"
