### ISSUE TITLE
No NavText element

### ISSUE THREAD

**Issue by octylFractal** [reactstrap/reactstrap#1707]
- components: `Navbar`
- reactstrap version `#8.1.1`
- import method `es`
- react version `#16.12.0`
- bootstrap version `#4.3.1`

### What is happening?

There is no shorthand variant for `<div className="nav-text">`.

### What should be happening?

I expected a `<NavText>` component as the text-only counterpart to `<NavLink>`. IMO it is not a huge deal, since I don't think it has any specific configurable options, but the ability to set e.g. `color` would be nice.

**Comment by BamMironov** [comment]
@octylFractal Styles of the "navbar-text" element depend on "Nav" component styles. That is why it's better to not to add an extra prop for changing the color,
