### ISSUE TITLE
Wrapper for button

### ISSUE THREAD

**Issue by ronaklalwaniii** [reactstrap/reactstrap#1709]
Hello, 
I want to wrap your button with my own wrapper to add waves effect to the button by extending your component. 
how can I do that without creating a custom component?
I am using React Ripples for this you can check it out from here: [https://rwu823.github.io/react-ripples/](https://rwu823.github.io/react-ripples/
)
Regards

**Comment by TheSharpieOne** [comment]
based on the docs posted, you'd have to create a custom component:
```jsx
import React from 'react';
import PropTypes from 'prop-types';
import { Button } from 'reactstrap';
import Ripples from 'react-ripples'

const RippleButton = ({ rippleColor, during, ...rest }) => (
  <Ripples color={rippleColor} during={during}>
    <Button {...rest} />
  </Ripples>
);

RippleButton.propTypes = {
  ...Button.propTypes,
  rippleColor: PropTypes.string,
  during: PropTypes.number,
};

export default RippleButton;
```

Demo https://stackblitz.com/edit/reactstrap-v8-qlefmt?file=Example.js

**Comment by ronaklalwaniii** [comment]
Hi, @TheSharpieOne

Thanks for the quick reply. I know I can do it by creating a custom component. 

But is there a way to do it without creating a custom component by extending the button component?

I want to get Ripple Effect every time I import a button from Reactstrap.

**Comment by TheSharpieOne** [comment]
AFAIK no, that is not possible.
But with the solution above, you would just simply change the import to something like `import RippleButton from 'components/RippleButton';` You don't have to redefine it every time you need it.
If you need it in multiple projects, you can create your own package with that code and publish it to npm; something like `reactstrap-ripple-button` and just import and use that everywhere.
Another solution would be to define an additional property on `Button`, allowing you to reference the custom component through the standard `Button` import. See https://stackblitz.com/edit/reactstrap-v8-y8ypj5?file=Example.js

**Comment by ronaklalwaniii** [comment]
Thanks, @TheSharpieOne I used the second option to make it work 😃.
