### ISSUE TITLE
Race condition in documentation wiki

### ISSUE THREAD

**Issue by dlifshitz-maca** [reactstrap/reactstrap#1712]
- reactstrap version `#8.1.1`

### What is happening?

I just started trying out reactstrap and went to make a Navbar with a NavbarText like the online doc shows. Turns out NavbarText was just added to master 2 hours ago so it's not in the latest version (ie `#8.1.1`) and I get an error.

### What should be happening?

Should have a `latest` branch which points to the latest release and have the wiki point to that instead of master.

**Comment by TheSharpieOne** [comment]
It would be nice to have #195, but until then I made it so travis CI will only publish the docs on tagged commits. Since tag commits only happen for releases, it should keep them in sync.

**Comment by dlifshitz-maca** [comment]
Ok, great. Thanks!
