### ISSUE TITLE
Cant focus Input after clicking Button

### ISSUE THREAD

**Issue by carlosfer02** [reactstrap/reactstrap#1716]
- components: `Input`
- reactstrap version `#8.0.0`
- react version `#16.8.6`
- bootstrap version `#4.3.1`

### What is happening?

I am trying to focus my input after sending a message (clicking a button) and even though i am using [ref](https://reactjs.org/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element)
Btw. AutoFocus is working fine.

### What should be happening?

The input should be focused after clicking a button

### Code

```
import React, { Component } from 'react';
import { Table,InputGroup, Input, InputGroupAddon, Button } from 'reactstrap';

class ChatTable extends Component {
  constructor(props) {
    super(props);
    
    this.textInput = React.createRef();
  }
  
  componentDidMount() {
    this.textInput.current.focus();
  }

  sendMessageHandler = () => {
    this.textInput.current.focus();
  }

  render() {
    return (
      <div className="animated fadeIn">
        <Input type="textarea" name="textarea-input" id="textarea-input" rows="3" placeholder="Mensaje" value={this.state.msg} onChange={this.updateMessageHandler} ref={this.textInput} autoFocus={true}/>
      </div>
    );
  }
}

export default ChatTable;
```

**Comment by TheSharpieOne** [comment]
`ref` will get you a reference to the instance of reactstrap's `Input`, not the raw DOM `input`. Use `innerRef` to get the reference to the actual `input`.
