### ISSUE TITLE
import error: 'NavbarText' is not exported from 'reactstrap'

### ISSUE THREAD

**Issue by BrettMCoding** [reactstrap/reactstrap#1717]
The docs at https://reactstrap.github.io/components/navbar/ show the last import as NavbarText. I get the title error when trying to use.

Searching my reactstrap node_module I see no NavbarText and in index.js I see no NavbarText export.

I used npm and my version is reactstrap@8.1.1

**Comment by januszdotnl** [comment]
Yep same issue here. File is not there. It is on Github though.

**Comment by TheSharpieOne** [comment]
Sorry, that has not be released yet. I'll try to create a release when I am at a computer and can create the bundles.
The Docs right now are ahead of the releases, but 546b15c57 should prevent that from happening in the future. Once the next release is made, the docs should be in lock-step.

**Comment by MarcStd** [comment]
Hi any updates, when the new release will be created?
