### ISSUE TITLE
Example from docs on Navbar broken?

### ISSUE THREAD

**Issue by giorgi-m** [reactstrap/reactstrap#1719]
- reactstrap version 8.1.1
- react version 16.8
- bootstrap version 4.4

### What is happening?

I basically copy pasted code from this example:
https://reactstrap.github.io/components/navbar/

and got:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Here is demo
https://codesandbox.io/s/elated-sanderson-uj669

**Comment by TheSharpieOne** [comment]
8.2.0 has been releases which has the new NavbarText component.
