### ISSUE TITLE
Tooltip is not positioned correctly if target has nested elements

### ISSUE THREAD

**Issue by vasilii-kovalev** [reactstrap/reactstrap#1736]
- components: `Tooltip`
- reactstrap version `#8.2.0`
- react version `#16.12.0`
- bootstrap version `#4.4.1`

### What is happening?

If a target element contains nested ones and user clicks on one of them (in real world it can be an icon near text in a button, for example), tooltip appears near the nested (clicked) element.

### What should be happening?

Tooltip appears near the highest element (a button in our example, not icon or other nested element).

### Steps to reproduce issue

Here you can find demo with the described behavior:
https://codesandbox.io/s/reactstrap-nested-target-issue-rjg1o
1. Click on "First line" text inside the button (and click again to hide the tooltip).
2. Click on "Second line" text inside the button (and click again to hide the tooltip).
3. Click on empty space between the lines inside the button (and click again to hide the tooltip).

Tooltip appears at different places.

### Additional information
It appears if `trigger` is "click". If it is "hover", the tooltip is positioned correctly.

Thank you in advance.

**Comment by vasilii-kovalev** [comment]
I debugged the library a little bit and found out that here in `show` function `this.currentTargetElement` starts to refer to the inner elements ("First/Second line" div in my case):
https://github.com/reactstrap/reactstrap/blob/8a1233041c67e3d69cdbf9e2cc6109785fabd063/src/TooltipPopoverWrapper.js#L162-L168

In `updateTarget` `newTarget` (array with the button) is not equal to `this._targets` (array with the same button):
https://github.com/reactstrap/reactstrap/blob/8a1233041c67e3d69cdbf9e2cc6109785fabd063/src/TooltipPopoverWrapper.js#L296-L304

Because of __or__ (`||`) expression `this.currentTargetElement` stays the same.

And then `this.currentTargetElement` is used in render function:
https://github.com/reactstrap/reactstrap/blob/8a1233041c67e3d69cdbf9e2cc6109785fabd063/src/TooltipPopoverWrapper.js#L345-L348

That's why a tooltip is placed near inner elements, not near the button.

**Comment by TheSharpieOne** [comment]
Yeah, we should probably be using `e.currentTarget` which would give us the element that with the listener that was triggered instead of `e.target` which gives us the element that was clicked.

**Comment by vasilii-kovalev** [comment]
@TheSharpieOne, when can I expect a fix? Is it possible to include it to the nearest minor/patch version?

**Comment by val1984** [comment]
This bug has come back for us in version `^8.4.0`. Version `^8.3.0` had fixed this bug.
