### ISSUE TITLE
No way to access tether object to trigger a manual position()

### ISSUE THREAD

**Issue by ConneXNL** [reactstrap/reactstrap#174]
There is currently no way for a Tooltip to trigger a manual "position()" to re-position the tooltip.

One way would be to add a ref on the tether object and make a function getTetherInstance on the Tooltip.

```
    getTetherInstance(){
        if (this.tetherContent && this.tetherContent._tether){
            return this.tetherContent._tether;
        }
        return null;
    }

    <TetherContent
         ref={(ref) => this.tetherContent = ref}
    >
```

What do you think?

**Comment by eddywashere** [comment]
👍 I think it's worth exposing the raw tether instance. It would also be good to have a convenience method for updating position (sounds common enough).

**Comment by TheSharpieOne** [comment]
I don't believe it is possible to override the ref functionality allow it to return something else. A proposed solution is to add `tetherRef`... which is a ref to get the tether instance as created by TetherContent. Tooltip and Popover have also been extended to pass the prop along so you can use tetherRef on them to get access to the tether instance. This allows you to perform the `position()` call. Note, that much like the native ref functionality, tetherRef will be called both when an instance is created (providing the instance in the call), as well as when it is destroyed (passing null). Then means, you should perform a null check before trying to access it.
