### ISSUE TITLE
Applying the hidden attribute to CustomInput

### ISSUE THREAD

**Issue by ainslie1171** [reactstrap/reactstrap#1741]
### Issue description

- components: `CustomInput`
- reactstrap version `#8.2.0`
- react version `#16.12.0`
- bootstrap version `#4.4.1`

### What is happening/What should be happening?

When a CustomInput component is given the hidden attribute you get different behavior based on the type. Types range and select work as expected, however, checkbox, file, radio and switch are all still shown when the hidden attribute is applied to the CustomInput component. The hidden attribute is being passed on to the Input element in all cases but I think due to the offending types being wrapped in divs, the effect of the hidden attribute is being negated and in those instances, it needs to instead be applied to the div to get the same effect for all types.

**Comment by TheSharpieOne** [comment]
closed via bb39b55
