### ISSUE TITLE
New modal static backdrop animation issue

### ISSUE THREAD

**Issue by Fakkio** [reactstrap/reactstrap#1754]
- components: `modal`
- reactstrap version `#8.3.1`
- import method `es` 
- react version `#16.12.0`
- bootstrap version `#4.4.1`

### What is happening?

The new modal animation when the backdrop is set to `static` is triggered even when you click inside modal. 

### What should be happening?

The animation should have been triggered only when you click outside.

### Steps to reproduce issue

1. Go to [https://reactstrap.github.io/components/modals/](https://reactstrap.github.io/components/modals/)
2. Scroll down to "Backdrop" section
3. Select "static" from dropdown and click "Open modal"
4. Click inside modal and stare at the unwanted animation

**Comment by kyletsang** [comment]
Sorry missed this.  I'll take care of it
