### ISSUE TITLE
Close the modal using Esc button when keyboard={true} and backdrop="static"

### ISSUE THREAD

**Issue by TheSharpieOne** [reactstrap/reactstrap#1766]
The behavior was changed since version 4.2.0: before I was able to close the modal using Esc button when keyboard={true} and backdrop="static", but now I can't. Is it expected?

_Originally posted by @ALEUT in https://github.com/reactstrap/reactstrap/pull/1750#issuecomment-577115892_

Also reference: https://github.com/twbs/bootstrap/issues/29978

**Comment by kyletsang** [comment]
The bootstrap bug fix was made post-4.4.1.  I'll take this one if you haven't already @TheSharpieOne

**Comment by TheSharpieOne** [comment]
@kyletsang all your 👍
