### ISSUE TITLE
Input type="number" can enter any special characters and letters.

### ISSUE THREAD

**Issue by tharindusenadeera** [reactstrap/reactstrap#1786]
- components: Input
- reactstrap version `6.4.0`
- react version `16.8.2`
- bootstrap version `4.1.3`

Input type number can enter any special characters and also letters in Safari web browser, but if I type a letter or character it is not taking as a value. In chrome it is working properly.

**Comment by TheSharpieOne** [comment]
This is the browser's doing. Reactstrap, just like bootstrap doesn't not try to fix this. It is up to you to implement your own validations (or use a third-party validation library such as `yup` with `formik` or (shameless plug) [`@availity/form`](https://availity.github.io/availity-react/form/components/field/))

**Comment by kyletsang** [comment]
Closing as answered
