### ISSUE TITLE
esktop\reactstrap\core\src' This error occurred during the build time and cannot be dismissed.

### ISSUE THREAD

**Issue by vamsikrishnadola** [reactstrap/reactstrap#1794]
Module not found: Can't resolve '@coreui/icons/css/coreui-icons.css' in 'C:\Users\Jagan\Desktop\reactstrap\core\src'
This error occurred during the build time and cannot be dismissed.

**Comment by TheSharpieOne** [comment]
It looks like you named your project "reactstrap", that's cool, but that doesn't mean you are using reactstrap. Based on the information provided, it looks like you are not using reactstrap and are simply missing a dependency you added to your project.
Have you tried installing the dependency you are missing?
