### ISSUE TITLE
PaginationLink Props not working properly

### ISSUE THREAD

**Issue by oakkar8** [reactstrap/reactstrap#1801]
- components  PaginationLink
- reactstrap version #7.1.0
- react version #16.12.0
- bootstrap version #4.4.1

### What is happening?
PaginationLink props type first and last icon are not showing.

![Screenshot from 2020-03-02 15-23-18](https://user-images.githubusercontent.com/35274540/75727486-e7630780-5c99-11ea-8db8-016c198bb4bf.png)

### Steps to reproduce issue
PaginationItem
    PaginationLink onClick={e => this.handlePageChange(e,0,"left")} first href="#" /
/PaginationItem

**Comment by kyletsang** [comment]
Use the latest version of reactstrap.  Pagination `first` and `last` appeared in v8

**Comment by oakkar8** [comment]
I updated to 8.4.1 but still not showing the first icon.

**Comment by kyletsang** [comment]
This works for me.  https://stackblitz.com/edit/react-7xux36

**Comment by oakkar8** [comment]
ohh nvm.. It's fixed now.. Thanks.
