### ISSUE TITLE
Clicking outside popover toggle popover

### ISSUE THREAD

**Issue by aentan** [reactstrap/reactstrap#1807]
- components: `Popover`
- reactstrap version `^8.4.1`
- import method `es` 
- react version `^16.13.0`
- bootstrap version `^4.4.1`

### What is happening?

`toggle` prop does not dismiss popover when clicked outside.

### What should be happening?

`toggle` props= dismisses a Modal. I guess the behavior should be consistent with popover?
Bootstrap uses `trigger: 'focus'`. Can we match this somehow?

### Code

[https://stackblitz.com/edit/reactstrap-ckciq5?file=Example.js](https://stackblitz.com/edit/reactstrap-ckciq5?file=Example.js)

**Comment by 4Michael1Angelo5** [comment]
I tried using a popover last night and have this same problem.  Can't figure it out.
my code is the same as your's but I'm using a function component. 

reactstrap version : 8.1.1
react version: 16.12.0
bootstrap version: 4.3.1

**Comment by 0x111** [comment]
Did you try to set `trigger="focus"`, you are missing the trigger param from the popover.

[Example with use-case](https://stackblitz.com/edit/reactstrap-yk52xc?file=Example.js)
Although this is just one of the options. 
Reactstrap already supports setting a trigger, see the example on [reacstrap here](https://reactstrap.github.io/components/popovers/):
```javascript
Popover.propTypes = {
  // space separated list of triggers (e.g. "click hover focus")
  trigger: PropTypes.string,
  //....
}
```

**Comment by 4Michael1Angelo5** [comment]
Ahh yes, he is missing that. I thought I saw it in his code before.  Once you add that his example works as it should. But unfortunately in my case, it does not.  I can copy and paste some code but visually it is not much different. What other information should I provide?

**Comment by 4Michael1Angelo5** [comment]
`const CustomOrderNav = (props) => {

    const [slabTooltipOpen, setSlabTooltip] = useState(false);

     const toggleSlabTooltip = () => setSlabTooltip(!slabTooltipOpen);

     const [seriesTooltipOpen, setSeriesTooltip] = useState(false);

    const toggleSeriesTooltip = () => setSeriesTooltip(!seriesTooltipOpen);

    

    return(
        <React.Fragment>

            <div className = "row d-flex justify-content-around custom-order-nav">
                <div id = "step1-select-series" className = " custom-order-nav-item" onClick= {props.handleStep}>
                    Series
                </div>
                {/* <div id = "step2-select-slab" onMouseLeave = {props.activeSeries.length === 0? toggleSeriesTooltip:null } onMouseEnter = {props.activeSeries.length === 0? toggleSeriesTooltip:null } className = " custom-order-nav-item" onClick= {props.activeSeries.length === 0? toggleSeriesTooltip :props.handleStep}>
                    Slabs
                </div> */}
                  <div id = "step2-select-slab" className = " custom-order-nav-item" onClick= {props.activeSeries.length === 0? toggleSeriesTooltip :props.handleStep}>
                    Slabs
                </div>
                {/* <div className = " custom-order-nav-item" onMouseLeave ={props.activeSeries.length === 0?toggleSlabTooltip:null} onMouseEnter = {props.activeSeries.length === 0?toggleSlabTooltip:null} onClick= {props.activeProduct.length ===0? toggleSlabTooltip :props.handleStep}>
                    Cut
                </div> */}

                <div className = " custom-order-nav-item" onClick= {props.activeProduct.length ===0? toggleSlabTooltip :props.handleStep}>
                    Cut
                </div>
                <div className = " custom-order-nav-item" onClick= {props.handleStep}>
                    Finish
                </div>
                <div className = " custom-order-nav-item" onClick= {props.handleStep}>
                    Hardware
                </div>
            </div>

            <div className = "custom-order-progress-bar active"

                style = {{transform: `translate(${props.translateAmount})`}}
                >

            </div>
 
                <Tooltip trigger = "focus" isOpen = {slabTooltipOpen}   target = "step2-select-slab" > 
                    <p>You Must Select Slab First
                    
                    </p> 
                    <div className = "x-btn" onClick = {toggleSlabTooltip}/>
                </Tooltip>

                {/* <Tooltip  trigger = "focus"  isOpen = {seriesTooltipOpen}    target="step1-select-series">
                    <p>You Must Select Serires First
                    
                    </p>   
                    <div className = "x-btn" onClick = {toggleSeriesTooltip}/>                 
                </Tooltip> */}

                <Popover trigger = 'focus' isOpen = {seriesTooltipOpen} target="step1-select-series">
                <p>You Must Select Serires First
                    
                    </p>  
                </Popover>

        </React.Fragment>
    );
[}`]

**Comment by 4Michael1Angelo5** [comment]
I did some playing around and noticed that I have the tooltip/popover triggered by the onClick event inside the div. I looked back over the examples and noticed that it isn't done that way. I don't think there's an issue with the way tooltip/popover is working now with trigger = 'focus'. There's a problem with my code. I replaced the divs with buttons and got rid of the conditional onClick methods and the behavior works as expected but I will have to explore more solutions as this doesn't quite give me the solution I am looking for. Thanks for your time

**Comment by aentan** [comment]
> Did you try to set `trigger="focus"`? you are missing the trigger prop from the popover
> 
> [Example with use-case](https://stackblitz.com/edit/reactstrap-yk52xc?file=Example.js)
> Although this is just one of the options.
> Reactstrap already supports setting a trigger, see the example on [reacstrap here](https://reactstrap.github.io/components/popovers/):
> 
> ```js
> Popover.propTypes = {
>   // space separated list of triggers (e.g. "click hover focus")
>   trigger: PropTypes.string,
>   //....
> }
> ```

Example works in Chrome but not Safari (popover doesn't open). So is this a bug?
