### ISSUE TITLE
cannot put tab inside modal

### ISSUE THREAD

**Issue by buncismamen** [reactstrap/reactstrap#1811]
- components: `Modal` and `Tabs`
- reactstrap version `#8.4.1`
- import method `I don't know  I just use create react app npm install and call it with import`
- react version `#16.13.0`
- bootstrap version `maybe 4`

### What is happening?

Cannot put tab inside modal body, it only show blank modal body

### What should be happening?

can render tab inside modal

### Steps to reproduce issue

1. create modal
2. put tab inside modal child component

### Code

```
import React, { useState } from 'react';
import { Button, Modal, ModalHeader, ModalBody, ModalFooter } from 'reactstrap';

const ModalExample = (props) => {
  const {
    buttonLabel,
    className
  } = props;

  const [modal, setModal] = useState(false);

  const toggle = () => setModal(!modal);

  return (
    <div>
      <Button color="danger" onClick={toggle}>{buttonLabel}</Button>
      <Modal isOpen={modal} toggle={toggle} className={className}>
        <ModalHeader toggle={toggle}>Modal title</ModalHeader>
        <ModalBody>
            <TabContent activeTab={1}>
              <TabPane tabId="1">
                <Row>
                  <Col sm="12">
                    <h4>Tab 1 Contents</h4>
                  </Col>
                </Row>
              </TabPane>
              <TabPane tabId="2">
                <Row>
                  <Col sm="6">
                    <Card body>
                      <CardTitle>Special Title Treatment</CardTitle>
                      <CardText>
                        With supporting text below as a natural lead-in to
                        additional content.
                      </CardText>
                      <Button>Go somewhere</Button>
                    </Card>
                  </Col>
                  <Col sm="6">
                    <Card body>
                      <CardTitle>Special Title Treatment</CardTitle>
                      <CardText>
                        With supporting text below as a natural lead-in to
                        additional content.
                      </CardText>
                      <Button>Go somewhere</Button>
                    </Card>
                  </Col>
                </Row>
              </TabPane>
            </TabContent>
          </ModalBody>
        <ModalFooter>
          <Button color="primary" onClick={toggle}>Do Something</Button>{' '}
          <Button color="secondary" onClick={toggle}>Cancel</Button>
        </ModalFooter>
      </Modal>
    </div>
  );
}

export default ModalExample;
```

**Comment by 0x111** [comment]
Hi!

This is due to the fact that the `activeTab` has to be set using a string, like `'1'` or `'2'`. This is also something you can see on the example page for Tabs [here](https://reactstrap.github.io/components/tabs/).

If you take a closer look, the example is setting the active tabs as string and not number like in your sample. 

I've created your example here: https://stackblitz.com/edit/react-ka3uh6

I hope this helps with your issue!

**Comment by buncismamen** [comment]
oh shit 
it's shame that I open this issue for that silly mistake,

my bad

(this is because deadline pressure pushing me to open this issue instead keep exploring)

**Comment by marwenfray** [comment]
> Hi!
> 
> This is due to the fact that the `activeTab` has to be set using a string, like `'1'` or `'2'`. This is also something you can see on the example page for Tabs [here](https://reactstrap.github.io/components/tabs/).
> 
> If you take a closer look, the example is setting the active tabs as string and not number like in your sample.
> 
> I've created your example here: https://stackblitz.com/edit/react-ka3uh6
> 
> I hope this helps with your issue!

Thanks for the example, can I use a part of the code?

**Comment by 0x111** [comment]
Feel free to do that 🙂 it is really just an example
