### ISSUE TITLE
FormFeedback should use "visibility: hidden" rather than "display: none"

### ISSUE THREAD

**Issue by kylanhurt** [reactstrap/reactstrap#1815]
- components: `FormFeedback`
- reactstrap version `8.0.0`
- react version `16.8.6`
- bootstrap version `4.3.1`

### What is happening?

When there is no feedback, the `FormFeedback` div uses `display: none` and so does not take up any height. Once it switched to `display: block` it causes everything beneath it to get pushed down.

### What should be happening?

When there is feedback vs. not should both take up the same height and therefore not cause any subsequent elements to be pushed down.

Shouldn't be too difficult, just one line of CSS change. Right now I am using `!important` CSS rules to enforce the style in both cases to be consistent.

**Comment by kyletsang** [comment]
This styling comes from bootstrap

**Comment by TheSharpieOne** [comment]
Please open this issue with bootstrap itself as the styles come from bootstrap and are outside of reactstrap's control.

**Comment by tkolleh** [comment]
A solution i've used for this problem.

```js
                      <FormFeedback
                        className={"d-block ".concat(
                          email.invalid ? "visible" : "invisible")}>
                        Enter a valid e-mail address
                      </FormFeedback>

```
