### ISSUE TITLE
Modal appears below Popover

### ISSUE THREAD

**Issue by spchaplin** [reactstrap/reactstrap#1818]
- components: `popover`, `modal`
- reactstrap version `#8.4.1`
- import method `es` 
- react version `#16.13.1`
- bootstrap version `#4.4.1`
- bootswatch bootstrap theme `#4.4.1` [`flatly`](https://bootswatch.com/flatly) (css only)

### What is happening?

A modal, which from a ui standpoint I believe should appear above everything else, appears below the popover that triggered it.  The popover also is not greyed out.

Specifically, a popover has a 'remove' button that triggers a modal asking the user if she really wants to delete a project.  The modal should be the only focus, but it's covered by the popover.

### What should be happening?

The popover should be beneath the modal, and the popover should be greyed out with the rest of the screen behind the modal.

### Steps to reproduce issue

Click a button in the popover that triggers the modal

### Error message in console

None 

### Code Details
When the modal is triggered, this element appears on the page containing the modal:
```<div tabindex="-1" style="position: relative; z-index: 1050; display: block;">```

The text that fills the style attribute appears to be populated with JS, as it flashes purple in the Chrome inspector when the modal first appears: `position: relative; z-index: 1050; display: block;`

![image](https://user-images.githubusercontent.com/26261343/79622277-3a730b80-80dc-11ea-9d30-b8d51893b14f.png)

### Possible solution
Changing the z-index of the modal in the Chrome inspector to `1070!important` seems to fix everything:

![image](https://user-images.githubusercontent.com/26261343/79622929-2086f800-80df-11ea-9d5c-5f7937f0a1bc.png)

### Further Details
Looking in reactstrap.js, the relevant code seems to be line 5766
``` var propsToOmit = Object.keys(propTypes$K);
  var defaultProps$F = {
    isOpen: false,
    autoFocus: true,
    centered: false,
    scrollable: false,
    role: 'dialog',
    backdrop: true,
    keyboard: true,
    zIndex: 1050,                          // THIS LINE
    fade: true,
    onOpened: noop$1,
    onClosed: noop$1,
    modalTransition: {
      timeout: TransitionTimeouts.Modal
    },
```

### Temporary Workarounds
Monkey patching the reactstrap pacakage does not seem like a good idea.  One workaround would be to apply a style rule to the contents of the style attribute, e.g., `div[style="position: relative;z-index: 1050;display: block;"]`, however this is also a very fragile solution that could break if reactstrap were ever updated.

Your help with this issue is greatly appreciated!

**Comment by kyletsang** [comment]
The modal component exposes a prop called `zIndex` that you can use to override the default value.

```
zIndex: PropTypes.oneOfType([
  PropTypes.number,
  PropTypes.string,
]),
```

See https://reactstrap.github.io/components/modals/

**Comment by spchaplin** [comment]
kyletsang,

Thank you for pointing me to the built-in functionality that addresses this issue, already present in the documentation.  I really appreciate your help and it fixed the issue for me!!

**Comment by spchaplin** [comment]
Kylestang's comment resolves the issue.
