### ISSUE TITLE
Add custom media query breakpoint

### ISSUE THREAD

**Issue by Pil0tJones** [reactstrap/reactstrap#1822]
Hi,

I was wondering if it is possible to add a custom media query and if so how? The xl-breakpoint is around 1200px, I would like to add another around 1450px..
I was searching around but couldn't find any info.

Thanks!

**Comment by sevdog** [comment]
This could be achieved by customizing Bootstrap's sass variable `$grid-breakpoints`, see [docs](https://getbootstrap.com/docs/4.4/getting-started/theming/#maps-and-loops) (and [code](https://github.com/twbs/bootstrap/blob/dca1ab7d877bc4b664b43604657a2b5fbe2b4ecb/scss/_variables.scss#L198-L204
)).

IE:
```
$grid-breakpoints: (
  xxl: 1450px,
);
```

**Comment by kyletsang** [comment]
Closing since this is answered.

**Comment by luczaki114** [comment]
Modifying bootstrap is one thing, but what about adding a new custom breakpoint like xxs, or xxl? we can do that in bootstrap, but reactstrap is tied to just the standard breakpoints.

**Comment by kyletsang** [comment]
@luczaki114 

You can pass an override in a prop called `widths`.  This takes an array of the breakpoints.

For example:
```
<Col widths={['xxs', 'xs', 'etc']} xxs={4} etc={2} />
```

This code iterates over the array:
https://github.com/reactstrap/reactstrap/blob/112b6f7ef3feac4a00cefc460860aa840853d176/src/Col.js#L57

**Comment by luczaki114** [comment]
Awesome! Thanks for the quick response!
