### ISSUE TITLE
Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>

### ISSUE THREAD

**Issue by adityakumartraveloka** [reactstrap/reactstrap#1825]
Selected Option is
`<option key={1} selected>Hello</option>`

And not selected options are
`<option key={"pds " + pds.name} >{pds.name}</option>`

and the warning is
`Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>`

Can anyone help?

**Comment by TheSharpieOne** [comment]
This is just basic react, nothing to do with reactstrap. Just use the defaultValue prop on the `select` instead of `selected` on an option.

```jsx
<select defaultValue="Hello">
  <option key={1}>Hello</option>
  <option key={"pds " + pds.name} >{pds.name}</option>
</select>
```

**Comment by adityakumartraveloka** [comment]
@TheSharpieOne sorry for my unambiguous question what if the I'm using `reactstrap multiselect`
