### ISSUE TITLE
defaultValue in input not working with template literals

### ISSUE THREAD

**Issue by abanchev** [reactstrap/reactstrap#1828]
- components: `Input`
- reactstrap version `#8.4.1`
- import method 'es` 
- react version `#16.13.1`

### What is happening?

I have a view that receives state params from redux, however when i try to change the **default value** using template literals ( `${myVariable}`) it doesnt update after the initial render.
If i put myVariable directly it works as expected when the variable changes.

### What should be happening?

The default value should show the latest content of the variable that i pass it.
If I set **value** instead of **defaultValue** it works as expected.
### Code

```
 <Input
  defaultValue={`${company?.vat_id}`}//Stays undefined, even after company is populated
  type="text"
 />
 <Input
  defaultValue={company?.vat_id}//shows the value correctly
  type="text"
 />
```

**Comment by kyletsang** [comment]
You should be using `value` instead of `defaultValue` for controlled inputs
