### ISSUE TITLE
Pagination Apply ClassName Incorrectly to the Nav tag instead of ul tag

### ISSUE THREAD

**Issue by qvn** [reactstrap/reactstrap#1829]
- components: `pagination`
- reactstrap version `^8.4.1`
- react version `#16.11.0`
- bootstrap version `#4.3.1`

### What is happening?

Pagination rendered to list but has no access to the `ul` element. 
```html
 <Pagination aria-label="Page navigation example" className="m-0">
    <PaginationItem>
        <PaginationLink first href="#" />
      </PaginationItem>
 </Pagination>
```
and rendered to
```html
<nav class="m-0">
<ul class="pagination">
   <li class="page-item">...</li>
</ul>
</nav>
```
And then `ul` inherit whatever `ul` style globally. There is no way to access the `ul` element directly. 

### What should be happening?

Bootstrap exposed the `ul` component like so:
```html
<nav aria-label="Page navigation example">
  <ul class="pagination m-0">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
  </ul>
</nav>
```
So I would expect the class to be applied to the **ul** not the **nav** tag. Otherwise, we might need another tag underneath the nav tag. 

### Steps to reproduce issue

Inspect the Pagination page on reactstrap

### Code
See above

**Comment by kyletsang** [comment]
You can use the `listClassName` prop to apply class name to the list element.
