### ISSUE TITLE
Clicking NavLink triggers a complete rerender

### ISSUE THREAD

**Issue by vlddamianvs** [reactstrap/reactstrap#1834]
- components: `NavLink`
- reactstrap version `#8.4.1`
- import method `es` 
- react version `#16.13.1`
- bootstrap version `none`

### What is happening?
When clicking on the NavLink the whole application gets rerendered , as if a window.location is being done.

### What should be happening?
To behave like <Link> from react-router-dom, which does not rerender. 
Also if I put a <Link> inside the NavItem it behaves correctly.
Also if I put a tag={Link} inside NavLink, which probably is the same as above, it behaves correctly.

### Steps to reproduce issue
see code below.

### Error message in console
None

### Code

```
import React from 'react';
import ReactDOM from 'react-dom';
import {BrowserRouter} from "react-router-dom";
import {Nav, NavItem, NavLink} from "reactstrap";

ReactDOM.render(
    <BrowserRouter>
        <div>
            <Nav className="mr-auto" navbar>
                <NavItem>
                    <NavLink href="/home">Home via NavLink</NavLink>
                </NavItem>
            </Nav>
        </div>

    </BrowserRouter>,
    document.getElementById('root')
);
```

Am I doing something wrong while using NavLink ? Thank you for any help !

**Comment by iamandrewluca** [comment]
`reactstrap` is not concerned about navigation. Please before opening a issue, first search if a issue already exists.

https://github.com/reactstrap/reactstrap/issues/298#issuecomment-273733613

**Comment by vlddamianvs** [comment]
Ok, thanks. 
Although I think it would be interesting to understand why the whole app is being reloaded when clicking on a link.

**Comment by iamandrewluca** [comment]
> why the whole app is being reloaded when clicking on a link.

Because it is a link :slightly_smiling_face:
