### ISSUE TITLE
New component request - Accordian

### ISSUE THREAD

**Issue by akhlesh** [reactstrap/reactstrap#1846]
- components: `Accordian`

### What is happening?
There is already a  Collapse component but it requires manual styling and handling if we want to make it like an Accordian. So would it be possible to add an Accordian component.

**Comment by iamandrewluca** [comment]
I'll close in favor of #334
Right now we don't have enough resources for development.
But you can try this [`Accordion`](https://gist.github.com/iamandrewluca/3f760b9218e926e1c4230a1ae3b025be) I created
