### ISSUE TITLE
The DropdownMenu component does not get positioned properly when styles are manually assigned

### ISSUE THREAD

**Issue by lehresman** [reactstrap/reactstrap#1849]
- components: `ButtonDropdown` with `DropdownMenu`
- reactstrap version `#8.4.1`
- import method `es`
- react version `#16.8`
- bootstrap version `#4.1`

### What is happening?

Popper styles are not getting applied when manually passing styles to `<DropdownMenu>`.  The menu does not get positioned properly because the Popper styles are not getting applied.

### What should be happening?

The menu should get positioned properly.

### Steps to reproduce issue

Use `<ButtonDropdown>` component with `direction="up"`.  On the nested `<DropdownMenu>` component, set any manual style override (e.g. `<DropdownMenu style={{padding: 10}}>`).

Notice that the dropup does not get positioned properly.  The popper styles are not getting applied.

### Code

Here is an example with it broken:  https://reactstrap-f1ftux.stackblitz.io
Here is an example with it working: https://reactstrap-li2s1n.stackblitz.io

Notice the only difference is that `<DropdownMenu style={{padding: 10}}>` vs `<DropdownMenu>`

**Comment by DaddyWarbucks** [comment]
I am experiencing a similar issue using `DropdownMenu` with the `right` prop.

https://stackblitz.com/edit/reactstrap-rwbltm
