### ISSUE TITLE
How can i custom breakpoint for Layout?

### ISSUE THREAD

**Issue by nguyengiahuynh** [reactstrap/reactstrap#1856]
Hello everyone, currently i want to **custom breakpoint** like that:
```
xs, extra-small: 0px
sm, small: 600px
md, medium: 960px
lg, large: 1280px
xl, extra-large: 1920px
```

How can i do? 
Thank you

**Comment by iamandrewluca** [comment]
You have to do that using bootstrap scss/css. `rectstrap` is just a wrapper for components.

https://github.com/twbs/bootstrap/blob/4f44a2afd0acbf8a2d199c6fffe619b91dee1c99/scss/_variables.scss#L195-L223
