### ISSUE TITLE
Fixed. Getting error "window is not defined" in polyfill.js

### ISSUE THREAD

**Issue by dhruvildave007** [reactstrap/reactstrap#1859]
### What is happening?
5 hours ago the react strap was working fine but suddenly it stopped working and i am getting this error `ReferenceError: window is not defined`
I checked the logs and find this line in logs
`at /node_modules/reactstrap/lib/polyfill.js:4:3`
and checked this file and here I get this code
`if (typeof window.CustomEvent === 'function') return;`
SO i checked the repo of `reactstrap` and checked the file polyfill.js and I saw there is a change in above line 4 hours ago and i has changed with `if ( typeof window !== 'object' || typeof window.CustomEvent === 'function' ) return;` So i tested locally in my system and it worked.
But I know that this thing is wrong to update any node_module file
Is there any solution which i can use for my problem

**Comment by iamandrewluca** [comment]
Folks please first search for any existing issues. I closed already 2 issues about this. Problem is fixed. Needs release.
I'll keep this open for people eyes.
