### ISSUE TITLE
npm install --save reactstrap (INSTALLATION PROBLEM)

### ISSUE THREAD

**Issue by Niranjan2054** [reactstrap/reactstrap#1878]
**I have got error install reactstrap**

I had run **npm install --save reactstrap** in the project folder 

the project was created using **npx create-react-app elearning**

I had once install **react-router-dom** in a similar way it works but reactstrap in not installing 

**Error**
```
npm ERR! Unexpected end of JSON input while parsing near '...:"^3.16.1","eslint-pl'
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/niranjan/.npm/_logs/2020-06-26T15_19_23_690Z-debug.log
```

**/home/niranjan/.npm/_logs/2020-06-26T15_19_23_690Z-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'reactstrap' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose npm-session fa72e49058bd0296
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/reactstrap 983ms (from cache)
8 silly fetchPackageMetaData error for reactstrap@latest Unexpected end of JSON input while parsing near '...:"^3.16.1","eslint-pl'
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 2591ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...:"^3.16.1","eslint-pl'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (/usr/lib/nodejs/json-parse-better-errors/index.js:7:17)
11 verbose stack     at consumeBody.call.then.buffer (/usr/share/npm/node_modules/node-fetch-npm/src/body.js:96:50)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose cwd /media/niranjan/3A402FE9402FAB19/E-learning/elearning
13 verbose Linux 5.4.0-37-generic
14 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "reactstrap"
15 verbose node v10.19.0
16 verbose npm  v6.14.4
17 error Unexpected end of JSON input while parsing near '...:"^3.16.1","eslint-pl'
18 verbose exit [ 1, true ]
```

**Comment by iamandrewluca** [comment]
I could not reproduce this. Can you give more info about node and npm versions?

**Comment by iamandrewluca** [comment]
Hmm. I could not reproduce this.

**Comment by iamandrewluca** [comment]
Can you show your package.json?

**Comment by Niranjan2054** [comment]
{
  "name": "elearning",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "bootstrap": "^4.5.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by iamandrewluca** [comment]
Try to remove `node_modules` and isntall verything again.
