### ISSUE TITLE
Can't open Spinner Component

### ISSUE THREAD

**Issue by lizardkingLK** [reactstrap/reactstrap#1889]
Cant open Spinner Component Docs in reactstrap github page. Gives 404 not found error.

**Comment by iamandrewluca** [comment]
@lizardkingLK What is the link?

https://reactstrap.github.io/components/spinners/

**Comment by TheSharpieOne** [comment]
Something is not right with the pre-rendered static content. It is serving a 404: view-source:https://reactstrap.github.io/components/spinners/
That plus the page itself seems off.
