### ISSUE TITLE
Add getting started section & document with create-react-app

### ISSUE THREAD

**Issue by eddywashere** [reactstrap/reactstrap#189]
reactstrap docs are missing a good getting started section. `create-react-app` really simplifies what I would have had to explain months ago.

As far as implementation, I'd love for this section to be a clone of [adding bootstrap](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-bootstrap) section from create-react-app. Instead of linking to a gist, I would inline that gist in a code block. This could be something their docs could link to for people who are looking for a bootstrap 4 support. Also, their [DangerButton](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#dangerbuttonjs) happens to match the reactstrap component api 😉 

Once this is added I'd like to visit a more in depth getting started that includes FAQs, advanced stuff, react router integration and more examples.

**Comment by cglewis** [comment]
I'll take a stab at this one.

**Comment by eddywashere** [comment]
@cglewis :thumbsup: ty!
