### ISSUE TITLE
Range input slider track doesn't align with the thumb position

### ISSUE THREAD

**Issue by erinknight242** [reactstrap/reactstrap#1930]
- components: `Input`
- reactstrap version `8.5.1`
- react version `16.0.0`
- bootstrap version `4.1.3`

### What is happening?
The slider track (blue progress bar) doesn't line up with the thumb toggle; there is a slight gap. You can also see the tick marks have a little bit unexpected position/padding.

The top bar is the reactstap Input; the bottom bar is a plain bootstrap input with the same properties to compare:

<img width="666" alt="Screen Shot 2020-07-29 at 9 34 52 PM" src="https://user-images.githubusercontent.com/3969554/88874067-c1f40e80-d1e3-11ea-9e3c-ee82885e10a7.png">

### What should be happening?
The second bar in the image above is a plain bootstrap input; showing the expected alignment/overlap of the track and the thumb.

### Steps to reproduce issue
1. Use an Input with type "range"

### Code
Here is the code for the example pictured above:

``` 
      <Input type="range" min="1" max="8" step="1" list="level"/>
      <datalist id="level">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
        <option>6</option>
        <option>7</option>
        <option>8</option>
      </datalist>
      <input type="range" min="1" max="8" step="1" list="levels" />
      <datalist id="levels">
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
          <option>6</option>
          <option>7</option>
          <option>8</option>
      </datalist>

**Comment by kyletsang** [comment]
I've tested this on bootstrap 4.5.2 and it looks ok.

Your code for the plain bootstrap range appears to be missing the bootstrap class?  Can you try this against the latest version of bootstrap 4.5.2?

**Comment by kyletsang** [comment]
Closing as stale

**Comment by erinknight242** [comment]
Thank you; yes this is resolved with the latest versions.

<img width="194" alt="Screen Shot 2020-10-21 at 7 54 43 PM" src="https://user-images.githubusercontent.com/3969554/96805492-66e34980-13d7-11eb-8450-7ad4727e2a0a.png">
