### ISSUE TITLE
DropDown item always put the end of the URL a hash (#) tag. So can't use to load subpage. Very big problem at Seo

### ISSUE THREAD

**Issue by nikolicsmilan** [reactstrap/reactstrap#1931]
- components: `name`
- reactstrap version `#x.x.x`
- import method `umd/csj/es` 
- react version `#x.x.x`
- bootstrap version `#x.x.x`

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by kyletsang** [comment]
DropdownItem doesn't append a hash anywhere in the code from what I can see.  If you are still seeing this, please reopen and add a code example.
