### ISSUE TITLE
Not able to autoplay the carousel on page load, I have to hover on sliders to make the slider to come in autoplay action, Is there are way that slider automatically autoload on page load  

### ISSUE THREAD

**Issue by isharad28** [reactstrap/reactstrap#1951]
- components: `name`
- reactstrap version `#x.x.x`
- import method `umd/csj/es` 
- react version `#x.x.x`
- bootstrap version `#x.x.x`

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by TheSharpieOne** [comment]
You need the prop: `ride="carousel"` to enable autoplay. See the docs: https://reactstrap.github.io/components/carousel/
