### ISSUE TITLE
Input multiple select broken?

### ISSUE THREAD

**Issue by ventrebleu** [reactstrap/reactstrap#1961]
- components: `Input`

### What is happening?

Trying to understand how to have an Input multiple select that gives the feedback of multiple values selected.
Even the example that you gave for a closed ticket doesn't seem to be working:
https://stackblitz.com/edit/reactstrap-v6-wwzerv?file=Example.js

The HTML element nor the console log is showing multiple options selected.

**Comment by mznet** [comment]
@ventrebleu you need to hold either `control`(windows) or `command`(mac) key to select multiple options.
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple

**Comment by TheSharpieOne** [comment]
The example above seems to be working just fine. As mznet stated, you have to use <kbd>ctrl</kbd> or <kbd>cmd</kbd> + clicking to select multiple ones. You can also use the keyboard arrows (while holding <kbd>ctrl</kbd> or <kbd>cmd</kbd>) with <kbd>space</kbd> to select for a11y.
These are implemented by the browser itself, not reactstrap nor bootstrap.
![Kapture 2020-09-16 at 11 31 33](https://user-images.githubusercontent.com/664714/93359462-a46d1980-f810-11ea-84ab-94a77a0e0797.gif)

**Comment by ventrebleu** [comment]
My bad and thanks for the replies.
What a poor UX pattern though.

PS: @mznet if you want to be taken seriously, avoid reference to w3schools 😉
