### ISSUE TITLE
Collapse show deprecated findDomNode in console.log()

### ISSUE THREAD

**Issue by Nawanop** [reactstrap/reactstrap#1962]
- components: `Collapse`
- reactstrap version `8.5.1`
- react version `16.9.48`
- bootstrap version `4.5.2`

Console log showing depecated findDomNode in StrictMode

I use Collapse class in Reactstrap and found logging like this
![image](https://user-images.githubusercontent.com/67582692/92413843-2065c280-f17c-11ea-8dce-1ecad7e30386.png)

react-transition-group 4.4.0 tell that use nodeRef instead of findDomNode to fix this issue
https://github.com/reactjs/react-transition-group/blob/1fd4a65ac45edd2aea3dec18eeb8b9c07c7eb93f/CHANGELOG.md#440-2020-05-05

**Comment by mznet** [comment]
@Nawanop [This Pull Reuqest](https://github.com/reactstrap/reactstrap/pull/1926) already handles this issue. It would be fixed if this PR is merged.

**Comment by Nawanop** [comment]
@mznet thank you so much

**Comment by irfancnk** [comment]
Getting the same error, waiting for the solution

**Comment by kyletsang** [comment]
Consolidating in #1833
