### ISSUE TITLE
peer dep missing: jquery@1.9.1 - 3, required by bootstrap@4.5.2

### ISSUE THREAD

**Issue by ahmedosama5200** [reactstrap/reactstrap#1974]
- reactstrap version `#latest`
- react version `#latest`
- bootstrap version `#latest`

### What is happening?
I get this warning in console:
`peer dep missing: jquery@1.9.1 - 3, required by bootstrap@4.5.2`

**Comment by kyletsang** [comment]
You can ignore this.  Regular bootstrap requires jquery for its js components, but it’s not needed here because reactstrap re-implements the js.
