### ISSUE TITLE
Component to toggle between ListView and GridView

### ISSUE THREAD

**Issue by ridhwaans** [reactstrap/reactstrap#1978]
- components: `Dropdown, DropdownToggle, DropdownMenu, DropdownItem`
- reactstrap version `#8.6.0`
- import method `es` 
- react version `#16.13.1`
- bootstrap version `latest`

![image](https://user-images.githubusercontent.com/1103336/95806822-9e1a7200-0cd6-11eb-98c0-18bc021f8374.png)

### What is happening?
There is no visible component for toggling between List view and Grid view. React Native has it but React for Web does not (at least reactstrap)

As a common use case, looking for a toggle on rendering reactstrap components, particularly a reactstrap grid and list.  No such custom component exists right out of the box that is designed for this behaviour  

### What should be happening?
Click the list icon or button, it becomes highlighted (visual change in css) and the reactstrap listview is rendered. Similarly, the same action for the Gridview button; the listview button or 'page' loses its highlight  

### Steps to reproduce issue

1. browse reactstrap components
2. create a new component with the expected functionality

### Error message in console

```
paste error message with stacktrack here
```

### Code

```
todo
```

**Comment by kyletsang** [comment]
See the section under "Checkbox and Radio Buttons (Stateful Buttons)" in the buttons page:
https://reactstrap.github.io/components/buttons/

You can use this to create your list/grid toggle.
