### ISSUE TITLE
Bugs in Card Title and Subtitle

### ISSUE THREAD

**Issue by Neeraj2212** [reactstrap/reactstrap#1991]
- components: `card`
- reactstrap version `#8.6.0`
- import method `import {
	Card,
	CardBody,
	CardImg,
	CardSubtitle,
	CardText,
	CardTitle,
} from 'reactstrap';` 
- react version `#16.13.1`
- bootstrap version `#4.5.2`

### What is happening?

In the displayed Card , card-title , card-subtitle, card-text are exactly same .

### What should be happening?

Font size of Card title should be large and bold too 
same goes with the Card subtitle but less than card title

### Steps to reproduce issue

1. inside `<Card>` create `<CardBody>` 
2. inside `<CardBody>` create `<CardTitle>`  `<CardSubtitle>` and `<CardText>` and  write something in it 

### Error message in console

```
Nothing , Not a error
```

### Code
```
import React from 'react';
import {
	Card,
	CardBody,
	CardImg,
	CardSubtitle,
	CardText,
	CardTitle,
} from 'reactstrap';

function RenderCard({ item }) {
	return (
		<Card>
			<CardImg src={item.image} alt={item.name} />
			<CardBody>
				<CardTitle >{item.name}</CardTitle>
				{item.designation ? (
					<CardSubtitle>{item.designation}</CardSubtitle>
				) : null}
				<CardText>{item.description}</CardText>
			</CardBody>
		</Card>
	);
}
```

**Comment by kyletsang** [comment]
`.card-title` and `.card-subtitle` classes only affect margins and not font styling.

To get cards to look like those in the upstream bootstrap docs, you would need to customize the tag that these are rendered with. 

For example:
```
<CardTitle tag="h5">Title</CardTitle>
<CardSubtitle tag="h6" className="text-muted">Subtitle</CardSubtitle>
```

Reactstrap docs could be improved to indicate this though.

**Comment by Neeraj2212** [comment]
Okay
