### ISSUE TITLE
There's no innerRef type definition for Table 

### ISSUE THREAD

**Issue by qkreltms** [reactstrap/reactstrap#1993]
- components: `Table`
- reactstrap version "^8.6.0"
- import method `es` 
- react version `"^16.14.0"`

### What is happening?
No innerRef in type definition for Table, but written on document and also other components seems not have it too.

Seems putting ```    innerRef?: React.Ref<HTMLButtonElement>;``` on Table.d.ts will resolve this issue
1. https://github.com/reactstrap/reactstrap/blob/2a47626dc088f1983239f606c91f6294c7e756d7/src/Table.js#L18
2. https://github.com/reactstrap/reactstrap/blob/2a47626dc088f1983239f606c91f6294c7e756d7/types/lib/Table.d.ts#L4-L18

**Comment by koenvg** [comment]
Hey, I would like to fix this will also check for other places where this is the case.
