### ISSUE TITLE
Collapse animation doesn't work correctly if we increase its duration

### ISSUE THREAD

**Issue by TexnikBy** [reactstrap/reactstrap#2004]
### What is happening?

The animation is interrupted when we increase its duration

### What should be happening?

The animation should not be interrupted

(P.S. in code too but https://getbootstrap.com/docs/4.5/components/collapse/ works fine)

### Steps to reproduce issue

1. go to https://reactstrap.github.io/components/collapse/
2. change class ".collapsing" - "transition: height **0.35s** ease" to "transition: height **5s** ease"
3. Click toogle

**Comment by TexnikBy** [comment]
![Uploading 2004bug.gif…](how it looks)

**Comment by kyletsang** [comment]
You'll have to set the `timeout` prop in Collapse to match your transition duration.
