### ISSUE TITLE
UncontrolledTooltip does not work on hover about half of the time (no error in console)

### ISSUE THREAD

**Issue by OlivierPapineau** [reactstrap/reactstrap#2005]
### Issue description
UncontrolledTooltip does not work on hover about half of the time

- components: `UncontrolledTooltip`
- reactstrap version `#6.3.0`
- import method `import { UncontrolledTooltip } from 'reactstrap'` 
- react version `#16.8.6`
- bootstrap version `#4.3.1`

### What is happening?

When using the UncontrolledTooltip component passing it the target ID, the tooltip and the delay, the tooltip doesn't appear on hover about half the time with valid prop data passed.

### What should be happening?

On hover, the UncontrolledTooltip should appear over my chosen component

### Steps to reproduce issue

1. Create a span
2. Put an UncontrolledTooltip inside of it with an <i> element with an Id as reference
3. Pass the <i> element Id as the target to the UncontrolledTooltip
4. Hover over the element in your browser

### Error message in console

```
No error in console
```

### Code

  
```
return (
  <span style={spanStyle} className={className}>
    <UncontrolledTooltip
      placement="top"
      target={id}
      delay={delay}
      className="tooltip">
      {tooltip}
    </UncontrolledTooltip>
    <i id={id} className={`zmdi ${icon} text-muted`} style={mergedIconStyle} />
  </span>
)

```

**Comment by kyletsang** [comment]
Can you post a complete repro?  Preferably on CodeSandbox or similar.  Thanks!

**Comment by kyletsang** [comment]
Closing as stale
