### ISSUE TITLE
Tooltip scheduleupdate not working as expected

### ISSUE THREAD

**Issue by Geddard** [reactstrap/reactstrap#2010]
- components: `Tooltip`
- reactstrap version `^8.5.0`
- react version `16.9.23`

### What is happening?

I'm trying to use the tooltip to display a loading spinner, then when an image is loaded change the content to display said image

### What should be happening?

When the image loads, and the tooltip component receives a new prop value `true` for `asyncLoaded`, the schedule update is executed and the tooltip position recalculated.

### What actually happens
The tooltip body is moved to the top left of the screen instead of pointing to the original trigger.

### Code

This is the code where i create my tooltip

```
const tooltipProps = {
    tooltipTrigger: <SmallImage />, // The trigger is a thumbnail version of the image that should load inside the tooltip
    isLink: !isEmpty(linkUrl), // This let's my custom tooltip decide if the trigger is also an anchor or not
    triggerLink: `${parsedDomain}/uploadedfile/${imageId}`, // anchor link
    tooltipBody: <BigImage />, // Image that should be loaded inside the tooltip
    placement: PLACEMENT['top'],
    container: tooltipRef, // ref of the anchor I'm using, this is only so I'm able to re'style the width of the tooltip, same wrong behaviour occurs even with the default trigger configuration
    asyncLoaded: imageLoaded, // State that let's the Tooltip know when to trigger the scheduleUpdate
    isAsync: true,
  };

  return imageId ? (
    <Image>
      <span ref={tooltipRef}></span> // custom tooltip anchor so it's easier to re-style the tooltip container
      <CustomTooltip {...tooltipProps} />
    </Image>
  ) : null;
```

And here is my ASyncBody component that triggers the scheduleUpdate:

```
const AsyncBody: React.FC<any> = ({ scheduleUpdate, children, loaded }) => { 
  useLayoutEffect(() => {
    if (loaded) {
        scheduleUpdate();
    }
  }, [loaded, scheduleUpdate]);

  return children;
};
```

Could anyone help me figure out why the re-positioning is not working correctly? Or is it just a bug no1 cares about?

Kind regards

**Comment by kyletsang** [comment]
Is your tooltip target still in the DOM?  Are you able to post a repro on a site like CodeSandbox?

**Comment by Geddard** [comment]
> Is your tooltip target still in the DOM? Are you able to post a repro on a site like CodeSandbox?

Hey there, thanks for you reply :)

Yeah I doesn't depend on any variables so it should be there, I also tried simply using a timeout to call the scheduleUpdate (meaning no state changes in the parent) and still the same happens.
 Even using the default Tooltip portal

**Comment by Geddard** [comment]
Im pretty sure the issue simply has to do with the image content, because if I change it to text and use timeouts the tooltip re-renders in the appropriate position :(

**Comment by Geddard** [comment]
Also, after the scheduleUpdate is triggered, and the tooltip appears in the wrong position, I can hover out and in over the element, and the position is corrected... I'm clueless as to why this happens

**Comment by Geddard** [comment]
Ok it seems the problem was related to the function I was using to render the trigger, wrapping this function in a useCallback solved my issue 😅 Thanks for the help

**Comment by himynameissebbo** [comment]
Hey @Geddard,
I am facing the same problem and tried to comprehend your solution. Can you maybe provide some example?
Thanks for your help!

**Comment by Geddard** [comment]
> Hey @Geddard,
> I am facing the same problem and tried to comprehend your solution. Can you maybe provide some example?
> Thanks for your help!

hey @himynameissebbo, as I described I think the problem was that another part of the component was triggering a whole component re-render, and in this second round the trigger ref was not loaded fast enough, maybe?

So what I did was wrap all the functions related to the rendering into useCallback.

So my main component looks like this:
```
export const TransformedImage = ({
  originalAccessor,
  data,
  fieldConfig: { domain, thumbnail, alt, linkUrl },
}: TransformParams) => {
  const imageId = get(data, originalAccessor);
  const parsedDomain = !isEmpty(domain) ? `//${domain}` : `//`;
  const parsedThumbnail = thumbnail.replace(REPLACER_TOKEN, imageId);
  const [thumbLoaded, setThumbLoaded] = useState<boolean>(false);
  const [imageLoaded, setImageLoaded] = useState<boolean>(false);
  const tooltipRef = useRef<HTMLElement>(null);

  const ImageLoader = (isLoaded: boolean, image: JSX.Element) => (
    <Loader>
      <SpinnerWrapper>
        <Spinner type="grow" color="dark" style={{ display: isLoaded ? 'none' : 'block' }} />
      </SpinnerWrapper>
      <span style={{ visibility: !isLoaded ? 'hidden' : 'visible' }}>{image}</span>
    </Loader>
  );

  const BigImage = useCallback(
    () =>
      ImageLoader(
        imageLoaded,
        <BigImg src={`${parsedDomain}/uploadedfile/${imageId}`} alt={alt} onLoad={() => setImageLoaded(true)} />
      ),
    [alt, imageId, imageLoaded, parsedDomain]
  );

  const SmallImage = useCallback(
    () =>
      ImageLoader(
        thumbLoaded,
        <Img
          src={`${parsedDomain}/uploadedfile/thumbnail${parsedThumbnail}`}
          alt={alt}
          onLoad={() => setThumbLoaded(true)}
        />
      ),
    [thumbLoaded, alt, parsedDomain, parsedThumbnail]
  );

  const tooltipProps = {
    tooltipTrigger: <SmallImage />,
    isLink: !isEmpty(linkUrl),
    triggerLink: `${parsedDomain}/uploadedfile/${imageId}`,
    tooltipBody: <BigImage />,
    placement: PLACEMENT['right'],
    container: tooltipRef,
    asyncLoaded: imageLoaded,
    isAsync: true,
  };

  return imageId ? (
    <Image>
      <span ref={tooltipRef}></span>
      <CustomTooltip {...tooltipProps} />
    </Image>
  ) : null;
};
```

and this is what I did in the body of the tooltip component I created

```
const withAsync = (scheduleUpdate: () => void) => (
    <AsyncBody scheduleUpdate={scheduleUpdate} loaded={!!asyncLoaded}>
      {tooltipBody}
    </AsyncBody>
  );

  return (
    <>
      <Trigger {...triggerProps}>{tooltipTrigger}</Trigger>
      <Tooltip
        container={container}
        placement={placement}
        autohide={false}
        isOpen={tooltipOpen}
        target={id}
        toggle={toggle}
      >
        {isAsync ? ({ scheduleUpdate }) => withAsync(scheduleUpdate) : tooltipBody}
      </Tooltip>
    </>
  );
```
