### ISSUE TITLE
Problem with Installing Reactstrap

### ISSUE THREAD

**Issue by karaku2u** [reactstrap/reactstrap#2015]
When im trying to install Reactstrap with the Command "npm install reactstrap" / "npm install --save reactstrap react react-dom" i get this Error:

* npm ERR! code ERESOLVE
* npm ERR! Cannot read property 'length' of undefined

debug.log ->

0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   'reactstrap'
0 verbose cli ]
1 info using npm@7.0.8
2 info using node@v15.1.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/Users/xxx/Documents/React/intro/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/Users/barishuvaj/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 6ms
19 verbose npm-session d66e8f533327323e
20 timing npm:load Completed in 13ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree:init Completed in 706ms
23 timing idealTree:userRequests Completed in 1ms
24 silly idealTree buildDeps
25 silly fetch manifest reactstrap@*
26 timing arborist:ctor Completed in 0ms
27 http fetch GET 304 https://registry.npmjs.org/reactstrap 852ms (from cache)
28 silly fetch manifest react@^17.0.1
29 http fetch GET 304 https://registry.npmjs.org/react 112ms (from cache)
30 silly fetch manifest react-dom@^17.0.1
31 http fetch GET 304 https://registry.npmjs.org/react-dom 96ms (from cache)
32 silly placeDep ROOT reactstrap@8.7.1 OK for: intro@0.1.0 want: *
33 silly fetch manifest classnames@^2.2.3
34 silly fetch manifest react-popper@^1.3.6
35 silly fetch manifest react-transition-group@^2.3.1
36 http fetch GET 304 https://registry.npmjs.org/react-popper 132ms (from cache)
37 http fetch GET 304 https://registry.npmjs.org/classnames 214ms (from cache)
38 http fetch GET 304 https://registry.npmjs.org/react-transition-group 215ms (from cache)
39 timing idealTree:#root Completed in 1300ms
40 silly fetch manifest react@^16.3.2
41 http fetch GET 200 https://registry.npmjs.org/react 8ms (from cache)
42 silly fetch manifest react-dom@^16.3.2
43 http fetch GET 304 https://registry.npmjs.org/react-dom 86ms (from cache)
44 silly placeDep ROOT classnames@2.2.6 OK for: reactstrap@8.7.1 want: ^2.2.3
45 silly placeDep node_modules/reactstrap react-popper@1.3.7 OK for: reactstrap@8.7.1 want: ^1.3.6
46 timing idealTree Completed in 2143ms
47 timing command:install Completed in 2146ms
48 verbose stack Error: unable to resolve dependency tree
48 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1020:25)
48 verbose stack     at Arborist.[placeDep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1096:30)
48 verbose stack     at Arborist.[placeDep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1232:41)
48 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:772:46
48 verbose stack     at Array.map (<anonymous>)
48 verbose stack     at Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:772:8)
48 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:203:7)
48 verbose stack     at async Promise.all (index 1)
48 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:121:5)
48 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:38:5)
49 verbose cwd /Users/xxxx/Documents/React/intro
50 verbose Darwin 19.6.0
51 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "reactstrap"
52 verbose node v15.1.0
53 verbose npm  v7.0.8
54 error code ERESOLVE
55 verbose stack TypeError: Cannot read property 'length' of undefined
55 verbose stack     at explainDependents (/usr/local/lib/node_modules/npm/lib/utils/explain-dep.js:68:19)
55 verbose stack     at explainNode (/usr/local/lib/node_modules/npm/lib/utils/explain-dep.js:13:3)
55 verbose stack     at explainEresolve (/usr/local/lib/node_modules/npm/lib/utils/explain-eresolve.js:24:24)
55 verbose stack     at report (/usr/local/lib/node_modules/npm/lib/utils/explain-eresolve.js:59:10)
55 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/utils/error-message.js:24:24)
55 verbose stack     at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:173:15)
55 verbose stack     at /usr/local/lib/node_modules/npm/lib/npm.js:118:9
55 verbose stack     at install (/usr/local/lib/node_modules/npm/lib/install.js:67:5)
56 verbose cwd /Users/xxx/Documents/React/intro
57 verbose Darwin 19.6.0
58 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "reactstrap"
59 verbose node v15.1.0
60 verbose npm  v7.0.8
61 error Cannot read property 'length' of undefined
62 verbose exit 1

**Comment by nayanagrawal79** [comment]
I am suffering from the same issue.
Please suggest a fix

**Comment by kyletsang** [comment]
This is a problem with npm cli and not reactstrap.  

It's likely the same problem as this:  https://github.com/npm/cli/issues/2134

I would suggest using the node LTS version.

**Comment by karaku2u** [comment]
> This is a problem with npm cli and not reactstrap.
> 
> It's likely the same problem as this: [npm/cli#2134](https://github.com/npm/cli/issues/2134)
> 
> I would suggest using the node LTS version.

Maybe that’s can cause the problem I wanna try the LTS thanks for your Suggestion 🙏

**Comment by kyletsang** [comment]
Closing since this is an issue with npm
