### ISSUE TITLE
UncontrolledDropdown Item Customization

### ISSUE THREAD

**Issue by emin-karadag** [reactstrap/reactstrap#2019]
- components: `Navbar`
- reactstrap version `8.1.1`
- react version `16.8.3`
- bootstrap version `4.5.2`

I am using Uncontrolled Dropdown within the NavBar component. DropdownMenu opens when I click on DropdownToggle. Actually, everything is normal up to this point.

However, I want to do this: When I click on the title of the popup menu I want to redirect to a page. However, when I click the icon (caret)  next to the title, I want the drop-down menu to open.

Can you help with how this can be done?

**Comment by kyletsang** [comment]
You can probably do this by wrapping your title in another element (like a span), assigning a click handler, then calling `stopPropagation` on the event so the button toggle won't receive a click event.

**Comment by emin-karadag** [comment]
Your advice worked. Thank you so much. :)

**Comment by kyletsang** [comment]
Glad you figured it out.  Closing this issue now.
