### ISSUE TITLE
Unable to click first tab of Nav Tabs

### ISSUE THREAD

**Issue by byronthe123** [reactstrap/reactstrap#2027]
- components: `Nav, NavItem, NavLink`
- reactstrap version `8.7.1`
- import method `umd/csj/es` 
- react version `#16.14.0`
- bootstrap version `4.5.3`

### What is happening?

When creating Tabs, the first Tab is not clickable.
[Video of issue](https://streamable.com/of6di5)

### What should be happening?

The entire Tab area should be clickable and should register click events.

### Error message in console

No error messages.

### Code

```jsx 
<Nav tabs>
    <NavItem onClick={() => toggle('1')}>
        <NavLink
            className={classnames({ active: activeTab === '1' })}
        >
            JUST WORK
        </NavLink>
    </NavItem>
    <NavItem onClick={() => toggle('2')}>
        <NavLink
            className={classnames({ active: activeTab === '2' })}
        >
            More Tabs
        </NavLink>
    </NavItem>
</Nav>

**Comment by kyletsang** [comment]
Works here:
https://codesandbox.io/s/currying-sea-t5g4h?file=/src/App.js
