### ISSUE TITLE
Create CodeSandbox Templates

### ISSUE THREAD

**Issue by kyletsang** [reactstrap/reactstrap#2030]
Would be nice to have some templates ready to go for writing quick repros and stuff.  We can link to these in the issue template so people will have a good starter for writing repros for issues.

@TheSharpieOne, can you assist with this?  I don't have permissions to create new repos under reactstrap org.  

Thanks!

**Comment by zaycation** [comment]
Can I help work on this too? Do you mean one code sandbox example for each component?

**Comment by kyletsang** [comment]
I've added a couple starters in https://github.com/reactstrap/code-sandbox-examples already.

I think simple examples should stay on the docs page and some that require a little more setup (like maybe showcasing a different bundler etc) should go into CodeSandbox.
