### ISSUE TITLE
css-module support?

### ISSUE THREAD

**Issue by gthomas-appfolio** [reactstrap/reactstrap#205]
Hi, have a use case for isolating bootstrap classes from rest of the page, and curious if there is a way to use css-modules with reactstrap so that Bootstrap does not need to be loaded as global classes?

[react-fontawesome](https://github.com/danawoodman/react-fontawesome/blob/master/api.md) has an example of how this could be specified.

**Comment by TheSharpieOne** [comment]
It's definitely something that can be done in a similar fashion as the library you linked to. Since there are so many components which would need this, I would suggest a utility be made to make this easier. The linked library doesn't use the classnames lib, it instead builds the className more/less manually.
I could imagine the helper taking the result of the classnames function (a string) and if cssModules are provided, simply doing a split on space (`' '`) and then mapping the results against the cssModules before joining them back. Something like:
```
function mapToCssModules(className, cssModule) {
  if (!cssModule) return className; // maybe ensure it is an object too?
  return className.split(' ').map(c => cssModule[c] || c).join(' ');
}
```

**Comment by hdngr** [comment]
Awesome!

**Comment by hdngr** [comment]
Sorry if this is more of an SO question, but it relates to your new feature.

I'm a bit new to react, and I'm now re-implementing Reactstrap to use 'cssModule'.  I just want to check, is there a way to assign the `cssModule` prop to all reactstrap components as they are imported, vs. when they are used by `render()`.

Here is an example of what I am trying to avoid:

```
MyAwesomeComponent() => {
    return(
        <NavLink cssModule={Bootstrap}>Foo</NavLink>
        <NavLink cssModule={Bootstrap}>Bar</NavLink>
        <NavLink cssModule={Bootstrap}>Hello</NavLink>
        <NavLink cssModule={Bootstrap}>React</NavLink>
    )
}
```

It seems inefficient and I am sure you know of a better way!

**Comment by gthomas-appfolio** [comment]
This is great, thanks for the fast fix @TheSharpieOne !  I have same question as @hdngr , wondering the best way to add globally and/or somehow wrap component so I can export them with a css-module already specified

**Comment by TheSharpieOne** [comment]
I realized the same thing when implementing it, but this the way the referenced library works. Not too sure if another adequate solution. Using context would definitely do it. Wrapping the components will work as well, but at that point making another package which extends reactstrap (using the component library linked in the readme as a starting place and eventually adding it to the list) is probably best.

**Comment by gthomas-appfolio** [comment]
Cool thanks for the start, thanks again!
