### ISSUE TITLE
Installing using npm throws an error

### ISSUE THREAD

**Issue by ag2byte** [reactstrap/reactstrap#2070]
### npm i reactstrap bootstrap throws an error

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
```

**Comment by kyletsang** [comment]
Not enough info here.   Are you using npm 7?  There might be issues with that and resolving peer dependencies.

**Comment by ag2byte** [comment]
I am using npm 7.0.15 so basically npm 7. Is this a problem with npm?

**Comment by kyletsang** [comment]
npm 7 auto-installs peer dependencies for you.  So an example where this would cause problems is if you're using React 17.  One of our peer dependencies react-popper doesn't support it, so it would error out.

**Comment by ag2byte** [comment]
So the solution currently is to use --legacy-peer-deps right?

**Comment by kyletsang** [comment]
Yeah.  Did that work out for you?

**Comment by ag2byte** [comment]
Yes. But I was looking for the reason of the error, which I got here. Thanks. Closing the issue
