### ISSUE TITLE
Not possible to apply custom height to `Progress`

### ISSUE THREAD

**Issue by vhenzl** [reactstrap/reactstrap#2071]
- components: `Progress`
- reactstrap version `8.8.1` (since `8.5.0`)
- import method - irrelevant
- react version `16.14`
- bootstrap version `4.5.3`

### What is happening?

It's not possible to apply custom height to `Progress` component as `style` prop is applied to the inner `progress-bar` element instead of the root `progress` element.

![image](https://user-images.githubusercontent.com/243381/104237311-bb6d0100-54bc-11eb-849a-fd1488d29fc0.png)

It's broken since `8.5.0` (likely because of #1771). Seems like #1970 in `8.7.0` tried to fix that but it didn't.

### What should be happening?

It should be possible to specify height with CSS styles as per [Bootstrap doc](https://getbootstrap.com/docs/4.5/components/progress/#height):

```
<div class="progress" style="height: 1px;">
  <div class="progress-bar" style="width: 25%;"></div>
</div>
```

The above should be equivalent to:

```jsx
<Progress value={25} style={{ height: "1px" }} />
```

### Steps to reproduce issue

https://codesandbox.io/s/reactstrap-progress-bug-tuqb1?file=/src/App.js

**Comment by kyletsang** [comment]
We should revert #1771 and expose a `progressStyle` prop or something to support it.
