### ISSUE TITLE
Trap Focus feature of Modal is preventing flyouts to open in modal dialog

### ISSUE THREAD

**Issue by ChiragRupani** [reactstrap/reactstrap#2072]
- components: `Modal`
- reactstrap version `^8.8.0`
- import method `es` 
- react version `16.14`
- bootstrap version `^4.5.3`

We are rendering custom controls inside modal, which use flyout to search product. However, due to recent change in trapping focus prevents such dropdowns/flyout to open, normally when user type some text, it would open, but now with latest version it is breaking while working fine on 8.7.1. May be due to focus trap introduced in #1941, is there way to disable it?

**Comment by kyletsang** [comment]
Currently no.  I'm thinking we should just make that behavior opt-in, since this is the second case of it inadvertently breaking.
