### ISSUE TITLE
Text field not getting focused while focusing

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [reactstrap/reactstrap#2079]
- components: `Modal`
- reactstrap version `^8.4.1`

- react version `^16.13.1`
- bootstrap version `^4.5.0`

In reactstrap modal with **another modal with textfields** are not getting focused while focusing. The same has been working fine in previously.
![image](https://user-images.githubusercontent.com/67726510/105016356-8c044a00-5a10-11eb-9de4-1dde98f7bbf2.png)

text field in the popover with Modal ( text field not getting focused while focusing ). The same has been working fine in previously.
![image](https://user-images.githubusercontent.com/67726510/105017191-7e9b8f80-5a11-11eb-86c6-470111ce8688.png)

**Comment by Rajesh-Thiyagarajan** [comment]
if I delete the **modal-dialog div**, the text field getting focused while focusing.
![image](https://user-images.githubusercontent.com/67726510/105019660-53666f80-5a14-11eb-85cb-903afeeda9e8.png)

after deleting modal-dialog div the text field getting focused while focusing.
![image](https://user-images.githubusercontent.com/67726510/105020125-ea332c00-5a14-11eb-88f0-fd55aa498bba.png)

**Comment by kyletsang** [comment]
Will be making a release today to fix this
