### ISSUE TITLE
Trap focus error

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [reactstrap/reactstrap#2082]
- components: `Modal`
- reactstrap version `^8.4.1`
- react version `^16.13.1`
- bootstrap version `^4.5.0`

Modal with while opening Another Modal below error showing in browser console.
![image](https://user-images.githubusercontent.com/67726510/105155535-b9b4c600-5ad8-11eb-932a-8d3ebfdcc8a2.png)

**Comment by kyletsang** [comment]
Can you provide a code repro?  I'm trying the nested modals and I can't reproduce.

**Comment by kyletsang** [comment]
Can you also check the version of reactstrap you have installed?  Is it 8.9.0?

**Comment by Rajesh-Thiyagarajan** [comment]
> Can you provide a code repro? I'm trying the nested modals and I can't reproduce.

Sorry it's private repo.

**Comment by Rajesh-Thiyagarajan** [comment]
> Can you also check the version of reactstrap you have installed? Is it 8.9.0?

Please find the screen shot. 
**Right side latest version** - Issue occurs
**Left side previous version** - Previously working fine
![image](https://user-images.githubusercontent.com/67726510/105281749-cc7fd700-5b7a-11eb-9c2a-d7a4ccf791a2.png)

**Comment by kyletsang** [comment]
Ok, so you're running 8.8.1.   This issue should be resolved for you if you upgrade to 8.9.0

**Comment by Rajesh-Thiyagarajan** [comment]
ok thanks.
