### ISSUE TITLE
What is the use of dist, es, lib folder

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [reactstrap/reactstrap#2086]
Hi team

To understand how reactstrap working i am asking this question.
![image](https://user-images.githubusercontent.com/67726510/105692482-77222d80-5ecc-11eb-9a03-0a2854b0369a.png)

What is use of es, dist, lib folder ?
why we are providing src code to the user ?

**Comment by TheSharpieOne** [comment]
Different users use different loaders.
`dist` is for CDNs, it powers things like https://cdnjs.com/libraries/reactstrap. Everything gets transpiled and there is UMD exporting. There are also a couple of "flavor" with and without external dependencies.
`lib` is for commonjs importing (using `require` and `exports`), plus everything gets transpiled.
`es` is for module importing (using `import` and `export`), it's good for treeshaking, plus everything else gets transpiled.
`src` is also for module importing, but it allows for the end user to determine what gets transpiled and can be useful for avoiding the extra junk in `es`. I believe this is what CRA will pick up out-of-the-box now-a-days. Webpack with babel-loader will do the same unless you tell it to exclude node_modules.

**Comment by Rajesh-Thiyagarajan** [comment]
Is reactstarp will not support TypeScript ?

**Comment by TheSharpieOne** [comment]
typings are included in `es` and `lib`. There used to be `@types/reactstrap`, but that was moved to be within the repo. I guess we are not including the `types` in the release for the `src`.

**Comment by Rajesh-Thiyagarajan** [comment]
@TheSharpieOne I am just asking for my knowledge. what is the project name ? like Node.js prospect, React project , etc ...
![image](https://user-images.githubusercontent.com/67726510/108077028-148b0000-703a-11eb-98df-bd729de60b16.png)

**Comment by TheSharpieOne** [comment]
this project is named "reactstrap"; as found in the "name" property within the package.json
