### ISSUE TITLE
Attempted import error: 'Accordion' is not exported from 'reactstrap'.

### ISSUE THREAD

**Issue by VityaSchel** [reactstrap/reactstrap#2134]
- components: `Accordion`
- reactstrap version `#9.0.0-0` (also tested on 8.9.0)
- import method `es`
- react version `#17.0.1`
- bootstrap version `#4.6.0`

### What is happening?

I'm trying to import Accordion

### What should be happening?

Accordion should be imported as [described](https://reactstrap.github.io/components/accordion/) in docs

### Steps to reproduce issue

1. try to import Accordion

### Error message in console

```
Attempted import error: 'Accordion' is not exported from 'reactstrap'.
```

No stack trace

### Code

`import { Alert, Button, Card, CardBody, Accordion, AccordionBody, AccordionHeader, AccordionItem } from 'reactstrap'`

Alert, button, card and cardbody are imported with no errors

Same error is happening with UncontrolledAccordion:
`Attempted import error: 'UncontrolledAccordion' is not exported from 'reactstrap'.`

**Comment by VityaSchel** [comment]
Accordion actually isn't exported:
[https://github.com/reactstrap/reactstrap/blob/master/src/index.js](https://github.com/reactstrap/reactstrap/blob/master/src/index.js)

**Comment by VityaSchel** [comment]
Was it renamed or maybe removed? I can't find anything about accordion in this repository, but it exist in docs 🤔

![image](https://user-images.githubusercontent.com/59040542/110241256-3f95af00-7f69-11eb-9ff2-84409226e03f.png)

**Comment by VityaSchel** [comment]
I tried recreating it myself, but it works shitty. It works fine on docs page, so I don't see an issue in taking this component from the docs to src.

**Comment by kyletsang** [comment]
Accordion is only available in the 9.x beta which uses bootstrap 5, so you would need to update your bootstrap css.

**Comment by VityaSchel** [comment]
> Accordion is only available in the 9.x beta which uses bootstrap 5, so you would need to update your bootstrap css.

I updated reactstrap to 9 beta as mentioned in issue

**Comment by VityaSchel** [comment]
Anyway I was able to solve this by importing plain version of bootstrap and inserting in in iframe because reactstrap stylesheets were preventing accordion from animating 🤦‍♀️

**Comment by TheSharpieOne** [comment]
reactstrap shouldn't have stylesheets. It depends on bootstrap for styles.
