### ISSUE TITLE
Switch input

### ISSUE THREAD

**Issue by byronrau** [reactstrap/reactstrap#2137]
- components: `FormGroup switch`
- reactstrap version `#8.9.0`
- import method `es` 
- react version `#17.0.1`
- bootstrap version `#4.6.0`

### What is happening?

Hi, I'm just trying the example FormGroup switch and it is not rendering the switch properly. It's showing as a regular input type instead of switch.

### What should be happening?

It should display as a switch from the example.

### Steps to reproduce issue

Load example FormGroup switch code in latest react, reactstrap, bootstrap

### Error message in console

NA

### Code

https://codesandbox.io/s/upbeat-chaum-zrdte?fontsize=14&hidenavigation=1&theme=dark

**Comment by kyletsang** [comment]
Docs site is showing examples from reactstrap 9.x.   For 8.x see this codesandbox for the syntax:

https://codesandbox.io/s/staging-sound-01nl0

**Comment by byronrau** [comment]
Great thank you.
