### ISSUE TITLE
Media component is not showing the picture

### ISSUE THREAD

**Issue by DerGroncki** [reactstrap/reactstrap#214]
I have the following code:

```
import React from "react"
import { Media } from 'reactstrap';
import MyPlaceHolderPicture from './MyPlaceHolderPicture.png';

const MediaWrapper = () => (
    <Media>
      <Media left href="#">
        <Media object data-src={MyPlaceHolderPicture} alt="My PlaceHolder Picture" />
      </Media>
      <Media body>
        <Media heading>
          Media heading
        </Media>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
      </Media>
    </Media>
)

export default MediaWrapper

```

After running the code the picture is not visible.
Thanks for helping.
Michael

**Comment by TheSharpieOne** [comment]
The `data-src` attribute is for holder.js, it's just for the documentation (similar to bootstrap docs). You should use the `src` attribute.

**Comment by DerGroncki** [comment]
Ok, when I change data-src to src the picture is still not visible. I discovered that the size of the picture is 0x0px (org. size is 128x128px).

When I change the code to

```
import React from "react"
import { Media } from 'reactstrap';
import MyPlaceHolderPicture from './MyPlaceHolderPicture.png';

var imgStyle = {
  minWidth: "128px",
};

const MediaWrapper = () => (
    <Media>
      <Media left>
        <Media style={imgStyle} object src={MyPlaceHolderPicture} alt="My PlaceHolder Picture" />
      </Media>
      <Media body middle>
        <Media heading>
          Media heading
        </Media>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
      </Media>
    </Media>
)

export default MediaWrapper

```

the size of the picture is 128x128px and is visible.

If it is necessary to add the size of an image it should be mentioned somewhere.

Thanks.

Michael

**Comment by TheSharpieOne** [comment]
This is working fine when using the latest reactstrap with the latest bootstrap 4 alpha. See: http://www.webpackbin.com/VkHLN_Zlf
Perhaps the thing you are using to import your image is not working correctly or you are overriding the bootstrap media image styles somewhere globally. Can you provide an example of this happening using webpackbin, jsfiddle, plunkr, or something similar? Or maybe the markup generated by react (the img tag with the src)

**Comment by DerGroncki** [comment]
Ok, thanks. I will investigate it further. I will close this for now.

**Comment by kevinsims1** [comment]
Are there more recent solutions to this problem?

**Comment by TheSharpieOne** [comment]
Check your browser's devtools (network tab) to see if it is attempting to load the image (maybe it cannot find the image (the image path is wrong))

**Comment by VolodymyrPliuta** [comment]
Worked for me with src. I feel like data-src should be replaced with src in docs. If my understanding is correct

**Comment by VolodymyrPliuta** [comment]
@kevinsims1 Plus I had to import it and pass it with curlies `src={image}`, browser couldn't resolve if I passed string `src='../data/image.png'`

**Comment by apoorva-ard** [comment]
> Worked for me with src. I feel like data-src should be replaced with src in docs. If my understanding is correct

yes!

**Comment by Ankurgupta5442** [comment]
### Can anybody please help me in this react code I am not able to render image though image path was correct.
import React, { Component } from 'react';
import { Media } from 'reactstrap';

var imgStyle = {
    minWidth: "128px",
  };
  

class Menu extends Component {
    constructor(props) {
        super(props);
        this.state = {
            dishes: [
                {
                  id: 0,
                  name:'Uthappizza',
                  image: './assets/images/uthappizza.png',
                  category: 'mains',
                  label:'Hot',
                  price:'4.99',
                  description:'A unique combination of Indian Uthappam (pancake) and Italian pizza, topped with Cerignola olives, ripe vine cherry tomatoes, Vidalia onion, Guntur chillies and Buffalo Paneer.'                        },
               {
                  id: 1,
                  name:'Zucchipakoda',
                  image: 'assets/images/zucchipakoda.png',
                  category: 'appetizer',
                  label:'',
                  price:'1.99',
                  description:'Deep fried Zucchini coated with mildly spiced Chickpea flour batter accompanied with a sweet-tangy tamarind sauce'                        },
               {
                  id: 2,
                  name:'Vadonut',
                  image: '/assets/images/vadonut.png',
                  category: 'appetizer',
                  label:'New',
                  price:'1.99',
                  description:'A quintessential ConFusion experience, is it a vada or is it a donut?'                        },
               {
                  id: 3,
                  name:'ElaiCheese Cake',
                  image: '/assets/images/elaicheesecake.png',
                  category: 'dessert',
                  label:'',
                  price:'2.99',
                  description:'A delectable, semi-sweet New York Style Cheese Cake, with Graham cracker crust and spiced with Indian cardamoms'                        }
               ],
        };
    }
    


         render() {
        const menu = this.state.dishes.map((dish) => {
            return (
              <div key={dish.id} className="col-12 mt-5">
                <Media tag="li">
                  <Media left middle >
                      <Media style = {imgStyle} object src = {dish.image} alt = {dish.name} />
                  </Media>
                  <Media body className="ml-5">
                    <Media heading>{dish.name}</Media>
                    <p>{dish.description}</p>
                  </Media>
                </Media>
              </div>
            );
        });

        return (
          <div className="container">
            <div className="row">
              <Media list>
                  {menu}
              </Media>
            </div>
          </div>
        );
    }
}

export default Menu;
