### ISSUE TITLE
Page scrolled up after opening modal

### ISSUE THREAD

**Issue by AndrejZelonka** [reactstrap/reactstrap#2142]
### Issue description

- components: `Modal`
- reactstrap version `#8.9.0`
- react version `#17.0.1`
- bootstrap version `#4.6.0`

### What is happening?

After opening modal, page is being scrolled to the top. 

### Code
f.e. most basic example from the official docs.
https://reactstrap.github.io/components/modals/

Just in case if is somebody wondering, event.preventDefault() is not a problem in my case, also I tried add overflow: hidden to html tag.

**Comment by mark-bt** [comment]
What was the solution?
