### ISSUE TITLE
Can't make reactstrap modal fullscreen

### ISSUE THREAD

**Issue by shuvo22890** [reactstrap/reactstrap#2143]
There is an example of making reactstrap modal fullscreen. But it's not mentioned what to pass in the fullscreen property to make the modal fullscreen. Please tell the value of the fullscreen prop....
![fullscreenmodal](https://user-images.githubusercontent.com/49811495/111027796-b543c400-841c-11eb-9710-923ea2d8e390.png)

**Comment by kyletsang** [comment]
It's in the list of properties in the docs:

```
fullscreen: PropTypes.oneOfType([
    PropTypes.bool, // always fullscreen
    PropTypes.oneOf(['sm', 'md', 'lg', 'xl']), // fullscreen below breakpoints
  ]),
```
