### ISSUE TITLE
Remove or Subdue Political Messaging

### ISSUE THREAD

**Issue by wschmrdr** [reactstrap/reactstrap#2144]
Persistent political messaging has no place in a help document, regardless of whether or not one believes in the cause. If an announcement of the same wishes to be made, that's respected, but it should be able to be dismissed and never seen again. It seems especially inappropriate to sticky it to the top of the page in a manner that makes it more difficult to read the contents of the help documentation on account of the distraction.

**Comment by rickyplouis** [comment]
Civil rights can hardly be considered inappropriate.

**Comment by TheSharpieOne** [comment]
It's not political, it's civil. As far as rights go, I'd say that both are important. As it is today, civil rights need more of the spotlight as things have become out of control.

>Civil rights include the ensuring of peoples' physical and mental integrity, life, and safety; protection from discrimination on grounds such as race, gender, sexual orientation, gender identity, national origin, color, age, political affiliation, ethnicity, religion, and disability; and individual rights such as privacy and the freedom of thought, speech, religion, press, assembly, and movement.

>Political rights include natural justice (procedural fairness) in law, such as the rights of the accused, including the right to a fair trial; due process; the right to seek redress or a legal remedy; and rights of participation in civil society and politics such as freedom of association, the right to assemble, the right to petition, the right of self-defense, and the right to vote.

Maybe we can improve the way it look and how it is positioned?

Some things other sites have done:
styled-components moved it to the bottom https://github.com/styled-components/styled-components-website/commit/4afb1d11f482c752768228f784bafcdce77035b9
golang, react-bootstrap, emotion-js, reactiflux, draftjs do not have it as a fixed position (it moves when you scroll)
momentjs has it huge, but only on the homepage
expressjs is similar to how we current have it

The banner stays until things improve and are not just forgotten out, but maybe let it scroll as many other sites have it.
