### ISSUE TITLE
Dropdown or UncontrollerDropdown with Problem Opening Menu in Animated Table

### ISSUE THREAD

**Issue by andrefelipeschulle** [reactstrap/reactstrap#2145]
- components: `Dropdown or UncontrolledDropdown`
- reactstrap version `#8.9.0`
- react version `#17.0.1`
- bootstrap version `#4.6.0`

### What is happening?

when opening the dropdown menu in an animated line of a table, the dropdown menu has a problem, the bottom line icon appears in the dropdown menu, if you go to the last line and click on the icon it does not happen because the menu opens up, I created the component in the [codesandbox](https://codesandbox.io/s/adoring-rgb-xx9vc?fontsize=14&hidenavigation=1&theme=dark) to reproduce the error.

### Code

https://codesandbox.io/s/adoring-rgb-xx9vc?fontsize=14&hidenavigation=1&theme=dark

thanks, sorry for my english, i'm from brazil and i'm still learning english

**Comment by kyletsang** [comment]
Dropdowns don't work particularly well with tables due to how tables are rendered in general.  Try setting `container="body"` on the dropdown menu.  This will change the element the dropdown is appended to.

**Comment by andrefelipeschulle** [comment]
Thanks, it worked for me
