### ISSUE TITLE
Accordion component js file not be found in src

### ISSUE THREAD

**Issue by Murugaraju** [reactstrap/reactstrap#2147]
### Issue description

- components: `Accordion`
- reactstrap version `#8.9.0`
- import method `umd/csj/es` 
- react version `#x.x.x`
- bootstrap version `#x.x.x`

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by Murugaraju** [comment]
All component related to Accordion not found

**Comment by kyletsang** [comment]
Accordion is available in the 9.x beta:
https://www.npmjs.com/package/reactstrap/v/9.0.0-0

**Comment by Murugaraju** [comment]
@kyletsang 
Thanks, Do you want me to close this, or keeping it for others to get notified on same.

**Comment by Murugaraju** [comment]
Accordion is available in the 9.x beta:
https://www.npmjs.com/package/reactstrap/v/9.0.0-0
