### ISSUE TITLE
Where is CSS of components?

### ISSUE THREAD

**Issue by nndung179** [reactstrap/reactstrap#215]
I have installed in my machine. Then I imported to test it. CSS did not effect.

**Comment by TheSharpieOne** [comment]
This library is only the components which produce the markup which matches bootstrap's markup/classes. It will produce all of the HTML with the proper classNames to be styled by bootstrap using bootstrap's CSS. You need to include bootstrap's CSS. You can do so

- You can use npm: `npm install --save bootstrap@4.0.0-alpha.5`
- You can reference it from a CDN: https://cdnjs.com/libraries/twitter-bootstrap/4.0.0-alpha.5
- You can use bower (though you really shouldn't): `bower install --save bootstrap#v4.0.0-alpha.5`
- You can download the files and manually add them to your project: https://github.com/twbs/bootstrap/archive/v4.0.0-alpha.5.zip

see https://github.com/twbs/bootstrap#quick-start for more

Related: #156 and maybe #173

**Comment by eddywashere** [comment]
@nndung179 track #189 for getting started guide work and review the comment above for info on ways to get the css applied to your setup. Thanks!
