### ISSUE TITLE
InputGroupAddon not found in 9.0.0-0 release

### ISSUE THREAD

**Issue by cody-elhard** [reactstrap/reactstrap#2171]
- components: `InputGroupAddon`
- reactstrap version `9.0.0-0`
- import method `esm`
- react version `16.5.2`
- bootstrap version `5.0.0-beta2`

### What is happening?

When I download the release source code from zip, InputGroupAddon is not found in the `index.js` exports file. However, it does exist on the `master` branch.

The images below represent respectively in this order
1. Code in Master
2. `node_modules/reactstrap/dist/reactstrap.js`
3. Downloading zip and viewing `src/index.js`

![code-master-branch-reactstrap](https://user-images.githubusercontent.com/32208000/117165720-5e5acb00-ad8b-11eb-85ff-28a3297867f8.png)
<img width="1484" alt="node-modules-reactstrap" src="https://user-images.githubusercontent.com/32208000/117165724-5ef36180-ad8b-11eb-8d9c-47e8e889f41c.png">
<img width="1478" alt="source-code-release-reactstrap" src="https://user-images.githubusercontent.com/32208000/117165737-6155bb80-ad8b-11eb-8e3e-bdd67266a61d.png">

### What should be happening?

When I download using NPM I would expect it to match master at the time of the pre release.

### Steps to reproduce issue

1. `yarn add reactstrap@9.0.0-0`
2. View `node_modules/reactstrap/dist/reactstrap.js`
3. Confirm that it does not export `InputGroupAddon`

### Error message in console
- When running `yarn start`
- `Attempted import error: 'InputGroupAddon' is not exported from 'reactstrap'.`

**Comment by rosauceda** [comment]
I have the same issue.

**Comment by tim-montague** [comment]
Reactstrap does not support Bootstrap 5

**Comment by cody-elhard** [comment]
I viewed `bootstrap5` and `InputGroupAddOn` does not yet exist in the src folder.

If I am given some direction, I can attempt to work on this one. However, I have not contributed to this project yet

**Comment by scottpageindysoft** [comment]
I don't know why this is closed.
This is a major issue for those of us upgrading to v9, that previously used InputGroupAddon.

What alternative(s) should we be using?  Google only has this one result that clearly calls out reactstrap 9 and InputGroupAddon.

**Comment by coucoseth** [comment]
was there a fix to this?

**Comment by arunachaleshwaran** [comment]
i also having same issue.

**Comment by jalik** [comment]
Please see https://github.com/reactstrap/reactstrap/releases/tag/v9.0.0

**Comment by deybith** [comment]
same issue.

**Comment by deybith** [comment]
@jalik is right.

Within Reactstrap 9 upgrade.

InputGroupAddon - This in no longer needed in Bootstrap 5, you can now add Buttons, Inputs directly to InputGroups in the order you wish.

the new way to do it is in: https://reactstrap.github.io/?path=/docs/components-inputgroup--input-group-addon

**Comment by srijan555** [comment]
Was there any fix provided for this issue recently?

**Comment by neerajvr09** [comment]
@srijan555 

InputGroupAddon has been removed , now you can use Buttons , Inputs directly to InputGroups  in the order you wish.
