### ISSUE TITLE
Target button for popover loses focus when clicked away but doesn't close the pop over.

### ISSUE THREAD

**Issue by clisterdmello** [reactstrap/reactstrap#2206]
- components: `popovers`
- reactstrap version `8.9.0`

### What is happening?

When i visit "popover" component on https://reactstrap.github.io/components/popovers/ 
I observed a behaviour. 

- Click on Launch popover [first example]
- Once the pop over is open, click off of the button. [to remove the focus from the button]
- The button has lost its focus but the tooltip still remains open

### What should be happening?

- The tooltip should have closed when you click away from button.

### Steps to reproduce issue

- Click on Launch popover [first example]
- Once the pop over is open, click off of the button. [to remove the focus from the button]
- Now though the button has no focus, the tooltip remains open

**Comment by illiteratewriter** [comment]
@clisterdmello This is the intended behaviour of [Popover](https://getbootstrap.com/docs/5.1/components/popovers/).
