### ISSUE TITLE
Any timeline for Bootstrap 5 upgrade ?

### ISSUE THREAD

**Issue by KKS1** [reactstrap/reactstrap#2211]
We are looking to adopt reactstrap for a green field Bootstrap 5 project. And wondering what's the expected timeline for Bs5 components in reactstrap ?

**Comment by robinjoerke** [comment]
also see this issue regarding the topic #1748

**Comment by bestguy** [comment]
Not a maintainer but I [commented on the issue above](https://github.com/reactstrap/reactstrap/issues/1748#issuecomment-834849509)

I believe the only thing missing currently is the Offcanvas component.  I have a WIP PR for it (https://github.com/bestguy/reactstrap/pull/1/files) but it needs some work if anyone is up for helping.  I'll try and get back to it myself as well.

**Comment by phwebi** [comment]
Update: We have a pre-release version supporting Bottstrap 5 here: https://github.com/reactstrap/reactstrap/releases/tag/v9.0.0-2. Feel free to use it/give feedback in #1748
