### ISSUE TITLE
Badges not working? 

### ISSUE THREAD

**Issue by mcqueene** [reactstrap/reactstrap#2216]
### Issue description

- components: `Badge`
- reactstrap version `#8.9.0`
- react version `#17.0.2`
- bootstrap version `#5.0.2`

### What is happening?

Badges are not visible / showing as white foreground on white blackground. 

### What should be happening?

Badges should appear as in the demo. 

### Steps to reproduce issue

1. Used npm to install new app per the instructions
2. Add Badge to page from samples https://reactstrap.github.io/components/badge/

### Error message in console
None

### Code

Basic react app with any code from https://reactstrap.github.io/components/badge/

<div>test start</div>
      <div>
      <Badge color="primary">Primary</Badge>
      <Badge color="secondary">Secondary</Badge>
      <Badge color="success">Success</Badge>
      <Badge color="danger">Danger</Badge>
      <Badge color="warning">Warning</Badge>
      <Badge color="info">Info</Badge>
      <Badge color="light">Light</Badge>
      <Badge color="dark">Dark</Badge>
    </div>
    <div>test end</div>
![Screenshot 2021-07-11 090633](https://user-images.githubusercontent.com/30414128/125198424-6588d400-e227-11eb-8f47-4ce60898ba25.jpg)

**Comment by jepfp** [comment]
same here.

**Comment by krnlde** [comment]
Did you also import the corresponding CSS file?

**Comment by trickybestia** [comment]
@mcqueene, I have run into this issue about an hour ago and found a solution. When you install bootstrap without explicitly specified version, yarn (or npm) automatically installs the latest version of the package. reactstrap can only work with Bootstrap 4, while you probably have Bootstrap 5 installed. So to resolve a conflict you can execute the following commands:
```sh
yarn remove bootstrap
yarn add bootstrap@4.6.0
```
or
```sh
npm remove bootstrap
npm install bootstrap@4.6.0
```
Hope this will help you too.

**Comment by phwebi** [comment]
@mcqueene We 're also currently working on updating to Bootstrap 5 and have a prerelease version here: https://github.com/reactstrap/reactstrap/releases/tag/v9.0.0-2 if you'd like to use it.

**Comment by phwebi** [comment]
Going to close this - please reopen if the above suggestions don't work. Thanks!
