### ISSUE TITLE
Tooltip arrow doesn't show up 

### ISSUE THREAD

**Issue by tpn1s** [reactstrap/reactstrap#2226]
- components: `UncontrolledTooltip`
- reactstrap version `#8.9.0`
- react version `#17.0.2`
- bootstrap version `#5.0.2`

### What is happening?

The tooltip does not have an arrow as I would expect. 

Here is what it looks like: 

![image](https://user-images.githubusercontent.com/87543204/125989760-0334dc4e-8a50-4ffd-a8a3-b1887459d45b.png)

### What should be happening?

There should be an arrow on the tooltip since that is what is what is shown in the docs. 

### Steps to reproduce issue

1.  New react app according to docs
```
npx create-react-app my-app
cd my-app/
npm i bootstrap
npm i reactstrap react react-dom
```
2.  Add boostrap to index.js
```
import 'bootstrap/dist/css/bootstrap.css';

```
3. Import component into App.js

```
import "./App.css";
import { UncontrolledTooltip } from "reactstrap";

function App() {
  return (
    <div className="App">
      <div>
        <p>
          Somewhere in here is a{" "}
          <span
            style={{ textDecoration: "underline", color: "blue" }}
            href="#"
            id="UncontrolledTooltipExample"
          >
            tooltip
          </span>
          .
        </p>
        <UncontrolledTooltip
          placement="right"
          target="UncontrolledTooltipExample"
        >
          Hello world!
        </UncontrolledTooltip>
      </div>
    </div>
  );
}

export default App;
```

5. See that there's no arrow:
![image](https://user-images.githubusercontent.com/87543204/125995450-9c538d93-4c84-4e67-92aa-5caa9af2ceb5.png)
Tested in safari and chrome. 

Looking at my bootstrap.css, I do see that the css for the arrow exists.

**Comment by phwebi** [comment]
Hi! The current release of reactstrap is on bootstrap 4! We 're currently working on updating to Bootstrap 5 have a prerelease version here: https://github.com/reactstrap/reactstrap/releases/tag/v9.0.0-2

**Comment by phwebi** [comment]
Going to close this - please reopen if ^ doesn't work. Thanks!
