### ISSUE TITLE
Attempted import error: 'react-bootstrap' does not contain a default export (imported as 'Offcanvas').

### ISSUE THREAD

**Issue by TalibehSerignKebbeh** [reactstrap/reactstrap#2229]
- components: `name`
- reactstrap version `#x.x.x`
- import method `umd/csj/es` 
- react version `#x.x.x`
- bootstrap version `#x.x.x`

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by cody-elhard** [comment]
According to your error message, `react-bootstrap` is a different library found here

https://github.com/react-bootstrap/react-bootstrap
