### ISSUE TITLE
NavbarBrand and Link

### ISSUE THREAD

**Issue by lednhatkhanh** [reactstrap/reactstrap#223]
Hi, I tried this `<NavbarBrand tag={Link} to="/">Home</NavbarBrand>` but it doesn't work, the text became darker and back to a normal text instead of a link.

**Comment by lednhatkhanh** [comment]
I found the answer here: #83

**Comment by mackbrowne** [comment]
@lednhatkhanh how did you fix this?  I read through the page and there doesn't seem to be a clear answer on how to fix NavbarBrand to use react-router instead of a basic a tag

**Comment by mackbrowne** [comment]
@lednhatkhanh and anyone else who ends up here

```  
<NavbarBrand tag={Link} to={'/'}>
    Novus Dashboard
</NavbarBrand>
```

**Comment by dodds-cc** [comment]
Thanks @mackbrowne, that works perfectly on a <Button> component too so I guess it works everywhere pretty much.
