### ISSUE TITLE
Upcoming Bootstrap alpha 6 breaking changes

### ISSUE THREAD

**Issue by eddywashere** [reactstrap/reactstrap#224]
From the alpha 6 ship list https://github.com/twbs/bootstrap/issues/20939

- [x] New flexbox column classes - (conflict with `auto` prop value) https://github.com/twbs/bootstrap/pull/20963
- [x] `Tag` renamed back to `Badge` https://github.com/twbs/bootstrap/pull/21020
- [x] `.in` and `.active` to `.show` - https://github.com/twbs/bootstrap/pull/20982/files https://github.com/twbs/bootstrap/pull/21036
  - affects the following:  Alert, Collapse, Dropdown, Modal, Popover, Tooltips
  - <strike>now could be a good time to switch `isOpen` to `isActive` across the library</strike>
  - ^ it might be possible to support both props in the next version vs doing that in current version
- [x] .row `.no-gutters` https://github.com/twbs/bootstrap/pull/21211
- [x] Progress bar rewritten https://github.com/twbs/bootstrap/pull/21473
- [x] Fix navbars and navs

Also, I think it's time to ship alpha releases that keep up with changes in `twbs/bootstrap#master` for people keeping up with latest. Also need to get #195 out to help with this.

## reactstrap v4 prerelease

We'll be using the `v4` branch to prioritize bootstrap breaking changes. Prerelease versions are now published to npm under the `next` tag and their respective prerelease version.

**Comment by ronnyhaase** [comment]
I'll take care of the new column classes.

**Comment by LiJinyao** [comment]
I'll take care of the Collapse component.

**Comment by eddywashere** [comment]
Released `4.0.0-alpha.2` to address the new `active` class https://github.com/reactstrap/reactstrap/blob/v4/CHANGELOG.md#400-alpha2-2016-11-28

**Comment by eddywashere** [comment]
More changes to look out for, https://github.com/twbs/bootstrap/pull/21036 `.in` -> `.active` -> `.show`.

**Comment by eddywashere** [comment]
Released [4.0.0-alpha.6](https://github.com/reactstrap/reactstrap/blob/v4/CHANGELOG.md#400-alpha6-2017-01-03) with a few fixes. Navbar and navs seem to be very broken. I don't think `.container-fluid` still works inside of `.navbar`. Might be a bug. Need to dig more into that. `Col` also needs to be updated.

**Comment by eddywashere** [comment]
Released `reactstrap@4.0.0-alpha.7`, read more about it here https://github.com/reactstrap/reactstrap/pull/269.

Closing this out. Feel free to open up individual issues for anything broken in bootstrap v4 branch / alpha v6.
