### ISSUE TITLE
How to make the table sortable? any reference?

### ISSUE THREAD

**Issue by Jazzykhan** [reactstrap/reactstrap#2256]
### Issue description

- components: `Table`
- reactstrap version `8.9.0`
- import method `umd/csj/es` 
- react version `17.0.2`
- bootstrap version `5.1.0`

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by bestguy** [comment]
Hi @Jazzykhan , this is not currently a part of reactstrap, though might be a good idea to have Table helper like this.

I am aware of this implementation which is based on Bootstrap & reactstrap:

https://github.com/appfolio/react-gears/blob/master/src/components/UncontrolledTable.tsx

Demo:
https://appfolio.github.io/react-gears/?path=/story/table--uncontrolled-table-example

**Comment by hollygirouard** [comment]
@Jazzykhan - Try `react-table`. It's got a lot more functionality.
