### ISSUE TITLE
Sidebar Left

### ISSUE THREAD

**Issue by zillBoy** [reactstrap/reactstrap#2257]
### Issue description

- components: `Modal`
- reactstrap version `8.6.0`
- react version `17.0.1`
- bootstrap version `4.5.2`

### What is happening?

<Modal
      isOpen={open}
      toggle={handleModal}
      **className='sidebar-sm'
      modalClassName='modal-slide-in'**
      contentClassName='pt-0'
    ></Modal>

**Comment by bestguy** [comment]
Hi @zillBoy ,

Not sure I understand, Bootstrap 4.x Modals transition in from top only - what are you referring to when you mean currently appearing from right?

**Comment by zillBoy** [comment]
Hi, @bestguy thanks for reaching out! I solved the problem.
I'm actually using **Vuexy Template** you can see this link
https://pixinvent.com/demo/vuexy-react-admin-dashboard-template/demo-1/apps/invoice/edit/4987

If you click on **Send Invoice Button** the modal actually comes in the form of a sidebar because they were using 
**modalClassName='modal-slide-in'** in Modal Component.

I did the inline styling
`{position: absolute; left: 0}`
Solved it for me and now the sidebar comes appears from the left side.

Thank You

**Comment by bestguy** [comment]
Sounds good, FYI for the future: Bootstrap 5 and reactstrap 9 will support the new "Offcanvas" component: https://getbootstrap.com/docs/5.1/components/offcanvas/#live-demo

This sounds similar to your needs.
