### ISSUE TITLE
Tooltip arrows?

### ISSUE THREAD

**Issue by gthomas-appfolio** [reactstrap/reactstrap#232]
This may be a work in progress, but noticed that the reactstrap Tooltip does not have an arrow like the Bootstrap v4 docs:

BS4:
http://v4-alpha.getbootstrap.com/components/tooltips/#static-demo

Reactstrap:
https://reactstrap.github.io/components/tooltips/#

Is this intentional or an oversight?    Happy to look at this if so, but wanted to check first.

**Comment by eddywashere** [comment]
Oof. Thanks for reporting! Looks like a change in the latest alpha release. See https://github.com/twbs/bootstrap/commit/e7f79b32f22d7f39138a7003272b54ceb3b12426#diff-9ff9d982e0cf16baef57b77d798f5400

Feel free to send a pr.

**Comment by gthomas-appfolio** [comment]
Thanks for the quick update, will take a look!

**Comment by gthomas-appfolio** [comment]
This is a bit more involved than I assumed - I'm still looking at it but if anyone more knowledgable of the codebase wants to grab it in the meantime, please do.

**Comment by eddywashere** [comment]
@gthomas-appfolio published in `3.9.2` and `4.0.0-alpha.2`. Also pushed out the `in` -> `.active` switch in `4.0.0-alpha.2`.
