### ISSUE TITLE
How to change Components Default Tag?

### ISSUE THREAD

**Issue by sajumani** [reactstrap/reactstrap#235]
Hi,

How can i change reactstrap Components default tags ?? 

Example : DropdownToggle   render with Button Tag, i want to make it as Anchor Tag

Anybody please could you help me ???

**Comment by kjcpaas** [comment]
@sajumani You can specify `tag` prop. e.g.

```jsx
<DropdownToggle tag="anchor" />
```

It can also be React component, e.g.

```jsx
import { Button } from 'reactstrap'

<DropdownToggle tag={Button} />
```

**Comment by eddywashere** [comment]
Not enough info. I believe this is a duplicate of #213. Be sure to include the reactstrap version when submitting a request like this.
