### ISSUE TITLE
Can't run with `npm link`

### ISSUE THREAD

**Issue by ssteinerx** [reactstrap/reactstrap#237]
### Issue description

I have `"reactstrap": "^3.9.1"` in my `package.json` and I'm wanting to work on some of the issues in this repo. 

Installed via `npm`, I get version 3.9.1, and all works as expected but, obviously, I can't edit the project files.

So, I attempted to link to a local checkout of this repository by checking out the source code and:

```bash
git clone...reactstrap
cd reactstrap
npm link
cd <my project dir>
npm link reactstrap
```

This seems to correctly link to reactstrap (the symlink to /usr/local/lib/node_modules/reactstrap is correctly inserted into my node_modules/ subdir).

And, that should link me to the local reactsrap, right?

Instead, I get:
```
ERROR in ./static/js/example.jsx
Module not found: Error: Cannot resolve module 'reactstrap' in .../example/static/js
 @ ./static/js/example.jsx 13:18-39
```

- version `#3.9.1`
- components: `all`

### Steps to reproduce issue
See above.

**Comment by TheSharpieOne** [comment]
You'll have to run the build in your local reactstrap repo to generate the files npm is looking for I can the lib folder.

**Comment by ssteinerx** [comment]
Somehow I thought `npm run build` would/should have been run as part of the link but I guess not.  Thanks!

I'm going to put this in the README or CONTRIBUTING doc on the first pull request I make on this repo.
