### ISSUE TITLE
Legacy 8.10.1 Documentation does not load correctly

### ISSUE THREAD

**Issue by jSadoski** [reactstrap/reactstrap#2371]
- components: n/a
- reactstrap version 9.0.0
- import method: n/a
- react version: n/a
- bootstrap version: n/a

### What is happening?

1. Visiting https://reactstrap.github.io/legacy/8.10.1 directly loads the basic page but cannot access any of the assets. Links also lead to pages on the root path. I'm guessing the links did not get updated to the new legacy docs path.

2. Clicking the link for the docs from the ReactStrap 9 documentation loads an empty page in Storybook, I'm guess because it doesn't exit the Storybook router.

### What should be happening?

The legacy documentation loads correctly.

### Steps to reproduce issue

1. Visit https://reactstrap.github.io/legacy/8.10.1/
2. Click the ReactStrap 4 legacy documentation link from within ReactStrap 9 Legacy Documentation.

### Error message in console

```
logo.png:1 Failed to load resource: the server responded with a status of 404 ()
prism.js:1 Failed to load resource: the server responded with a status of 404 ()
main.css:1 Failed to load resource: the server responded with a status of 404 ()
bundle.js:1 Failed to load resource: the server responded with a status of 404 ()
docs.css:1 Failed to load resource: the server responded with a status of 404 ()
prism.js:1 Failed to load resource: the server responded with a status of 404 ()
bundle.js:1 Failed to load resource: the server responded with a status of 404 ()
main.css:1 Failed to load resource: the server responded with a status of 404 ()
docs.css:1 Failed to load resource: the server responded with a status of 404 ()
```

### Code

n/a

**Comment by jSadoski** [comment]
Poking around, I found #2368 which has been merged and uses this link, which works right now: https://deploy-preview-2356--reactstrap.netlify.app/.

**Comment by RajeevPullat** [comment]
@jSadoski  Super helpful <3

**Comment by jSadoski** [comment]
An update: The link in the v9 docs to the legacy v8 docs still works correctly, but it's still linking to the deploy preview 2356, which I'm guessing is likely to change.

**Comment by jSadoski** [comment]
Since the link works, I consider this resolved for now. Thank you!

**Comment by therajuahammad** [comment]
> Poking around, I found [#2368](https://github.com/reactstrap/reactstrap/pull/2368) which has been merged and uses this link, which works right now: https://deploy-preview-2356--reactstrap.netlify.app/.

currently it also doen't work
