### ISSUE TITLE
Modal "onClosed" handler doesn't called

### ISSUE THREAD

**Issue by Tsyklop** [reactstrap/reactstrap#2373]
- components: `Modal`
- reactstrap version `#9.0.0`
- import method `import {Modal, ModalBody, ModalFooter, ModalHeader} from "reactstrap";` 
- react version `#17.0.2`
- bootstrap version `5.1.3`

### What is happening?

`onClosed` handler doesn't called after modal closed. With `onOpened` all fine.

### What should be happening?

`onClosed` handler called and print "onCLosed" in console.

### Steps to reproduce issue

1. Open modal
2. Close modal and see console. 

### Code

 ```

           <Modal isOpen={shown}
                   toggle={toggle}
                   centered
                   onOpened={() => {
                      console.log('onOpened');
                   }}
                   onClosed={() => {
                       console.log('onClosed');
                   }}>

                ...

            </Modal>
        
```

**Comment by AdeonMaster** [comment]
I've tried it and everything is working as expected. You can check this example to ensure - https://codesandbox.io/s/nifty-lake-696i1
