### ISSUE TITLE
Carousel Component captions overflow

### ISSUE THREAD

**Issue by ronaklalwaniii** [reactstrap/reactstrap#2393]
- components: `Carousel`
- reactstrap version `9.0.0`
- react version `17.0.2`
- bootstrap version `5.1.0`

### What is happening?

- When using a carousel the captions are visible twice & overflow out of the component.

### What should be happening?

- Captions shouldn't overflow out of the component.

### Steps to reproduce issue

- Copy the code from documentation: [https://reactstrap.github.io/?path=/docs/components-carousel--carousel](https://reactstrap.github.io/?path=/docs/components-carousel--carousel
)
### Error message in console

- Warning: Carousel.childContextTypes is specified but there is no getChildContext() method on the instance. You can either define getChildContext() on Carousel or remove childContextTypes from it.

![image](https://user-images.githubusercontent.com/44769573/141961838-56fb8b25-1070-40a7-98ab-9f6dc5300fe4.png)

![image](https://user-images.githubusercontent.com/44769573/141961903-f1f91150-eeea-4b48-8003-2e7131e5f552.png)

**Comment by filippos13** [comment]
I am facing the same problem with the same setup.

**Comment by Gunbit** [comment]
same problem....

**Comment by christian0712** [comment]
Same problem x3

**Comment by vmoll** [comment]
Same problem here too!

**Comment by BrandonDevU95** [comment]
Same problem x4, When are they going to fix this?

**Comment by YohannesTz** [comment]
I am still facing the problem, is there any fix?

**Comment by kirciemre** [comment]
I used this for CSS to solve bad text but the error message in colsone still continues 😢 

`.carousel-indicators button {
  color: transparent;
}`

**Comment by YohannesTz** [comment]
oh thanks! I just removed the text from the carousel and It worked!

**Comment by filippos13** [comment]
Removing the caption is a temp solution and should not be considered as a fix. Lately, the carousel slides one way is anyone else getting the same behaviour?

**Comment by YohannesTz** [comment]
yeah removing captions might be a temporary solution but that's what I got at that time. I am also getting the same weird behavior on the carousel, It only slides one way, also doesn't have animation to the other way.

**Comment by kirciemre** [comment]
Even reactstrap's own documentation has the same error. Unfortunately, we will manage with workarounds until a solution is found by the reactstrap team. :face_with_head_bandage:

**Comment by AdetolaAremu** [comment]
I am experiencing same issue, showing up in my console

**Comment by Krobirow** [comment]
Same both problems. Even if we can fix one bug by CSS, second with warning is still a question.. 
Current question is more than one year old, probably many developers just change the carousel to the good one(any another library), when facing this problem.

**Comment by th-e0** [comment]
Hi!
"reactstrap": "^9.1.1",
Warning: Carousel.childContextTypes is specified but there is no getChildContext() method on the instance. You can either define getChildContext() on Carousel or remove childContextTypes from it.
Is it not fixed??

**Comment by kirciemre** [comment]
> 

It is working perfectly. Those who have problems can update reactstrap with npm.

**Comment by nicks6853** [comment]
> Hi! "reactstrap": "^9.1.1", Warning: Carousel.childContextTypes is specified but there is no getChildContext() method on the instance. You can either define getChildContext() on Carousel or remove childContextTypes from it. Is it not fixed??

Same issue here

**Comment by illiteratewriter** [comment]
@th-e0 , @nicks6853 can you create a reproducible example?

**Comment by nicks6853** [comment]
The example from the docs has this problem. I use NextJS in my project so I created[ an example in NextJS](https://codesandbox.io/s/staging-mountain-r7ipfh?file=/pages/index.js).
