### ISSUE TITLE
No documentation of props such as "className"

### ISSUE THREAD

**Issue by tykavanaugh** [reactstrap/reactstrap#2409]
### What is happening?
I was hoping to add stuff like margins or padding. I found by sheer accident a code snippet of someone using "className" and that seemed to work. ie `className="m-5"` to add bootstrap classes that aren't specific to component

### What should be happening?
Most common and seemingly very important props are not explained at all in the documentation. For example, if you wanted to add margin or padding like I did, and search reactstrap docs, you will not find anything helpful. `className` is simply mentioned as a prop that is a string with no further explanation. The purpose of it is not clear unless you already know exactly what it does.

**Comment by illiteratewriter** [comment]
added documentation. :)
