### ISSUE TITLE
Carousel: Console warning about Context

### ISSUE THREAD

**Issue by Reddine** [reactstrap/reactstrap#2417]
- components: Carousel
- reactstrap version `#9.0.1`
- import method `es` 
- react version `#17.0.2`
- bootstrap version `#5.1.3`

### What is happening?

Get a warning in the console : 

`Warning: Carousel.childContextTypes is specified but there is no getChildContext() method on the instance. You can either define getChildContext() on Carousel or remove childContextTypes from it.`

### What should be happening?

I think `childContextTypes` should be removed from Carousel component since it's not used after https://github.com/reactstrap/reactstrap/pull/2182 changes 

### Steps to reproduce the issue

A link to the code example is provided

### Error message in console

```
Warning: Carousel.childContextTypes is specified but there is no getChildContext() method on the instance. You can either define getChildContext() on Carousel or remove childContextTypes from it.<br>Carousel@https://reactstrap-yjfysi.stackblitz.io/turbo_modules/reactstrap@9.0.1/dist/reactstrap.umd.js:2810:32<br>div<br>Example@https://reactstrap-yjfysi.stackblitz.io/~/Example.js:45:51<br>div<br>Container@https://reactstrap-yjfysi.stackblitz.io/turbo_modules/reactstrap@9.0.1/dist/reactstrap.umd.js:468:21<br>App@https://reactstrap-yjfysi.stackblitz.io/~/index.js:31:9
```

### Code

https://stackblitz.com/edit/reactstrap-yjfysi?devtoolsheight=33&file=Example.js

**Comment by PysarenkoDS-BWT** [comment]
I found this issue on https://ovio.org/projects and would love to contribute!

**Comment by Reddine** [comment]
the issue seems to be fixed! closing!
