### ISSUE TITLE
Hardcoded `zIndex: 1000`on Modal

### ISSUE THREAD

**Issue by JohanBengtsson** [reactstrap/reactstrap#243]
### Issue description

- version `#3.9.1`
- components: `Modal.js`

In the following [commit](https://github.com/reactstrap/reactstrap/commit/9ddeb8a0be17eddddac278490f9b278096494781)  a hardcoded `zindex = 1000` was added to the root element of the modal that is created in `Modal.js`. This can be a problem for users that have elements above `z-index 1000` since the modal itself and the backdrop will be underneath these elements. We have solved this temporarily by using the `3.9.0` release, but it would be nice if the hardcoded `1000` on line `129` in `Modal.js` can be made configurable or the issue can be resolved in some other way.

**Comment by eddywashere** [comment]
+1 to making it configurable

**Comment by JohanBengtsson** [comment]
@TheSharpieOne That was quick, thanks! :)
