### ISSUE TITLE
Input type="select" onBlur does not trigger onfocusout

### ISSUE THREAD

**Issue by ECCKaka** [reactstrap/reactstrap#2435]
- components: `Input`
- reactstrap version `#8.4.1`
- import method `umd/csj/es` 
       import "bootstrap/dist/css/bootstrap.min.css";
- react version `#16.12.0`
- bootstrap version `#4.3.1`

### What is happening?

<Input type="select"> onBlur does not trigger until click on other fields or click on the <option>

### What should be happening?

<Input type="select"> onBlur should be triggered when close the selection

### Steps to reproduce issue

1. click on the selection input
2. click on other places to close the select input
3. onBlur will not be triggered
4. click on another input field/ other place once more(onBlur will trigger), for example: <input type='text'>
5. click on other places other than this "text" input
6. onBlur will be triggered right away

### Error message in console

```
No Error
```

### Code
https://codesandbox.io/s/goofy-wood-o9s8w?file=/src/App.js

https://user-images.githubusercontent.com/21689797/149574697-ea215fdc-15cc-450f-a5d8-cb3ad44f8904.mov

**Comment by Thedineshk24** [comment]
Hi, i think it's react bug. please check this [Link => ](https://github.com/facebook/react/issues/12363)

I've also [created a simple Input component](https://codesandbox.io/s/onblur-bug-react-bootstrap-o12id?file=/src/App.js) using bootstrap and react it look like the same as Reactstrap 

`<Input type="select" />`

there also I'm facing 

> onBlur does not trigger until click on other fields  **ISSUE**

**Comment by mohammadizanloo55** [comment]
Hello @Chrisfufu This is also normal in vanilla JavaScript and not really an reactstrap or react problem For example, check this [code sand box ](https://codesandbox.io/s/exciting-water-tk0tiv?file=/index.html)You can see that there is also a problem in vanilla JavaScript
