### ISSUE TITLE
NavbarToggler not working on click 

### ISSUE THREAD

**Issue by ansulagrawal** [reactstrap/reactstrap#2474]
- components: `NavbarToggler`
- reactstrap version `#9.0.0`
- import method `umd/csj/es` 
- react version `#x.x.x`
- bootstrap version `#x.x.x`

### What is happening?
On smaller size navbar toggle is not working.

https://user-images.githubusercontent.com/55939700/157454993-9112f5e6-3925-4e79-a5e6-8c520d92da5a.mp4

### What should be happening?

The navbar should be expand.

### Code
https://codesandbox.io/s/trusting-ritchie-k5k0lw?file=/src/Main.js:440-453
The above link is for the code.

**Comment by BiswaViraj** [comment]
@ansulagrawal You're using the `Collapse` component that needs `isOpen` props and need to update the value passed to `isOpen` when clicking on the `NavbarToggler`.
Please, look into this example https://github.com/reactstrap/reactstrap/blob/master/stories/examples/NavbarToggler.js

**Comment by k-funk** [comment]
I was also under the impression that this was an uncontrolled component, due to the example code at https://reactstrap.github.io/?path=/docs/components-navbar--navbar#navbar-toggler only showing 
```
<Collapse navbar>
  ...
</Collapse>
```
