### ISSUE TITLE
noRefCheck function not working for class component

### ISSUE THREAD

**Issue by HallofFamer** [reactstrap/reactstrap#2476]
It seems that the documentation on Reactstrap has something like this to deal with findDOMNode warning: 

```
<Alert
  color="info"
  toggle={function noRefCheck(){}}
>
  I am an alert and I can be dismissed!
</Alert>
```

But it does not seem to work for me, still get the warning: `findDOMNode is deprecated in StrictMode.` Moreover, the toggle will not even work, it does not dismiss the alert at all. I am confused, what is this noRefCheck function at all, and how to use it? I dont even see anyone asking this so I decide to bring it up.

**Comment by ansulagrawal** [comment]
Its not working for Functional component too.

**Comment by BiswaViraj** [comment]
Follow the code from here https://github.com/reactstrap/reactstrap/blob/master/stories/examples/AlertDismiss.js
The storybook docs examples are not 100% correct.

**Comment by HallofFamer** [comment]
I still dont understand what is noRefCheck() function and how it works, it doesnt seem to prevent the warning message.

**Comment by illiteratewriter** [comment]
`function noRefCheck(){}` this part of the code is added by StoryBook. [This](https://github.com/reactstrap/reactstrap/blob/master/stories/examples/AlertDismiss.js) as pointed out by @BiswaViraj is the complete code for that example.

**Comment by illiteratewriter** [comment]
Currently, we are in the process of updating the docs (#2545). Let me know your thoughts. PRs are welcome.
