### ISSUE TITLE
Dropdown menu doesn't open up

### ISSUE THREAD

**Issue by DerrickJames** [reactstrap/reactstrap#248]
### Issue description
The toggle method correctly sets the dropdownOpen state but the dropdown menu doesn't open up on dropdown click.

- version `4.0.0-alpha.2 & 4.0.0-alpha.3`
- components: `Dropdowns`

### Steps to reproduce issue
Just use the dropdowns example found in the docs.

**Comment by eddywashere** [comment]
@DerrickJames in the latest bootstrap v4 branch (potentially the alpha v6 release), the classes we're changed from `.in` to `.active`. It's documented in the v4 branches [changelog](https://github.com/reactstrap/reactstrap/blob/v4/CHANGELOG.md#bug-fixes). We don't have versioned docs yet. I've got an issue to track that. For now, the bare minimum is having this prerelease version.

I'm not sure what version of css you're using. For Bootstrap alpha 5, the latest release, reactstrap `3.9.3` should be used. To use what's in the Bootstrap v4-dev branch, or latest, use the reactstrap `4.0.0-alpha` releases.

To test out in this repo, try installing the latest commit from master in bootstrap. For reactstrap repo this would be:

```
npm install twbs/bootstrap#d9ab97b2d0f8e16c46415ef4a8eeb53f0ebf6c93 --save
```

**Comment by albertkim** [comment]
I'm having this issue right now with the Bootstrap alpha 6 and reactstrap 4.0.1 by following the documentation.

**Comment by TheSharpieOne** [comment]
@albertkim I just used this last night with the latest versions without any issues. Can you post your component code or use something like webpackbin, jsfiddle, or  codependent to showcase this issue?

**Comment by virgofx** [comment]
Working for me in latest tagged releases.

**Comment by albertkim** [comment]
Here is the simplest code for this scenario

```
import * as React from 'react'
import {ButtonDropdown, DropdownToggle, DropdownMenu, DropdownItem} from 'reactstrap'

export class Test extends React.Component {

  constructor() {
    super()
    this.state = {
      dropdownOpen: false
    }
  }

  render() {
    return (
      <ButtonDropdown isOpen={this.state.dropdownOpen} toggle={() => {
        this.setState({dropdownOpen: !this.state.dropdownOpen})
      }}>
        <DropdownToggle caret>
          Button Dropdown
        </DropdownToggle>
        <DropdownMenu>
          <DropdownItem header>Header</DropdownItem>
          <DropdownItem disabled>Action</DropdownItem>
          <DropdownItem>Another Action</DropdownItem>
          <DropdownItem divider />
          <DropdownItem>Another Action</DropdownItem>
        </DropdownMenu>
      </ButtonDropdown>
    )
  }

}
```

With the following package.json entries:

```
"bootstrap": "^4.0.0-alpha.6",
"reactstrap": "^4.0.1"
```

The wrapping div seems to go from `btn-group` to `btn-group show`, and the actual button goes from `dropdown-toggle btn btn-secondary` to `dropdown-toggle active btn btn-secondary`. Is this correct?

**Comment by DavidCarpus** [comment]
I am getting this same behavior with basic Dropdown inside a Navbar . (The 'active' class is being added/removed from the div containing the dropdown items themselves but the .dropdown-menu 'display' is 'none' and thus the items never become visible)
```
"bootstrap": "4.0.0-alpha.6",  
"reactstrap": "^4.8.0",  
```

Code Snippet
```
export default class Menu extends React.Component {
    constructor(props) {
        super(props);
        
        this.toggle = this.toggle.bind(this);
        this.state = {
            dropdownOpen: false
        };
    }
    
    toggle() {
        this.setState({
            dropdownOpen: !this.state.dropdownOpen
        });
    }

    render(){
        return (
            <div key={this.props.index} >
                  <Nav navbar>
                    <Dropdown isOpen={this.state.dropdownOpen} toggle={this.toggle} nav>
                      <DropdownToggle color="primary" nav caret data-toggle="NavDropdown">
                        Dropdown
                      </DropdownToggle>
                      <DropdownMenu>
                        <DropdownItem header>Header</DropdownItem>
                        <DropdownItem disabled>Action</DropdownItem>
                        <DropdownItem>Another Action</DropdownItem>
                        <DropdownItem divider />
                        <DropdownItem>Another Action</DropdownItem>
                      </DropdownMenu>
                  </Dropdown>
                  </Nav>
            </div>
        )
    }
```

I am hoping I just missed something in the documentation.
