### ISSUE TITLE
Missing support for Buttons as Links (aka btn-link)

### ISSUE THREAD

**Issue by AurelioDeRosa** [reactstrap/reactstrap#2500]
- components: `Button`
- reactstrap version `9.0.2`
- import method `es`
- react version `#17.0.1`
- bootstrap version `#5.1.3`

### What is happening?

There seems to be no way to recreate a button as a link as shown in the example here: https://getbootstrap.com/docs/5.0/components/buttons/#examples

### What should be happening?

Support could be provided

### Steps to reproduce issue

N/A

**Comment by lukbak** [comment]
I do not understand. Do you mean there is no such example in the component documentation?

`<Button color="link">Link</Button>`

**Comment by AurelioDeRosa** [comment]
My bad on not finding it. I didn't realize the "link" would be under `color`.
