### ISSUE TITLE
Reactstrap 9 require('reactstrap') returns string in Create React App

### ISSUE THREAD

**Issue by davidlyons** [reactstrap/reactstrap#2508]
### What is happening?

In Create React App:

`require('reactstrap')`

with Reactstrap 8, returns `Module` ✅

with Reactstrap 9, returns string `/static/media/reactstrap.d7ce21f132f9948c585d.cjs` ❌
so Reactstrap components are undefined

### What should be happening?

`require('reactstrap')` should return `Module` in Reactstrap 9

### Repo reproducing the issue:
https://github.com/davidlyons/cra-reactstrap-require/blob/main/src/App.js
Run npm install && npm start and check console

**Comment by davidacevedo** [comment]
We can't completely get rid of commonjs yet as testing frameworks like jest still don't support esm outside of an experiment. Commons is usually needed for the node side of things.

**Comment by illiteratewriter** [comment]
@davidacevedo so should we try and fix this issue?

**Comment by davidacevedo** [comment]
Tbh, I don't really understand the issue above. Is this in the webpack context, node context, or something else? Can this possibly be a configuration error?
I tried require('reactstrap') in node and it seems to import correctly.

**Comment by davidlyons** [comment]
Steps to reproduce:
```
npx create-react-app cra-reactstrap-require
cd cra-reactstrap-require
npm i reactstrap bootstrap
npm start
```
add to App.js:
```
const reactstrap = require('reactstrap');
console.log(reactstrap);
console.log(reactstrap.Button);
```

Here's a repo reproducing the issue:
https://github.com/davidlyons/cra-reactstrap-require/blob/main/src/App.js
Run `npm start` and check console

**Comment by Elie-asmar** [comment]
Any potential fixes or news reagrding this issue?

**Comment by davidlyons** [comment]
@Elie-asmar While this doesn't address the root issue, I found a hopefully temporary workaround for this in the meantime using react-app-alias to point reactstrap to the reactstrap.modern.js file instead of reactstrap.cjs

https://github.com/oklas/react-app-alias#usage

jsconfig.paths.json:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "reactstrap": ["node_modules/reactstrap/dist/reactstrap.modern.js"]
    }
  }
}
```

**Comment by davidlyons** [comment]
This is no longer an issue with one of the latest versions of reactstrap. Tested with reactstrap 9.2.0. Thanks!
