### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by davidacevedo** [reactstrap/reactstrap#2545]
Adding more text content to the docs to make it look more like the Bootstrap documentation might make it easier to use the documentation. Currently, we have examples in stories, with almost zero text and I think adding text might make things better.

For example [the accordion flush page for Reactstrap](https://reactstrap.github.io/?path=/docs/components-accordion--accordion#flush) doesn't say anything. I was thinking of taking the text from [Bootstrap accordion flush](https://getbootstrap.com/docs/5.1/components/accordion/#flush) and adding to it to look something like the following:

> Add `flush` prop to remove the default background-color, some borders, and some rounded corners to render accordions edge-to-edge with their parent container.

This would make it easier for users to use Reactstrap without referring to the bootstrap docs. Let me know your thoughts.

_Originally posted by @illiteratewriter in https://github.com/reactstrap/reactstrap/discussions/2509#discussioncomment-2902389_

**Comment by phoneticallySAARTHaK** [comment]
The sidebar is kinda weird in mobile as well... takes too much space

https://user-images.githubusercontent.com/71564671/174047239-ba0a25ac-50f7-4c51-9712-f2cdbcc8a397.mp4

(notice the clicks, it doesn't auto-hide)

**Comment by illiteratewriter** [comment]
@phoneticallySAARTHaK This is more of an issue with Storybook rather than with Reactstrap

**Comment by phoneticallySAARTHaK** [comment]
> ith Reactstrap

I realise. Still, Reactstrap is UI framework. It wouldn't feel right if their own docs website had silly bugs.
