### ISSUE TITLE
Add crossfade to Carousel

### ISSUE THREAD

**Issue by illiteratewriter** [reactstrap/reactstrap#2555]
- components: `Carousel`

Carousel component doesn't have `crossfade` prop. [Bootstrap doc for crossfade](https://getbootstrap.com/docs/5.0/components/carousel/#crossfade).

**Comment by illiteratewriter** [comment]
Sure. Go ahead. I think it actually has a prop called `fade`, but it is not working as expected.

**Comment by nerdjfpb** [comment]
Hi @illiteratewriter I've write a solution, can you review this? Thanks
