### ISSUE TITLE
CloseButton is missing in the index.d.ts file

### ISSUE THREAD

**Issue by dudina-ma** [reactstrap/reactstrap#2563]
- components: `CloseButton`
- reactstrap version `#9.1.1`
- react version `#18.2.0`
- bootstrap version `#5.1.3`

### What is happening?

```typescript
import {CloseButton} from 'reactstrap';
```
gives an error that reactstrap has no exported member `CloseButton`. Turns out, its export is missing in `index.d.ts`.

### What should be happening?

`CloseButton` should be imported with no errors

### Steps to reproduce issue

1. import `CloseButton` in your ts-file

**Comment by illiteratewriter** [comment]
Closed with #2564
