### ISSUE TITLE
Can't find the Switch component in Storybook

### ISSUE THREAD

**Issue by akoskm** [reactstrap/reactstrap#2587]
I'm looking for this component:
![image](https://user-images.githubusercontent.com/3111627/182101712-7589b03e-96db-4f05-8f26-52cd0199b8d6.png)

Bootstrap 5 link: https://getbootstrap.com/docs/5.0/forms/checks-radios/#switches

A variation of it is also featured on this demo site: https://demo.uifort.com/bamburgh-react-crypto-application-reactstrap-pro-demo/Settings

![image](https://user-images.githubusercontent.com/3111627/182101791-82485396-2d8d-46d4-9015-75b926109d6f.png)

**Comment by illiteratewriter** [comment]
You can use a switch component like:
```
<FormGroup switch>
  <Input type="switch" />
  <Label>Some label</Label>
</FormGroup>
```

**Comment by akoskm** [comment]
@illiteratewriter thanks, it worked! 🙇‍♂️

**Comment by illiteratewriter** [comment]
We will add it to the docs and then mark it as complete. :)
