### ISSUE TITLE
Is it possible to utilize toggle switch button properly using reactstrap?

### ISSUE THREAD

**Issue by yehtet-linn** [reactstrap/reactstrap#2592]
- components: `ButtonToggle`
- reactstrap version `9.0.2`
- import method `umd/csj/es` 
- react version `18`
- bootstrap version `5.1.3`

### What is happening?
 I cannot utilize toggle switch button properly.

### What should be happening?
 It should be something like ButtonToggle has full functionality.

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by illiteratewriter** [comment]
Can you elaborate on what you mean by full functionality?

**Comment by yehtet-linn** [comment]
Yes. Now, I've got it by using react-switch package. Before that, I was trying to use ButtonToggle from reactstrap. But, it didn't work for me. That's all about it. Thank you.
