### ISSUE TITLE
React motion

### ISSUE THREAD

**Issue by xgrommx** [reactstrap/reactstrap#26]
How about https://github.com/chenglou/react-motion instead of react-addons-transition-group ?

**Comment by eddywashere** [comment]
@xgrommx great question. I'm not entirely against it.

I initially went with a DIY component for applying fade in/out. Then I moved the inner workings of that component to a react core project, `react-addons-transition-group`. I heard that it will probably be moved to another maintainer. Even with that, I still think it's a simple enough api and most of the bootstrap related animations come from applying bootstrap classes. I don't think it's worth changing at the moment but worth investigating.

I'd love to see an examples of this with any of the following: dropdowns, tooltips, popovers, modals, collapse.

**Comment by eddywashere** [comment]
Closing this out. Feel free to re-open with an example.
