### ISSUE TITLE
DropdownToggle with children does not close when toggle is clicked

### ISSUE THREAD

**Issue by FoodProduct** [reactstrap/reactstrap#2660]
- components: `DropdownToggle`
- reactstrap version `#9.1.5`
- import method `es` 
- react version `#18.2.0`, `#16.14.0`
- bootstrap version `#5.2.3`

### What is happening?

Clicking a `<DropdownToggle>` with non-string children on an open Dropdown triggers `toggle()` twice, which prevents the dropdown from closing.

### What should be happening?

Clicking the dropdown toggle should close the dropdown.

### Steps to reproduce issue

https://github.com/FoodProduct/bootstrap-dropdown-component
1. Have a `<DropdownToggle>` whose children are not a simple string (e.g.`<div>Click me</div>`)
2. Open the dropdown
3. Click the dropdown toggle

### Error message in console

N/A

### Code

https://stackblitz.com/edit/reactstrap-vcxbgg?file=Example.js

This is because the document click event handler does not recognize the click event on the toggle properly, causing an extra trigger, i.e. the following check fails:
https://github.com/reactstrap/reactstrap/blob/75a4ab3d5a3cb200e21cd124ca9ee4a90c3ef25f/src/Dropdown.js#L101

**Comment by rabarrota** [comment]
Any update on this?

**Comment by FoodProduct** [comment]
> Any update on this?

@illiteratewriter graciously opened [a PR with the fix](https://github.com/reactstrap/reactstrap/pull/2673) in December, but unfortunately it does not seem to have been reviewed yet 😞
