### ISSUE TITLE
Warning: Container: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by pksorensen** [reactstrap/reactstrap#2662]
React seems to be going away from defaultProps, and we should use default parameters instead

```
const defaultProps = {
  tag: 'div',
};
//Remove above and add like this i assume?
function Container(props) {
  const { className, cssModule, fluid, tag: Tag = 'div', ...attributes } = props;
```

Low hanging fruit for new contributor to carry out?

**Comment by amillward** [comment]
Using Next13 this now spams the console with red warnings
https://codesandbox.io/p/sandbox/default-props-reactstrap-np5tdy

<img width="747" alt="Screenshot 2023-05-10 at 20 58 35" src="https://github.com/reactstrap/reactstrap/assets/1857493/501b303a-21a0-47c1-a06a-9637b4f83a40">

**Comment by Zaknarfen** [comment]
I'm having the same problem with Next.js 13

**Comment by DominicWrege** [comment]
same here

**Comment by 0xAnakin** [comment]
Any updates on this?

**Comment by kevb10** [comment]
> Any updates on this?

Take a look at https://github.com/vercel/next.js/discussions/52522
