### ISSUE TITLE
Offcanvas Backdrop not triggering close

### ISSUE THREAD

**Issue by tamb** [reactstrap/reactstrap#2664]
- components: `Offcanvas`
- reactstrap version `#9.1.4`
- import method `es` 
- react version `#18.2.0`
- bootstrap version `#5.2.1`

### What is happening?
Offcanvas is working but I would like to be able to close the component by clicking the backdrop

### What should be happening?
Clicking the offcanvas backdrop should close the component. This is the functionality of Bootstrap.

### Steps to reproduce issue

1. Open Offcanvas
2. Click the backdrop
3. The component does NOT close

### Error message in console

```
paste error message with stacktrack here
```

**Comment by illiteratewriter** [comment]
Can you provide a reproducible example in CodeSandbox or similar? 

https://reactstrap.github.io/?path=/docs/components-offcanvas--offcanvas 
This closes when clicked on the backdrop.

**Comment by tamb** [comment]
@illiteratewriter Toggle "fade" to false and it breaks

**Comment by inboundsan** [comment]
> Can you provide a reproducible example in CodeSandbox or similar?
> 
> https://reactstrap.github.io/?path=/docs/components-offcanvas--offcanvas This closes when clicked on the backdrop.

Please update the example in the URL. It doesn't show the correct usage of this component. I have to go to the first version of the source code to see its usage.

**Comment by tamb** [comment]
@inboundsan If you use the Storybook documentation and toggle "fade" to `false` it breaks. You can't click the backdrop and close the off canvas component.
