### ISSUE TITLE
Input autofocus - Missing property?

### ISSUE THREAD

**Issue by Vadorequest** [reactstrap/reactstrap#270]
Is there a way to set the property `autofocus` on an `Input`? I looked at the doc and the code and I don't see any. Did I miss something?

I'm using the v4 version.

**Comment by eddywashere** [comment]
Check this comment out and the discussion, https://github.com/reactstrap/reactstrap/issues/172#issuecomment-260214633. We'll need to add it to the docs.

**Comment by Vadorequest** [comment]
Using a ref to autofocus looks so dirty. Also, it doesn't work well with functional components.

**Comment by TheSharpieOne** [comment]
All of the properties/attributes you pass will be passed to the underlying input, including autofocus. Ref is special, so there needed to be a way to pass that down. It doesn't pertain to you for your use case, you can just use autofocus.
