### ISSUE TITLE
Add docs for Button checkboxes and radios

### ISSUE THREAD

**Issue by bestpika** [reactstrap/reactstrap#273]
### Issue description

- version `#3.9.5`
- components: `ButtonGroup`, `Label`, `Input`

### Steps to reproduce issue

How do I create something like: https://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons

**Comment by TheSharpieOne** [comment]
Those are just states, you can control the states in your component. I had asked the same thing in slack and came to the conclusion that state management is outside of the scope of this project and is left in developer land. You can create reusable components which manage state to use in your project or even create a project using reactstrap and publish it for others (similar to the validation library I made which is linked in the readme)

**Comment by eddywashere** [comment]
Not sure specifically what you're looking to get answered. As far as form state, +1 to @TheSharpieOne's comment. It's important to work with forms or controlled inputs/Inputs as you would without reactstrap. As far as markup, the core components are available to help build this. I don't consider that hidden input something that should be a reactstrap component. It's best kept simple as a normal input.

Here's what documentation could look like for checkbox buttons:

```jsx
<ButtonGroup>
  <Button tag="label" active={this.state.val1 === true} onClick={this.toggleVal(1)}>
    <input type="checkbox" checked={this.state.val1 === true} autocomplete="off" /> Checkbox 1 (pre-checked)
  </Button>
  <Button tag="label" active={this.state.val2 === true} onClick={this.toggleVal(2)}>
    <input type="checkbox" checked={this.state.val2 === true} autocomplete="off" /> Checkbox 2
  </Button>
  <Button tag="label" active={this.state.val3 === true} onClick={this.toggleVal(3)}>
    <input type="checkbox" checked={this.state.val3 === true} autocomplete="off" /> Checkbox 3
  </Button>
</ButtonGroup>
```

I'll rename this issue to reflect the lack of missing docs for this.

**Comment by wzup** [comment]
@eddywashere 
@TheSharpieOne 

Your button group. Created as you suggest

![button-group](https://user-images.githubusercontent.com/3880497/36030764-1c41f360-0db1-11e8-8791-8d14b1d16a54.png)

**Comment by TheSharpieOne** [comment]
See the bottom of https://reactstrap.github.io/components/buttons/ (it should probably be moved to the Button Group page...)
