### ISSUE TITLE
v9.1.7 and v9.1.8 import errors

### ISSUE THREAD

**Issue by oleics** [reactstrap/reactstrap#2730]
Example Code

```typescript
import {
  Collapse,
  NavbarToggler,
  // NavbarBrand,
  Nav,
  NavItem,
  NavLink,
  NavbarText,
} from 'reactstrap'
```

9.1.7 gives

```
Module not found: Can't resolve './Container'
```

9.1.8 gives

```
import _Container from './Container';
^^^^^^
SyntaxError: Cannot use import statement outside a module
```

reverting to 9.1.6 works fine

**Comment by oleics** [comment]
Additional informations:
* nextjs v13.2.4
* typescript v4.9.5
* node v16

**Comment by saad277** [comment]
also getting this in ^9.1.4

**Comment by danielcherrington** [comment]
seeing the same issue

**Comment by lloan** [comment]
I was JUST going to post an issue about this yesterday. I'm having the same issue.

**Comment by illiteratewriter** [comment]
I've made a PR, it would be great if someone can test this [PR](https://github.com/reactstrap/reactstrap/pull/2733) using `yarn link`?

To test using `yarn link`, you can follow this [doc](https://classic.yarnpkg.com/lang/en/docs/cli/link/).

**Comment by Hasham-dev** [comment]
Any solution?

**Comment by firatkeler** [comment]
For now, you can import like this

`let Row = dynamic(
    () => import("reactstrap").then(d => d.Row), { ssr: false }
);`

**Comment by shintu0** [comment]
I have changed it to version 9.1.6 It is working in Nextjs.
Please provide if anyone has any other solution or fix.

**Comment by rojaence** [comment]
**With reactstrap v9.1.8 I tried the following:**
Change the extension from index.js to index.mjs in "node_modules/reactstrap/lib/index.js"

I think it is not the most appropriate but this solved the problem.

**Dependencies in my case:**

```json
  "dependencies": {
    "next": "^13.2.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "reactstrap": "^9.1.8"
  },
  "devDependencies": {
    "@types/node": "18.15.11",
    "@types/react": "18.0.33",
    "typescript": "5.0.3"
  }
```

**Comment by jeremyccrane** [comment]
@rojaence how does this work for deployments?
