### ISSUE TITLE
Events for Collapse component

### ISSUE THREAD

**Issue by j-francisco** [reactstrap/reactstrap#277]
It would be useful if the Collapse component could accept props like onOpened (or onShown), onClosed (or onHidden), etc. An example of needing this is I'm building a feature in my app where when a Collapse component is opened, I want to scroll the header of the Collapse to the top of the screen. This causes some trouble because I need to perform the scroll after the Collapse has finished opening, otherwise the scroll position would be off.

I took a crack at implementing an onOpened prop [here](https://github.com/j-francisco/reactstrap/tree/collapse-on-opened-callback) but because I don't know if you guys have greater plans for how to handle events across the library, I figured it's not worth working on a PR right now.

**Comment by eddywashere** [comment]
We haven't really had to expose lifecycle events but Collapse is a unique component that could really use this. I'd expect props to be name `on${Event}` for the different transition states. Could you rebase the pr for v4 from master?

**Comment by j-francisco** [comment]
I'll try to get to it soon. Should there be 4 new props: onShow, onShown, onHide, onHidden?

**Comment by eddywashere** [comment]
@j-francisco ah good point, I should have said only `onOpened` and `onClosed`, since they are the only events not currently exposed. `onOpen` and `onClose` are the basic state transition events that can be checked in toggle method. If you find the latter critical to expose, feel free to do it. Thanks for your patience and help!

**Comment by j-francisco** [comment]
@eddywashere should the onOpened and onClosed events be triggered only on updates, or should they also be triggered on the initial render based on the isOpen prop? I'm leaning towards only on updates, since the main reason for these events is because of the delay, which only happens on updates.

**Comment by eddywashere** [comment]
@j-francisco haven't published this just yet but will update this thread when it gets published.

**Comment by iamkratos** [comment]
Was this added? Any chance we could props like this to the Modal component?

**Comment by j-francisco** [comment]
This was added to the Collapse component. The props have since been renamed to `onEntered` and `onExited`.  I believe Modal has `onOpened` and `onClosed`.
