### ISSUE TITLE
Dropdown not working witn Reactstrap v8 and Bootstrap v4

### ISSUE THREAD

**Issue by acoroza-capital** [reactstrap/reactstrap#2790]
### What is happening?
- I followed the documentation here https://deploy-preview-2356--reactstrap.netlify.app/components/dropdowns/
and i cannot make it to work. I need to work on v8 because I am working on an old project and upgrading to v9 is not in our choices as it will be time consuming and will affect lots of features in the project
- The problem is the menu is not appearing, theres no error in the console or whatever

### What should be happening?
Should work just like in the documentation

### Error message in console
None

### Code
Example code is here
https://stackblitz.com/edit/react-16-test-c7uiil?file=index.js

**Comment by illiteratewriter** [comment]
You've to use `this.setState` to set the state. `this.setState({ dropdownIsOpen: !this.state.dropdownIsOpen})` inside the `toggle` function. React does not rerender if [setState](this.setState({ dropdownIsOpen: !this.state.dropdownIsOpen})) is not used.

Change toggle function to this:
```
toggle() {
    this.setState({ dropdownIsOpen: !this.state.dropdownIsOpen });
    console.log(this.state);
 }
  ```
