### ISSUE TITLE
It won't accept floating numbers when I add the minimum and maximum number limits.

### ISSUE THREAD

**Issue by keyurDevani5061** [reactstrap/reactstrap#2793]
- components: `Input`
- reactstrap version `9.2.1`
- react version `18.2.0`
- bootstrap version `5.3.1`

### What is happening?

It won't accept floating numbers when I add the minimum and maximum number limits.

### What should be happening?

When I add the minimum and maximum number restrictions, it need to accept floating values as floating numbers are crucial for any tax field or GST tax.

### Code

<InputGroup>

      <InputGroupText>@</InputGroupText>
      <Input type="number" min={"0"} max={"100"} name="tax" placeholder="username" />
    </InputGroup>

![clipboard-image (18)](https://github.com/reactstrap/reactstrap/assets/119301800/6d85fe32-7c79-4355-8e86-98c90daf2546)
![clipboard-image (17)](https://github.com/reactstrap/reactstrap/assets/119301800/8870f4a8-7cfc-477d-bde4-8bbbb39dacc6)

**Comment by illiteratewriter** [comment]
> One issue with number inputs is that their step size is 1 by default. If you try to enter a number with a decimal (such as "1.0"), it will be considered invalid. If you want to enter a value that requires decimals, you'll need to reflect this in the `step` value (e.g. step="0.01" to allow decimals to two decimal places). 

[Mdn web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#allowing_decimal_values)
