### ISSUE TITLE
How do buttons get form data outside the form and go to validation？

### ISSUE THREAD

**Issue by cangsnage** [reactstrap/reactstrap#2794]
I want to use the form component, the button outside the form to get the form data, which can be obtained through usestate, but I want to use the form component itself to get any good way

**Comment by illiteratewriter** [comment]
Kindly ask questions on StackOverflow. This question seems to be more of how to pass data in React rather than a Reactstrap question. Also while asking on StackOverflow, keep [how to ask a good question](https://stackoverflow.com/help/how-to-ask) in mind.
