### ISSUE TITLE
Unable to customise scrollbar of reactstrap table

### ISSUE THREAD

**Issue by MrFarhan** [reactstrap/reactstrap#2796]
- components: `Table`
- reactstrap version `^9.0.1`
- import method `es` 
- react version `^18.1.0`
- bootstrap version `^5.1.3`

### What is happening?

Unable to customise reactstrap table bottom scrollbar

### What should be happening?

Should allow to customise scrollbar

### Steps to reproduce issue

Create table and make the screen width shorter

### Error message in console
Nothing

### Code

```
          <Table
            bordered
            hover
            style={{
              overflowY: "auto",
              scrollbarColor: "#888 #f1f1f1 !important",
            }}
            {...getTableProps()}
            className="table"
          > 
          // thead and body etc here
       </Table>
```

also tried below code on global scss:

```
::-webkit-scrollbar {
  width: 10px; /* Width of the scrollbar */
}

::-webkit-scrollbar-track {
  background: red; /* Color of the track */
}

::-webkit-scrollbar-thumb {
  background: red; /* Color of the thumb */
  border-radius: 5px; /* Rounded corners for the thumb */
}
```

**Comment by illiteratewriter** [comment]
Creating a responsive table and adding styles to the class `.table-responsive` will add colour to scrollbars.
