### ISSUE TITLE
Collapse within Navbar doesn't have height when isOpen=false

### ISSUE THREAD

**Issue by corydeppen** [reactstrap/reactstrap#280]
Based on the [NavbarToggler example](http://reactstrap.github.io/components/navbar/), I've noticed a few issues when using Collapse inside Navbar:

- The `div` rendered by Collapse adds a style with `height: 0` when the `isOpen` prop is false. The navbar is rendered appropriately without the height specified.
- Collapse has a `navbar-toggleable-md` class, but the Bootstrap example shows it should have a `navbar-collapse` class when used in a navbar. The content is hidden using the NavbarToggler example, but changing the class to `navbar-collapse` displays the content as expected.
- The button rendered by NavbarToggler is empty and appears to need a child element (e.g. `<span class="navbar-toggler-icon"></span>`). Would you consider adding this `span` as a default if a child isn't specified?

I'm using version `#4.0.0-alpha.8`.

**Comment by eddywashere** [comment]
@corydeppen thanks for reporting, this was fixed in #284 and shipped in `4.0.0`. Let me know what you think about the changes.
