### ISSUE TITLE
Fade: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by RichardLindhout** [reactstrap/reactstrap#2801]
chunk-FUOFC43Q.js?v=2a0f9713:521 Warning: Fade: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at Fade (

**Comment by adventofryz** [comment]
This is not just happening for Fade. It is happening for multiple other components as well. 

![image](https://github.com/reactstrap/reactstrap/assets/22504701/59d27cef-0ce3-4c6a-bcd0-b976557301a8)

![image](https://github.com/reactstrap/reactstrap/assets/22504701/5b8ac917-1dda-49cc-bb25-e157a31cf2b7)

Please provide a patch for the affected components due to default props being deprecated.

**Comment by batu-han3428** [comment]
Is it resolved?

**Comment by islam-kamel** [comment]
I'll solve that problem.

**Comment by turi4200** [comment]
also on Popover using UncontrolledPopover

**Comment by SabihYallaMotor** [comment]
I'm facing same issue on popover component? any update?

**Comment by sbaechler** [comment]
@illiteratewriter I opened a merge request that resolves this issue for all affected components.

**Comment by vladdg-dev** [comment]
Is this going to be fixed soon?

**Comment by luis-redatlas** [comment]
![image](https://github.com/user-attachments/assets/a9cb0466-b2a7-4192-9a42-1cac13b28787)

I have the same issue, but this time using the `UncontrolledTooltip` component.

What do you think I should do in the meantime?

**Comment by vladdg-dev** [comment]
> ![image](https://private-user-images.githubusercontent.com/109181894/352708571-a9cb0466-b2a7-4192-9a42-1cac13b28787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjc0MDcsIm5iZiI6MTcyMjA2NzEwNywicGF0aCI6Ii8xMDkxODE4OTQvMzUyNzA4NTcxLWE5Y2IwNDY2LWIyYTctNDE5Mi05YTQyLTFjYWMxM2IyODc4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwNzU4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmI3YjUxMTk2ZTM0MGQ4NTBmNjA0NjIyOTZhNzNhZTM3MzMyYWI0MzIzYzdjYTQ2NWFiODA1ZGNlYzBiODQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oP3qWGyQAH101BMxjm17klIGNRBVEizAdIEHNb1gfpg)
> 
> I have the same issue, but this time using the `UncontrolledTooltip` component.
> 
> What do you think I should do in the meantime?

Unless you contribute to the project, the best thing to do is to keep a close eye on #2801 and update you package when it's merged.

**Comment by filip-be** [comment]
I've took a look at your PR @islam-kamel @sbaechler and both of them are still using `propTypes` for functions - which will be silently ignored in React 19 - see the [Removed: propTypes and defaultProps for functions](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-deprecated-react-apis).

I've took a look at the code to asses how difficult it would be to migrate them to TypeScript components, but this looks like a major change and it would be the best just to rewrite all components to TS (unless I'm missing something) :(

Anyway this PR seems to be ready and will make the reactstrap components still work with React 19, no matter the propType checks - #2812

**Comment by sbaechler** [comment]
To be honest, the last time I worked on a codebase that used propTypes was 7 years ago. I think it would be a good time to move everything to Typescript. The propTypes and defaultProps are somehow dependent on each other, which made removing them more difficult than necessary.

I think with a Typescript codebase we should be able to get rid of the `addDefaultProps` utility function which is O(n).

It looks like there is a [Codemod](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-deprecated-react-apis) for migrating propTypes to Typescript.

It might also be worthwile to give [Cursor](https://www.cursor.com/) a try to migrate the whole codebase to Typescript.

**Comment by jack-hermanson** [comment]
In the meantime, is it possible to at least suppress this "warning" (which is actually printed as an error) so it doesn't clog up the console? That could work as a band-aid to the immediate issue and allow time to come up with a longer-term solution.

**Comment by sbaechler** [comment]
@filip-be 

Maybe a simpler approach would be to just revert the function components back to class components.

**Comment by pavlos256** [comment]
What is needed to move this forward? I see there are two open PRs, with one built on the other, but the necessary next steps are unclear from the comments.

**Comment by vladdg-dev** [comment]
Guys, this needs to be fixed. Can somebody do it already?

**Comment by emorling** [comment]
+1

**Comment by ChortJulio** [comment]
Keeps happening :/

**Comment by KingGym** [comment]
Please fix, thanks

**Comment by sbaechler** [comment]
@illiteratewriter https://github.com/reactstrap/reactstrap/pull/2806 fixed the console error for the Fade component. While only the Fade component was mentioned in this issue, the Tooltip and Popover component are function components that use default props as well so the console error still shows.

**Comment by vinayv-456** [comment]
@illiteratewriter   @islam-kamel  there are still some components using default props of Fade leading to undefined warnings if the prop is required. but it is removed and default parameters are used within the fade component.

**Comment by alamothe** [comment]
This is not fixed for Popover!
