### ISSUE TITLE
Col with offset always left justified.

### ISSUE THREAD

**Issue by TimMeade** [reactstrap/reactstrap#292]
Not sure if I'm just crazy. Long time user of bootstrap, and I've been loving this version of it until I tried the offset for the Col component.    It does not seem to be working.    The component seems to stay left justified.  I've been pouring over the CSS and everything else and no idea why.

            <Container>
              <Row>
                <Col md={{ size: 5, offset: 3 }} lg={{ size: 7, offset: 2 }}  xl={{ size: 8, offset: 1 }}>
                  {React.Children.toArray(this.props.children)}
                </Col>
              </Row>
            </Container>

Note: the container and the row are both full width.  It's just the column is like float:left, but there is no float.

No matter which size.   Always left justified.   Am I missing something?

**Comment by TheSharpieOne** [comment]
Works fine for me. I am using the latest release of both reactstrap (v4.0.1) and bootstrap (v4.0.0-alpha.6)
Can you confirm the version numbers you are using?

![image](https://cloud.githubusercontent.com/assets/664714/21869909/c95eda06-d827-11e6-942e-c0d068a1fc71.png)

**Comment by TimMeade** [comment]
OK Thanks for checking.  Completely on my end.  I had done a hard git reset during testing and still had a bootstrap 3 css file.   the 4 alpha 6 file makes it work fine.  Closing as not an issue.
