### ISSUE TITLE
DropdownMenu without Button?

### ISSUE THREAD

**Issue by ucarion** [reactstrap/reactstrap#293]
I'd like to add a dropdown menu to an existing element, but I don't want that element to be styled like a button. Is there a way to use DropdownMenu without a surrounding Dropdown, or to have a Dropdown whose DropdownToggle isn't a button, but rather an element of my choosing?

**Comment by eddywashere** [comment]
Not documented but if you look at the src code for DropdownToggle it's really a convenience component that uses context to call the toggle onClick from Dropdown. To replace, you need to provide your own element and add the toggle to your onClick prop. [CODEPEN DEMO](http://codepen.io/eddywashere/pen/JEKdyW)

```jsx
<Dropdown isOpen={this.state.dropdownOpen} toggle={this.toggle}>
  <YourElement onClick={this.toggle} data-toggle="dropdown">
    Your Content
  </YourElement>
  <DropdownMenu>
    <DropdownItem header>Header</DropdownItem>
    <DropdownItem>Action</DropdownItem>
  </DropdownMenu>
</Dropdown>
```

Note: when tether prop is passed to Dropdown (for auto switching to drop up or down depending on available space), it expects 1 element to have the `data-toggle` attribute set to dropdown: tl;dr add `data-toggle="dropdown"` and `onClick={this.toggle}`.

Feel free to add a pr that documents this in a `Custom Dropdown Toggle` section.

**Comment by eddywashere** [comment]
To follow up, I missed the part about doing this without a wrapping `Dropdown`, I don't think that's possible as context is required for DropdownMenu and that comes from Dropdown.

**Comment by eddywashere** [comment]
I take that back. Because of tether support it is possible, you could set the tether prop to an object that contains "target", which is a dom element, id or function that returns a dom element. You would have to set the onClick behavior on your element of choice. It would be very similar to the way tooltips work. Added docs to cover the simple example.

**Comment by ucarion** [comment]
Wow, thanks for the help! This library is great. ❤️

**Comment by eddywashere** [comment]
You're welcome! Relevant line where tether prop is destructured right after default target: https://github.com/reactstrap/reactstrap/blob/master/src/Dropdown.js#L105

Closing this out, reopen if that doesn't work out.

**Comment by mackbrowne** [comment]
@eddywashere , Not sure if this is still working.  I tried updating your codepen with the version of reactstrap I am using, instantly started getting errors.

[See here](https://codepen.io/mackbrowne/pen/PQjNZg)

I followed your directions and tried to reverse-engineer the codepen you provided, the only difference I can find is a difference in reactstrap version.  Perhaps this isn't working for 5.0.0-alpha.8 ?


As a workaround, I've been forced to include the DropdownToggle component on the page, but I'm hiding it with opacity 0 and positioning it where I want with "position: absolute".  It's hacky, but provides the functionality I want.  @eddywashere, I want to replace my hack with something nicer, any suggestions?

**Comment by TheSharpieOne** [comment]
See the "Custom Dropdown" section of https://reactstrap.github.io/components/dropdowns/ (I don't think the `onClick` and other props are needed on the `DropdownToggle`; need to test and update the docs)
You have to use `DropdownToggle`, but you can provide a `tag` with the custom component you want rendered.
```jsx
<Dropdown isOpen={this.state.dropdownOpen} toggle={this.toggle}>
  <DropdownToggle tag={YourElement}>
    Your Content
  </DropdownToggle>
  <DropdownMenu>
    <DropdownItem header>Header</DropdownItem>
    <DropdownItem>Action</DropdownItem>
  </DropdownMenu>
</Dropdown>
```

**Comment by TheSharpieOne** [comment]
Apparently void elements are the only thing that currently cannot be used there. We seem to always force children which will break void elements as you are seeing.
https://github.com/reactstrap/reactstrap/blob/24951541a110451c167ff53e6ebb367972717bc5/src/DropdownToggle.js#L68

For the other issue, I am not sure what is going on there. `Input` and `DropdownToggle` are not stateless components.

**Comment by alexandredepape** [comment]
I stumbled upon this question while researching a way to create a dropdown in react.
The thing is I have my own React element that should trigger the dropdown, is there a way to pass props to the tag ?

**Comment by TheSharpieOne** [comment]
@alexandredepape check out this example: https://stackblitz.com/edit/reactstrap-yfetbz?file=Example.js
Not sure what you `SelectablePanelPlaceHolder` looks like, but make sure you are spreading props (or at least the `onClick` prop) on the thing you want to be the clickable trigger.

```jsx
import React, { useState } from 'react';
import {
  Button,
  ButtonGroup,
  ButtonDropdown,
  DropdownToggle,
  DropdownMenu,
  DropdownItem,
} from 'reactstrap';

const CustomDropdownToggle = (props) => {
  return <Button {...props}>idk, something custom</Button>;
};

const Example = () => {
  const [isOpen, setIsOpen] = useState(false)
  return (
    <div>
      <ButtonGroup>
        <ButtonDropdown isOpen={isOpen} toggle={() => setIsOpen(!isOpen)}>
          <DropdownToggle tag={CustomDropdownToggle}></DropdownToggle>
          <DropdownMenu>
            <DropdownItem>lol</DropdownItem>
            <DropdownItem>lol</DropdownItem>
          </DropdownMenu>
        </ButtonDropdown>
      </ButtonGroup>
    </div>
  );
};

export default Example;
```
