### ISSUE TITLE
Fix Nav stacked option

### ISSUE THREAD

**Issue by Pavek** [reactstrap/reactstrap#295]
### Issue description

- version `#4.0.1`
- components: `Nav`

### Steps to reproduce issue
Just create a `<Nav stacked>...</Nav>` component => items are not stacked.

In code we see it results in `nav-stacked` class being added: https://github.com/reactstrap/reactstrap/blob/master/src/Nav.js#L41

This produces no desired affect as current BS4@alpah6 documentation suggests adding a general 'flex-column' utility class:
http://v4-alpha.getbootstrap.com/components/navs/#vertical

**Comment by eddywashere** [comment]
Thanks for reporting! For this example and for similar issues, the bool class props should be updated to support both a boolean value, for rendering the "xs" base class, and string values for rendering size classes. PR welcome!

Also, long term goal, it might make sense to remove props and old classes that have been replaced by flexbox utility classes. Worth discussing.

**Comment by Tsury** [comment]
Any workarounds in the meanwhile?

**Comment by eddywashere** [comment]
Working on some ideas to fix this. @Tsury for now, you can pass in the `flex-column` class like a normal className. `<Nav className="flex-column">`.
