### ISSUE TITLE
Media component API no longer meshes with changes in Bootstrap 4 Alpha 6.

### ISSUE THREAD

**Issue by threehams** [reactstrap/reactstrap#296]
### Issue description
Media component applies deprecated alignment classes to the .media container. The API for these classes has completely changed in alpha 6.

- version `4.0.1`
- components: `Media`

### Steps to reproduce issue
- Create a Media component with a "middle" or "bottom" prop.

Result:
The component applies `.media-middle` and `.media-bottom` props.

Expected: 
Bootstrap now expects Flex responsive utility classes on the child media component:
https://v4-alpha.getbootstrap.com/layout/media-object/

The issue is visible on the Reactstrap docs.
https://reactstrap.github.io/components/media/

I can fix this, but we'll need to decide the API since quite a bit has changed.
So much of this is now open-ended as far as spacing goes, so it may just end up being `<Media>` and `<Media body>`, with both accepting classNames for the rest of their behavior.

**Comment by eddywashere** [comment]
I would define this issue and #295 as upstream changes, that specifically switch component class modifiers with breakpoint enabled flex utility classes. The workaround should be to use the available flex classes and pass them in className prop.

Some ideas:

- remove support for these types of props, rely on flex classes without props (do less approach, encourage people to learn core flexbox features of bootstrap)
- remove support for these types of props, add support for all flex utility classes by extending a base component that has these props defined (possible performance issues)
- update support for the current named props and add breakpoint specific props that render the flex classes (abstracts core features of bootstraps switch to flebox to fix "broken" reactstrap apis)

**Comment by threehams** [comment]
At my company, we decided on approach 1: Media accepts only a `body` prop. The flex classes are getting a ton of use by us after the initial learning curve (even though I don't like how much CSS they add after prefixing).

I can submit a pull request if you're OK with this option.

**Comment by gthomas-appfolio** [comment]
Yes it's quite different, noticed when trying to jive the docs with the components.   I can PR as well, have some  prototype code

**Comment by brandonwbrown** [comment]
status on this?

**Comment by andres-moreno** [comment]
I think the right approach is to allow flex classes do the work. I just tried ` <Media className="align-self-end">` and it works like a charm!
