### ISSUE TITLE
Default behaviour of Navbar and NavbarToggler

### ISSUE THREAD

**Issue by in2progress** [reactstrap/reactstrap#302]
Hi,

The default behaviour of the Navbar and NavbarToggler as per sample https://reactstrap.github.io/components/navbar/ should mimic the default behaviour as provided by Bootstrap 4 located here https://v4-alpha.getbootstrap.com/components/navbar/#toggler

The current behaviour is always collapsed regardless of the screen size. 

I have tried varied other options to get it to behave in the same way but with no success. Could someone perhaps provide with an example? 

Thanking you for your awesome module thus far.

**Comment by Xilonz** [comment]
You can use `<Navbar toggleable>` for the default bootstrap behavior.

**Comment by in2progress** [comment]
Thank you. That works barring the alignment of the NavItem(s), but I am sure that is a minor tweak on my end. Will close this issue.

**Comment by TheSharpieOne** [comment]
Not sure how to interpret this requirement from bootstrap's docs

> Navbars require a wrapping `.navbar` with `.navbar-toggleable-*` for responsive collapsing and color scheme classes.
