### ISSUE TITLE
Add navbar dropdowns

### ISSUE THREAD

**Issue by Xilonz** [reactstrap/reactstrap#304]
Hi!

Is it possible to add navbar dropdowns like demonstrated on https://v4-alpha.getbootstrap.com/components/navbar/

Thanks! Using reactstrap with great pleasure 👍

**Comment by TheSharpieOne** [comment]
Yes, this library has dropdowns as documented here: https://reactstrap.github.io/components/dropdowns/. You can see in the documentation that there is a nav prop on DropdownToggle which is noted as "For DropdownToggle usage inside a Nav"

**Comment by virgofx** [comment]
Is there a way to use the DropdownToggle in a responsive fashion as it appears it requires the `show` prop ?

**Comment by Xilonz** [comment]
Thanks a lot! I guess I overlooked that prop.

**Comment by TheSharpieOne** [comment]
@Xilonz Yeah, to a point, it would be great if the reactstrap docs mimicked the bootstrap docs as far as examples go. It would require a bit of work though.

**Comment by Xilonz** [comment]
Hi!

I'm reopening this because I found out it's not 100% ok.

The dropdown toggle does have the nav propery, and gets the right classes, but the dropdown itself doesn't have a nav property, and is rendered as div and without the nav-item class. 

My workaround for now:
``<Dropdown
        isOpen={isOpen}
        toggle={this.toggle} tag="li" className="nav-item">``

Is it possible to add a nav attribute on Dropdown as well?

**Comment by TheSharpieOne** [comment]
Use `<NavDropdown ... >`instead of `<Dropdown ... >`

**Comment by Xilonz** [comment]
You're awesome! Thanks.
