### ISSUE TITLE
Modal should trap focus

### ISSUE THREAD

**Issue by TheSharpieOne** [reactstrap/reactstrap#310]
- version `v4.0.1`
- components: `Modal`

### Steps to reproduce issue

Open modal and hit tab. Focus should stay in the modal. You should not be able to focus on the element behind the modal/backdrop.

https://reactstrap.github.io/components/modals/
http://v4-alpha.getbootstrap.com/components/modal/

**Comment by toddgeist** [comment]
Safari on mac OS Sierra shows the problem.
With Chrome, you can't focus on anything behind the modal.  But it tabbing does take you off to the Window elements. So it isn't as bad.

**Comment by chrismay** [comment]
> With Chrome, you can't focus on anything behind the modal. 

Chrome (65 on Linux, at least) _does_ allow you to focus on elements behind the modal, but you have to tab through the URL bar first. 

On the reactstrap demo page linked above, clicking "launch modal" and then pressing tab-tab-tab-tab-tab-esc-tab will put the focus onto the first clickable element on the page, the "Reactstrap" link behind the modal. (The "esc" dismisses the URL bar autocomplete). Subsequent tabs will navigate through the component menu on the right-hand-side of the page.
