### ISSUE TITLE
Input, read value

### ISSUE THREAD

**Issue by kozakluke** [reactstrap/reactstrap#311]
- version `3.3.7`
- components: `Input`

Hello, I try read selected value from option list like this.

example code:
```

<Input ref="input" type="select">
<option>1</option>
<option>2</option>
</Input>

this.refs.input.value;
```
but value does exist..

I found works example like:

```

<Input getRef={(input) => (this.input= input)} type="select">
<option>1</option>
<option>2</option>
</Input>


this.input.value;
```
But it is ugly, and strange, so is better way to read this simple value? like in classic react..?

**Comment by TheSharpieOne** [comment]
String refs are deprecated. I would advise against using them.

https://facebook.github.io/react/docs/refs-and-the-dom.html

**Comment by eddywashere** [comment]
That's what you'll have to do when working with an uncontrolled input. Consider using controlled components - https://facebook.github.io/react/docs/forms.html#controlled-components.

**Comment by eddywashere** [comment]
@kozakluke Also, I don't think support for getRef was added until `3.8.1`, so `3.3.7` will likely not support that. Closing this out. If you're really passionate about this, look up old issues that mention `refs`, read them to catch up on discussions and feel free to leave any feedback/perspective that we might have missed.
