### ISSUE TITLE
Add Popover hover support

### ISSUE THREAD

**Issue by eddywashere** [reactstrap/reactstrap#312]
Currently the Tooltip component auto adds the event handlers to support hovering over the target to show the tooltip content. It would be nice to have this available in a similar fashion for the Popover component. It technically can be added with `toggle` and `isOpen`, and the event handlers onMouseLeave, onMouseEnter, etc. That doesn't seem practical. Noticed this when reviewing the new Uncontrolled components [here](https://github.com/reactstrap/reactstrap/pull/307#issuecomment-275879786). Keeping this open to track.

**Comment by TheSharpieOne** [comment]
Not 100% sure what you are asking here. You want a prop which will tell Popover to trigger the toggle prop function on mouse enter and leave? How will it work with the existing toggle trigger (clicking on the document which I believe is handled in the tether component), as in, will it replace it or work in combination with it somehow?

**Comment by Lobosque** [comment]
@eddywashere From the Bootstrap documentation:

```
How popover is triggered - click | hover | focus | manual. You may pass multiple triggers; separate them with a space. `manual` cannot be combined with any other trigger.
```

What if both Tooltip and Popover can receive either a string, in which case it would handle the cases above, or a function for other use cases?

**Comment by Geczy** [comment]
Any update?

**Comment by DorienMay** [comment]
Any update?

**Comment by TheSharpieOne** [comment]
#1181 will add this feature

**Comment by bpas247** [comment]
I'm guessing #1222 closes this issue?
