### ISSUE TITLE
Why is the toggle prop required on Modal?

### ISSUE THREAD

**Issue by bherila** [reactstrap/reactstrap#323]
Just wondering why the toggle prop is marked as required on the Modal component? Any objections to a PR which would make this functionality optional?

**Comment by TheSharpieOne** [comment]
It's for when the user clicks on the backdrop and/or uses the keyboard (esc) to close the modal. But yes, those things can be turned off / disabled, in which case the toggle prop should not be required.
Also if toggle is not passed, it should be the same as if the close on keyboard and close on backdrop click there false.

**Comment by bherila** [comment]
Ok thanks @TheSharpieOne , I've sent a PR.
