### ISSUE TITLE
Vertically stacked Navbar

### ISSUE THREAD

**Issue by chuan137** [reactstrap/reactstrap#324]
### Issue description

- version `#4.1.1`
- components: `Navbar`

### Steps to reproduce issue
```
  render() {
    return (
      <div>
        <Navbar color="faded" light toggleable={false}>
          <NavbarBrand href="/">reactstrap</NavbarBrand>
          <Nav navbar>
            <NavItem>
              <NavLink href="/components/">Components</NavLink>
            </NavItem>
            <NavItem>
              <NavLink href="https://github.com/reactstrap/reactstrap">Github</NavLink>
            </NavItem>
          </Nav>
        </Navbar>
      </div>
    );
  }
```

Brand and items are vertically stacked, with flex-direction = "column".

**Comment by chuan137** [comment]
I must have toggleable on to avoid vertical stacking menu items.

**Comment by eddywashere** [comment]
Thanks for mentioning the fix. There's an upstream fix that might be in the next beta, 🤞 https://github.com/twbs/bootstrap/pull/21719
