### ISSUE TITLE
Reactstrap and React-router 4.0.0-beta.6 - active <NavLink>

### ISSUE THREAD

**Issue by Y-Taras** [reactstrap/reactstrap#336]
### Issue description

- components: `Navlink`

### Steps to reproduce issue

-  I'm using Reactstrap and React-router 4.0.0-beta.6 in the educational project that is located on gitlab with custom domain - http://harazd.org/.
According to Reactstrap docs: that's the way I should use active navlink

```
  import { NavLink } from 'reactstrap'
  ... 
  <NavLink href="#" active = true >Link< /NavLink>
```
According to React-router v4 docs:

```
  import { NavLink } from 'react-router-dom'
  ...
  <NavLink to="/about" activeClassName="active">About</NavLink> 
```

So how should I do implement navlink active state and use react-router?

**Comment by eddywashere** [comment]
The simplest answer is that you can't use reactstrap navlink active prop when passing in react-router navlink. And that's fine because it's just 1 class `active` and react-router NavLink can take care of that with the activeClassName prop.

To use both, you'll need to rename one of those and use the tag prop in reactstrap NavLink.

```jsx
import { NavLink } from 'reactstrap';
import { NavLink as RRNavLink } from 'react-router-dom';

<NavLink to="/about" activeClassName="active" tag={RRNavLink}>About</NavLink> 
```

**Comment by Y-Taras** [comment]
Thanks for a quick solution (You can paste your answer here: http://stackoverflow.com/questions/42372179/reactstrap-and-react-router-4-0-0-beta-6-active-navlink). And one more thing : <NavLink activeClassName='active' tag={RRNavLink} to='/'>...</NavLink> - root path is always active for some reason..

**Comment by TheSharpieOne** [comment]
The root path is always active because '/' is in every path. I am not too fimilar with react-router-dom and it's NavLink, it looks like it has an `exact` prop which may be what you are looking for.

**Comment by Y-Taras** [comment]
Here's my router code, so I do use exact for root path.  
```
`      <BrowserRouter>
        <div className='app'>
          <Switch>
            <Route exact path='/' component={Landing} />
            <Route path='/products' component={Products} />
            <Route path='/services' component={Services} />
            <Route path='/price' component={Price} />
            <Route path='/contacts' component={Contacts} />
            <Route component={NoMatch} />
          </Switch>
        </div>
      </BrowserRouter>`
```

**Comment by Y-Taras** [comment]
@TheSharpieOne yes adding exact to root Navlink helped)

**Comment by TheSharpieOne** [comment]
Previously you were using [`<NavLink>` from react-router-dom](https://github.com/ReactTraining/react-router/blob/v4.0.0-beta.6/packages/react-router-dom/modules/NavLink.js). From that file, it looks like it creates the `Route` and the `Link` for you in one go.
react-router v4 has a ton of changes and I am not familiar with it enough to know how to use it compared to previous version so I can only offer some limited help with it.

**Comment by dhanyn10** [comment]
@Y-Taras @TheSharpieOne can you give me example code? a have try it but doesnt work so far.

**Comment by Y-Taras** [comment]
@dhanyn10 here's a link to my working example 
https://gitlab.com/ytaras/pinobeton2/blob/master/js/Navigation.js

**Comment by arthurkrupa** [comment]
@Y-Taras your link is down

**Comment by piavgh** [comment]
Hi everyone,

Is there anyway to use NavLink from reactstrap alone to style the active link?

Thanks

**Comment by JonSilver** [comment]
@Y-Taras I can confirm your solution works here too. Thanks so much - you saved me many hours of pain.

**Comment by TheSharpieOne** [comment]
@piavgh if you just want to use reactstrap's `NavLink` alone (without react-router-dom) you can use the `active` prop:
```jsx
import { NavLink } from 'reactstrap';

<NavLink to="/about" active>About</NavLink> 
```

**Comment by softmixt** [comment]
I think you can add something like : 

`  <NavLink to="/about" active={window.location.hash === '/about'}>About</NavLink> 
`

**Comment by nathfy** [comment]
This works for me:
```
<NavItem active={window.location.pathname === "/thing"}>
  <NavLink href="/thing">Things</NavLink>
</NavItem>
```

**Comment by AbProgr** [comment]
I had the `exact prop in react-router 4.3.1 route` but also needed to add `exact to reactstrap 7.0.2 NavLink` to prevent base route from being shown as active at all other child routes.

```
<NavItem>
  <NavLink to="/" activeClassName="active" exact tag={RRNavLink}>
    Home
  </NavLink>
</NavItem>
<NavItem>
  <NavLink to="/some-route" activeClassName="active" tag={RRNavLink}>
    Some Text
  </NavLink>
</NavItem>
```
