### ISSUE TITLE
Tooltip `target` requires string, but Tether takes object? 

### ISSUE THREAD

**Issue by mawburn** [reactstrap/reactstrap#337]
version: 4.1.1
components: Tooltip 

I'm not sure if this is intended functionality or not, I might be overlooking it, but I can't find anything in the issues concerning this. 

But when using the tooltip it requires a target ID **string**, however Tether can take a DOM Object, ID, etc. I can get around this by giving it a junk ID that I threw on some html in the top level component, then setting the target directly inside the tether prop using the `event.target` coming from a child component. 

eg: 

```JSX
<Tooltip
    isOpen={this.state.tooltipOpen}
    target="junkidcuzwhousesidsinreact"
    tether={{target: this.state.tooltipTarget}}
    toggle={this.toggle}
>
    I'm a tooltip.
</Tooltip>
```

This seems very hacky solution to me and it feels like target should accept the same proptypes that Tether can. 

>target: The DOM element, jQuery element, or a selector string of an element which the element will be attached to

http://tether.io/#options

**Comment by eddywashere** [comment]
Nice find! I agree that's how it should work. Unfortunately I simplified that target prop too much by coercing it into an id selector. Changing it would be a breaking api change that would affect everyone using those components (Tooltip & Popover). I would like to switch out tether for popper.js soon and would rather use that as a reason for a breaking change. I think the new prop would be `reference` but not sure just yet.

For now, I'd happily accept a pr that makes the target prop optional.

**Comment by mawburn** [comment]
You think it would be a breaking change? 

I did this and all your tests still passed. I haven't dug much deeper than this or tested it against my code yet, though. 

```JavaScript
target: PropTypes.oneOfType([
  PropTypes.object,
  PropTypes.string
]).isRequired,
```

```JavaScript
getTetherConfig() {
  const attachments = getTetherAttachments(this.props.placement);
  const target = (typeof this.props.target === 'object') ? this.props.target : `#${this.props.target}`;

  return {
    ...defaultTetherConfig,
    ...attachments,
    target,
    ...this.props.tether
  };
}
```

**Comment by eddywashere** [comment]
> however Tether can take a DOM Object, ID, etc.

`ID` in tether is a css selector that looks like `#junkidcuzwhousesidsinreact ` vs the `ID` expected in reactstrap which looks like `junkidcuzwhousesidsinreact `. To completely match the tether api for target, it would be a breaking change. Based on the code snippet, I think you're suggesting keeping strings as an id selector but allowing for dom nodes to be passed in as well. I'm totally cool with that. That would be a welcome enhancement.

**Comment by mawburn** [comment]
Yeah, basically. I started out just trying to pass the `e.target` in and it wasn't working. 

Since you're already appending the hash, to maintain backwards compatibility, you *could* test for the hash tag and append it if it doesn't exist. 

I can mess around with it this week and submit a PR.

**Comment by TheSharpieOne** [comment]
> Since you're already appending the hash, to maintain backwards compatibility, you could test for the hash tag and append it if it doesn't exist.

I think what he was going for is other selectors besides id, such as class. You could check it if starts with a `.` as well (and maybe even `[` for attribute selectors). The only thing that wouldn't be supported at that point would be element selectors.

**Comment by threehams** [comment]
@eddywashere Would you accept a pull request to switch to popper.js, or do you already have something in-progress?

**Comment by eddywashere** [comment]
@threehams nothing in progress, I'd only ask for a similar api if possible or info on why it would change. I'm not 100% sold on the react-tether or react-popper api.

**Comment by cr101** [comment]
Bootstrap 4 has now [switched to Popper](https://github.com/twbs/bootstrap/pull/22444) from Tether
