### ISSUE TITLE
Compare to React Bootstrap in README?

### ISSUE THREAD

**Issue by chillu** [reactstrap/reactstrap#34]
We're an open source CMS (silverstripe.org) which is redesigning the CMS UI in React, and we're planning to use Bootstrap to make it easy for contributors to customise. At the moment, we're planning to integrate React+Bootstrap via the https://react-bootstrap.github.io/ project. Your repo has just come on our radar, looks like you're making great progress with covering the bootstrap APIs!

Would you be able to give some insight on why you decided to start this project, rather than contributing to https://react-bootstrap.github.io/? I think a lot of potential users of your library would have the same question, so it might be worth listing notable differences in the README?

Feel free to close this issue if you think its inappropriate to make direct comparisons to other libraries (it's technically not a bug). We're just interested in your take to aid our own evaluation of these two libraries :)

/cc @sminnee @hafriedlander @clarkepaul @tractorcow

**Comment by eddywashere** [comment]
@chillu great questions. This came up before in a reddit thread. https://www.reddit.com/r/javascript/comments/4g76jj/reactstrap_react_bootstrap_4_components/d2fejq6

> Hi, I'm the author of reactstrap. I think that would have been ideal but there were a few things that prevented this. The github issue for v4 was locked https://github.com/react-bootstrap/react-bootstrap/issues/1187 and I only now see that it was recently unlocked. That was totally fair of them. But even with that, I wanted to introduce a ton of breaking changes and that's probably not a great thing for that project. With reactstrap I was heavily influenced by the simplicity of mui-css react components and really wanted a better way to write tooltips and bootstrap markup in general. If you look at the examples markup it aims for brevity and composition. Also, like /u/joshmanders mentioned, I wanted to use bootstrap 4 sooner rather than later.

I think it's worth noting differences. I think it's partially preference and feature set. I'll keep this open to track this.

**Comment by chillu** [comment]
Great, thanks for the quick response!

**Comment by eddywashere** [comment]
Update: this was asked again and I just want to add some additional feedback. 

> Feel free to close this issue if you think its inappropriate to make direct comparisons to other libraries

I made a suggestion that it was worth noting the differences but I won't be adding that. On second thought that seems weird. I will add some follow up thoughts from #58 to help others that are looking for something like that.

> I think users should do their own due diligence when deciding on a library. I think the docs, the source code and the project goals in the readme should help with that. Consider trying a simple example with both projects. Then see if it's worth doing a more involved example.

There's a ton of great work in both projects and many others that inspired this project. Definitely take time to evaluate them and see what works and what is important to you.

**Comment by sorahn** [comment]
Now that react 4 is out, and react-bootstrap is going to start a heavy migration to support v4, is it worth trying to merge these projects together so we don't have 2 react + bootstrap v4 libraries?  It really seems like the combined time of everyone involved would be better off tackling 1 library together and solving the issues faster, rather than having both libraries solving all the same problems twice.

**Comment by virgofx** [comment]
This is the definitive library. It works with bootstrap 4 and is well maintained. Please don't comment on old issues that are already closed.

**Comment by xaviershay** [comment]
> This is the definitive library. It works with bootstrap 4 and is well maintained. 

This is not obvious to new players (and hence how I ended up here also.)

>  I think users should do their own due diligence when deciding on a library. I think the docs, the source code and the project goals in the readme should help with that.

I'm new to react, but not new to web development or bootstrap. I simply don't know enough about react or the ecosystem to be able to do my own diligence in a reasonable amount of time. For example, the "About the Project" section of the README doesn't mean anything unless you're already familiar with the ecosystem.

So I'm just going to pick one and see how it goes, all the while feeling vaguely uncomfortable that I'm doing the wrong thing, which adds to my already long list of things I'm uncomfortable about learning a new ecosystem. That's fine for me, I'll work through it, but please do consider adding some words that would help ease the learning burden for new users.
