### ISSUE TITLE
Ability to disable the call to toggle in DropdownItem

### ISSUE THREAD

**Issue by kennyjwilli** [reactstrap/reactstrap#340]
- version `#4.2.0`
- components: `Dropdown`, `DropdownItem`

Right now `DropdownItem` assumes that any time you click it you want the[ `toggle` function to be called](https://github.com/reactstrap/reactstrap/blob/master/src/DropdownItem.js#L42). This is not always true. It'd be great if there was a way to prevent the call to toggle from a property on `DropdownItem`. Another possibility is to use the return value of the onClick function to determine if toggle should be called.

My use case is I have a dropdown where the user can select multiple things from the dropdown. I only want to close the dropdown when the user clicks outside of the dropdown.

**Comment by CoderJoeIO** [comment]
I have this exact same use case, and I second that it would be really great to have a property on DropdownItem to control the toggle, with the default being true, but allowing for toggle={false} if you want to keep the menu open when an item is clicked. Do you think that would be the right approach?

**Comment by CoderJoeIO** [comment]
I'm not sure if the team wants this functionality, so I'm waiting to see how they respond. So for now I've done the following until I hear back:

DropdownItem:
- added 'toggle' PropType.bool which defaults to true
- in onClick I check if true before firing toggle
- changed passing ...props to the Tag and instead pass children and onClick selectively

I'd like some feedback on this approach.

**Comment by kennyjwilli** [comment]
This solution would solve my use case.

**Comment by CoderJoeIO** [comment]
hmm one thing is that once props passing is removed you can't pass anything extra down to the button tag.  So I'm not sure if just deleting the toggle prop from the props you spread to Tag.

**Comment by CoderJoeIO** [comment]
#346 PR for this issue, adding the toggle switch while not passing it down to the Tag as props

**Comment by eddywashere** [comment]
Catching up, thanks for your patience. Will review this asap.

**Comment by CoderJoeIO** [comment]
Great thanks, much appreciated

**Comment by jebarjonet** [comment]
@eddywashere Do you have some news about this?

**Comment by jebarjonet** [comment]
Could close this issue because of https://github.com/reactstrap/reactstrap/pull/346

**Comment by TheSharpieOne** [comment]
This was fixed in version 4.4.0. Add the prop `toggle={false}` to your `DropdownItem`s
Here is an example showing a mix of items which with and without `toggle={false}` as well as with the standard `Dropdown` and `UncontrolledDropdown`.
