### ISSUE TITLE
Navbar (.fixed-top) overshadows Modal

### ISSUE THREAD

**Issue by alihammad-gist** [reactstrap/reactstrap#342]
### Issue description
Navbar with `.fixed-top` className overshadows `Modal`. `Modal` has the default zIndex set to `1000` while `Navbar.fixed-top` has zIndex set to `1030`. The problem can be fixed by setting `Modal` zIndex property to greater than 1030.
- version `#4.2.0`
- components: `Modal`

### Steps to reproduce issue
http://codepen.io/alihammad-gist/pen/MpwBeY
- ...

**Comment by TheSharpieOne** [comment]
Looks like bootstrap uses z-index of 1050. This was an oversight on my part

**Comment by treygithub** [comment]
still having the same problem, if I set fix-top on the navbar, the drop-down modal is invisible. The links show just not the modal background. If i donot use the fixed top then it works fine but then my nav bar will not stay at the top. i checked the modal zIndex and it was set to 1050, tryed changing it and nothing working

**Comment by TheSharpieOne** [comment]
can you reproduce this using https://stackblitz.com/edit/reactstrap?file=Example.js

**Comment by treygithub** [comment]
https://reactstrap.stackblitz.io    link to my files....
