### ISSUE TITLE
Theme install

### ISSUE THREAD

**Issue by uncledent** [reactstrap/reactstrap#345]
Hello, will it work with custom theme installed? For example with http://themes.getbootstrap.com/products/application?

Thank you in advance!

**Comment by TheSharpieOne** [comment]
Yes and no. The theme extends bootstrap to add additional components which reactstrap doesn't support (sine they are not part of bootstrap). You can use reactstrap for all of the common  components as well as for the base of the extended components. For example "card profile" is just a card with an extra class, you can use reactstrap's Card component with className to add the extra class.

**Comment by uncledent** [comment]
@TheSharpieOne  Thank you for a quick reply!
