### ISSUE TITLE
Modal props doesn't work

### ISSUE THREAD

**Issue by dhwrwmgwra** [reactstrap/reactstrap#347]
```wrapClassName: PropTypes.string,
  modalClassName: PropTypes.string,
  backdropClassName: PropTypes.string,
  contentClassName: PropTypes.string,```

These props doesn't work on Modal.

**Comment by harshita-sahusoft** [comment]
I am facing the same issue... Please fix this ASAP

**Comment by TheSharpieOne** [comment]
Those were added just a few weeks ago. Can you confirm the version you are using?

**Comment by TheSharpieOne** [comment]
It's working fine for me using the latest version of reactstrap: http://www.webpackbin.com/N1JBhKfcG

![image](https://cloud.githubusercontent.com/assets/664714/23560116/4ef55c42-0007-11e7-88bd-07a4d5f9350f.png)

**Comment by dhwrwmgwra** [comment]
@TheSharpieOne "reactstrap": "4.0.0-alpha.1",
