### ISSUE TITLE
popover appears outside of window

### ISSUE THREAD

**Issue by th3fallen** [reactstrap/reactstrap#348]
### Issue description

- version `4.2.0`
- components: `popover`

### Steps to reproduce issue
open example page for popovers with chromes device emulator and set the size to ipad pro or below then click the "top" button example
- ...

**Comment by TheSharpieOne** [comment]
This is what I see:
![image](https://cloud.githubusercontent.com/assets/664714/23558750/b3c86a06-0002-11e7-860b-248151f7a839.png)

This is the same for bootstrap's docs (the same as in the text can be cut off by the viewport).

**Comment by eddywashere** [comment]
@th3fallen checkout the tether docs, specifically the constraints section, for adjusting this behavior: http://tether.io/#constraints

I did sneak this in for the Dropdown component when tether is enabled, https://github.com/reactstrap/reactstrap/blob/master/src/Dropdown.js#L39-L42

I'd be interested in a pr that adds it to popover if it handled the scenario in the above image from @TheSharpieOne, flipping top or bottom would still produce a cropped popover, ideally it would move to the right if there wasn't enough space.

Going to close this out, thanks!

**Comment by stefan-schweiger** [comment]
@eddywashere any idea how to fix the arrow position when using constraints?

![capture](https://user-images.githubusercontent.com/3532342/28117941-93c2f1c6-670f-11e7-91f7-284d624fb660.PNG)

Codepen: https://codepen.io/anon/pen/qjLMxW

With react-bootstrap the positioning works, but I haven't really figured out how they do it.

**Comment by ozhe** [comment]
@stefan-schweiger I encountered the same issue. Do you find any fix?

**Comment by TheSharpieOne** [comment]
Looks like bootstrap 4 beta 1 has fixed the issue. The generated markup is different so reactstrap will need to make a change in order to support bootstrap 4 beta 1

**Comment by jdpagley** [comment]
Did anyone ever make a fix for this? It seems inconclusive. I'm dealing with this same problem still using reactstrap version 5.0.0-beta.

**Comment by TheSharpieOne** [comment]
It looks to be fixed in the latest reactstrap release. It should be in the beta as well. Reactstrap as well as bootstrap switched to Popper.js which handles the arrow and position better than tether did.
Here is what I see in the latest docs:
![](https://i.imgur.com/APu6oZN.jpg)

**Comment by QuantumInformation** [comment]
Is there a way to get the popup to not reposition, even if it is outside the window? 

Ie, I want it to position "right" and don't want it to over move.

**Comment by TheSharpieOne** [comment]
You can use the modifiers to pass options directly to popper.js

https://stackblitz.com/edit/reactstrap-v6-aqb1kn?file=Example.js

```jsx
import React, { Component } from 'react';
import { Popover, PopoverHeader, PopoverBody, Button } from 'reactstrap';

const modifiers = {
  preventOverflow: {
    enabled: false,
  },
  flip: {
    enabled: false,
  },
};

class Example extends Component {
  state = {};
  toggle = () => {
    this.setState(({isOpen}) => ({isOpen: !isOpen}));
  };
  render() {
    return (
      <div>
        <Button id="button" onClick={this.toggle}>Click me</Button>
        <Popover target="button" placement="bottom" modifiers={modifiers} isOpen={this.state.isOpen} toggle={this.toggle}>
          <PopoverHeader>Popover Title</PopoverHeader>
          <PopoverBody>Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</PopoverBody>
        </Popover>
      </div>
    )
  }
}

export default Example;
```

**Comment by QuantumInformation** [comment]
Perfect thanks!!! ))

**Comment by TheSharpieOne** [comment]
you are creating a `div` and rendering to that `div`, but you need to append that div to the document body (that is where reactstrap is looking for it).

In the near future that error will just be a warning and it just not render the popover/tooltip.

**Comment by QuantumInformation** [comment]
@TheSharpieOne but isn't react supposed to take care of that, I mean it work like that in the real app?

**Comment by TheSharpieOne** [comment]
when using `document.createElement('div')` in the browser and within JSDOM, it's just created an element and not attaching it to the body. It has nothing to do with react at that point. React can mount to _any_ element, within the body or not. reactstrap is specifically looking for the target to be within the body when the target is a string.

Anytime reactstrap creates a new element programitcally, we also add it to the body as the browser only renders/draws the body:
https://github.com/reactstrap/reactstrap/blob/35b4dd7c132dc1c636f537d8f14d0a4bb29ec9e9/src/Portal.js#L25-L26
