### ISSUE TITLE
It seems component inside modal will not update anymore

### ISSUE THREAD

**Issue by zzswang** [reactstrap/reactstrap#35]
Following code, {this.props.field.name} will not change after state change, unless we change {isOpen}
The children components' updating are blocked.

Not sure why, any ideas?

```
      <Modal isOpen toggle={closeModal}>
        <ModalHeader toggle={closeModal}>{this.props.field.name}</ModalHeader>
        <ModalBody>
            ...
        </ModalBody>
      </Modal>
```

**Comment by eddywashere** [comment]
Thanks for reporting the issue. This is due to the way I'm handling updates in componentDidUpdate within Modal.jsx. I'm working on a fix 👍

**Comment by eddywashere** [comment]
@zzswang fixed in 1.3.4. See [codepen example](http://codepen.io/eddywashere/pen/0f4e34da6e0c67b277ae3144943aeedb?editors=0010)

**Comment by zzswang** [comment]
Cool, thanks, it's working fine now.

**Comment by arpitprod** [comment]
I'm facing same issue

I'm using these versions - 
```
react - 16.2.0,
reactstrap - 5.0.0-alpha.4,
bootstrap - 4.0.0-beta.2
```

**full details**

I'm using a component in modal and changing dynamic content with state and props but Modal is not updating dynamic until we don't close Modal and open again with isOpen props
