### ISSUE TITLE
isOpen naming convention is inconsistent with other boolean props.

### ISSUE THREAD

**Issue by threehams** [reactstrap/reactstrap#350]
### Issue description
The props naming convention of `isOpen` appears to be inconsistent with other boolean props - all other props in all components avoid the `is` prefix. Examples:
`<Button block>`
`<Card inverse>`

We're seeing this in an internal project when using Reactstrap as a base - there's a lot of confusion about whether to prefix `is` for existing props or not.

Is this something which makes sense to change, or is it a more specific convention than just the typical "boolean vs. other props" use of "is"?

**Comment by eddywashere** [comment]
It was a convention the react docs used. I'm not sure it's worth the breaking change for consistency and I think it's important to have some distinction for this prop that controls visibility vs a modifier prop that changes how something looks.

**Comment by threehams** [comment]
Fine by me - it'd be a painful deprecation, and it's simple enough for us to map to the different name.
