### ISSUE TITLE
When placing form on Modal, clicking on label does does not focus the associated input

### ISSUE THREAD

**Issue by ablbol** [reactstrap/reactstrap#351]
### Issue description

- version `^4.2.0`
- components: `Modal`

### Steps to reproduce issue
I have placed a form inside the body of the Modal component, here is a simple example

```
<form ....>
  <div className='form-group'>
    <label className="form-control-label" htmlFor='myComponent'>label</label>
    <input name='myComponent' id='myComponent' type='text' className='form-control' />
  </div>
</form>
```
When I click on the label, the input field does not get focused.  I checked Bootstrap similar behavior and it works.  But focus does not work in reactstrap.

Please let me know if I am missing something.
Thanks

**Comment by TheSharpieOne** [comment]
Here is a working example using the latest reactstrap. Everything seems to be working as it should: https://www.webpackbin.com/bins/-KedQ07IP8fS6hjMOjDk

**Comment by ablbol** [comment]
Thanks

**Comment by TheSharpieOne** [comment]
Closing this as the issue as it seems to be resolved and is not active.
