### ISSUE TITLE
Make Row component with custom element type

### ISSUE THREAD

**Issue by rikobo** [reactstrap/reactstrap#353]
Wondering if it is possible to make the `Row` component with possibility to use a custom element type, something like in react-bootstrap:

https://react-bootstrap.github.io/components.html#grid-props-row 

cheers.

**Comment by TheSharpieOne** [comment]
Use the `tag` prop `<Row tag="div">`. You can also pass in other components, not just strings.

**Comment by rikobo** [comment]
Very nice, thank you.
