### ISSUE TITLE
Modal: Tabindex ? - also for WCAG reasons - is it possible to stay in the modal (tabwise)

### ISSUE THREAD

**Issue by Alphavader** [reactstrap/reactstrap#354]
### Issue description

- version `#4.0.0`
- components: `modals`

Hi, 
when i open an modal - the focus lays on the close button.
Is it possible to change the tab-focus on the button first ?
I tried that with TabIndex - but it doesnt work for me.
Is it possible via keyboard prop? What does this anyway - you did not specify this in your docs.

Also is it possible (for WCAG-reasons) - that the Tabindex stays in the modal ? 
Like when i press tab - tab again - the focus only switches between the close button and 
the button in the footer.

Thanks

**Comment by TheSharpieOne** [comment]
When the modal opens, [focus is given to the dialog](https://github.com/reactstrap/reactstrap/blob/master/src/Modal.js#L160-L165), not a button. This means the next time tab is hit, it will focus the on the first focusable element within the modal. The first focusable element may be the top close button if you use `ModalHeader` with the `toggle` prop.
For the second issue see #310

**Comment by Alphavader** [comment]
hmm,  screenreader says its focused on the close button.
But thanks for your answer - do you have a solution for the tabbing in the modal
without leaving it ?

**Comment by TheSharpieOne** [comment]
https://github.com/davidtheclark/focus-trap-react is a very nice solution. It is basically made with modal in mind. I wonder if it would be alright to bring it in as a dependency to address this issue on the library level instead of having individual dev/users having to implement it in their projects.

**Comment by Alphavader** [comment]
Thanks man - i will look into it and maybe open a merge request for you ;)

**Comment by Alphavader** [comment]
Focus-trap-react works very well!

**Comment by TheSharpieOne** [comment]
Modal has an `autoFocus` prop which can be set to `false` to disable it from automatically focusing on the modal. This allow you to use `autoFocus` on things like buttons and inputs (any focusable item) within the modal to automatically focus them when opened.

Closing this is favor of #310. Use that ticket to track the effort of modal trap focus.
