### ISSUE TITLE
Ability to have Fade animation on tooltips and popover

### ISSUE THREAD

**Issue by JohanBengtsson** [reactstrap/reactstrap#363]
It would be great to have the ability to add a fade animation to Reactstrap Tooltip and Popover, similar to bootstrap tooltip option `animation`

![image](https://cloud.githubusercontent.com/assets/3408400/23955758/2bac69c2-099b-11e7-9d39-fae6117351ae.png)

Are there any plans of introducing this? Thanks!

**Comment by KamiGim** [comment]
I'm also waiting 
Thanks

**Comment by Geczy** [comment]
Yes!

**Comment by TheSharpieOne** [comment]
@amikhalev might you be able to help with this on the v5 branch? From the looks of it, tooltips and popovers should always render the PopperContent and the PopperContent can use  the `Fade` around the [`ReactPopper`](https://github.com/reactstrap/reactstrap/blob/9b80d11447320ef4cb64d2aa97b2cc95672b686e/src/PopperContent.js#L159-L162) similar to this example: https://github.com/souporserious/react-popper/blob/ef520ee1213f30d3af3f10c6f5b4a04a888deb73/example/index.jsx#L170-L188
what do you think?

**Comment by amikhalev** [comment]
Yeah, I think I could do that. Might take me a few days to get to it though

**Comment by Geczy** [comment]
Any update? @TheSharpieOne @amikhalev

**Comment by DorienMay** [comment]
I would love to have this feature too.
