### ISSUE TITLE
DropdownItem - submit form problem

### ISSUE THREAD

**Issue by cervotoc** [reactstrap/reactstrap#366]
### Issue description

- version `#4.1.1`
- components: `DropdownItem`

### Steps to reproduce issue

- DropdownItem is rendering as button and then  is inside form after select is form submitting
- Should be default props `type` as `button`, not empty

**Comment by mikeatlas** [comment]
Actually, default behavior for HTML5 for `type` should be `submit`, not `button`.

See https://github.com/reactstrap/reactstrap/issues/382

The "fix" for this actually broke the default behavior that we happened to be relying on.

**Comment by geoffreyhale** [comment]
Workaround, I used `as="div"`.
