### ISSUE TITLE
form group doesn't have class of input state

### ISSUE THREAD

**Issue by martinsvb** [reactstrap/reactstrap#369]
Hi there,

I use this form group expression in jsx:
                        <Input state={this.state.firstNameState} type="text" name="firstName" value={this.state.firstName} onChange={this.handleChange} placeholder="First Name" />
                        <FormFeedback>{this.state.firstNameError}</FormFeedback>

When I changed this.state.firstNameState value(danger/success), **value is applied only to input in resulting html, but no to parent div**.

result (danger example):
```
<div class="form-group">
<input type="text" name="firstName" value="x" placeholder="First Name" class="form-control-danger form-control">
<div class="form-control-feedback">Minimal length is 5 characters.</div>
</div>
```

desired result:
```
<div class="form-group-danger">
<input type="text" name="firstName" value="x" placeholder="First Name" class="form-control-danger form-control">
<div class="form-control-feedback">Minimal length is 5 characters.</div>
</div>
```

Can you check it?

Anyway react strap is very nice tool! :-)

Martin

**Comment by TheSharpieOne** [comment]
Form group has a color prop. Use that to control the class on the form group. Reactstrap is meant to be simple components, so each of the components here are individual, if you are looking for a simple way to do validation and styling without having to manually manage each of the elements, I would have to recommend you look at availity-reactstrap-validation, the link is in reactstrap readme at the bottom.

**Comment by martinsvb** [comment]
Hi, thank you for your quick react. :-)
I found color attribute after issue created too.
Thanks for validation component recommendation.
