### ISSUE TITLE
No offset-0, meaning the can't reset offset at larger sizes. 

### ISSUE THREAD

**Issue by dotstormz** [reactstrap/reactstrap#374]
### Issue description
Currently there is no way to specify offset 0. This means that if you choose to use an offset at a smaller size and then remove it at another breakpoint you can't. Modifying bootstrap classes not through React strap will get the desired results with offset-0

### Steps to reproduce issue
- Create a Col and give it an offset of one of greater at xs,sm or md
- Try and reset using offset-lg-0

Reseting of offset is ignored.

**Comment by TheSharpieOne** [comment]
Example of issue: https://www.webpackbin.com/bins/-KgVu7n8-_va3SdIrm93 (inspect and see call is not present)
