### ISSUE TITLE
DatePicker

### ISSUE THREAD

**Issue by rosieks** [reactstrap/reactstrap#385]
Do you have plan to add date picker to this project or do you have any recommendation of one that work with reactstrap? I know that it's not part of Bootstrap but I think that it's quite common component and it would be nice to have it here. It's even part of Angular UI Bootstrap: http://angular-ui.github.io/bootstrap/#!#datepickerPopup

**Comment by eddywashere** [comment]
I don't have plans to contribute one but I'm more than happy to link out to one that works with reactstrap or add it to the project org. I've heard good things about https://github.com/airbnb/react-dates. It might be useful to have bootstrap 4 themed scss/css for it.

**Comment by NathanCH** [comment]
@rosieks were you able to find a good alternative? Airbnb react-dates has style conflicts with Bootstrap 4 and requires **a lot** of styling to get it looking like Bootstrap.

I tried to fork react-bootstrap-datepicker to be compatible reactstrap but ran into a lot of trouble. I might try to make a simple one if no good alternative shows up.

**Comment by rosieks** [comment]
Eventually I decided to use datepicker from react-widgets

**Comment by Flo-Slv** [comment]
Hello here!

**Comment by virgofx** [comment]
Nowadays most browsers support native integration via the `input type="date"`. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

For a truly cross compliant version you can browse Github.

**Comment by Flo-Slv** [comment]
Thanks
Finally. i use react-datepicker.

**Comment by TheSharpieOne** [comment]
Personally, I use https://github.com/Adphorus/react-date-range and place it in a reactstrap Popover. Even though it is called react-date-range, it provides both date and date range capabilities.

**Comment by tahv0** [comment]
> Eventually I decided to use datepicker from react-widgets

How do you use it?

Mine breaks like this
![screenshot from 2018-10-27 16-47-43](https://user-images.githubusercontent.com/16887142/47604890-13b4a700-da08-11e8-9794-00336381c282.png)

**Comment by viniciustodesco** [comment]
> Thanks
> Finally. i use react-datepicker like this:
> 
> ` <DatePicker selected={this.state.startDate} onChange={this.handleChange} dateFormat="DD/MM/YYYY" locale="fr-fr" showYearDropdown scrollableYearDropdown yearDropdownItemNumber={15} customInput={<CustomInput date={this.state.startDate} />} />`
> `const CustomInput = props => ( <Input onClick={props.onClick} value={props.date.format('DD/MM/YYYY')} /> );`
> 
> I use 'customInput' property to add Reactstrap 'Input'.

Tks worked perfectly
