### ISSUE TITLE
Form onSubmit not working

### ISSUE THREAD

**Issue by stanleynguyen** [reactstrap/reactstrap#388]
Previously when I was using version 4.2.0. onSubmit function binding was working fine. But after updating to the newest release, onSubmit is not there anymore. What was the change? How should I go about handling form submit now?

**Comment by TheSharpieOne** [comment]
#382 use type="submit" on your button

**Comment by stanleynguyen** [comment]
@TheSharpieOne Thank you! 4.5.0 release indeed solves the problem

**Comment by whydna** [comment]
this s broken in the beta

**Comment by TheSharpieOne** [comment]
@whydna can you elaborate? I cannot reproduce: https://stackblitz.com/edit/reactstrap-v5beta-form-submit-button?file=Example.js

**Comment by whydna** [comment]
@TheSharpieOne Interesting... https://stackblitz.com/edit/reactstrap-v5beta-form-submit-button-rzq1hw?file=Example.js

**Comment by TheSharpieOne** [comment]
Yes, if you provide an action via onClick it will not act as a form button and not submit the form (it will perform the onClick action specified). If you want both, you will need to add `type="submit"`.

**Comment by whydna** [comment]
Evan, I think you misunderstood. See my demo link.

I want the signup button to execute signup(), the login button to execute login() and hitting enter on any field to execute the submit().

**Comment by TheSharpieOne** [comment]
You have to have a button with type=submit (the default if there is no onClick). This is not reactstrap, this is the html spec for the browser (only a single field form can trigger the submit on enter without a button).
You can try adding a button and visually hiding it or add keydown listeners to the fields and listening for the enter key.

**Comment by whydna** [comment]
Ah gotcha.

Thanks Evan.
