### ISSUE TITLE
Option to hide 'X' in top right corner

### ISSUE THREAD

**Issue by 3v3r3tt** [reactstrap/reactstrap#390]
### Issue description
 
- components: `modal`

More of an "improvement" than an issue, but was just wondering if there is an easy option to hide the `X` in the top right corner of the modal? For a use case where the user should not be able to just dismiss the modal, but must address it by clicking either the Confirm or Cancel button.

**Comment by TheSharpieOne** [comment]
Do not supply the toggle prop to ModalHeader. You might also not want to supply it to the Modal either, to prevent keyboard (esc) and clicking on the backdrop from closing the modal.

**Comment by TheSharpieOne** [comment]
Closing this issue since it appears to be resolved and has not been active in over 30 days. If you believe the issue was not resolved, please comment with more information and it will be reopened.
