### ISSUE TITLE
React Addons are discontinued; fix dependencies

### ISSUE THREAD

**Issue by apaatsio** [reactstrap/reactstrap#393]
reactstrap has peer dependency on react-addons-css-transition-group and react-addons-transition-group. These have been discontinued as of React 15.5.0 and there are drop-in replacements available.

See https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by virgofx** [comment]
Can the build be fixed to exclude PropTypes in the /dist versions as well.

**Comment by apaatsio** [comment]
@virgofx see #395

**Comment by virgofx** [comment]
Thanks @apaatsio  Looks good ... will the dist builds have PropTypes removed? I didn't see any changes in the babelrc to include the babel transform that removes these.

**Comment by apaatsio** [comment]
Ah, now I understand you were talking about a completely different thing. 

Regarding the dist build, I tried https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types but it failed to remove all of the proptypes. I didn't investigate further.

**Comment by virgofx** [comment]
Thanks @apaatsio ... I noticed the same thing in my project, I'm investing a few parent/child issues to see if a small PR will fix that ... then I'll test here later and follow up in a later PR.

**Comment by hellowin** [comment]
PR related, I hope it would be merged soon https://github.com/reactstrap/reactstrap/pull/399

**Comment by AleksanderGrzybowski** [comment]
Great! I just started a small side project with c-r-a and this library is very promising, waiting to get rid of this React warning in console. Cheers!

**Comment by eddywashere** [comment]
this is fixed in 4.6.1
