### ISSUE TITLE
Add React v15.5 support

### ISSUE THREAD

**Issue by Airkro** [reactstrap/reactstrap#398]
>Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by ahmadsholehin** [comment]
Facing the same issue above.

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by TheSharpieOne** [comment]
It's not an issue, it's a depracation warning. React 15.5 is fully supported. Everything still works 100% and that message is only in development. Yes, the depracation will be addressed before it becomes an issue. There is currently a pending PR #395

**Comment by ahmadsholehin** [comment]
Awesome. That's great to know!

**Comment by nathancahill** [comment]
#399 also addresses addon deprecation.

**Comment by eddywashere** [comment]
This should be fixed in 4.6.1. Thanks!
