### ISSUE TITLE
Docs: It should close all nested modals if the main modal get closed

### ISSUE THREAD

**Issue by Skaronator** [reactstrap/reactstrap#400]
This issue has more to do with the docs itself and not with the reactstrap code:

Version: 4.5.0

Reproduce:
1. Open https://reactstrap.github.io/components/modals/
2. Scroll down to 'Nested Modals' and launch the example
3. Open the nested modal
4. Click on "All Done"
5. Launch Example again and it'll open the nested modal as well.

I assume it would be better when the nested modal won't reopen again?

**Comment by TheSharpieOne** [comment]
Right, it should dismiss/close the nested modal before dismissing/closing the outer one. The animation would look better doing that as well.
