### ISSUE TITLE
How to add custom elements in modal header component?

### ISSUE THREAD

**Issue by rehat101** [reactstrap/reactstrap#403]
How can I add custom elements like below inside the modal header component? 

![image](https://cloud.githubusercontent.com/assets/8665427/25343781/a9eb80dc-292d-11e7-8c5c-3f5eba80ae65.png)

**Comment by TheSharpieOne** [comment]
`<ModalHeader>....your stuff here...</ModalHeader>`

**Comment by eddywashere** [comment]
looks like this was answered

**Comment by Nienormalny** [comment]
Yeah bt this `<ModalHeader>...Your staff...</ModalHeader>` generate "Your staff" in my case `<i className="ICON" /> <div calssName="collapse btn-toggle"><button>info 1</button><button>info 2</button></div>` inside `<h5>` if you know what i mean.

**Comment by gergely-nagy** [comment]
Use the `tag` prop!
```javascript
<ModalHeader tag="h3">
    <i className="ICON" />
    <div calssName="collapse btn-toggle">
        <button>
            info 1
        </button>
        <button>
            info 2
        </button>
    </div>
</ModalHeader>
```
You can also pass in other components, not just strings!
