### ISSUE TITLE
Question about props.children

### ISSUE THREAD

**Issue by maxlibin** [reactstrap/reactstrap#405]
```
  return (
      <Tag
        type={(Tag === 'button' && attributes.onClick) ? 'button' : undefined}
        {...attributes}
        className={classes}
        ref={getRef}
        onClick={this.onClick}
      />
    );
```
Can anyone tell me where this Tag come from? sorry if i post in wrong place, learning react.

**Comment by TheSharpieOne** [comment]
The `tag` prop is optionally passed in when you use the component. It defaults to `button` or `a` depending on other props if you do not provide it.

**Comment by maxlibin** [comment]
<Tag.../> looks like a component to me, but i don't see anywhere you defined this.

**Comment by TheSharpieOne** [comment]
Tag is a component, it's a component you can optionally provide via a prop to override the default component/tag/element (see the defaultProps for where it is defaultly defined). Let's say `Tag` defaulted to `div`, but you want a `span` (block vs inline display style elements), you can pass `tag="span"` and now the component you are calling/rendering outputs a `span`. You can also pass in other components, like `Link` from react-router (`tag={Link}`)  and it will render that.

**Comment by aclave1** [comment]
@maxlibin Tag is a component that you can pass in via props, you can see [here](https://github.com/reactstrap/reactstrap/blob/master/src/Card.js#L28) the syntax which converts the tag prop to the uppercase Tag used in the jsx
