### ISSUE TITLE
24 hours time format for "time" type Input

### ISSUE THREAD

**Issue by hhashmi** [reactstrap/reactstrap#406]
is it possible to have 24 hours (military) time formate for "time" type Input?

datetime type Input is not working

**Comment by TheSharpieOne** [comment]
It is up to the browser to determine the UI which is displayed within the input. reactstrap adds the bootstrap classes, bootstrap styles the input [container]. Different browsers will display different UIs.
more information: http://stackoverflow.com/questions/13523060/html5-time-inputs-shows-12-hours

As for datetime, it didn't make the cut for HTML5, try `datetime-local` instead: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime
