### ISSUE TITLE
alignment

### ISSUE THREAD

**Issue by ceesss** [reactstrap/reactstrap#408]
Looking at the bootstrap docs, there's a whole section on Alignment:
https://v4-alpha.getbootstrap.com/layout/grid/#alignment

Are these supported by reactstrap or something I just use via css classes? I'm trying to figure out the grid based on the examples, but it doesn't really map to https://v4-alpha.getbootstrap.com/layout/grid/

**Comment by c-sojka** [comment]
What I really want is an equally-spaced, 6 column row when viewing on a desktop but then goes to 2 rows of 3 once there's not room for 6 and then goes to a single column as soon as there's not room for 3. 
Large Screen
XXXXXX

Middle
XXX
XXX

Mobile
X
X
X
X
X
X

I'm unclear if that means I need to use the "t-shirt" size properties and if need to set them to a size like 'sm=2'?

**Comment by eddywashere** [comment]
You should be able to use the css classes. The Col component sticks to just the core grid classes and not the flex modifiers.
