### ISSUE TITLE
Dropdown requires 2 clicks to open

### ISSUE THREAD

**Issue by alexsalajan** [reactstrap/reactstrap#409]
### Issue description

- version `#4.5.0`
- components: `Dropdown`

After adding React Router 4 to the project, every dropdown requires two clicks in order to open. Did anyone else encounter this issue?

**Comment by TheSharpieOne** [comment]
Can you create a fiddle, plnkr, pen, or bin with a reduced case showcasing this issue?

**Comment by alexsalajan** [comment]
Sorry for the delayed response. I fixed the problem, it was caused by an error in my webpack configuration.
