### ISSUE TITLE
Dropdown on the right?

### ISSUE THREAD

**Issue by Industrial** [reactstrap/reactstrap#411]
### Issue description

How do I get a dropdown to align to the right like displayed at https://v4-alpha.getbootstrap.com/components/dropdowns/#menu-alignment ?

- version `#4.5.0`

### Steps to reproduce issue

- NavDropdown

**Comment by iamandrewluca** [comment]
@Industrial how the issue was fixed? I also encountered this problem.

had to add a hack to fix this temporary
https://github.com/twbs/bootstrap/issues/23553
```
// https://github.com/twbs/bootstrap/issues/23553
.dropdown-menu-right {
  right: 0;
  left: auto; // Reset the default from `.dropdown-menu`
}
```
