### ISSUE TITLE
Proper way to have multiple dropdown menu button?

### ISSUE THREAD

**Issue by HadiAkmal** [reactstrap/reactstrap#422]
### Issue description
What is the proper way to have two dropdown menu button such as in example : https://reactstrap.github.io/components/button-dropdown/

For now this is how I do it:

- version `#4.5.0`
- components: `button-dropdown`

### Steps to reproduce issue
Create initial state, method and button. Here is my state in constructor:
```
    this.state = {
      isOpen1: false,
      isOpen2: false,
    };
```

My method: 
```
  toggle1() {
    this.setState({
      isOpen1: !this.state.isOpen1,
    });
  }

  toggle2() {
    this.setState({
      isOpen2: !this.state.isOpen2,
    });
  }
```

Component:
```
<ButtonDropdown isOpen={this.state.isOpen1} toggle={this.toggle1}>
  <DropdownToggle caret size="lg">
    Large Button
  </DropdownToggle>
  <DropdownMenu>
    <DropdownItem>Another Action</DropdownItem>
    <DropdownItem>Another Action</DropdownItem>
  </DropdownMenu>
</ButtonDropdown>

<ButtonDropdown isOpen={this.state.isOpen2} toggle={this.toggle2}>
  <DropdownToggle caret size="sm">
    Small Button
  </DropdownToggle>
  <DropdownMenu>
    <DropdownItem>Another Action</DropdownItem>
    <DropdownItem>Another Action</DropdownItem>
  </DropdownMenu>
</ButtonDropdown>
```

Output is working:
![image](https://cloud.githubusercontent.com/assets/14165645/26004259/c4980fd4-3767-11e7-9361-517a6c3bac98.png)

Is this the correct way to have multiple dropdown button? Thanks in advance.

**Comment by TheSharpieOne** [comment]
Yes, that is correct.
But as you have noticed, there is a lot of boilerplate for something that is the most common use-case for dropdown (clicking to toggle). Because of this, reactstrap has Uncontrolled components which most simply means, you do not get to control them (you do not need to have isOpen and toggle). They work the same from the user experience, but do not require the isOpen state nor the toggle funtions.

```
<UncontrolledButtonDropdown>
  <DropdownToggle caret size="lg">
    Large Button
  </DropdownToggle>
  <DropdownMenu>
    <DropdownItem>Another Action</DropdownItem>
    <DropdownItem>Another Action</DropdownItem>
  </DropdownMenu>
</UncontrolledButtonDropdown>

<UncontrolledButtonDropdown>
  <DropdownToggle caret size="sm">
    Small Button
  </DropdownToggle>
  <DropdownMenu>
    <DropdownItem>Another Action</DropdownItem>
    <DropdownItem>Another Action</DropdownItem>
  </DropdownMenu>
</UncontrolledButtonDropdown>
```

More info: very bottom of https://reactstrap.github.io/components/dropdowns/

**Comment by HadiAkmal** [comment]
I prefer your solution. Thank you :)

**Comment by apwat56102** [comment]
Plz SumMenu

**Comment by Nels4UCA** [comment]
Thanks brooooo

**Comment by shahzadthathal** [comment]
Great answer
