### ISSUE TITLE
Class application order

### ISSUE THREAD

**Issue by bessey** [reactstrap/reactstrap#423]
Some background: I am using [babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules/issues) to use CSS modules, but handling the process at build time. In short this means
`<Card styleName="blah"/>`
is compiled to
`<Card className="123-blah" />`.

This works great with reactstrap, however, reactstrap in every component I've checked applies it's own class names [_after_ the className passed in](https://github.com/reactstrap/reactstrap/blob/master/src/Dropdown.js#L189) from `props`.

I'm wondering if there is a need for this? My issue is that the result of outputting
`<div class="123-blah card">`
is that I cannot override without `!important` the attributes reactstrap sets, because the selectors have equal specificity.

If not, I would like to submit a PR to replace, in all components, 

```jsx
        {...attributes}
        className={classes}
```

with

```jsx
        className={classes}
        {...attributes}
```

**Comment by TheSharpieOne** [comment]
The attributes are in that order to allow the className's provided by the user to be extended with the bootstrap classes.
If you do not want the bootstrap classes, then do not user reactstrap components. All reactstrap does for most of it's components (such as `Card`) is add bootstrap classes.
In your case, change `<Card styleName="blah"/>` to `<div styleName="blah"/>`.

**Comment by bessey** [comment]
I _do_ want the Bootstrap class though, I just want to be able to override _some_ attributes _some_ of the time. 

I'm not sure I follow what you mean by "allow the className's provided by the user to be extended with the bootstrap classes.", could you give an example? I don't see how a framework could extend a user's styles, only the reverse. When would you specifically want `.my-thing.card` and not `.card.my-thing`?

**Comment by TheSharpieOne** [comment]
`.my-thing.card` and `.card.my-thing` are the same thing in css. 
Let's say you want to add your own class to card, you can provide your class and it will be added along with card. Since you specified you wanted card by using `Card`, that class is added along with your extra class. 
If you don't want the card class, don't use `Card`, same for the other components because the components pretty much just add classes for you.

**Comment by bessey** [comment]
Oh my, I'm an idiot 😅. I really thought that class order affected the chosen attribute when specificity was equal, [my apologies](https://jsfiddle.net/atpwk5tw/).

My webpack build must be appending the BS CSS after my CSS modules. Thanks for your help, and for the library!

**Comment by harshpatel991** [comment]
In case anyone comes across this, if you're using the default react setup with create-react-app, you need to change the order bootstrap.css is loaded. In `src/index.js`, move bootstrap.css above index.css and App.js:
```
import "bootstrap/dist/css/bootstrap.css";
import "./styles/index.css";
import App from "./App";
```
