### ISSUE TITLE
Standardize `getTarget`

### ISSUE THREAD

**Issue by eddywashere** [reactstrap/reactstrap#424]
From https://github.com/reactstrap/reactstrap/pull/331#issuecomment-301344176

> It looks like we need to standardize and abstract the getTarget functionality into utils. Right now popover/tooltip have different ways of getting target. To future proof getTarget as much as possible it should support a css selector (string), a dom reference or a function that returns a dom reference. Once that's in it will be easier to check if target matches click target. going to close this out until that happens.

Components to update

- Tooltip
- Popover

**Comment by TheSharpieOne** [comment]
Just so happens that I did that.
https://github.com/reactstrap/reactstrap/blob/v5/src/utils.js#L96-L110
