### ISSUE TITLE
Link in DropdownItem will not work in IE11

### ISSUE THREAD

**Issue by zzswang** [reactstrap/reactstrap#43]
If I put Link inside dropdownitem, it will not work in IE11.  It's ok in chrome.

Any ideas?

import {Link} from 'react-router';

```     
     <Dropdown isOpen={this.state.isAdminMenuOpen} toggle={this.toggleAdminMenu.bind(this)}>
            <DropdownToggle>
              <Button color="secondary"><i className="icon-cog" /></Button>
            </DropdownToggle>
            <DropdownMenu right>
              <DropdownItem><Link to="/me"> Account </Link></DropdownItem>
              <DropdownItem><Link to="/admin">Admin</Link></DropdownItem>
              <DropdownItem divider/>
              <DropdownItem onClick={this.props.actions.logout}>Logout</DropdownItem>
            </DropdownMenu>
          </Dropdown>
```

**Comment by eddywashere** [comment]
Looks like I didn't add the documentation for that. You should be able to do something like this:

```jsx
<DropdownItem tag={Link} to="/me">text here</DropdownItem>
```

Most components have a tag prop to customize which element/component to use when rendering.

**Comment by zzswang** [comment]
Cool, it works.

**Comment by eddywashere** [comment]
closing this. I added a note in V2 roadmap to cover this sort of documentation.

**Comment by alamothe** [comment]
Isn't the suggested solution going to interfere with Link's `onClick` handler? Basically, this turns Link into an anchor element - clicking will do full refresh

**Comment by AbhaysinghBhosale** [comment]
> If I put Link inside dropdownitem, it will not work in IE11. It's ok in chrome.
> 
> Any ideas?
> 
> import {Link} from 'react-router';
> 
> ```
>      <Dropdown isOpen={this.state.isAdminMenuOpen} toggle={this.toggleAdminMenu.bind(this)}>
>             <DropdownToggle>
>               <Button color="secondary"><i className="icon-cog" /></Button>
>             </DropdownToggle>
>             <DropdownMenu right>
>               <DropdownItem><Link to="/me"> Account </Link></DropdownItem>
>               <DropdownItem><Link to="/admin">Admin</Link></DropdownItem>
>               <DropdownItem divider/>
>               <DropdownItem onClick={this.props.actions.logout}>Logout</DropdownItem>
>             </DropdownMenu>
>           </Dropdown>
> ```

How can we send the props with the link like this.
<Link to={{ pathname: '/accountslist/policylist', search: '', state: { Account: row.original, isWizard: false, prevPath: this.props.location.pathname } }}>
                            <DropdownItem className="pb-2 pt-2 pl-2 pr-2">
                            <i className='fa fa-gears mr-1 ml-0 text-dark' id={'update_policies' + row.value}><CustomTooltip text={Resource.LBL_Policies} target={'update_policies' + row.value} placement='top' /></i>{Resource.LBL_Policies}
                            </DropdownItem>
                          </Link>

this is working in chrome but not in IE

**Comment by FullyFerret** [comment]
This doesn't work anymore

**Comment by mvgrimes** [comment]
Replacing it with the following worked for me.

```
      <DropdownItem tag="span">
          <Link href="/overview">
                <NavLink>Overview</NavLink>
          </Link>
    </DropdownItem>
```

**Comment by ptn1411** [comment]
`   <DropdownMenuItem asChild>
                            <Link href={route("profile.edit")}>Profile</Link>
                        </DropdownMenuItem>`
