### ISSUE TITLE
[4.6.1] Pointing to minified react causes warning

### ISSUE THREAD

**Issue by agos** [reactstrap/reactstrap#430]
### Issue description

Upon upgrading from 4.5.0 to 4.6.1, a new warning pops up in console:

> reactstrap.min.js:1 Warning: It looks like you\'re using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.

I was not able to fork the suggested pen to reproduce the issue, likely due to #429.

**Comment by Skaronator** [comment]
same as #429

**Comment by jameschao** [comment]
@Skaronator - thanks it definitely seems related.

But what I don't understand is that the `package.json` change you referenced (https://github.com/reactstrap/reactstrap/commit/546104971b2526dc9be8491cf6f50b9e8c3fdcb2) seems to be present for 4.5.0 already according to the tag list for that commit. But this current React warning wasn't there for 4.5.0 for me.

**Comment by eddywashere** [comment]
fixed in 4.6.2
