### ISSUE TITLE
Align button right

### ISSUE THREAD

**Issue by brooth** [reactstrap/reactstrap#431]
### Issue description

- version `#4.6.1`
- components: `Button`

I'm trying to create a form with a right-aligned button. `class="float-righ"` not working. Here is the code:

```jsx

export default class LoginForm extends Component {
    render() {
        return (
            <div>
                <Form>
                    <FormGroup row>
                        <Label for="loginEmail" sm={2}>Email</Label>
                        <Col sm={10}>
                            <Input type="email" name="email" id="loginEmail" />
                        </Col>
                    </FormGroup>
                    <FormGroup row>
                        <Label for="loginPassword" sm={2}>Password</Label>
                        <Col sm={10}>
                            <Input type="password" name="password" id="loginPassword" />
                        </Col>
                    </FormGroup>
                    <Button color="primary">Submit</Button>
                </Form>
            </div>
        );
    }
}
```

**Comment by shaaslam** [comment]
class name is wrong, please use class="float-right"
![capture](https://cloud.githubusercontent.com/assets/23412337/26068452/732b815c-3952-11e7-8930-87a57b71cd4b.PNG)

**Comment by brooth** [comment]
Ok, I found. It's `className` property, not just `class`. Now it works.

```html
<Button color="primary" className="float-right">Submit</Button>
```

**Comment by omkarsk98** [comment]
How can I put the button in the center?

**Comment by TheSharpieOne** [comment]
if you wrap the button in a `<div>` and give that div `className="text-center"` it will be centered. Similarly, using `className="text-right"` will make it right-aligned and is preferred over `float-right` due to how floats need to be cleared.
