### ISSUE TITLE
React's "minified copy of the development build" warning after upgrading to 4.6.1

### ISSUE THREAD

**Issue by jameschao** [reactstrap/reactstrap#432]
### Issue description

After upgrading to 4.6.1 from 4.5.0, I'm seeing the following warning message when running my tests in Jest:

```
    console.error node_modules/reactstrap/dist/reactstrap.min.js:1
      Warning: It looks like you\'re using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.
```
I get this simply by importing `Button` (or other components) from `reactstrap`, even without actually using it in my JSX code.

Related changes I made on my end is to use `react-transition-group` and no longer `react-addons-css-transition-group` and `react-addons-transition-group`.

Was there a built related change that might've caused this?

- version `#4.6.1`
- components: `Button`

### Steps to reproduce issue
- Upgrade to 4.6.1.
- import a component like `Button`.

**Comment by th3fallen** [comment]
same here

**Comment by Skaronator** [comment]
same as #429

**Comment by jameschao** [comment]
This duplicates #430 so I'll close this issue.
