### ISSUE TITLE
Sidebar / Drawer

### ISSUE THREAD

**Issue by ablbol** [reactstrap/reactstrap#441]
Hi,
Sorry this is not an issue but rather a question.

I was wondering if it is possible to do togglable sidebar or drawer with reactstrap? Does any body know or tried something.
Thanks

**Comment by eddywashere** [comment]
This a good question for the main bootstrap repo or stackoverflow. But while you're here, I sort of built something like that with alpha 2 css, http://codepen.io/eddywashere/pen/wGVgoN.

**Comment by JinRi-coding** [comment]
The foundation of reactstrap is bootstrap.
So in reactstrap project, it is good to use bootstrap element.
Check this : https://bootstrapious.com/p/bootstrap-sidebar
You can make reactstrap sidebar by using this
