### ISSUE TITLE
react-addons-transition-group and react-addons-css-transition-group are deprecated

### ISSUE THREAD

**Issue by zhaoyao91** [reactstrap/reactstrap#442]
### Issue description
when I install dependencies following the steps in home page, I received such warnings
```
npm WARN deprecated react-addons-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+. We recommend you use TransitionGroup from 'react-transition-group' instead.
npm WARN deprecated react-addons-css-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+. We recommend you use CSSTransitionGroup from 'react-transition-group' instead.
```
It seems that `react-addons-css-transition-group` and `react-addons-transition-group` are deprecated. So I hope this projected be updated to remove these dependencies.

- version `4.6.2`

**Comment by virgofx** [comment]
I believe the Readme.md is accurate and up-to-date; however, the website has not been updated to reflect changes. I do believe this is fixed and all transitions use the new module now.

**Comment by cr101** [comment]
@zhaoyao91 both of those packages have been removed. Are you sure you are running version 4.6.2?

**Comment by zhaoyao91** [comment]
yeah, so it only the problem with the github.io page. the guide is outdated.
