### ISSUE TITLE
Can i Custom className on Component ?

### ISSUE THREAD

**Issue by kenshero** [reactstrap/reactstrap#445]
ex.
```
<div>
    <InputGroup size="lg" className="input-search" > 
     <style jsx>{`
        .input-search {
          margin: 0 auto;
          width: 67%;
        }
      `}
      </style>
</div>
```

i use with next.js

**Comment by TheSharpieOne** [comment]
You sure can. Your custom class get [added to the bootstrap ones](https://github.com/reactstrap/reactstrap/blob/master/src/InputGroup.js#L25-L29) which then get [added to the element](https://github.com/reactstrap/reactstrap/blob/master/src/InputGroup.js#L32).

All of the reactstrap components should do this. Open a defect if you find one that doesn't. Note, some components output more than one element and may provide additional props for adding classes to inner/outer elements.

**Comment by kenshero** [comment]
sorry. i am newbie. do you have example ?

**Comment by TheSharpieOne** [comment]
Your example works, you just need to provide content and a closing tag (or self closing tag). 
```
<InputGroup size="lg" className="input-search">Your stuff here</InputGroup>
```

Working example: https://www.webpackbin.com/bins/-KklyalFvjyPjBHGALcb

**Comment by kenshero** [comment]
I will try.
```
  <div>
        <InputGroup size="lg" className="input-search">
          <Input />
          <InputGroupButton color="secondary">Search</InputGroupButton>
        </InputGroup>
         <style jsx>{`
        .input-search {
          margin: 0 auto;
          width: 67%;
        }
      `}
      </style>
   </div>

```

I think it dosen't work because server-rendering ?.

**Comment by oleole90** [comment]
Same problem here. [Styled-jsx](https://github.com/zeit/styled-jsx) css properties don't get attached to the component but the class name gets added.

Using global as a workaround:
```
<style jsx global>{`
.input-search {
    margin: 0 auto;
    width: 67%;
 }
`}</style>
```

Any solution?

**Comment by TheSharpieOne** [comment]
I am closing this as the question does not pertain to reactstrap directly. As noted above, you can add custom classes to components via the `className` prop.
styled-jsx question should be asked in stackoverflow or that project's repo.
