### ISSUE TITLE
Can't use any Bootstrap components without error

### ISSUE THREAD

**Issue by thomasbaldwin** [reactstrap/reactstrap#446]
### Issue description

- version `#4.6.2`
- components: `Button`

### Steps to reproduce issue

<img width="420" alt="screen shot 2017-05-24 at 3 15 36 pm" src="https://cloud.githubusercontent.com/assets/5099084/26421409/fa04cf1a-4093-11e7-84d6-96c320de6980.png">

    Error in ./~/reactstrap/lib/Alert.js
    Module not found: 'react-transition-group/CSSTransitionGroup' in /Users/.../node_modules/reactstrap/lib
    @ ./~/reactstrap/lib/Alert.js 21:26-78

**Comment by lecstor** [comment]
I just did the exact same thing after install. Worked fine. Did you install `react-transition-group`?

**Comment by TheSharpieOne** [comment]
Yes, `react-transition-group` is a peerDep, meaning you have to install it yourself, similar to `react` and `react-dom`. So if you create a fresh project, you will need to install it alongside of `reactstrap`, `react`, and `react-dom`. If you are upgrading to the latest version, you will need to simply install `react-transition-group` by itself.

Idk if this qualifies as a breaking change or not :\

**Comment by tobymurray** [comment]
> If you are upgrading to the latest version, you will need to simply install react-transition-group by itself.

I just took a look at this project today, perhaps worth adding this to the "Getting Started" documentation (beside all the other peer dependencies)?

**Comment by thomasbaldwin** [comment]
Yep that was the trick. Thanks guys

**Comment by virgofx** [comment]
It's clearly labeled in the Readme to install all 3 peer dependencies.

**Comment by turnerhayes** [comment]
Could the dep version be bumped? If you just run `npm install react-transition-group`, it installs (at the time of writing) `2.0.2`. I had to explicitly install `react-transition-group@^1.1.2`, which isn't terrible, but it's an extra thing to keep in mind.

**Comment by TheSharpieOne** [comment]
Closing this in favor of #502 as it is more specific about react-transition-group being the issue and has some comments about supporting the new react-transition-group v2 API.

The solution to this was to use specific install `react-transition-group@^1.1.2` via `npm i react-transition-group@^1.1.2 -S`
