### ISSUE TITLE
Size ballooned recently?

### ISSUE THREAD

**Issue by davidascher** [reactstrap/reactstrap#448]
27 days ago, the analysis of my app had this size allocation for reactstrap:

<img width="244" alt="screenshot 2017-05-25 16 19 53" src="https://cloud.githubusercontent.com/assets/51278/26474466/1510eab4-4166-11e7-80c5-365f82ded0ae.png">

Today, with 4.6.2, I'm seeing:

<img width="566" alt="screenshot 2017-05-25 16 20 59" src="https://cloud.githubusercontent.com/assets/51278/26474494/2ae0d944-4166-11e7-84c6-a0ee2d29d09f.png">

I can't recall what version of reactstrap I was on 27 days ago but it was the current one then.  I've since updated the scripts in create-react-app to its 1.0 version, which switches to webpack 2.0, but reactstrap is the only of my dependencies which has ballooned like that, and so I wonder if somehow there's been a change in the way reactstrap is being distributed.

**Comment by TheSharpieOne** [comment]
I imagine some dependencies are being bundled that should be. This probably correlates to the change from webpack to rollup and forking tether.

**Comment by virgofx** [comment]
May need to check to make sure that the `prop-types` package is **not** being included as well. It should be up to caller to include this.

**Comment by TheSharpieOne** [comment]
Looks like everything is being included in the minified version... react, react-dom, prop-types, tether, etc.
If you are using es modules with tree shaking, it will shake out the code you are not using.
If you are using common js and doing `require`s / `import`s in your code, it will use the `/lib` directory and pull in just what you are using (it will not use the `.min.js` from `/dist`.)
If you are using UMD to import your script on the page using 1990's `<script>` tags... then there is no hope. The dist needs to be fixed for this case to remove the libraries which should be external.

**Comment by virgofx** [comment]
External should be:
1. React
2. React-dom
3. prop-types  (We should be able to run this through the babel transpiler with the option of convert which converts prop types). It may not remove it 100% because of contextType components. Either way, it should be external.

I'd argue that tether should be included.

Then update documentation for using the dist to properly include above components.

**Comment by jeffmad** [comment]
looking at [rollup.config.js](https://github.com/reactstrap/reactstrap/blob/master/rollup.config.js), it seems that react and react-dom ARE set to be external,  package.json build task runs  rollup.  How are they sneaking back in?

**Comment by TheSharpieOne** [comment]
fixed and released in 4.8.0
