### ISSUE TITLE
How to style a popover

### ISSUE THREAD

**Issue by skmexyz** [reactstrap/reactstrap#449]
I'm a bit confused on how to style a popover. Adding style to PopoverTitle and PopoverContent works but I can't seem to do the same for the Popover component. Any style applied to it is completely ignored.

**Comment by designbyadrian** [comment]
Indeed, I wanted to add a class with `className`, but it isn't added to `.popover` - only it's direct child.

**Comment by TheSharpieOne** [comment]
Right now it looks like classes are added to the "popover-inner", no user defined classes are added to the "popover" which is the `TetherContent`
Not too sure if the `className`s should be move to be applied to the "popover" instead of the "popover-inner" and the "popover-inner" have a special prop (such as `innerClassName`) or if className should stay where it is and add a special prop for the outer/wrapper (such as `wrapperClassName`).

**Comment by SahilRS200** [comment]
Hi,
Is there any update on this. How do I override the standard .popover elements that comes with the tag.
Also there is a transform3d styling, which I need to change to remove blur effects.

**Comment by rkumar-auro** [comment]
Is there any update on this ?

**Comment by yudihindarko** [comment]
We can't add class directly component, as far as i know what we can only do is to override style of .popover with your own style in your css file.
For example if you want to change the max-width, just add .popover in your css file then type in your desired max width into it.

**Comment by TheSharpieOne** [comment]
Correct, you have to use css to change the styles of your popovers. You can make a global change as recommended by @yudihindarko or you can use a custom className to target specific ones

https://stackblitz.com/edit/reactstrap-v8-jqzz8v?file=Example.js

given `className="my-custom-popover"` on the `Popover` or `UncontrolledPopver` you can use something like:

```css
.my-custom-popover .popover {
  max-width: 500px;
}
```

**Comment by moniqueboea** [comment]
This is old but...

Define your style:

`const popoverStyle = {
  margin: "10px",
  width: "500px",
};`

Then add it to the popover:

`  <Popover.Content style={popoverStyle}>`
