### ISSUE TITLE
Modal Component Prevent closing on escape

### ISSUE THREAD

**Issue by oliverasistemas** [reactstrap/reactstrap#453]
Hi, I don't see an option that makes closing on escape optional. Is there any way of doing that?

**Comment by TheSharpieOne** [comment]
the `keyboard` prop is used for that. It is a boolean which defaults to `true`. It lines up with the [bootstrap js modal property](http://v4-alpha.getbootstrap.com/components/modal/#options) of the same name/function.
It is somewhat documented in the listing of the reactstrap modal props on https://reactstrap.github.io/components/modals/

**Comment by TheSharpieOne** [comment]
I am closing this issue as it appears to be resolve. If that is not correct, please feel free to comment and it will be reopened.
