### ISSUE TITLE
problem react transition group

### ISSUE THREAD

**Issue by dhanyn10** [reactstrap/reactstrap#455]
- version `4.6.2`
how to solve this problem?
![react-transition-group](https://cloud.githubusercontent.com/assets/11478316/26758445/44b78440-4908-11e7-8d82-0afdd230099c.png)

**Comment by virgofx** [comment]
The Readme explicitly how to install the package and peer dependencies. The website is out-of-date.

https://github.com/reactstrap/reactstrap#adding-bootstrap
```
npm install bootstrap@4.0.0-alpha.6 --save
npm install --save reactstrap react-transition-group react react-dom
```
