### ISSUE TITLE
Customize Components CSS

### ISSUE THREAD

**Issue by adamsaparudin** [reactstrap/reactstrap#457]
- version `#4.0.0-alpha.6`
- components: `-`

Is there any way to customize components global ? using scss or sass ? I was trying to customize components rather than direct edit it via class. on CSS.

**Comment by cr101** [comment]
I'm not sure I fully understand what you are asking but [adding the CSS preprocessor SASS](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc) to your project might help.

**Comment by adamsaparudin** [comment]
I was trying to change font using this code on CSS
`body {font-family: 'Roboto', sans-serif;}`

but it's not work as it should. I was meaning is there any default environment on reactstrap I can edit ?

I can do manual select component and change font-family individually but it's kinda not good things for me...

**Comment by TheSharpieOne** [comment]
Depending on which is included first, your style may be overridden by bootstrap's. Try setting it to `!important` or use a selector with more weight(such as `html>body`).

**Comment by TheSharpieOne** [comment]
Depending on which is included first, your style may be overridden by bootstrap's. Try setting it to `!important` or use a selector with more weight(such as `html>body`).

**Comment by FernandoBoza** [comment]
if you download the BS4 Source files, it comes included with the sass files, and within they included a _custom.scss partial so you can include and modify any custom bootstrap code. All you need to do is get the variables from the _variables partial AND move the custom.scss import to the very top when you compile the boostrap.scss [https://v4-alpha.getbootstrap.com/getting-started/options/](url)

**Comment by TheSharpieOne** [comment]
Closing this since it has not been active for over 30 days. Also this project doesn't include any styles itself.
This is more of a bootstrap question or issue. They have documentation https://v4-alpha.getbootstrap.com/getting-started/options/#content.
