### ISSUE TITLE
Popovers, tooltips, Dropdown doesn't close on iOS devices.

### ISSUE THREAD

**Issue by Arsolio** [reactstrap/reactstrap#458]
- version `#4.6.2`
- components: Popover, Tooltip, Drodown

How to reproduce:
- Open components with iPhone or iPad (iOS 10.3.1) in demo -> popover
- Open some popover
- Try to close it

Here my pull request: https://github.com/reactstrap/reactstrap/pull/456
I just added touchstart event in TetherContent and Dropdown components. Please check

**Comment by TheSharpieOne** [comment]
fixed in 9b80d11. Released in 5.0.0-alpha.1
