### ISSUE TITLE
Navbar with dropdown is not working properly

### ISSUE THREAD

**Issue by kprathapk** [reactstrap/reactstrap#459]
### Issue description
How to use NavDropdown along with Navbar, due to having two collapse states, this is not working properly, sorry I am new to React.
- version `#Latest`
- components: `Navbar, Nav`

### Steps to reproduce issue
Navbar component along with NavDropdown
- ...

**Comment by TheSharpieOne** [comment]
This question may be best for stackoverflow. Without seeing your code I cannot tell you what is happening.
