### ISSUE TITLE
Popover toggle does not work with target?

### ISSUE THREAD

**Issue by malikwas** [reactstrap/reactstrap#465]
So, I'm following the [Reactstrap docs example for Popovers](https://reactstrap.github.io/components/popovers/) and everything displays fine. However, the Popover component toggle does not work if I click on the target when it is open. The behaviour is such that it closes first because it thinks that the user is clicking away from the Popover, but then the `onClick` handler is fired immediately after on the target, so it reopens. What results is an action where the toggle does not work after the Popover is open.

Is there anyway to address this? You can test this out yourself for all examples in the docs I just linked.

**Comment by designbyadrian** [comment]
I have the same issue with reactstrap 4.6.2

**Comment by liubko** [comment]
`event.stopPropagation()` may work

**Comment by jrtilson** [comment]
This still appears to be an issue, anyone have a workaround?

**Comment by jrtilson** [comment]
My workaround if it helps anyone: 

```
componentDidMount() {
    document.addEventListener('click', this.handleDocumentClick, true);
}

...

handleDocumentClick(event) {
    // this._id is the id of the target element
    const targetElement = document.getElementById(this._id);
    if (event.target === targetElement && this.state.popoverOpen) {
        event.preventDefault();
        event.stopPropagation();
    }
}
```
