### ISSUE TITLE
Cannot bundle 'reactstrap' by 'browserify' because of 'reactstrap-tether'

### ISSUE THREAD

**Issue by fantasydr** [reactstrap/reactstrap#466]
Thanks for providing this awesome package which made my development much easier.

I got an issue related to 'reactstrap-tether'. I've also added a comment in https://github.com/HubSpot/tether/pull/175

It is caused by the tether.js forked in 'reactstrap-tether'.
Basically this tether.js will block browserify from bundling 'reactstrap', there will be an error:
```
Error: Cannot find module './utils' from .....
```

The workaround is ignore 'reactstrap-tether' from the bundling.
```javascript
bundle.ignore('reactstrap-tether');
//or command line
browserify -i reactstrap-tether ....
```
But the result will not have ToolTip or other components which used 'tether'.
It seems the webpack or 'create-react-app' could work with current 'reactstrap' setup without any issue.
I think it would be nice to let 'browserify' finish its job properly.

BTW, directly include './node_modules/reactstrap-tether/src/js/tether' won't work.
The 'import' and 'export' keyword will cause trouble. User must provide preset such as es2015.
Is it better to avoid using 'import/export' and keep the minimal dependency?

#438

**Comment by MarkRich** [comment]
yeah can't use reactstrap because of this. Any update would be appreciated.

**Comment by zekedroid** [comment]
+1

**Comment by und0ck3d** [comment]
+1

**Comment by zekedroid** [comment]
Given that Bootstrap has dropped tether in favor of popper.js, I wonder if we could make a release that makes this change to drop `reactstrap-tether` as a dependency

**Comment by TheSharpieOne** [comment]
reactstrap is working on making the change from tether to popper.js as well. See: https://github.com/reactstrap/reactstrap/issues/487#issuecomment-324473298
