### ISSUE TITLE
How to access files from input of type `file`

### ISSUE THREAD

**Issue by ryannealmes** [reactstrap/reactstrap#467]
This is more of a query,

I am struggling to figure out how to pull files from a file input

```javascript
<Input
                type="file"
                ref="attachments"
                onChange={this.onUploadFile}
/>
```
Is there something I am missing? When I inspect the attachments reference the only way I can get to it is if I dig down to `_reactInternalInstance` which I am guessing is the wrong way.

**Comment by TheSharpieOne** [comment]
`ref` doesn't get passed down to the `<input>` use `getRef` instead

**Comment by ryannealmes** [comment]
What does getRef do? Does that pass the actual input element within the react control?

**Comment by TheSharpieOne** [comment]
Yes, exactly.

**Comment by ryannealmes** [comment]
This solves my issue. Thanks.
