### ISSUE TITLE
DropdownItem should support "active" attribute

### ISSUE THREAD

**Issue by ened** [reactstrap/reactstrap#468]
As title, the "DropdownItem" component should probably be able to receive `active` (just like `disabled`), in order to show the bootstrap class.

**Comment by ened** [comment]
See #469

**Comment by TheSharpieOne** [comment]
This was added via [83df86ef] and [released](https://github.com/reactstrap/reactstrap/releases/tag/4.8.0) in [4.8.0](https://github.com/reactstrap/reactstrap/blob/master/CHANGELOG.md#480-2017-06-28).
