### ISSUE TITLE
File Size in 4.6.0 has jumped from 95kB to 335.6kB

### ISSUE THREAD

**Issue by balloob** [reactstrap/reactstrap#472]
### Issue description

Looks like the file size has tripled since release 4.6. I will spend some time later this week to see what caused it.

[4.5.0](https://unpkg.com/reactstrap@4.5.0/dist/) - 95.35kB:

![image](https://user-images.githubusercontent.com/1444314/27412332-c0ddeb74-56a8-11e7-850b-6e4acf5bec50.png)

[4.6.0](https://unpkg.com/reactstrap@4.6.0/dist/) - 335.6kB:

![image](https://user-images.githubusercontent.com/1444314/27412329-b85b4b4a-56a8-11e7-9ab1-1076d746e431.png)

**Comment by balloob** [comment]
So it looks like the build that is published to npm wasn't generated using `npm run build` or `yarn build`. Just checked it out locally and all seems fine.

![image](https://user-images.githubusercontent.com/1444314/27453967-13c9bcce-574d-11e7-817e-3635d830b0b8.png)

**Comment by joseluisq** [comment]
v4.6.2
![image](https://user-images.githubusercontent.com/1700322/27509541-d4872150-58ff-11e7-8520-0d3802376474.png)

**Comment by balloob** [comment]
@joseluisq the fix has been merged and will even be a little smaller in now that #478 has been merged. Even smaller when #477 is merged 👍

**Comment by joseluisq** [comment]
@balloob amazing!
I await for the next release!

**Comment by eddywashere** [comment]
released in 4.8.0

**Comment by joseluisq** [comment]
:+1:
