### ISSUE TITLE
cdn subresource integrity

### ISSUE THREAD

**Issue by ggerber** [reactstrap/reactstrap#476]
Is there a cdn link available that allows for subresource integrity?

**Comment by TheSharpieOne** [comment]
unpkg, which is the only CDN listed on the docs doesn't support SRI (AFAIK) and that can cause an issue (see: https://news.ycombinator.com/item?id=14111499)
I have created a request and a PR with cdnjs to add reactstrap to their CDN, which does support SRI.

**Comment by ggerber** [comment]
great news! thank you

On 28 Jun 2017 6:57 p.m., "Evan Sharp" <notifications@github.com> wrote:

unpkg, which is the only CDN listed on the docs doesn't support SRI (AFAIK)
and that can cause an issue (see: https://news.ycombinator.com/
item?id=14111499)
I have created a request and a PR with cdnjs to add reactstrap to their
CDN, which does support SRI.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/reactstrap/reactstrap/issues/476#issuecomment-311722232>,
or mute the thread

**Comment by ggerber** [comment]
Hi,
I use the current reactstrap npm module with the react/react-dom/react-router-dom library links below.
However, it looks like the reactstrap npm module requires the react-transition-group npm module.
Will the new reactstrap cdn work without the react-transition-group npm module or is there a cdn link for react-transition-group as well?

  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react.min.js" integrity="sha256-ivdPAn5h6U67z6OPgwfiLM9ug6levxmYFqWNxNCV0YE=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react-dom.min.js" integrity="sha256-UEqn5+tyzezD6A5HBMNTlc5mXkmt+ohTfCBPtXMaGb0=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react-router-dom/4.1.1/react-router-dom.min.js" integrity="sha256-rHZKWvuytV/U6FmleC31neSgHS78pzsgr8w1qCpnBvc=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

**Comment by TheSharpieOne** [comment]
react-transition-group is needed; it is not included in the umd bundle which is on the cdn. I am not sure if react-transition-group is in cdnjs or not (I cannot easily check at the moment), but if it isn't you can open a request (issue) with them to add it. 
Also cdnjs just makes it super easy to use SRI by providing the hash, but you can determine the hash yourself and use any CDN which has CORS support (unpkg.com may have that, I cannot check at the moment). Check out https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by ggerber** [comment]
I have opened a request on cdnjs for react-transition-group.
In the meantime I found that unpkg has a cdn. I am using the unpkg links of
reactrstrap and react-transition-group at the moment. My pages work, except
for those that contain an Alert element.
I get this error: Uncaught TypeError: Cannot read property
'CSSTransitionGroup' of undefined
    at zo (Alert.js:71)
In my browser I have React and ReactTransitionGroup objects. How do I get
Alert to use ReactTransitionGroup.CSSTransitionGroup?

**Comment by virgofx** [comment]
@ggerber Reactstrap is now available via cdnjs thanks to @TheSharpieOne. 

https://cdnjs.com/libraries/reactstrap

I'll send a PR this weekend which updates the documentation website for the CDN to use CDNJS instead of unpkg (Even though the backends are the same we want end users to use the same frontend for optimal edge caching) as well as add that information in the readme.
