### ISSUE TITLE
static prop on Input component

### ISSUE THREAD

**Issue by corydeppen** [reactstrap/reactstrap#485]
While this is related to a TypeScript definition file, I wanted to submit the issue here since a change may need to be made in this repo before the definition is updated (+1 for [co-locating definitions](https://github.com/reactstrap/reactstrap/issues/276) in this repo).

As the [comment](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/reactstrap/lib/Input.d.ts#L41-L42) in the `Input` definition file states, `static` is a keyword in both JS and TS and therefore cannot be used as a property in the `InputProps` interface. As a result, folks need to use the `form-control-static` class in their components. That's obviously not the end of the world, but I think it's safe to assume using a prop is preferable.

I wanted to see if there were any ideas about whether there'd be a way to support this by using a non-reserved word as a prop.

/cc  @alihammad @mfal @danilobjr

**Comment by TheSharpieOne** [comment]
>As a result, folks need to use the form-control-static class in their components

No, that is incorrect. Yes, `static` is a keyword, but it is allowed as a property on an object; same as other keywords (`default` is used a ton). It may need to be quoted, but JSX takes care of that. Here is an example: https://www.webpackbin.com/bins/-Kq0mBkPJ_V09tCYsL7_

Here is the transpiled markup.
```
_createClass(ReactstrapExample, [{
    key: 'render',
    value: function render() {
      return _react2.default.createElement(
        _reactstrap.Container,
        { className: 'py-4' },
        _react2.default.createElement(
          _reactstrap.Input,
          { 'static': true },
          'Static prop works just fine'
        )
      );
    }
  }]);
```
This sounds like a limitation of TypeScript, a defect should probably be opened with them.

**Comment by corydeppen** [comment]
The JS output from TypeScript looks almost identical to what Babel produces, with the exception of the reserved word not being quoted (still valid JS, though, as you mentioned). Seems like the problem is that TypeScript throws when reserved words are used as props in TSX files. Hopefully Microsoft/TypeScript#17452 will provide clarity and potential solution.

**Comment by TheSharpieOne** [comment]
Looks like this will be fixed upstream. A PR has been merged, just waiting for a new release. It looks to be slated for TypeScript 2.5 based on the milestone.

**Comment by TheSharpieOne** [comment]
Bootstrap v4 beta change this to `plaintext` . reactstrap will follow suite, but probably keep (and depracate) `static` for a little.

**Comment by TheSharpieOne** [comment]
I made the prop change I mention before. Also TypeScript 2.5 has been release which should have a fix on their end.
