### ISSUE TITLE
Nginx gateway timeout on linked "demo here" from https://reactstrap.github.io/ main page

### ISSUE THREAD

**Issue by ssteinerx** [reactstrap/reactstrap#489]
July 2, 2017 -- 9:41:17 AM (EST)

Gateway timeout trying to visit demo linked from https://reactstrap.github.io/ main page at the "check out demo here" link right after CDN section.

https://output.jsbin.com/dimive/latest

**Comment by TheSharpieOne** [comment]
jsbin doesn't seem to be reliable enough. We might want to switch to webpackbin or something else (Note: react uses codepen for their tutorial).

**Comment by supergibbs** [comment]
Seems to be working now but also really out of date
