### ISSUE TITLE
Dropdown context issue

### ISSUE THREAD

**Issue by haroldcb** [reactstrap/reactstrap#496]
### Issue description
Hello,
I made a component, that creates a list of dropdowns dynamically, and in the dropdowns, a dynamical list of DropdownItems (checkbox inputs).
Everything worked fine when I had one instance of the component, but when I tried to add another one, a click on the second dropdown , the first one opens (the toggle function of the NavDropDown is called for no reason...). I guess it's due to the context, but I'm not sure and I don't know how to fix it...

- version `#4.8.0`
- components: NavDropdown, DropdownToggle

### Code :

```
{filterList && filterList.map(list =>
      (
          <Col xs="12" sm="auto" key={list.code} className="hidden-sm-down">
                      <FormGroup>
                        <Nav pills className=" nav-fill">
                          <NavDropdown name={list.libelleFiltre}>
                            {list && list.values && list.values.map(item =>
                                <DropdownItem key={item.id} tag="span">
                                  <Input
                                      type="checkbox"
                                      name={item.id}
                                      id={item.libelle + "-search"}
                                      value={item.libelle}
                                  />
                                  <Label for={item.libelle + "-search"}>{item.libelle}</Label>
                                </DropdownItem>
                            )}
                          </NavDropdown>
                        </Nav>
                      </FormGroup>
                    </Col>
         ))}
```

NavDropdown Component render (state is handled just like in the examples) : 

```
<NavDropdown isOpen={this.state.dropdownOpen} toggle={() => this.toggle()}
                        className="NavDropdown">
          <DropdownToggle caret nav>
            {this.props.name} <Badge number>{this.props.number}</Badge>
          </DropdownToggle>
          <DropdownMenu>
            {this.props.children}
          </DropdownMenu>
</NavDropdown>
```

If anyone could help me with this, it would be great. How to make the 2 instances of the component act separately?

**Comment by TheSharpieOne** [comment]
The easiest way to do this is to use `UncontrolledDropdown` instead and do __not__  pass it `isOpen` or `toggle` (it will handle that for you).

**Comment by haroldcb** [comment]
Hello,
thanks for your answer, I tried it too, but it didn't worked...

**Comment by TheSharpieOne** [comment]
You'll probably need to show all of your code for the relevant components (the whole component). You can create a webpackbin or something similar to share it.

**Comment by haroldcb** [comment]
Hello again,
I created a create-react-app project, and I reproduce my case quite easily (see the zip attached, just 2 files added).
If you could help me it would be perfect :)

[testapp.zip](https://github.com/reactstrap/reactstrap/files/1139124/testapp.zip)

**Comment by TheSharpieOne** [comment]
The dropdowns work independently for me: https://www.webpackbin.com/bins/-KomAdSlYbqeZrQZYyqc

**Comment by haroldcb** [comment]
Ok maybe I explained wrongly i'm sorry ;)
For example on your WepackBin (this is exactly my problem) : if you open the dropdown2, and then select any of the items, the dropdown2 closes, and the dropdown1 opens with the selected item...
Do you see the same behavior?
What I want it that when you select an item from the dropdown2, the dropdown2 stays open with the selected item. Is this possible?
Thanks in advance :)

**Comment by TheSharpieOne** [comment]
The reason the other dropdown is opening an has the selected dropdown is because the checkboxes are not unique. The name of the checkbox (`name` prop) ends up being duplicated because of the map/loop. Adding the map/loop index to the name helps make it unique and solves that issue. keys (`key` prop) also end up being duplicated, which is not allowed by react. This is probably because the dataset which generates these items itself was just copied and pasted.

As for the other thing, keeping the dropdown open after the checkbox is clicked, you can stop the event from propagating to the dropdownitem which will prevent the dropdown from toggling closed.

I updated the [webpackbin](https://www.webpackbin.com/bins/-KomAdSlYbqeZrQZYyqc) so show these changes.
Also, here is a gif:
![reactstrap-dropdowns-checkboxes](https://user-images.githubusercontent.com/664714/28078505-15b71a50-6633-11e7-8432-9218e3179730.gif)

**Comment by haroldcb** [comment]
Ok thank you so much!
The data is the same because it comes from webservices and is stored in the redux-store.
I thought the problem was on the dropdown so I didn't check the inputs.

Thank you for your time :)

**Comment by haroldcb** [comment]
@TheSharpieOne one more question : do you have an idea to prevent the dropdown from closing, whether you click exactly on the checkbox (working fine), but also on the label, or the entire DropdownItem "span" area?
I tried to sop the event from propagating  on each of the components, but no success...
Thanks in advance :)

**Comment by TheSharpieOne** [comment]
I changed the span to be a label since label has the ability to toggle the checkbox when clicked and moved the noBubble onClick to that. I also added `pointerEvents :none` the checkbox itself to allow the click on the checkbox to just pass through to the label.

The webpackbin has been updated: https://www.webpackbin.com/bins/-KomAdSlYbqeZrQZYyqc
And here is a gif demo:
![reactstrap-dropdowns-checkboxes](https://user-images.githubusercontent.com/664714/28128731-ba71b1e2-66fe-11e7-9b0f-002135a6e24e.gif)

**Comment by TheSharpieOne** [comment]
@haroldcb: Apparently there is a `toggle` prop on the `DropdownItem` which can be used to prevent the default toggle from being triggered when set to `false`. That is probably better to use than preventing the bubble.
Here is an example of that: https://www.webpackbin.com/bins/-Kput64BMivF-SpzMkIc

**Comment by frankhale** [comment]
Would like to look at the example code but the links are dead =(

**Comment by TheSharpieOne** [comment]
Here is the code from the link:

This is just a sample, it may not be production quality code. The sample code is also old and there may be better ways to do it with newer react and reactstrap versions.

https://webpackbin-prod.firebaseapp.com/bins/-Kput64BMivF-SpzMkIc

```jsx
import React from "react";

//componennts
import NavDropdown from './NavDropdown';

//reactstrap
import {Row, Col, Nav, Label, Form, FormGroup, DropdownItem, Input} from 'reactstrap';

const filterList = [
    {
      codeFiltre: 'capacity',
      libelleFiltre: 'capacity',
      values: [
          {
            id: '0',
            libelle: '0 - 500 '
          },
          {
            id: '1',
            libelle: '500 - 1500 '
          },
          {
            id: '2',
            libelle: '1500 - 5000 '
          },
          {
            id: '3',
            libelle: '+ 5000 '
          }
        ]
    },
  
    {
      codeFiltre: 'capacity 2',
      libelleFiltre: 'capacity 2',
      values: [
          {
            id: '0',
            libelle: '0 - 500 '
          },
          {
            id: '1',
            libelle: '500 - 1500 '
          },
          {
            id: '2',
            libelle: '1500 - 5000 '
          },
          {
            id: '3',
            libelle: '+ 5000 '
          }
        ]
    }
];

class SearchForm extends React.Component {

  render() {
    return (
        <Form>
          <Row grid gutters="xs" flexWrap="nowrap">
            {filterList && filterList.map((list, i) =>
                (
                    <Col xs="12" sm="auto" key={`${i}-${list.codeFiltre}`}>
                      <FormGroup>
                        <Nav pills className="nav-fill">
                          <NavDropdown name={list.libelleFiltre}>
                            {list && list.values && list.values.map((item, index) =>
                                <DropdownItem key={`${i}-${index}-${item.id}`} tag={Label} for={`${i}-${index}-${item.id}`} toggle={false}>
                                    <Input
                                      type="checkbox"
                                      name={`${i}-${index}-${item.id}`}
                                      id={`${i}-${index}-${item.id}`}
                                      value={item.libelle}
                                      style={{pointerEvents:'none'}}
                                      /> {item.libelle}
                                </DropdownItem>
                            )}
                          </NavDropdown>
                        </Nav>
                      </FormGroup>
                    </Col>
            ))}
          </Row>
        </Form>
    );
  }
}

export default SearchForm;
```
NavDropdown:
```jsx
import React from 'react';

//Reactstrap
import {DropdownToggle, DropdownMenu, UncontrolledNavDropdown as LibNavDropdown} from 'reactstrap';


class NavDropdown extends React.Component {
  render() {
    const filteredProps = {...this.props};
    delete filteredProps.number;
    delete filteredProps.name;

    return (
        <LibNavDropdown {...filteredProps} className="NavDropdown">
          <DropdownToggle caret nav>
            {this.props.name}
          </DropdownToggle>
          <DropdownMenu>
            {this.props.children}
          </DropdownMenu>
        </LibNavDropdown>
    );
  }
}

export default NavDropdown;
```
