### ISSUE TITLE
Alert Doesn't Work

### ISSUE THREAD

**Issue by asifsaho** [reactstrap/reactstrap#498]
<img width="1026" alt="screenshot 2017-07-13 21 36 39" src="https://user-images.githubusercontent.com/2722232/28174498-806770ca-6813-11e7-8e45-11e2ebaea8a4.png">

**Comment by TheSharpieOne** [comment]
dupe #493
Fix summary: use react-transition-group v1.2.0; react-transition-group v2 does not currently work.

**Comment by asifsaho** [comment]
It worked, thank you for your kind help :)

**Comment by asifsaho** [comment]
It worked, thank you for your kind help :)
