### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by akatebi** [reactstrap/reactstrap#50]
Hi Eddy,
   
You have done a fantastic job with this package. Any ideas when Forms and other components will become available? 

Thanks so much!
Alex

**Comment by eddywashere** [comment]
Thanks! I'm kind of prioritizing stuff based on my personal usage. Right now I'm working on some React 15.2 warnings around unknown props.

I think I kind of dropped the ball on a good contributing section to help enable folks to submit issues/prs for adding and requesting components. Once I get a prioritized list I'll update this issue and add some rough timelines to components.

**Comment by TheSharpieOne** [comment]
Forms are in release 2.1.0
