### ISSUE TITLE
close popover on focusOut/ mouseLeave event

### ISSUE THREAD

**Issue by epetrashen** [reactstrap/reactstrap#500]
I need my popover to open on hover and to close when the mouse focus is out of it (it contains some menu options so user is supposed to be able to click them). However, when I try using onMouseLeave/onFocusOut ot outer div to close it, it does not let me lead the cursor inside popover's body, closing it as soon as it's not focused on the button.

Here is a working codepen: https://codepen.io/anon/pen/jwJwXW

Is there a known workaround for this issue maybe? Thanks!

- version `#4.8.0`
- components: `Popover`

**Comment by TheSharpieOne** [comment]
reactstrap's fork of tether doesn't contain HubSpot/tether#204 which would allow you to specify the popover to be within the div. I am not sure if it is possible using your current method of `onMouseEnter` and `onMouseLeave` without that ability.

**Comment by epetrashen** [comment]
Thanks for your reply @TheSharpieOne!  Do you maybe know if there is some other not-too-invasive way to get this kind of behavior from a reactstrap popover - so that it would only be open while user hovers over it and closes when the focus is out?

**Comment by TheSharpieOne** [comment]
Depending on if you need to have the ability to select the text in the popover, you can use `pointer-events: none` on the popover to make the hover of the popover not hover the popover... You'd also need to add some extra space to ensure the popover appears within the div have the enter and leave triggers on.
It's pretty simple and looks something like this: https://codepen.io/anon/pen/awMMzN

Other than that, something with timeouts and clearing timeouts which ends up looking like this: https://codepen.io/anon/pen/YQggwr

**Comment by epetrashen** [comment]
thanks for your advice! the second solution worked perfectly for my case.
