### ISSUE TITLE
Popover 'bottom right' placement issue

### ISSUE THREAD

**Issue by jonnyojonny** [reactstrap/reactstrap#501]
### Issue description
Hey team, could you please check 'bottom right' ('bottom left') placements for the Popover component. Arrow between popover and target looks broken! Can i fix it somehow without diving into the sources? Thanks in advance!

### Steps to reproduce issue
https://codepen.io/anon/pen/MoRemW

- version 
  "react": "^15.3.0",
   "react-dom": "^15.3.0",
   "react-transition-group": "^1.1.2",
   "reactstrap": "^4.8.0"
   "bootstrap": "^4.0.0-alpha.6"
- components: Popover

**Comment by stefan-schweiger** [comment]
Duplicate of https://github.com/reactstrap/reactstrap/issues/114

**Comment by TheSharpieOne** [comment]
Closing as duplicate of #114. Please use the original issue to track the status.

**Comment by TheSharpieOne** [comment]
Closing as duplicate of #114. Please use the original issue to track the status.
