### ISSUE TITLE
react-transition-group 2.x causes an unknown props error on Modal open

### ISSUE THREAD

**Issue by will-stone** [reactstrap/reactstrap#502]
### Issue description

- version `#4.8.0`
- components: `modal`

### Steps to reproduce issue

- Install react-transition-group 2.1.0.
- Open a Modal
```
Warning: Unknown props `onExited`, `appear`, `enter`, `exit` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Fade)
    in Fade
    in div (created by TransitionGroup)
    in TransitionGroup
```
Downgrading to 1.2.0 fixes the problem.

**Comment by TheSharpieOne** [comment]
The peerDep doesn't allow react-transition-group 2.x. The readme installation instructions was also updated to explicitly show how to install reactstrap and its peerDeps with versions.
react-transition-group 2 completely changed the API so it is not compatible.

**Comment by will-stone** [comment]
Ah, I was using the install instructions from the website; this'll need updating too. Any plans to fix for the new version? Or use a different solution? I can just imagine people will want to use the latest version of packages if they can.

**Comment by virgofx** [comment]
Readme is up-to-date. The website is having issues pushing new changes now and is a work in progress with new changes. Supporting 2.0 is pretty straight forward and will get implemented in a PR soon.

**Comment by will-stone** [comment]
Awesome. Thanks!

**Comment by Phainix** [comment]
Also experiencing the same issue, Downgrading react-transition-group to 1.2.0 solved the error. Will be looking forward to 2.0 support. Great job @reactstrap team.

**Comment by micahalcorn** [comment]
I'm getting `Unknown prop 'onOpened' on <div> tag. Remove this prop from the element.` with the following installation:

react-15.6.1
react-dom-15.6.1
react-transition-group-1.2.0
reactstrap-4.8.0

```
import React from 'react';
import { Button, Form, FormGroup, FormText, Input, Modal, ModalBody, ModalFooter, ModalHeader, Label } from 'reactstrap';

export default class MyModal extends React.Component {
  constructor(props) {
    super(props);
  }

  ...

  render() {
    const { open, toggleModal } = this.props;

    return (
      <Modal isOpen={open} toggle={toggleModal} onOpened={() => alert('opened')}>
        ...
      </Modal>
    );
  }
}
```

As a result, I don't see the alert. Any suggestions?

**Comment by TheSharpieOne** [comment]
@micahalcorn your issue is completely unrelated; you should have opened a new issue. But the solution for your issue is to remove `onOpened`.
While onOpened has been recently added/merged, it has not been released.

**Comment by micahalcorn** [comment]
@TheSharpieOne sorry, I thought it would be best to avoid clutter with redundant issues. I also could have sworn that I saw the `onOpened` code in my local installation, but I see now that I was mistaken, thanks.

**Comment by TheSharpieOne** [comment]
I guess I can see the relation a little, but this issue is specificly with react transition group 2.x. #434 added the prop your using, should be in the next release.

**Comment by neginbasiri** [comment]
I have the same issue when I trie to have animation when a list gets rendered

warning.js:36 Warning: Unknown props `onExited`, `appear`, `enter`, `exit` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by TripFilteredList)
    in div (created by TransitionGroup)
    in TransitionGroup (created by TripFilteredList)
    in div (created by TripFilteredList)
    in TripFilteredList (created by TripSortedList)
    in div (created by TripSortedList)
    in TripSortedList (created by TripFinder)
    in div (created by TripFinder)
    in TripFinder

            import TransitionGroup from 'react-transition-group/TransitionGroup';

            <TransitionGroup component="div" childFactory={child => child} >
                <div className={`cards ${display === 'other' ? 'search-results__other-content' : ''}`}>

                    {display === 'row' &&
                        tripFilteredList.map((data, index) => <TripRow key={index} {...data} />)
                    }

                </div>
            </TransitionGroup>

**Comment by neginbasiri** [comment]
I am getting the same warning on TransitionGroup. I try to add animation when items adding/removing from a list.

**Comment by TheSharpieOne** [comment]
Update react transition group WIP (Thanks to @amikhalev) being tracked by: #557
