### ISSUE TITLE
Col adding 'col' class to all col elements - breaks responsive breakpoints

### ISSUE THREAD

**Issue by jonbnewman** [reactstrap/reactstrap#506]
The default codepen even displays this issue: http://codepen.io/eddywashere/pen/ZOjmkm

For example the responsive breakpoints will not work on something this simple:

```
<Row>
  <Col md={3}>1</Col>
  <Col md={3}>2</Col>
  <Col md={3}>3</Col>
  <Col md={3}>4</Col>
</Row>
```

...because the rendered element comes out as:

```
<div class="row">
  <div class="col col-md-3">1</div>
  <div class="col col-md-3">2</div>
  <div class="col col-md-3">3</div>
  <div class="col col-md-3">4</div>
</div>
```

...that will not work, for the breakpoints to work each `<Col />` must be rendered like this:

```
<div class="row">
  <div class="col-md-3">1</div>
  <div class="col-md-3">2</div>
  <div class="col-md-3">3</div>
  <div class="col-md-3">4</div>
</div>
```

...perhaps I am missing something entirely but I don't see this working on any examples out of the box...and I will have to fork this project to fix this if I want to use it right now - far as I can see.

I can submit a PR to remove the default `col` class if wanted?

**Comment by eddywashere** [comment]
Hey @jonbnewman, did you close because you found a solution? Feel free to post it to help others. I was going to suggest applying the first break point xs={3} and only adding another when it needs to be overridden. The Col component has a full column fallback as an out of the box experience.

**Comment by jonbnewman** [comment]
I opened it again with example @ #507
