### ISSUE TITLE
Close <Collapse> when user clicks outside of it

### ISSUE THREAD

**Issue by amitsch666** [reactstrap/reactstrap#515]
I have implemented reactstrap's Navbar with a slight customization to the Collapse component. This customization allows me to have the navigation pane slide in/out from the side instead of the top in mobile view. Is there any way to trigger the close event when any area outside of the Collapse component is clicked/tapped? My repo is hosted at https://github.com/amitsch666/nano and my Navbar component looks like this:

```
<Navbar color="inverse" inverse toggleable={`md`} fixed={`top`} className={this.state.fatnav}>
  <NavbarToggler right onClick={this.toggle} />
  <NavbarBrand href="/">
    <img src="/static/img/logo.svg" class="d-inline-block align-top" alt="TaleSpinners logo" />
    <span id="tale">Tale</span><span id="spinners">Spinners</span>
  </NavbarBrand>
  <Collapse isOpen={this.state.isOpen} navbar delay={{show: 0, hide: 350}}>
    <div id="collapse-nav-head">
      <div id="collapse-nav-title" className="p-2">TaleSpinners</div>
      <Button outline color="secondary" onClick={this.toggle} className="m-auto"><span aria-hidden="true">&times;</span></Button>
    </div>
    <Nav className="ml-auto" navbar>
      <NavItem>
        <NavLink href="/browse">Browse</NavLink>
      </NavItem>
      <NavItem>
        <NavLink href="/community">Community</NavLink>
      </NavItem>
      <NavItem>
        <NavLink href="/login">Sign In</NavLink>
      </NavItem>
    </Nav>
  </Collapse>
</Navbar>
```

As of now, the only way to close the pane is by clicking the custom close button inside of it.

**Comment by NamanAulakh** [comment]
same issue

**Comment by TheSharpieOne** [comment]
This is more of a question for stackoverflow than an issue with reactstrap. The feature/functionality you are wanted does not exist in bootstrap and thus does not exist in reactstrap. That said, it is simple enough to handle this in your code.

When the nav opens, you attached a click (and touchstart) capture listener to the document with a callback of something like `this.handleDocumentClick` which you will create (`document.addEventListener('click', this.handleDocumentClick, true);`)

You will need a reference to a DOM element which wraps your render (add a `<div>` around your render's output, `<div ref={(c)=> (this._element = c)}>...your nav stuff...</div>`)

`handleDocumentClick` looks something like this (don't forget to bind it to the `this` of your component and **do not bind inline** (do it in the constructor or use an arrow function when defining it):
```javascript
  handleDocumentClick(e) {
    const container = this._element;
    if (e.target !== container && !container.contains(e.target)) {
      this.toggle();
    }
  }
```

This checks that the event was not triggered inside the container and then calls a toggle method which will close the nav.

When your nav closes, you need to remove the listener you added (`document.removeEventListener('click', this.handleDocumentClick, true);`) Note: You will also want to make sure you remove the listener when the component unmounts (in `componentWillUnmount`) to avoid leaks.

**Comment by NamanAulakh** [comment]
@TheSharpieOne This works fine, thanks.

**Comment by robertlagrant** [comment]
@TheSharpieOne, @NamanAulakh can this be closed?

Passing stranger who thought lowering the list of issues by 1 might be nice for the devs :-)

**Comment by NamanAulakh** [comment]
@robertlagrant yes, it can be closed.

**Comment by Maxim-Mazurok** [comment]
> ```js
>   handleDocumentClick(e) {
>     const container = this._element;
>     if (e.target !== container && !container.contains(e.target)) {
>       this.toggle();
>     }
>   }
> ```

No need to check that `e.target !== container`. Just `!container.contains(e.target)` should suffice, because:

> The Node.contains() method returns a boolean value indicating whether a node is a descendant of a given node, i.e. **the node itself**, one of its direct children (childNodes), one of the children's direct children, and so on.
([source](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains))
