### ISSUE TITLE
export 'default' (imported as 'rs') was not found in 'reactstrap'

### ISSUE THREAD

**Issue by amirouche** [reactstrap/reactstrap#517]
I would like to import to whole reactstrate module as a single variable in my project. For instance,

```javascript
import rs from 'reactstrap';
```

And then use it like that:

```jsx
var Input = function({label, text, error, onChange}) {
  var state, feedback;
  if (error) {
    state = "danger";
    feedback = <rs.FormFeedback>{error}</rs.FormFeedback>;
  } else {
    state = undefined;
    feedback = '';
  }
  
  return (
    <rs.FormGroup color={state}>
        <rs.Input state={state} />
        {feedback}
        <rs.FormText color="muted">{text}</rs.FormText>
    </rs.FormGroup>
  );
}
```

But CRA fails to compile with the title message. I already do that for other javascript modules that exports things using the following syntax:

```js
export default {
  Link,
  Router,
  Title,
  clean,
  createApp,
  redirect,
  saveAs,
  fromJS,
};

```

**Comment by TheSharpieOne** [comment]
I believe the components must start with an uppercase letter thus you must use something like `Rs`. I'm not sure if this is a convention or a rule, but this is why all of gherkin components start with an uppercase letter. Only DOM elements can be lowercase, like div and span.

**Comment by amirouche** [comment]
> I believe the components must start with an uppercase letter thus you must use something like Rs.

That's not the case (anymore). I use that syntax for other components it work well.

**Comment by TheSharpieOne** [comment]
Are there any error messages? Can you create an example demonstrating this issue on webpackbin? (I am on my mobile right now so I cannot.)

**Comment by amirouche** [comment]
I don't know what to do with webpackbin.

I looked up `reactstrap/dist/reactstrap.es.js` file and it seems to me that if the last line was:

```js
export default { Alert, .... };
```

Instead of 

```js
export { Alert, .... }
```

**My** usecase will work correctly.

No hurry, you can also reject that issue if you don't see the point of importing things that way.

**Comment by TheSharpieOne** [comment]
I wonder if exporting both as default and how it currently is would work for everyone. I also wonder if that would affect the tree shaking for people who only want to include what they reference.

**Comment by TheSharpieOne** [comment]
@balloob do you foresee this proposed way of exporting causing any issues with importing and tree shaking?

**Comment by balloob** [comment]
I would need to look into it if it breaks tree-shaking.

However, I don't think that we should add a default support. Instead, the JavaScript spec allows to group all imports under an object like this:

```js
import * as rs from 'reactstrap';
```

**Comment by balloob** [comment]
Do note that when you use it like this, you will not be able to leverage tree shaking in your library.

**Comment by TheSharpieOne** [comment]
@amirouche does [balloob's suggestion](https://github.com/reactstrap/reactstrap/issues/517#issuecomment-321070745) work for you?

**Comment by amirouche** [comment]
Yes, it works. Thanks.

**Comment by yjadhav** [comment]
I have following scenario 

I have one store for example **TestStore.js**

TestStore.js:

function TestStore() {
   async function NestedAsyncFunction(){
    /* Logic*/
   }
}

module.export=TestStore()

Now i am using this store in my component like this

TestComponents.jsx:
     import TestStore from 'TestStore';

I am getting following error
TestComponents.jsx
44:26-37 **"export 'default' (imported as 'TestStore') was not found in 'TestStore'**
