### ISSUE TITLE
Modal not functioning as expected

### ISSUE THREAD

**Issue by graphical-iain** [reactstrap/reactstrap#518]
### Issue description
- Clicking the backdrop or esc does not close the modal.
- Focus is put on the modal container, not the modal itself. This causes screen readers to not read the content of the modal.

Adding something like the following causes the screenreader to read the content, but I don't want to actually put this in my code:
```
onEnter={()=>{ setTimeout(function() { $(".modal-dialog").attr("tabIndex", "-1").focus(); }, 1000); }}
```

- version `#4.8.0`
- components: `Modal`

**Structure of my modal:**
```
<Modal isOpen>
	<ModalHeader>Selector</ModalHeader>
	<ModalBody>
		<p>Some Text</p>
	</ModalBody>
	<ModalFooter class="d-flex justify-content-between align-items-center">
		<Button onClick={this.close}>Close</Button>
		<Button onClick={this.accept}>Accept</Button>
	</ModalFooter>
</Modal>
```

I tried to fork the codepen, but TransitionGroup cannot be included, and therefor trying to open a modal throws an error.

**Comment by TheSharpieOne** [comment]
> Clicking the backdrop or esc does not close the modal.

This is because you are responsible for creating a toggle method which is called when the backdrop is clicked and/or the esc key is pressed. This toggle method should toggle the `isOpen` prop (from `true` to `false`). Currently, you are hard-coding the `isOpen` prop to `true` (by not giving it a value when passing it to `Modal`) so the modal will always be open.

> Focus is put on the modal container, not the modal itself. This causes screen readers to not read the content of the modal.

Does bootstrap v4 itself not have this issue? I ask, because bootstrap's modal also focus on the modal container (`.modal`), same as reactstrap. We may need to add some accessibility attributes (such as `role="dialog"`) which bootstrap's examples have.

**Comment by graphical-iain** [comment]
> you are responsible for creating a toggle method
Is there an example of the implementation of the toggle method? I can't find that in the documentation. 
According to the BS4 documentation, with the default settings it should close when the backdrop is clicked or esc is pressed: http://v4-alpha.getbootstrap.com/components/modal/#usage

> Does bootstrap v4 itself not have this issue?
Nope. Tested it with the demo on the documentation page, and the screen reader announces the modal correctly. I believe it's the combo of role="dialog" and aria-labelledby="{ID OF TITLE}" that makes it work.

**Comment by TheSharpieOne** [comment]
> Is there an example of the implementation of the toggle method? I can't find that in the documentation.

Yes, every example on https://reactstrap.github.io/components/modals/ has toggle which is a simple function that toggles a boolean value

```javascript
  toggle() {
    this.setState({
      modal: !this.state.modal
    });
  }
```

the `toggle` method (bound to `this`) is then provided, along with the `this.state.modal` to the `Modal` component:

```jsx
<Modal isOpen={this.state.modal} toggle={this.toggle} className={this.props.className}>
  ...
</Modal>
```

When `this.state.modal` is `true`, the modal will appear, when it is `false` is will not appear.
By default, `toggle` is called by the `Modal` component when esc is pressed or the backdrop is clicked.

**Comment by graphical-iain** [comment]
Oh! I didn't even look at the code examples (doh). I was looking for a list of options/properties. Thanks!

**Comment by TheSharpieOne** [comment]
Thinking about accessibility, I can easily add `role="dialog"` to the modal, I cannot think of a simple way without using context to automatically get the `aria-labelledby` to be the id of the title. For that, I think leaving it up to the user is the best course of action (especially seeing how adding both of these attributes is left up to the user in bootstrap itself)
Thus, I will add a `role` (to be able to override the default which will be set to "dialog") and `labelledBy` to the `Modal`. Does that sounds right/reasonable?

**Comment by graphical-iain** [comment]
So since the title is generated by the ModalHeader component, would you not be able to reference that ID as the aria-labelledby value?

**Comment by TheSharpieOne** [comment]
`Modal` knows nothing about it's children's prop, including the `ModalHeader` which doesn't even have to be included. While it would be possible to use context achieve this, I don't believe it would be the proper use of contexts. That plus a pure bootstrap user would have to manually add it to their modals, I don't think it would be that big of a deal.
