### ISSUE TITLE
Tooltips need a hover delay before displaying

### ISSUE THREAD

**Issue by bostondevin** [reactstrap/reactstrap#520]
### Issue description

- version `#4.8.0`
- components: `ToolTip`

### Steps to reproduce issue
Hover quickly over an element with a tooltip - the tooltip shows up when it shouldn't
- ...

There are usually mouseover delays of a few hundred milliseconds before deciding whether to show the tooltip or not - same as in NavBar navigation - this prevents flickery interfaces when the user is moving the mouse around. It would be nice if this was a tooltip setting that could be modified. If the user is hovered over something for more than a few hundred milliseconds, we can assume they are interested in it, otherwise ignore it.

**Comment by TheSharpieOne** [comment]
There is a delay prop which you can pass a number (or object with {show, hide} values to have different delays for showing and hiding). These values represent the how long to wait/delay (in milliseconds) before showing and hidden the tooltip. It is similar to bootstrap's delay property for tooltip. Also similarly to bootstrap, the delay defaults to 0 (currently only the show delay is 0, there is a PR to correct the hide delay to be 0 be default to match bootstrap itself).

**Comment by TheSharpieOne** [comment]
closing this issue as it appears to be resolved and is no longer active. If this is not the case, feel free to reopen with more details.

**Comment by krupalox** [comment]
With this configuration that can be done.
delay={{ "show": '250', "hide": '0' }}

**Comment by NSegal** [comment]
Thanks Krupalox! This worked for me: 
<UncontrolledTooltip delay={{ "show": '1000', "hide": '0' }} placement="bottom" target="chargeCodesButton">

**Comment by grreeenn** [comment]
didn't work for me. Version 8.0.1

**Comment by JoshMcCullough** [comment]
I agree that the `delay` prop doesn't seem to work (tried with v5.0.0 and upgraded to v8.4.1 with no luck) -- the tooltip shows immediately and hides very quickly, even with ridiculous numbers for the delay. Tried both, e.g. `delay={3000}` and `delay={{ show: 3000, hide: 100000 }}`.

Also noticing that `autohide={false}` appears to have no affect, the tooltip closes anyway.

```js
      <UncontrolledTooltip target={id} delay={3000} autohide={false}>
        ...
      </UncontrolledTooltip>
```
