### ISSUE TITLE
How can I make a bootstrap panel in reactstrap?

### ISSUE THREAD

**Issue by sjorsvanheuveln** [reactstrap/reactstrap#527]
I have this old code which I now want to use in react. However there doesn't seem to be support anymore for headers. Does reactstrap have a solution for this?

```
<div className="col-sm-6">
        <div className="panel panel-default">
          <div className="panel-heading">
            <h3 className="panel-title">Title</h3>
          </div>
          <div className="panel-body">Body</div>
        </div>
      </div>
</div>
```

**Comment by TheSharpieOne** [comment]
[Cards](http://v4-alpha.getbootstrap.com/components/card/) replaced panels and more in Bootstrap 4.
> If you’re familiar with Bootstrap 3, cards replace our old panels, wells, and thumbnails. Similar functionality to those components is available as modifier classes for cards.

[Card Header and Footer](http://v4-alpha.getbootstrap.com/components/card/#header-and-footer) is how cards are used in a similar way to panels.

In reactstrap, there are [similar examples](https://reactstrap.github.io/components/card/), here is how it would be done:

```jsx
    <Col sm={6}>
      <Card>
        <CardHeader>Title</CardHeader>
        <CardBlock>
          <CardText>Body</CardText>
        </CardBlock>
      </Card>
    </Col>
```

**Comment by yasharma** [comment]
I've used the card and collapse component to get accordion flavor - check out (https://github.com/yasharma/reactstrap-card-accordion)
```javascript
<Card style={{ marginBottom: '1rem' }} key={index}>
      <CardHeader onClick={this.toggle} data-event={index}>Header</CardHeader>
      <Collapse isOpen={collapse === index}>
            <CardBody>
            Anim pariatur cliche reprehenderit,
             enim eiusmod high life accusamus terry richardson ad squid. Nihil
             anim keffiyeh helvetica, craft beer labore wes anderson cred
             nesciunt sapiente ea proident.
            </CardBody>
      </Collapse>
</Card>

use toggle as like
toggle(e) {
      let event = e.target.dataset.event;
      this.setState({ collapse: this.state.collapse === Number(event) ? 0 : Number(event) });
}
```
Hope this helps
