### ISSUE TITLE
Importing `Badge` does not seem to work.

### ISSUE THREAD

**Issue by mattdeboard** [reactstrap/reactstrap#528]
### Issue description

- version `#3.9.2`
- components: `Badge`

```
Uncaught (in promise) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Pill`.
```

### Steps to reproduce issue

- `import { Badge } from "reactstrap";` then use the `Badge` component inside another component, as normal.

```jsx
import { Badge } from "reactstrap";
import { IconTimes } from "react-svg-icons";
import { Row } from "shared/components/react-bootstrap-subset";

class Pill extends React.PureComponent {
  props: { label: string };

  render() {
    return (
      <Badge color="default" pill>
        {this.props.label}
        <IconTimes className={css(styles.close)} />
      </Badge>
    );
  }
}
```

I have tried removing `Badge` from the `Pill` component and everything renders as expected. if I remove everything but `Badge`, the error persists.

**Comment by mattdeboard** [comment]
Oh it looks like maybe this is related to #523. I don't see a `Badge` component at all in `reactstrap.js`.

**Comment by mattdeboard** [comment]
Oh and in fact we're running an old-ish version of reactstrap! Nevermind!

**Comment by TheSharpieOne** [comment]
For the record bootstrap did this thing where the changed the name`Badge` -> `Tag` -> `Badge` and reactstrap followed. So if `Badge` is not in your version and you cannot upgrade (for whatever reason), `Tag` will be there and do the same thing.
