### ISSUE TITLE
reactstrap modal.js show function alway use 'style.position = "relative"' 

### ISSUE THREAD

**Issue by yjs301** [reactstrap/reactstrap#529]
### Issue description

The modal form is always out of the parent div tag. 

I want to put this modal popup in div tag classnamed 'wrapper01'.
This 'wrapper01' has css style 'position: relative' for parent view.
 
but the modal is always use 'position: relative', so I can't put this modal popup in my parent 'wrapper01'.

here is my html map.

![3](https://user-images.githubusercontent.com/23020861/29063582-4afae0c2-7c61-11e7-8110-d3f64145e210.png)

I think 'show()' function in the modal.js has the static position style 'relative'. 

![1](https://user-images.githubusercontent.com/23020861/29063658-824eb080-7c61-11e7-82a3-0126fd9c95af.png)

I want to put more elements like 'position: absolute' , 'top: 100px'. so I use this modal popup in my parent div tag.

Can it be fixed? 

- version: 4.8.0
- components: modal.js

**Comment by TheSharpieOne** [comment]
#113 is tracking this issue. Currently you cannot specify a container and  thus the body tag is used. #113 proposes allowing the container to be specified so that it will append the modal (and other components) to the parent.

**Comment by petrleocompel** [comment]
@yjs301 partial/temporarily solution can be extending Modal and override method show. 
Like this
```javascript
export default class CustomModal extends Modal {
    show = () => {
        const {topWrapperClassName} = this.props;
        const classes = document.body.className;
        this._element = document.createElement('div');
        this._element.setAttribute('tabindex', '-1');
        // this._element.style.position = 'relative';   // This you dont want
        this._element.style.zIndex = this.props.zIndex;
        this.originalBodyPadding = getOriginalBodyPadding();

        conditionallyUpdateScrollbar();

        document.body.appendChild(this._element);

        document.body.className = mapToCssModules(classNames(
            classes,
            'modal-open'
        ), this.props.cssModule);

        this.renderIntoSubtree();
    }
}
```

I'm using this until #113 will be fixed.
