### ISSUE TITLE
Modal AutoFocus broken with React 16 because of render unstable changes

### ISSUE THREAD

**Issue by virgofx** [reactstrap/reactstrap#532]
Rendering a Modal component with defaults fails in React 16 with:

```
Uncaught TypeError: Cannot read property 'parentNode' of undefined
```

The root cause is because the Modal's autoFocus is attempting to reference the `this._dialog` which is set via callback and does not exist as result of changes made in `unstable_renderSubtreeIntoContainer`.

Reference: https://github.com/facebook/react/issues/10309

- Reactstrap: `4.8.0`
- React: `16.0.0-beta.3`
- Components: `Modal`

### Steps to reproduce issue
1. Specify a new `Modal` component with no `autoFocus` attribute or `autoFocus={true}`

### Demonstration
https://www.webpackbin.com/bins/-Kr2BOnFO9GcE691BLYr

To toggle the error adjust the `autoFocus` property (Setting to `false` removes error)
`<Modal isOpen={true} autoFocus={true}>`

**Comment by virgofx** [comment]
Reference Notes:

* AutoFocus is used to ensure that pressing the **Escape** key registers the event.
* A separate `autoFocus` property was added to allow custom elements to be automatically focused on load. This conflicts directly with the `keyboard` property and should be resolved.

[ ] Move the escape click handling to the document element and catch via bubble. This would remove need for reference to the dialog for focusing and ensure compatibility with `keyboard`. It would also allow removal of `autoFocus` property as it's not needed.

[ ] Otherwise, fixing the timeout focus logic would work and keep both properties; however, there exists the untested case where setting `keyboard` = `true` and `autoFocus` = `false` currently does not work.

**Comment by TheSharpieOne** [comment]
> Would there be any issue moving the event listener to the document?

Multiple `Modals`, which bootstrap itself does not support, so we can probably drop support as well(?). The issue becomes, which `Modal` is being closed.

Yes, `autoFocus` = `false` does break the keyboard, but `autoFocus` = `false` was meant to allow the user to control focus himself/herself, focusing on something within the `Modal` which would allow **esc** to work. I wonder if we could determine if focus is in the `Modal` via `document.activeElement` and not auto focus the modal, thus removing the need for `autoFocus` prop on `Modal`.

**Comment by virgofx** [comment]
Good points. Sounds like we should handle a couple other outstanding issues as well and get the Modal alll  tidied up. I've added multiple modals into the checklist above.

As far as multiple modals .... I'm not sure on the best practice. Weird things happen in different libraries (e.g. Sometimes things stack including more backdrops, others have a single persistent backdrop and single active modal)

**Comment by TheSharpieOne** [comment]
Yeah, for multiple modals there is a ton of questions and because bootstrap doesn't support it, we cannot reference the way bootstrap does it. I am for removing multiple modals to be more inline with bootstrap itself.

**Comment by virgofx** [comment]
Supporting a single modal is obviously easier; however, there could be valid use cases for multiple modals:

Example of the multiple modal concept:

Click the delete trashcan icon button in the main form:
http://jsfiddle.net/KyleMit/QqqxF/224/show/light/

I wouldn't mind supporting this as it wouldn't be too difficult to implement. Specifically:

* Move back the escape listener to document (if `keyboard = true`)
* Single backdrop only
* Allow multiple modals. Latest modal pushes z-index above backdrop. Previous ones below.
* If keyboard = true, escape closes top modal (if last modal or only 1, backdrop gets closed)

**Comment by TheSharpieOne** [comment]
Just going to leave this here since A11y should also be included when talking about some of these changes https://github.com/davidtheclark/react-aria-modal. #310 would be nice since we are talking about focus management.
@davidtheclark did a great job making react-aria-modal and all of the smaller components/libraries it utilizes. It would be awesome to leverage those same libraries and even react-aria-modal itself (just managing/mapping props to be more inline with bootstrap). Food for thought.
