### ISSUE TITLE
Support for Custom Form Inputs

### ISSUE THREAD

**Issue by bartonwelt** [reactstrap/reactstrap#534]
Is there any plan to support Bootstrap 4 custom form inputs as found here: https://v4-alpha.getbootstrap.com/components/forms/#custom-forms

**Comment by carlosmarte** [comment]
@TheSharpieOne I would like to tackle this feature. Currently there are 4 types of custom forms (https://v4-alpha.getbootstrap.com/components/forms/#custom-forms).

- Checkboxes and radios
- Select menu
- File browser

Should i create a file for each one under reactstrap/src/?
- InputBoxes.js
- SelectMenu
- FileBrowser

**Comment by TheSharpieOne** [comment]
The docs link is now https://getbootstrap.com/docs/4.0/components/forms/?#custom-forms it is slightly different than the alpha stuff. As far as components and separation, I wouldn't mind if there was a single CustomInput or CustomControl component which had a type prop to control which custom input is rendered.
Besides the inputs here is also a stack class, we could have thst as CustomInputStack or CustomControlStack.

**Comment by carlosmarte** [comment]
@TheSharpieOne, just pushed the initial implementation. Would appreciate any feedback before I write the unit test. 

Screenshot of custom elements:
![image](https://user-images.githubusercontent.com/3478576/30531502-c50db4d6-9c1c-11e7-94ab-37e3a559c682.png)

**Comment by Stainzl** [comment]
How do I use them when I installed it to via npm install?
My version of reactstrap is 5.0.0-alpha.4

**Comment by TheSharpieOne** [comment]
The PR which adds custom inputs has some change requests and hasn't been merged. You'll have to create your own for now.
