### ISSUE TITLE
Button color defaultProp as "secondary" is a bad default in Bootstrap 4-beta

### ISSUE THREAD

**Issue by humean** [reactstrap/reactstrap#535]
- version `#4.8.0`
- components: `Button`

So bootstrap 4 has finally moved from alpha to beta, and with it they have dramatically changed the default colour palette. Most notably they have changed the `btn-secondary` css class from a white color to a dark grey, which doesn't seem like a good default for a button. Unfortunately, "secondary" is the default prop for the reactstrap Button class. I recommend making the default for the Button class to be just the bootstrap `btn` css class or `btn-light` css class, because otherwise I imagine that it might become necessary to explicitly give a color prop to almost every instance of Button.

https://getbootstrap.com/docs/4.0/components/buttons/

**Comment by gthomas-appfolio** [comment]
Defaulting to `light` might too opinionated as it seems to be for edge cases.  But the `.btn` with no color looks okay:

<img width="795" alt="screen" src="https://user-images.githubusercontent.com/18536746/29223609-08686b68-7e7c-11e7-8584-c9dcb23299e2.png">

Though it looks pretty similar to secondary TBH

**Comment by humean** [comment]
Maybe having primary as the default is a better option

**Comment by gthomas-appfolio** [comment]
Defaulting to primary just seems to be a a bigger change than leaving as secondary or removing default, at least in the apps I've seen use reactstrap (where primary is a call to action and not the default state).

**Comment by TheSharpieOne** [comment]
Just `.btn` doesn't have nice states and it is not recommended to use `.btn` without a style class. I don't think primary is wanted (IIRC, reactstrap originally had primary, but was changed to secondary). FWIW I say to just leave it as most often than not, people are going to override it one way or the other.

**Comment by supergibbs** [comment]
You could make it a required prop to force users to make a decision

**Comment by virgofx** [comment]
Since it's allowed without a styled class, we should respect bootstrap and make color optional. Default to regular (regardless of look or anything else)

**Comment by supergibbs** [comment]
BS4 doesn't allow `btn` without a style. Sure it sorta works as mentioned above but it's not meant to be used that way. All examples have `btn btn-<style>`.

https://getbootstrap.com/docs/4.0/components/buttons/

**Comment by virgofx** [comment]
Ah, I was going off of the screenshot above. It looks like the leftmost default button was added manually, I'd vote then to make it required.

**Comment by bestguy** [comment]
Yes, sorry that was me pasting markup into their example.  It's not a documented button style

**Comment by mtakac** [comment]
+1 for making color required. Bootstrap buttons don't seem to work properly without specifying `btn-<style>` class. Reactstrap implementation is a bit confusing right now.

**Comment by TheSharpieOne** [comment]
FWIW I believe providing a sensible default with the ability to override (which is how it currently is) is better than just forcing users. Secondary is probably the most sensible since it doesn't convey meaning like the others (light and dark excluded as they seem to have more specific use cases for contrast). It may look less appealing, but that is on bootstrap.

**Comment by supergibbs** [comment]
A default is convenient but my only argument is that isn't how BS4 works. If you were creating a button in HTML/CSS, Bootstrap makes you decide what color button to make it. There is no default. I know it's a breaking change but I feel Reactstrap should match Bootstrap in this case.

**Comment by jp7carlos** [comment]
> Secondary is probably the most sensible

I agree. People can always change the color ```.btn-secondary``` will actually have on their CSS or SASS. It's semantically secondary, it's not primary. 

Not liking the default color for a secondary button is a good reason to create your custom theme with your favorite colors, but it's not a good reason for this button to stop being secondary.

**Comment by vndevil** [comment]
just insert color="deoco" in <Button>

`                        <Button type="submit" color="deoco" className="yourCssClassName" title="Your Title">
                            Button with class='yourCssClassName btn btn-deoco'
                        </Button>`
