### ISSUE TITLE
Setup a Row component with nested Col components of equal height.

### ISSUE THREAD

**Issue by sjorsvanheuveln** [reactstrap/reactstrap#536]
I have a Row component with two Col components. I want them to be the same height, i.e. I want the col with the smallest height to match the other col's height. How to do this in react strap, without reverting to css.

```
<Row>
      <Col sm={10}>
            <Button color="primary" >A </Button> &nbsp;
            <Button color="primary" >B</Button> &nbsp;
      </Col>
      <Col sm={2} />
</Row>
```

**Comment by mtakac** [comment]
`Col`s in one row are always the same height. Your example does exactly what you describe. Why do you thing it doesn't work? Try adding border to `cols` and see what happens.

**Comment by sjorsvanheuveln** [comment]
Ok then my question is different. In my real code I use cards inside the Cols. However they do not expand to the bottom of the Col. How to fix this?

**Comment by mtakac** [comment]
I see. In that case don't use `Row` and `Col` but use `CardGroup` or `CardDeck`. Both will make cards in one group / deck same height. Only difference is that `CardGroup` will stack the cards next to each other and `CardDeck` will create a gutter between them.

```
<CardDeck>
    <Card>...</Card>
    <Card>...</Card>
</CardDeck>

```

You can set the card's dimensions using Bootstrap [size utilities](https://getbootstrap.com/docs/4.0/utilities/sizing/).

**Comment by sjorsvanheuveln** [comment]
Thanks!
