### ISSUE TITLE
The DropdownItem child do NOT get the click event

### ISSUE THREAD

**Issue by akatebi** [reactstrap/reactstrap#54]
<ButtonDropdown isOpen={this.state.dropdownOpen} toggle={this.toggle}>
        <DropdownToggle color="primary" caret>
          Sign in
        </DropdownToggle>
        <DropdownMenu right>
          <DropdownItem>
            <Button onClick={ neverFires } />
          </DropdownItem>
        </DropdownMenu>
      </ButtonDropdown>

**Comment by eddywashere** [comment]
@akatebi could you provide a demo of this issue? In the docs the examples show that you must provide an onclick handler that triggers the toggle or updates the state that you provide.

**Comment by akatebi** [comment]
Hi Eddy, Change your demo page for the Dropdowns like shown below. The <div> component will not see the click event. Thanks!

<DropdownItem>
      <div onClick={() => console.log('will never fire')}>
          Another Action
       </div>
</DropdownItem>

**Comment by TheSharpieOne** [comment]
I updated the docs locally to wrap the text within the `DropdownItem` in a `div` with an `onClick` and it seems to be working fine. See the screenshot below.
Also, he is the code that was used:
```
<DropdownItem>
  <div onClick={() => console.log('This will fire!')}>
    Another Action
  </div>
</DropdownItem>
```
![image](https://cloud.githubusercontent.com/assets/664714/17221329/65c64eaa-54c1-11e6-8130-2a142fc6eb9a.png)

**Comment by akatebi** [comment]
Hi Evan,

  I did the same as you. It works in Chrome. But it does NOT work in
Firefox :(

Thanks,
Alex

**Comment by TheSharpieOne** [comment]
I see, this is because the element with the onClick (the div in this case) ends up be put inside of a button. In chrome the said element gets the event, in firefox and [per the spec](https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element), it does not.
Basic test: https://jsfiddle.net/TheSharpieOne/vfk3uvt8/

DropdownItem defaulting is a `button` is the problem (maybe it should default to `a`, more inline with the bootstrap examples), but you can override the default tag/element via the tag prop like this:
```
<DropdownItem tag="a">
  <div onClick={() => console.log('This will fire!')}>
    Another Action
  </div>
</DropdownItem>
```

Screenshot from Firefox with passing tag prop:
![image](https://cloud.githubusercontent.com/assets/664714/17225691/fdba8110-54d3-11e6-993a-b272a7fa273e.png)

**Comment by eddywashere** [comment]
Good info @TheSharpieOne.

@akatebi I just picked up that there was a formatting issue in your original comment. To edit your comment, add three back ticks like this -> ``` to a new line before your code, and another set of three back ticks to a new line at the end of your code block.

Example: 

![image](https://cloud.githubusercontent.com/assets/399776/17226453/6cba0254-54be-11e6-9177-8861a9840f8a.png)

then it will output 

```
<ButtonDropdown isOpen={this.state.dropdownOpen} toggle={this.toggle}>
        <DropdownToggle color="primary" caret>
          Sign in
        </DropdownToggle>
        <DropdownMenu right>
          <DropdownItem>
            <Button onClick={ neverFires } />
          </DropdownItem>
        </DropdownMenu>
      </ButtonDropdown>
```

That said, the `DropdownItem` is already a button, so you can remove that inner child `Button` and you can move the `onClick` handler to that `<DropdownItem onClick`. If that can't be avoided, consider the suggestion and feedback from @TheSharpieOne.

**Comment by akatebi** [comment]
Awesome !!!
Thanks !!!

**Comment by AndyCJ** [comment]
Was this issue supposed to be closed without any changes being made?

It's still a problem today, and is still solved by `<DropdownItem tag="a">`.

The [bootstrap documentation](https://getbootstrap.com/docs/4.1/components/navbar/#supported-content) seems to show `a` tags being used for dropdown items.

But the [reactstrap DropDownItem source](https://github.com/reactstrap/reactstrap/blob/master/src/DropdownItem.js) shows it's still defaulting to Button.

**Comment by TheSharpieOne** [comment]
> It's still a problem today, and is still solved by <DropdownItem tag="a">.
> 
> The bootstrap documentation seems to show a tags being used for dropdown items.
> 
> But the reactstrap DropDownItem source shows it's still defaulting to Button.
> 
> I can put in a pull request if you want?
> I think it's just a matter of changing the prop default from button to a?

anchor tags (`a`) **require** and `href` per the spec, if you provide an `href` to `DropdownItem` it will output an anchor tag. If you don't provide an `href` it will output a `button`. Providing `tag` will of course override this.

**Comment by pranavig** [comment]
I had an issue with DropdownItem onClick as well. I have tried the above scenarios, but in my case when i'm using inside map function, it still threw an error..

What worked for me is below code. (Creating the function reference locally and then assigning it inside the map function)

        const toggleFunc = this.toggleOnClick;
        let itemList = this.props.itemList.map(function (item, index) {
            return (
                <DropdownItem key={index} id={item.id} onClick={() => toggleFunc(item.id)}>
                    {item.text}
                </DropdownItem>
            );
        });

**Comment by refrigerator** [comment]
I'm having this issue — tried everything suggested here, but to no avail. Here's my code:

```
<DropdownMenu triggerType="button" trigger="Menu">
                <DropdownItem tag="a" onClick={() => alert("Never fires")}>One</DropdownItem></DropdownMenu>
```

I've tried putting a `<div onClick={...}`> inside the `<DropdownItem>`, I've tried with/without `tag="a"`.

Can anyone help? 

Thanks!

**Comment by AbreezaSaleem** [comment]
I am having the same issue as @refrigerator. Can someone please guide me?
@eddywashere @TheSharpieOne

**Comment by AndyCJ** [comment]
@refrigerator @AbreezaSaleem 

As TheSharpieOne said a couple of posts up ...

> anchor tags (a) require and href per the spec, if you provide an href to DropdownItem it will output an anchor tag. If you don't provide an href it will output a button. Providing tag will of course override this.

I don't see a href on your components, you have checked that it's outputting an anchor and not a button?

**Comment by AbreezaSaleem** [comment]
@AndyCJ I am doing 
`				return <DropdownItem tag="a" key={index} onClick={(index, website) => console.log(index, website)}>{website}</DropdownItem>
`
DropdownItems are getting outputted as anchor tags.

**Comment by AbreezaSaleem** [comment]
I have also tried adding onChange to DropdownMenu but that isn't getting called either.

**Comment by afielden** [comment]
I wonder why this has been closed. Because I'm trying to get this working and it doesn't. My onClick function is not being called. Looking at the component inspector from React developer tools, I see

onClick: ƒ onClick() {}

I definitely specified 

<Dropdown.Item tag="a" href='#' key='1' onClick={() => console.log('selected')}>

What happened to my click function?

**Comment by YannisMarios** [comment]
This also doesn't work on latest release 8.4.1

**Comment by supercede** [comment]
I'm having this problem in July 2020. Please fix this issue. I've done everything @refrigerator did above all to no avail

**Comment by pranavig** [comment]
> I wonder why this has been closed. Because I'm trying to get this working and it doesn't. My onClick function is not being called. Looking at the component inspector from React developer tools, I see
> 
> onClick: ƒ onClick() {}
> 
> I definitely specified
> 
> <Dropdown.Item tag="a" href='#' key='1' onClick={() => console.log('selected')}>
> 
> What happened to my click function?

hi, could you try removing the href?

If still facing the issue, may be try creating a sub component? Something like below -

clickHandler = () => {
   Console.log("Selected");
}
render () {
return <Dropdown.Item tag="a">
     <TestComponent clickHandler={this.clickHandler} />
</Dropdown.Item>
}

----‐-----------------

Class TestComponent extends Component{
  render (){
    return <Button onClick={this.props.clickHandler} />
}
}
