### ISSUE TITLE
ButtonDropdown missing DropdownMenu on toggle

### ISSUE THREAD

**Issue by Puschek** [reactstrap/reactstrap#542]
If I click the Button to show my DropdownButton Menu I do not see anything. 
In the inspector tools it seems everythign allright. Im looking in electron in the Elements and in the react tab, it seems that i is updating all states propperly, but as soon as isOpen is true, it does not shwo my DropdownMenu.

- version `#4.8.0`
- components: `ButtonDropdown`

I used the example on reactstrap for ButtonDropdown but i changed few thing: 

I pass the toggle state from my main component and give it the current toggle state reversed as soon as i click the button. The values are passed around perfectly, but i dont see my dropdownMenu.

EDIT: As far I can tell now, the display: propperty is not set correctly. If i manuel edit it, i can see my Dropdown menu.

EDIT2: So I see the error. If I click the Button it does not change the display of my dropdown div block. I dont know why it is like this. Maybe i did something wrong....I included Bootstrap 4 Beta and imported it correctly. My classNames are working perfectly so I think that isnt the problem. could the Problem be that I installed the beta version and not the alpha one?

**Comment by TheSharpieOne** [comment]
The version of bootstrap released 3 days ago has tons of breaking changes and is not yet supported. reactstrap need more time to coordinate all of the changes needed to update to bootstrap v4 beta. For now, use bootstrap v4.0.0-alpha.6

See #487

**Comment by YutHelloWorld** [comment]
beacuse of bootstrap's update.I checked the navbar need add class like 'navbar-expand-lg', and the  secondary button was changed!

**Comment by TheSharpieOne** [comment]
Closing this in favor of tracking in #487. This has been added to the list as "dropdowns use `show`" as it affects all dropdowns and the class has changed from `open` to `show`
