### ISSUE TITLE
Upgrade Bootstrap 4 from Alpha 6 to Beta

### ISSUE THREAD

**Issue by benxgao** [reactstrap/reactstrap#546]

**Comment by GitShaffi** [comment]
DropDown in reactstrap is broken after upgrading from alpha 6 to Beta. Please make reactstrap compatible with latest version of BootStrap4.

**Comment by KeitIG** [comment]
Yes please :) The beta being out, it should be far more stable now and there should not be new breaking changes once reactstrap will be ready for the beta.

**Comment by KeitIG** [comment]
Dupe with https://github.com/reactstrap/reactstrap/issues/487 btw

**Comment by TheSharpieOne** [comment]
Duplicate of #487.
Closing this in favor of #487. Please use #487 to track this issue.
