### ISSUE TITLE
Example navbar code does not match example shown

### ISSUE THREAD

**Issue by LiamKenneth** [reactstrap/reactstrap#547]
Example navbar code does not match example shown.

Go to here -> https://reactstrap.github.io/components/navbar/
 
The example shows the navbar with the brand name on the left and links on the right.

But when I copied the example code.

My brand name was on the right and on the left was toggle button for menu.

I had to add this class to my navbar `className="navbar-expand-sm"` to get the links to show.

I also needed to switch NavbarBrand and NavbarToggler to make my navbar match the example.

So I'm unsure if the example is wrong or it's something to do with Bootstrap 4 Beta which I am using instead of the Alpha version mentioned on reactstrap website.

If it is an issue I can do a pull request.

**Comment by TheSharpieOne** [comment]
This is bootstrap 4 beta related. It has already been addressed in the v5 branch both in code and in the examples. Just waiting on other bootstrap 4 beta related issues to be addressed before releasing it and updating the docs site.

**Comment by LiamKenneth** [comment]
Ah brilliant, good stuff!
