### ISSUE TITLE
error when deploy on production env

### ISSUE THREAD

**Issue by phamvankhang** [reactstrap/reactstrap#550]
### Issue description

- version `#4.8.0`
- components: `Modal`
i dont know why, on development env it ok, but on production is not
### Steps to reproduce issue
- goto my link and click to CTA button: `https://beta.jamja.vn/khuyen-mai/bedding-gallery-0/thu-sms-moi-config-0`
- login modal will open but it dont add `show` class

<img width="625" alt="screen shot 2017-08-23 at 10 59 57 am" src="https://user-images.githubusercontent.com/3737352/29598372-bd6a9ea8-87f2-11e7-9a7d-5701a275596d.png">

**Comment by virgofx** [comment]
Personal website references are not helpful. You can create a jsbin/webpackbin with exact source code that shows the problem in detail. Most likely, if it's working in development, but not production, the error is on your side.  Close/non-issue.

**Comment by TheSharpieOne** [comment]
It appears that you are using react-transition-group 2.x (based on inspecting the compiled code) which is currently not supported.
Depending on how you create your production assets, you may have react-transition-group 1.x locally but react-transition-group 2.x gets installed on your build server when creating the production assets.
What does your package.json have for react-transition-group and what version do you have locally (`npm info react-transition-group version`)?

**Comment by phamvankhang** [comment]
@TheSharpieOne thank you
