### ISSUE TITLE
v4-beta .show class for navbars conflict with Collapse component

### ISSUE THREAD

**Issue by QuantumHive** [reactstrap/reactstrap#551]
reactstrap version `4.8.0`
### Issue description
I'm using the `Collapse` component for my `.navmenu`, in Bootstrap v4 alpha 6, the styling was good.
Now I've updated to v4-beta and this is the result:

![capture](https://user-images.githubusercontent.com/2554952/29603040-e116c08a-87e2-11e7-91b4-d051d9fd17fc.PNG)

As you can see the color of the `.nav-link` inside the collapse are more white. This is because of the `.show` class that is being used in v4-beta. The `.show` class is also used by reactstrap for the `Collapse` component which now messes with the styling.

You can see the class in the source here: https://github.com/twbs/bootstrap/blob/35f80bb12e4e71fd777ee60ffa43711d8f84b1a6/scss/_navbar.scss#L264

**Comment by TheSharpieOne** [comment]
This issue is probably best taken up with bootstrap itself. bootstrap v4-beta uses `.show` on the `.collapse` the same as reactstrap.
https://github.com/twbs/bootstrap/blob/3a6fc265f6db182ad8fdc2b1b5b5dadcbb411cfc/js/src/collapse.js#L47

**Comment by QuantumHive** [comment]
@TheSharpieOne 

> This issue is probably best taken up with bootstrap itself.

What do you mean? I know both libraries use the same class in this case, but what's the best approach to avoid this conflict?

**Comment by TheSharpieOne** [comment]
reactstrap doesn't contain any styles. All of the styles are from bootstrap. If you are seeing an issue with the way something is styled/looks then that issues is with bootstrap. 
reactstrap components like Collapse are a react implementation of the bootstrap js. If bootstrap's implementation adds a `.show` class (which it does), so must reactstrap.

**Comment by QuantumHive** [comment]
I don't think this is an issue with Bootstrap itself. It's an issue the way Reactstrap handles it's collapse mechanism by misusing the `.show` class. You can see from the source that Bootstrap *just* styles elements that have a `.show` class within a navbar. Pre-beta, this `.show` class was not used in Bootstrap for styling, it's a new addition.  
This new addition now has a **conflict** with Reactstrap, because Reacstrap is not using the `.show` class for styling, but more for functionality (the collapsible should expand). You could argue that this might also be styling, but it's not the styling intended by Bootstrap. The intention was not with collapsible in mind.  
So I think that Reactstrap should adjust with Bootstrap's new version and use another class (just name it something else) that does not conflict with Boostrap.

**Comment by TheSharpieOne** [comment]
I see, I missed this part:

> Now I've updated to v4-beta and this is the result

reactstrap 4.8.0 doesn't support bootstrap v4-beta. reactstrap 5 alpha has support for bootstrap v4-beta and has been released using the `next` tag (`npm install reactstrap@next`). Can you give that a try?

Ref: #487, #574

**Comment by QuantumHive** [comment]
@TheSharpieOne You were right from the start, this wasn't a bug in Reactstrap. It's indeed a Bootstrap issue.
In Bootstrap 4 expanded [dropdowns](https://getbootstrap.com/docs/4.0/components/dropdowns/) have the `.show` class, I thought you guys were adding this class, but it's actually a Bootstrap functionality.  
In my case my `nav-link`s are nested inside the dropdowns which in turn are nested inside `navbar-nav` and `nav-pills`. So I think this might just be a bug in Bootstrap:
https://github.com/twbs/bootstrap/blob/fc94de5b8b5b329a298eeeb76174b146ff17af2d/scss/_navbar.scss#L279
and
https://github.com/twbs/bootstrap/blob/fc94de5b8b5b329a298eeeb76174b146ff17af2d/scss/_nav.scss#L80

**Comment by QuantumHive** [comment]
I've created an issue at Bootstrap: https://github.com/twbs/bootstrap/issues/24928
