### ISSUE TITLE
react-transition-group peer dependency?

### ISSUE THREAD

**Issue by amikhalev** [reactstrap/reactstrap#552]
Is there a reason that `react-transition-group` is a peer dependency? Because as it is, it forces any projects that use `reactstrap` to also use `react-transition-group@1.x` which isn't ideal. Since `react-transition-group` only exposes components, there's no risk in having a version mismatch. And if the parent project uses the same version, it will be deduped anyways.

If there's no reason for this, I would be happy to submit a PR which makes it a regular dependency (and also upgrade it to `2.x` for good measure)

**Comment by virgofx** [comment]
Not sure on the peer vs. dep rational ; however, we do need to upgrade to 2.x regardless. It's a pretty straightforward migration if you want to tackle that :)

**Comment by virgofx** [comment]
I think the original reasoning is that `react-transition-group` is considered a plugin of sorts. Reactstrap does not depend on it explicitly depending on components used and other options. That was the original intent behind `peerDependencies`.

**Comment by TheSharpieOne** [comment]
@amikhalev make a PR, branch from the v5 branch (and PR back to v5) and we can try to get it into the next major release

**Comment by sjorsvanheuveln** [comment]
I agree with this proposal. The TranisitionGroup component from react-transition-group 2.2.0 is not working properly with reactstrap 4.8.0. It messes up the inline styling and it is hard to repair it with lots of css lines to make it look good again.

**Comment by virgofx** [comment]
@sjorsvanheuveln Reactstrap currently does not support react-transition-group 2.2.0. If you have it installed that's a failure on your part to read the Readme/installation instructions.
