### ISSUE TITLE
bootstrap.css in  bootstrap@4.0.0-alpha.6 not functioning properly

### ISSUE THREAD

**Issue by apdjustino** [reactstrap/reactstrap#553]
I'm not sure if this is an issue to report with reactstrap or bootstrap. Adding the bootstrap using npm install bootstrap@4.0.0-alpha.6 --save in the Getting Started instructions to use the bootstrap.css does not produce a .css file that will work with all of the reactstrap components. 

I tested the <Dropdown> components and the dropdown component does not work properly. The classes and properties of the rendered HTML change correctly on the dropdown toggle, but the styling does not change and the dropdown does not display menu items. 

I copied the css from the bootstrap.css file in one of my older projects, and this resolved the issue.

**Comment by TheSharpieOne** [comment]
You need to import the css from bootstrap, installing isn't enough. If you are using webpack, you need the style loader and css loader or the sass loader.
If you don't plan on customizing bootstrap via sass (creating a custom build), then it would probably be best to pull in bootstrap from a CDN, such as https://www.bootstrapcdn.com/beta/ or https://cdnjs.com/libraries/twitter-bootstrap/4.0.0-alpha.6

**Comment by apdjustino** [comment]
Thanks for the quick response. I guess I forgot to mention that I did import the css from bootstrap in my index.js file (I used the create-react-app)  the import line looks like:

import 'bootstrap/dist/css/bootstrap.css

The <Dropdown> renders in bootstrap styling, although it is a darker grey than white. And of course the menu does not display when clicking on it. If I inspect the rendered elements in chrome, I can see that the appropriate classes change on a click, and the items in the menu are in the rendered DOM, but not displayed.

**Comment by TheSharpieOne** [comment]
> I copied the css from the bootstrap.css file in one of my older projects, and this resolved the issue.

Double check that you have the right version of bootstrap installed. If you can, post your package.json and the code where your import bootstrap and a component which isn't working.

**Comment by saphp** [comment]
importing minified css file will fix the issue
`import 'bootstrap/dist/css/bootstrap.min.css';`

**Comment by smithmanny** [comment]
I have the same problem. Changing to minified version worked then I restarted server and issue happened again.

**Comment by hachtman** [comment]
Importing the minified version solved the issue on my end (webpack `/sass/css/style loaders`. Maybe update the docs to suggest importing the minified by default? Or is there a reason to use the unminified with different tooling?

**Comment by TheSharpieOne** [comment]
The suggestion for not modifying/customizing bootstrap is to include it from their CDN. If you plan on modifying bootstrap to customize colors and such, then you should import it, which works just fine for me.
Also, if you are having difficulties import bootstrap, you might want to open an issue with them. This library doesn't handle any styles directly, only applying classes and such.
