### ISSUE TITLE
reactstrap v5

### ISSUE THREAD

**Issue by ablbol** [reactstrap/reactstrap#555]
Hi
Do I need reactstrap v5 with bootstrap beta?  I am using reactstrap ^4.8.0 but noticed that old classes are still being used.  How do I yarn v5? I tried yarn reactstrap@next but I don't think this is the one.
Thanks

**Comment by lueurxax** [comment]
It's intresting for me too

**Comment by foodgy** [comment]
Well, 5.0.0 is not yet listed on npm

**Comment by virgofx** [comment]
There is no 5.0. It's currently being actively developed in a branch. When it's ready all documentation will be updated.

Reactstrap stable is compatible with **Bootstrap-alpha.6**. 

Please see the readme which currently states how to install Reactstrap along with supported versions.

**Comment by zhaoyao91** [comment]
Sorry, I am not pushing anybody. Just curious about the plan when v5 is expected to be ready. I notice that it has not been updated for nearly half a month, that's a little longer for an activily developed project.

**Comment by TheSharpieOne** [comment]
@zhaoyao91 We are doing our best, and yes, while v5 has not had a commit in 15 days, other spike branches of this repo have and forks from contributors are actively being worked on. When the individual components/updates are ready, they will be merged to v5 and when all of the components/updates are done v5 will be merged into master.

You, and everyone else, are welcome to help by contributing to make this process faster and get a stable release out sooner. You don't have to write code or create a PR to contribute; #487 tracks known changes, but I am fairly certain that there are more changes which need to be accounted for. We need help finding out all of the various changes that need to be made.

**Comment by TheSharpieOne** [comment]
I'm closing this as the question has been answered.
The TL;DR is I'm working on it.

**Comment by TheSharpieOne** [comment]
reactstrap@next is has been published with v5 alpha 1 which has bootstrap v4 beta 1 support.
