### ISSUE TITLE
[Question] Carousel example

### ISSUE THREAD

**Issue by DCKT** [reactstrap/reactstrap#558]
Hello,

I didn't found Carousel example on the online documentation. I've only found [this example](https://github.com/reactstrap/reactstrap/blob/v5/docs/lib/examples/Carousel.js).

With this example, the carousel is not visible and I have no error in the console.

I'm using the v5 branch. Any idea about this ? Is this example outdated ?

Thanks.

**Comment by mkalish** [comment]
I believe that the work to update reactstrap to the bootstrap 4 beta has delayed the publishing of this component, so its not in the current version you would get from NPM.

**Comment by TheSharpieOne** [comment]
Closing this as the question has been answered. 
Also adding: v5 will have (and the branch currently has) `Carousel` and an `UncontrolledCarousel` as well as examples for both. It will [hopefully] be released soon.
