### ISSUE TITLE
Popover with fixed target; placement incorrect after resize

### ISSUE THREAD

**Issue by michaeldzjap** [reactstrap/reactstrap#563]
### Issue description
The placement of a popover bound to a fixed target becomes incorrect after resizing the viewport/window.

- version `#4.8.0`
- components: `Popover`

### Steps to reproduce issue

- Create a container with a `Button` that has CSS property position fixed and a `Popover` with some dummy content. 
- Resize your window; the popover jumps to the left end of the screen

See this [CodeSandbox](https://codesandbox.io/s/zn4wpo31km)

**Comment by virgofx** [comment]
We can leave this open to track. I believe this should be fixed once we switchover to Popper which is almost complete.

**Comment by QuantumInformation** [comment]
Similar issue: https://github.com/reactstrap/reactstrap/issues/348#issuecomment-420246341
