### ISSUE TITLE
Issue with using react-css-module in create-react-app

### ISSUE THREAD

**Issue by ruchikagamage** [reactstrap/reactstrap#568]
im using react-css-module for my own component then when im using reactstrap  global bootstrap.css file not taking for styling bootstrap component.

**Comment by TheSharpieOne** [comment]
reactstrap uses the standard bootstrap class names and allows for these names to be mapped to generated css module class names via the `cssModule` prop available on all of the components.
If react-css-module is changes the bootstrap classes, you will need to supply the a map from the bootstrap class names to the react-css-module class names via the `cssModule` prop.
