### ISSUE TITLE
Warning: Input is changing an uncontrolled input of type text to be controlled

### ISSUE THREAD

**Issue by RosenPIvanov** [reactstrap/reactstrap#570]
I am using simple Input type like this:
<Input type="text" id="host" placeholder="Enter Coupa host name" required value={this.state.values.host}
                  onChange={(evt) => this.handleHost(evt.currentTarget.value)}/>
...
 handleHost = (value) =>{
   this.setState((prev) => {prev.values.host = value })
 }
But I got this warning:
 Warning: Input is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component

Everything works fine, but still cannot figure out why I have this.
Maybe it is not issue of reactstrap but such questions are unanswered in stack-overflow.

**Comment by TheSharpieOne** [comment]
what is your initial value of `this.state.values.host`? It cannot be `undefined` if you plan on setting it later. This is per react, not reactstrap.
It being `undefined` tell react that it is not set and that you do not plan on controlling the input... Then when you set it, you tell react you want to control it and thus react gives you a warning.

**Comment by RosenPIvanov** [comment]
You are 100% right - when the value is not initialized react treats it as uncontrolled component.
Thanks for the support!

**Comment by valnub** [comment]
Thanks a lot for this! Changing the init value from undefined to `''` did work for me

**Comment by dipakchandranp** [comment]
What dose it mean when **React says input field is an uncontrolled field**? How it will affect the a web page with a form of uncontrolled input fields.  I can see a warning message in console while changing values of the field, other than that what are other issues going to be there on the system?

**Comment by gergely-nagy** [comment]
@dipakchandranp , This is a general React question, and not related to reactstrap. Please have a look at the React's documentation:
[Controlled Components](https://reactjs.org/docs/forms.html#controlled-components)
[Uncontrolled Components](https://reactjs.org/docs/uncontrolled-components.html)

...or this would have been a good question for stackoverflow.

**Comment by mecklundie** [comment]
> You are 100% right - when the value is not initialized react treats it as uncontrolled component.
> Thanks for the support!

100% accurate. The input must contain an initial value. Thanks!

**Comment by RyanPaulMcKenna** [comment]
I have the same problem. However I do have an inital value being set in the state so I'm not sure if it is something to do with the color picker being summoned as a separate window.
                    <input
                        type="color"
                        onChange={this.handleColorChangeEvent}
                        value={this.state.color}
                    />

        this.state = {
            color: this.props.data.color,
            alias: this.props.data.displayName
        };
