### ISSUE TITLE
Cannot resolve reactstrap#v5

### ISSUE THREAD

**Issue by Puschek** [reactstrap/reactstrap#578]
### Issue description
Installed reactsrap manually to get the newest version for testing.

- version `#v5`

### Steps to reproduce issue
-npm install git+https://github.com/reactstrap/reactstrap.git\#v5
-import reactstrap from 'reactstrap'
-webpack error: Module not found: Error: Can't resolve 'reactstrap' in ...
-Is it normal that the reactstrap folder only contains the Changelog, LICENSE package.json and README.md? Not really sure if this is how it should be

If i install reactstrap via npm (4.8.0 version) my reactstrap folder contains the dist and lib folder, if I install the v5 branch it doesnt. It seems strange.

**Comment by TheSharpieOne** [comment]
Reactstrap doesn't check in npm distribution files to the git repo. The best way to test v5 is to clone it and build the dist files and use npm link. If you just want to demo its capabilities, you can do npm start to start up the documentation which has examples and demos of the various components.

**Comment by Puschek** [comment]
Hey 2 min ago i started to build the v5 branch and now it works! I wanted to test the functions with boostrap 4 beta. But im really new to node.js npm and all the fancy stuff. 

Still thanks the solution was like you said clone v5 and build!

**Comment by TheSharpieOne** [comment]
Just FYI: reactstrap@next has been published with v5 alpha

Also: Closing this since the issue appears to be resolved
