### ISSUE TITLE
Dropdown doesnt work with BS4 beta

### ISSUE THREAD

**Issue by deepu105** [reactstrap/reactstrap#581]
### Issue description

The drop-down components are not working when used with Bootstrap 4-beta, it was working until alpha6

- version `latest`
- components: `Dropdown`

### Steps to reproduce issue

Here is the codepen https://codepen.io/deepu105/pen/oGxrdM

**Comment by deepu105** [comment]
FYI we are using this in our new React support for JHipster https://github.com/jhipster/generator-jhipster/tree/jh-react

**Comment by TheSharpieOne** [comment]
Bootstrap v4 beta support has not been publish just yet.
See #574 and #487

**Comment by deepu105** [comment]
any approximate ETA?

**Comment by deepu105** [comment]
or plans for a beta release?

**Comment by TheSharpieOne** [comment]
reactstrap@5.0.0-alpha.0 has been published to npm using the `next` tag. It can be installed using `npm install reactstrap@next`

**Comment by TheSharpieOne** [comment]
Closing in favor of #487

**Comment by deepu105** [comment]
Awesome thanks
