### ISSUE TITLE
<input> reference for Input 

### ISSUE THREAD

**Issue by Linell** [reactstrap/reactstrap#583]
### Issue description

I'm attempting to make a hidden file input where, when I click a button, the file input dialog shows up. The codepen link below illustrates the problem pretty well -- when you click the button nothing happens. However, when you change the `<Input>` to a basic `<input>` everything works just like you'd expect.

Is there a way to reference the basic `<input>`? Not a huge issue for me here since the input doesn't need to look fancy anyway, but could be an issue for other applications.

- version `#4.8.0`
- components: `Input`

### Steps to reproduce issue

Check out [this](https://codepen.io/anon/pen/xXOyoE) pen. Clicking the button does nothing at first, but once you change the `Input` to `input` everything works as expected.

**Comment by TheSharpieOne** [comment]
With the way react works, `ref` is consumed by react and not passed down to the component. The `ref` your getting is the reference to reactstrap's `Input` component and not the DOM `input`. This is a common issue in libraries which wrap components and they have to expose a new/custom prop to be used by the developer to get a reference to the DOM.

In v4.8.0 you can provide `getRef` the same way as `ref` and it will return a reference to the DOM `input`. We just pass [`getRef` as a `ref` to the `input` `Input` creates](https://github.com/reactstrap/reactstrap/blob/0bac1f496d8f6e2472bbbcd9958ece1218173f01/src/Input.js#L75)

Note: In v5, `getRef` is changing to `innerRef` to better line up with other libraries.

This is mostly a documentation issue as `Input`'s props are not documented, including `getRef`

**Comment by TheSharpieOne** [comment]
I have updated the docs on the v5 branch which should resolve the documentation issue.

**Comment by 416serg** [comment]
As per https://reactjs.org/docs/refs-and-the-dom.html could `innerRef` be updated for `react16.3+` and be able to take in a `React.createRef()` object?

Thanks 😃

**Comment by TheSharpieOne** [comment]
@416serg, I just ran into that myself and opened #947

**Comment by 416serg** [comment]
@TheSharpieOne for now, got around it by doing `nameRef = React.createRef();` and then `innerRef={input => (this.nameRef = input)}` so you have access to `this.nameRef.value`
