### ISSUE TITLE
Popper performance with many dropdowns

### ISSUE THREAD

**Issue by GaelGRIFFON** [reactstrap/reactstrap#584]
### Issue description
Hi all,

I have more than 100 dropdown on a page, and since I switched to reactstrap v5 (to try bootstrap 4-beta), I have problems of performance when I scrool.
I think this is a problem with Popper (open the example below, check performance with Chrome Dev Tools), but I have no idea how to go further.
Any idea?

- version `5`
- components: `Dropdown`

### Steps to reproduce issue

https://codepen.io/anon/pen/LzRYEW

**Comment by GaelGRIFFON** [comment]
Oh and, no problem with standard bootstrap:
https://jsfiddle.net/usj5sunw/

Seems to only appear with react/reactstrap.

**Comment by TheSharpieOne** [comment]
I meant to fix this... well not this issue exactly (I didn't think it would cause an issue), but the thing which is causing this issue.
This is why it is good to release alpha version and get things in front of people to play with.
Thanks for reporting this, I will address this in the next alpha.

**Comment by TheSharpieOne** [comment]
reactstrap@5.0.0-alpha.1 has been release with a fix for this. Here is your example but with 5.0.0-alpha.1: https://codepen.io/anon/pen/NabxER Scrolling looks a lot more smooth for me; can you confirm the same for you?

**Comment by GaelGRIFFON** [comment]
Yes this is ok!

Thanks!
