### ISSUE TITLE
Navbar component always shows toggler

### ISSUE THREAD

**Issue by meeoh** [reactstrap/reactstrap#587]
### Issue description
I've been using the navbar component for a while now. But for some reason its staying collapsed no matter what size of the window. I've even copy and pasted the basic sample in to my code and it still stays collapsed instead of displaying all the `NavItems`. Here is my current setup

```
<Navbar className='promo-signin-bar' light toggleable>
    <NavbarToggler right onClick={this.toggleNavbar} />
    <Collapse isOpen={this.state.isNavbarOpen} navbar>
        <Nav navbar className='row top-nav' style={{marginLeft: '0', marginRight: '0'}}>
                <NavItem>...</NavItem>
                <NavItem>...</NavItem>
                <NavItem>...</NavItem>                              
        </Nav>
    </Collapse>
</Navbar>
```

**Comment by TheSharpieOne** [comment]
You need to make sure you are using the reactstrap v5 alpha with bootstrap v4-beta OR reactstrap v4.x with bootstrap v4.0.0-alpha.6. You cannot mix and match. I have tried your code with both and it works.
Demos:
[reactstrap v4.8.0 with bootstrap v4.0.0-alpha.6](https://www.webpackbin.com/bins/-KueGB5968kv81qhIJHN)
[reactstrap v5.0.0-alpha.0 with bootstrap v4.0.0-beta](https://www.webpackbin.com/bins/-KueGiPvQF-kR5FeTWET)

Also, the `toggleable` prop has been deprecated in favor of the newly added `expand` prop which lines up with a similar change it bootstrap. `toggleable` works the oposite way of `expand` but we have done our best to ensure it will not break existing functionality (we map `toggleable` values to `expand` values so the menu looks the same at the same breakpoints)

**Comment by meeoh** [comment]
My package.json is as follows:
```
  "dependencies": {
    "reactstrap": "^4.8.0",
    "bootstrap": "^4.0.0-alpha.6",
  }
```

So I think my versions are correct, could something else influence this?

**Comment by TheSharpieOne** [comment]
The `^` is killing you here. You have already opted into the @next releases for bootstrap, so you get the very latest @next there. You haven't done that with reactstrap so you get only the latest stable.

You package.json means this (with the currently published versions)
```
 "dependencies": {
    "reactstrap": "4.8.0",
    "bootstrap": "4.0.0-beta",
  }
```
Double check the packages themselves in your node_modules. Look at their package.json to see the version.(you can also apparently you [`npm list [packagename]`](https://stackoverflow.com/a/10986132/1873485)
Give it a try (here is what I see):
![image](https://user-images.githubusercontent.com/664714/30754359-6a488306-9f90-11e7-927d-92f386cb838f.png)

**Comment by meeoh** [comment]
Yeah, I realized that as soon as I posted it so I deleted it. For people who come across this in the future, I had 
```
 "dependencies": {
    "reactstrap": "^4.8.0",
    "bootstrap": "^4.0.0-alpha.6",
  }
```
Since `^` updates you to the most recent version, it was breaking my navbar

**Comment by mbrochh** [comment]
What is the current status on this issue?

I'm importing bootstrap like this:

```
      <Helmet>
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossOrigin="anonymous"
        />
      </Helmet>
```

The navbar is pretty basic, like this:

```
      <Container>
        <Row>
          <Col>
            <Navbar light>
              <NavbarBrand href="/">Brand</NavbarBrand>
              <NavbarToggler onClick={this.toggle} />
            </Navbar>
          </Col>
        </Row>
      </Container>
```

And the toggler shows up at all times.

**Comment by mbrochh** [comment]
Oh wow! We need the `toggleable` prop on the `NavBar` component.

This is not reflected in the docs here: https://reactstrap.github.io/components/navbar/

**Comment by TheSharpieOne** [comment]
Yes, you can still use `toggleable`, but is deprecated, you will get warning in your console telling you its deprecated and it use `expand`. It's not documented as it's being removed and the new/correct way is with `expand` as documented.

**Comment by mbrochh** [comment]
Oh damn, I completely overlooked the `expand` prop! Thanks for clarification!

**Comment by Bhushan001** [comment]
@TheSharpieOne I am using reactstrap@6.0.1 & bootstrap@4.0.0-alpha.6. but the toggle is always there. any input? I tried downgrading to 4.8.0 but then modal won't work.

**Comment by TheSharpieOne** [comment]
@Bhushan001 You need to use reactstrap 5 or higher with bootstrap@4.0.0 or higher (no alpha or beta)

**Comment by Bhushan001** [comment]
@TheSharpieOne thanks buddy. got it resolved
