### ISSUE TITLE
Dropdown not working with bootstrap@4.0.0-beta

### ISSUE THREAD

**Issue by FredyC** [reactstrap/reactstrap#588]
### Issue description
I am aware that this library officially supports boostrap@4.0.0-alpha6, but this should be probably fixed for beta support. Not only that dropdown menu it won't toggle open, but the whole thing has strange grey color for some reason.

- version `4.8.0`
- components: `DropdownMenu`

### Steps to reproduce issue
I've prepared two identical codesandbox examples except using a different version of Bootstrap css (in resources panel).
[bootstrap@4.0.0-beta](https://codesandbox.io/s/50lx59p76x)
[bootstrap@4.0.0-alpha6](https://codesandbox.io/s/72l7337mwx)

From my short investigation it seems that DropdownMenu was relying on this piece of css, but that's gone in beta version and `show` css class in required directly on dropdown-menu element.
```
.show > .dropdown-menu {
  display: block;
}
```

**Comment by TheSharpieOne** [comment]
`npm i -S reactstrap@next` to get the latest alpha release which has support for bootstrap v4.0.0-beta

Here is your example with the latest alpha release (Note: I used `UncontrolledDropdown` to simpliy it and not need to manage state, but it is the same under the hood):
https://www.webpackbin.com/bins/-KueKuiTBf2Cgitm4n-a

Ref: #487 #574

**Comment by FredyC** [comment]
Ah, thanks. Might be worth mentioning this in the readme for `latest`. I could have saved like hour of my time :/

**Comment by FredyC** [comment]
I was actually looking at the list of branches here in repo, but I haven't seen anything like "next" there. For someone who is not following development around bootstrap, it's hard to understand that v5 is support for beta version of bootstrap 😕

**Comment by TheSharpieOne** [comment]
🔍  
![image](https://user-images.githubusercontent.com/664714/30754727-daab9e20-9f91-11e7-8881-7ad29548341e.png)

**Comment by FredyC** [comment]
Ok, I give up, apparently, you think that current state is friendly to newcomers, so have a nice weekend...

**Comment by udtrokia** [comment]
solve my problem, have a cigarette for rest

**Comment by FredyC** [comment]
I don't smoke ... I just wanted to point out obvious lack of information around here, but it's not wanted here. I won't bother next time preparing detailed bug report with working examples. No appreciation for that in here.

**Comment by TheSharpieOne** [comment]
Detailed bug reports with examples are awesome, but you can save time by checking to see if it has already been reported.
Dropdowns not working with bootstrap 4 beta have several issues already open. Even if there wasn't an alpha with a fix and no documentation about it, you should check to make sure you are not creating a duplicate issue.
I don't mean to be rude, but there was just a flood of new issues for the same stuff (fixed or not) and it's tiring. And don't get me wrong, I appreciate your inclusion of the examples and actually triage, I wish the other issues were as good.
I apologize for being short with my screenshot of the github search bar, I have been putting effort into the v5 (pretty much the only person) and the late nights (the only time I get for this) have made me a bit short fused.
I hope you continue to use and support reactstrap.

**Comment by FredyC** [comment]
> Detailed bug reports with examples are awesome, but you can save time by checking to see if it has already been reported.

I could save even more time if there would be a simple announcement in the README, that beta version is supported under `next` dist tag. It would be even less tiring for you ultimately. Instead of explaining all the time, most people would see the message and understand the problem.

Right now when someone comes here there is uncertainty what happens if I use the beta version of Bootstrap? It's more stable, right? Why would I stick to alpha version? Obviously, I am not only one asking these questions since there are so many duplicates... That's my point of view as a user.

Honestly, I tried searching initially, but since I am not familiar with this project, nor bootstrap, I just wasn't sure what to look for.

**Comment by TheSharpieOne** [comment]
Let me break it down since you forced the issue. This has nothing to do with the alpha release, Even the alpha release didn't exist or you couldn't find anything about it (and since I am talking about duplicate issues) what you would have found was #581, #574, #487, #549, #569, #545.

>Honestly, I tried searching initially, but since I am not familiar with this project, nor bootstrap, I just wasn't sure what to look for.

You don't have to be familiar with something to search for it; that is pretty much what search is for. You only have to be familiar enough with a site (such as github itself) to know where the search bar is (which may be why I included a screenshot. :wink:)

I found the issues above looking for the word "dropdown". What also would have brought back results: "dropdown beta", "dropdown bootstap beta", "BS4 beta", "bootstrap4 beta", "bootstrap 4 beta",, "bootstrap beta", "bootstrap@4.0.0-beta", "bootstrap 4.0.0-beta", "beta", and probably more since these are just variations of the title of this ticket (terms which you were familiar enough with to create).

So now I am curious, what exactly did you search for? In fact, I am so curious that I might change the issue template to include a checkbox to indicate that you search and couldn't find anything and ask them to provide the search terms they used.

**Comment by FredyC** [comment]
I don't really remember what I was searching for, but trust me, I am really not a guy who goes straight to reporting issues without giving it any thought. My point here is why to even force users to use search if all you need to do is add one sentence to readme? But I already suggested it twice and if you don't agree with such approach, I don't have anything else to say here.

**Comment by dfloratos** [comment]
His they changed the css file from alpha to beta.
You have to add 
```
.show > .dropdown-menu {
  display: block;
}
```
to your css file project
