### ISSUE TITLE
why my {data-src} in <Media> doesn`t work even less a warning

### ISSUE THREAD

**Issue by udtrokia** [reactstrap/reactstrap#591]
### Issue description

- version `#4.8.0`
- components: `Media`

### Steps to reproduce issue

-- bootstrap version `^3.3.7`

```javascript
 <Media 
    object 
    data-src="http://localhost:3600/avatar/0009" 
    alt="Generic placeholder image">
</Media>

```

**Comment by TheSharpieOne** [comment]
This library is for bootstrap v4. You should use react-bootstrap if you need bootstrap v3 support.

**Comment by udtrokia** [comment]
```javascript
    <img src="http://localhost:3600/avatar/0009" alt="avatar"/>//works
    <Media
       object
       data-src="http://localhost:3600/avatar/0009"
       alt="Generic placeholder image" />
    </Media>//not
```
well, I updated my bootstrap to ^4.0.0-beta, it still failed... with my offset went to mess :(

**Comment by TheSharpieOne** [comment]
Bootstrap v3 and v4 are drastically different, especially when it comes to spacing thanks to the change from floats to flexbox. Media itself now relies on the new flexbox and spacing utility within bootstrap 4. There is an open an issue to determine how to better address this within reactstrap, but for now just like bootstrap itself, you have to apply those classes yourself. As for the image, just use src. The docs use placeholder.js which uses the data-src to add the fake images. We probably need to not use that or at least not show it being used in the example code which displays.

**Comment by udtrokia** [comment]
Nice~ it works!!  I love your avatar very much! @TheSharpieOne
