### ISSUE TITLE
Add value to <input> with onChange freezes input

### ISSUE THREAD

**Issue by mweiczorek** [reactstrap/reactstrap#593]
The Input component value becomes read-only when an onChange or onInput prop are passed with a value property. Is there a way to add a value to the input? The use case is a user preference form where there are default values (e.g. name, email) present for editing.

- version 4.8.0
- components: Input

Usage:

    <Input
          ref={(f) => this.emailField = f }
          type="text"
          value={this.state.value.email} // <-- causes issue
          placeholder="E-mail Address"
          onChange={this.setEmail.bind(this)}
          className="bg-icon icon-login-inverse" />

**Comment by TheSharpieOne** [comment]
This is how react works. React has a separate prop, `defaultValue` for setting the initial value for an uncontrolled input.
See https://github.com/reactstrap/reactstrap/issues/543#issuecomment-331005424

**Comment by mweiczorek** [comment]
Now don't I feel stupid.. I'm new to the React ecosystem. Thanks for replying quickly.
