### ISSUE TITLE
Dropdown menu doesn't work with BS 4.0 beta

### ISSUE THREAD

**Issue by autarch** [reactstrap/reactstrap#596]
From what I can see, the way that dropdown menus work must have changed since the v4 alpha 6. Previously, showing a dropdown menu involved making sure that it was contained with an element that had the `show` class.

Now you also have to make sure that the `div` containing the menu is given the `show` class as well.

I was able to hack around this by adding the following SASS to my styles:

```
.show > .dropdown-menu {
    display: block;
    position: absolute;
}
```

But I think the better fix is to fix the component to do the right thing.

**Comment by autarch** [comment]
Digging in further it looks like this change may be related to the use of [popper](https://www.npmjs.com/package/popper.js) in the beta.

**Comment by autarch** [comment]
Also see https://github.com/twbs/bootstrap/commit/54a8ab40111dacdf50fad22e6f36d2801ba653c9 for the relevant commit in bootstrap.

**Comment by TheSharpieOne** [comment]
Dulipcate of #581, Dulipcate of #549, Dulipcate of #569, Dulipcate of #545, Dulipcate of #588
Tracked in #487 
PR: #574
