### ISSUE TITLE
Can't put an icon as part of buttonLabel on modal

### ISSUE THREAD

**Issue by tatsujb** [reactstrap/reactstrap#599]
If you create a modal in your app  : 

`<ModalConfirmDelete resetting={this.resetting} buttonLabel="Delete" />`

you can't place an icon before the label as you would with a button : 

`<Button><i className="fa fa-trash-o" /> delete</Button>`

And that's really annoying because the two end up looking exactly the same except for the missing icon.

`<ModalConfirmDelete resetting={this.resetting} buttonLabel="<i className='fa fa-trash-o' /> Delete" />`

is not interpreted and will literally add that text to the label.

**Comment by TheSharpieOne** [comment]
Quoted strings are always string literals. Try with curly brackets instead. Also in react <16 you will need to wrap the `i` tag and the words that comes next to it in something, like a `span`. 

```jsx
 <ModalConfirmDelete resetting={this.resetting} buttonLabel={<span><i className="fa fa-trash-o" /> Delete</span>} /> 
```

**Comment by tatsujb** [comment]
oh.
of course.

my bad still learning.
