### ISSUE TITLE
Child ref null in componentDidUpdate of parent containing a Modal component

### ISSUE THREAD

**Issue by michaeldzjap** [reactstrap/reactstrap#601]
### Issue description

- version `#5.0.0-alpha.2`
- components: `Modal`, `ModalBody`, `ModalHeader`

After updating to React 16 I noticed that a child component of `ModalBody` containing a ref is `null` in the `componentDidUpdate()` lifecycle method. Not sure if this is caused by React v16 or if it is due to reactstrap. It seems wrong to me, but perhaps there is a good reason for this that I am overlooking? When you close the modal again you do see that the ref is defined.

### Steps to reproduce issue

See [this](https://codesandbox.io/s/xo428w6pnz) CodeSandbox. Open the JS console and click the button to open the modal. The console prints `null` (tested in latest Chrome).

**Comment by TheSharpieOne** [comment]
This is related to https://github.com/facebook/react/issues/9808
It looks like we will need to switch to `unstable_createPortal` but provide a fallback to `unstable_renderSubtreeIntoContainer` when `unstable_createPortal` doesn't exist to keep supporting 15.x.

**Comment by Chima1707** [comment]
@TheSharpieOne sure that was the reason. If you dont mind, can i work on this for this hacktoberfest?

**Comment by virgofx** [comment]
@TheSharpieOne Even better ... `ReactDOM.createPortal(child, container)`   which marked as stable. Just need to change requirement to >= R16. Maybe we can do it next version?

**Comment by TheSharpieOne** [comment]
Sure, go for it. I would also look at how material UI did itc(I saw a PR with something similar to what we need)
Also, yeah, I saw the stable name and that it was aliased to the unstable name. For better compatibility I would use the unstable name (support the R16 betas)

**Comment by Chima1707** [comment]
Ok, guys will send a fix likely this weekend.

**Comment by TheSharpieOne** [comment]
@Chima1707 how is this coming along?

**Comment by Chima1707** [comment]
@TheSharpieOne am investigating the problem, will give my update by the end of tomorrow

**Comment by leetercola** [comment]
Curious about status, this is currently breaking unit tests in jest & enzyme with react 16.

**Comment by TheSharpieOne** [comment]
As am I. @Chima1707 any update? If you are not able to complete it, it's not a big deal, just let us know.

**Comment by Chima1707** [comment]
I have not been able to complete it, please can someone take a look at it?

**Comment by martindavid** [comment]
@TheSharpieOne is anyone working on this at the moment? I'd like to give it a try?

**Comment by TheSharpieOne** [comment]
@martindavid go for it.

**Comment by thimo1** [comment]
are there any news on that issue?

**Comment by fantua** [comment]
Looks like it's still doesn't resolved. 

According to [this](https://github.com/reactstrap/reactstrap/pull/645#issuecomment-342696266) comment I can try to: 
1. Use [react-portal](https://github.com/tajo/react-portal) (uses React v16 and its official API for creating portals; has a fallback for React v15).
2. Refactor code base for `Modal` component.
3. Implement better fix for #761.

Can I take a look a this?

cc @TheSharpieOne @martindavid

**Comment by TheSharpieOne** [comment]
@fantua go for it
