### ISSUE TITLE
DropdownMenu is failing on Popper

### ISSUE THREAD

**Issue by Rootmafia** [reactstrap/reactstrap#606]
**Issue description**

- version "reactstrap": "next",
- components: DropdownMenu
- react version   "^16.0.0",

DropdownMenu is failing on "Popper" library: 

`
import {Dropdown, DropdownMenu, DropdownItem} from 'reactstrap'
`

`
 <Dropdown sOpen={isFilterOpen} toggle={toggleFilter}>
   <a onClick={toggleFilter}>
           Click
  </a>
     <DropdownMenu className='dropdown-menu-right' style={{width: "220px"}}>
           <DropdownItem>
                Element
            </DropdownItem>
        </DropdownMenu>
  </DropdownMenu>`

When i click on element And i'm **getting**:

`popper.js:2325 Uncaught TypeError: Cannot read property 'jquery' of undefined
    at new Popper (popper.js:2325)
    at Popper._createPopper (Popper.js:173)
    at Popper._updatePopper (Popper.js:152)
    at Popper.componentDidMount (Popper.js:129)
    at commitLifeCycles (react-dom.development.js:11505)
    at commitAllLifeCycles (react-dom.development.js:12294)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
    at invokeGuardedCallback (react-dom.development.js:1195)
    at commitAllWork (react-dom.development.js:12415)
Popper @ popper.js:2325
_createPopper @ Popper.js:173
_updatePopper @ Popper.js:152
componentDidMount @ Popper.js:129
commitLifeCycles @ react-dom.development.js:11505
commitAllLifeCycles @ react-dom.development.js:12294
callCallback @ react-dom.development.js:1299
invokeGuardedCallbackDev @ react-dom.development.js:1338
invokeGuardedCallback @ react-dom.development.js:1195

react-dom.development.js:8305 The above error occurred in the <Popper> component:
    in Popper (created by DropdownMenu)
    in DropdownMenu (at Header.js:61)
    in div (created by Manager)
    in Manager (created by Dropdown)
    in Dropdown (at Header.js:52)
    in li (at Header.js:51)
    in ul (at Header.js:50)
    in header (at Header.js:35)
    in Header (created by Connect(Header))
    in Connect(Header) (created by Route)
    in Route (created by withRouter(Connect(Header)))
    in withRouter(Connect(Header)) (at HomeContainer.js:19)
    in div (at HomeContainer.js:18)
    in Home (created by Connect(Home))
    in Connect(Home) (at WrapHome.js:7)
    in WrapHome (at Menu.js:58)
    in main (at PrivateRoute.js:11)
    in Route (at PrivateRoute.js:6)
    in PrivateRoute (at App.js:34)
    in Switch (at App.js:32)
    in div (at App.js:30)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:28)
    in App (created by Connect(App))
    in Connect(App) (at index.js:14)
    in Provider (at index.js:13)
`

**Comment by TheSharpieOne** [comment]
You need to use `DropdownToggle` for the element which the `DropdownMenu` will "attach" to when it opens. You can still style it the way you have it and output an `<a>` by using `tag="a"` on `DropdownToggle` like this (though, I would recommend not using `tag="a"` since semantically it identifies a navigatable link):

```jsx
import {Dropdown, DropdownMenu, DropdownItem, DropdownToggle} from 'reactstrap'

// .... 

<Dropdown sOpen={isFilterOpen} toggle={toggleFilter}>
  <DropdownToggle tag="a"> Click </DropdownToggle>
  <DropdownMenu right style={{width: "220px"}}>
    <DropdownItem> Element </DropdownItem>
  </DropdownMenu>
</Dropdown>

//....
```

Note: `DropdownMenu` has a prop `right` which when set tells the menu to open to the right. There is no need to add the class manually. In fact, doing it manually will not work so great as the prop is used to help [popper.js's placement](https://github.com/reactstrap/reactstrap/blob/72fb7142cf1243a06a7fc64eb0fb1e0ba1d5d7d6/src/DropdownMenu.js#L44-L45)

**Comment by Rootmafia** [comment]
@TheSharpieOne 
Thank you very match for you help, it helped me,

P.S. Iit was the quickest answer on github in my life :)
