### ISSUE TITLE
Navbar expand & collapse no longer working w 5.0.0-alpha.3

### ISSUE THREAD

**Issue by johnpickly** [reactstrap/reactstrap#613]
### Issue description

- version `#5.0.0-alpha.3`
- components: `Navbar`

Hello, I recently upgraded to v5.0.0-alpha.3 - mainly to get rid of the tether warnings. In doing so, the NavBar stopped working.. The NavBar no longer expands and collapses as expected with previous versions... Are there any updated docs for 5.0.0-alpha.3 available showing how to get this working as seen here: https://getbootstrap.com/docs/4.0/components/navbar/ (collapse example)?

Here's my basic code snippet:

```
<Navbar light expand>
  <div className="container">
    <NavbarToggler className="navbar-toggler-right" onClick={this.toggle} />
    <NavbarBrand tag={Link} to="/xxx">XXX</NavbarBrand>
    <Collapse isOpen={this.state.navbarTogglerOpen} navbar>
      <Nav navbar>
        <NavItem>
          <NavLink tag={Link} to="/dashboard">Stuff</NavLink>
        </NavItem>
      </Nav>
      }
      <Nav className="ml-auto" navbar>
          <NavDropdown isOpen={this.state.dropdownOpen} toggle={this.dropDownToggle}>
            <DropdownToggle nav caret>
              {currentUserProfile.displayName || currentUserProfile.email}
            </DropdownToggle>
            <DropdownMenu right>
              <DropdownItem tag={Link} to={`/@${currentUserProfile.username}`}>
                My Profile
              </DropdownItem>
            </DropdownMenu>
          </NavDropdown>
        }
      </Nav>
    </Collapse>
  </div>
</Navbar>
```
The above used to work fine before upgrading to v^5.0.0

If I'm missing the new docs, please let me know. Thanks again

Thanks

**Comment by TheSharpieOne** [comment]
the `expand` prop on `Navbar` looks to be the issue, `expand` without a value indicates that it should always expand. You can provide a breakpoint value (`xs`, `sm`, `md`, `lg`, `xl`) to have it expand at different breakpoints.

Checkout this quick demo using (mostly) your code (I removed things like `Link` and variables which are not important for the demo):
https://codesandbox.io/s/4r5k30xy3w (resize the preview panel to see it change)

**Comment by TheSharpieOne** [comment]
I have updated the docs to show `expand` and remove `toggleable` since it it's use is depracated. I also changed the order of `NavbarBrand` and `NavbarToggler` so that it looks more like bootstrap's docs (and updated the navbar on the docs site itself).

**Comment by johnpickly** [comment]
**thank you**

**Comment by Suban5** [comment]
I got the following warning
Warning: Unknown prop `expand` on <nav> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop  in nav (created by Navbar).

My NavLinks does not open on Large screen.
Please tell me how to fix it?

**Comment by TheSharpieOne** [comment]
@Suban5 use the reactstrap alpha by following the installation instructions on the readme and/or the documentation site.
