### ISSUE TITLE
FormText tag prop cannot take in React element

### ISSUE THREAD

**Issue by afholderman** [reactstrap/reactstrap#616]
- components: `FormText `
- reactstrap version `5.0.0`

FormText cannot take in a react element as a tag. This is inconsistent with other text items like CardText and ListGroupItemText

**Comment by TheSharpieOne** [comment]
This is a leftover from a while ago. It's just the PropType which needs to be updated. An easy fix for anyone wanting to submit a PR for hacktoberfest.

**Comment by afholderman** [comment]
I'll submit a PR for it, this causes issues when using TypeScript since the @types definitions adhere to the PropType.

**Comment by TheSharpieOne** [comment]
Awesome, thanks.
