### ISSUE TITLE
Lots of NavDropDown components on page

### ISSUE THREAD

**Issue by deanchalk** [reactstrap/reactstrap#619]
I have a complex NavBar with many NavDropDowns on it. 

The issue I have is that according to the docs, I have to implement a 'toggle' function for each one, which is significantly cluttering up my code.
I expected there to be a way for these NavDropDowns to just open and close when clicked - without having to implement a toggle method and use the component state for the 'isOpen' property.

Is there any kind of 'autoToggle' property available where the dropdown just open and close automatically on user clicks (same as the standard select element in dom) ?

Thanks

**Comment by TheSharpieOne** [comment]
For the most typical use case of dropdowns, there is an uncontrolled component which does what you are looking for. `UncontrolledNavDropdown` which doesn't need isOpen or toggle props. It is documented under the dropdown docs (I think)

**Comment by deanchalk** [comment]
Ahhhhhhh, that's the one I need. Thanks so much :)
