### ISSUE TITLE
Throw error on invalid id

### ISSUE THREAD

**Issue by gforge** [reactstrap/reactstrap#620]
### Issue description

- components: `utils`
- reactstrap version `#5.0.0-alpha.3`
- import method `es`
- react version `#16.0.0`
- bootstrap version `#4.0.0-beta`

### What is happening?

The `getTarget()` fails when an ID contains spaces

### What should be happening?

I would like the `getTarget()` to check and throw an error if the string is incorrect, alternatively use `getElementById()` that is space safe.

### Steps to reproduce issue

From the tooltip example:

```
import React from 'react';
import { Tooltip } from 'reactstrap';

export default class Example extends React.Component {
  constructor(props) {
    super(props);

    this.toggle = this.toggle.bind(this);
    this.state = {
      tooltipOpen: false
    };
  }

  toggle() {
    this.setState({
      tooltipOpen: !this.state.tooltipOpen
    });
  }

  render() {
    const id = "Tooltip Example"
    return (
      <div>
        <p>Somewhere in here is a <a href="#" id={id}>tooltip</a>.</p>
        <Tooltip placement="right" isOpen={this.state.tooltipOpen} target={id} toggle={this.toggle}>
          Hello world!
        </Tooltip>
      </div>
    );
  }
}
```

### Error message in console

```
TypeError: this._target is null
```

### Code

  

Here's a suggested fix:

```
export function getTarget(target) {
  if (isFunction(target)) {
    return target();
  }

  if (typeof target === 'string' && document) {
    let selection = document.querySelector(target);
    if (selection === null) {
      select = document.querySelector(`#${target}`);
      if (selection === null) {
        select = document.getElementById(target);
        if (selection === null) {
          throw new Error(`The target '{target}' could not be identified in the dom, tip: check spelling`);
        }
      }
    }
    return selection;
  }

  return target;
}
```

**Comment by TheSharpieOne** [comment]
Yeah, throwing here could help developers. I don't know if I would go as far as to add the `document.getElementById(target)` check. Yes, is works with space, but no; [spaces are not allowed in ID](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id) attributes, so throwing there should be desired.

**Comment by gforge** [comment]
Yeah, throwing with an informative error should be enough.

**Comment by canotech** [comment]
I have the same error, my id is generate automatically from shortId library and these thrown the next error: main-c4535317c7574c6083af.js:1 The target 'rkaWgUuw2Q' could not be identified in the dom, tip: check spelling
Error: The target 'rkaWgUuw2Q' could not be identified in the dom, tip: check spelling 
`import React from 'react';
import { Tooltip } from 'reactstrap';
import shortId from 'shortid';

export default class TooltipCustom extends React.Component {
  constructor(props) {
    super(props);

    this.toggle = this.toggle.bind(this);
    this.state = {
      tooltipOpen: false,
      id: shortId.generate()
    };
  }

  toggle() {
    this.setState({
      tooltipOpen: !this.state.tooltipOpen
    });
  }

  render() {
    return (
      <span >
        <span><a id={this.state.id}>{this.props.children}</a></span>
        <Tooltip  placement={this.props.placement || 'top'}  isOpen={this.state.tooltipOpen} target={this.state.id} toggle={this.toggle} offset={this.props.offset || 2} autohide={false} delay={10}>
          {this.props.text}
        </Tooltip>
      </span>
    );
  }
}`
