### ISSUE TITLE
React Popper latest doesn't support React 16—need to use fork until it does

### ISSUE THREAD

**Issue by jameswomack** [reactstrap/reactstrap#621]
### Issue description

- reactstrap version `#5.0.0-alpha.3`
- react version `#16.0.0`

### What is happening?

See **"Error message in console"**

### What should be happening?

There should be no warnings regarding transient dependencies when I install Reactstrap

### Steps to reproduce issue

1. Create a project with React 16 & Reactstrap 5.0.0-alpha.3 as deps
2. Execute `npm i`

### Error message in console

```
npm WARN react-popper@0.7.3 requires a peer of react@0.14.x || ^15.0.0 but none was installed.
npm WARN react-popper@0.7.3 requires a peer of react-dom@0.14.x || ^15.0.0 but none was installed.
```

### Relevant links

* [React Popper PR](https://github.com/souporserious/react-popper/pull/59)
* [Reactstrap fork branch](https://github.com/jameswomack/reactstrap/tree/react-popper_react-dom-16)

**Comment by TheSharpieOne** [comment]
Not much we can do about that. I :+1: that PR as soon as it was made. Need @souporserious to merge it and release it.
We could fork it like we did for tether but that seems a bit extreme at this point.

**Comment by souporserious** [comment]
Apologies, I've super busy preparing for a trip to Africa. I'll be gone about a week, but I'll be able to get react-popper sorted when I get back.

**Comment by jameswomack** [comment]
@TheSharpieOne Got it. I’ve forked & upgraded reactstrap & react-popper for use in Semiotic. We’ll use those until they get merged or the packages get otherwise updated.

**Comment by williamoliveira** [comment]
I am having this error when trying to use a Dropdown:

```
Uncaught TypeError: Cannot read property 'jquery' of undefined
    at new Popper (popper.js:2319)
    at Popper._createPopper (Popper.js:173)
    at Popper._updatePopper (Popper.js:152)
    at Popper.componentDidMount (Popper.js:129)
    at commitLifeCycles (react-dom.development.js:11505)
    at commitAllLifeCycles (react-dom.development.js:12294)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
    at invokeGuardedCallback (react-dom.development.js:1195)
    at commitAllWork (react-dom.development.js:12415)
```
is it related?

"react": "^16.0.0",
"react-dom": "^16.0.0",
"reactstrap": "^5.0.0-alpha.3",

**Comment by deltaskelta** [comment]
@jameswomack I am trying to use your fork for the time being by adding it to my dependencies like so...

```json
"reactstrap": "jameswomack/reactstrap#fd9a7df74b7dde095ec9066d49980cddbc7ba74c",
```

but it is just installing a repository with a `package.json`, `README`, `LICENSE` and no code...am I missing something with `npm`?

**Comment by jameswomack** [comment]
@deltaskelta you’re right, I didn’t consider that many newer Node modules don’t run build steps on install from git. It was useful for testing if the change would theoretically work but I’d need to commit the build to the repo or change the package JSON script to have it work without any manual steps

**Comment by TheSharpieOne** [comment]
react-popper has been updated to allow react 16 (thanks @souporserious :heart:). The update has been [released](https://github.com/souporserious/react-popper/releases/tag/0.7.4) and falls within the semver reactstrap uses so you should be able to use it as is now.
