### ISSUE TITLE
Layout property doesn't work

### ISSUE THREAD

**Issue by JonathanMaga** [reactstrap/reactstrap#627]
When i use 
<Col sm={{ size: 'auto', offset: 1 }}>.col .col-sm .col-sm-offset-1</Col>
doesn't work anymore

**Comment by TheSharpieOne** [comment]
offsets have been removed from bootstrap v4-beta so they will not work. They have been added back in the yet to be released bootstrap v4-beta.2

**Comment by iDuuck** [comment]
I would suggest to go back to the alpha release until they are added back.

**Comment by TheSharpieOne** [comment]
Closing this as it is an upstream issue in bootstrap which has been resolved. Just make sure you are using bootstrap v4-beta.2
