### ISSUE TITLE
Don't hide dropdown on clicked DropdownItem

### ISSUE THREAD

**Issue by Rootmafia** [reactstrap/reactstrap#632]
How can i prevent from hiding when i click on **DropdownItem**?

**Comment by TheSharpieOne** [comment]
set the `toggle` prop to `false` on the `DropdownItem`:
```jsx
<DropdownItem toggle={false}>...</DropdownItem>
```

Sadly, this is not documented. In fact, none `DropdownItem`'s props are documented in the properties section on the [Dropdown docs](https://reactstrap.github.io/components/dropdowns/); it's completely missing.

**Comment by Visovsiouk** [comment]
Can I take up this task?

**Comment by TheSharpieOne** [comment]
@Visovsiouk yes, please.

**Comment by iad42** [comment]
Is there any solution to prevent toggling `DropdownItem` when a `Modal` is opened by clicking on `DropdownItem` ?

**Comment by iad42** [comment]
Could you help me with the similar problem?

The code is like this:

```
<ButtonDropdown toggle={this.toggle_dropdown}>
    <DropdownMenu>
    <DropdownItem onClick={this.toggle_modal} toggle={false}>
          <Modal></Modal>
    </DropdownItem>
    </DropdownMenu>
</ButtonDropdown>
```

When `dropdownItem` calls `Modal`, it is created as usual, but clicking in any area calls `this.toggle_dropdown`, which closes modal and dropdown.
Any help would be really appreciated!

Thanks

**Comment by iad42** [comment]
Basically the question if there is any possibility to prevent dropdown toggle for all descendants.

**Comment by TheSharpieOne** [comment]
Is it possible with how you are using the components to not have your modal as a child of `DropdownItem` and `DropdownMenu`. The thing which is happening that the modal itself gets attached to the body, outside of the `DropdownItem` so clicking it triggers the callback of clicking outside of the dropdown which closes the dropdown and thus unmounting it and all of it's children, including the `Modal`.

This should work
```jsx
<ButtonDropdown toggle={this.toggle_dropdown} isOpen={this.state.dropdownOpen}>
  <DropdownToggle caret>
    Button Dropdown
  </DropdownToggle>
  <DropdownMenu>
    <DropdownItem onClick={this.toggle_modal}>
      Open the modal
    </DropdownItem>
  </DropdownMenu>
  <Modal isOpen={this.state.modalOpen} toggle={this.toggle_modal}>
    Stuff and junk. Use the Modal components.
  </Modal>
</ButtonDropdown>
```
live demo: https://www.webpackbin.com/bins/-KwKwHAXW_jnckqiZeZe

Other than that, you'll have to handle it in your `toggle_dropdown` function to determine when it should close or not probably based on if the modal is open.
To the question of "any possibility to prevent dropdown toggle for all descendants", that control is completely in your hands, with the function you provide to toggle.

**Comment by iad42** [comment]
Oh! It was obvious indeed. Thank you for giving such a verbose answer. 
I will try to make `Modal` and `DropdownMenu` at the same level of hierarchy, as your example works great indeed. Thanks again!

**Comment by teddy-error** [comment]
Should dropdownHide be triggered when elements outside of the Nav are interacted with- like a Modal?

**Comment by TheSharpieOne** [comment]
Yes, the toggle is trigger when the document is clicked so that it closes when users click off of it (or at least triggers the callback, it is up to the developer to change the isOpen prop value to close it) . It works the same as bootstrap (and the UncontrolledDropdown also takes this out of the developer's hands to work exactly like bootstrap)

**Comment by jonasgrilleres** [comment]
Hi,
does toggle={false} prevents all focus inside the DropdownItem?
I have an issue with an input that can't be typed

Thanks,

**Comment by jonasgrilleres** [comment]
thanks it works now
