### ISSUE TITLE
[Question] Does this library make use of bootstrap.css in the background or no? 

### ISSUE THREAD

**Issue by fxantopraveen** [reactstrap/reactstrap#639]
### Issue description

- components: `name`
- reactstrap version `#x.x.x`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `#x.x.x`
- bootstrap version `#x.x.x`

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by TheSharpieOne** [comment]
It add the bootstrap classes to the rendered DOM, but this library does not include nor use bootstrap.css (except for the documentation site)
