### ISSUE TITLE
Question: Screenshot testing?

### ISSUE THREAD

**Issue by amilajack** [reactstrap/reactstrap#64]
Wondering if screenshot testing would be a welcome addition to this project.

**Comment by eddywashere** [comment]
What kind of tests are you thinking about adding? I would say yes, in general. I'm concerned about the complexity it adds to the project vs the value it provides. I'd love to have assurance about what browsers this is working in and I think right now it is assumed to be working across what react and bootstrap 4 supports.

**Comment by amilajack** [comment]
Good point. I think this would add too much complexity. Closing for now.
