### ISSUE TITLE
Make CarouselItem accept children of any type

### ISSUE THREAD

**Issue by GitShaffi** [reactstrap/reactstrap#641]
### Issue description

Getting the below warning when I try to use my own element with CarouselItem.
```
Invalid prop `children.type` of value `div` supplied to `CarouselItem`, expected one of [null].
```

- components: `CarouselItem`
- reactstrap version `5.0.0-alpha.3`
- react version `15.6.1`
- bootstrap version `4.0.0-beta`

Please make it accept an element or node, so that we are able to customize the CarouselItem.

**Comment by joao-alberto** [comment]
Can I do it?

**Comment by TheSharpieOne** [comment]
@joao-alberto go for it

**Comment by TheSharpieOne** [comment]
@joao-alberto today is the last day of hacktoberfest

**Comment by yyynnn** [comment]
so any progress guys?

**Comment by tim-stasse** [comment]
Pull request up #735
