### ISSUE TITLE
Popover Error: "export 'PopoverHeader' was not found in 'reactstrap'

### ISSUE THREAD

**Issue by sjorsvanheuveln** [reactstrap/reactstrap#647]
- reactstrap version 4.8.0

I'm trying to implement a Popover component, but I get an error that PopoverHeader and PopoverBody are not included in the reactstrap library. HotReloading is throwing me this error:

```
./src/components/shared/Video.jsx
123:10-23 "export 'PopoverHeader' was not found in 'reactstrap'
./src/components/shared/Video.jsx
128:10-21 "export 'PopoverBody' was not found in 'reactstrap'
```

 I've implemented it in the same way as in the examples. What am I doing wrong here?

**Comment by TheSharpieOne** [comment]
Those only exist in the newest version which currently is in alpha and needs to be installed using the `@next` tag.
v4 uses the bootstrap alpha.6 names: PopoverTitle and PopoverContent

**Comment by sjorsvanheuveln** [comment]
Thanks.

**Comment by Sahero** [comment]
I am using latest version "reactstrap": "^5.0.0-beta.2" but still getting the same error.

**Comment by TheSharpieOne** [comment]
Delete your node modules directory and rerun npm install

**Comment by Sahero** [comment]
I did that but still getting the same error. I am using `PopoverTitle` and `PopoverContent` for now.
