### ISSUE TITLE
How to add tabIndex to modal close button

### ISSUE THREAD

**Issue by ogheo** [reactstrap/reactstrap#652]
I want to add tabIndex to modal close button, is there a way to add it?

Thanks.

**Comment by TheSharpieOne** [comment]
Currently, no, at least not when using `ModalHeader`. The only workaround is to just can create your own header to achieve this (It's not too complex of a shape).

I see this type of issue a lot. We output complex components which render more than one element and there is often no way to affect the props of those elements (only 1 element gets the props/attributes spread). We often single out individual prop to be added to these other elements (such as `closeAriaLabel ` for this particular button). We should have a better standard for apply any prop/attribute to any element which is rendered. The only way I can thing of would be to have the ability to pass objects which just get spread onto the target element.

For instance, for this button we could have a prop on ModalHeader called `closeButtonProps` which accepts an object which we just spread onto the Button. We can even put the current props in defaultProps and end what with something like:

```jsx
<button onClick={toggle} {...closeButtonProps} className={mapToCssModules(classNames('close', closeButtonProps.className), cssModule)}>
```
