### ISSUE TITLE
autoPlay={false} doesn't work

### ISSUE THREAD

**Issue by fadehelix** [reactstrap/reactstrap#653]
### Issue description

- components: `UncontrolledCarousel`
- reactstrap version `#5.0.0-alpha.3`
- import method `es` 
- react version `#16.0.0`
- bootstrap version `#4.0.0-beta`

### What is happening?
If I set `autoPlay={false}` then:
- Carousel still switch slides
- I got a warning in the DevTools console:
```
proxyConsole.js:54 Warning: Failed prop type: Invalid prop `ride` of value `false` supplied to `Carousel`, expected one of ["carousel"].
    in Carousel (created by UncontrolledCarousel)
    in UncontrolledCarousel (at Slider.jsx:70)
    in div (at Slider.jsx:69)
    in Slider (at PageHome.jsx:35)
    in div (at PageHome.jsx:35)
    in div (at PageHome.jsx:34)
    in PageHome (created by Route)
    in Route (at App.jsx:17)
    in Switch (at App.jsx:16)
    in main (at App.jsx:15)
    in div (at App.jsx:11)
    in App (at index.js:10)
    in Router (created by BrowserRouter)
    in BrowserRouter (at index.js:10)
```
### What should be happening?
Carousel should only display the first slide all the time, unless the user change slides manually.

**Comment by kumar342** [comment]
const Example = () => <UncontrolledCarousel items={items} interval={false} />

set interval is "false"  in uncontrollable carousel.

Its Working..............................................................

**Comment by kumar342** [comment]
const Example = () => <UncontrolledCarousel items={items} interval={false} />;

**Comment by kumar342** [comment]
interval = {false}
