### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by TheSharpieOne** [reactstrap/reactstrap#66]
I have noticed that while there is an eslintrc, many of the files have linter errors.
![image](https://cloud.githubusercontent.com/assets/664714/17251614/816030f2-5577-11e6-9291-a83be4cb602d.png)

I am not sure if the eslintrc would need to be updated to match the particular code-style used or if the code should be updated to make the linter happy.

It's no big deal, just wanted know which direction to go.

**Comment by amilajack** [comment]
Adding a linter would be a good idea, in my opinion

**Comment by TheSharpieOne** [comment]
Well, the linter is already there, but it doesn't seem like it is being ran or that people are trying to follow the styles it is configured for.

**Comment by amilajack** [comment]
Usually what I do is add the linter to the tests

**Comment by eddywashere** [comment]
Definitely an issue. It's there but was never ran as part of npm test. I kept wanting to clean up but it wasn't a top priority. Feel free to update/fix. Semicolons are my only ask 🙏 . Not sure if it's worth adding to watch task, I think letting the editor throw warnings is the best integration for dev and having proper exit on failures when running npm test. Open to feedback on this.

**Comment by TheSharpieOne** [comment]
This was fixed in #89
