### ISSUE TITLE
<Input type="select"> size attribute don't work

### ISSUE THREAD

**Issue by tafkanator** [reactstrap/reactstrap#660]
### Issue description

if using `<Input type="select" size="5">`
then in DOM, size attribute is not applied

- components: `Input `
- reactstrap version `5.0.0-alpha.3`
- react version `16.0.0`
- bootstrap version `4.0.0-beta`

### Code

https://codesandbox.io/s/504m2rw7lp

**Comment by gergely-nagy** [comment]
Can I do it?

**Comment by TheSharpieOne** [comment]
Sure, but the reactstrap size prop goes to the bootstrap size for input size and not the html size.
Also size is only used for multiple select (AFAIK), so maybe we can have multiple be a boolean or a number and when it is a number, pass that number to the raw underlying select.

**Comment by gergely-nagy** [comment]
Thanks for your quick reply, @TheSharpieOne ! The **size** attribute is not only used for multiple select.
Please refer to the link below.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-size
So  can we use the size prop for html attribute not just for bootstrap size?

**Comment by TheSharpieOne** [comment]
Maybe we should rename the one that determines the bootstrap class and just pass size through. Not too sure what to call it though

**Comment by gergely-nagy** [comment]
Can be renamed to the bsSize.

**Comment by TheSharpieOne** [comment]
That works. We can also deprecated it in a way where if the value of size is a string like lg or sm it will warn and then map it to the class. That way it is not a breaking change

**Comment by pablougas** [comment]
Is there currently any way to add html size to a multiple select when using reactstrap?

**Comment by TheSharpieOne** [comment]
A release was just cut with the changes to allow `size` on input pass through to the DOM. `bsSize` is now used to control the input's bootstrap size class

**Comment by pawel-n** [comment]
It's working now. But I got warning: 
`Warning: Failed prop type: Invalid prop 'size' of type 'number' supplied to 'Input', expected 'string'`

components: Input
reactstrap version 5.0.0-alpha.4
bootstrap version 4.0.0-beta.2

**Comment by TheSharpieOne** [comment]
Use a string such as `size="5"` just like you would for html.

**Comment by pawel-n** [comment]
my bad. Thanks.

**Comment by john-tipper** [comment]
This appears to have regressed and is still a problem. If I use a string such as @TheSharpieOne suggests then I get a TS error:

```
TS2769 
Type 'string' is not assignable to type 'number | undefined'
```

If I use a number then I get no TS errors but I get the warning in the console.
