### ISSUE TITLE
Why do bootstrap-4 doesn't work correct in reactstrap?

### ISSUE THREAD

**Issue by Charlie91** [reactstrap/reactstrap#663]
There is no working offsets for example.
Even the example in [docs](https://reactstrap.github.io/components/layout/
) works incorrect. You can see offsets in blocks but they are not working. Or may be there is something that i not understand?

**Comment by TheSharpieOne** [comment]
The docs have not been updated to use bootstrap v4-beta.2 which brings offsets back. If you are using v4-beta.2 in your development, everything will work.

**Comment by HamadaBrest** [comment]
@Charlie91 Reinstall Bootstrap with this command and it should work
`npm install --save reactstrap@next react react-dom`
