### ISSUE TITLE
Custom checkbox scss style package with reactstrap tags fails to render.

### ISSUE THREAD

**Issue by ArbanNichols** [reactstrap/reactstrap#664]
### Issue description

- components: FormGroup, Label, Input
- reactstrap version 4.80
- react version 15.5.4
- bootstrap version 4.0.0-beta

### What is happening?
I'm attempting to use a scss style from the pretty-checkbox npm package on my checkboxes within a FormGroup. The creator of the library affirms that his customization can be used with bootstrap.

### What should be happening?
The UI in the browser should show a customized checkbox from the pretty-checkbox package but only shows a clickable label with a blank space where the checkbox should be.

### Steps to reproduce issue

1. Used the sample code in different browsers.
2. Initially thought it was because of the AvGroup tag used in other parts of code. Confirmed its the reactstrap tags by isolating the AvGroup tags from the FormGroup tags.

### Error message in console

Complies fine.

### Code
Without the reactstrap tags, the custom checkbox library works fine:
```
 <div className="pretty p-default">
    <input type="checkbox" />
        <div className="state">
            <label>Check</label>
        </div>
 </div>
```

With the reacstrap tags however, the label appears but the custom checkbox doesn't show:
```
<FormGroup check className="pretty p-default">
    <Label check className="state">
       <Input type="checkbox" />{' '}
           Check me out
       </Label>
</FormGroup>
```

package site link: https://lokesh-coder.github.io/pretty-checkbox/

**Comment by TheSharpieOne** [comment]
Reactstrap adds bootstrap classes, your markup which works fine doesn't contain any bootstrap classes, so reactstrap will not help you.
You can use reactstrap alongside with your markup, just  not to generate your markup.
Also you should be using reactstrap v5 (install using `@next`) with bootstrap v4-beta

**Comment by ArbanNichols** [comment]
thank you fro the prompt response. Is there a way to customize the checkbox in reactstrap?

**Comment by TheSharpieOne** [comment]
You can add any attribute and classes you want by just passing the extra attributes and using className, but you cannot really remove the bootstrap classes. Any classes you provide in className will be added to the output along with the bootstrap class.
Reactstrap mostly determines the bootstrap classes and adds them, which is why you cannot remove them. If you don't want them, you can basically just not use reactstrap (in your case, use input instead of Input) and you can get the desired result.

**Comment by ArbanNichols** [comment]
That's unfortunate. I wanted to use the validation features in the availity-reactstrap package with the custom checkbox class but I see now why that would not work. Thanks anyway.

**Comment by TheSharpieOne** [comment]
You can extend the availity reactstrap validation to create custom components which get validated. I do that with react-select and other custom components.
Similar to reactstrap, you can pass a component to the tag prop to AvInput and it will render that. The only caveat is since you have wrapping elements around your input, you would need to pass listeners (onChange, onBlur, onInput) to the input in your component.

**Comment by ArbanNichols** [comment]
Similar to reactstrap, you can pass a component to the tag prop to AvInput and it will render that.

Honestly Sharp I am new to all this and I would not be able to replicate that without an example.

**Comment by TheSharpieOne** [comment]
Open an issue with availity-reactstrap-validation and I'll provide an example there.

**Comment by ArbanNichols** [comment]
https://github.com/Availity/availity-reactstrap-validation/issues/40

**Comment by TheSharpieOne** [comment]
Closing this as it is more related to availity-reactstrap-validation and can be tracked there.

**Comment by chamaraonline** [comment]
Use Bootstrap HTML Ver
<div class="custom-control custom-radio">
  <input type="radio" id="customRadio1" name="customRadio" class="custom-control-input">
  <label class="custom-control-label" htmlfor="customRadio1">Toggle this custom radio</label>
</div>

https://stackoverflow.com/questions/22752116/react-label-element

**Comment by chamaraonline** [comment]
Use HTML version 
https://stackoverflow.com/questions/22752116/react-label-element
`<div class="custom-control custom-radio">
  <input type="radio" id="customRadio1" name="customRadio" class="custom-control-input">
  <label class="custom-control-label" htmlfor="customRadio1">Toggle this custom radio</label>
</div>
`
