### ISSUE TITLE
Closing modal doesn't unlock the main body

### ISSUE THREAD

**Issue by Y-Less** [reactstrap/reactstrap#665]
### Issue description

- components: `Modal`
- reactstrap version `#5.0.0-alpha3`
- import method `npm + import`
- react version `#16.0.0`
- bootstrap version `#4.0.0-beta`

### What is happening?

The modal background isn't clearing to allow access to the main body after closing it.

### What should be happening?

Not that...

### Steps to reproduce issue

1. Open a modal.
2. Close it.

### Error message in console

```
None
```

### Code

https://codepen.io/anon/pen/YEXNMv
 
There might be something else elsewhere in my code that causes this as well, since that link doesn't actually have the same issue, but I get no errors so I'm not sure how to quickly narrow it down.

**Comment by TheSharpieOne** [comment]
Without being able to reproduce the problem, it make the problem difficult to solve. Can you give any more information?
When the issue happens:
1. Does the `<body>` have the class `modal-open`?
2. Are the modal elements still attached to the body?
![image](https://user-images.githubusercontent.com/664714/32225456-aab17390-be1b-11e7-8bca-29b99b882f17.png)
3. What is the value of `isOpen` (use the react dev tools to see the actual value Modal receives)?

**Comment by Y-Less** [comment]
I switched to React 15 and the exact same code didn't have this issue.  I realise the previous information wasn't much help...

**Comment by TheSharpieOne** [comment]
I think this is related to an issue where toggling the modal too quickly caused it to get into a bad state. A fix was added in 2cdf225. I am trying to cut a release, but am running into rollup issues. I'll investigate that when I have time and hopefully get a release out soon for you to test.

**Comment by supergibbs** [comment]
Please test with the latest release and reopen issue if still occurs

**Comment by gustblima** [comment]
Still happening to me.
Using: 
- bootstrap: "4.0.0-beta.3" 
- reactstrap: "5.0.0-beta"
My quick fix was to call: 
```document.getElementsByTagName('body')[0].classList.remove('Modal_modal-open-3Y')```
when the modal is closed but it's a terrible fix haha.
