### ISSUE TITLE
Unable to apply CSS styles to image for CarouselItem and how to use div instead of image

### ISSUE THREAD

**Issue by PSPanesar** [reactstrap/reactstrap#669]
Hi,

I wonder if someone could help me with implementing reactstrap carousel. I am trying to apply CSS to the image itself for CarouselItem but it is not getting applied. For CarouselItem there is a prop for src but because the full img tag is not used I'm not sure how to apply CSS to that. I wonder if someone could help me with that?

I am also building a slider with text but no images for a news feed using Carousel and I'm not sure how to setup the CarouselItems with a div of text instead of a img?

I would really appreciate some help with those two issues. New to reactstrap and amazing resource so trying to implement it in production. Thank you. 

Bw
P

**Comment by TheSharpieOne** [comment]
Currently this cannot be done. the tag is unfortunately hardcoded for this one.
https://github.com/reactstrap/reactstrap/blob/78322b1b624663913d89ec359876dff3d6bb4e74/src/CarouselItem.js#L88

This should be more flexible to support your use-use.

**Comment by gergely-nagy** [comment]
I can do it. Any suggestions are welcome.

**Comment by gergely-nagy** [comment]
If I understand you correctly, we have 2 issues:
- [ ] **1: we should add a custom property to the CarouselItem to apply custom class names in the img tag** 
- [ ] **2: we need to allow the CarouselItems to work without images**
  - [ ] add a prop (bool, not required, default: false)
  - [ ] if the prop is false : we should render the img tag
  - [ ] else : we should render the src prop in a h1 or h2 tag

**Comment by TheSharpieOne** [comment]
We typically use a `tag` prop for allow the component element/tag to be overridden. It accepts a string or function. You can checkout other components for examples.

**Comment by jbmeslin** [comment]
Today i would like use the Carousel to render my own content, "I can write" any child inside the CarouselItem but i got Invalid prop `children.type` of value `div` supplied to `CarouselItem` because the child must be a CarouselCaption, else it works great.

**Comment by udtrokia** [comment]
my advice is crop your images before import
however, carousel, no need to change the size after we settled it done
