### ISSUE TITLE
Documentation doesn't show possible prop values

### ISSUE THREAD

**Issue by edward-hong** [reactstrap/reactstrap#670]
The documentation only shows what the possible props are but it doesn't show what the possible values for those props are. For example, under Navbar, the only value show for the prop Color is "faded" there's no indication what other values are.

**Comment by TheSharpieOne** [comment]
The value can be anything you want it to be. This library does not limit that. The only limitation would be the styles you have, such as bootstrap itself. Bootstrap has predefined colors/values/names (such as primary, secondary, info, warning, danger, light, and dark), but also allows you to extend it to create new colors/values/names (such as accent or anything you want or need). faded, for example, used to exist in bootstrap and have been removed by bootstrap, but you can still use faded if you add the class to your stylesheets yourself. So to answer the question, the possible values depend on how you are using bootstrap and thus cannot be predefined.

**Comment by barbalex** [comment]
Although this issue is closed it is very confusing for new users not to have @TheSharpieOne 's explanation in the docs
