### ISSUE TITLE
How to create different states using a for loop in reactstrap?

### ISSUE THREAD

**Issue by paullam328** [reactstrap/reactstrap#679]
```

      dropDownItems() {
        var listODropDownItems = [];
        var sampleDropDown = [{'name': 'A', 'id': '1'}, {'name':B'', 'id': '2'}, {'name': 'C', 'id': '3'}];

        for (var i = 0; i < sampleDropDown.length; i++) {

            listOfDropDownItems.push(<Label check>
                                         <Input type="checkbox" onClick={this.toggleCheckbox}/>{' '}
                                            {sampleDropDown[i]['name']}
                                     </Label>);
        }
```
Right now, I have to make a bunch of checkboxes using a forloop.  From my understanding, if I am to create a JSON string for each selected checkbox, the best way would be to create a true/false state for each checkbox.  However, is there any possible way to create a for loop and different states that represent each checkbox? (e.g., from the case above, it would be great if the 3 true/false states are generated for name = A, B, and C respectively, using the for loop).  If not, what are the alternative(s) that differentiate between three different checkboxes, that allow me to retrieve their checked/unchecked value, and generate a json string for each of them?

**Comment by paullam328** [comment]
Seems like I gotta answer this question by myself by suggesting a dynamic state creation.
```
inputChangeHandler : function (event) {
    this.setState( { event.target.id  : event.target.value } );
}
```

**Comment by TheSharpieOne** [comment]
This would have been a good question for stackoverflow. While you are using reactstrap, the thing you are trying to do is not specific to reactstrap, but react itself.
Also, to dynamically create object and set variable key names, you need to wrap your variable key name in in brackets in es2015 (AFAIK, it will not work without them)
```javascript
inputChangeHandler : function (event) {
    this.setState( { [event.target.id]  : event.target.value } );
}
```
reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names

Closing this as it seems to be solved and if not, stackoverflow would be a better place to ask.
