### ISSUE TITLE
NPM Install at NPM website vs github repository

### ISSUE THREAD

**Issue by chocomel1** [reactstrap/reactstrap#683]
Hi all, 

The reactstrap npm install command outlined at the npm website ([npm link](https://www.npmjs.com/package/reactstrap)) does not match the reactstrap npm install command outlined in this repository. I don't know whether this is on purpose, but I had some problems getting things to work when installing reactstrap through the npm page. For example, the documentation regarding the Card component uses the CardBody component instead of the CardBlock component, and CardBody is not exported in the reactstrap through the NPM link.

Kind regards,

chocomel1

**Comment by supergibbs** [comment]
That is because reactstrap 5.0.0 is still in beta. The npmjs.org only shows final releases (as far as I know). Notice the version it says is 4.8.0 (the last version that worked with `bootstrap@4.0.0-alpha.6`).

**Comment by TheSharpieOne** [comment]
@supergibbs is correct. If you want the latest alpha version which is what the docs are using and documenting, follow the instructions on the docs.
#195 would allow for other versions (including the one on npm when there are pre-releases) to have documentation.

Closing as the question has been answered and there is another actionable issue which may better address this concern in the future. Please feel free to continue the conversation or reopen the issue if you feel it is not resolved.
