### ISSUE TITLE
How do I use an img src in Carousel Items?

### ISSUE THREAD

**Issue by rahamin1** [reactstrap/reactstrap#684]
### The Carousel example in the reacstrap docs uses 'data:image' for img src. How do I use 'img'?

- components: `Carousel`
- reactstrap version `0.31.5`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `16.1.0`
- bootstrap version `4.0.0-beta`

I am sure it is a silly question, but the need overrides the shame :-)

The example in the doc is using the following:
```
<CarouselItem
          onExiting={this.onExiting}
          onExited={this.onExited}
          key={item.src}
          src={item.src}
          style={imgStyle}
          altText={item.altText}
        >
```

Where src is:
`src: 'data:image/svg+xml;charset=UTF-8,...`

I would like to use img instead. How do I define src for that?
I tried:
`src: 'book1.jpg'`

But it doesn't work.

**Comment by TheSharpieOne** [comment]
`src: 'book1.jpg'` will work as long as the path to the image is relative the URL. If you're image is somewhere specific (like an `images` directory/folder at the root of your domain/site) you'll need to do `/images/book1.jpg`,
Reactstrap isn't doing any magic here, it is the standard browser fetching and rendering of your image. See https://www.w3schools.com/hTml/html_filepaths.asp for the possible ways to resolve your path.

**Comment by rahamin1** [comment]
Thanks, you were right, path issue. I knew it was silly :)

**Comment by rahamin1** [comment]
Thank you very much!

Best Regards
Yossi

**Comment by PujaSrivastava10** [comment]
Hello @rahamin1 ,
can you please help me out to debug this issue, I am still stuck. I am entering the path but the carousel is not working. Here is my code 
1. I tried using import
2. I tried using require
3. I tried giving the path directly. Moreover, I may not know the actual path of the image, since these are getting built by webpack, even I have tried using `/static/media` in the relative path, but of no use.
```
import React , {Component} from 'react';
import { Carousel,
  UncontrolledCarousel,
  CarouselItem,
  CarouselControl,
  CarouselIndicators,
  CarouselCaption } from 'reactstrap';
  import himalaya from './images/himalaya.jpg';

 const items = [
  {
    src : {require('./images/beach.jpg')}, // even I tried using require, but no result
    altText: 'img can not be displayed',
    caption: '-Roxane Gay',
    header: '“Long walks on the beach are the supposed holy grail of a romantic evening. The beach becomes a kind of utopia - the place where all our dreams come true.”'
  },
  {
    src: {himalaya}, //by import, this is getting treated as a constant.
    altText: 'img can not be displayed',
    caption: '-Karen Blixen',
    header: '“You know you are truly alive when you’re living among lions.”'
  },
  {
    src:'./images/stream.jpg',
    altText: 'img can not be displayed',
    caption: '-Edmund Hillary',
    header: '“It is not the mountain we conquer but ourselves.”'
  }
];
```
Below is my folder structure:

![folder structure](https://user-images.githubusercontent.com/30182041/41921444-81591de2-7980-11e8-9349-8e2d5c830926.JPG)

Please let me know, where am I missing. It will be of great help.
Thanks

**Comment by rahamin1** [comment]
Sorry, no idea...
