### ISSUE TITLE
React Alert opacity is 0 by default 

### ISSUE THREAD

**Issue by Vadorequest** [reactstrap/reactstrap#687]
I'm using Alert for the first time using 5.0.0 alpha 3 and my Alerts don't show because the opacity of the "fade" class is 0.

.fade {
    opacity: 0;
    -webkit-transition: opacity .15s linear;
    -o-transition: opacity .15s linear;
    transition: opacity .15s linear;
}

I don't really understand if it's a bug or misconfiguration.

```
            <Alert color="info">
              blabla
            </Alert>
```

**Comment by TheSharpieOne** [comment]
What version of bootstrap are you using? 5.0.0 alphas only work with bootstrap v4.0.0-beta (and mostly with 4.0.0-beta.2).

Working demo: https://codesandbox.io/s/r5k0y4rp4o

**Comment by Vadorequest** [comment]
I'm using 4.0.0-alpha.5
Maybe an update there will help, thanks for hint.

**Comment by Vadorequest** [comment]
It indeed fixed the issue, alongside with another one I was having with z-index for input-group and form-control.

Well, it also added a bunch of new ones =D
Thanks!
