### ISSUE TITLE
How to get value from ListGroupItem?

### ISSUE THREAD

**Issue by jacklee814** [reactstrap/reactstrap#698]
Like this ... 

```
handkeGetValue(event) {
   console.log(event.target.value)
}

...

<ListGroup>
        <ListGroupItem onClick={this.handleGetValue}>Cras justo odio</ListGroupItem>
</ListGroup>
```

When I console is empty content ... what's wrong of this way?

thanks .

**Comment by TheSharpieOne** [comment]
Only inputs have `value`. If you want the text within the element, you'll need to use `event.target.innerText`

**Comment by jacklee814** [comment]
Thanks a lot.
