### ISSUE TITLE
Whitespace ignored inside FormGroup, between Label and Input

### ISSUE THREAD

**Issue by np-8** [reactstrap/reactstrap#699]
##  Current behaviour

In the [examples](https://reactstrap.github.io/components/form/), whitespace is added with `{' '}`, which does not work as intended.

```
      <Form inline>
        <FormGroup>
          <Label for="exampleEmail">Email</Label>{' '}
          <Input type="email" name="email" id="exampleEmail" placeholder="something@idk.cool" />
        </FormGroup>
        {' '}
        <FormGroup>
          <Label for="examplePassword">Password</Label>{' '}
          <Input type="password" name="password" id="examplePassword" placeholder="don't tell!" />
        </FormGroup>
        {' '}
        <Button>Submit</Button>
      </Form>
```

![image](https://user-images.githubusercontent.com/17479683/33010455-36342bfc-cde3-11e7-94fa-a5da303ab419.png)

## Possible solution
Usage of `{'\u00A0'}` seems to fix the issue.

```
      <Form inline>
        <FormGroup>
          <Label for="exampleEmail">Email</Label>{'\u00A0'}
          <Input type="email" name="email" id="exampleEmail" placeholder="something@idk.cool" />
        </FormGroup>
        {'\u00A0'}
        <FormGroup>
          <Label for="examplePassword">Password</Label>{'\u00A0'}
          <Input type="password" name="password" id="examplePassword" placeholder="don't tell!" />
        </FormGroup>
        {'\u00A0'}
        <Button>Submit</Button>
      </Form>
```

![image](https://user-images.githubusercontent.com/17479683/33010594-b8d394e4-cde3-11e7-8651-13647e33b3b1.png)

**Comment by TheSharpieOne** [comment]
The spaces are a leftover from before bootstrap when all flexbox. The actual solution is to use the spacing and flexbox utilities provided by bootstrap (this is what bootstrap recommends).

**Comment by supergibbs** [comment]
For reference: https://getbootstrap.com/docs/4.0/components/forms/#inline-forms

**Comment by TheSharpieOne** [comment]
Docs have been updated to use the spacing utils as recommended by bootstrap
![image](https://user-images.githubusercontent.com/664714/33067238-8fb094e8-ce7b-11e7-91db-a23f95f6a281.png)

**Comment by np-8** [comment]
Nice! And thanks for the quick reactions.

For the curious, the `mb-2 mr-sm-2 mb-sm-0` are (behind the link @supergibbs posted) [Bootstrap 4 spacing classes](https://getbootstrap.com/docs/4.0/utilities/spacing/). For example, `mr-sm-2` adds margin right (`mr`) for breakpoint `sm`, with size of `$spacer * .5` (the `2`), where `$spacer` is a Sass variable. If breakpoint is omitted, `xs` is assumed.
