### ISSUE TITLE
Breadcrumb is showing for desktop when implemented Navbar code

### ISSUE THREAD

**Issue by Sunil1890** [reactstrap/reactstrap#705]
I am using bootstrap navbar code but getting hamburger icon on desktop
### Issue description
```jsx
import React from 'react';
import { Collapse, Navbar, NavbarToggler, NavbarBrand, Nav, NavItem, NavLink } from 'reactstrap';
import PropTypes from 'prop-types';

export default class GaragerNavbar extends React.Component {
  constructor(props) {
    super(props);

    this.toggle = this.toggle.bind(this);
    this.state = {
      isOpen: false
    };
  }
  toggle() {
    this.setState({
      isOpen: !this.state.isOpen
    });
  }
  render() {
    return (
      <div>
        <Navbar color="faded" light expand="md">
          <NavbarBrand href="/"></NavbarBrand>
          <NavbarToggler onClick={this.toggle} />
          <Collapse isOpen={this.state.isOpen} navbar>
            <Nav className="ml-auto" navbar>
              <NavItem>
                <NavLink href="/components/">Components</NavLink>
              </NavItem>
              <NavItem>
                <NavLink href="https://github.com/reactstrap/reactstrap">Github</NavLink>
              </NavItem>
            </Nav>
          </Collapse>
        </Navbar>
      </div>
    );
  }
}
Navbar.propTypes = {
  light: PropTypes.bool,
  dark: PropTypes.bool,
  fixed: PropTypes.string,
  color: PropTypes.string,
  role: PropTypes.string,
  expand: PropTypes.oneOfType([PropTypes.bool, PropTypes.string]),
  tag: PropTypes.oneOfType([PropTypes.func, PropTypes.string])
  // pass in custom element to use
}
NavbarBrand.propTypes = {
  tag: PropTypes.oneOfType([PropTypes.func, PropTypes.string])
  // pass in custom element to use
}
```
### What should be happening?

It should display navbar for desktop and breadcrumb for mobile devices

**Comment by TheSharpieOne** [comment]
You are not using breadcrumbs in the code you posted. If you expect to see them on mobile, you'll need to use them. Have you tried using breadcrumbs?
https://reactstrap.github.io/components/breadcrumbs/
Also, chances are you are talking about the navbar expand and are using reactstrap 4.x with 5.x documentation which will not work.

**Comment by Sunil1890** [comment]
Yeah but i dont want that hamburger icon for desktop. it should only be visible for adaptive. what's the way ? i've just use your code only. if you have doubt then just copy paste your code on react app, you'll see that hamburger icon but according to your mentioned code for your website it's working fine. Can you please inform about this.

**Comment by TheSharpieOne** [comment]
Are you still having this issue after upgrading to the version mentioned in the docs?

**Comment by Sunil1890** [comment]
yes

**Comment by josephmaxim** [comment]
@miketheprogrammer alpha for reactstrap or bootstrap?

**Comment by josephmaxim** [comment]
@Sunil1890 I figured it out! after changing versions make sure to delete modules folder and restart dev server. currently using.  "bootstrap": "^4.0.0-beta.2" & "reactstrap": "^5.0.0-alpha.4".
