### ISSUE TITLE
 'reactstrap' does not contain an export named 'Carousel'.

### ISSUE THREAD

**Issue by Sunil1890** [reactstrap/reactstrap#706]
'reactstrap' does not contain an export named 'Carousel'. what does it mean ?

**Comment by TheSharpieOne** [comment]
It means you are using a version prior to that feature being added. Use the installation instructions in the docs which will install the v5 alpha which has that feature.

**Comment by Sunil1890** [comment]
fixed issue after installation of "npm i -S reactstrap@5.0.0-alpha.3" you can close this issue. but please mention that to install latest version.

Thanks

**Comment by TheSharpieOne** [comment]
Yes, It is already mentioned in the documentation in the readme and in the documentation website.
