### ISSUE TITLE
Using reactstrap with redux-form: does it work? Can anyone post a working example?

### ISSUE THREAD

**Issue by rahamin1** [reactstrap/reactstrap#707]
I have been trying to use redux-form with reactstrap and faced some problems.
Is anybody using it extensively? If you do, can you post an example? Which versions of react / bootstrap / reactstrap are you using?

If not, how do you implement forms? Doing it without any package seems like plenty of work...

Thanks!

**Comment by TheSharpieOne** [comment]
You can create a wrapper component which spreads the input prop on reactstrap's Input or you should be able to add Field as the tag for Input and set component to the string "input" (or select or textarea depending on of the type is one of those things.) 
```jsx
<Input tag="Field" component="input" name="something" />
```

**Comment by rahamin1** [comment]
Thanks. I am curious to know what users of reactstrap are doing when they create forms... Use redux-forms? Anything else? Just write the forms from the ground up? I am looking for users who tried redux-forms extensively, with reactstrap...

_Probably a good time (I understand that you are reactstrap's mother and father :) to tell you that I experienced a little bit with the more popular react-bootstrap and found reactstrap to be much easier to use, much more friendly... :)_

**Comment by TheSharpieOne** [comment]
redux-form uses redux to have a global state of all of the fields and validation within a form, I don't find that too useful (all I need is validation and easy handling of submissions) so I personally don't use it. What I use is react-formik which is a super nice way to manage forms and validation within a component. I also use availity-reactstrap-validation, which actually uses reactstrap's fields and looks like bootstrap out of the box, but it has some complexity when doing more advanced thing (which is why it needs a rewrite for its v2)

**Comment by rahamin1** [comment]
Thanks again :)  Looked at availity-reactstrap-validation but it seems to get too little support and some issues that take long to solve.

Regarding react-formik: does it work together with reactstrap smoothly? I am a beginner...

**Comment by TheSharpieOne** [comment]
Yes, just use reactstrap's components (Input and Form) in place of input and form in react-formik's examples. You also want to add/use things like FormGroup and FormFeedback to look like bootstrap.

**Comment by mishelen** [comment]
@TheSharpieOne 
> or you should be able to add Field as the tag for Input and set component to the string "input" (or select or textarea depending on of the type is one of those things.)
```js
<Input tag={Field} component="input" name="something" />
```
This will not work ... But wrapper that you mean as first solution or renderer for me -- yes:
@rahamin1
```js
import React, { Fragment } from 'react';
import { Input, FormFeedback, FormText } from 'reactstrap';

export const renderTextField = ({ input, meta: { touched, error, warning }, ...custom }) => (
    <Fragment>
        <Input {...(touched ? { valid: !error } : {})} {...input} {...custom} />
        {error && <FormFeedback>{error}</FormFeedback>}
        {!error && warning && <FormText>{warning}</FormText>}
    </Fragment>
);

export const renderRadioField = ({ value, input, ...custom }) => (
    <Input type="radio" checked={value === input.value} {...input} {...custom} />
);

export const renderCheckbox = ({ input: { value, onChange } }) => (
    <Input type="checkbox" checked={!!value} onChange={onChange} />
);

export const renderSelectField = ({ input, meta: { touched, error }, children, ...custom }) => (
    <Input type="select" {...(touched ? { valid: !error } : {})} {...input} {...custom}>
        {children}
    </Input>
);
```


I generally did not so like redux-form. They are certainly cool and do a lot of things, but how?

While I forced to work a simple form killed a lot of time. And although they have detailed documentation, but it is very untidy. Perhaps this is personal dislike)))

**Comment by rahamin1** [comment]
Thanks. 
I also decided not to use redux-form, using my own controlled components, based on the following:
[React.js Forms: Controlled Components](https://lorenstewart.me/2016/10/31/react-js-forms-controlled-components/)

**Comment by mishelen** [comment]
cool! I read this article early. 

In any case, I hope that my snippet will save someone some time)) Not everyone can choose which library to work with)))
I think it's worth looking at [formik](https://github.com/jaredpalmer/formik)  as an alternative to redux-form

**Comment by rahamin1** [comment]
I saw that many people like formik. I tried both formik and Availity and decided to use my own code (based on what I mentioned above) - gives more control on everything, which seemed to me more important than the benefits of using a library.

**Comment by harrowm** [comment]
A very useful code snippet @mishelen !

One query - when a field is in error then it doesn't go red etc .. see form validation at https://reactstrap.github.io/components/form/

Any ideas why ? I have no clue ..

**Comment by TheSharpieOne** [comment]
@harrowm set the `valid` prop to `false` on the `Input` when it is invalid.

**Comment by aikidoshi** [comment]
@mishelen I really appreciate your field wrappers above.
Do you happen to have a solution for a date picker that will work in IE, because type="date" does not.
Many thanks!

**Comment by k8martian** [comment]
I use reactstrap with redux form as well, so far only can't get the date picker work. Any suggestion? thanks.

**Comment by k8martian** [comment]
@aikidoshi Did you get the date picker work with redux form? So far only date picker not work for me. Anyone has a fix for this? thanks.

**Comment by aikidoshi** [comment]
What style classes are you using Bootstrap, reactstrap or Material-ui? I had mixed success but found reactstrap easier.

                <Field
                    name="StartDate"
                    type="date"
                    label="Start Date"
                    component={renderTextField}
                    validate={[required, isdate]}
                />

const renderTextField = ({input, name, label, meta: {valid, touched, error, warning}, ...custom}) => (
    <FormGroup row>
        <Label for={name} sm={2}>{label}</Label>
        <Col sm="10">
            {(touched && error) ?
                <Input invalid bsSize="sm"
                       {...input}
                       {...custom} /> :
                <Input valid bsSize="sm"
                       {...input}
                       {...custom} />
            }
            <FormFeedback>{error}</FormFeedback>
            {warning && <FormText>{warning}</FormText>}
        </Col>
    </FormGroup>
);

This should work in recatstrap context.
Regards,
aikidoshi

**Comment by k8martian** [comment]
@aikidoshi  I am using reactstrap and thanks for reply, Will try it out later.

**Comment by TheSharpieOne** [comment]
@Olu93 	this may be related to #1308 in a way where the new `React.forwardRef` is ac component object (which is new) and not one of the expected types. I just fixed the types it checks for everywhere else and will release soon.

For now, this is just a warning which only shows in development and you can just ignore it.

**Comment by avanish19** [comment]
It worked for me, there is a bit change here

const renderSelectField = ({ input, label,meta: { touched, error,warning }, children, ...custom }) => (
    <FormGroup>
        <Label for={label}>{label}</Label>
    <Input type="select" invalid={(touched && error) || (warning)}  {...input} {...custom}>
        {children}
    </Input>
    <FormFeedback>{error}</FormFeedback>
    </FormGroup>
);
