### ISSUE TITLE
command failed with exit code 127.

### ISSUE THREAD

**Issue by kingerking** [reactstrap/reactstrap#711]
My operating system: OSX 10.12.6
I followed the instructions on the main website on how to set up a react-strap project.
I get the following output when trying to run: yarn start

Kyles-MacBook-Pro:sandbox1 kyle$ yarn start
yarn run v1.3.2
$ react-scripts start
/bin/sh: react-scripts: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by TheSharpieOne** [comment]
Did you install first?

**Comment by kingerking** [comment]
Nope. sorry about this

**Comment by jakeasmith** [comment]
Haha. This is the top google result for "yarn exit code 127" and super helpful. Thanks, peoples!

**Comment by w3debugger** [comment]
I mean seriously? How I missed this part? 😄 just run `yarn` and it's fixed 🤦‍♂️  🎉

**Comment by tracyalison11** [comment]
Really helpful! Thank you!

**Comment by benomatis** [comment]
For those of you who face the issue even after running `yarn install`, for me it was some remaining files in the `node_modules` folder. Getting rid of the `node_modules` folder entirely (`rm -rf node_modules` from the root folder), then running `yarn install` resolved this for me.

**Comment by sentientouroboros** [comment]
I'm teaching a class right now and running into this issue a lot, also ran into it on my own just now. I believe the issue me and the students were having was that one of the parent directories that the React project is in has a space in its name. If any of the directories above the project have a space in their name, then `yarn install` doesn't solve this error. Once I renamed the directories to not have spaces, the thing worked.

**Comment by Jmcobb** [comment]
@sentientouroboros Have you tried just the "Yarn" command by itself? After browsing for about 30 minutes through the doc and trying different stuff it just kind of worked haha

Sorry for the lack of insight I am still kinda new to this.

**Comment by viniciusfreitasrj17** [comment]
I've delete directory node_module, after run `yarn install && yarn start` and it's fixed.

**Comment by o-pooja-o** [comment]
nothing of above working for me!! :(

**Comment by miladbahramii** [comment]
world is beautiful.

**Comment by hamiltonhart** [comment]
Following @TheMshary thought process, I apparently had a colon in a parent directory a few levels up. Changing that directory name did it for me.

**Comment by ahmcho** [comment]
@TheMshary Thank you so much! It worked for me

**Comment by enricotempesti** [comment]
worked for me after running just the command yarn in project folder

**Comment by dawidstefaniak** [comment]
Remember to bind `/node_modules` to volume if you bind volume rest of the project.

**Comment by mimifitz** [comment]
Mine oh mine! This forum is so helpful.My parent directory has space also, yarn install, npm install an all the other tricks weren't working for me.Changed the directory and boom,back on track. No space in naming folders pls.

**Comment by ejoo** [comment]
I forgot to install `pretty-quick` as I was using it to format code using prettier.

` "format:precommit": "pretty-quick --staged  --pattern \"src/**/*.*(js|jsx|ts|tsx)\""`

**Comment by syedhassanraza15** [comment]
i did npm install and it worked fine

**Comment by Valkirin** [comment]
All things well done! Just install yarn globally, then install yarn in project using `yarn install` ang `yarn start`

**Comment by oceankrish76** [comment]
**npm install -g concurrently**

**Comment by umeraqeel786** [comment]
it worked fine .thanks beautiful people

**Comment by VergoEcho** [comment]
Fased this problem on my Macbook 13 pro 2018 BigSur 11.2
The problem dissapear after i **change directory** of my project, and then reinstall **_node_modules_**.
I moved project from folder with **_.nosync_** ending, to my desktop. Think that **_.nosync_** cause problem in my case(i just wanted to disable sync projects, becouse of node_modules, maybe someone know how to do not sync them to icloud in other way?)

**Comment by jb0gie** [comment]
🙌🏿

**Comment by drive-subeesh** [comment]
Worked for me!...thanks bro

**Comment by TheGeus** [comment]
just use the cmd and type yarn in the root of your proyect and that's all

**Comment by aMarCruz** [comment]
If everything fails ...
check the `scripts` block of the package.json of the package to install.
If "husky" is in `postinstall`, that's the culprit.

**Comment by kirtirajsinh** [comment]
I've tried many times deleting and then running `yarn install` it's giving me the same error. On adding Tailwind CSS as it needs craco instead of react-scripts and now it shows that "/bin/sh: 1: craco: not found". Can anyone Help? I'm in a hackathon and not even the mentors are able to solve it.

**Comment by filmons** [comment]
Really helpful! Thank you!

**Comment by LueSantos** [comment]
Voltou a funcionar apenas executando o yarn na pasta...

**Comment by Irtaza1993** [comment]
I've deleted directory node_module, then run yarn install && yarn start commands but fi=or me it's still hasn't fixed yet.

**Comment by rjdjohnston** [comment]
> For those of you who face the issue even after running `yarn install`, for me it was some remaining files in the `node_modules` folder. Getting rid of the `node_modules` folder entirely (`rm -rf node_modules` from the root folder), then running `yarn install` resolved this for me.

Can anyone update the docs and advise to browse into project folder and run `yarn` ? Crazy

**Comment by janpierts** [comment]
simply ---> $yarn global add nodemon yarn global add ts-node

**Comment by YodaLightsabr** [comment]
I'm just dropping this here because this produces a similar error message even though it's something completely different:
https://github.com/yarnpkg/yarn/issues/7373

**Comment by RohanSingh182003** [comment]
> 

run **npm i next** command

**Comment by kellykaufman** [comment]
> I've delete directory node_module, after run `yarn install && yarn start` and it's fixed.

This worked! Thank you🙏🏻

**Comment by Ge6ben** [comment]
I was run `npm run serve`  I should run `npm run dev` ...

**Comment by MichaelMorami** [comment]
haha so silly yet so helpful thanks for that :D
To be fair though, "exit code 127" isn't exactly a descriptive error.

**Comment by zhangpeichao-cmd** [comment]
reflect on it!

**Comment by Hadi2525** [comment]
npm commands does not work for me. Yarn install worked for me

**Comment by xibsked** [comment]
I am not sure why but `npx yarn` seems to resolving the issue for me.

**Comment by Mel-snobbery** [comment]
Got the solution https://reacter.space/questions/the-gatsby-head-api-is-experiencing-issues-with-correctly-formatting-scripts
