### ISSUE TITLE
<div> cannot appear as a descendant of <p>

### ISSUE THREAD

**Issue by MokoPolo** [reactstrap/reactstrap#715]
If I have:

      <div>
        <ListGroup className="TransparentBackground">
          <ListGroupItem className="TransparentBackground">
            <ListGroupItemHeading>{this.props.title}</ListGroupItemHeading>
            {GroceryItems2}
          </ListGroupItem>
        </ListGroup>
      </div>

And {GroceryItems2} is 

    const GroceryItems2 = this.props.ingredients.map(ingredient => (
      <GroceryItem
        key={ingredient.Id}
        showDone={this.props.showDone}
        ingredient={ingredient}
        toggleItemClick={this.groceryItemClickHandler}
        editItemClick={this.groceryEditItemModalHandler}
      />

And each GroceryItem is

      <ListGroupItemText key={this.state.ingredient.Id} className={itemClass}>
        <Row>
          <Col xs="1" lg="1" className="align-middle">
            <Input
              type="checkbox"
              defaultChecked={this.state.ingredient.Done}
              onChange={this.toggle}
            /></Col>
          <Col xs="10" lg="8">
            {this.state.ingredient.Name} (Qty:{this.state.ingredient.Quantity})
            </Col>
          <Col xs="1" lg="3">
            <Button onClick={this.groceryEditItemModalHandler} >Edit item</Button>
          </Col>
        </Row>
      </ListGroupItemText>

I'll get error

<div> cannot appear as a descendant of <p>

How can I fix this?

**Comment by MokoPolo** [comment]
If this helps I also get 
![image](https://user-images.githubusercontent.com/3758891/33333840-05917122-d436-11e7-987e-1a4aa57da7dd.png)

**Comment by MokoPolo** [comment]
If this helps I also get
![image](https://user-images.githubusercontent.com/3758891/33334042-9ed4b6dc-d436-11e7-9787-01d342c1ffb8.png)

**Comment by TheSharpieOne** [comment]
You can use `tag` to override the default tag. By default, the `ListGroupTextItem` outputs a `p` because it is most commonly a text item, but you are using the layout (rows and columns) within there and not text. You can change it to a div via `tag="div"` or make it the row directly via `tag={row}`.

**Comment by MokoPolo** [comment]
This works perfectly thanks!
