### ISSUE TITLE
Why does the popover styling look so odd compared to example?

### ISSUE THREAD

**Issue by kpennell** [reactstrap/reactstrap#717]
The popover doesn't look like the one in the example docs and it moves as I scroll vs. staying put and looking all nice (like it does in the docs)

![image](https://user-images.githubusercontent.com/1060385/33418648-bd94fed0-d55b-11e7-8e03-39a26aa97848.png)
![image](https://user-images.githubusercontent.com/1060385/33418654-c502f8c0-d55b-11e7-9532-6feb4e098532.png)

**Comment by kpennell** [comment]
I realize this is all volunteer run and it open source. So thank you for that. But it's sooooooooooo endlessly frustrating when you spend hours fighting with something while following the docs exactly.

**Comment by TheSharpieOne** [comment]
You need to use bootstrap v4-beta.2 with reactstrap alpha. 
Follow the docs for how to install and use reactstrap.
If you don't want to use bootstrap v4, reactstrap recommends react-bootstrap for bootstrap v3.

**Comment by kpennell** [comment]
Pretty sure I am 
```
{
  "name": "CallYourGovernmentCoreUI",
  "version": "1.0.0-alpha.3",
  "private": true,
  "homepage": ".",
  "devDependencies": {
    "firebase": "^4.6.0",
    "google-map-react": "^0.25.0",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.0",
    "gulp-sass": "^2.3.2",
    "moment": "^2.19.1",
    "react-loader": "^2.4.2",
    "react-moment": "^0.6.5",
    "react-scripts": "0.8.5",
    "react-soundcloud-widget": "^2.0.4",
    "react-spotify-player": "^1.0.3",
    "react-transition-group": "^2.2.1"
  },
  "dependencies": {
    "bootstrap": "^4.0.0-beta.2",
    "react": "^15.6.2",
    "react-addons-css-transition-group": "^15.4.2",
    "react-addons-transition-group": "^15.4.2",
    "react-breadcrumbs": "^1.5.2",
    "react-dom": "^15.6.2",
    "react-router": "^3.0.2",
    "react-router-dom": "^4.2.2",
    "react-transition-group": "^2.2.1",
    "reactstrap": "^5.0.0-alpha.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

```

**Comment by kpennell** [comment]
Tried this as well:
```

{
  "name": "CallYourGovernmentCoreUI",
  "version": "1.0.0-alpha.3",
  "private": true,
  "homepage": ".",
  "devDependencies": {
    "firebase": "^4.6.0",
    "google-map-react": "^0.25.0",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.0",
    "gulp-sass": "^2.3.2",
    "moment": "^2.19.1",
    "react-loader": "^2.4.2",
    "react-moment": "^0.6.5",
    "react-scripts": "0.8.5",
    "react-soundcloud-widget": "^2.0.4",
    "react-spotify-player": "^1.0.3",
    "react-transition-group": "^2.2.1"
  },
  "dependencies": {
    "bootstrap": "^4.0.0-beta.2",
    "react": "^16.2.0",
    "react-addons-css-transition-group": "^15.4.2",
    "react-addons-transition-group": "^15.4.2",
    "react-breadcrumbs": "^1.5.2",
    "react-dom": "^16.2.0",
    "react-popper": "^0.7.4",
    "react-router": "^3.0.2",
    "react-router-dom": "^4.2.2",
    "react-transition-group": "^2.2.1",
    "reactstrap": "^5.0.0-alpha.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

```

**Comment by kpennell** [comment]
Now getting: 

```
PropTypes.js:8 Uncaught TypeError: Cannot read property 'func' of undefined
    at Object.<anonymous> (PropTypes.js:8)
    at __webpack_require__ (bootstrap f7a4c8009a1d4f678d82:555)
    at fn (bootstrap f7a4c8009a1d4f678d82:86)
    at Object.<anonymous> (index.js:15)
    at __webpack_require__ (bootstrap f7a4c8009a1d4f678d82:555)
    at fn (bootstrap f7a4c8009a1d4f678d82:86)
    at Object.<anonymous> (index.js:3)
    at __webpack_require__ (bootstrap f7a4c8009a1d4f678d82:555)
    at fn (bootstrap f7a4c8009a1d4f678d82:86)
    at Object.<anonymous> (bootstrap f7a4c8009a1d4f678d82:578)
```

**Comment by virgofx** [comment]
Popovers and collapses work perfectly. It's most likely configuration error on your side. If you want more immediate help you need to reproduce the issue in a codepen where we can confirm the EXACT issue you are seeing.

**Comment by kpennell** [comment]
That's fair. I'm in dependency hell. I'm just going to switch to material ui or https://github.com/react-bootstrap/react-bootstrap. I can't deal with this anymore.

**Comment by TheSharpieOne** [comment]
@kpennell You do realize reactstrap has the same deep dependencies (the only dependencies you have to worry about and install on your own) as react-bootstrap... in-fact the only difference when installing is using reactstrap instead of react-bootstrap and using bootstrap v4 instead of v3 (which doesn't even need to be installed if you reference the css from a cdn)......
Maybe if you post some code we can help you figure out the problem with your code.

**Comment by TheSharpieOne** [comment]
Turns about you are using bootstrap v4.0.0.alpha.6 which is *not* support in the latest reactstrap, please upgrade to bootstrap v4.0.0-beta or v4.0.0-beta.2.
I see you are referencing `"bootstrap": "^4.0.0-beta.2",` in your package.json but you are most likely pulling in v4.0.0.alpha.6 via a CDN reference or just have an outdated version installed locally.

Below are examples, the *only* difference is the version of the bootstrap css
What you are seeing (using bootstrap 4.0.0-alpha.6): https://www.webpackbin.com/bins/-L-CkY5ee-hDSscZDBUN
What we recommend (uising bootstrap 4.0.0-beta.2): https://www.webpackbin.com/bins/-L-CmZ08c8W40LTWK7YQ

**Comment by kpennell** [comment]
I'll try some things and try other libraries and report if I find a breakthrough
