### ISSUE TITLE
 Unknown prop `expand` on <nav> tag

### ISSUE THREAD

**Issue by Suban5** [reactstrap/reactstrap#718]
### I got the following is while using Reactstrap Navbar. The hamburgur button is shown below navbar brand instead of right side.
Warning: Unknown prop `expand` on <nav> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop in 
nav (created by Navbar) in Navbar (at AdminPanel.js:67) 
 in div (created by Container) in Container (at AdminPanel.js:30)
 in AdminPanel (at ShowJobList.js:50)
 in div (created by Row) in Row (at ShowJobList.js:49)
 in div (created by Container) in Container (at ShowJobList.js:48)
 in ShowJobList (created by Route) in Route (at App.js:60) 
 in Switch (at App.js:35) in div (created by Container) in Container (at App.js:34) 
 in App (at index.js:11)
 in Router (created by BrowserRouter)
 in BrowserRouter (at index.js:10)

- components: `Navbar`
- reactstrap version `4.8.0`
- react version `15.6.2`
- bootstrap version `^4.0.0-beta.2`

**Comment by TheSharpieOne** [comment]
Reference the readme and/or the documentation site for how to install and use reactstrap.
Currently you have mismatch versions and are using new features with old versions.
