### ISSUE TITLE
Basic Grid Doesn't Work?

### ISSUE THREAD

**Issue by ddantzler** [reactstrap/reactstrap#721]
Full Disclosure, I am a newbie at this. If I am doing something wrong, please advise.

This traditionally would work and provide a responsive layout, such when the user resizes the browser to the medium size, the content in the second column would flow beneath the content in the first column.
```html
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      Some content
    </div>
    <div class="col-md-6">
      Some content
    </div>
  </div>
</div>
```

When trying to replicate this in reactstrap as follows:
```html
<Container fluid>
  <Row>
    <Col md="6">
      Some content
    </Col>
    <Col md="6">
      Some content
    </Col>
  </Row>
</Container>
```
`<Col md="6">` results in `<div class="col col-md-6">`. This does not function as expected. The two columns remain side by side no matter the size of the viewport.

Is there a workaround other than creating the Grid manually with div elements and applying className?

**Comment by jantonso** [comment]
I've been having the same issue. The workaround for me as of now is to manually apply xs="12" to everything, which is annoying but seems like it works for now.

**Comment by TheSharpieOne** [comment]
This is a change in bootstrap which defaults the xs to not 100%. You need to just specify xs and if you want xs to be the same as sm and md, you can just use xs instead of md in your code.
