### ISSUE TITLE
Bottom popover arrow color

### ISSUE THREAD

**Issue by gbrlsnchs** [reactstrap/reactstrap#723]
First of all, I want to thank the creator and the contributors for this great library.

About the issue, when a bottom popover is shown, its arrow should have the same color of the header, just like in [the original popover](https://v4-alpha.getbootstrap.com/components/popovers/).

Curiously, I could not found any Bootstrap adaptations (for Angular, Vue or React) that didn't have this issue, so I'm not sure if it's a common difficulty.

Also, if it's a complicated one, I'm willing to help, but I'm not sure where to start, so I'd be glad if someone could me give directions here, so I could try something out.

Thanks in advance!

**Comment by TheSharpieOne** [comment]
This is an issue with bootstrap itself as you can tell from the latest v4 documentation: http://getbootstrap.com/docs/4.0/components/popovers/
The documentation you linked to is from bootstrap v4 alpha, which is now dated. bootstrap v4 beta suffer from the issue you are seeing.

**Comment by gbrlsnchs** [comment]
I see... thanks for the clarification! :1st_place_medal: 

I'm closing this since it's not related to Reactstrap itself.
