### ISSUE TITLE
Col order not working in React 16.2.0

### ISSUE THREAD

**Issue by ivoilic** [reactstrap/reactstrap#727]
The order classes were not showing up for my Col elements so I assumed something was wrong with my syntax.
So I copied the entire Layout example from [here](https://reactstrap.github.io/components/layout/) to test and but had the same issue.
Other properties like size and offset work fine but order does not show up at all as a class.

**Comment by mishelen** [comment]
It still not work. And react version isnot matter. Because in source code there are not order prop in PropTypes and below in code **not executed hadling of this props in whole**.

**Comment by jamesremuscat** [comment]
It looks like the documentation has been updated in advance of that functionality being released.

The commit which added support for `order` was 7c5e690 on 21 November; the most recent release was 14th November. I'd therefore expect this to start working in the next reactstrap release.

As a workaround you can manually add e.g. `className='order-sm-7'`to your `Col`s.

**Comment by supergibbs** [comment]
This should work now, `order` is supported with the latest release.
