### ISSUE TITLE
Outline version of dropdown button variants

### ISSUE THREAD

**Issue by Chimaytric** [reactstrap/reactstrap#728]
### Issue description

- components: `Dropdown`
- reactstrap version `5.0.0-alpha.3`
- import method `es`
- react version `15.6.1`
- bootstrap version `4.0.0-beta`

### What is happening?

Would it be possible to have the outline versions of the button variants in a Dropdown menu

### Code
```
<ButtonDropdown isOpen={isOpen} toggle={toggle}>
  <DropdownToggle caret color="primary"> {/* right here, having a prop for the outline version would be so great ! */}
    Text
  </DropdownToggle>
  <DropdownMenu>
    <DropdownItem header>Header</DropdownItem>
    <DropdownItem disabled>Action</DropdownItem>
    <DropdownItem>Another Action</DropdownItem>
    <DropdownItem divider/>
    <DropdownItem>Another Action</DropdownItem>
  </DropdownMenu>
</ButtonDropdown>
```

**Comment by TheSharpieOne** [comment]
Yep, just add the `outline` prop.
Like many other components within reactstrap, all of the props passed to `DropdownToggle` are passed down to the component it renders. By default `DropdownToggle` will render a `Button`, so you can pass any `Button` props to it and it will pass them to the `Button.

Demo: https://www.webpackbin.com/bins/-L-Xqjxl7ga1hx5zNbBu

Relevent Code: 
```jsx
        <ButtonDropdown isOpen={this.state.open} toggle={this.toggle}>
          <DropdownToggle caret color="primary" outline>
            Text
          </DropdownToggle>
          <DropdownMenu>
            <DropdownItem header>Header</DropdownItem>
            <DropdownItem disabled>Action</DropdownItem>
            <DropdownItem>Another Action</DropdownItem>
            <DropdownItem divider/>
            <DropdownItem>Another Action</DropdownItem>
          </DropdownMenu>
        </ButtonDropdown>
```

**Comment by Chimaytric** [comment]
Nice, didn't know that ! Thanks for your quick answer 👍
