### ISSUE TITLE
Card component throws error

### ISSUE THREAD

**Issue by codingkapoor** [reactstrap/reactstrap#730]
### Issue description
Card component throws errors.

- components: `Card`
- reactstrap version `^4.8.0`
- react version `^16.2.0`
- bootstrap version `v4.0.0-alpha.2`

### What is happening?
When I use Card component with only CardImg, I don't get any errors
```
import React, { Component } from 'react';
import { Card, Button, CardImg, CardTitle, CardText, CardDeck, CardSubtitle, CardBody } from 'reactstrap';

class MoviesIndex extends Component {

    render() {
        return (
            <CardDeck>
                <Card>
                    <CardImg top width="100%" src="" alt="Movie Poster" />
                </Card>
            </CardDeck>
        );
    }
}

export default MoviesIndex;
```

### Steps to reproduce issue
But when I use this version of Component instead:
```
import React, { Component } from 'react';
import { Card, Button, CardImg, CardTitle, CardText, CardDeck, CardSubtitle, CardBody } from 'reactstrap';

class MoviesIndex extends Component {

    render() {
        return (
            <CardDeck>
                <Card>
                    <CardImg top width="100%" src="" alt="Movie Poster" />
                    <CardBody>
                        <CardTitle>Card title</CardTitle>
                        <CardSubtitle>Card subtitle</CardSubtitle>
                        <CardText>This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</CardText>
                        <Button>Button</Button>
                    </CardBody>
                </Card>
            </CardDeck>
        );
    }
}

export default MoviesIndex;
```

### Error message in console
![screenshot from 2017-12-06 22-11-46](https://user-images.githubusercontent.com/4599890/33683215-2cb485d0-daf0-11e7-8534-f4834656798e.png)

### package.json
```
{
  "name": "client",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "test": "mocha --compilers js:babel-core/register --require ./test/test_helper.js --recursive ./test",
    "test:watch": "npm run test -- --watch"
  },
  "devDependencies": {
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "chai": "^3.5.0",
    "chai-jquery": "^2.0.0",
    "jquery": "^2.2.1",
    "jsdom": "^8.1.0",
    "mocha": "^2.4.5",
    "react-addons-test-utils": "^0.14.7",
    "webpack": "^1.12.9",
    "webpack-dev-server": "^1.14.0"
  },
  "dependencies": {
    "axios": "^0.17.1",
    "babel-preset-stage-1": "^6.1.18",
    "lodash": "^3.10.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-transition-group": "^2.2.1",
    "reactstrap": "^4.8.0",
    "redux": "^3.7.2",
    "redux-promise": "^0.5.3"
  }
}

```

**Comment by TheSharpieOne** [comment]
The documentation site has the latest release (reactstrap v5.0.0-alpha.4), you are using reactstrap v4.8.0. The components you are using are not available in v4.8.0, you need to update or use the equivalent components (`CardBody` -> `CardBlock`)
#195 would have helped with this by having a public documentation of the version you are using. For now, you can run the docs locally by cloning this project and checking out the 4.8.0 tag and `npm install` then `npm start`.

5.0.0-alpha.4 Demo: https://stackblitz.com/edit/react-rnchuj?embed=1&file=Hello.js
4.8.0 Demo: https://stackblitz.com/edit/react-axflbx?file=Hello.js (stackblitz seems to be having some issues with reactstrap-tether... don't know why)

**Comment by androidand** [comment]
Using "reactstrap": "^5.0.0-alpha.4" I am getting
'reactstrap' does not contain an export named 'CardBody'.

**Comment by TheSharpieOne** [comment]
@androidand run `npm ls reactstrap` to get the version installed locally, what is in the package.json may not reflect the actual version installed. You can use `npm up reactstrap` to tell it to update to the latest version allowed by the package.json.

**Comment by androidand** [comment]
Not sure what was wrong but latest version after uninstalling and installing seems to work fine!

**Comment by olefrank** [comment]
Why isn't this mentioned anywhere in the docs????

**Comment by TheSharpieOne** [comment]
@olefrank this is an issue with npm; if anything. It's a given for any library that you need the correct version. Nothing can fix the problem when you think you have the latest version (as that is what is listed in your pacakge.json), but don't have it installed/in your node_modules.
`rm -rf node_modules && npm i` is just standard when dealing with npm.

**Comment by YechiamTK** [comment]
@TheSharpieOne I've encountered the same issue as well. You're correct that we shouldn't assume the docs' version, but given that v5 is in alpha it seems quite odd that the docs would be based on this an not on the official latest release (even on your site you say that the CDN link should take v4.8.0). At the very least, I think it'd be appropriate to include in the header of the docs which version it is based on (I personally think that it's expected to say which components have been deprecated from v4.8.0 to v5 and what has replaced them, for clarity purposes).
