### ISSUE TITLE
Input type Select with Required not working.

### ISSUE THREAD

**Issue by christianbalderrama** [reactstrap/reactstrap#731]
- reactstrap version: 5.0.0-alpha.4
- react version: 16.0.0
- bootstrap version : 4.0.0-beta.2

### What is happening?
I want to create this issue which is not critical but to be aware of, I am using the Input and Modal and the Input type is a select and I've added a required for this select. This is enclosed in a Form and the button type used is submit as per usual.

It jump over the need required field which is an input select

### What should be happening?

It is expected that if I didn't choose something in the select If I hit **submit** it'll notify me that I didn't select  anything in the select option. 

### Steps to reproduce issue

1. ...
2. ...

### Error message in console
There's no error.

### Code
`<Input 
									type="select" 
									name="category"
									onChange={(e) => props.handleInputChange(e)}
									disabled={props.isSubmitted}
									required
									defaultValue="placeholder">
									<option value="placeholder" disabled>Select Type</option>
									{renderCategory}
								</Input>
`

**Comment by TheSharpieOne** [comment]
What you are looking for is availity-reactstrap-validation

**Comment by christianbalderrama** [comment]
That can solve the problem but is there any other natural work around this other than you've mentioned which is installing another package?

**Comment by TheSharpieOne** [comment]
Yes, you can implement that feature yourself in your own code. In your form submission handler, you can run the check to see if the field's value is populated or not.
reactstrap does the same thing bootstrap does here, which is absolutely nothing, relying only on the native browser validation.
It is worth noting that when a field is required, it is only invalid when the value is empty (an empty string) and "placeholder" is not an empty value/string.

Demo: https://stackblitz.com/edit/react-vtrupn?file=Example.js

P.S. if you want to use the [bootstrap validation styles](http://getbootstrap.com/docs/4.0/components/forms/#validation), you will need to _disable_ the native browser validation and handle that validation yourself, as noted in bootstraps docs. If you don't want to do that, and still want the validation styles, that is where availity-reactstrap-validation comes into play.

**Comment by pavinduLakshan** [comment]
This article has a good explanation on using `required` with Select.

http://maxdesign.com.au/articles/select-required/
