### ISSUE TITLE
Can't Set Popper Modifiers for Popover

### ISSUE THREAD

**Issue by dodacr** [reactstrap/reactstrap#732]
### Issue description

- components: `popover`
- reactstrap version `5.0.0-alpha.4`
- import method `es` (if umd, are you using the "full" version (only for v5+)?)
- react version `#16.1.1`
- bootstrap version `not installed`

### What is happening?
When using popover like this:

```
<Popover
        className="PopOver"
        isOpen={props.isOpen}
        target={props.target}
        placement={props.placement}
        toggle={props.toggle}
        modifiers={{flip: {enabled: false}}}>

        {props.children}
</Popover>
```
seems like `modifiers` object is ignored. Popper still gets its

```
modifiers: {
    flip: {
      behavior: "flip"
      enabled: true
    }
    ...
}
```
props object. 

### What should be happening?

I think the `props.modifiers.flip.enabled` prop of `Popper` should be `false`.

### Steps to reproduce issue

Just render the `<Popover>` like I described and check if the Popper get correct prop.

**Comment by supergibbs** [comment]
Seems like its being set using the flip prop here: https://github.com/reactstrap/reactstrap/blob/master/src/PopperContent.js#L153

I agree though if you aren't using the flip prop, your modifiers object should work.

**Comment by TheSharpieOne** [comment]
I don't think #710 has been released yet.

**Comment by dodacr** [comment]
To which milestone it is assigned?

**Comment by ashwinputhige** [comment]
This causes `Warning: Unknown prop `modifiers` on <div> tag.` warnings in console.

**Comment by supergibbs** [comment]
This should be working now with the latest release. If not, please reopen.

**Comment by dodacr** [comment]
Yes, I confirm that the issue is resolved.
