### ISSUE TITLE
Cannot access event when using Modal onClosed, onOpened..

### ISSUE THREAD

**Issue by adavia** [reactstrap/reactstrap#733]
**Issue description**
Cannot access event when using Modal events

components: Modal
reactstrap version ^5.0.0-alpha.4
react version ^16.1.1
bootstrap version ^4.0.0-beta.2

**What is happening?**
Lets say i want to access event like doing:

```
<Modal
        onClosed={(e) => {
          console.log(e)
        }}
</Modal>
```
I get undefined. Any idea why are you guys omitting this?

**Comment by slhawkins** [comment]
Are you expecting the event `hidden.bs.modal`? Reactstrap uses `Transition` from `react-transition-group` for closing/hiding, and it does not provide an event of any kind for exiting. So it's not being omitted on purpose, it's just simply not available with this implementation.

**Comment by TheSharpieOne** [comment]
Looking at this again after the work which was done on the Modal. We don't seem to have access to the event, only `node`

https://github.com/reactstrap/reactstrap/blob/4dea4a639973918d178ca666c7c85899045a1d03/src/Modal.js#L142-L151

`node` can be passed to the callback. Would that help you issue?
