### ISSUE TITLE
form validation and error handling

### ISSUE THREAD

**Issue by aseroj** [reactstrap/reactstrap#737]
i have read the docs and could not find anything regarding to form validation and error handling and error texts. 

I think a feature [like this](http://www.material-ui.com/#/components/text-field) should be fair to have in reactstrap or if this already exists please let us know and add it to the documentations.

**Comment by TheSharpieOne** [comment]
Much like in the material library you linked, reactstrap has ways to show field level validation messages (using bootstrap classes and styles).
If you need actual validation, again just like with the material library, it's not part of the library. You can implement that feature yourself in your own code or find another library which does that for you (there are tons of validation libraries (like react-formik) and at least one validation library that works directly with reactstrap (availity-reactstrap-validation)).
reactstrap does the same thing bootstrap does here, which is absolutely nothing, relying only on the native browser validation.

If you want to use bootstrap validation styles, you will need to disable the native browser validation and handle that validation yourself, as noted in bootstraps docs. If you don't want to do that, and still want the validation styles, that is where something availity-reactstrap-validation comes into play.

**Comment by aseroj** [comment]
already started to use [availity-reactstrap-validation](https://github.com/Availity/availity-reactstrap-validation).
