### ISSUE TITLE
Modal not updating dynamic content

### ISSUE THREAD

**Issue by arpitprod** [reactstrap/reactstrap#740]
it's looking as same #35 issue but I can't reopen that issue so, creating new one

I'm using these versions - 
```
react - 16.2.0,
reactstrap - 5.0.0-alpha.4,
bootstrap - 4.0.0-beta.2
```

**full details**

I'm using a component in modal and changing dynamic content with state and props but Modal is not updating dynamic until we don't close Modal and open again with isOpen props

**Comment by TheSharpieOne** [comment]
If you can provide some code I can help determine the cause of the issue. For now, here is an example using react 16.2.0 with reactstrap 5.0.0-alpha.4 showing that the contents within a modal can be dynamic: https://stackblitz.com/edit/reactstrap-v5a4-dynamic-modal-content?file=Example.js

**Comment by arpitprod** [comment]
here is not bug. issue was in my code. I was not adding componentWillReceiveProps in another component.
so, that component was not updating until close and reopen Modal
