### ISSUE TITLE
Is it possible to set fixed 12hrs format for <Input type="time" /> ??

### ISSUE THREAD

**Issue by sovanjana** [reactstrap/reactstrap#742]
Input type "time" takes pc's time format as default time format but I want to use fixed 12 hours format. Is it possible to set fixed 12hrs format for input type "time".

**Comment by supergibbs** [comment]
That is a function of the browser and is currently inconsistent. I try to use a third-party library to ensure it's the same for all your users. In any case, that is out of scope for reactstrap.
