### ISSUE TITLE
Dark navbar problems

### ISSUE THREAD

**Issue by 0x111** [reactstrap/reactstrap#743]
### Issue description

- components: `NavBar`
- reactstrap version `5.0.0-alpha.4`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `16.2.0`
- bootstrap version `4.0.0-beta.2`

### What is happening?

How can create a dark navbar with this version? I tried it various ways and the navbar is just gone.

### Steps to reproduce issue

1. I was using the example from the website. https://reactstrap.github.io/components/navbar/
2. Get the first example from the url, change the light prop to dark.

**Comment by supergibbs** [comment]
It's a little confusing how bootstrap does this. The `dark` prop lets everything in the `Navbar` that it has a dark background so the components use their light foreground. You still need to set the background color though. This will get you something like http://getbootstrap.com/docs/4.0/examples/starter-template/
```
<Navbar dark className="bg-dark">...</Navbar>
```

**Comment by 0x111** [comment]
Thanks, that has solved the problem. The class was missing. Maybe for future reference it would be good to have such an example on the reactstrap page with this short explanation. It would help a lot.
