### ISSUE TITLE
Please update npm version.

### ISSUE THREAD

**Issue by codefln** [reactstrap/reactstrap#745]
Hi! I'm trying to install last version: npm install reactstrap@5.0.0-alpha.4

But after installation, the module does not contain these edits:
https://github.com/reactstrap/reactstrap/pull/690

**Comment by TheSharpieOne** [comment]
I am using reactstrap@5.0.0-alpha.4 from npm and I get the changes referenced in the release. Can you confirm the version in the node modules directory directly?

**Comment by supergibbs** [comment]
It's working for me but an `alpha.5` seems due anyway. Quite a few changes to get `BS4-beta.2` working are in master but not released. Would be nice to start using the Projects tab to help prioritize issues and show upcoming releases. I'd be happy to help on the project management side along with coding. LMK!

**Comment by lukeon** [comment]
Actually I have problem with input addons. Your documentation and repo (since commit [fa3555ff2ea9e9aea47a3fb41dfbccb516188cb1](https://github.com/reactstrap/reactstrap/commit/fa3555ff2ea9e9aea47a3fb41dfbccb516188cb1)) are updated with new BS4 input addon styles, but you still didn't release new version.

**Comment by supergibbs** [comment]
Yes, we're working on it. If you need it asap, you can compile a local version

**Comment by LukeOak** [comment]
Have you got approximate estimated date for new release withone you can publish?

**Comment by kirkins** [comment]
Bump for npm release to fix addons. Thanks,

https://github.com/reactstrap/reactstrap/issues/766

**Comment by LukeOak** [comment]
New version have been released. Thanks

**Comment by kirkins** [comment]
@LukeOak great! Do you know if `bootstrap": "^4.0.0-beta.3"` is still the recommend bootstrap version to use with the update?

**Comment by LukeOak** [comment]
Actually I migrated to version `4.0.0` and everything seems to be fine. `reactstrap` is using same version as well

**Comment by supergibbs** [comment]
Yes 4.0 should work
