### ISSUE TITLE
Carousel is missing in types

### ISSUE THREAD

**Issue by epaillous** [reactstrap/reactstrap#746]
### Issue description

- components: `Carrousel`
- reactstrap version `#5.0.0-alpha.4`
- import method `es`
- react version `#16.2.0`
- bootstrap version `#4.0.0-beta.2`

### What is happening?

I am using react with typescript.
When I try : 

import { Carousel } from 'reactstrap';

I get the following error :

(..)/@types/reactstrap/index"' has no exported member 'Carousel'

Carousel does not appears in this list : 
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/reactstrap/lib

Thank you for your help :)

**Comment by supergibbs** [comment]
Looks like @KurtPreston last updated DefinitelyTyped. Maybe he can again? Regardless, the issue is in DefinitelyTyped. There is talk about officially supporting TS though. https://github.com/reactstrap/reactstrap/issues/276

**Comment by KurtPreston** [comment]
@supergibbs DefinitelyTyped/DefinitelyTyped#22512

**Comment by supergibbs** [comment]
Awesome, thanks!
