### ISSUE TITLE
Suppress `col` className in `Col` component

### ISSUE THREAD

**Issue by guludo** [reactstrap/reactstrap#750]
### Issue description

- components: `Col`
- reactstrap version `#5.0.0-alpha.4`
- bootstrap version `#4.0.0-beta.2`

### What is happening?

Sometimes it's not desirable to have a column element having the class `col`. For example, one might want to reproduce the [Stacked to horizontal](https://getbootstrap.com/docs/4.0/layout/grid/#stacked-to-horizontal) example from Bootstrap's documentation.

In my specific case, I wan my columns to have only the class `col-md-4`. If I use `<Col md='4'>My content</Col>` the resulting HTML element will have the class `col col-md-4`. By looking into `Col`'s source code, I found out that I can get rid of the `col` class by setting `xs={false} md='4'`, but I believe that's not the correct way of doing it (right?).

I think it would be nice to have an "intended" way of suppressing the `col` class name.

**Comment by jharris4** [comment]
I actually have the opposite problem, i'm finding that the `col` class is missing, which was unexpected for me...

**Comment by supergibbs** [comment]
The `xs` prop is defaulted to `true` here  https://github.com/reactstrap/reactstrap/blob/master/src/Col.js#L63 so I guess maybe that could be removed to require `xs={true}` to add `col` class instead. I don't see anything wrong with using `xs={false}` to prevent the `col` class though and reversing it would be a pretty big breaking change for a lot of projects.

**Comment by pravdomil** [comment]
Class `col` should be defined only as a fallback if any `col-*` classes are not present.

Now I need to type `xs={false}` into every `Col` so that they stack on mobile devices. So maybe I just ended up with `<div className="col-md-6">`.

BTW: I haven't found any usage of `<div class="col col-md-6">` (which is now generating reactstrap) in official Bootstrap 4.0 documentation

**Comment by supergibbs** [comment]
There is a similar example here: http://getbootstrap.com/docs/4.0/layout/grid/#variable-width-content

I tend to agree though. Maybe if you want to add `col`, you should have to include `xs` prop but as I mentioned above, this would be a pretty big breaking change. @TheSharpieOne needs to weigh in here.

**Comment by TheSharpieOne** [comment]
`col` is in [bootstrap's documentation](http://getbootstrap.com/docs/4.0/layout/grid/) and features things like `<div class="col col-lg-2">` (showing `col` in conjuction with a col-breakpoint value)
I'm fine with making this change if everyone thinks it is the right thing to do. Breaking changes don't matter, we have semvar.

**Comment by supergibbs** [comment]
Yes, `col` is still useful but should be opt in with `xs` prop. Fits the no `prop={false}` guideline. :)

**Comment by pravdomil** [comment]
Yes, that's what I would expect from `Col`.

`<Col md={6}>` should create `<div class="col-md-6">`

`<Col md={6} xs>` should create `<div class="col col-md-6">`

`<Col>` should create `<div class="col">`

Does it makes sense for everybody?
