### ISSUE TITLE
Navbar color Documentation

### ISSUE THREAD

**Issue by WeslleyNasRocha** [reactstrap/reactstrap#752]
The new BootStrap 4 [docs](https://getbootstrap.com/docs/4.0/components/navbar/#nav) says that the `bg-` property, it's now `light` and not `faded` anymore. This should be changed in the docs, or explained, at least.

**Comment by WeslleyNasRocha** [comment]
This took me long 3 hours to figure out

**Comment by peterblazejewicz** [comment]
ref: https://github.com/twbs/bootstrap/pull/22836#issuecomment-310945638

**Comment by supergibbs** [comment]
Reactstrap documentation shows how to use reactstrap and documents the available props. It assumes you are familiar with bootstrap already. Now that bootstrap in final, there should be fewer issues like this.
