### ISSUE TITLE
Support <span> in NavbarBrand

### ISSUE THREAD

**Issue by Xerillio** [reactstrap/reactstrap#753]
I'm trying to make a navbar that uses a `<span>` as the [bootstrap docs](https://getbootstrap.com/docs/4.0/components/navbar/#brand) suggest for a non-clickable brand. Is this possible with the current implementation?

- components: `NavbarBrand`
- reactstrap version `npm v5.0.0-alpha.4`
- react version `16.0.0`

**Comment by sebacruz** [comment]
As the documentation says, you can change the tag generated by the `NavbarBrand` component using the `tag` property:

```js
<NavbarBrand tag="span">reactstrap</NavbarBrand>
```

**Comment by Xerillio** [comment]
Ah great, didn't get that.
