### ISSUE TITLE
Issue with Modal on nested modals unmount.

### ISSUE THREAD

**Issue by mmartyniuk** [reactstrap/reactstrap#761]
### Issue description

- components: `Modal`
- reactstrap version `5.0.0-alpha.4`
- react version `16.2.0`
- bootstrap version `4.0.0-beta.2`

### What is happening?

modal-open class is removing from <body> when I have a modal which is always opened and nested modals in it which are mounting and un-mounting when it is needed.

### What should be happening?
modal-open class for parent modal should not be removed till i not close it.
### Steps to reproduce issue
1) Go to https://codepen.io/anon/pen/WdOgPd
2) find body element 
3) click on the buttons and notice that 'modal-open' class disappears while main modal window is opened.

**Comment by TheSharpieOne** [comment]
Looks like an easy fix if anyone wants to put up an PR. Just need to check that the modal is open before removing the class (probably want to also wrap the other things (like the scrollbar stuff) in the same check)

https://github.com/reactstrap/reactstrap/blob/master/src/Modal.js#L159-L160

**Comment by mmartyniuk** [comment]
Please note that opening nested modal adds one more 'modal-open' class to body.
