### ISSUE TITLE
Add tag prop to Col component

### ISSUE THREAD

**Issue by LKay** [reactstrap/reactstrap#764]
### Issue description

- components: `Col`

### What is happening?

The `Col` component does not accept `tag` prop to generate html code. 

### What should be happening?

Similar to `Row` component this one should also accept `tag` prop to reuse grid classes for example to generate horizontal list as described here: https://getbootstrap.com/docs/4.0/content/typography/#description-list-alignment

### Code

Example of where it would be useful:
```jsx
function HorizontalList() {
    return (
        <Row tag="dl">
            <Col tag="dt" md={ 3 }>Title</Col>
            <Col tag="dd" md={ 9 }>Description</Col>
        </Row>
    );
}
```

**Comment by TheSharpieOne** [comment]
Col already has a `tag` prop which controls the HTML element it generates. See https://stackblitz.com/edit/reactstrap-v5a4-col-tag?file=Example.js
