### ISSUE TITLE
[Question] How to validate checkbox?

### ISSUE THREAD

**Issue by fantua** [reactstrap/reactstrap#768]
How can I validate following checkbox (code is taken from [docs](https://reactstrap.github.io/components/form/)):

```js
<FormGroup check>
    <Label check>
        <Input type="checkbox" />{' '}
        Check me out
    </Label>
</FormGroup>
```

Setting `valid={false}` prop to `Input` component doesn't work. 

Also where should I put `FormFeedback` component in this case?

**Comment by supergibbs** [comment]
I just looked at bootstrap and they only support `invalid-feedback` on a [custom form control ](http://getbootstrap.com/docs/4.0/components/forms/#supported-elements). I created a PR to fix this https://github.com/twbs/bootstrap/pull/25210 but in the meantime, the missing CSS rule is:
```
.was-validated .form-check-input:invalid ~ .invalid-feedback, 
.was-validated .form-check-input:invalid ~ .invalid-tooltip, 
.form-check-input.is-invalid ~ .invalid-feedback, 
.form-check-input.is-invalid ~ .invalid-tooltip {
    display: block;
}
```

Just add that then @TheSharpieOne code above should work. A `FormFeedback` just needs to be added in the `FormGroup` (as a sibling to the `Input`).

**Comment by fantua** [comment]
Thanks for explanations. 

@supergibbs is bootstrap removed support for wrapping inputs with labels? I have reusable form component and adding `id` for checkboxes can be a little bit complicated (to avoid duplications). Or I need to ask this question in the bootstrap repo?

**Comment by supergibbs** [comment]
I don't speak for bootstrap but it seems in general it should still work. I see two cases that rely on siblings though. Muting the label when checkbox is disabled and validation so you'll have to use `id` for those cases.

**Comment by rahamin1** [comment]
I have built a small test example that includes different types of controlled components, maybe it can help.
It can be found [here](https://github.com/rahamin1/reactstrap-form), and tested [here](https://reactstrap-form.herokuapp.com/).
