### ISSUE TITLE
Modal fade out animation failed if change content when close modal:

### ISSUE THREAD

**Issue by kennywangjin** [reactstrap/reactstrap#772]
### Issue description

- components: `Modal`
- reactstrap version `#5.0.0-alpha.4`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `#16.2`
- bootstrap version `#4.0.0-beta.3`

### What is happening?
when i try to change modal content and close modal concurrently, modal fade out animation failed.

### What should be happening?

modal should fade out

**Comment by supergibbs** [comment]
Please try with the latest version (both BS 4.0 and reactstrap) and if still an issue, post an example
