### ISSUE TITLE
Error while Alert showing

### ISSUE THREAD

**Issue by pvaritta** [reactstrap/reactstrap#774]
it has error with the 'Alert' component when it's appear. I using react version 15.6.1, reactstrap version 4.8.0 and bootstrap version 4.0.0-alpha.6 

It's showing error on console as 
_Invariant Violation: Unable to find node on an unmounted component._

and after that the program is freezing.

Thank you

**Comment by KamiGim** [comment]
I face the exact problem too

**Comment by pvaritta** [comment]
I found the issue. Thank you

**Comment by shanecav84** [comment]
@pvaritta What was the solution?
