### ISSUE TITLE
Change theme colours question

### ISSUE THREAD

**Issue by FWMatt** [reactstrap/reactstrap#776]
### Issue description

- components: all
- reactstrap version `#5.0.0`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `#0.16.0`
- bootstrap version `#4.0.0`

### What is happening?

This is a question - might have a super simple answer. What is the simpliest way of overriding theme colours (i.e. primary, danger etc) via react code?

(I've searched documentation and can't find a straightforward answer - not sure if I'm missing something + sorry if I am!)

Thanks!

**Comment by TheSharpieOne** [comment]
>What is the simpliest way of overriding theme colours (i.e. primary, danger etc) via react code?

Via react, none that I know of.

This library adds the bootstrap classes which use CSS. You can override the SASS variables in bootstrap and create a custom build/theme.

You can apply inline styles, but that doesn't really allow you to override the theme colors as much as override individual styles.

**Comment by FWMatt** [comment]
OK - thanks for the swift response and the great repo.

**Comment by saplf** [comment]
I found the method bootstrap [supplied](http://getbootstrap.com/docs/4.1/getting-started/webpack/#importing-precompiled-sass) is valid to this repo as well. Just remember to remove 

```js
import 'bootstrap/dist/css/bootstrap.css'
```

in your enter point file.

**Comment by rkej** [comment]
I know this is pretty late but you can edit bootstrap.min.css file in bootstrap/dist/css/bootstrap.min.css and replace the primary color code to whatever you want. Remember to do a replace all for best results. Just remember to correct the --blue tag to #007bff. Worked well for me.

**Comment by matiassicardi** [comment]
Hi everybody. I'm just wondering if is there any kind of Reacstrap theme switcher, something that allows us to switch between different bg and colors on the Bootstrap's className that came with the components.
