### ISSUE TITLE
Adding "dropright"/"dropleft" prop to Dropdown component

### ISSUE THREAD

**Issue by DhawalRank** [reactstrap/reactstrap#785]
### Issue description

- components: `Dropdown`
- reactstrap version: `4.8.0`
- import method 'reactstrap/DropDown';
- react version `16.2.0`
- bootstrap version `4`

### What is happening?

Nesting a dropdown into another dropdown

### What should be happening?

There should be a prop option "drop" right as provided by bootstrap as a class named "dropright" to open the dropdown menu on the right of the dropdown button

**Comment by TheSharpieOne** [comment]
The `DropdownMenu` has a prop `right` which accepts a boolean to indicate whether or not the menu should open to the right. 
See the Alignment section of https://reactstrap.github.io/components/dropdowns/

**Comment by flipxfx** [comment]
Should we create a new issue to get reactstrap caught up with the official release?

**Comment by TheSharpieOne** [comment]
We can just use individual issues and add them to the same milestone or project to group them together.

**Comment by supergibbs** [comment]
Instead of adding more props I deprecated `dropup` and replaced with `dropDirection`. You can set `dropDirection` to  "down" (default), "up", "left" or "right". Is still backwards compatible with `dropup` IF you don't use `dropDirection`.  See #813
