### ISSUE TITLE
Reactstrap snippets for VScode

### ISSUE THREAD

**Issue by dimpu** [reactstrap/reactstrap#786]
First of all, I absolutely love  Reactstrap. Thank yours for creating it. Is there any extension for Reactstrap snippets package for VScode? Something like this `https://marketplace.visualstudio.com/items?itemName=thekalinga.bootstrap4-vscode.`

**Comment by supergibbs** [comment]
Not done by this team. Sounds like a cool project idea though!

**Comment by jjpatel361** [comment]
For all users who might stumble upon this, there is an extension published [VSCode Snippets for ReactStrap](https://marketplace.visualstudio.com/items?itemName=jjpatel361.reactstrap-snippets)

**_Note: This is still under active development._**
