### ISSUE TITLE
feature: add to Dropdown onFocusLost

### ISSUE THREAD

**Issue by Woile** [reactstrap/reactstrap#787]
Hi folks, I was wondering if it'd be possible to include in the `Dropdown` component a way to handle the on focus lost, by this, I mean, when the user clicks outside the dropdown, in consequence the dropdown closes, but it would be great to be able to perform some actions after it closes.

Maybe there's already a way to do it, but I do not know how, maybe someone could help me.

Thanks!

**Comment by supergibbs** [comment]
The solution @TheSharpieOne created here https://github.com/reactstrap/reactstrap/issues/780 should be able to achieve what you want.
