### ISSUE TITLE
Collapse

### ISSUE THREAD

**Issue by eddywashere** [reactstrap/reactstrap#79]
http://v4-alpha.getbootstrap.com/components/collapse/
- [x] Collapse
  - consider using refactoring [Fade component](https://github.com/reactstrap/reactstrap/blob/master/src/Fade.jsx)

**Comment by eddywashere** [comment]
Todo: list transition states and classes. I looked at this for a bit and I think there's something more to just adding and removing classes during these states. I believe there is a height inline style applied before showing the content.

**Comment by LiJinyao** [comment]
I'd like to build this component😊,  can you assign it to me?

**Comment by lvauvillier** [comment]
Humm, I didn't see this issue before sending a PR (#190) for the navbar.
Maybe I can help here and update it to do a more generic one with a Collapse component

**Comment by LiJinyao** [comment]
Ops, My work almost finished. Maybe you can left it to me.

**Comment by eddywashere** [comment]
@lvauvillier I saw the pr. I was going to suggest that you use or look into the work @LiJinyao is doing. Thanks for the update @LiJinyao. Let me know if you need anything. Component is looking good. I'll try it out as soon as I get some free time. Traveling this week until Monday.

**Comment by lvauvillier** [comment]
@LiJinyao thanks for your work, I'll try it with the navbar toggler.
@eddywashere If all works fine, I'll update my PR using the new `Collapse` component. (My PR will finally just be a doc update for the navbar toogler use case)

**Comment by lvauvillier** [comment]
@LiJinyao's, your Collapse component is working fine
I created a branch with a sample mixing Collapse and the navbarToggler here : https://github.com/lvauvillier/reactstrap/tree/NavbarToggler-sample

Ready to PR when your component will officially be available.

**Comment by LiJinyao** [comment]
@lvauvillier Good job! I'll make a PR toady.

**Comment by eddywashere** [comment]
released in 3.8.0, thanks @LiJinyao!

**Comment by gthomas-appfolio** [comment]
FYI bootstrap v5 alpha now uses `collapse active` instead of `collapse in`:

https://github.com/twbs/bootstrap/pull/21019

What's the proper way to follow up with these changes in the reactstrap codebase?  PR as they are made in BS4 or you wait for certain milestones?

**Comment by eddywashere** [comment]
@gthomas-appfolio thanks for the heads up! There's nothing official about this for reactstrap. PRs for official upcoming changes are more than welcomed. We can label them as `waiting-on-bs4-release` or something more appropriate. They can be shipped as soon it's released upstream.

Does that work for you? Or are you looking for something like a prerelease branch for stuff in `twbs:v4-dev` (bs4 latest).

**Comment by eddywashere** [comment]
@gthomas-appfolio tracking these changes over at #224.

**Comment by gthomas-appfolio** [comment]
Sorry just saw, sounds great @eddywashere
