### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by eddywashere** [reactstrap/reactstrap#80]
http://v4-alpha.getbootstrap.com/components/carousel/
- [ ] Carousel
- [ ] CarouselItem

**Comment by raavanan** [comment]
Hey @eddywashere , I want to do help build this Component.

**Comment by raavanan** [comment]
calling Dibs on this. I have started work.

**Comment by raavanan** [comment]
@eddywashere  I have joined your slack team. I have forked the repo, and am studying the codebase. please ping me on starting work on this.

**Comment by raavanan** [comment]
@eddywashere So here is the breakdown for the carousel component wise.

- [ ] Carousel (container)
- [ ] CarouselIndicators
- [ ] CarouselItem
- [ ] CarouselCaption
- [ ] CarouselControl (left and right)

**Comment by eddywashere** [comment]
Looks good to start to me. I assume the methods would live on the wrapping component and get passed via state or context. Same for options via props?

**Comment by raavanan** [comment]
Yup, that's the plan.

**Comment by chefnobody** [comment]
@raavanan Any chance this Component will be wrapped up soon? I could make use of it asap 😃

**Comment by raavanan** [comment]
@chefnobody I am done with most of the logic. been busy with work lately.. will knock this off this weekend

**Comment by chefnobody** [comment]
@raavanan You're a good man! I'll keep an eye out for a PR, then. 👍

**Comment by TheSharpieOne** [comment]
@raavanan Any update?

**Comment by nielk** [comment]
Hey, can someone finish this component? 😃

**Comment by louisscruz** [comment]
Are there any updates with this? Very much looking forward to a carousel!

**Comment by Gribbs** [comment]
Boooooo! No carousel still

**Comment by slimeygecko** [comment]
@raavanan, It looks like you've come a long way on the carousel. I'd be happy to finish it up for you. Do you have a fork / branch that has the code in it?

**Comment by mpartipilo** [comment]
Please update #13 with this. Thanks :+1:
