### ISSUE TITLE
Custom classNames order

### ISSUE THREAD

**Issue by xymopen** [reactstrap/reactstrap#800]
### What is happening?
Rare cases we need to modify Bootstrap CSS rules to fit our needs, but custom classNames would be added **before** Bootstrap classNames, causing Bootstrap CSS rules override custom ones.

### What should be happening?
Adding custom classNames **after** Bootstrap classNames to let us override Bootstrap rules.

**Comment by TheSharpieOne** [comment]
That is not how CSS works. See #423 

Also see: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Comment by xymopen** [comment]
Sorry for the inconvenience. It was my mistake. 😂
