### ISSUE TITLE
Is it possible to use individual CSS instead of full bootstrap.css file?

### ISSUE THREAD

**Issue by vinaybedre** [reactstrap/reactstrap#803]
Hi,

Is it possible to use individual component's scss or compiled css files along with reactstrap, instead of importing whole bootstrap.css file?

**Comment by TheSharpieOne** [comment]
The styles you import is up to you. The only "requirement" is that the classes are bootstrap classes (through you can get around that with some cssModule trickery).
If you wanted, you can have a scss file which just imports specific bootstrap styles; making a custom build essentially.
