### ISSUE TITLE
Utility Classes

### ISSUE THREAD

**Issue by eddywashere** [reactstrap/reactstrap#81]
http://v4-alpha.getbootstrap.com/components/utilities/
- [ ] Identify which utils to include as components

**Comment by TheSharpieOne** [comment]
Looking at this not too many of the utility classes can be included as individual components. Most of them are just adding a class to something... anything. If each one was it's own component, it would be a pain as often the utilities are combined.
If there was a single Utility component which had attributes for all of the classes, it would save the trouble of having to use className, but would essentially be a one-to-one of prop to class. We can shorten/assume some of the classNames from the props such as `text-uppercase` could just be `uppercase` prop. 
```
<Utility tag="p" left="md" right={['xs', 'lg']} mt={1} pa={2} uppercase color="success" bg="inverse">test</Utility>
```
would become
```
<p class="text-md-left text-xs-right text-lg-right m-t-1 p-a-2 text-uppercase text-primary bg-inverse">test</p>
```

These two are a tiny bit more than just adding classes:
[Close Icon](http://v4-alpha.getbootstrap.com/components/utilities/#close-icon)
[Responsive Embeds](http://v4-alpha.getbootstrap.com/components/utilities/#responsive-embeds)

**Comment by eddywashere** [comment]
Closing this out. I think it's reasonable to use className for utility classes.
