### ISSUE TITLE
Ability to pass down Popper modifiers from the Dropdown/DropdownMenu

### ISSUE THREAD

**Issue by aleksey-shmatov** [reactstrap/reactstrap#811]
### Pass down Popper modifiers
There is no way to pass Popper modifiers from the Dropdown/DropdownMenu interface. Similar issue https://github.com/reactstrap/reactstrap/issues/732 was fixed for Popover but not for Dropdowns. My use case is trying to add some offsets for dropdown positioning.

- components: `Dropdown, DropdownMenu`
- reactstrap version `#5.0.0-beta`
- import method `es`
- react version `#15.6.1`
- bootstrap version `#4.0.0-alpha.1`

**Comment by borm** [comment]
https://github.com/reactstrap/reactstrap/pull/929
