### ISSUE TITLE
Tooltip not testable in virtual DOMs

### ISSUE THREAD

**Issue by cavaloni** [reactstrap/reactstrap#818]
### Issue description

- components: `Tooltip`
- reactstrap version `5.0.0-alpha.3`
- import method `es'
- react version `15.5.4`
- bootstrap version `?`

### What is happening?

Not sure whether is issue here, or with Enzyme/Jest. Using Jest/Enzyme with Reactstrap returns a null with `querySelector` (method used for getting `target` passed to `Tooltip`), likely due to DOM elements not yet rendered in JSDOM (used by Jest).

This works just fine in browser, not in testing environment using a virtual DOM.

### What should be happening?

Component should be mounted without error, and should likely be accessing DOM after mount.

### Steps to reproduce issue

1. Use Tooltip as suggested.
2. Add a target in component
3. Run tests with Enzyme and Jest, or other testing environment using a virtual DOM.

### Error message in console

> TypeError: Cannot read property 'addEventListener' of null
> 
>       at Tooltip.addTargetEvents (node_modules/reactstrap/dist/reactstrap.cjs.js:4156:20)
>       at Tooltip.componentDidMount (node_modules/reactstrap/dist/reactstrap.cjs.js:4056:12)
>       at node_modules/react-dom/lib/ReactCompositeComponent.js:262:25
>       at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)
>       at node_modules/react-dom/lib/ReactCompositeComponent.js:261:11
>       at CallbackQueue.notifyAll (node_modules/react-dom/lib/CallbackQueue.js:74:22)
>       at ReactReconcileTransaction.close (node_modules/react-dom/lib/ReactReconcileTransaction.js:78:26)
>       at ReactReconcileTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:207:25)
>       at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:154:16)
>       at batchedMountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:124:15)
>       at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:141:20)
>       at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:26)
>       at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:95:27)
>       at Object._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:317:18)
>       at Object._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:399:32)
>       at Object.render (node_modules/react-dom/lib/ReactMount.js:420:23)
>       at Object.renderIntoDocument (node_modules/react-dom/lib/ReactTestUtils.js:89:21)
>       at renderWithOptions (node_modules/enzyme/build/react-compat.js:200:24)
>       at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:94:59)
>       at mount (node_modules/enzyme/build/mount.js:19:10)
>       at Object.<anonymous> (comp/static/components/elements/suggestions/__tests__/suggestions-modal.spec.js:38:32)
>           at new Promise (<anonymous>)
>       at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
>           at <anonymous>
>       at process._tickCallback (internal/process/next_tick.js:188:7)
> 

### Code

> 	<div className="distribution">
> 				<div className="adj-item-head">
> 					Distribution <button className="icon-info" />
> 				</div>
> 				<div className="dist-buttons">
> 					<label
> 						className={proLabelClass}
> 						htmlFor="proportional"
> 						id="proportional"
> 					>
> 						<input
> 							checked={distribution === 'proportional'}
> 							className="dist-radio-butt"
> 							disabled={warn}
> 							name="proportional"
> 							onChange={changeSpread}
> 							type="radio"
> 						/>
> 						<span className="radio-name">Proportional</span>
> 					</label>
> 					<label className={evenLabelClass} htmlFor="even" id="even">
> 						<input
> 							checked={distribution === 'even'}
> 							disabled={warn}
> 							name="even"
> 							onChange={changeSpread}
> 							type="radio"
> 						/>
> 						<span className="radio-name">Even</span>
> 					</label>
> 					<label className={customLabelClass} htmlFor="custom">
> 						<input
> 							checked={distribution === 'custom'}
> 							disabled={warn}
> 							name="custom"
> 							onChange={changeSpread}
> 							type="radio"
> 						/>
> 						<span className="radio-name">Custom</span>
> 					</label>
> 					<Tooltip
> 						className="tooltip-warning"
> 						innerClassName="warning-inner"
> 						isOpen={warn}
> 						placement="bottom"
> 						target={nextSpread || 'proportional'}
> 					>
> 						<div className="tooltip-warn">
> 							<span className="icon-warn" />
> 							<span className="tooltip-warn-message">Alert</span>
> 						</div>
> 						<p>
> 							All of your custom changes to compensations will be
> 							erased if you change the distrbution from 'custom'.
> 						</p>
> 						<p>Would you like to change the distrbution?</p>
> 						<div className="button-container">
> 							<Button onClick={() => closeWarnTip(false)}>
> 								Cancel
> 							</Button>
> 							<Button onClick={() => closeWarnTip(true)}>
> 								Proceed
> 							</Button>
> 						</div>
> 					</Tooltip>
> 				</div>
> 			</div>
>

**Comment by gergely-nagy** [comment]
I am not sure I understand the issue, but you can check our test cases.
https://github.com/reactstrap/reactstrap/blob/2b71fd633ece693089c35ad32d44df84d5776cb3/src/__tests__/Tooltip.spec.js#L1-L567

**Comment by cavaloni** [comment]
Interesting. Thanks for the quick response. It gave me the idea needed to make the test passable. 

I am wondering, however,  how others might have handled this because it does not seem a very intuitive way to make a test pass. Basically my question was that the `target` passed to `Tooltip` returns null, because a querySelector is used in this function here: 

(https://github.com/reactstrap/reactstrap/blob/2b71fd633ece693089c35ad32d44df84d5776cb3/src/utils.js#L121)

which attempts to obtain the target by using querySelectors. In a real DOM this seems to work just fine, but in a virtual DOM, like JSDOM used by Jest, it returns null because the elements have not truly/virtually mounted yet. 

Manually setting the target, however, like you have in your tests can make them passable because it then has an element to attach to and therefore not failing on `addEventListener`.

**Comment by TheSharpieOne** [comment]
See #738. It's because you are mounting your component outside of the document, it's still in the DOM, just at a different location than reactstrap looks. querySelector looks at all of the descendents from the node it is referenced from (document in this case) so you must place your target within that node. Enzyme allows you to specify where you mount the component with attachTo.

**Comment by cavaloni** [comment]
Thanks @TheSharpieOne, those are all helpful considerations. The reason why Tooltip is getting thrown in the test is because I am doing integration tests and e2e tests and it can be a bit troublesome to mock out every library component. But you are right that the testing is redundant so that seems the best solution.
