### ISSUE TITLE
Image Widget

### ISSUE THREAD

**Issue by supun19** [reactstrap/reactstrap#819]
i have a  256x256 image different place i want to use that image like circle or square with different size 16x16,32x32, with boarder without boarder could you implement that feature

**Comment by supergibbs** [comment]
Bootstrap has a few [helper classes for images](http://getbootstrap.com/docs/4.0/content/images/) and some [border-radius utilities](http://getbootstrap.com/docs/4.0/utilities/borders/) but they are just classes so there aren't any `reactstrap` components to use them.
