### ISSUE TITLE
How do I capture button group change event and values as checkboxes?

### ISSUE THREAD

**Issue by wzup** [reactstrap/reactstrap#821]
I want to use button group as a checkbox. How can I do it? Could you please add some documentation on that. What methods do I use?

This should be radio buttons:
```
<ButtonGroup>
    <Button>AAA</Button>
    <Button>BBB</Button>
    <Button>CCC</Button>
</ButtonGroup>
```

**Comment by TheSharpieOne** [comment]
See #300, Here is a demo: https://stackblitz.com/edit/reactstrap-v5beta-zxdfeh?file=Example.js
Since the state is managed by your component, you don't need use actual inputs (such as bootstrap does).

**Comment by wzup** [comment]
Switched over to plain old Bootstrap 4 and happy

**Comment by TheSharpieOne** [comment]
Yep, works exactly the same. You manage the state yourself. The only thing reactstrap does for these components is abstract the classNames, so you adding the classNames yourself is the same thing.
