### ISSUE TITLE
Add color list for navbar

### ISSUE THREAD

**Issue by AlexanderInsulin** [reactstrap/reactstrap#823]
### Issue description
Add list for navbar colors 
- components: `navbar`
- reactstrap version `#5.0.0-beta`

### What is happening?

User should go to getbootstrap to know possible navbar colors.

### What should be happening?

User see possible colors in navbar topic

### Steps to reproduce issue

1. Open [navbar](http://reactstrap.github.io/components/navbar/)
2. Don't find possible color list

**Comment by gergely-nagy** [comment]
Hey @AlexanderInsulin ,

Each component uses the same color palette. 
I think it is redundant in every component to display this information.

But, we could add the background colors and gradients to the Utilities section, 
like bootstrap did. https://getbootstrap.com/docs/4.0/utilities/colors/#background-color

 @TheSharpieOne @supergibbs

**Comment by supergibbs** [comment]
Agreed, available colors are set by bootstrap not reactstrap. The prop value is used to add the class `bg-<value>` so best to refer to bootstrap docs which are valid. You can also make your own.

**Comment by TheSharpieOne** [comment]
Yes, the bootstrap color names are well-known and this library is not limited to those.
I often have to add custom colors in addition to bootstrap, sticking with generic names such as "accent" or "alternative" and those values can be provided to color.
We do not limit the user to only using the defaults bootstrap colors out of the box like other libraries do and thus there is not set list of values which can be provided.
