### ISSUE TITLE
Add ability to disable fade on <Alert />

### ISSUE THREAD

**Issue by charlex** [reactstrap/reactstrap#824]
I see this [PR](https://github.com/reactstrap/reactstrap/pull/339) was merged to allow `<Modal fade={false} />`, but I'm wondering if the `fade={false}` prop could also be used on the `<Alert />` component.

### Issue description

- components: `<Alert />, <Fade />`
- reactstrap version `5.0.0-beta`
- import method `umd` (I don't think I'm using "full")
- react version `16.2.0`
- bootstrap version `4.0.0`

### What is happening?

Attempting to use `fade={false}` on `<Alert />`, much like you can use it on the modal: `<Modal fade={false />`.

### What should be happening?

When using `<Alert fade={false} />` there should be no transition.

**Comment by TheSharpieOne** [comment]
I like this idea and I would even take it a step further. Maybe instead of toggling a single transition, we can have the ability to pick the animation and/or disable it.
The prop can be `animation` (or `transition`, but we already have `transition`...)
`animation="fade"`, (or `transition={Fade}` is we determine to just pass in the transition component) `transition="collapse"`, or `transition={false}`. We can still default to `Fade` but this allows the transition to be disabled as well as changed.

**Comment by zanisis** [comment]
but in transition always give me Warning: Failed prop type: Invalid prop `transition` of type `boolean` supplied to `Alert`, expected `object`. but i already give transition object.

```
<Alert color="dagger" isOpen={this.state._error} transition={{in: true, timeout: 150}}>
  Something Text
</Alert>
```

**Comment by TheSharpieOne** [comment]
@zanisis it's currently not possible and need to be addressed. My previous comment was a suggestion to further enhance the user's control over the transitions.

**Comment by gergely-nagy** [comment]
@TheSharpieOne I'd like to jump in on this! :rocket:

**Comment by TheSharpieOne** [comment]
@gergely-nagy go for it 👍

**Comment by googamanga** [comment]
Just make timeout 0...

**Comment by mdanilakis** [comment]
```
<Alert color="info" transition={{ baseClass: '', timeout: 0 }}>
  Hello world
</Alert>
```

**Comment by electriccode** [comment]
See if this would work #1078

**Comment by charlex** [comment]
Thanks everyone for your work!

**Comment by stevula** [comment]
Since the prop type for transition is now a React element, this can now be accomplished by specifying `<Alert transition={null}>...</Alert>`.
