### ISSUE TITLE
'reactstrap' does not contain an export named 'CardBody'

### ISSUE THREAD

**Issue by sandeepperkariappdev** [reactstrap/reactstrap#826]
### Issue description

- components: `card`
- reactstrap version `#5.0.0-beta-4`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `#16.2.0`
- bootstrap version `#4.0.0`

### What is happening?

getting error on compiling the create-react-app 'reactstrap' does not contain an export named 'CardBody'

### What should be happening?
Should not receive error
### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by TheSharpieOne** [comment]
What does `npm list reactstrap` return / print out?

**Comment by elisechant** [comment]
+1

**Comment by sandeepperkariappdev** [comment]
npm list reactstrap returns "reactstrap@5.0.0-alpha.4"

**Comment by TheSharpieOne** [comment]
do `npm install reactstrap@next` to get the latest beta release.

**Comment by BartusZak** [comment]
Installed that latest  beta version and still receiving 
`reactstrap' does not contain an export named 'Carousel'.`

`import {Carousel}  from 'reactstrap';


const advert = (props) => {
  return (
        <div className="AdvertDiv">
            <h1>Wspierają nas</h1>
            
            <Carousel>
              <Carousel.Item>
                <img width={900} height={200} alt="900x500" src="/carousel.png" />
                <Carousel.Caption>
                  <h3>First slide label</h3>
                  <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                </Carousel.Caption>
              </Carousel.Item>
              <Carousel.Item>
                <img width={900} height={200} alt="900x500" src="/carousel.png" />
                <Carousel.Caption>
                  <h3>Second slide label</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                </Carousel.Caption>
              </Carousel.Item>
              <Carousel.Item>
                <img width={900} height={200} alt="900x500" src="/carousel.png" />
                <Carousel.Caption>
                  <h3>Third slide label</h3>
                  <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                </Carousel.Caption>
              </Carousel.Item>
            </Carousel>;
            
        </div>
  );
}

export default advert;`

https://react-bootstrap.github.io/components/carousel/

**Comment by TheSharpieOne** [comment]
@BartusZak if you had the latest beta, you'd probably be seeing #870. Delete your node modules and try installing again.

**Comment by BartusZak** [comment]
1. Removed node_modules folder inside my ReactApp.

**Comment by BartusZak** [comment]
1. Removed `node_modules" folder from my ReactApp.
2. `npm install reactstrap@next --save`
3.  `npm install`
4. Inserted `import {Carousel} from 'reactstrap'` and added first code from `https://react-bootstrap.github.io/components/carousel/`
4. `npm start`
5.  `TypeError: carouselItems.map is not a function`

Error details: https://drive.google.com/open?id=1fe2GZeUB2lKXVqLvQ35Quc2XlfNhJp6Y

**Comment by TheSharpieOne** [comment]
Can you provide your code? The issue is coming from where you use carousel without any `CarouselItem` as children.

**Comment by BartusZak** [comment]
https://gist.github.com/BartusZak/70da7b1b830ffd573988c1cec6fcf5dd

**Comment by TheSharpieOne** [comment]
The carousel imports are separate. CarouselItem, not Carousel.Item (same for the others)

**Comment by BartusZak** [comment]
Ok, I get that but...

For better error msgs understanding:
I have removed 2 CarouselItems and left just one.
https://gist.github.com/BartusZak/3aa3e52df667d685e73c87248516e008

**Another error:**
`TypeError: children.every is not a function`

It is freaky coz when I am useing 3 CarouselItems, then the same error like before appears.

**Comment by TheSharpieOne** [comment]
Seems like a slight bug with handling only a single `CarouselItem`. Instead of `TypeError: children.every is not a function` it should probably throw an error like "Carousels require at least 2 items" since having a Carousel with a single item doesn't make any sense.
Here is an example with three items: https://stackblitz.com/edit/reactstrap-v5beta-nse9mm?file=Example.js
Note that with `Carousel` you have to manage the state; meaning you need to define `next` and `previous` functions to control the `activeIndex`.
You can use `UncontrolledCarousel` which abstracts some of that away.

**Comment by ehlilier** [comment]
somthing like this happened on my own defined components, how to solve it

**Comment by TheSharpieOne** [comment]
@ehlilier make sure you are exporting and importing them correctly
