### ISSUE TITLE
Dropdown seems to be missing 'active' property

### ISSUE THREAD

**Issue by crimson11** [reactstrap/reactstrap#827]
### Issue description

- components: `Dropdown`
- reactstrap version `5.0.0-beta`
- import method `es` 
- react version `16.2.0`
- bootstrap version `4.0.0`

### What is happening?
I'm using \<Dropdown\> component within \<Nav\> component (property 'nav' set to true).
I can successfully set \<DropdownItem\> property 'active', but \<Dropdown\> itself has **no** such property.
Therefore the Dropdown entry in the navbar isn't highlighted although its child (\<DropdownItem\>) is active/highlighted.

### What should be happening?

In pure Bootstrap, I would set the class of \<li\> representing the dropdown to "nav-item dropdown **active**".
Doing this would correctly highlight the Dropdown button in the navbar.
I would expect \<Dropdown\> to also expose an 'active' property.

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by TheSharpieOne** [comment]
For now the workaround is manually adding the className or using `NavItem` with the `tag` prop set to `Dropdown`
```jsx
<NavItem tag={Dropdown} nav ...>
```

**Comment by crimson11** [comment]
Shall I Close this issue? Your answer helped me a lot! I still expect, that "Dropdown" component gets an "active" property in a later release ...

**Comment by TheSharpieOne** [comment]
We can leave it open to track adding the active prop. I think that something like `nav && active && 'active'` needs to be added to the classnames.
