### ISSUE TITLE
babel-plugin-react-css-modules & reactstrap cssModule issue

### ISSUE THREAD

**Issue by gtournie** [reactstrap/reactstrap#829]
Using [babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules) & reactstrap cssModule, if I want to do:

```
import Bootstrap from 'bootstrap/scss/bootstrap.scss'
import styles from './styles'

export default class extends React.Component { 
  render() {
    return (
      <div styleName="styles.container">
        <Button cssModule={Bootstrap}>OK</Button>
      </div>
    )
  }
}
```

I get a `Cannot use anonymous style name with more than one stylesheet import.` error.
This is because `mapToCssModules` doesn't allow you to use [named references](https://github.com/gajus/babel-plugin-react-css-modules#named-reference)

Also, that would be great to add a global cssModule option, to not have to pass it to every component...

**Comment by TheSharpieOne** [comment]
The value provided to `cssModule` should be a map from the bootstrap className (such as "btn") to the generated css module className. It's really just a hash map from one string value to the other. I believe the intended use was for run-time and not compile-time. If the plugin you choose cannot do that, you will need to find a better one or you will need to create the map yourself (sounds like you can map "btn" to "bootstrap.btn" and then your plugin should be able to do the rest.)
The reason a named reference should not be needed is you are passing an object (Bootstrap in your case) which should contain only those styles, only that reference, and not the styles from other stylesheets. Objects cannot have duplicate keys, so there is no confusion as to which stylesheet you are referring to. 
As for the global way to set the cssModule, it already exists though I'm sure it's not documented :frowning:
You can grab the setGlobalCssModule method from reactstrap and call it with your cssModule. 
See: https://github.com/reactstrap/reactstrap/blob/master/src/utils.js#L49-L53

**Comment by gtournie** [comment]
`setGlobalCssModule` solves the problem. I only have to import bootstrap once so I don't have conflicts with others css anymore :)
