### ISSUE TITLE
update react-popper version

### ISSUE THREAD

**Issue by swarthy** [reactstrap/reactstrap#831]
### Issue description
Warning due yarn install
```bash
warning reactstrap > react-popper@0.7.5: please use 0.7.4 or 8.0.0 and above
```

### What should be happening?
no warning?

### Steps to reproduce issue
yarn install --dev reactstrap

**Comment by supergibbs** [comment]
Sounds like this is a `react-popper` issue with that version. https://github.com/souporserious/react-popper/issues/81

@TheSharpieOne reactstrap should probably pin to 0.7.4 for now and look into migrating to 0.8.x

**Comment by virgofx** [comment]
We should migrate to 0.8.x as it fixes some other core issues with SSR. Using the current beta Reactstrap with dependencies is currently broken with react-popper until upgrade (Need to use external version @ 0.8.x).
