### ISSUE TITLE
superimpose Two component

### ISSUE THREAD

**Issue by tetar998** [reactstrap/reactstrap#832]
Hello is there a way to superimpose reactstrap tabs with carousel ? 
I actually try to have my carousel running and my tab in the center but i don't find the good way to do that anyone have an idea ?

**Comment by tetar998** [comment]
hello 
i would like to display a carousel and over it my tab pannel

**Comment by supergibbs** [comment]
You'll probably need to use some css absolute positioning to do that. Seems out of scope for `reactstrap`.
