### ISSUE TITLE
Uncontrolled dropdowns not working

### ISSUE THREAD

**Issue by borisyordanov** [reactstrap/reactstrap#834]
### Issue description

- components: UncontrolledDropdown/UncontrolledButtonDropdown
- reactstrap version 5.0.0-beta`
- react version `16.1.1`
- bootstrap version `4.0.0`

### What is happening?

I copied and pasted the UncontrolledDropdown into my project, and though the dropdown open you can't select values. I double checked if i missed anything from the [examples](https://reactstrap.github.io/components/dropdowns/) and saw that the example doesn't work too. 

### What should be happening?

I'm aware how to set up a standard Dropdown, but what is the point of the UncontrolledDropdown if you still need to change its value with a toggle function. Isn't it supposed to work as a normal static html `<select/>` element?

**Comment by TheSharpieOne** [comment]
`Dropdown`s and `UncontrolledDropdown`s are not a replacement for `<select>`. They are intended to be used as menu dropdowns.
Here is how Bootstrap describes the dropdowns:
> Dropdowns are toggleable, contextual overlays for displaying lists of links and more.

UncontolledDropdown just makes it so you don't need to have a toggle method nor manage the isOpen state. Bootstrap doesn't have any examples working in the way you describe
