### ISSUE TITLE
Navbar not collapsing

### ISSUE THREAD

**Issue by meeoh** [reactstrap/reactstrap#837]
### Issue description
Using a navbar like `<Navbar expand>...</Navbar>` would prevent the navbar from collapsing at any browser size. 

- components: `Navbar`
- reactstrap version `^5.0.0-beta"`
- react version `^16.0.0`
- bootstrap version `^4.0.0`

### What is happening?
The navbar isnt collapsing when the browser size is small when using it like  `<Navbar expand>...</Navbar>`

### What should be happening?
It should collapse when the browser gets reasonably small (maybe sm or xs). When you use `expand="sm"` however it works completely fine

**Comment by TheSharpieOne** [comment]
Correct. When you tell it to always expand (by not passing a value to `expand`) it will always be expanded and never collapse. It's the same as if you had `expand="xs"` indicating you want it to expand on "xs" and larger (similar to how bootstrap's breakpoints work with column sizes). You should pass it the breakpoint in which you want it to start being expanded.

**Comment by meeoh** [comment]
Ah I see, was just a misunderstanding then, thanks!
