### ISSUE TITLE
onHide event does not propagate the event for the Modal component

### ISSUE THREAD

**Issue by RobbySingh** [reactstrap/reactstrap#838]
"Event" object is undefined when dismissing a modal by clicking outside of it. This occurs when writing a custom onHide function that uses the event

The cause is this code:

    handleDialogClick(e) {
        if (e.target !== e.currentTarget) {
          return;
        }
    
        this.props.onHide();
      }

e should be passed to the onHide() function

**Comment by supergibbs** [comment]
So should `e` be passed to the `toggle` prop?

**Comment by TheSharpieOne** [comment]
Yes, I think we should be passing the events to any callbacks we call when we have an event

**Comment by GoPro16** [comment]
closed via #903

**Comment by GoPro16** [comment]
closed via #903
