### ISSUE TITLE
Err with Col

### ISSUE THREAD

**Issue by fpsstyle228** [reactstrap/reactstrap#839]
### Issue description

- components: `Col`
- reactstrap version `#5.0.0`
- import Col from 'reactstrap';
- react version `#16.2.0`
- bootstrap version `#4.0.0`

I got an error

./src/App.js
54:10-13 "export 'default' (imported as 'Col') was not found in 'reactstrap'

I wanna make page layout

import React, { Component } from 'react';
import './App.css';
import Header from "./Components/Header";
import ThirdMenu from "./Components/ThirdMenu";
import Sidebar from "./Components/Sidebar";
import Goods from './Components/Goods';
import Col from 'reactstrap';

```class App extends Component {
  render() {
    return (
      <div className="App">
      <Header />
      <ThirdMenu />
      <Col md="3"><Sidebar /></Col>
      <Col md="9"><Goods /></Col>

      </div>
    );
  }
}```

export default App;

**Comment by TheSharpieOne** [comment]
reactstrap exports all of the components, if you need to import a specific component there are a few options:
```
import { Col } from 'reactstrap';
// or
import Col from 'reactstrap/lib/Col';
// or
import reactstrap from 'reactstrap';
const Col = reactstrap.Col;
```

**Comment by fpsstyle228** [comment]
Thank you.All work.
