### ISSUE TITLE
FormFeedback's style is now working when an input validation is false.

### ISSUE THREAD

**Issue by onurdegerli** [reactstrap/reactstrap#843]
### Issue description

- components: `FormFeedback`
- reactstrap version `#4.8.0`
- react version `#16.2.0`
- bootstrap version `#4.0.0`

### What is happening?

I applied the <FormFeedback> component and added onChange method for an input to check the validity of the input.
But I am getting this html output:
`<div class="form-control-feedback">Please use a valid URL.</div>`
The error color is not red, it is black.

### What should be happening?

The error class should be applied the error feedback div. 
Just like this example: https://reactstrap.github.io/components/form/

### Code

```
<Input 
	type="text" 
	name="domain" 
	id="domain"
	placeholder="https://www.test.com, etc." 
	value={this.state.domain} 
	onChange={this.handleDomainChange} 
	getRef={(input) => (this.domainRef = input)}
	required />
{
	this.state.isValidDomain == false &&
	<FormFeedback>Please use a valid URL.</FormFeedback>
}
```

**Comment by TheSharpieOne** [comment]
The versions of reactstrap and bootstrap you are using are not compatible
if you want to use reactstrap `v4.8.0`, you need to use bootstrap `v4.0.0-alpha.6`
If you want to use bootstrap `v4.0.0`, you need to use reactstrap `v5.0.0-beta` (you can install it via `npm install reactstrap@next`

**Comment by onurdegerli** [comment]
I upgraded Reactstrap.
The package.json is like this:

`"bootstrap": "^4.0.0",
    "css-loader": "^0.28.9",
    "html-webpack-plugin": "^2.30.1",
    "path": "^0.12.7",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-transition-group": "^2.2.1",
    "reactstrap": "^5.0.0-beta",
    "style-loader": "^0.20.1",
    "webpack": "^3.11.0",
    "webpack-dev-server": "^2.11.1"`

The React code is like this:
`
<FormGroup>
<Input 
type="text" 
name="project" 
id="project" 
placeholder="Project" 
value={this.state.project} 
onChange={this.handleProjectNameChange} 
innerRef={(input) => (this.projectNameRef = input)} />
<FormFeedback>Please write at least 3 characters.</FormFeedback>
</FormGroup>
`

The feedback field could not be sen both black or red.

**Comment by onurdegerli** [comment]
It is adding `valid-feedback` class. The attributes of class are like this:

```
.invalid-feedback {
    display: none;
    width: 100%;
    margin-top: 0.25rem;
    font-size: 80%;
    color: #dc3545;
}
```

**Comment by TheSharpieOne** [comment]
https://stackblitz.com/edit/reactstrap-v5beta-otzhpy?file=Example.js
![image](https://user-images.githubusercontent.com/664714/36491338-7db190f6-16f8-11e8-997b-bbef1f2a1110.png)

You can also add `valid={false}` to the input to trigger bootstrap styles to display the invalid feedback
https://stackblitz.com/edit/reactstrap-v5beta-zte92o?file=Example.js
![image](https://user-images.githubusercontent.com/664714/36491519-e9a2f232-16f8-11e8-8b98-390ebf372ddc.png)

**Comment by onurdegerli** [comment]
Thanks @TheSharpieOne 
It is working.

**Comment by rahamin1** [comment]
@TheSharpieOne, Your [example](https://stackblitz.com/edit/reactstrap-v5beta-zte92o?file=Example.js) doesn't work for me (the FormFeedback msg is not displayed), not sure why (BTW, I cannot have the code run on stackbliz, not sure why, but I believe you that it works properly :)

Any idea why?

My package.json:
```
{
  "name": "fth-submission-form",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "axios": "^0.18.0",
    "bootstrap": "^4.0.0",
    "firebase": "^4.11.0",
    "lodash": "^4.17.5",
    "react": "^16.2.0",
    "react-addons-css-transition-group": "^15.6.2",
    "react-addons-transition-group": "^15.6.2",
    "react-dom": "^16.0.0",
    "react-redux": "^5.0.7",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.1.1",
    "reactstrap": "^5.0.0-beta",
    "redux": "^3.7.2",
    "redux-persist": "^4.8.3",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.2.0",
    "xml2js": "^0.4.19"
  }

```

**Comment by tsneed290** [comment]
@onurdegerli can you provide how you got it working? 

I'm running into this now and it seems that the input never gets the "is-invalid" CSS class applied to it, therefore the <FormFeedback /> element stays hidden. If I manually add "is-invalid" to the input, I see the error.

I am using bootstrap@4.0.0 and reactstrap@5.0.0-beta.3.

Thanks!

**Comment by TheSharpieOne** [comment]
please use reactstrap v5 and try again

**Comment by tsneed290** [comment]
Thanks @TheSharpieOne. 

I have moved to reactstrap@5.0.0 and am still seeing the same problem. The "is-invalid" CSS class is still not being applied to the input.

**Comment by TheSharpieOne** [comment]
are you adding the `valid={false}` prop? https://stackblitz.com/edit/reactstrap-v5beta-zte92o?file=Example.js

**Comment by tsneed290** [comment]
I have something like this:

```
      <Container>
        <Row>
          <Col sm="12" md={{ size: 6, offset: 3 }}>
            <Form>
              <FormGroup>
                <Input type="number" onChange={this.onChange} onKeyPress={this.onKeyPress} valid={false} />
                <FormFeedback>Test Error</FormFeedback>
              </FormGroup>
            </Form>
          </Col>
        </Row>
      </Container>
```

**Comment by TheSharpieOne** [comment]
https://stackblitz.com/edit/reactstrap-v5beta-aupvat?file=Example.js
Input's output: `<input type="number" class="is-invalid form-control">`

**Comment by tsneed290** [comment]
Yes - I see you're example is working. 

When I step through the code on my side, it's skipping this if() block: https://github.com/reactstrap/reactstrap/blob/5.0.0/src/Input.js#L70 because state is undefined for me.

**Comment by tsneed290** [comment]
Ah - ok. So your example is using 5.0.0-beta. I was using just 5.0.0. When I pull in 5.0.0-beta and re-run, it works. Going back to 5.0.0 seems to break it.

https://github.com/reactstrap/reactstrap/blob/5.0.0/src/Input.js#L70
https://github.com/reactstrap/reactstrap/blob/5.0.0-beta/src/Input.js#L68

Those two are different. 5.0.0 seems to use "invalid" variable, whereas 5.0.0-beta uses "valid".

**Comment by TheSharpieOne** [comment]
may bad, that is what I get for grabbing the example from above. Here is an updated one. I recall now that we changed from `valid={false}` to just `invalid`
https://stackblitz.com/edit/reactstrap-v5-aupvat?file=Example.js

**Comment by tsneed290** [comment]
Ah jeez, I totally missed that in the docs. Thanks for the help!

**Comment by TheSharpieOne** [comment]
Sorry I only added to the confusion :sweat_smile:

**Comment by eeriee** [comment]
How can i make FormFeedback visible if we don't have any Input Field to set to invalid?

**Comment by TheSharpieOne** [comment]
you can add `d-block` to the `className`. it will force it to be displayed.
