### ISSUE TITLE
Dropdown with multiselection

### ISSUE THREAD

**Issue by rlech** [reactstrap/reactstrap#846]
Reactsrap is missing a component like this from Semantic UI

https://semantic-ui.com/modules/dropdown.html (see Multiple Selection)

**Comment by TheSharpieOne** [comment]
You mean bootstrap is missing a component like that from Semantic UI. reactstrap only implements bootstrap in react, replacing the need for bootstrap.js which is jQuery based and doesn't play too nice with react and making it so you don't have `className` all over the place to apply the bootstrap classes. If bootstrap doesn't have it, neither should reactstrap.
I personally use [react-select](https://github.com/JedWatson/react-select) for that type of functionality.
