### ISSUE TITLE
setGlobalCssModule not work

### ISSUE THREAD

**Issue by Miziak** [reactstrap/reactstrap#849]
### Issue description

- components: `setGlobalCssModule`
- reactstrap version: `5.0.0-beta`
- import method `es`
- react version `16.2.0`
- bootstrap version `#4.0.0`

### What is happening?

When I import bootstrap as css module and pass it to `setGlobalCssModule` all bootstrap css is included to the page  but components in my case Button not receive css classes generate by css modules.

### What should be happening?

Components should receive mapped css module classes.

### Code
```
import React, { Component } from 'react';

import { setGlobalCssModule } from 'reactstrap/lib/utils';
import { Button, ButtonDropdown, DropdownToggle, DropdownMenu, DropdownItem } from 'reactstrap';
import bootstrap from 'bootstrap/scss/bootstrap.scss';

class FormTest extends Component<{}, {}> {
  state = {}
  render() {
    setGlobalCssModule(bootstrap);
    return (
      <React.Fragment>
        <h1>test</h1>
        <Button color="primary" onClick={() => alert(':O')}>Test</Button>
        <Button color="danger">Test</Button>
        <Button color="warning">Test</Button>
        <ButtonDropdown isOpen toggle={() => alert('')}>
          <DropdownToggle caret>
            Button Dropdown
          </DropdownToggle>
          <DropdownMenu>
            <DropdownItem header>Header</DropdownItem>
            <DropdownItem disabled>Action</DropdownItem>
            <DropdownItem>Another Action</DropdownItem>
            <DropdownItem divider />
            <DropdownItem>Another Action</DropdownItem>
          </DropdownMenu>
        </ButtonDropdown>
      </React.Fragment>
    );
  }
}

export default FormTest;
```

**Comment by TheSharpieOne** [comment]
log the value of `bootstrap`. It is an object? Are the keys of that object the bootstrap classes (`btn`, `btn-primary`, etc.)? Are the values in the object the generated names which correspond with the output in the generated css file?

**Comment by pilifs** [comment]
I had the same problem with Reactstrap 6.0.1 es and other similar dependencies. It ended up being the util import for `setGlobalCssModule`. It should be done like this:

```
import { Util } from 'reactstrap';
Util.setGlobalCssModule(...)
```

If you import from libs, `globalCssModule` will be undefined when `mapToCssModules` is called. I'm not sure if this changed at some point, or if it works with another import method. Since it's undocumented, I originally just copied and pasted the same syntax that you had from somewhere.

**Comment by GoPro16** [comment]
Closing this issue, feel free to re-open if you are still running into issues.
