### ISSUE TITLE
Modal 'centered' property to add 'modal-dialog-centered' class

### ISSUE THREAD

**Issue by vanyadymousky** [reactstrap/reactstrap#851]
Can you please add a feature of 'centered' prop for a Modal component? 

### Issue description

- components: `Modal`
- reactstrap version `#5.0.0-beta`
- import method `es`
- react version `#16.2.0`
- bootstrap version `#4.0.0`

### What is happening?

https://github.com/twbs/bootstrap/blob/v4-dev/scss/_modal.scss#L53
It's impossible to set property 'centered' on a Modal to apply modal-dialog-centered class under-the-hood

### What should be happening?

There should be possibility to set such prop, e.g. 
`<Modal isOpen={isOpen} fade={false} toggle={this.toggle} centered>`
so modal-dialog-centered class is added under-the-hood

**Comment by dshitik** [comment]
+

**Comment by dshitik** [comment]
++
