### ISSUE TITLE
There's no possibility to add close button above the modal-dialog

### ISSUE THREAD

**Issue by vanyadymousky** [reactstrap/reactstrap#853]
### Issue description

- components: Modal
- reactstrap version #5.0.0-beta
- import method es
- react version #16.2.0
- bootstrap version #4.0.0

### What is happening?

Looks like there's no correct way of adding close button outside the modal-dialog container (so relative position of modal-dialog and modal-content doesn't prevent me from positioning close button where I want).

### What should be happening?

Can there be additional prop or way to pass close button so it traps above modal-dialog, giving possibility of positioning it on entire viewport? 

Not providing PR for now since don't know quick and correct way of resolving this. 

My current workaround (I really doubt such way can be considered as a fix, since it's **breaking react composition principles**, etc. ): 

```jsx
export class ModalExtended extends Modal {
  renderModalDialog() {
    return (
      <Fragment>
        {this.props.closebutton}
        {super.renderModalDialog()}
      </Fragment>
    );
  }
```

**Comment by TheSharpieOne** [comment]
How would someone go about doing this in bootstrap? I only ask as it may help to determine a solution for reactstrap as well as make the reactstrap way more intuitive since it would be similar to bootstrap.

**Comment by vanyadymousky** [comment]
@TheSharpieOne for example, describing modal layout, insert button in a right place: 

```html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <button class="cool-close-button">Goes here</button>
  <div class="modal-dialog" role="document">
...
```

**Comment by TheSharpieOne** [comment]
Since you would be most likely using absolute position to position the button, we probably don't need another prop to insert something after the modal-dialog as well. (just making sure we don't need something to target after the modal-dialog as well as before.)

**Comment by vanyadymousky** [comment]
@TheSharpieOne Correct, we don't. The only thing we need is to put some node on the same level as model-dialog in DOM tree, so relativeness doesn't prevent us from using entire viewport. Thank you!

**Comment by TheSharpieOne** [comment]
RFC on both the different way to do it as well as potential prop names
accept a node:
```jsx
<Modal isOpen={...} toggle={this.toggle} external={<Button className="cool-close-button" onClick={this.toggle}></Button>}>
 ...
</Modal>
```
more powerful, more control.

toggle just a button
```jsx
<Modal isOpen={...} toggle={this.toggle} externalButton externalButtonClassName="cool-close-button">
 ...
</Modal>
```
simple, but less control over what gets rendered, but the user would no need to apply onClick and there would also probably be a base-classname which could be used.

**Comment by vanyadymousky** [comment]
@TheSharpieOne I would go with first one, even though my concrete case needs standard &times; that can easily be applied. I believe people will want to replace &times; and then we need another prop for that.
