### ISSUE TITLE
Failed prop type: Invalid prop `to` supplied to `Link` with custom `tag={MyComponent}`

### ISSUE THREAD

**Issue by charlex** [reactstrap/reactstrap#855]
### Issue description

- components: `<PaginationLink>`
- reactstrap version `#next`
- import method `unsure`
- react version `#16.2.0`
- bootstrap version `#4.0.0`

### What is happening?

Using `<PaginationLink>` with a custom `tag={CustomLink}` prop and a prop, like `to='xyz'`, which is not expected by `PaginationLink` but is expected by `CustomLink` results in a warning.

```
import { Link as RRLink } from 'react-router-dom';
import { Pagination, PaginationItem, PaginationLink } from 'reactstrap';

class MyComp extends Component {
  render() {
    return (
      <Pagination>
        <PaginationItem disabled={!prevLink}>
          <PaginationLink previous tag={RRLink} to='/my/link/' />
        </PaginationItem>
      </Pagination>
    )
  }
}
```

```
warning.js:33 Warning: Failed prop type: Invalid prop `to` supplied to `Link`.
    in Link (created by PaginationLink)
    in PaginationLink (created by MyComp)
    in li (created by PaginationItem)
    in PaginationItem (created by MyComp)
    in ul (created by Pagination)
    in Pagination (created by MyComp)
    ...
```

### What should be happening?

Ideally, `<PaginationLink>` or other reactstrap link props, should be capable of handling custom props without throwing warnings if those props are supported by the component passed into `tag={}`.

**Comment by charlex** [comment]
Ah, thanks @supergibbs

**Comment by TheSharpieOne** [comment]
Cannot reproduce: https://stackblitz.com/edit/reactstrap-v5beta-w7vnwb?file=Example.js

**Comment by charlex** [comment]
Hmm, yeah I see that too @TheSharpieOne. I'm trying to figure out how to isolate what I am seeing on my end.
