### ISSUE TITLE
"Added non-passive event listener to a scroll-blocking 'mousewheel' event." on select inputs

### ISSUE THREAD

**Issue by asliwinski** [reactstrap/reactstrap#864]
### Issue description

Go to the [form section](http://reactstrap.github.io/components/form/), open console (make sure Verbose level is selected) and click on any select input.

### Error message in console

```
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

It does not affect functionality but can affect performance, according to [this](https://github.com/angular/material2/issues/4221).

**Comment by TheSharpieOne** [comment]
I don't think this is coming from reactstrap as reactstrap does set any mousewheel events as far as I can tell. It may be coming from a chrome extension.
I'm on mobile now so I cannot confirm, but the log message should have a file and line number indicating where the offending event listener is coming from.

**Comment by supergibbs** [comment]
Agreed. I can't reproduce on MacOS Chrome browser. Try safe mode or disable all extensions and see if it's still an issue.

**Comment by asliwinski** [comment]
I disabled all the extensions for the incognito mode and verified again, the error is there:

![nonpassive](https://user-images.githubusercontent.com/14044823/36688024-8398d4e8-1b2b-11e8-928f-bdfa44bccd57.png)

64bit Chrome v. 64.0.3282.186
Windows 10

**Comment by TheSharpieOne** [comment]
Do get the error when opening the select in https://jsfiddle.net/zauc6ebc/ ?

**Comment by asliwinski** [comment]
Yes, and after I did some googling it seems it's a local issue, however I can't pinpoint the cause. Anyway, I'm closing the bug.
