### ISSUE TITLE
Draggable modal

### ISSUE THREAD

**Issue by jitendrasaroj93** [reactstrap/reactstrap#866]
I'm looking for draggable capability in reactstrap but i don't find any. Is that feature in Reactstrap. 
for example i want to create draggable dialog modal.

**Comment by TheSharpieOne** [comment]
This library aims to be a react replacement for bootstrap.js (since bootstrap.js is jquery based and doesn't play too nice with react). If it's not in bootstrap, it's not in reactstrap.
