### ISSUE TITLE
cannot custom button on modals

### ISSUE THREAD

**Issue by zanisis** [reactstrap/reactstrap#869]
can u make give props render custom buttton close ?. 💃

**Comment by supergibbs** [comment]
I agree, more control over the `ModalHeader` would be nice.

**Comment by BrianTatum** [comment]
More control would be nice but I think I have a work around. I replaced the ModalHeader component with some jsx modeled after the regular Bootstrap 4 modal header. So far everything appears to work as expected. See example below.

<Modal isOpen={showModel} toggle={closeModel} className='modal-dialog-centered' >
     <div className="modal-header">
	<h5 className="modal-title">Modal title</h5>
		<button type="button" className="close myClose" onClick={closeModel} aria-label="Close">
			<i className="fa fa-times-circle"></i>
		</button>
	</div>			
	<ModalBody>
                 {. . . . .}
        </ModalBody>
</Modal>

**Comment by gergely-nagy** [comment]
Merged via (#1168) (5f33a1a) . Released in [6.5.0](https://github.com/reactstrap/reactstrap/compare/6.4.0...6.5.0)
