### ISSUE TITLE
dynamic multiple dropdownmenus with hover

### ISSUE THREAD

**Issue by EVALIJANI** [reactstrap/reactstrap#880]
hi how can you help me on multiple dropdowns not just one, your example is just one toggle, 

for example for second toggle is should add toggle1(){}  toggle2(){} and  .... 

i want it with mouse hover

**Comment by TheSharpieOne** [comment]
Per bootstrap's docs: 
> They’re toggled by clicking, not by hovering; this is [an intentional design decision](http://markdotto.com/2012/02/27/bootstrap-explained-dropdowns/).

Reference: http://getbootstrap.com/docs/4.0/components/dropdowns/

As for toggling multiple with the same event, you can have all of the dropdown's `isOpen` prop be the same so when one is shown, they all are shown. Or you can have the `toggle` callback toggle multiple values, one for each dropdown `isOpen`.
See https://stackblitz.com/edit/reactstrap-v5beta-ddvqhe?file=Example.js
