### ISSUE TITLE
Using collapse component, onEntered callback not being called after opening collapse

### ISSUE THREAD

**Issue by avee7** [reactstrap/reactstrap#881]
### Issue description

- components: Collapse
- reactstrap version `^4.8.0`
- react version `^15.6.1`
- bootstrap version `4.0.0`

### What is happening?

My aim is to add `up arrow` and `down arrow` in the Collapse component when it is opened and closed respectively.

I'm trying to use callbacks `onEntered` and `onExited` in order to add class on an element. But I guess the basic call to `onEntered` function is not happening.

Here's the code snippet:

### Code

```
import React from 'react';
import { Button, Card, CardBlock, CardHeader, CardText, Col, Collapse, TabPane, Row  } from 'reactstrap';
class Expandables extends React.Component {
  constructor (props) {
    super(props);
    this.onEntered = this.onEntered.bind(this);
    this.onExited = this.onExited.bind(this);
    this.toggle = this.toggle.bind(this);
    this.state = { collapse: false, status: 'closed' };
  }

  onEntered() {
    this.setState({ status: 'opened' });
  }

  onExited() {
    this.setState({ status: 'closed' });
  }

  toggle() {
    this.setState({ collapse: !this.state.collapse });
  }

  render () {
    return (
      <TabPane tabId={this.props.id}>
        <Row className='mt-5'>
          <Col>
            <ul className='boxed-list'>
              <li>
                <Card>
                  <CardHeader>
                    <h5 className='title' onClick={this.toggle}>
                      Expandable
                    </h5>
                    <span>{this.state.status}</span>
                  </CardHeader>
                  <Collapse isOpen={this.state.collapse} onExited={this.onExited} onEntered={this.onEntered}>
                    <CardBlock>
                      <CardText>Lorem ipsum</CardText>
                    </CardBlock>
                  </Collapse>
                </Card>
              </li>
            </ul>
          </Col>
        </Row>
      </TabPane>
    )
  }
```

### Output:

Closed State:
![screen shot 2018-03-05 at 10 58 19](https://user-images.githubusercontent.com/23307038/36972003-79d63c86-2065-11e8-8aa4-d2f557c2c67b.png)

Open state:
![screen shot 2018-03-05 at 11 04 37](https://user-images.githubusercontent.com/23307038/36971981-6923a950-2065-11e8-9b6c-bb37bcc9d608.png)

I'm pretty new to the react world. Please let me know if I'm missing something.

Thanks a lot.

**Comment by arghgr** [comment]
This doesn't quite address your specific issue, but you might not need to use onEntered/onExited at all for the class changes. You can make the class conditional on this.state.collapse.

Example (assuming "show"/"hide" are the classes you need to toggle between):
```
<div className={this.state.collapse ? "show" : "hide"}>
This should be hidden when Collapse is closed
</div>
```

**Comment by TheSharpieOne** [comment]
The callbacks are working correctly in the latest version. You should upgrade to reactstrap 5, especially since you indicated you are using bootstrap 4.0.0 and reactstap 4.8.0 only supports up to bootstrap 4.0.0-alpha.6.
Here is your example using reactstrap 5 https://stackblitz.com/edit/reactstrap-v5-ifkvvh?file=Example.js

**Comment by GoPro16** [comment]
Closing this issue, feel free to re-open if you are still running into issues.
