### ISSUE TITLE
Custom class names appear in HTML in the wrong order

### ISSUE THREAD

**Issue by drannos** [reactstrap/reactstrap#882]
### Issue description

- components: Navbar (maybe all components, still testing)
- reactstrap version `5.0.0-beta`
- react version `16.2.0`
- bootstrap version `4.0.0`

### What is happening?

custom className values are added to the beginning of the class attribute in the generated HTML. They need to be added to the end. For example, this React component: 

`<NavbarToggler onClick={this.toggle} className="test-class" />`

Where `test-class` is the custom class to be added. This results in the following HTML: 

`<button type="button" class="test-class navbar-toggler">
<span class="navbar-toggler-icon"></span>
</button>`

Where `navbar-toggler` is the native Bootstrap class.

### What should be happening?

It seems best (necessary) to have custom classes appended to the list of classes for the element. They really need to be at the end to prevent undesired CSS behaviors. **I found that adding the native Bootstrap classes** in the `className` attribute doesn't fix the issue; it just results in the native Bootstrap classes appearing twice. 

Thanks!

**Comment by TheSharpieOne** [comment]
The order of the class names does not matter; specificity matters.
See https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Comment by drannos** [comment]
Specificity matters, but so does Source Order.
https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Cascade_and_inheritance

**Comment by TheSharpieOne** [comment]
Source Order is the order in which you import/include your styles. If you include bootstrap's styles after your own styles, then in the case of the same importance and specificity, bootstrap's styles will win. If you import/include your styles after bootstrap in the same scenario, then your styles will win. The order of the class names on the actual element do not matter.

**Comment by drannos** [comment]
Ah! That was a misunderstanding on my part.

Thanks for the clarification! (And for correcting a years-long misconception! :-D )
