### ISSUE TITLE
Importing Reactstrap to window.reactstrap

### ISSUE THREAD

**Issue by DrEVILish** [reactstrap/reactstrap#883]
### Issue description

- components: `name`
- reactstrap version `#5.0.0-beta.2`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `#16.2.0`
- bootstrap version `#4.0.0`

### What is happening?

      if(err) throw err;
              ^
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### What should be happening?

Not be erroring

### Steps to reproduce issue

1. window.reactstrap = require('reactstrap')
adding this line of code which gets babilify'ed
2. this goes away as soon as I comment out this line. This method worked previously for "react-bootstrap" using the same method

### Error message in console

  if(err) throw err;
              ^
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by TheSharpieOne** [comment]
Seems like your setup is set to use es modules, but doesn't like es modules. You can explicitly import the common js version via `window.reactstrap = require('reactstrap/dist/reactstrap.cjs.js')` (give it a try)
Or you can just use the script tag to set it on the window.
```
<script src="https://unpkg.com/reactstrap@5.0.0-beta.2/dist/reactstrap.full.min.js"></script>
```

**Comment by DrEVILish** [comment]
Thanks for the heads up I tried `window.reactstrap = require('reactstrap/dist/reactstrap.cjs.js')` but got the same issue, instead I tried `window.reactstrap = require('reactstrap/dist/reactstrap.full.js')` and babelify/browserify built it perfectly.
