### ISSUE TITLE
**"export 'default' (imported as 'TestStore') was not found in 'TestStore'**

### ISSUE THREAD

**Issue by yjadhav** [reactstrap/reactstrap#885]
I have following scenario 

I have one store for example **TestStore.js**

TestStore.js:

function TestStore() {
   async function NestedAsyncFunction(){
    /* Logic*/
   }
}

module.export=TestStore()

Now i am using this store in my component like this

TestComponents.jsx:
     import TestStore from 'TestStore';

I am getting following error
TestComponents.jsx
44:26-37 **"export 'default' (imported as 'TestStore') was not found in 'TestStore'**

**Comment by TheSharpieOne** [comment]
You are not importing, using, nor referencing reactstrap
