### ISSUE TITLE
Style of select input is weird

### ISSUE THREAD

**Issue by KamiGim** [reactstrap/reactstrap#889]
### Issue description

- components: Input
- reactstrap version: 5.0.0-beta
- import method : not sure
- react version 16.2
- bootstrap version 4.0.0

### What is happening?

The style of select input is weird as you can see in your example website also

![image](https://user-images.githubusercontent.com/17401507/37072394-c12cb09e-21f3-11e8-9f9e-d5ee2305859b.png)

**Comment by TheSharpieOne** [comment]
Reactstrap is just applying bootstrap classNames here. All of the styles are coming from bootstrap. I would suggest opening and issue with bootstrap.

**Comment by KamiGim** [comment]
![image](https://user-images.githubusercontent.com/17401507/37082945-7e7bd16c-2220-11e8-9016-14aa1eb9a85e.png)
I don't think that the case because in the bootstrap website and w3school they don't have this weird style

**Comment by KamiGim** [comment]
I try delete one option in developer tool then the border is coming

**Comment by TheSharpieOne** [comment]
We add a class to a select and the browser does the actual rendering / painting to the screen. If it displays the same element with the same styles differently, that may be a browser issue.

**Comment by TheSharpieOne** [comment]
I cannot reproduce this on Chrome 65 Mac. It's browser specific and again, we only add class names to the standard `<select>`, bootstrap styles it.

**Comment by KamiGim** [comment]
I see I use Chrome on Windows. Anyway thanks
