### ISSUE TITLE
Input class for large input is incorrect

### ISSUE THREAD

**Issue by crissdev** [reactstrap/reactstrap#890]
### Issue description

- components: `Input`
- reactstrap version `#5.0.0-beta`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `#16.2.0`
- bootstrap version `#4.0.0`

### What is happening?

Input component adds `form-control-large` class.

### What should be happening?

The generated class should be `form-control-lg`

### Steps to reproduce issue

Create an Input component.

### Error message in console

```
No error message
```

### Code

https://codepen.io/crissdev/pen/WMVPXe?editors=1010

**Comment by TheSharpieOne** [comment]
The value of bsSize should match the bootstrap sizes. For this, it's defined and documented on bootstrap's site as "sm" and "lg".
This is the same convention for grid sizes and such (xs, sm, md, lg, xl). 
Bootstrap is not a rigid system, so neither is reactstrap, we don't enforce the values to lock them down to out of the box bootstrap values as users may want to use custom values; extending bootstrap.
Bootstrap "allows"  "form-control-large" just as much as reactstrap allows "large". Both will produce the same styles via the classes which get applied (whether or not any styles get applied depend on the actual css).

**Comment by crissdev** [comment]
Thanks for clarification @TheSharpieOne
