### ISSUE TITLE
Dynamically remove/edit/add table's rows [Not a bug]

### ISSUE THREAD

**Issue by dkati** [reactstrap/reactstrap#893]
Good evening. Newbie at reactstrap i am trying to create a table with editable/removable rows.
i have created the table ,added the rows but i dont know how to make actions with them.
my code so far:
```
 <Row> 
                    <Col>
                        <Button className="float-right" outline color="secondary">Add</Button>
                    </Col>
 </Row>
<Row>
<Table striped bordered hover size="sm">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Manufacturer</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">1</th>
                                 <td>man1</td>
                                <th>
                                    <Button outline color="info">Edit</Button>
                                    <Button outline color="danger">Remove</Button>
                                </th>
                            </tr>
                            <tr>
                                <th scope="row">2</th>
                                <td>man2</td>
                                <th>
                                    <Button outline color="info">Edit</Button>
                                    <Button outline color="danger" >Remove</Button>
                                </th>
                            </tr>
                        </tbody>
                    </Table>
</Row>
```
My questions are:
-can i somehow build all the rows dynamically ? (a for loop parsing a table?)
-can i somehow edit the current row by pressing the button 'Edit' ?
-can i somehow delete the current row by pressing the button 'Remove'?
-can i somehow add  a new row to the table by pressing the button 'Add' ?

Thanks in advance!

**Comment by twgraham** [comment]
@dkati github is not really the place to ask these types of questions. You'll find a much better place is stackoverflow. Github issues are - as the name suggests - directed at issues with the repo/bugs/feature requests etc.

That said, all these things you've asked are definitely possible, though I would say they are more general react questions than reactstrap.

**Comment by TheSharpieOne** [comment]
I'm closing this as, like @twgraham said, it's more of a general react question than anything related to reactstrap.
I can give you a push in the right direction with this example: https://stackblitz.com/edit/reactstrap-v5-tyjxxh?file=Example.js
