### ISSUE TITLE
npm modules in package?

### ISSUE THREAD

**Issue by Sathras** [reactstrap/reactstrap#896]
For some reason installing reactstrap with `npm i reactstrap@next` creates a npm_modules directory within the /npm_modules/reactstrap/ folder. This contains the react-popper optional dependency.

Normally I wouldn't bother much, but it disrupts the normal npm directory flow and returns errors when using UncontrolledTooltip (and maybe others):
```
error: Processing of node_modules/reactstrap/node_modules/react-popper/lib/react-popper.js failed. SyntaxError: 'import' and 'export' may only appear at the top level (5:4)
```
Installing `npm i react-transition-group` and `npm i react-popper` directly and deleting the `node_modules/reactstrap/node_modules/` folder solves the issue (until upgrade to next version).

I believe that npm modules should never be loaded within npm modules.

**Comment by NathanCH** [comment]
Can confirm and your solution fixed the problem, but I ended up downgrading to alpha 4 again in the meantime.

**Comment by TheSharpieOne** [comment]
> I believe that npm modules should never be loaded within npm modules.

You'll have to take that up with npm as that is just how npm handles different modules depending on different versions of the same module (with no overlap). Each module gets the version it wants/needs.
PeerDeps allows the module to let the user determine which version to use by forcing them to install it in their project's deps, but some people at npm think peerDeps was a mistake.

Basically what is happening here is #870. The latest version of react-popper (0.8.2) does not expose it's named exports correctly which cases reactstrap's release build to fail, but react-popper's previous version (0.8.1) does work in the build, but it does not work well for project's which depend on it (as you are seeing).
