### ISSUE TITLE
Modal 'centered' prop defined in docs but does not have implementation

### ISSUE THREAD

**Issue by shaieis** [reactstrap/reactstrap#898]
[Modal documentaion:](https://reactstrap.github.io/components/modals/) states: 

> Modal.propTypes = {
   ...
  **centered: PropTypes.bool,**
  ...

But implementation is missing.  
Trying to use 'centered' prop:

`<Modal isOpen={true} toggle={this.toggle} **centered**>`

and this warning appears: 

> Warning: Received `true` for a non-boolean attribute `centered`.

**Comment by TheSharpieOne** [comment]
Follow installation instructions found in the docs to install the correct version of reactstrap which the docs document.

**Comment by zaffkea** [comment]
@shaieis - I ran into the same thing today because I had not updated in a while. I was still using reactstrap version 5.0.0-beta. To fix it, I updated to version 5.0.0-beta.2. I hope that works for you too.
