### ISSUE TITLE
Form error feedback is not displayed for input of `type='file'`

### ISSUE THREAD

**Issue by rahamin1** [reactstrap/reactstrap#901]
### Versions:
- bootstrap: 4.0.0
- reactstrap: 5.0.0-beta

### The problem
Form error feedback is shown for input of `type=text` but not for input of `type=file`

**Comment by TheSharpieOne** [comment]
Upstream issue with bootstrap: https://github.com/twbs/bootstrap/issues/25399

**Comment by rahamin1** [comment]
Thank you!
