### ISSUE TITLE
Add Bootstrap sass files for customization?

### ISSUE THREAD

**Issue by ChristoRibeiro** [reactstrap/reactstrap#902]
I'm wondering if it's a good idea to add bootstrap sass files to Reactstrap for customization. 

**Why** 
Because when I want a full control of styles customization with Reactstrap I still use Bootstrap only for sass files.

**The problem** 
Reactstrap doesn't have extra dependencies 👍but Bootstrap does. Yarn tells me everytime that Bootstrap is missing dependencies to jQuery and popper.js (I just need sass files...). It's really annoying to get these warning 👎 

**Solution**
Getting all sass files from Reactstrap? What do you think guys? cc @eddywashere & @TheSharpieOne.

**Comment by TheSharpieOne** [comment]
The warning you get from yarn is just that, a warning. It's not going to cause any issues and it's not going to break and builds.
Reactstrap doesn't want to have any scss (outside of what is there for the docs, which is not used in typical third-party usage.)  
If we were to include the scss files, we would be more tied to a specific version of bootstrap and every time they released a new version, we would have to as well to update the files, even fluffy nothing in reactstrap itself didn't need to change.
I think the package @crissdev published is a better solution, but now every time bootstrap releases something he will need to also update and release a new version of his package in a timely manner.
I personally just use bootstrap and ignore the warning.

**Comment by supergibbs** [comment]
Agreed plus `bootstrap` has plans to do this as well: https://github.com/twbs/bootstrap/issues/23557

Planned for v4.3 https://github.com/twbs/bootstrap/projects/9

**Comment by ChristoRibeiro** [comment]
Thanks for your comments. 

I will use the @crissdev's package until an official package comes from Bootstrap.
