### ISSUE TITLE
Please update react-popper to version 0.8.2 in latest beta

### ISSUE THREAD

**Issue by adambisek** [reactstrap/reactstrap#904]
Latest version of reactstrap (5.0.0-beta.2) links dependency react-popper@0.8.1
But this version is broken (uncompiled), see below:

```
.../node_modules/reactstrap/node_modules/react-popper/lib/react-popper.js:1
(function (exports, require, module, __filename, __dirname) { export { default as Manager } from './Manager';
```

Manual update dependency react-popper to version 0.8.2 solves this.

Please update react-popper and publish 🥇

**Comment by TheSharpieOne** [comment]
react-popper 0.8.2 doesn't work with rollup out-of-the-box. #887 should fix it, but there are some other issues identified with SSR that need to be addressed.

**Comment by adambisek** [comment]
@TheSharpieOne Thanks for your answer! But, how can I make current beta (5.0.0-beta.2) working? For you is this version working without the error I've described above?

**Comment by TheSharpieOne** [comment]
some people are reporting that you can manually install react-popper 0.8.2 (and remove the version which npm will place under reactstrap's directory)

**Comment by Sathras** [comment]
manual only works without further ado in development. When it comes to deployment you unfortunately do not have that manual control...

**Comment by adambisek** [comment]
For me worked to modify yarn.lock and there switch 0.8.1 to 0.8.2.
Awkward, but relatively clean solution. Hope it is temporary solution for few days.

**Comment by TheSharpieOne** [comment]
https://github.com/souporserious/react-popper/pull/93 was just merged, so hopefully a new release will be published soon. I'll create a new reactstrap release with the min version being the next version of react-popper after that.

**Comment by Kernle32DLL** [comment]
@TheSharpieOne react-popper 0.8.3 was just released 🎉
