### ISSUE TITLE
Wrap text in button

### ISSUE THREAD

**Issue by KunalSinha7** [reactstrap/reactstrap#906]
Is there a way to wrap text inside a button for when there is a large amount of text?

**Comment by TheSharpieOne** [comment]
Not via anything specific to reactstrap, that is just CSS/styles. Bootstrap's `.btn` class has `  white-space: nowrap;` which is what is preventing it from wrapping. You'll have to override it via `style={{  whiteSpace: 'normal'}}`
More info on that CSS property: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by TheSharpieOne** [comment]
I'm closing this since the the issue appears to be answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered
