### ISSUE TITLE
Modal is not rendering in my DOM

### ISSUE THREAD

**Issue by DaanTul** [reactstrap/reactstrap#908]
components: Modal
    reactstrap version #4.8.0
    react version #16.2.0
    bootstrap version #4.0.0

### What is happening?

Modal is not rendering in my HTML -> inspecting it shows nothing. creates error on toggling.

### What should be happening?

Modal should be at least rendering in the DOM.

Error message in console on toggling: TypeError: this._dialog is undefined

```javascript
import React, { Component } from 'react';
import { Button, Modal, ModalHeader, ModalBody, ModalFooter } from 'reactstrap';

class Catalog extends Component {

constructor(props) {
  super(props);

  this.state = {
    itemsData: [],
    modal : false
  };
  this.toggle = this.toggle.bind(this);
}

toggle(){
  this.setState({modal : !this.state.modal});
}

render() {
  return (
    <div>
      <Button onClick={this.toggle}>Klik!</Button>
      <Modal isOpen={this.state.modal} toggle={this.toggle} className={"modalThing"}>
      <ModalHeader toggle={this.toggle}>Modal title</ModalHeader>
      <ModalBody>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </ModalBody>
      <ModalFooter>
        <Button color="primary" onClick={this.toggle}>Do Something</Button>{' '}
        <Button color="secondary" onClick={this.toggle}>Cancel</Button>
      </ModalFooter>
    </Modal>
    </div>
  )
}

}

export default Catalog
```

**Comment by TheSharpieOne** [comment]
reactstrap v4.8.0 is not compatible with bootstrap 4.0.0; it's only compatible with bootstrap 4.0.0-alpha.6.
To get bootstrap 4.0.0 (official), you'll have to use reactstrap@5.0.0-beta.1 or higher (currently there is an issue in reactstrap@5.0.0-beta.2, so I would suggest reactstrap@5.0.0-beta.1 for now).

**Comment by Alex-Joseph** [comment]
I was having the same issue (bootstrap 4.0, reactstrap 5 beta.3). I switched to beta 1 but I still had the bug. Once I removed the className it worked fine. Hope this helps!

`<Modal isOpen={this.state.modal} toggle={this.toggle} **className={"modalThing"}**>`

**Comment by TheSharpieOne** [comment]
reactstrap 5.0.0 (official) is out, you might want to try that as well.
