### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.     at Modal.destroy

### ISSUE THREAD

**Issue by devmarwen** [reactstrap/reactstrap#918]
### Issue description

- components: `Modal`
- reactstrap version `#5.0.0-beta.3`
- import method `es` (if umd, are you using the "full" version (only for v5+)?)
- react version `#16.2.0`
- bootstrap version `#4.0.0`

### What is happening?

Error when unmounting `Modal` route.

#### 1. Create the route
```jsx
        <Switch>
          <Route
            exact
            path={`${this.props.match.path}/nw`}
            render={(props) => (
              <ComponentAsAModal
                one="two"
                {...props}
              />
            )}
          />
        </Switch>
```
#### 2. The Component
```jsx
// The component
class ComponentAsAModal extends React.Component {
  constructor() {
    super();
    this.state = {
      visible: true,
    };
  }

  goBack = () => {
    // Transition to another route. Apparently this is the cause
    // of the error. If wrapped in `setTimeout` the error vanishes.
    this.props.dispatch(push('/some-other-route'));
  };

  close = (e) => {
    this.setState({ visible: false });
  };

  render() {
    return (
      <Modal
        toggle={this.close}
        isOpen={this.state.visible}
        onClosed={this.goBack}
      >
      Modal Content
      </Modal>
    );
  }
}
```
### Error message in console

```
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'. at Modal.destroy
```
```jsx
function destroy() {
   // this line fails because of `this._element`. Idealy we should test if 
   // `this._element` exists before executing `document.body.removeChild`
   document.body.removeChild(this._element);
   this._element = null;
   // rest of the code
}
```

**Comment by virgofx** [comment]
Good catch, I'll fix this in PR #916

**Comment by fantua** [comment]
@virgofx I'm not sure is that fix correct, maybe removing class from body need to be wrapped in that `if` too.

@devmarwen can you reproduce your error in [codesandbox](https://codesandbox.io/)?

**Comment by fantua** [comment]
@TheSharpieOne hmm, ok. Just created a new bug: https://codesandbox.io/s/9890x3mjmo

Take a look at console output, body class is removing 2 times after Modal closing 😞

**Comment by TheSharpieOne** [comment]
Try 5.0.0. I [re-]added some extra logic to ensure a modal only adds and removes the classname it adds once (well, ensure it doesn't add multiple and remove multiple)

**Comment by efstathiosntonas** [comment]
Using material-ui select dropdown on top of Modal, when item is selected it immediately throws:

![screen shot 2018-05-16 at 10 56 02](https://user-images.githubusercontent.com/717975/40104029-e13fc37c-58f7-11e8-961d-8caa528731c8.png)

**Comment by Imprasna** [comment]
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.


I am getting this error so, can anyone help me sort it out?
