### ISSUE TITLE
Centering brand in collapsed navbar not working as expected

### ISSUE THREAD

**Issue by daveonestar** [reactstrap/reactstrap#919]
In bootstrap, mx-auto is used in order to center the brand in the navbar.
However in collapsed mode, the toggler gets in the way, and it seems that the brand centers in the remaining space to the left of the toggler.

In the end, the brand is slightly to the left

| ------Brand------ Toggler |
Instead of:
| ----------Brand-- Toggler |

**Comment by supergibbs** [comment]
Please create an example on https://stackblitz.com/edit/reactstrap-v5-beta-starter

**Comment by kaicianflone** [comment]
@daveonestar Please take a look at this code https://stackblitz.com/edit/reactstrap-v5-beta-starter-16sgag. I was able to get mx-auto to work perfectly using it as a className value on the NavbarBrand. 

If it is no longer an issue please let @supergibbs close it. :)

**Comment by supergibbs** [comment]
Looks good to me, I also tried it with the latest versions of reactstrap and bootstrap. Closing unless someone comments.
