### ISSUE TITLE
QUESTION: How to use transition with Collapse component

### ISSUE THREAD

**Issue by emlmsc** [reactstrap/reactstrap#921]
### Issue description

- components: `Collapse`
- reactstrap version `5.0.0-beta.2`
- react version `16.2.0`
- bootstrap version `4.0.0`

Hi!

How to use transition with `Collapse` component? There is a `Transition.propTypes` in properties model, but its not obvious what to do exactly. Thanks for replying!

**Comment by TheSharpieOne** [comment]
We wrap `react-transition-group/transition` but pass those props through to it. It would be best detailed with their documentation: http://reactcommunity.org/react-transition-group/transition

We probably should add that link and a little blurb to the docs.

**Comment by jlsorak** [comment]
Would find this useful too 👍

**Comment by median-man** [comment]
I'm opening a PR with the following changes to the Collaps page of the docs:
![image](https://user-images.githubusercontent.com/8689789/45254250-14935b80-b32a-11e8-8812-61412b893d63.png)
