### ISSUE TITLE
No container class?

### ISSUE THREAD

**Issue by daveonestar** [reactstrap/reactstrap#923]
Using Jumbotron in BS requires a container div wrapping it.
Is there a <Container> class in Reactstrap? If so there is no documentation.

In not, should I use <div className="container> or is the <Container> class already has implementation of container?

Thanks

**Comment by gergely-nagy** [comment]
Hi @daveonestar !
The `Container` component is already exist.
https://github.com/reactstrap/reactstrap/blob/113e6d352ed04712cd67aada3b2b53603c684647/src/Container.js#L1-L39

**Comment by TheSharpieOne** [comment]
Yeah, it's in the docs in layout, but the docs' organization is kinda funny. It has "Components" but some (such as layout and form) are grouping of Components. There isn't a list of all available components, there is no search feature, and to top that, there are no "jump links" to the individual sections with a page.

**Comment by TheSharpieOne** [comment]
I'm closing this since the the issue appears to be answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered
