### ISSUE TITLE
"inline" prop missing in Typescript def

### ISSUE THREAD

**Issue by mrmanicou** [reactstrap/reactstrap#924]
### Issue description

- components: `FormGroup`
- reactstrap version `reactstrap: ^5.0.0-beta.3,`  `@types/reactstrap: ^5.0.20`
- import method `typescript imports` (if umd, are you using the "full" version (only for v5+)?)
- react version `16.2.0`
- bootstrap version `4`

### What is happening?

TS error `[ts] Property 'inline' does not exist on type`

### What should be happening?

`inline` should be included in typedef for FormGroup component
e.g. 
```
interface FormGroupProps extends React.HTMLProps<HTMLDivElement> {
  row?: boolean;
  check?: boolean;
  inline?:boolean;
  disabled?: boolean;
  tag?: React.ReactType;
  color?: string;
  className?: string;
  cssModule?: CSSModule;

}
```

**Comment by TheSharpieOne** [comment]
The typing are coming from https://github.com/DefinitelyTyped/DefinitelyTyped, please open an issue there.
