### ISSUE TITLE
Component css styling ?

### ISSUE THREAD

**Issue by dkati** [reactstrap/reactstrap#925]
Good evening.i am very comfused on how can i theme the components...
trying simple stuff like

-make tab's text unselectable
-do not change cursor on hover of tab text
-change one text field's text by pressing  a button
and such

are very difficult
in plain CSS its quite simple.do i miss something ? 
I am new at reactstrap

Generally,i would like to study reactstrap but there is no such documentation..just some examples of the components.i love your work and i would like to use reactstrap as my first development kit for webpages.

Thanks in advance!

**Comment by gergely-nagy** [comment]
This library is only the components which produce the markup which matches bootstrap's markup/classes. It will produce all of the HTML with the proper classNames to be styled by bootstrap using bootstrap's CSS. 

There is four ways to style react components:

1. **CSS Stylesheet**
Simply import css file `import './example.css'` so you can have a separate css file for each component.
2. **Inline styling**
In React, inline styles are not specified as a string. Instead they are specified with an object whose key is the camelCased version of the style name, and whose value is the style’s value, usually a string.
```javascript
import React from 'react';

const divStyle = {
  margin: '40px',
  border: '5px solid pink'
};
const pStyle = {
  fontSize: '15px',
  textAlign: 'center'
};

const Box = () => (
  <div style={divStyle}>
    <p style={pStyle}>Get started with inline style</p>
  </div>
);

export default Box;
```

3. **CSS Modules**
4. **Styled-components**
[Styled-components](https://github.com/styled-components/styled-components) is a library for React and React Native that allows you to use component-level styles in your application that are written with a mixture of JavaScript and CSS

**Comment by TheSharpieOne** [comment]
I'm closing this as it appears to be answered and is no longer active. I wanted to also add extending bootstrap and change it's variables (colors, sizing, spacing, and such). This is what I typically do as it makes it very easy to theme everything without overriding individual styles for each bootstrap component.
Information on how to do that can be found with bootstrap's official docs: 
http://getbootstrap.com/docs/4.1/getting-started/theming/
http://getbootstrap.com/docs/4.1/extend/approach/
