### ISSUE TITLE
Using reactstrap in rails

### ISSUE THREAD

**Issue by mukarramali** [reactstrap/reactstrap#928]
### What is happening?
I have installed reactstrap npm package. I added the `node_modules` folder to assets pipeline.

Included in application.js:

    //= reactstrap

Now in one of my react component, if

    import { Col, Button, Form, FormGroup, Label, Input, FormText } from 'reactstrap';

### Error message in console

```    
     ExecJS::ProgramError at /some_dir/
                    TypeError: require is not a function
```
What should be the correct way to use in rails.

**Comment by mukarramali** [comment]
@eddywashere @TheSharpieOne guys can you suggest ways to do this in rails. I am using sprockets for assets precompile.

**Comment by TheSharpieOne** [comment]
No clue. This is a javascript library which usually runs natively on the browser. I am not familiar with Ruby on Rails enough to even be aware that it can run javascript on the server. There is server-side rendering, but that very different and if that is what you are trying to do, I would open an issue with the tool you are using to render react on the server.

**Comment by virgofx** [comment]
Just a note: Reactstrap is supported and works for server-side-rendering (SSR). Like @TheSharpieOne  said you'll need to configure your environment appropriately. Some other libraries have numerous issues with globals that conflict at runtime ... none here (as of 5.0.0)  Reactstrap will work provided your environment is configured correctly.

**Comment by mukarramali** [comment]
I switched to using `webpacker`. It solves my case. Thanks guys!
