### ISSUE TITLE
Carousel not autosliding

### ISSUE THREAD

**Issue by borisyordanov** [reactstrap/reactstrap#930]
### Issue description

- components: `Carousel `
- reactstrap version `5.0.0-beta
- react version `16.1.1`
- bootstrap version `4.0.0

### What is happening?

[This is the homepage](https://enjoy-copenhagen-dev.herokuapp.com/en) of the app i'm working on. The carousel does not start sliding until you click the carousel controls. When you click them the slides transition very quickly.

### Steps to reproduce issue

1. I'm using pretty much the same implementation as the example in the documentation

### Code

```
const slides = items.map((item, index) => (
  <CarouselItem
    onExiting={this.onExiting}
    onExited={this.onExited}
    key={`carousel-item${index}`}
    src={`assets/carousel-images/${item.url}.jpg`}
    altText={item.description}
    className="item img-fluid"
  >
    <img
      src={`assets/carousel-images/${item.url}.jpg`}
      alt="Enjoy Copenhagen carousel item"
    />
    <CarouselCaption
      captionHeader={text}
      captionText={''}
      className="carousel-inner-text"
    />
  </CarouselItem>
));

return (
  <Carousel
    activeIndex={activeIndex}
    next={this.next}
    previous={this.previous}
    className="carousel-container"
  >
    {slides}
    <CarouselControl
      direction="prev"
      directionText="Previous"
      onClickHandler={this.previous}
    />
    <CarouselControl
      direction="next"
      directionText="Next"
      onClickHandler={this.next}
    />
  </Carousel>
);

```

**Comment by TheSharpieOne** [comment]
In the Carousel Docs: https://reactstrap.github.io/components/carousel/
The props have
> // Autoplays the carousel after the user manually cycles the first item. If "carousel", autoplays the carousel on load.
  // This is how bootstrap defines it... I would prefer a bool named autoplay or something...
  ride: PropTypes.oneOf(['carousel']),

So basically, you would have to set the prop `ride="carousel"` to have it autoside

**Comment by borisyordanov** [comment]
Yes, you're right - that fixed it. However i could have sworn it used to autoslide without the `ride="carousel` prop added to it. I was confused it stopped, which i why i made this issue. I can't however recreate the conditions it used to slide in.

@TheSharpieOne thank you for your help
