### ISSUE TITLE
Modal. Focus input element and allow ESC and backdrop dismissal

### ISSUE THREAD

**Issue by Xerillio** [reactstrap/reactstrap#931]
- components: `Modal`
- reactstrap version `5.0.0`
- react version `16.0.0`
- bootstrap version `4.0.0`

I'm having trouble connecting the dots between other issues and the documentation. I'm trying to have the modal focus the first `Input` element when shown and also allow clicking the backdrop or the 'ESC' button to dismiss the modal.

Though a bit counter-intuitive to me, I read in #392 that I need to disable `autoFocus` on the modal for it to work on the input element. So focusing the `Input` element when showing the modal works just fine with that. However, how do I enable dismissing the modal by pressing either 'ESC' or the backdrop? Setting `keyboard={true}` on the `Modal` doesn't seem to work, which as far as I understand is also the default.

Let me know if you need a code example.

**Comment by TheSharpieOne** [comment]
Dismissing the modal by both pressing either 'ESC' and/or clicking the backdrop is enabled by default and works with the autoFocus management.
This example works for me: https://stackblitz.com/edit/reactstrap-v5-kyqx4o?file=Example.js

**Comment by Xerillio** [comment]
Ah I see my mistake now. I wasn't aware that setting the `toggle` prop enabled that feature. Thanks

**Comment by Torvin** [comment]
I was pulling my hair out for a couple of hours trying to figure out why `<input autoFocus />` doesn't work inside modal. Turns out you're supposed to put `autoFocus={false}` on the `<Modal>` itself. Should be documented probably.

**Comment by uuykay** [comment]
Thanks for this insight, I also ran into this problem.

> Ah I see my mistake now. I wasn't aware that setting the `toggle` prop enabled that feature. Thanks
