### ISSUE TITLE
Question: Dynamically set the `ride` prop of a Carousel

### ISSUE THREAD

**Issue by aensley** [reactstrap/reactstrap#935]
### Issue description

- components: `Carousel`
- reactstrap version `#5.0.0`
- import method `es6`
- react version `#16.1.1`
- bootstrap version `#4.0.0`

### What is happening?

When I try to "play" or "stop" a carousel by changing the `ride` prop, only the "play" value of `carousel` is honored. It never stops.

### What should be happening?

I'd like to be able to set `ride` dynamically to either play or stop the carousel based on events in my app.

### Steps to reproduce issue

I started with a blank React ES6 app, added only the [the carousel example in your docs](https://reactstrap.github.io/components/carousel/), and then added buttons to change the `playing` state, to which the `<Carousel/>`'s `ride` prop is bound.

1. Open app.
2. Note carousel is not playing.
3. Click **Play**.
4. Carousel plays.
5. Click **Stop**.
6. Carousel continues to play.

### Error message in console

```
Warning: Failed prop type: Invalid prop `ride` of value `` supplied to `Carousel`, expected one of ["carousel"].
in Carousel (created by Example)
in Example
```

I have tried changing the `ride` prop to an empty string, boolean `false`, or simply a different string other than 'carousel' (like `'tomato'`), but every attempt yields the same warning and behavior. The only "false" value that doesn't log a warning is `null`, but the Carousel still continues to play.

### Code

https://stackblitz.com/edit/carousel-ride?file=index.js

----

Is there a way to do this? Alternatively, is there a way to dynamically recreate the entire Carousel without the ride prop at all? I'm a React newbie, so I apologize if this is a dumb question.

**Comment by TheSharpieOne** [comment]
We try to match bootstrap as much as possible and in the case of carousel the way bootstrap does it doesn't seem to be intuitive.

`ride` is defined as
> Autoplays the carousel after the user manually cycles the first item. If "carousel", autoplays the carousel on load.

`pause` (which one might thing would pause the carousel if set to `true` (but it doesn't)) is defined as
>If set to "hover", pauses the cycling of the carousel on mouseenter and resumes the cycling of the carousel on mouseleave. If set to false, hovering over the carousel won't pause it.

The one which you are looking for is probably `interval`
>The amount of time to delay between automatically cycling an item. If false, carousel will not automatically cycle.

Demo: https://stackblitz.com/edit/carousel-ride-qfnsu8?file=index.js

I know it is not clearly documented in reactstrap's docs as we usually require users to know / be familiar with bootstrap and bootstrap's properties, but for carousel I think an exception is needed.

**Comment by aensley** [comment]
@TheSharpieOne That makes sense, and is exactly what I needed. Again. Thank you!
