### ISSUE TITLE
Docs - Search 

### ISSUE THREAD

**Issue by gergely-nagy** [reactstrap/reactstrap#942]
We should support search feature in the documentation. [React ](https://reactjs.org/) and [Bootstrap ](https://getbootstrap.com/docs/4.0/getting-started/introduction/) docs is using [Algolia ](https://community.algolia.com/docsearch/) for search. If the the owner of the site request a key from algolia, I can work on this.

**Comment by TheSharpieOne** [comment]
I sent a request
> We'll review your request shortly, after making sure your website is eligible to DocSearch.
This is a manual process and can take some time.
We'll then email you the code you need to integrate on your website

**Comment by TheSharpieOne** [comment]
> If you add id attribute to your "lvlX" elements, we could get the anchor and thus scroll down to the right position thanks to the URL.
>
> Your .nav-link "Utilities" element redirect to a "404 Page Not Found" page contrary to "Components", it will not be crawled. It will not be scraped either since the .docSearch-content class is missing.
>
> Please PR your config once you have made these changes, I will help you fine tuning your DocSearch implementation.
>
> In the meanwhile, congratulations, your search is now ready! 
>
> I've successfully configured the underlying crawler and it will now run every 24h. 
>
> You're now a few steps away from having it working on your website: 
>
> - Copy the following CSS/JS snippets and add them to your page 
```html
<!-- at the end of the HEAD --> 
<link rel="stylesheet", href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" /> 

<!-- at the end of the BODY --> 
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script> 
<script type="text/javascript">  docsearch({ 
 apiKey: '2999e8cb716a50f4bd09a3addb18bf4f', 
 indexName: 'reactstrap', 
 inputSelector: '### REPLACE ME ####', 
 debug: false // Set debug to true if you want to inspect the dropdown 
}); 
</script>
```
>
> - Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field. 
>
> - Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/) 
> - You can also check your configuration in our github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/reactstrap.json). 
>
> Please open a pull request if want to leverage your configuration! 
>
> Feel free to get back to us if you have any issues or questions regarding the integration. 
>
> We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it. 
>
> Have a nice day :)

**Comment by TheSharpieOne** [comment]
The "Utilities" element redirect to a "404 Page Not Found" is only when opening the link directly (which is what a bot crawling the site would do). The 404 page ends up loading the app which then navigates, but it is acting differently than what `/components/` does (which apparently works for the bot crawling the site).

**Comment by TheSharpieOne** [comment]
I think we may need to do something to allow it to better deeplink into sections of a component. The links are there, but it seems to always go to `#app`. We may need to see about ending [the config](https://github.com/algolia/docsearch-configs/blob/master/configs/reactstrap.json).

**Comment by TheSharpieOne** [comment]
Completed via f8f5fe5, 3a09c85, and e18735f.
