### ISSUE TITLE
Dropdown does not work

### ISSUE THREAD

**Issue by izmn** [reactstrap/reactstrap#944]
### Issue description

- components: `Dropdown`
- reactstrap version: `5.0.0`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `v16.1.1`
- bootstrap version `v4.0.0`

### What is happening?

Throws error

### What should be happening?

Open dropdown

### Steps to reproduce issue

1. click on DropdownToggle

### Error message in console

```
Error in /turbo_modules/reactstrap@5.0.0/dist/reactstrap.cjs.js (1408:20)
this.context.toggle is not a function
```

### Code
```jsx
import React, { Component } from 'react';
import { Dropdown, DropdownMenu, DropdownToggle, DropdownItem } from 'reactstrap';

class Example extends Component {
  render() {
    return (
      <Dropdown>
        <DropdownToggle caret>
          Dropdown
        </DropdownToggle>
        <DropdownMenu>
          <DropdownItem header>Header</DropdownItem>
          <DropdownItem disabled>Action</DropdownItem>
          <DropdownItem>Another Action</DropdownItem>
          <DropdownItem divider />
          <DropdownItem>Another Action</DropdownItem>
        </DropdownMenu>
      </Dropdown>
    )
  }
}

export default Example;
```

### Example at stackblitz
https://stackblitz.com/edit/reactstrap-v5-beta-starter-x1jxrf?file=Example.js

**Comment by gergely-nagy** [comment]
Hey there @izmn !
The `Dropdown `component is used to pass the `isOpen `& `toggle `props via context to the following components. You must specify these properties.

**Example `Dropdown`:**
https://stackblitz.com/edit/reactstrap-v5-beta-starter-blshka?file=Example.js

Or for the most basic use-case an uncontrolled component can provide the functionality wanted without the need to manage/control the state of the component. `UncontrolledDropdown `does not require `isOpen `nor `toggle `props to work. 

**Example `UncontrolledDropdown `:**
[https://stackblitz.com/edit/reactstrap-v5-beta-starter-aso2rv?file=Example.js](https://stackblitz.com/edit/reactstrap-v5-beta-starter-aso2rv?file=Example.js)

**Comment by izmn** [comment]
Thank you @gergely-nagy !

**Comment by CarlosReing** [comment]
Thank you @gergely-nagy !

**Comment by roberto-rodriguez** [comment]
I get error in this line in the DropdownToggle.js
 
  **this.context.toggle(e);**

It says context doesnt have toogle function.. )-:
