### ISSUE TITLE
Collapse: Warning Failed context type: Minified exception occurred;

### ISSUE THREAD

**Issue by dkati** [reactstrap/reactstrap#945]
i am using the default example from here -> https://reactstrap.github.io/components/collapse/

and i get that warning ->

`Warning: Failed context type: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings. in e (created by t) in t (created by OverviewTab) in div (created by OverviewTab) in OverviewTab (created by LaborersTabs) in div (created by Pe) in Pe (created by LaborersTabs) in div (created by ke) in ke (created by LaborersTabs) in div (created by _) in _ (created by LaborersTabs) in div (created by t) in t (created by LaborersTabs) in div (created by LaborersTabs) in LaborersTabs`

i am using reactstrap via cdn links

**Comment by GoPro16** [comment]
Closing this issue, feel free to re-open if you are still running into issues.
