### ISSUE TITLE
What "inNavbar" means?

### ISSUE THREAD

**Issue by johnunclesam** [reactstrap/reactstrap#955]
In this page I see this:

`<UncontrolledDropdown inNavbar nav>`

What "`inNavbar`" means?

**Comment by TheSharpieOne** [comment]
that the `UncontrolledDropdown` component is in the `Navbar` component (as it acts slightly differently when that happens)

**Comment by johnunclesam** [comment]
And how it acts? There is a guide? A doc? A wiki?

**Comment by TheSharpieOne** [comment]
getbootstrap.com

**Comment by TheSharpieOne** [comment]
I'm closing this since the the question was answered above. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Comment by allicanseenow** [comment]
Can we officially add this directly to the documentation? It is not a good idea when I actually have to reach this page to find the definition of a props that should be displayed in the documentation page.
