### ISSUE TITLE
total newb with this

### ISSUE THREAD

**Issue by binartech** [reactstrap/reactstrap#958]
### Issue description

Simply trying to load from my own version of App Navbar the Alerts code.
It simply does nothing.
This works:
`<NavLink href="https://github.com/reactstrap/reactstrap">GitHub</NavLink>`
but this `<NavLink href="Alr" >Alarms</NavLink>` isn't doing anything.
I know I'm missing something but can't find any code which shows how the NavLink
refers to the code in the Alr.js file:
```jsx
import React from 'react';
import { Alert } from 'reactstrap';

export const myAlr = (props) =>{
  return (
    <div>
      <Alert color="primary">
        This is a primary alert — check it out!
```

How the NavLink renders the Als.js ?
If I don't use the href=......  than the NavLink doesn't allow to select the option on the nav bar.
tried to=..... tag......
Nothing works for me. 
Thanks for your help 

- components: `name`
- reactstrap version `#x.x.x`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `#x.x.x`
- bootstrap version `#x.x.x`

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by GoPro16** [comment]
Closing this issue, feel free to re-open if you are still running into issues.
