### ISSUE TITLE
Question , col support for justify-content-end

### ISSUE THREAD

**Issue by ThomasJT** [reactstrap/reactstrap#961]
Hello

Am I right in that there is no support at the moment for justify-content-end:

```
<Col xs="4" className="justify-content-end">
          Some blabb Some blabb Some blabb Some blabb Some blabb Some blabb Some
          blabb Some blabb Some blabb
</Col>
```
(edit: for now I will use offset instead)
Thanks in advance

**Comment by TheSharpieOne** [comment]
Correct, per #81, using `className` is the only way to do it (there is no nice prop-based way).
