### ISSUE TITLE
Right aligned dropdowns have wrong width on Bootstrap 4.1

### ISSUE THREAD

**Issue by cauethenorio** [reactstrap/reactstrap#962]
Since version 4.1, bootstrap added some CSS rules which relies on `x-position` attribute added by `popper.js` to properly size the dropdown menu node:

https://github.com/twbs/bootstrap/pull/25400
https://github.com/twbs/bootstrap/pull/25400/files#diff-17c7180c6905243675dbb731bacf389aR90

But since version 0.8.1, `react-popper` doesn't set the `x-position` attribute on the menu node:

https://github.com/FezVrasta/react-popper/commit/4338327916e05888a7cfc371eeda80023edcfbfc

So when using right-aligned dropdown menus with reactstrap the menu node is set with `left:0` and `right:0` resulting in a wrong width, since there's no `x-position` to add the `right: auto` rule.

The error can be reproduced on the right aligned dropdown reactstrap doc page if you add a dropdown item with a longer content:

![image](https://user-images.githubusercontent.com/496987/38892453-a2a74c1c-425d-11e8-98a1-13a25876dba3.png)

Not sure how it can be fixed. Maybe updating reactstrap to add the `x-position` manually?

**Comment by TheSharpieOne** [comment]
We'll have to fix this in reactstrap as the next version of react-popper (currently in beta) changes drastically and we would have to apply that attribute in that version.
