### ISSUE TITLE
Dropdown button with direction up not working?

### ISSUE THREAD

**Issue by iamglenbacs** [reactstrap/reactstrap#967]
- components: `dropdown`
- reactstrap version `latest`
- react version `latest
- bootstrap version `4`

### What is happening?

reactstrap on dropdown direction variations button with direction up not working, it's at  https://reactstrap.github.io/components/button-dropdown/:
![1](https://user-images.githubusercontent.com/17801912/38958309-758a4d14-438f-11e8-9db5-cc2597026996.png)

**Comment by TheSharpieOne** [comment]
Docs look good now
