### ISSUE TITLE
still missing prop type object innerRef in latest version

### ISSUE THREAD

**Issue by tngmichael** [reactstrap/reactstrap#980]
### Issue description

I saw this commit https://github.com/reactstrap/reactstrap/commit/a5795b8bd1815a12660f39928e8c7d2b0ac8c45a but still not updated in reactstrap installed

- reactstrap version `#5.0.0`

**Comment by virgofx** [comment]
InnerRef has been fixed in master and will be available in the next release. /close

**Comment by tngmichael** [comment]
Thank you for info, will wait till next release

**Comment by TheSharpieOne** [comment]
We are currently waiting for an upstream issue to be addressed before we can cut a new release.
