### ISSUE TITLE
Dropup breaks with Bootstrap 4.1.0

### ISSUE THREAD

**Issue by FelixHenninger** [reactstrap/reactstrap#987]
**Thanks a lot for all of your effort with Reactstrap!** I 🧡 your library, and it's been a massive help in several projects. I recently encountered an issue after updating Bootstrap, and I thought I'd let you know -- I'm not sure if you support 4.1.0 at present; please feel free to close/defer this issue. Bootstrap hasn't changed the `CSS` classes, so I'm guessing this is a popper issue. 

I haven't spotted any other problems with the Bootstrap update, at least in my apps (i.e. Dropdowns continue to work perfectly).

----

### Issue description

- components: `Dropdown` / `UncontrolledDropdown`
- reactstrap version `#5.0.0`
- import method `es`
- react version `#16`
- bootstrap version `#4.1.0`

### What is happening?

`<Dropdown direction="up">` components are not displayed correctly *(only) after switching to Bootstrap 4.1.0*:

![dropup 4.1.0](https://user-images.githubusercontent.com/8349942/39408541-37d5ec16-4bd8-11e8-9128-7ee363247a57.png)

### What should be happening?

![dropup 4.0.0](https://user-images.githubusercontent.com/8349942/39408556-831f4dac-4bd8-11e8-9ca3-192f655c4304.png)

### Steps to reproduce issue

1. Enjoy building react applications with reactstrap, loving life, just going about your business
2. Upgrade to Bootstrap `#4.1.0`

### Error message in console

```
- None -
```

### Code

[Codepen with Bootstrap 4.1.0](https://codepen.io/anon/pen/KRaoNQ?editors=1111)

**Comment by TheSharpieOne** [comment]
Fixed in #966, waiting on upstream fix to be released before releasing.

**Comment by FelixHenninger** [comment]
Oh, fantastic, I didn't see that. Thanks soooo much, I really appreciate the effort you put into this, and sorry for the trouble!
