### ISSUE TITLE
Is it using jQuery and popper?

### ISSUE THREAD

**Issue by alamchrstn** [reactstrap/reactstrap#988]
is the library using jQuery and popper? So it's something only like a wrapper components?

**Comment by TheSharpieOne** [comment]
Nope, this library doesn't use jquery, it's all react. It uses popper.js via reac-popper which does wrap popper, but popper.js doesn't use jquery either.
Using reactstrap means you don't need bootstrap.js nor jquery.

**Comment by alamchrstn** [comment]
ah ok awesome! thanks man @TheSharpieOne
