### ISSUE TITLE
Feature request - add properties to the modal-header component to allow customization of the the header content.

### ISSUE THREAD

**Issue by ed-polly** [reactstrap/reactstrap#990]
### Issue description

- components: `modal-header`
- reactstrap version `#5.0.0-beta`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `#16.0.35`
- bootstrap version `#4.0.0-alpha.6`

### Feature request

Add properties to the modal-header component to allow customization of the the header content including the title and close button. For example: add a link button to the modal-header that is horizontally aligned to one side.

### Code
sample JSX code
```jsx
<WrapTag {...attributes} className={classes}>
      {preTitle}
      <Tag className={mapToCssModules('modal-title', cssModule)}>
        {children}
      </Tag>
      {postTitle}
      {closeButton}
</WrapTag>
```

sample HTML output
```html
<div class="modal-header">
  <span class="justify-content-start">stage left</span>
  <h5 class="modal-title">The Title</h5>
  <span class="justify-content-end">stage right</span>
  <button type="button" class="close" aria-label="Close">
    <span aria-hidden="true" class="icon-close-icon">χ</span>
  </button>
</div> 
```

**Comment by GoPro16** [comment]
closed via #1168
