### ISSUE TITLE
prop-types in some component

### ISSUE THREAD

**Issue by benitocas88** [reactstrap/reactstrap#993]
![screenshot from 2018-05-01 19-55-22](https://user-images.githubusercontent.com/2643684/39500466-3f5de512-4d7a-11e8-9dfb-37e587520e1b.png)

### Issue description

- components: `not sure`
- reactstrap version `6`
- import method `umd/csj/es` (if umd, are you using the "full" version (only for v5+)?)
- react version `16.3.2`
- bootstrap version `
![screenshot from 2018-05-01 19-55-22](https://user-images.githubusercontent.com/2643684/39500455-29298f58-4d7a-11e8-9160-65bea0b28a4a.png)
4`

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by TheSharpieOne** [comment]
Thanks for reporting; fixed in 6.0.1
