### ISSUE TITLE
Tooltip offset?

### ISSUE THREAD

**Issue by alamchrstn** [reactstrap/reactstrap#995]
Is there any way to set the offset of a tooltip? something like the one in the official bootstrap tooltip.
Thanks in advance 💃

**Comment by illiteratewriter** [comment]
You can set the offset of a tooltip by passing `offset`  as the property of `modifier`, which in turn can be passed as a `prop` to `Tooltip`.  For example 
```jsx
<Tooltip placement="right" isOpen={this.state.tooltipOpen} target="TooltipExample" toggle={this.toggle} modifiers={{offset:{offset: '-200px', enabled: true}}}>
  Hello world!
</Tooltip>
```

**Comment by gergely-nagy** [comment]
@illiteratewriter 
Yes. That's the way to do it right now! ([Demo](https://stackblitz.com/edit/reactstrap-995?file=Example.js))
But we should add `offset` prop to `Tooltip` and `Popover` components for ease of use.

**Comment by illiteratewriter** [comment]
Can I give it a shot?

**Comment by gergely-nagy** [comment]
@illiteratewriter go for it.
@TheSharpieOne Any thoughts?

**Comment by illiteratewriter** [comment]
What should be done if someone passes the `offset` prop and also his/her modifiers also contain `offset`?

**Comment by illiteratewriter** [comment]
`offset` object should be passed or just the value of `offset` inside the offset object needs to be passed as `prop`?

**Comment by gergely-nagy** [comment]
We should pass just the value of offset.

`offset` prop should be like:

```javascript
PropTypes.oneOfType([
  PropTypes.number,
  PropTypes.string
]),
```
Valid examples are:

```javascript
10
'10%'
'10, 10'
'10%, 10'
'10 + 10%'
'10 - 5vh + 3%'
'-10px + 5vh, 5px - 6%'
```

**Comment by gergely-nagy** [comment]
Completed via 3561e3c.
